Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2019-09, with the labels that each got.

#1470 Messy Space Chatter Rewrite
  code/modules/busy_space/air_traffic.dm
  code/modules/busy_space/organizations.dm
  code/modules/busy_space_vr/organizations.dm
  code/modules/lore_codex/lore_data/orgs.dm
  code/modules/lore_codex/lore_data_vr/orgs.dm
  vorestation.dme
Labels: Test Merge Candidate

#1525 Adds Cable Coils to Autolathe
  code/datums/autolathe/tools.dm
Labels: Feature

#1528 did you guys know that phoronguard was supposed to be a flag and not an item_flag? i didn't
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/clothing/spacesuits/rig/rig_pieces.dm
  code/modules/clothing/spacesuits/rig/suits/alien.dm
  code/modules/clothing/spacesuits/spacesuits.dm
  code/modules/clothing/suits/bio.dm
Labels: Code Improvement, Tweak

#1530 Advanced Mining Scanners & Ore Doesn't Delete On Explosion
  code/modules/mining/drilling/scanner.dm
  code/modules/mining/ore.dm
  code/modules/mining/ore_redemption_machine/equipment_vendor.dm
  code/modules/research/designs/mining_toys.dm
  icons/obj/device.dmi
Labels: Feature, Sprites

#1527 Fixes the chirp emote for human mobs
  code/modules/mob/living/carbon/human/emote_vr.dm
Labels: Fix

#1532 Because Boop Doesn't Do This
  code/modules/mob/living/silicon/robot/robot_modules/station_vr.dm
Labels: Feature

#1536 Adds new moth wing types to the wing selection
  code/modules/vore/appearance/sprite_accessories_vr.dm
  icons/mob/vore/wings_vr.dmi
Labels: Code Improvement, Feature, Sprites

#1534 map fix that probably doesn't work (temporarily switches back tgm to dmm on tether runtime loaded levels)
  maps/tether/submaps/aerostat/aerostat.dmm
  maps/tether/submaps/aerostat/surface.dmm
  maps/tether/submaps/alienship/alienship.dmm
  maps/tether/submaps/beach/beach.dmm
  maps/tether/submaps/beach/cave.dmm
  maps/tether/submaps/tether_misc.dmm
  maps/tether/submaps/tether_ships.dmm
  maps/tether/submaps/tether_underdark.dmm
Labels: FUCK

#1541 Fixes Cables in Lathe
  code/datums/autolathe/tools.dm
Labels: Fix

#1543 QoL Updates to the text boxes for talking & emotes
  code/game/mecha/mecha.dm
  code/modules/mob/say.dm
  code/modules/mob/say_vr.dm
  code/modules/mob/typing_indicator.dm
Labels: Tweak

#1539 Makes Phoron scrubbers stronger
  maps/tether/tether_phoronlock.dm
Labels: Tweak
