Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2019-12, with the labels that each got.

#1618 Medbay Area Fix
  maps/tether/tether-07-station3.dmm
Labels: Fix

#1617 Removes the "has this user been here before" check from bans
  code/modules/admin/DB ban/functions.dm
Labels: Removal

#1613 More GPS Units
  code/game/objects/items/devices/gps.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/crates_lockers/closets/secure/security_vr.dm
  code/modules/mining/shelter_atoms.dm
  icons/obj/gps.dmi
  maps/southern_cross/structures/closets/misc.dm
Labels: Feature, Fix, Sprites

#1610 Spacebike buff
  code/datums/supplypacks/robotics.dm
  code/modules/vehicles/bike.dm
Labels: Balance/Rebalance, Tweak

#1619 Adds a Tracking Implant Crate
  code/datums/supplypacks/security_vr.dm
Labels: Feature

#1620 adds a new lounge to station level 1
  code/game/area/Space Station 13 areas.dm
  maps/tether/tether-05-station1.dmm
Labels: Feature

#1601 Excursion Shuttle: V3b Surface
  maps/tether/submaps/tether_ships.dmm
  maps/tether/tether-03-surface3.dmm
  maps/tether/tether_areas2.dm
  maps/tether/tether_shuttles.dm
Labels: Feature

#1624 Brighter tox damage on Crew Monitor
  nano/css/shared.css
Labels: Tweak

#1623 Remove small_cruiser & associated shuttle elements
  maps/tether/submaps/tether_ships.dmm
  maps/tether/tether-05-station1.dmm
  maps/tether/tether_shuttle_defs.dm
  maps/tether/tether_shuttles.dm
Labels: Fix, Removal
