Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2019-11, with the labels that each got.

#1591 [RP Server] Bar rebuild (3rd times a charm)
  maps/tether/tether-03-surface3.dmm
Labels: Feature

#1592 SpaceTalk Expansion Pack 1
  code/modules/busy_space/air_traffic.dm
  code/modules/busy_space/organizations.dm
Labels: Feature, Removal, Tweak

#1593 Map Merge Test
  maps/tether/tether-03-surface3.dmm
Labels: Removal

#1597 Small tweaks/fixes for the RPD.
  code/game/machinery/pipe/pipe_recipes.dm
  code/game/objects/items/weapons/RPD.dm
Labels: Tweak

#1598 [Antag balance] Removes Binary keys from R&D
  code/modules/research/designs/illegal.dm
Labels: Balance/Rebalance, Removal

#1605 Resprites doorbell sprites and changes the sound.
  code/game/machinery/doorbell_vr.dm
  icons/obj/machines/doorbell_vr.dmi
Labels: Sprites, Tweak

#1608 fixes first day joins being unable to join any jobs
  code/modules/client/client_procs.dm
Labels: Priority: High

#1607 Porting sleeper and charger upgrades!
  code/game/machinery/Sleeper.dm
  code/game/objects/items/weapons/circuitboards/frame.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
  nano/templates/sleeper.tmpl
Labels: Feature

#1606 bodybags - density + pressure, cell chargers suck a lil less dick
  code/game/machinery/cell_charger.dm
  code/game/machinery/frame.dm
  code/game/machinery/recharger.dm
  code/game/objects/items/bodybag.dm
  code/game/objects/items/weapons/circuitboards/frame.dm
  code/game/objects/items/weapons/stunbaton.dm
  code/game/objects/items/weapons/tanks/tank_types.dm
  code/game/objects/items/weapons/tanks/tanks.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/modules/xenobio/items/weapons.dm
Labels: Fix

#1612 Bar Fixes
  maps/tether/tether-03-surface3.dmm
Labels: Fix
