Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2019-10, with the labels that each got.

#1547 medihounds get beakers but not standard medborgs? hmm
  code/modules/mob/living/silicon/robot/robot_modules/station_vr.dm
Labels: Feature

#1552 Digging Fiddling
  code/__HELPERS/unsorted.dm
  code/datums/supplypacks/supply.dm
  code/game/objects/effects/overlays.dm
  code/game/objects/structures/crates_lockers/closets/coffin.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/game/objects/structures/flora/trees.dm
  code/game/turfs/simulated/floor_attackby.dm
  code/game/turfs/simulated/outdoors/snow.dm
  code/modules/clothing/spacesuits/void/station.dm
  code/modules/mining/mine_items.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mob/living/silicon/robot/robot_modules/event.dm
  code/modules/xenoarcheaology/artifacts/replicator.dm
  maps/RandomZLevels/labyrinth.dmm
  maps/RandomZLevels/snowfield.dmm
  maps/RandomZLevels/stationCollision.dmm
  maps/cit_tether/tether-01-surface1.dmm
  maps/endeavor/endeavor-01-ship1.dmm
  maps/endeavor/endeavor-03-ship3.dmm
  maps/endeavor/submaps/odin5a-desert/odin5a-cave.dmm
  maps/northern_star/polaris-1.dmm
  maps/northern_star/polaris-5.dmm
  maps/southern_cross/southern_cross-1.dmm
  maps/southern_cross/southern_cross-3.dmm
  maps/submaps/surface_submaps/mountains/backup/cultmine.dmm
  maps/submaps/surface_submaps/mountains/cultmine.dmm
  maps/submaps/surface_submaps/mountains/digsite.dmm
  maps/submaps/surface_submaps/mountains/quarantineshuttle.dmm
  maps/submaps/surface_submaps/plains/construction1.dmm
  maps/submaps/surface_submaps/wilderness/Manor1.dmm
  maps/submaps/surface_submaps/wilderness/Rocky2.dmm
  maps/tether/tether-01-surface1.dmm
  maps/virgo/virgo-1.dmm
  maps/virgo/virgo-5.dmm
Labels: Code Improvement, Feature

#1551 Science Crew Uniforms + Explorer Uniform Markings
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/clothing/under/solgov.dm
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/mob/uniform_rolled_down.dmi
  icons/mob/uniform_sleeves_rolled.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Feature, Sprites, Tweak

#1550 Sandstone Plant Plots
  code/modules/materials/material_recipes.dm
Labels: Fix

#1553 Miners With Magboots + Toggle Magboots
  code/modules/clothing/spacesuits/void/void.dm
  maps/tether/tether-01-surface1.dmm
Labels: Feature, Tweak

#1554 Fulton Fixes - objects and stuntimes
  code/modules/mining/fulton.dm
Labels: Tweak

#1559 Revert "that one thing about the ore boxes and not exploding"
  code/modules/mining/satchel_ore_boxdm.dm
Labels: Revert

#1557 [READY] Ore Scanner Range Toggle (Altclick) + Ore Boxes No Longer Explode
  code/game/objects/structures/transit_tubes.dm
  code/modules/mining/drilling/scanner.dm
  code/modules/mining/satchel_ore_boxdm.dm
Labels: Do Not Merge, Feature, Needs Review, Tweak

#1555 Welding Tools Now Set Flammable People On Fire (on non-help intents)
  code/game/objects/items/weapons/tools/weldingtool.dm
Labels: Fix

#1561 YASHCT - Demodularization, Engineering Stuff, More Stupid Plate Carrier Stuff, DIY Toxin Gathering
  code/datums/supplypacks/contraband_vr.dm
  code/datums/supplypacks/costumes_vr.dm
  code/datums/supplypacks/engineering.dm
  code/datums/supplypacks/hydroponics.dm
  code/datums/supplypacks/misc_vr.dm
  code/datums/supplypacks/security_vr.dm
  code/game/objects/random/mob.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/modules/clothing/under/accessories/armor.dm
  code/modules/mining/drilling/scanner.dm
  code/modules/mob/living/simple_animal/animals/carp.dm
  code/modules/mob/living/simple_animal/vore/carp.dm
  modular_citadel/code/datums/supplypacks/contraband_cit.dm
  modular_citadel/code/datums/supplypacks/costumes_cit.dm
  modular_citadel/code/datums/supplypacks/misc.dm
  modular_citadel/code/datums/supplypacks/security.dm
  vorestation.dme
Labels: Balance/Rebalance, Code Improvement, Feature, Tweak

#1560 Hardy No Longer Suffers With Negative Slowdown
  code/modules/mob/living/carbon/human/human_movement.dm
Labels: Tweak

#1567 why the fuck do fuzzycuffs act as standards
  code/game/objects/items/weapons/handcuffs.dm
  code/game/objects/items/weapons/handcuffs_vr.dm
Labels: Tweak

#1568 Submap Generation Respects Config
  code/game/world.dm
Labels: Code Improvement

#1571 [SPEEDMERGE] Revert "Submap Generation Respects Config"
  code/game/world.dm
Labels: Revert

#1572 Ports (with some modification) CitMain's borg petting
  code/modules/mob/living/silicon/robot/robot.dm
  sound/effects/clang1.ogg
Labels: Feature, Sound, Tweak

#1564 Small tweak to the default tesla engine layout (Input requested!)
  maps/submaps/engine_submaps/engine_tesla.dmm
Labels: Tweak

#1569 Atmospherics Overhaul (Maybe) Part 1 - The RPD
  code/ATMOSPHERICS/components/tvalve.dm
  code/ATMOSPHERICS/components/unary/outlet_injector.dm
  code/ATMOSPHERICS/components/valve.dm
  code/__defines/construction.dm
  code/datums/autolathe/engineering.dm
  code/game/machinery/pipe/pipe_dispenser.dm
  code/game/machinery/pipe/pipe_recipes.dm
  code/game/objects/items/weapons/RPD.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/modules/mob/living/silicon/robot/robot_modules/station.dm
  code/modules/mob/living/silicon/robot/robot_modules/station_vr.dm
  code/modules/recycling/disposal-construction.dm
  icons/obj/tools.dmi
  maps/tether/tether-01-surface1.dmm
  maps/tether/tether-06-station2.dmm
  vorestation.dme
Labels: Feature, Sprites, Tweak

#1577 BYOND 513
  code/__DEFINES/__513_compatibility.dm
  code/__DEFINES/is_helpers.dm
  code/__HELPERS/lists/associations.dm
  code/__HELPERS/unsorted.dm
  code/__defines/math.dm
  code/modules/client/client_procs.dm
  code/modules/organs/organ_external.dm
  code/modules/surgery/generic.dm
  interface/skin.dmf
  interface/stylesheet.dm
  vorestation.dme
Labels: Code Improvement, FUCK

#1570 SHARPENING KITS (but also a new combat knife sprite yoinked from /tg/station)
  code/game/objects/items/weapons/material/knives.dm
  code/game/objects/items/weapons/material/material_weapons.dm
  code/game/objects/items/weapons/material/whetstone.dm
  icons/obj/kitchen.dmi
Labels: Feature, Sprites

#1563 Shortening xenochimera reconstitute form timers and deleting cooldown + extra
  code/modules/mob/living/carbon/human/species/station/station_special_abilities_vr.dm
  code/modules/mob/living/carbon/human/species/station/station_special_vr.dm
Labels: Balance/Rebalance, Code Improvement, Feature

#1581 adds tasercoolers for k9
  code/modules/mob/living/silicon/robot/robot_modules/station_vr.dm
Labels: Fix

#1582 lol what the fuck is momo
  code/modules/food/food/snacks.dm
Labels: Fix

#1584 makes foam weapons work, i guess
  code/game/objects/items/weapons/material/foam.dm
Labels: Fix, PRB: Reset

#1586 Seriously? Adds code to handle sleepers being destroyed
  code/game/machinery/Sleeper.dm
Labels: Fix

#1585 Fixes a camera name
  code/game/objects/items/devices/tvcamera.dm
Labels: Fix
