Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2020-02, with the labels that each got.

#1671 Numerous Tweaks to Bar and Hydroponics
  maps/tether/tether-03-surface3.dmm
Labels: Tweak

#1669 Exploration Hangar Rework
  code/game/area/Space Station 13 areas.dm
  code/game/objects/items/weapons/storage/belt.dm
  maps/southern_cross/structures/closets/misc_vr.dm
  maps/tether/tether-05-station1.dmm
  maps/tether/tether-06-station2.dmm
  maps/tether/tether_areas2.dm
Labels: Feature, Removal, Tweak

#1678 Voxxy Clothing Part 1
  icons/mob/species/vox/suit.dmi
  icons/mob/species/vox/uniform.dmi
Labels: Sprites

#1683 Adds Shield Diffusers around most EVA exits
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  maps/submaps/engine_submaps/engine_sme.dmm
  maps/submaps/engine_submaps/engine_tesla.dmm
  maps/tether/tether-01-surface1.dmm
  maps/tether/tether-03-surface3.dmm
  maps/tether/tether-05-station1.dmm
  maps/tether/tether-06-station2.dmm
  maps/tether/tether-07-station3.dmm
Labels: Feature

#1682 Vox Hardsuits Plus Radsuit and Explorer Suit
  code/game/machinery/suit_storage_unit.dm
  code/game/machinery/suit_storage_unit_vr.dm
  code/modules/clothing/spacesuits/void/void_vr.dm
  icons/mob/species/vox/head.dmi
  icons/mob/species/vox/helmet.dmi
  icons/mob/species/vox/suit.dmi
  icons/obj/clothing/species/vox/hats.dmi
  icons/obj/clothing/species/vox/suits.dmi
Labels: Code Improvement, Feature, Sprites

#1685 Orange Tesh Goggles
  code/modules/client/preference_setup/loadout/loadout_xeno.dm
  code/modules/clothing/glasses/glasses.dm
  icons/mob/species/seromi/eyes.dmi
  icons/obj/clothing/glasses.dmi
Labels: Feature, Sprites

#1686 Voxxy Hats
  icons/mob/species/vox/head.dmi
Labels: Feature, Sprites, Tweak

#1690 Unfucks mailing room
  maps/tether/tether-07-station3.dmm
Labels: Fix

#1689 Allows all species to tie their hair
  code/modules/mob/living/carbon/human/species/station/alraune.dm
  code/modules/mob/living/carbon/human/species/station/blank_vr.dm
  code/modules/mob/living/carbon/human/species/station/station_special_vr.dm
  code/modules/mob/living/carbon/human/species/station/station_vr.dm
  code/modules/mob/new_player/sprite_accessories.dm
Labels: Tweak

#1692 No More "Why is the barkeeper outside?" - Nanomaps Updated
  nano/images/nanomap_z1.png
  nano/images/nanomap_z2.png
  nano/images/nanomap_z3.png
  nano/images/nanomap_z4.png
  nano/images/nanomap_z5.png
  nano/images/nanomap_z6.png
  nano/images/nanomap_z7.png
  nano/images/nanomap_z8.png
Labels: Sprites

#1695 Vox 'Hair' and 'Beards'
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
  icons/mob/human_face_m.dmi
  icons/mob/human_face_or_vr.dmi
Labels: Sprites

#1696 Re-Enables Playsound for the Scream Emote
  code/modules/mob/living/carbon/human/emote.dm
Labels: Code Improvement
