Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2020-10, with the labels that each got.

#2394 BL3 P Sprite fix
  code/game/mecha/equipment/tools/medical_tools_vr.dm
Labels: Fix, Sprites

#2378 In High Demand: More Mercenaries
  code/modules/mob/living/simple_mob/subtypes/humanoid/mercs/mercs.dm
  icons/mob/merc.dmi
Labels: Balance/Rebalance, Feature, Fix, Sprites, Tweak

#2390 Handful of Additions (IPC heads, Vox, Protogen marking support)
  code/modules/client/preference_setup/loadout/loadout_xeno.dm
  code/modules/clothing/masks/monitor.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/human_powers.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/hivebot/ranged_damage.dm
  code/modules/mob/new_player/sprite_accessories.dm
  code/modules/organs/robolimbs.dm
  icons/mob/human_races/cyberlimbs/c-tech/c_beast.dmi
  icons/mob/human_races/markings.dmi
  icons/mob/monitor_icons.dmi
  vorestation.dme
Labels: Sprites

#2382 Donator Item - Prop Camera
  code/modules/client/preference_setup/loadout/loadout_donator.dm
  code/modules/vore/fluffstuff/custom_items.dm
  icons/mob/belt.dmi
  icons/vore/custom_items_vr.dmi
  vorestation.dme
Labels: Sprites

#2399 Removes floral somatoray pin requirement
  code/modules/projectiles/guns/energy/special.dm
Labels: Feature, Removal

#2400 Removes firing pin requirement from: Temperature gun and Phase weapons.
  code/modules/projectiles/guns/energy/phase.dm
  code/modules/projectiles/guns/energy/temperature.dm
Labels: Removal, Tweak

#2401 CE can have his stamp back
  _maps/map_files/NSV_Triumph/triumph-01-deck1.dmm
Labels: Feature, Map Edit

#2389 Minor Adjustments to Triumph Map
  _maps/map_files/NSV_Triumph/triumph-01-deck1.dmm
  _maps/map_files/NSV_Triumph/triumph-02-deck2.dmm
  _maps/map_files/NSV_Triumph/triumph-03-deck3.dmm
  _maps/map_files/NSV_Triumph/triumph-04-deck4.dmm
Labels: Feature, Map Edit

#2406 Adds dogborg plushies
  code/game/objects/items/toys.dm
  icons/obj/toy.dmi
  vorestation.dme
Labels: Feature, Sprites

#2404 Fixes Optical Meson Aviators in the Loadout
  code/modules/client/preference_setup/loadout/loadout_eyes.dm
Labels: Fix

#2403 Gives borg and dogborg hypos the same chems as dogborg sleepers
  code/modules/mob/living/silicon/robot/dogborg/dog_modules_vr.dm
  code/modules/mob/living/silicon/robot/robot_modules/station/medical.dm
  code/modules/reagents/reagent_containers/borghydro.dm
Labels: Tweak

#2402 The Library's Private Study is now a separate area
  _maps/map_files/NSV_Triumph/triumph-04-deck4.dmm
  maps/nsv_triumph/triumph_areas2.dm
Labels: Feature, Map Edit

#2410 updates sdql2 yet again
  code/modules/admin/verbs/SDQL2/SDQL_2.dm
Labels: Administration, Fix, Priority: High

#2411 [READY] Icon Fixes and Implementation
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/mob/species/zaddat/head.dmi
  icons/mob/species/zaddat/suit.dmi
  icons/obj/barsigns.dmi
  icons/obj/clothing/species/zaddat/hats.dmi
Labels: Needs Review, Sprites

#2407 Misc. Clothing Fixes and _vr File Merging
  code/game/objects/items/weapons/traps.dm
  code/game/objects/items/weapons/traps_vr.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/masks/gasmask_vr.dm
  icons/mob/head.dmi
  icons/mob/mask.dmi
  icons/mob/mask_vr.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/clothing/masks_vr.dmi
  vorestation.dme
Labels: Code Improvement, Fix, Sprites

#2418 Ports the HoS/CMO/RD turtlenecks from Main
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/under/jobs/medsci.dm
  code/modules/clothing/under/jobs/security.dm
  icons/mob/uniform.dmi
  icons/mob/uniform_sleeves_rolled.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Feature, Sprites

#2419 Update triumph-01-deck1.dmm
  _maps/map_files/NSV_Triumph/triumph-01-deck1.dmm
Labels: Map Edit, Removal, polly

#2423 Refactors Preference Colour Previews, Improves Marking & Hair Customization
  code/modules/client/preference_setup/general/03_body.dm
  code/modules/client/preference_setup/global/01_ui.dm
  code/modules/client/preference_setup/preference_setup.dm
  code/modules/mob/new_player/preferences_setup.dm
Labels: Feature, Refactor, Tweak

#2420 Fixes Only One Accessory Equipped at Spawn & in Character Preview
  code/controllers/subsystems/jobs.dm
  code/modules/mob/new_player/preferences_setup.dm
Labels: Fix

#2422 Replaces Surgeon General with Chief Surgeon for the CMO
  code/game/jobs/job/medical.dm
Labels: Removal

#2429 Readds Bullet lighter and Zippo sounds
  code/game/objects/items/weapons/cigs_lighters.dm
  icons/obj/zippo.dmi
  sound/items/zippo_close.ogg
  sound/items/zippo_open.ogg
Labels: Feature, Sound, Sprites

#2426 Adds Missing Colourable Apron Sprites
  icons/mob/species/teshari/suit.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: Sprites

#2425 Hearts on BOTH SLEEVES
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_races/markings.dmi
Labels: Feature, Sprites, Tweak

#2434 Fixes Galore! Runtime Fixes Begin!
  code/datums/outfits/jobs/civilian.dm
  code/datums/outfits/jobs/civilian_vr.dm
  code/game/mecha/space/shuttle.dm
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/weapons/tanks/tank_types_vr.dm
  code/modules/admin/verbs/custom_event.dm
  code/modules/admin/verbs/dice.dm
  code/modules/clothing/suits/storage.dm
  code/modules/integrated_electronics/core/tools.dm
  code/modules/lighting/lighting_overlay.dm
  code/modules/lighting/lighting_source.dm
  code/modules/mob/living/carbon/human/species/station/plasmen.dm
  code/modules/mob/living/simple_animal/animals/farm_animals.dm
  code/modules/mob/transform_procs.dm
  code/modules/recycling/disposal.dm
  vorestation.dme
Labels: Fix, Priority: High

#2433 CCC: Roast Teshstravaganza!
  _maps/map_files/NSV_Triumph/triumph-02-deck2.dmm
  code/modules/food/food/snacks.dm
  code/modules/food/food/snacks/meat.dm
  code/modules/food/recipes_oven.dm
  code/modules/mob/living/carbon/human/species/station/teshari.dm
  icons/obj/food.dmi
Labels: Map Edit, Sprites

#2432 Adds an "Event Rewards" section to the loadout. Changes Donator Items to cost 0 loadout points.
  code/modules/client/preference_setup/loadout/loadout_donator.dm
  code/modules/client/preference_setup/loadout/loadout_event_rewards.dm
  vorestation.dme
Labels: Feature, Tweak

#2438 Map configs
  _maps/map_files/triumph/triumph-01-deck1.dmm
  _maps/map_files/triumph/triumph-02-deck2.dmm
  _maps/map_files/triumph/triumph-03-deck3.dmm
  _maps/map_files/triumph/triumph-04-deck4.dmm
  _maps/map_files/triumph/triumph-05-flagship.dmm
  _maps/triumph.dm
  config/maps.txt
  maps/nsv_triumph/triumph.dm
  vorestation.dme
Labels: Config Update, Currently Testmerged, Map Edit, Test Merge Candidate

#2439 Linter Errors
  _maps/triumph.json
  code/__DEFINES/math_physics.dm
  code/__DEFINES/misc.dm
  code/__DEFINES/mobs.dm
  code/game/jobs/job/special.dm
  code/game/jobs/job/special_vr.dm
  code/game/machinery/oxygen_pump.dm
  code/game/machinery/status_display.dm
  code/game/machinery/telecomms/telecomunications.dm
  code/game/mecha/mecha.dm
  code/game/objects/items/weapons/tanks/tanks.dm
  code/game/objects/structures/stool_bed_chair_nest/wheelchair.dm
  code/game/turfs/snow/snow.dm
  code/game/turfs/turf.dm
  code/modules/ai/ai_holder_targeting.dm
  code/modules/alarm/alarm.dm
  code/modules/atmospherics/components/binary_devices/pipeturbine.dm
  code/modules/client/client_procs.dm
  code/modules/rogueminer_vr/zone_console.dm
  code/modules/shuttles/shuttle_ferry.dm
  code/modules/surgery/organs_internal.dm
  maps/nsv_triumph/triumph_phoronlock.dm
  vorestation.dme
Labels: Currently Testmerged, Fix, Map Edit

#2424 PMD - Exotic Weaponry Update
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/ammunition/rounds.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  code/modules/projectiles/projectile/bullets.dm
  icons/mob/items/lefthand_guns.dmi
  icons/mob/items/righthand_guns.dmi
  icons/obj/ammo.dmi
  icons/obj/gun/ballistic.dmi
  icons/obj/gun/energy.dmi
Labels: Currently Testmerged, Sprites

#2427 Hard Boiled: A Citadel Story (Gives the Detective their .45 instead of a taser.)
  _maps/map_files/triumph/triumph-04-deck4.dmm
  code/game/objects/structures/crates_lockers/closets/secure/explorer.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/turfs/simulated/water.dm
Labels: Currently Testmerged, Map Edit

#2441 Adds automatic TGS DMAPI updates
  .github/workflows/update_tgs_dmapi.yml
Labels: GitHub, Good First PR

#2445 Haha i'm dumb
  .github/workflows/update_tgs_dmapi.yml
Labels: GitHub

#2444 Updates to Triumph Layout: Improved Stairwell (Fore Section)
  _maps/map_files/triumph/triumph-01-deck1.dmm
  _maps/map_files/triumph/triumph-02-deck2.dmm
  _maps/map_files/triumph/triumph-03-deck3.dmm
  _maps/map_files/triumph/triumph-04-deck4.dmm
  maps/nsv_triumph/triumph_areas.dm
  maps/nsv_triumph/triumph_things.dm
Labels: Map Edit, Tweak

#2452 Fix git add in DMAPI update action
  .github/workflows/update_tgs_dmapi.yml
Labels: GitHub

#2453 Adds fission monitoring program to modular computers.
  code/modules/power/fission/computer.dm
  code/modules/power/fission/engine.dm
  code/modules/power/fission/modular_computer.dm
  nano/templates/fission_monitor_prog.tmpl
  vorestation.dme
Labels: Feature

#2443 The Art of Mimicry: An update for Mimics [Ready to Merge]
  code/modules/mob/living/simple_mob/subtypes/vore/mimic.dm
  icons/mob/animal.dmi
Labels: Code Improvement, Feature, Sprites

#2454 Fission Engine Temperature Rebalance
  code/modules/power/fission/engine.dm
  code/modules/power/fission/rods.dm
Labels: Balance/Rebalance

#2461 Donator Item
  code/modules/client/preference_setup/loadout/loadout_donator.dm
  modular_citadel/code/modules/clothing/donatorclothing.dm
  modular_citadel/icons/mob/donatorclothing.dmi
  modular_citadel/icons/obj/clothing/donatorclothing.dmi
Labels: Feature

#2460 Fixes uniform sprite issue
  icons/mob/uniform.dmi
Labels: Fix, Good First PR, Sprites

#2448 Triumph Update: New Engineering Bay & Reactor
  _maps/map_files/triumph/triumph-01-deck1.dmm
  _maps/map_files/triumph/triumph-02-deck2.dmm
  _maps/map_files/triumph/triumph-03-deck3.dmm
  _maps/map_files/triumph/triumph-04-deck4.dmm
  code/__DEFINES/tgs.dm
  code/modules/tgs/v3210/api.dm
  code/modules/tgs/v3210/commands.dm
  code/modules/tgs/v5/api.dm
  maps/nsv_triumph/triumph_areas.dm
  maps/nsv_triumph/triumph_things.dm
Labels: Feature, Map Edit
