Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2020-07, with the labels that each got.

#2141 MAP: Improved medbay lobby, CMO locker, Mining equipment & HoS Pet
  _maps/map_files/Tether/tether-01-surface1.dmm
  _maps/map_files/Tether/tether-03-surface3.dmm
  _maps/map_files/Tether/tether-05-station1.dmm
  _maps/map_files/Tether/tether-07-station3.dmm
  code/game/jobs/job/medical.dm
  code/modules/mob/living/simple_mob/subtypes/animal/pets/dog.dm
  code/modules/vore/fluffstuff/guns/cell_loaded/ml3m.dm
  icons/mob/animal.dmi
Labels: Feature, Map Edit, Sprites, Tweak

#2150 Circulator Sprite Tweak
  icons/obj/power.dmi
Labels: Sprites

#2155 Let there be Light
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
Labels: Feature

#2158 Search & Rescue Access Fix Pt 2 & Gear
  _maps/map_files/Tether/tether-05-station1.dmm
Labels: Balance/Rebalance, Map Edit, Tweak

#2167 Rat Migration no longer OOMs due to Vermintide.
  code/modules/events/hostile_migration_vr.dm
Labels: Fix

#2160 Fixes Stacker Console Runtime
  _maps/map_files/Tether/tether-01-surface1.dmm
Labels: Map Edit

#2157 CCC: The Snake Oil Salesman Event!
  code/game/machinery/computer3/computers/arcade.dm
  code/game/machinery/vending.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/trash.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/modules/food/drinkingglass/metaglass.dm
  code/modules/food/food/snacks.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/reagents/Chemistry-Recipes.dm
  icons/obj/drinks.dmi
  icons/obj/food.dmi
  icons/obj/toy.dmi
  icons/obj/trash.dmi
  icons/obj/zippo.dmi
Labels: Sprites

#2149 Adds firing pins and their associated behaviour. No more gunsci please.
  _maps/map_files/Tether/tether-02-surface2.dmm
  _maps/map_files/Tether/tether-07-station3.dmm
  code/datums/supplypacks/munitions.dm
  code/game/objects/items/weapons/storage/boxes.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/pins.dm
  code/modules/research/designs.dm
  code/modules/research/designs/weapons.dm
  code/modules/vore/fluffstuff/custom_guns_vr.dm
  code/modules/vore/fluffstuff/guns/cell_loaded/ml3m.dm
  icons/obj/device.dmi
  icons/obj/storage.dmi
  vorestation.dme
Labels: Map Edit, Sprites

#2173 Adds way of Unbricking RIGs
  code/modules/clothing/spacesuits/rig/rig_wiring.dm
Labels: Feature

#2177 Readds cargo carp/spider
  code/datums/supplypacks/hydroponics.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/_giant_spider.dm
  code/modules/mob/living/simple_mob/subtypes/animal/space/carp.dm
Labels: Balance/Rebalance, Tweak

#2164 Woaw glasses that don't look like mugs? Impossible!
  code/modules/client/preference_setup/loadout/loadout_eyes.dm
  code/modules/clothing/glasses/glasses.dm
  icons/mob/eyes.dmi
Labels: Sprites, Tweak

#2124 Modular Energy Guns 2
  code/modules/client/client_procs.dm
  code/modules/projectiles/guns/energy/modular/gunframes.dm
  code/modules/projectiles/guns/energy/modular/lasermediums.dm
  code/modules/projectiles/guns/energy/modular/modularcooling.dm
  code/modules/projectiles/guns/energy/modular/modularfcu.dm
  code/modules/projectiles/guns/energy/modular/modulargun.dm
  code/modules/projectiles/guns/energy/modular/modularlenses.dm
  code/modules/projectiles/guns/energy/modular/modularpower.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/scatter.dm
  code/modules/research/designs/weapons.dm
  icons/obj/gun.dmi
  vorestation.dme
Labels: Feature, Removal, Sprites

#2182 Map Adjustments for Surface 3 & Station 1
  _maps/map_files/Tether/tether-03-surface3.dmm
  _maps/map_files/Tether/tether-05-station1.dmm
  maps/tether/tether_areas2.dm
  nano/images/nanomap_z3.png
  nano/images/nanomap_z5.png
Labels: Feature, Map Edit

#2185 some stealth/min updates
  code/__HELPERS/unsorted.dm
  code/game/verbs/advanced_who.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/deadsay.dm
  code/modules/client/preference_setup/global/setting_datums.dm
  code/modules/client/preferences_toggle_procs.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/mob_helpers.dm
  code/modules/mob/new_player/new_player.dm
  config/admin_nicknames.txt
Labels: Config Update

#2188 Holographic and Wrist-Bound PDA Port
  code/__HELPERS/global_lists.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/modules/client/preference_setup/general/04_equipment.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/new_player/preferences_setup.dm
  icons/mob/pda_wrist.dmi
  icons/mob/species/seromi/pda_wrist.dmi
  icons/obj/pda_holo.dmi
  icons/obj/pda_wrist.dmi
Labels: Code Improvement, Feature, Sprites

#2193 AFW: Summer Catalog
  code/game/machinery/vending_vr.dm
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/food/food/snacks.dm
  code/modules/food/recipes_microwave.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/vore/fluffstuff/custom_boxes_vr.dm
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/food.dmi
  modular_citadel/code/modules/client/preference_setup/loadout_donator.dm
  modular_citadel/code/modules/clothing/donatorclothing.dm
  modular_citadel/code/modules/clothing/under/accessories/donatoraccessory.dm
  modular_citadel/icons/mob/donatorclothing.dmi
  modular_citadel/icons/obj/clothing/donatorclothing.dmi
Labels: Sprites

#2192 supermatter weapon fix
  code/game/objects/items/weapons/material/material_weapons.dm
  code/game/objects/items/weapons/material/twohanded.dm
Labels: Fix

#2189 New Sci Outpost
  .gitattributes
  _maps/map_files/Tether/tether-09-solars.dmm
  maps/tether/tether_areas2.dm
Labels: Map Edit

#2191 Un-hugboxes Tesla Reactor
  code/modules/power/tesla/energy_ball.dm
Labels: Tweak

#2203 Fixes an age old typo
  _maps/map_files/Tether/tether-05-station1.dmm
  code/modules/admin/topic.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/simple_animal/animals/parrot.dm
  code/modules/mob/living/simple_mob/subtypes/animal/pets/parrot.dm
  icons/mob/birds.dmi
  maps/tether/submaps/gateway/zoo.dmm
Labels: Map Edit, Sprites

#2197 Summer Catalog Hotfix / Surface Medical Treatment Center Rework
  _maps/map_files/Tether/tether-01-surface1.dmm
  _maps/map_files/Tether/tether-03-surface3.dmm
  _maps/map_files/Tether/tether-06-station2.dmm
  _maps/map_files/Tether/tether-07-station3.dmm
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/food/food/snacks.dm
  icons/obj/clothing/glasses.dmi
  icons/obj/clothing/species/vulpkanin/suits.dmi
Labels: Map Edit, Sprites

#2218 Why does paramed have mining access like that lmao
  code/game/jobs/job/medical.dm
Labels: Balance/Rebalance, Tweak

#2213 Jukebox UI Minor Tweaks
  nano/templates/jukebox.tmpl
Labels: Feature

#2209 Gives shadekin trash-eat and lick-wounds
  code/modules/mob/living/carbon/human/species/shadekin/shadekin.dm
Labels: Feature

#2204 Sci post adjust/fix
  _maps/map_files/Tether/tether-09-solars.dmm
Labels: Map Edit

#2201 Adds hotkey for LOOC and changeable bind
  code/modules/client/verbs/ooc.dm
  code/modules/keybindings/keybind/mob.dm
Labels: Feature

#2220 regarding autolathes
  code/game/machinery/autolathe.dm
Labels: Priority: High

#2219 Mind the Gap Update
  _maps/map_files/Tether/tether-01-surface1.dmm
  _maps/map_files/Tether/tether-06-station2.dmm
  _maps/map_files/Tether/tether-10-colony.dmm
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/clothing/head/hood.dm
  code/modules/clothing/suits/hooded.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/accessories/permits.dm
  code/modules/clothing/under/accessories/permits_vr.dm
  code/modules/surgery/robotics.dm
  icons/mob/suit.dmi
  icons/obj/clothing/suits.dmi
  maps/tether/submaps/tether_misc.dmm
Labels: Map Edit, Sprites

#2226 toxins floor hole fix
  _maps/map_files/Tether/tether-09-solars.dmm
Labels: Fix, Map Edit

#2225 The "Pardon Our Dust" Update
  _maps/map_files/Tether/tether-01-surface1.dmm
  _maps/map_files/Tether/tether-02-surface2.dmm
  _maps/map_files/Tether/tether-05-station1.dmm
Labels: Map Edit

#2221 More Traits
  code/modules/mob/living/carbon/human/species/station/traits_vr/negative.dm
  code/modules/mob/living/carbon/human/species/station/traits_vr/positive.dm
Labels: Feature, Tweak

#2217 raises max keybind command length to 32 so controller users don't get kicked
  code/__DEFINES/admin/keybindings.dm
Labels: IGNORE TRAVIS, Priority: High

#2205 Meltdown Creaturepocalypse
  code/modules/power/fission/engine.dm
Labels: Feature, MEME PR

#2199 logs now also show the user's area because i don't realize how terrible this is until i have to use it
  code/__HELPERS/logging.dm
Labels: Priority: High

#2198 drops log access cooldown from !20! seconds to 3.
  code/__HELPERS/files.dm
Labels: IGNORE TRAVIS

#2228 [READY] Xenolove: New Bodysuits, Shrouds and Envirosuits
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/crates_lockers/closets/secure/security_vr.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/clothing/spacesuits/void/zaddat.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/head.dmi
  icons/mob/spacesuit.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/spacesuits.dmi
  icons/obj/clothing/uniforms.dmi
  modular_citadel/icons/mob/plasmeme/helmet.dmi
  modular_citadel/icons/mob/plasmeme/suit.dmi
  modular_citadel/icons/obj/plasmeme/hats.dmi
  modular_citadel/icons/obj/plasmeme/suits.dmi
Labels: Needs Review, Sprites

#2230 Copypasta Code Gone Wild (whoever added looc key forgot the "l" before "ooc")
  code/modules/keybindings/keybind/mob.dm
Labels: Priority: High

#2234 A Trait Fix
  code/modules/mob/living/carbon/human/species/station/traits_vr/negative.dm
Labels: Fix

#2233 [FIX][READY] Xenolove Hotfix
  code/modules/clothing/spacesuits/void/zaddat.dm
  icons/mob/uniform.dmi
Labels: Needs Review, Sprites
