Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2020-03, with the labels that each got.

#1698 Adds Songs to the Jukebox
  code/game/machinery/jukebox.dm
  config/jukebox.json
  config/jukebox.txt
Labels: Config Update, Grammar and Formatting, Sound

#1697 Vox EVA Hardsuit Sprites
  icons/mob/species/vox/gloves.dmi
  icons/mob/species/vox/head.dmi
  icons/mob/species/vox/shoes.dmi
  icons/mob/species/vox/suit.dmi
Labels: Sprites

#1699 Vox Industiral Suit Sprites
  icons/mob/species/vox/gloves.dmi
  icons/mob/species/vox/head.dmi
  icons/mob/species/vox/shoes.dmi
  icons/mob/species/vox/suit.dmi
Labels: Sprites

#1700 stack crossover automerge and alt click splitting because clicking on 50 sheets of metal is not something that is okay
  code/game/objects/items/stacks/stack.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/inventory.dm
Labels: Feature

#1704 Added rodent squeak emote
  code/modules/mob/living/carbon/human/emote.dm
Labels: Code Improvement, Feature

#1703 Misc Map Fixes
  maps/tether/tether-05-station1.dmm
  maps/tether/tether-07-station3.dmm
  maps/tether/tether-09-solars.dmm
Labels: Fix

#1702 Vox Medical Rig Sprites
  icons/mob/species/vox/gloves.dmi
  icons/mob/species/vox/head.dmi
  icons/mob/species/vox/shoes.dmi
  icons/mob/species/vox/suit.dmi
Labels: Sprites

#1701 Adds in the fat dragon tails, and some smaller tails, horns to match
  code/modules/vore/appearance/sprite_accessories_taur_vr.dm
  code/modules/vore/appearance/sprite_accessories_vr.dm
  icons/mob/vore/ears_vr.dmi
  icons/mob/vore/tails_vr.dmi
  icons/mob/vore/taurs_vr.dmi
Labels: Code Improvement, Feature, Sprites

#1705 Added TechPriest robes to loadout, chapel, and cargo crates
  code/datums/supplypacks/costumes.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/clothing/head/hood.dm
  code/modules/clothing/suits/hooded.dm
  code/modules/clothing/suits/miscellaneous.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: Feature, Sprites

#1707 Adds cooking oil tank crate, and icon for it
  code/datums/supplypacks/hospitality_vr.dm
  icons/obj/objects.dmi
Labels: Feature, Sprites

#1708 More tiny map fixes
  maps/tether/tether-01-surface1.dmm
  maps/tether/tether-02-surface2.dmm
  maps/tether/tether-03-surface3.dmm
  maps/tether/tether-09-solars.dmm
Labels: Fix

#1709 New Hair, updated from Polaris
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
  icons/mob/human_face_m.dmi
  icons/mob/human_face_or_vr.dmi
Labels: Feature, Sprites

#1719 Adjustements to Bar/Kitchen area
  code/game/turfs/flooring/flooring_premade.dm
  maps/tether/tether-03-surface3.dmm
  maps/tether/tether-05-station1.dmm
Labels: Feature, Tweak

#1712 [WEBEDIT] Fixes Teshari QM cloak description
  code/modules/clothing/suits/aliens/seromi.dm
  code/modules/clothing/under/xenos/seromi.dm
Labels: Tweak

#1711 Assorted Vox Apparel
  icons/mob/species/vox/head.dmi
  icons/mob/species/vox/helmet.dmi
  icons/mob/species/vox/suit.dmi
Labels: Sprites

#1724 Remakes Enzo's bar PR
  code/game/machinery/vending.dm
  code/modules/food/drinkingglass/metaglass.dm
  code/modules/food/food/drinks/bottle.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/reagents/Chemistry-Recipes.dm
  icons/obj/drinks.dmi
  maps/tether/tether-03-surface3.dmm
Labels: Code Improvement, Feature, Sprites, Tweak

#1727 Get Bandanas Working
  icons/mob/species/vox/masks.dmi
Labels: Sprites

#1728 Adding 6 new drink sprites.
  code/modules/food/drinkingglass/metaglass.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/reagents/Chemistry-Recipes.dm
  icons/obj/drinks.dmi
Labels: Feature, Sprites

#1733 Medbay Changes/Upgrades : The word of the day is, chemfridge.
  maps/tether/tether-07-station3.dmm
Labels: Feature

#1734 Revamped food changes part 1, also known as: Burgers only contained 4 useful food units while shakers had 65 omegalul.
  code/game/machinery/vending.dm
  code/modules/food/drinkingglass/shaker.dm
  code/modules/food/food/snacks.dm
Labels: Balance/Rebalance, Code Improvement, Grammar and Formatting, Tweak

#1736 Fixes Phantom Jukebox Problem, Resolves #1735
  code/modules/media/media_machinery.dm
Labels: Fix

#1743 Adds two new crates, the Jukebox crate, and Jukebox Circuit Board crate.
  code/datums/supplypacks/misc_vr.dm
  code/datums/supplypacks/recreation.dm
  code/datums/supplypacks/science.dm
Labels: Feature

#1740 Roundstart implants now work. Also known as: wow tracking implants ACTUALLY track you? Cool!
  code/game/jobs/job_controller.dm
  code/game/objects/items/weapons/implants/implant.dm
  code/modules/client/preference_setup/loadout/loadout.dm
  code/modules/client/preference_setup/loadout/loadout_utility.dm
  code/modules/mob/mob.dm
Labels: Code Improvement, Feature, Fix

#1726 fixes stackers being horrendous shitcode
  code/modules/mining/machine_stacking.dm
Labels: Test Merge Candidate

#1744 Adding extension to Midpoint (With proper mapmerge yeee)
  maps/tether/tether-04-transit.dmm
Labels: Feature

#1750 Adds ~250 Songs to the Jukebox, Adds More Lobby Music, Removes Emagged Jukebox Explosions.
  code/game/machinery/jukebox.dm
  config/jukebox.json
  config/jukebox.txt
  icons/obj/jukebox.dmi
Labels: Config Update, Grammar and Formatting, Removal, Sound, Sprites, Tweak

#1749 Fixed Tech Priest Robes not displaying properly
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/clothing/head/hood.dm
  code/modules/clothing/suits/hooded.dm
  code/modules/clothing/suits/miscellaneous.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Fix, Sprites
