Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2020-12, with the labels that each got.

#2524 Added Astral Wind drink.
  code/modules/food/drinkingglass/metaglass.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/reagents/Chemistry-Recipes.dm
  icons/obj/drinks.dmi
Labels: Currently Testmerged, Feature, Sprites, Testmerge Only

#2531 [READY] jagged spikes, disruptor blades, nullrod bonus damage fix, armblade inhands fix
  code/datums/autolathe/general.dm
  code/game/objects/items/contraband.dm
  code/game/objects/items/weapons/nullrod.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/items/weapons/swords_axes_etc.dm
  code/modules/clothing/under/accessories/holster.dm
  code/modules/mob/living/carbon/human/human.dm
  icons/mob/items/lefthand_material.dmi
  icons/mob/items/righthand_material.dmi
  icons/obj/weapons.dmi
Labels: Currently Testmerged, Feature, Needs Review, Sprites, Work in Progress

#2532 fuck off with the 10 second log access delay
  code/__HELPERS/files.dm
Labels: Currently Testmerged

#2533 lowers clothes vendor prices across the board to like 25% and adds fake marisa hats
  code/game/machinery/vending.dm
Labels: Balance/Rebalance, Currently Testmerged

#2535 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
  code/modules/clothing/suits/hooded.dm
Labels: Currently Testmerged, Tweak

#2539 fixes protean vore settings because if i get hardstunned by a carp again i'm going to go ape and punch a hole through the code
  code/modules/mob/living/carbon/human/species/station/protean/protean_blob.dm
Labels: Currently Testmerged

#2521 Minor Alraune Fix
  code/modules/mob/living/carbon/human/species/station/alraune.dm
Labels: Currently Testmerged

#2538 Removes the m41a
  code/game/objects/structures/crates_lockers/closets/secure/explorer.dm
Labels: Currently Testmerged, Removal

#2540 Security Eyepatch Now Selectable on Loadout Screen
  code/modules/client/preference_setup/loadout/loadout_eyes.dm
Labels: Currently Testmerged

#2542 fixes curtains, typo in toy code
  code/game/objects/items/toys.dm
  code/game/objects/structures/curtains.dm
  code/modules/mob/living/carbon/human/emote.dm
Labels: Currently Testmerged, Fix

#2543 Ghost hud buttons
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/_defines_vr.dm
  code/_onclick/hud/ghost.dm
  code/_onclick/hud/other_mobs.dm
  code/modules/mob/dead/observer/observer.dm
  icons/mob/screen_ghost.dmi
  vorestation.dme
Labels: Currently Testmerged, Sprites

#2544 Speech bubbles appear above objects you're inside of.
  code/modules/mob/living/say.dm
Labels: Currently Testmerged

#2545 removes pin requirement on xeno taser (missed one, damn)
  code/modules/xenobio/items/weapons.dm
Labels: Currently Testmerged, Removal

#2541 Job titles
  code/game/jobs/job/assistant.dm
  code/game/jobs/job/captain.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/civilian_chaplain.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/exploration.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/game/jobs/job/silicon.dm
  code/game/jobs/job/z_all_jobs_vr.dm
  modular_citadel/code/game/jobs/job/assistant_cit.dm
  modular_citadel/code/game/jobs/job/engineering_cit.dm
  modular_citadel/code/game/jobs/job/z_all_jobs_cit.dm
  vorestation.dme
Labels: Currently Testmerged

#2552 Unusable emote 'me'. Say *help for a list.
  code/modules/mob/living/carbon/human/emote.dm
Labels: Currently Testmerged, Fix

#2548 Tweaks Acid/Blood Turf Damage & Adds Captain's Carapace Armor
  code/game/atoms_movable.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/suits/armor.dm
  code/modules/mob/living/living_defense.dm
  icons/mob/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: Currently Testmerged, Sprites

#2498 New Marksman Gunbox
  code/datums/supplypacks/munitions.dm
  code/game/objects/items/gunbox.dm
  code/modules/mining/ore_redemption_machine/survey_vendor.dm
  code/modules/power/cells/device_cells.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/projectile/boltaction.dm
  code/modules/projectiles/guns/projectile/semiauto.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets.dm
  icons/obj/gun/ballistic.dmi
Labels: Currently Testmerged, Feature, Sprites

#2553 you can now color things with color matrices with a colormate and in foresight letting players do this is a HORRIBLE idea, but it's fun, so i did it anyways
  code/__HELPERS/matrices/color.dm
  code/game/machinery/painter_vr.dm
Labels: Currently Testmerged, Feature

#2555 ore processor speed toggle
  code/modules/mining/machine_processing.dm
Labels: Currently Testmerged, Tweak

#2556 hardsuit recharging via borg charger
  code/game/machinery/rechargestation.dm
Labels: Currently Testmerged, Feature

#2557 Fixes medHUDs being broken for over a year
  code/modules/mob/living/carbon/human/life.dm
  icons/mob/hud_jobs_vr.dmi
Labels: Currently Testmerged, Sprites

#2558 "Fixes" Pathfinder Locker
  code/game/objects/structures/crates_lockers/closets/secure/explorer.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  icons/obj/gun/ballistic.dmi
Labels: Currently Testmerged, Feature, Sprites

#2559 adds shapeshifting verbs to xenochimera because why wasn't it here
  code/modules/mob/living/carbon/human/species/station/station_special.dm
Labels: Currently Testmerged

#2563 changes how xenochimera can regenerate because my brain is liquid
  code/modules/mob/living/carbon/human/species/station/station_special_abilities.dm
Labels: Currently Testmerged

#2566 let's make vampirism not bad
  code/game/objects/items/stacks/medical.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/species/station/station_special_abilities.dm
  code/modules/vore/eating/living_vr.dm
Labels: Currently Testmerged

#2567 Ports gradients on hairstyles from Polaris
  code/modules/client/preference_setup/general/03_body.dm
  code/modules/client/preferences.dm
  code/modules/mob/living/carbon/human/appearance.dm
  code/modules/mob/living/carbon/human/gradient.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/species/species_shapeshift.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  icons/mob/hair_gradients.dmi
  vorestation.dme
Labels: Currently Testmerged, Feature, Sprites

#2571 adds regeneration verb to xenochimera
  code/modules/mob/living/carbon/human/species/station/station_special.dm
Labels: Currently Testmerged

#2569 Make chemical patches more usefull
  code/modules/reagents/reagent_containers/patch.dm
Labels: Currently Testmerged, Feature, Fix

#2565 Removes defib timer. Replaces with brain damage over time. Alien species can now be defibbed.
  code/__DEFINES/species_languages.dm
  code/game/objects/items/devices/defib.dm
  code/modules/mob/living/carbon/human/species/outsider/skeleton.dm
  code/modules/mob/living/carbon/human/species/station/station_special.dm
  code/modules/organs/organ.dm
Labels: Currently Testmerged, Removal

#2371 [WIP] Adds new explosions and ship creaking sound effects
  code/__DEFINES/sound.dm
  code/game/objects/explosion.dm
  code/modules/events/event_container_vr.dm
  code/modules/events/gravity.dm
  sound/effects/creak1.ogg
  sound/effects/creak2.ogg
  sound/effects/creak3.ogg
  sound/effects/explosioncreak1.ogg
  sound/effects/explosioncreak2.ogg
Labels: Currently Testmerged, Feature, Sound, Work in Progress

#2574 adds more funcitonality to bloodsucker()
  code/modules/mob/living/carbon/human/species/station/station_special_abilities.dm
Labels: Currently Testmerged, Feature

#2572 marks food as opencontainer so you can pois- errrr take toxins out of them ^w^
  code/modules/food/food/snacks.dm
Labels: Currently Testmerged, Fix

#2562 Map Tweaks: Engineering Atmos and Mining Shuttle Relays
  _maps/map_files/triumph/triumph-01-deck1.dmm
  _maps/map_files/triumph/triumph-02-deck2.dmm
  code/game/objects/items/weapons/grenades/chem_grenade.dm
Labels: Currently Testmerged, Map Edit

#2570 Increases Mining Void Rad Resistance So People Stop Dying, Even If It's Funny When They Do
  code/modules/clothing/spacesuits/rig/suits/station.dm
  code/modules/clothing/spacesuits/void/station.dm
Labels: Currently Testmerged

#2564 Adds proper dehusking/detoxifying/reoxygenating surgery.
  _maps/map_files/triumph/triumph-03-deck3.dmm
  code/game/objects/items/weapons/surgery_tools.dm
  code/modules/surgery/external_repair.dm
  code/modules/surgery/other.dm
  icons/obj/surgery.dmi
Labels: Currently Testmerged, Map Edit, Sprites

#2575 microoptimization for origin tech
  code/game/objects/items.dm
Labels: Currently Testmerged

#2576 fixes fulton extraction packs
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/crates_lockers/crates.dm
Labels: Currently Testmerged

#2577 unbelievably shitcode fix for janiborgs not being able to recycle glass which is caused by a bug that was the result of unbelievably shitcode code
  code/modules/materials/material_sheets.dm
  code/modules/mob/living/silicon/robot/robot_modules/station/service.dm
Labels: Currently Testmerged

#2578 Makes chem machines eject beakers into your hand. Add radials to grinder.
  code/modules/reagents/Chemistry-Machinery.dm
  code/modules/reagents/dispenser/dispenser2.dm
Labels: Currently Testmerged

#2573 Unlocks Exploration Jump Console
  _maps/map_files/triumph/triumph-04-deck4.dmm
Labels: Currently Testmerged, Map Edit

#2589 SANITIZE YOUR FUCKING INPUTS
  code/game/machinery/pipe/pipe_dispenser.dm
Labels: Priority: High

#2581 local expedition team found crashing through meteors at 60 Gm/h after proteans fall asleep in cyborg recharger, more at 10
  code/game/machinery/rechargestation.dm
Labels: Currently Testmerged, Feature

#2579 Prevents any Diagonal Movement while ventcrawling
  code/modules/ventcrawl/ventcrawl_atmospherics.dm
Labels: Currently Testmerged, Fix

#2561 small cleanup of visible message
  code/game/atoms.dm
  code/game/gamemodes/nuclear/pinpointer.dm
  code/modules/mob/mob.dm
Labels: Currently Testmerged

#2582 Adds recipes for gel variants of Inaprovaline, Bicaridine, Dermaline …
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Currently Testmerged, Feature

#2584 removes some of the goddawful shitcode from protean rigs, removes their complete radiation and taser immunity
  code/modules/clothing/spacesuits/rig/suits/alien.dm
Labels: Balance/Rebalance, Currently Testmerged, Removal

#2585 ghosts are infact supposed to go past the barrier tape
  code/game/objects/items/weapons/barrier_tape.dm
Labels: Currently Testmerged

#2588 Fixes airlocks not having wires after being constructed
  code/game/machinery/doors/airlock.dm
Labels: Currently Testmerged

#2587 Suppresses beaker dipping for foods, drinks and other beakers.
  code/modules/reagents/reagent_containers/glass.dm
Labels: Currently Testmerged

#2580 polaris 7784 and 7098 port - RPED QoL, destructive analyzers return material to lathe, R&D UI improved
  code/datums/wires/autolathe.dm
  code/defines/obj/weapon.dm
  code/game/machinery/_machinery.dm
  code/game/machinery/autolathe.dm
  code/game/objects/items.dm
  code/game/objects/items/weapons/storage/_storage.dm
  code/modules/research/destructive_analyzer.dm
  code/modules/research/rdconsole.dm
Labels: Currently Testmerged, Fix, Tweak

#2600 New fancy glowing cloaks
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/clothing/under/accessories/clothing.dm
  icons/mob/ties.dmi
  icons/obj/clothing/ties.dmi
Labels: Currently Testmerged, Feature, Good First PR, Sprites

#2593 Fixes All of the RandomZ Maps
  _maps/map_files/triumph/triumph-04-deck4.dmm
  maps/RandomZLevels/Academy.dmm
  maps/RandomZLevels/beach.dmm
  maps/RandomZLevels/blackmarketpackers.dmm
  maps/RandomZLevels/carpfarm.dmm
  maps/RandomZLevels/challenge.dmm
  maps/RandomZLevels/desertbase.dmm
  maps/RandomZLevels/example.dmm
  maps/RandomZLevels/jungle.dmm
  maps/RandomZLevels/labyrinth.dm
  maps/RandomZLevels/labyrinth.dmm
  maps/RandomZLevels/listeningpost.dmm
  maps/RandomZLevels/randomz_areas.dm
  maps/RandomZLevels/snow_outpost.dmm
  maps/RandomZLevels/snowfield.dmm
  maps/RandomZLevels/spacebattle.dmm
  maps/RandomZLevels/stationCollision.dm
  maps/RandomZLevels/stationCollision.dmm
  maps/RandomZLevels/wildwest.dm
  maps/RandomZLevels/wildwest.dmm
  maps/RandomZLevels/zoo.dmm
  maps/RandomZLevels/zresearchlabs.dmm
  vorestation.dme
Labels: Currently Testmerged, Map Edit

#2598 Assistant is missing, but Tourist was left in. lol
  code/game/jobs/job/assistant.dm
Labels: Currently Testmerged

#2603 Engineering rework/Additional error item, airlock and camera location fixes
  _maps/map_files/triumph/triumph-01-deck1.dmm
  _maps/map_files/triumph/triumph-02-deck2.dmm
  _maps/map_files/triumph/triumph-03-deck3.dmm
  _maps/map_files/triumph/triumph-04-deck4.dmm
Labels: Currently Testmerged, Map Edit

#2599 Cyborg Sprite Ports
  code/modules/mob/living/silicon/robot/robot_modules/station/cargo.dm
  code/modules/mob/living/silicon/robot/robot_modules/station/engineering.dm
  code/modules/mob/living/silicon/robot/robot_modules/station/medical.dm
  code/modules/mob/living/silicon/robot/robot_modules/station/misc.dm
  code/modules/mob/living/silicon/robot/robot_modules/station/science.dm
  code/modules/mob/living/silicon/robot/robot_modules/station/security.dm
  code/modules/mob/living/silicon/robot/robot_modules/station/service.dm
  icons/mob/robots.dmi
Labels: Currently Testmerged, Sprites
