Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2020-09, with the labels that each got.

#2297 Fixes the broken (read: nonexistent) sprite on the pleated skirt.
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Fix, Sprites

#2298 Adds Purr emote
  code/modules/mob/living/carbon/human/emote_vr.dm
  modular_citadel/sound/voice/purr.ogg
Labels: Feature

#2295 external rsc loading, no more waiting 20 minutes to download resources and both servers lagging every time someone joins the game
  code/controllers/configuration/entries/resources.dm
  code/game/world.dm
  code/modules/client/client_procs.dm
  vorestation.dme
Labels: Config Update

#2301 Restores missing mob states
  icons/mob/64x64.dmi
  icons/mob/vore.dmi
Labels: Sprites

#2302 Miscellaneous Clothing Fixes and Adjustments
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/client/preference_setup/loadout/loadout_uniform_vr.dm
  code/modules/clothing/under/accessories/clothing.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/vore/fluffstuff/custom_clothes_vr.dm
  icons/mob/ties.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/ties.dmi
  icons/obj/clothing/uniforms.dmi
  icons/vore/custom_clothes_vr.dmi
  modular_citadel/code/modules/vore/fluffstuff/custom_clothes_vr.dm
  vorestation.dme
Labels: Sprites

#2291 Dark Corners of the Galaxy: Cult Simple Mobs and Weapon Integration
  code/datums/supplypacks/munitions.dm
  code/game/machinery/vending_vr.dm
  code/game/objects/random/guns_and_ammo.dm
  code/game/objects/random/random.dm
  code/modules/mob/living/simple_mob/subtypes/humanoid/cultist.dm
  code/modules/mob/living/simple_mob/subtypes/occult/constructs/_construct.dm
  code/modules/mob/living/simple_mob/subtypes/occult/constructs/artificer.dm
  code/modules/mob/living/simple_mob/subtypes/occult/constructs/harvester.dm
  code/modules/mob/living/simple_mob/subtypes/occult/constructs/juggernaut.dm
  code/modules/mob/living/simple_mob/subtypes/occult/constructs/proteon.dm
  code/modules/mob/living/simple_mob/subtypes/occult/constructs/shade.dm
  code/modules/mob/living/simple_mob/subtypes/occult/constructs/wraith.dm
  code/modules/reagents/reagent_containers/blood_pack.dm
  code/modules/reagents/reagent_containers/blood_pack_vr.dm
  icons/mob/cult.dmi
  maps/southern_cross/structures/closets/misc_vr.dm
  vorestation.dme
Labels: Feature, Sprites, Tweak

#2293 Return To Menu - VOREStation/VOREStation#8050 Port
  code/__HELPERS/global_lists.dm
  code/controllers/configuration_old/configuration.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/mob/dead/observer/observer.dm
  code/modules/mob/death.dm
  code/modules/mob/living/silicon/ai/latejoin.dm
  code/modules/mob/mob.dm
  code/modules/mob/new_player/new_player.dm
  config/legacy/config.txt
Labels: Config Update, Refactor, Tweak

#2294 Why the hell do so many people have R&D Access?
  _maps/map_files/Tether/tether-03-surface3.dmm
  code/game/jobs/job/science.dm
Labels: Map Edit, Tweak

#2304 Dark Corners of the Galaxy: The Awakening
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/misc.dm
  code/__DEFINES/traits.dm
  code/_globalvars/misc.dm
  code/_globalvars/traits.dm
  code/datums/components/anti_magic.dm
  code/datums/mind.dm
  code/game/jobs/job/civilian_chaplain.dm
  code/game/objects/items/contraband.dm
  code/game/objects/items/contraband_vr.dm
  code/game/objects/items/weapons/grenades/chem_grenade.dm
  code/game/objects/items/weapons/manuals.dm
  code/game/objects/items/weapons/nullrod.dm
  code/game/objects/items/weapons/storage/backpack.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/shoes/boots.dm
  code/modules/clothing/spacesuits/rig/modules/combat.dm
  code/modules/clothing/spacesuits/rig/suits/ert.dm
  code/modules/clothing/spacesuits/void/station.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/back.dmi
  icons/mob/feet.dmi
  icons/mob/hands.dmi
  icons/mob/head.dmi
  icons/mob/items/lefthand_melee.dmi
  icons/mob/items/righthand_melee.dmi
  icons/mob/rig_back.dmi
  icons/mob/spacesuit.dmi
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/backpack.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/spacesuits.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/weapons.dmi
  vorestation.dme
Labels: Sprites

#2314 Loadout Alphabetization, File Merging, and Cleanup
  code/__HELPERS/global_lists_vr.dm
  code/datums/outfits/jobs/civilian.dm
  code/game/machinery/vending_vr.dm
  code/game/objects/random/maintenance.dm
  code/game/objects/random/random.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/modules/client/preference_setup/loadout/gear_tweaks.dm
  code/modules/client/preference_setup/loadout/gear_tweaks_vr.dm
  code/modules/client/preference_setup/loadout/loadout.dm
  code/modules/client/preference_setup/loadout/loadout_accessories.dm
  code/modules/client/preference_setup/loadout/loadout_accessories_vr.dm
  code/modules/client/preference_setup/loadout/loadout_cosmetics.dm
  code/modules/client/preference_setup/loadout/loadout_donator.dm
  code/modules/client/preference_setup/loadout/loadout_ears.dm
  code/modules/client/preference_setup/loadout/loadout_eyes.dm
  code/modules/client/preference_setup/loadout/loadout_eyes_vr.dm
  code/modules/client/preference_setup/loadout/loadout_general.dm
  code/modules/client/preference_setup/loadout/loadout_gloves.dm
  code/modules/client/preference_setup/loadout/loadout_gloves_vr.dm
  code/modules/client/preference_setup/loadout/loadout_head.dm
  code/modules/client/preference_setup/loadout/loadout_head_vr.dm
  code/modules/client/preference_setup/loadout/loadout_mask.dm
  code/modules/client/preference_setup/loadout/loadout_shoes.dm
  code/modules/client/preference_setup/loadout/loadout_shoes_vr.dm
  code/modules/client/preference_setup/loadout/loadout_smoking.dm
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/client/preference_setup/loadout/loadout_suit_vr.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/client/preference_setup/loadout/loadout_uniform_vr.dm
  code/modules/client/preference_setup/loadout/loadout_utility.dm
  code/modules/client/preference_setup/loadout/loadout_utility_vr.dm
  code/modules/client/preference_setup/loadout/loadout_vr.dm
  code/modules/client/preference_setup/loadout/loadout_xeno.dm
  code/modules/client/preference_setup/loadout/loadout_xeno_vr.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/lore_codex/codex.dm
  code/modules/vore/fluffstuff/custom_boxes.dm
  code/modules/vore/fluffstuff/custom_clothes.dm
  code/modules/vore/fluffstuff/custom_guns.dm
  code/modules/vore/fluffstuff/custom_items.dm
  code/modules/vore/fluffstuff/custom_mecha.dm
  code/modules/vore/fluffstuff/custom_permits.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/vore/custom_clothes_vr.dmi
  maps/southern_cross/loadout/loadout_accessories.dm
  maps/southern_cross/loadout/loadout_head.dm
  maps/southern_cross/loadout/loadout_suit.dm
  maps/southern_cross/loadout/loadout_uniform.dm
  modular_citadel/code/modules/client/preference_setup/loadout/loadout_general_cit.dm
  modular_citadel/code/modules/client/preference_setup/loadout/loadout_shoes_cit.dm
  modular_citadel/code/modules/client/preference_setup/loadout/loadout_suit_cit.dm
  modular_citadel/code/modules/client/preference_setup/loadout/loadout_uniform_cit.dm
  modular_citadel/code/modules/client/preference_setup/loadout/loadout_utility.dm
  vorestation.dme
Labels: Fix, Sprites

#2311 Updates to the ship and overmap generation fixed. Prep for new Shuttle
  _maps/map_files/NSV_Triumph/triumph-01-deck1.dmm
  _maps/map_files/NSV_Triumph/triumph-02-deck2.dmm
  _maps/map_files/NSV_Triumph/triumph-03-deck3.dmm
  _maps/map_files/NSV_Triumph/triumph-04-deck4.dmm
  _maps/map_files/NSV_Triumph/triumph-05-flagship.dmm
  code/__DEFINES/atmospherics/atmospheres.dm
  code/game/area/Space Station 13 areas.dm
  code/modules/events/meteors.dm
  code/modules/maps/tether/atmospheres/gaia_planet.dm
  code/modules/overmap/events/generation.dm
  code/modules/overmap/events/overmap_event.dm
  code/modules/overmap/ships/engines/ion_thruster.dm
  code/modules/planet/gaia_planet.dm
  maps/nsv_triumph/submaps/_triumph_submaps.dm
  maps/nsv_triumph/submaps/gaia_planet/_gaia_planet.dm
  maps/nsv_triumph/submaps/gaia_planet/gaia_planet.dmm
  maps/nsv_triumph/submaps/gaia_planet/gaia_planet_things.dm
  maps/nsv_triumph/submaps/triumph_ships.dmm
  maps/nsv_triumph/triumph_areas2.dm
  maps/nsv_triumph/triumph_defines.dm
  maps/nsv_triumph/triumph_overmap.dm
  maps/nsv_triumph/triumph_shuttles.dm
  nano/images/nanomap_z1.png
  nano/images/nanomap_z1_tether.png
  nano/images/nanomap_z2.png
  nano/images/nanomap_z2_tether.png
  nano/images/nanomap_z3.png
  nano/images/nanomap_z3_tether.png
  nano/images/nanomap_z4.png
  nano/images/nanomap_z4_tether.png
  vorestation.dme
Labels: Code Improvement, Feature, Fix, Map Edit

#2324 [READY] Xenolove: RIGs for Everyone
  code/modules/clothing/spacesuits/rig/rig_pieces.dm
  code/modules/clothing/spacesuits/rig/rig_pieces_vr.dm
  icons/mob/species/phoronoid/head.dmi
  icons/mob/species/phoronoid/suit.dmi
  icons/mob/species/zaddat/head.dmi
  icons/mob/species/zaddat/shoes.dmi
  icons/mob/species/zaddat/suit.dmi
  icons/obj/clothing/species/phoronoid/hats.dmi
  icons/obj/clothing/species/phoronoid/suits.dmi
  icons/obj/clothing/species/zaddat/hats.dmi
  icons/obj/clothing/species/zaddat/suits.dmi
Labels: Needs Review, Sprites

#2317 Asset cache - CitRP Edition
  .gitignore
  code/__DEFINES/configuration.dm
  code/__DEFINES/controllers/_subsystems.dm
  code/__HELPERS/_logging.dm
  code/__HELPERS/files.dm
  code/__HELPERS/icons.dm
  code/__HELPERS/icons_vr.dm
  code/__HELPERS/lists.dm~1fb83e6... Merge pull request #5959 from elgeonmb_suit++
  code/__HELPERS/logging.dm
  code/__HELPERS/logging_vr.dm
  code/__HELPERS/text.dm
  code/__HELPERS/type2type.dm
  code/_globalvars/logging.dm
  code/controllers/configuration/config_entry.dm
  code/controllers/configuration/configuration.dm
  code/controllers/configuration/entries/general.dm
  code/controllers/master.dm
  code/controllers/subsystem.dm
  code/controllers/subsystems/assets.dm
  code/controllers/subsystems/nanoui.dm
  code/datums/browser/_browser.dm
  code/datums/wires/wires.dm
  code/game/objects/items/weapons/id cards/station_ids.dm
  code/game/world.dm
  code/modules/admin/view_variables/topic.dm
  code/modules/asset_cache/asset_cache_client.dm
  code/modules/asset_cache/asset_cache_item.dm
  code/modules/asset_cache/asset_list.dm
  code/modules/asset_cache/asset_list_items.dm
  code/modules/asset_cache/readme.md
  code/modules/asset_cache/transports/asset_transport.dm
  code/modules/asset_cache/transports/webroot_transport.dm
  code/modules/asset_cache/validate_assets.html
  code/modules/client/_security.dm
  code/modules/client/asset_cache.dm
  code/modules/client/client_click.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/client/client_topic.dm
  code/modules/instruments/songs/editor.dm
  code/modules/mapping/minimaps.dm
  code/modules/nano/nanoui.dm
  config/config.txt
  config/resources.txt
  html/admin/panels.css
  html/admin/search.js
  html/ban.png
  html/chrome-wrench.png
  html/coding.png
  html/jquery.min.js
  html/padlock.png
  html/scales.png
  interface/skin.dmf
  vorestation.dme
Labels: Code Improvement, Config Update

#2329 Gonk
  code/modules/mob/living/silicon/robot/emote.dm
  sound/machines/gonk.ogg
Labels: Feature, Sound

#2325 Anotherteshupdate
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/weapons/towels.dm
  code/modules/client/preference_setup/loadout/loadout_accessories.dm
  code/modules/client/preference_setup/loadout/loadout_xeno.dm
  code/modules/clothing/suits/aliens/teshari.dm
  code/modules/clothing/suits/aliens/teshari_vr.dm
  code/modules/clothing/under/accessories/accessory.dm
  code/modules/clothing/under/accessories/clothing.dm
  code/modules/clothing/under/xenos/teshari.dm
  code/modules/mob/living/carbon/human/species/station/teshari.dm
  code/modules/mob/new_player/sprite_accessories_vr.dm
  icons/mob/human_face.dmi
  icons/mob/human_face_m.dmi
  icons/mob/species/teshari/belt.dmi
  icons/mob/species/teshari/ears.dmi
  icons/mob/species/teshari/gloves.dmi
  icons/mob/species/teshari/head.dmi
  icons/mob/species/teshari/masks.dmi
  icons/mob/species/teshari/pda_wrist.dmi
  icons/mob/species/teshari/shoes.dmi
  icons/mob/species/teshari/suit.dmi
  icons/mob/species/teshari/teshari_cloak.dmi
  icons/mob/species/teshari/teshari_cloak_vr.dmi
  icons/mob/species/teshari/teshari_uniform.dmi
  icons/mob/species/teshari/ties.dmi
  icons/mob/species/teshari/uniform.dmi
  icons/obj/clothing/species/teshari/uniform.dmi
  icons/obj/clothing/ties.dmi
  vorestation.dme
Labels: Feature, Fix, Sprites

#2334 RNG placement for ship and POIs on Overmap
  code/modules/overmap/events/overmap_event.dm
  icons/obj/overmap.dmi
  maps/nsv_triumph/triumph_overmap.dm
Labels: Fix, Sprites

#2330 Fixes sounds for some random events: also known as "OH MY GOD MY EARS ARE GONE"
  code/modules/events/cult.dm
  code/modules/events/meteors.dm
Labels: Fix

#2320 Cyber Horror
  code/modules/ai/say_list.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/cyber_horror/cyber_horror.dm
  icons/mob/cyber_horror.dmi
  vorestation.dme
Labels: Sprites

#2315 Dark Corners of the Galaxy: Silver Bullets and Blood Hunters [Merge Ready]
  code/game/objects/items/weapons/material/misc.dm
  code/modules/mob/living/simple_mob/subtypes/humanoid/cultist.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/ammunition/rounds.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/boltaction.dm
  code/modules/projectiles/guns/projectile/contender.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  code/modules/projectiles/guns/projectile/revolver.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/bullets.dm
  icons/mob/cult.dmi
  icons/mob/items/64x64_lefthand.dmi
  icons/mob/items/64x64_righthand.dmi
  icons/mob/items/lefthand_guns.dmi
  icons/mob/items/righthand_guns.dmi
  icons/obj/ammo.dmi
  icons/obj/ammo_vr.dmi
  icons/obj/gun.dmi
Labels: Code Improvement, Feature, Sprites, Tweak

#2333 Removes something that shouldn't have been cleared in any way shape or form
  code/game/jobs/job/security.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/clothing/under/miscellaneous.dm
Labels: Removal

#2326 Dehusking
  code/modules/surgery/external_repair.dm
Labels: Feature, Good First PR

#2340 TeshariScream.ogg
  code/modules/mob/living/carbon/human/species/station/teshari.dm
  sound/effects/mob_effects/teshariscream.ogg
Labels: Sound

#2344 New Frozen Planet and minor Overmap Changes
  code/__DEFINES/atmospherics/atmospheres.dm
  code/modules/maps/tether/atmospheres/frozen_planet.dm
  code/modules/planet/frozen_planet.dm
  maps/nsv_triumph/submaps/_triumph_submaps.dm
  maps/nsv_triumph/submaps/frozen_planet/_frozen_planet.dm
  maps/nsv_triumph/submaps/frozen_planet/_templates.dm
  maps/nsv_triumph/submaps/frozen_planet/frozen_planet.dmm
  maps/nsv_triumph/submaps/frozen_planet/frozen_planet_things.dm
  maps/nsv_triumph/submaps/frozen_planet/ruins1.dmm
  maps/nsv_triumph/submaps/frozen_planet/ruins2.dmm
  maps/nsv_triumph/submaps/frozen_planet/ruins3.dmm
  maps/nsv_triumph/submaps/frozen_planet/ruins4.dmm
  maps/nsv_triumph/submaps/frozen_planet/ruins5.dmm
  maps/nsv_triumph/submaps/gaia_planet/gaia_planet.dmm
  maps/nsv_triumph/triumph_defines.dm
  maps/nsv_triumph/triumph_overmap.dm
  vorestation.dme
Labels: Feature, Tweak

#2345 Security updates to Deck 4 per feedback
  _maps/map_files/NSV_Triumph/triumph-04-deck4.dmm
Labels: Feature, Map Edit, Tweak

#2357 Fixes Teshari Big RIG Boot Bug + Ports EVA RIG Sprites for Sergals, Akula, Nevreans & Nagas
  code/modules/clothing/spacesuits/rig/rig_pieces.dm
  code/modules/clothing/spacesuits/rig/rig_pieces_vr.dm
  icons/mob/species/akula/helmet_vr.dmi
  icons/mob/species/akula/suit_vr.dmi
  icons/mob/species/nevrean/helmet_vr.dmi
  icons/mob/species/nevrean/suit_vr.dmi
  icons/mob/species/sergal/helmet_vr.dmi
  icons/mob/species/sergal/suit_vr.dmi
  icons/mob/taursuits_naga_vr.dmi
Labels: Fix, Good First PR, Sprites

#2336 Miscellaneous Additions/Changes
  code/__DEFINES/species_languages.dm
  code/game/atoms_movable.dm
  code/game/machinery/doors/door.dm
  code/game/objects/effects/decals/crayon.dm
  code/game/objects/items/crayons.dm
  code/game/objects/items/weapons/cosmetics.dm
  code/game/objects/items/weapons/storage/fancy.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/game/turfs/simulated/wall_types_vr.dm
  code/game/turfs/simulated/water.dm
  code/modules/client/preference_setup/loadout/loadout_cosmetics.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/clothing/under/accessories/permits.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/food/food/snacks/meat.dm
  code/modules/materials/material_sheets.dm
  code/modules/materials/materials.dm
  code/modules/mob/language/generic.dm
  code/modules/mob/language/station_vr.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/simple_animal/animals/penguin.dm
  code/modules/mob/living/simple_mob/defense.dm
  code/modules/mob/living/simple_mob/subtypes/animal/passive/penguin.dm
  code/modules/paperwork/pen.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
  code/modules/tables/presets.dm
  icons/mob/human_face.dmi
  icons/mob/submerged.dmi
  icons/mob/uniform.dmi
  icons/obj/card_cit.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/crayons.dmi
  icons/obj/food.dmi
  icons/obj/items.dmi
  icons/turf/outdoors.dmi
  icons/turf/stomach_vr.dmi
  icons/turf/wall_masks.dmi
  maps/southern_cross/southern_cross_jobs.dm
Labels: Sprites

#2327 Optimizes lorecode
  code/__DEFINES/_globals.dm
  code/controllers/subsystems/emergency_shuttle.dm
  code/datums/ai_law_sets.dm
  code/game/machinery/computer/communications.dm
  code/modules/busy_space/air_traffic.dm
  code/modules/busy_space/loremaster.dm
  code/modules/busy_space/organizations.dm
  code/modules/gamemaster/actions/stowaway.dm
  code/modules/gamemaster/actions/swarmboarder.dm
  code/modules/lore_codex/lore_data_vr/orgs.dm
  code/modules/security levels/security levels.dm
Labels: Code Improvement

#2353 Haha airlock stops siphoning the entire cargobay now
  _maps/map_files/NSV_Triumph/triumph-02-deck2.dmm
Labels: Fix, Map Edit

#2343 Raise the Black Flag: Pirate Mobs Just in time for '"Talk Like a Pirate Day"
  code/game/objects/structures/loot_piles.dm
  code/modules/ai/say_list.dm
  code/modules/mob/living/simple_mob/subtypes/humanoid/pirates.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/mecha/ripley.dm
  icons/mecha/mecha.dmi
  icons/mob/mecha.dmi
  icons/mob/pirate.dmi
Labels: Balance/Rebalance, Feature, Sprites, Tweak

#2356 you now have to dragdrop yourself into tram doors to leave instead of bumping into it and literally falling out of the world
  maps/nsv_triumph/triumph_things.dm
  maps/tether/tether_things.dm
Labels: Tweak

#2364 Civvie shuttle 2.0
  _maps/map_files/NSV_Triumph/triumph-04-deck4.dmm
Labels: Map Edit, Tweak

#2361 Tweaks the amount of parameds to fit their lockers because they are nerds
  code/game/jobs/job/medical.dm
Labels: Tweak

#2341 Pizza
  code/game/objects/items/falling_object.dm
  code/game/objects/items/pizza_voucher.dm
  code/game/objects/random/maintenance.dm
  code/game/objects/structures/trash_pile.dm
  code/modules/food/food/snacks.dm
  icons/obj/items.dmi
  vorestation.dme
Labels: Sprites

#2362 Pilot helmets fixed
  code/modules/clothing/head/pilot_helmet.dm
  code/modules/shuttles/shuttle_autodock.dm
  code/modules/shuttles/shuttle_console.dm
  code/modules/shuttles/shuttles_web.dm
Labels: Fix

#2351 goo suiting fetish content
  code/modules/mob/holder.dm
  code/modules/mob/living/carbon/human/species/station/protean_vr/protean_species.dm
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
Labels: Feature, Sprites

#2374 Ports some ram horns from main
  code/modules/vore/appearance/sprite_accessories_vr.dm
  icons/mob/vore/ears_vr.dmi
Labels: Feature, Sprites

#2365 Adds Deanman's helmswoman thingie idk
  code/game/jobs/job/captain.dm
Labels: Feature, Tweak

#2375 updates sdql2 for the 513546th time to support all object datatypes so i can debug the next time the bridge draws 12 KW for no reason and the CE yells at me
  code/modules/admin/verbs/SDQL2/SDQL_2.dm
Labels: Fix, Priority: High

#2370 Cures the Silence of Sergals
  code/modules/mob/language/station_vr.dm
Labels: Fix

#2377 custom names/descriptions in loadout + a few misc items & fixes
  code/defines/obj/weapon.dm
  code/modules/admin/topic.dm
  code/modules/client/preference_setup/loadout/gear_tweaks.dm
  code/modules/client/preference_setup/loadout/loadout.dm
  code/modules/client/preference_setup/loadout/loadout_accessories.dm
  code/modules/client/preference_setup/loadout/loadout_eyes.dm
  code/modules/client/preference_setup/loadout/loadout_general.dm
  code/modules/client/preference_setup/loadout/loadout_gloves.dm
  code/modules/client/preference_setup/loadout/loadout_head.dm
  code/modules/client/preference_setup/loadout/loadout_shoes.dm
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/client/preference_setup/loadout/loadout_utility.dm
  code/modules/client/preference_setup/loadout/loadout_xeno.dm
  code/modules/clothing/glasses/glasses.dm
  icons/mob/eyes.dmi
  icons/mob/human_races/cyberlimbs/unbranded/unbranded_teshari.dmi
  icons/mob/items/lefthand_melee.dmi
  icons/mob/items/righthand_melee.dmi
  icons/mob/species/teshari/eyes.dmi
  icons/obj/clothing/glasses.dmi
  icons/obj/weapons.dmi
Labels: Administration, Code Improvement, Feature, Sprites

#2363 Rebranding!
  icons/CS13.png
  icons/ss13_32.png
  icons/ss13_64.png
  icons/virgoicon.png
  interface/skin.dmf
Labels: Removal, Sprites

#2347 Mercenary Suppressors (alt title: The Plutonia Experience)
  code/game/objects/items/weapons/grenades/concussion.dm
  code/game/objects/items/weapons/grenades/flashbang.dm
  code/modules/ai/say_list.dm
  code/modules/mob/living/simple_animal/humanoids/syndicate.dm
  code/modules/mob/living/simple_mob/subtypes/humanoid/mercs/mercs.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/projectiles/projectile/pellets.dm
  icons/mob/animal.dmi
  icons/obj/grenade.dmi
  sound/weapons/doompistol.ogg
Labels: Config Update, Feature, Fix, Sound, Sprites

#2366 makes r&d weapons start firingpin-less
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/crates_lockers/closets/secure/security_vr.dm
  code/modules/research/designs.dm
  code/modules/research/designs/weapons.dm
Labels: Balance/Rebalance

#2381 Borgi/Otie Port 2.0
  code/modules/mob/living/silicon/robot/robot_modules/station/security.dm
  code/modules/mob/living/silicon/robot/robot_modules/station/service.dm
  code/modules/mob/living/silicon/robot/robot_modules/station_vr.dm
  icons/mob/widerobot_vr.dmi
Labels: Feature, Sprites

#2384 Upgrades and hopefully fixes Travis
  .travis.yml
  README.md
  maps/nsv_triumph/triumph.dm
  maps/tether/tether.dm
  tools/travis/compile_and_run.sh
  tools/travis/install-byond.sh
  tools/travis/validate_files.sh
  vorestation.dme
Labels: Priority: High, Refactor, Tools

#2393 Travis, I love and hate you.
  code/datums/components/fantasy/_fantasy.dm
  code/datums/components/mood.dm
  code/game/atom_vv.dm
  code/game/objects/items/weapons/mop.dm
  code/modules/client/client_procs.dm
  maps/nsv_triumph/triumph.dm
  tools/travis/install_byond.sh
  tools/travis/validate_files.sh
Labels: Fix, Tools

#2383 Avo Fall Fashion Show
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/clothing/spacesuits/void/void.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites

#2388 Eyepatch no Longer Covers Other Eye with Strap
  icons/mob/eyes.dmi
Labels: Fix, Sprites
