Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2020-04, with the labels that each got.

#1747 Food Balance pt 1.5: Added Liquid Protein, and further minor adjustments to current food. also minor tasty borger buffs.
  code/datums/supplypacks/misc_vr.dm
  code/game/machinery/vending.dm
  code/game/objects/items/trash.dm
  code/modules/food/drinkingglass/metaglass.dm
  code/modules/food/food/snacks.dm
  icons/obj/food.dmi
  icons/obj/trash.dmi
Labels: Balance/Rebalance, Feature, PENDING CLOSURE DNM, Sprites

#1751 Cargo Supply Consoles NOW check for ID
  code/game/machinery/computer/supply.dm
Labels: Fix, PENDING CLOSURE DNM

#1752 Minor adjustments to Tether Midpoint
  maps/tether/tether-04-transit.dmm
Labels: Feature, PENDING CLOSURE DNM

#1753 Bar & Kitchen Changes (Map Layout) Otherwise known as: Uhh.. Bar and Kitchen.. changes..
  maps/tether/tether-03-surface3.dmm
Labels: PENDING CLOSURE DNM, Tweak

#1755 Adds access to collector crate
  code/datums/supplypacks/engineering.dm
Labels: Fix, PENDING CLOSURE DNM

#1759 One New Facial Hairstyle, Four New Outfits, Five New Glasses
  code/modules/client/preference_setup/loadout/loadout_eyes.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/mob/new_player/sprite_accessories_vr.dm
  icons/mob/eyes.dmi
  icons/mob/human_face_or_vr.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/glasses.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Feature, PENDING CLOSURE DNM, Sprites

#1760 Fixes Map Rendering Issues
  code/__DEFINES/MC.dm
  code/__DEFINES/ZAS.dm
  code/__DEFINES/_globals.dm
  code/__DEFINES/_lists.dm
  code/__DEFINES/_planes+layers.dm
  code/__DEFINES/_planes+layers_vr.dm
  code/__DEFINES/_tick.dm
  code/__DEFINES/admin.dm
  code/__DEFINES/admin_vr.dm
  code/__DEFINES/appearance.dm
  code/__DEFINES/atmos.dm
  code/__DEFINES/belly_modes_vr.dm
  code/__DEFINES/callbacks.dm
  code/__DEFINES/chemistry.dm
  code/__DEFINES/chemistry_vr.dm
  code/__DEFINES/color.dm
  code/__DEFINES/construction.dm
  code/__DEFINES/damage_organs.dm
  code/__DEFINES/dna.dm
  code/__DEFINES/flags.dm
  code/__DEFINES/gamemode.dm
  code/__DEFINES/holomap.dm
  code/__DEFINES/integrated_circuits.dm
  code/__DEFINES/inventory_storage.dm
  code/__DEFINES/items_clothing.dm
  code/__DEFINES/lighting.dm
  code/__DEFINES/machinery.dm
  code/__DEFINES/map.dm
  code/__DEFINES/map_vr.dm
  code/__DEFINES/math.dm
  code/__DEFINES/math_physics.dm
  code/__DEFINES/maths.dm
  code/__DEFINES/misc.dm
  code/__DEFINES/misc_vr.dm
  code/__DEFINES/mobs.dm
  code/__DEFINES/mobs_vr.dm
  code/__DEFINES/nifsoft.dm
  code/__DEFINES/parameters_world.dm
  code/__DEFINES/planets.dm
  code/__DEFINES/process_scheduler.dm
  code/__DEFINES/qdel.dm
  code/__DEFINES/research.dm
  code/__DEFINES/roguemining_vr.dm
  code/__DEFINES/sound.dm
  code/__DEFINES/species_languages.dm
  code/__DEFINES/species_languages_vr.dm
  code/__DEFINES/stat_tracking.dm
  code/__DEFINES/subsystems.dm
  code/__DEFINES/subsystems_vr.dm
  code/__DEFINES/supply.dm
  code/__DEFINES/targeting.dm
  code/__DEFINES/time.dm
  code/__DEFINES/turfs.dm
  code/__DEFINES/typeids.dm
  code/__DEFINES/unit_tests.dm
  code/__DEFINES/vote.dm
  code/__DEFINES/xenoarcheaology.dm
Labels: PENDING CLOSURE DNM, Tweak

#1761 bandaids around the shitty id system with .Copy()s to prevent stuff from touching the global cache lists
  code/game/jobs/access.dm
Labels: Priority: High

#1765 Adds Bridge Officer outfit, a bunch of sprites, and a Cardigan
  code/modules/client/preference_setup/loadout/loadout_head.dm
  code/modules/client/preference_setup/loadout/loadout_shoes.dm
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/shoes/boots.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/feet.dmi
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites

#1787 PARAMED JACKET TAKE THREE
  code/modules/client/preference_setup/loadout/loadout_head.dm
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/suits/hooded.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/accessories/clothing.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/mob/ties.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/ties.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites

#1788 Pilot Hardsuit, AMI Vox Suit, and Minor Edits
  code/modules/clothing/spacesuits/void/void.dm
  icons/mob/species/vox/gloves.dmi
  icons/mob/species/vox/head.dmi
  icons/mob/species/vox/shoes.dmi
  icons/mob/species/vox/suit.dmi
Labels: Sprites

#1774 shameless protean buff
  code/modules/mob/living/carbon/human/species/station/protean_vr/protean_powers.dm
  code/modules/mob/living/carbon/human/species/station/protean_vr/protean_species.dm
  code/modules/organs/subtypes/nano.dm
  icons/mob/species/protean/protean_powers.dmi
Labels: Sprites

#1806 Revert "New to Initialize pass #1 - Turfs and some random stuff" kevinz doesn't know what DNM is
  code/__DEFINES/color/colour_priority.dm
  code/__DEFINES/misc.dm
  code/__DEFINES/tgs.config.dm
  code/__HELPERS/global_lists.dm
  code/_global_vars/bitfields.dm
  code/controllers/subsystem.dm
  code/controllers/subsystems/air.dm
  code/controllers/subsystems/atoms.dm
  code/controllers/subsystems/xenoarch.dm
  code/game/atoms.dm
  code/game/gamemodes/cult/hell_universe.dm
  code/game/gamemodes/endgame/supermatter_cascade/blob.dm
  code/game/gamemodes/endgame/supermatter_cascade/universe.dm
  code/game/gamemodes/events/wormholes.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/gps.dm
  code/game/objects/objs.dm
  code/game/turfs/simulated.dm
  code/game/turfs/simulated/dungeon/wall.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/outdoors/outdoors.dm
  code/game/turfs/simulated/wall_types.dm
  code/game/turfs/simulated/wall_types_vr.dm
  code/game/turfs/simulated/walls.dm
  code/game/turfs/space/space.dm
  code/game/turfs/space/transit.dm
  code/game/turfs/turf.dm
  code/game/turfs/unsimulated.dm
  code/game/turfs/unsimulated/beach.dm
  code/game/turfs/unsimulated/planetary.dm
  code/modules/admin/verbs/adminjump.dm
  code/modules/admin/verbs/atmosdebug.dm
  code/modules/admin/verbs/grief_fixers.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/holodeck/HolodeckObjects.dm
  code/modules/lighting/lighting_turf.dm
  code/modules/mob/freelook/update_triggers.dm
  code/modules/telesci/construction.dm
  code/modules/telesci/gps_advanced.dm
  code/modules/turbolift/turbolift_turfs.dm
  maps/tether/tether_turfs.dm
  maps/~map_system/maps.dm
  vorestation.dme
Labels: Revert

#1808 [WIP] FIXED VERSION OF NEW TO INITIALIZE PASS
  code/__DEFINES/color/colour_priority.dm
  code/__DEFINES/misc.dm
  code/__DEFINES/tgs.config.dm
  code/__HELPERS/global_lists.dm
  code/_global_vars/bitfields.dm
  code/controllers/subsystem.dm
  code/controllers/subsystems/air.dm
  code/controllers/subsystems/atoms.dm
  code/controllers/subsystems/xenoarch.dm
  code/datums/mind.dm
  code/game/atoms.dm
  code/game/gamemodes/cult/hell_universe.dm
  code/game/gamemodes/endgame/supermatter_cascade/blob.dm
  code/game/gamemodes/endgame/supermatter_cascade/universe.dm
  code/game/gamemodes/events/wormholes.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/gps.dm
  code/game/objects/objs.dm
  code/game/turfs/flooring/flooring_decals.dm
  code/game/turfs/simulated.dm
  code/game/turfs/simulated/dungeon/wall.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/outdoors/outdoors.dm
  code/game/turfs/simulated/wall_types.dm
  code/game/turfs/simulated/wall_types_vr.dm
  code/game/turfs/simulated/walls.dm
  code/game/turfs/space/space.dm
  code/game/turfs/space/transit.dm
  code/game/turfs/turf.dm
  code/game/turfs/unsimulated.dm
  code/game/turfs/unsimulated/beach.dm
  code/game/turfs/unsimulated/planetary.dm
  code/modules/admin/verbs/adminjump.dm
  code/modules/admin/verbs/atmosdebug.dm
  code/modules/admin/verbs/grief_fixers.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/holodeck/HolodeckObjects.dm
  code/modules/instruments/songs/editor.dm
  code/modules/lighting/lighting_turf.dm
  code/modules/mob/freelook/update_triggers.dm
  code/modules/mob/living/carbon/human/species/station/plasmen.dm
  code/modules/telesci/construction.dm
  code/modules/telesci/gps_advanced.dm
  code/modules/turbolift/turbolift_turfs.dm
  maps/tether/tether_turfs.dm
  maps/~map_system/maps.dm
  vorestation.dme
Labels: Work in Progress

#1796 Little Bit of The Bubbly - Available now at LilBitOfTheBubbly
  code/game/machinery/vending.dm
  code/modules/food/drinkingglass/metaglass.dm
  code/modules/food/food/drinks/bottle.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  icons/obj/drinks.dmi
Labels: Sprites

#1798 PARAMEDIC JACKET SPEEDFIX
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/clothing/under/accessories/clothing.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/ties.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/ties.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites

#1804 Takes Bay Frame Port from Upstream
  icons/obj/stock_parts.dmi
Labels: Sprites

#1805 Updates Vent and Scrubber Sprites to Virgo Version
  icons/atmos/vent_pump.dmi
  icons/atmos/vent_scrubber.dmi
  icons/obj/atmospherics/vent_pump.dmi
  icons/obj/atmospherics/vent_scrubber.dmi
  icons/obj/pipe-item.dmi
Labels: Sprites

#1802 Poncho Fix for Vox and Tesh
  code/modules/clothing/under/accessories/accessory.dm
  code/modules/clothing/under/accessories/clothing.dm
  icons/mob/species/vox/ties.dmi
Labels: Sprites

#1814 Removes the AI shell restriction
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Removal

#1812 OKAY, THE ACTUAL PARA FIX
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/clothing/suits/jobs.dm
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites

#1815 Fixing LiquidProtein Sprite cause whoopsy daisy.
  code/modules/food/food/snacks.dm
Labels: Tweak

#1818 Minor Map Adjustments, honk.
  maps/tether/tether-02-surface2.dmm
Labels: Feature, Tweak

#1801 *meow
  code/modules/mob/living/carbon/human/emote.dm
  sound/voice/meow1.ogg
Labels: Sound

#1820 BACON IS BACK oh yeah I guess this also fixes drinks not having sprites and brings back the chain of command
  code/game/objects/items/weapons/melee/misc.dm
  code/modules/fishing/fishing_rod.dm
  icons/obj/drinks.dmi
  icons/obj/food.dmi
  icons/obj/food_custom.dmi
  icons/obj/food_ingredients.dmi
Labels: Sprites

#1839 More Minor Map Fixing, Also Round-Start Spawn Locations for Science Team
  maps/tether/tether-02-surface2.dmm
  maps/tether/tether-03-surface3.dmm
Labels: Feature, Tweak

#1841 field medics are infact part of medical (all exploration roles now appear in their respective 'master' departments on manifest as well)
  code/game/jobs/jobs.dm
Labels: Tweak

#1842 OOC is infact allowed while voting
  code/game/verbs/ooc.dm
Labels: Tweak

#1845 turns down weather sounds
  code/datums/looping_sounds/weather_sounds.dm
Labels: Tweak

#1844 moves ZAS from code\ATMOSPHERICS to code\modules\atmospherics because no you don't deserve a top level folder that makes me have to scroll
  code/__DEFINES/atmospherics.dm
  code/modules/atmospherics/_atmos_setup.dm
  code/modules/atmospherics/_atmospherics_helpers.dm
  code/modules/atmospherics/atmospherics.dm
  code/modules/atmospherics/components/binary_devices/algae_generator_vr.dm
  code/modules/atmospherics/components/binary_devices/binary_atmos_base.dm
  code/modules/atmospherics/components/binary_devices/circulator.dm
  code/modules/atmospherics/components/binary_devices/dp_vent_pump.dm
  code/modules/atmospherics/components/binary_devices/passive_gate.dm
  code/modules/atmospherics/components/binary_devices/passive_gate_vr.dm
  code/modules/atmospherics/components/binary_devices/pipeturbine.dm
  code/modules/atmospherics/components/binary_devices/pump.dm
  code/modules/atmospherics/components/binary_devices/volume_pump.dm
  code/modules/atmospherics/components/omni_devices/_omni_extras.dm
  code/modules/atmospherics/components/omni_devices/filter.dm
  code/modules/atmospherics/components/omni_devices/mixer.dm
  code/modules/atmospherics/components/omni_devices/omni_base.dm
  code/modules/atmospherics/components/portables_connector.dm
  code/modules/atmospherics/components/trinary_devices/filter.dm
  code/modules/atmospherics/components/trinary_devices/mixer.dm
  code/modules/atmospherics/components/trinary_devices/trinary_base.dm
  code/modules/atmospherics/components/tvalve.dm
  code/modules/atmospherics/components/unary/cold_sink.dm
  code/modules/atmospherics/components/unary/generator_input.dm
  code/modules/atmospherics/components/unary/heat_exchanger.dm
  code/modules/atmospherics/components/unary/heat_source.dm
  code/modules/atmospherics/components/unary/outlet_injector.dm
  code/modules/atmospherics/components/unary/oxygen_generator.dm
  code/modules/atmospherics/components/unary/unary_base.dm
  code/modules/atmospherics/components/unary/vent_pump.dm
  code/modules/atmospherics/components/unary/vent_scrubber.dm
  code/modules/atmospherics/components/unary/vent_scrubber_vr.dm
  code/modules/atmospherics/components/valve.dm
  code/modules/atmospherics/datum_pipe_network.dm
  code/modules/atmospherics/datum_pipeline.dm
  code/modules/atmospherics/mainspipe.dm
  code/modules/atmospherics/pipes/cap.dm
  code/modules/atmospherics/pipes/he_pipes.dm
  code/modules/atmospherics/pipes/manifold.dm
  code/modules/atmospherics/pipes/manifold4w.dm
  code/modules/atmospherics/pipes/pipe_base.dm
  code/modules/atmospherics/pipes/simple.dm
  code/modules/atmospherics/pipes/tank.dm
  code/modules/atmospherics/pipes/universal.dm
  code/modules/atmospherics/pipes/vent.dm
  vorestation.dme
Labels: Code Improvement

#1823 SecTech Change (minor adjustment)
  code/game/machinery/vending.dm
Labels: Tweak

#1833 F
  icons/obj/clothing/uniforms.dmi
Labels: Sprites

#1843 Removing birds from garden to stop eating the fish, weh.
  maps/tether/tether-02-surface2.dmm
Labels: Removal

#1861 Space spice.
  maps/tether/tether-03-surface3.dmm
Labels: Feature

#1827 Makes default config use 0.5 ticklag instead of 0.6
  config/legacy/config.txt
Labels: Config Update

#1852 Fixes SDQL2 global proccalling
  code/modules/admin/verbs/SDQL2/SDQL_2.dm
Labels: Priority: High

#1850 Brings nanopaste functionality back to pre-hardsync.
  code/game/objects/items/stacks/nanopaste.dm
Labels: Feature

#1855 [DCS] Removes mob login observation event to be replaced with login/logout signals
  code/__DEFINES/dcs/signals.dm
  code/datums/observation/logged_in.dm
  code/modules/mob/login.dm
  code/modules/mob/logout.dm
  code/modules/mob/new_player/login.dm
  code/modules/mob/new_player/login_vr.dm
  vorestation.dme
Labels: Removal

#1857 victorian suits, making the hudpatch not just a normal eyepatch, and fixes
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/clothing/glasses/hud_vr.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/eyes.dmi
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/glasses.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites

#1860 DS9 Outfits for Vox
  code/modules/vore/fluffstuff/custom_clothes_vr.dm
  icons/mob/species/vox/suit.dmi
  icons/mob/species/vox/uniform.dmi
Labels: Sprites

#1863 Scarves, Armbands, Webbings, and Holsters Oh Skrek
  icons/mob/species/vox/ties.dmi
Labels: Sprites

#1864 Buffs the Fuel Rod Cannon
  code/modules/projectiles/projectile/magnetic.dm
Labels: Balance/Rebalance

#1865 S
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites

#1866 Fishing & Food tweaks pt 3: Otherwise known as, :agony:
  code/game/objects/items/weapons/storage/boxes.dm
  code/game/objects/items/weapons/storage/boxes_vr.dm
  code/modules/food/food/snacks.dm
  maps/tether/tether-02-surface2.dmm
Labels: Feature, Tweak

#1867 readds machetes to sar lockers
  maps/southern_cross/structures/closets/misc_vr.dm
Labels: Feature

#1868 Minimaps
  code/controllers/configuration/entries/general.dm
  code/controllers/subsystems/minimaps.dm
  code/game/area/areas.dm
  code/modules/client/verbs/minimap.dm
  code/modules/mapping/minimaps.dm
  config/config.txt
  html/blank.png
  vorestation.dme
Labels: Config Update, Feature

#1872 fixes saber and can of worms having no icons
  code/game/objects/items/weapons/melee/melee.dm
  code/game/objects/items/weapons/melee/misc.dm
  code/game/objects/random/_random.dm
  icons/obj/food.dmi
Labels: Sprites

#1879 gravgog fix
  icons/mob/eyes.dmi
  icons/obj/clothing/glasses.dmi
Labels: Fix, Sprites

#1873 fixes the ticker a bit, improves it just a bit
  code/__DEFINES/controllers/_subsystems.dm
  code/__DEFINES/controllers/ticker.dm
  code/__DEFINES/gamemode.dm
  code/__DEFINES/subsystems_vr.dm
  code/__HELPERS/roundend.dm
  code/controllers/configuration/entries/lobby.dm
  code/controllers/subsystems/ticker.dm
  code/datums/looping_sounds/_looping_sound.dm
  code/datums/looping_sounds/weather_sounds.dm
  code/game/response_team.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/mob/new_player/new_player.dm
  config/config.txt
  config/entries/lobby.txt
  interface/stylesheet.dm
  sound/announcer/classic/aimalf.ogg
  sound/announcer/classic/aliens.ogg
  sound/announcer/classic/animes.ogg
  sound/announcer/classic/attention.ogg
  sound/announcer/classic/commandreport.ogg
  sound/announcer/classic/granomalies.ogg
  sound/announcer/classic/intercept.ogg
  sound/announcer/classic/ionstorm.ogg
  sound/announcer/classic/meteors.ogg
  sound/announcer/classic/newAI.ogg
  sound/announcer/classic/outbreak5.ogg
  sound/announcer/classic/outbreak7.ogg
  sound/announcer/classic/poweroff.ogg
  sound/announcer/classic/poweron.ogg
  sound/announcer/classic/radiation.ogg
  sound/announcer/classic/shuttlecalled.ogg
  sound/announcer/classic/shuttledock.ogg
  sound/announcer/classic/shuttlerecalled.ogg
  sound/announcer/classic/spanomalies.ogg
  sound/announcer/classic/welcome.ogg
  sound/announcer/medibot/aliens.ogg
  sound/announcer/medibot/animes.ogg
  sound/announcer/medibot/attention.ogg
  sound/announcer/medibot/commandreport.ogg
  sound/announcer/medibot/granomalies.ogg
  sound/announcer/medibot/intercept.ogg
  sound/announcer/medibot/ionstorm.ogg
  sound/announcer/medibot/meteors.ogg
  sound/announcer/medibot/newAI.ogg
  sound/announcer/medibot/outbreak5.ogg
  sound/announcer/medibot/outbreak7.ogg
  sound/announcer/medibot/poweroff.ogg
  sound/announcer/medibot/poweron.ogg
  sound/announcer/medibot/radiation.ogg
  sound/announcer/medibot/shuttlecalled.ogg
  sound/announcer/medibot/shuttledocked.ogg
  sound/announcer/medibot/shuttlerecalled.ogg
  sound/announcer/medibot/spanomalies.ogg
  sound/announcer/medibot/welcome.ogg
  vorestation.dme
Labels: Config Update, Sound

#1882 Fixes a bunch of stuff
  code/_onclick/click.dm
  code/_onclick/item_attack.dm
  code/game/atoms_movable_movement.dm
  code/game/objects/items/devices/spy_bug.dm
  code/game/objects/items/weapons/autopsy.dm
  code/game/objects/items/weapons/improvised_components.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/detectivework/tools/evidencebag.dm
  code/modules/detectivework/tools/uvlight.dm
  code/modules/mining/shelter_atoms.dm
  code/modules/mining/shelter_atoms_vr.dm
  code/modules/mining/shelters.dm
  code/modules/mob/living/carbon/human/human_species.dm
  code/modules/mob/living/carbon/human/human_species_vr.dm
  code/modules/multiz/movement.dm
  code/modules/multiz/movement_vr.dm
  code/modules/multiz/structures.dm
  code/modules/projectiles/guns/launcher/crossbow.dm
  code/modules/surgery/surgery.dm
  code/modules/tables/interactions.dm
  code/modules/tables/tables.dm
  code/modules/telesci/telesci_computer.dm
  icons/mob/mask.dmi
Labels: Sprites

#1880 Changes gyrotron circuitboard to gyrotron control board
  code/datums/supplypacks/engineering.dm
Labels: Tweak

#1888 i fucking hate how tg changed how hands worked
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites

#1869 If the Phoron Bore is so good, why isn't there a Phoron Bore 2?
  code/modules/mining/vertibore.dm
  code/modules/power/cell.dm
  code/modules/projectiles/guns/magnetic/bore.dm
  code/modules/projectiles/projectile/magnetic.dm
  code/modules/research/designs/mining_toys.dm
  icons/obj/mining.dmi
  icons/obj/railgun.dmi
  vorestation.dme
Labels: Feature, Sprites

#1892 carbon dioxide breathing people get a co2 tank
  code/game/objects/items/weapons/tanks/tank_types.dm
  icons/obj/tank_vr.dmi
Labels: Sprites

#1885 makes sm weapons do 150 armorpiercing damage
  code/game/objects/items/weapons/material/material_weapons.dm
Labels: Balance/Rebalance

#1887 Buffs Morphium in line with its rarity
  code/modules/materials/materials.dm
Labels: Balance/Rebalance, Do Not Merge

#1883 New Supply Pack - Vampire Care Package
  code/datums/supplypacks/hospitality_vr.dm
  code/game/objects/structures/crates_lockers/closets/coffin.dm
  code/modules/reagents/reagent_containers/blood_pack_vr.dm
Labels: Feature

#1886 config entry fix for gamemode vote
  code/controllers/configuration/entries/lobby.dm
Labels: Config Update

#1884 Wiki links replacement
  config/legacy/config.txt
  html/changelog.html
  html/templates/header.html
Labels: Config Update, Feature, Fix
