Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2020-11, with the labels that each got.

#2447 Airlock Map Helpers are nice
  _maps/map_files/triumph/triumph-01-deck1.dmm
  _maps/map_files/triumph/triumph-03-deck3.dmm
  _maps/map_files/triumph/triumph-04-deck4.dmm
  code/__DEFINES/tgs.dm
  code/modules/mapping/map_helpers/_map_helpers.dm
  code/modules/mapping/map_helpers/airlock.dm
  code/modules/mapping/map_helpers/baseturf.dm
  code/modules/mapping/map_helpers/network_builder/_network_builder.dm
  code/modules/mapping/map_helpers/network_builder/atmos_pipe.dm
  code/modules/mapping/map_helpers/network_builder/power_cable.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/tgs/core/datum.dm
  code/modules/tgs/v3210/api.dm
  code/modules/tgs/v4/api.dm
  code/modules/tgs/v5/api.dm
  icons/map/mapping_helpers.dmi
  icons/obj/airlock_machines.dmi
  maps/nsv_triumph/submaps/triumph_misc.dmm
  maps/nsv_triumph/triumph_areas.dm
  maps/nsv_triumph/triumph_shuttles.dm
  maps/nsv_triumph/triumph_things.dm
  vorestation.dme
Labels: Feature, Map Edit, Sprites

#2459 belting is cringe but what can you do: shuttle goes faster, ore yields/spread buff, bores no pin required, etc
  code/modules/clothing/under/accessories/holster.dm
  code/modules/mining/ore_datum.dm
  code/modules/mining/ore_redemption_machine/equipment_vendor.dm
  code/modules/projectiles/guns/magnetic/bore.dm
  maps/nsv_triumph/triumph_shuttle_defs.dm
Labels: Balance/Rebalance, Feature, Tweak

#2450 Adds Stun Swords
  _maps/map_files/triumph/triumph-04-deck4.dmm
  code/game/objects/items/weapons/stunbaton.dm
  code/modules/overmap/ships/computers/helm.dm
  icons/obj/weapons.dmi
Labels: Currently Testmerged, Map Edit, Sprites

#2417 protean rigs/protean fixes
  code/__HELPERS/global_lists_vr.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/clothing/spacesuits/rig/rig_attackby.dm
  code/modules/clothing/spacesuits/rig/suits/alien.dm
  code/modules/mob/living/carbon/human/species/station/protean/protean_blob.dm
  code/modules/mob/living/carbon/human/species/station/protean/protean_species.dm
  code/modules/mob/living/silicon/robot/dogborg/dog_sleeper_vr.dm
  code/modules/vore/eating/bellymodes_vr.dm
  code/modules/vore/eating/living_vr.dm
  icons/mob/feet.dmi
  icons/mob/hands.dmi
  icons/mob/head.dmi
  icons/mob/rig_back.dmi
  icons/mob/spacesuit.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/spacesuits.dmi
  icons/obj/rig_modules.dmi
Labels: Currently Testmerged, Feature, Fix, Sprites

#2464 New 7.62 Ammo & Phase Bolt fix
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/ammunition/rounds.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/projectiles/projectile/energy.dm
Labels: Currently Testmerged, Feature, Fix

#2465 Exploration Gimmick Packs
  code/game/machinery/vending.dm
  code/game/machinery/vending_vr.dm
  code/game/objects/items/weapons/shields.dm
  code/game/objects/items/weapons/storage/lockbox.dm
  code/game/objects/structures/crates_lockers/closets/secure/explorer.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/mining/ore_redemption_machine/mine_point_items.dm
  code/modules/mining/ore_redemption_machine/survey_vendor.dm
  icons/mob/feet.dmi
  icons/mob/head.dmi
  icons/mob/items/lefthand_melee.dmi
  icons/mob/items/righthand_melee.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/weapons.dmi
  vorestation.dme
Labels: Currently Testmerged, Sprites

#2466 beartraps upgraded
  code/game/objects/items/weapons/traps.dm
Labels: Currently Testmerged, Tweak

#2467 Closes #2463
  code/modules/reagents/Chemistry-Machinery.dm
Labels: Currently Testmerged

#2468 Closes #2413
  code/datums/outfits/jobs/command.dm
Labels: Currently Testmerged

#2476 Adds soulcatchers to NIFs by default
  code/modules/nifsoft/nif.dm
Labels: Feature

#2469 Fixes the Civilian Shuttle
  _maps/map_files/triumph/triumph-04-deck4.dmm
Labels: Currently Testmerged, Map Edit

#2475 Fixes soulcatcher mobs not being able to understand AIs
  code/modules/mob/living/carbon/brain/brain.dm
Labels: Currently Testmerged, Fix

#2474 soulcatchers: text formatting, better range for AR
  code/modules/nifsoft/software/13_soulcatcher.dm
Labels: Currently Testmerged, Fix, Tweak

#2478 fixes clientside keybinds minus T/O/M because those are the usual hardbinds for communication macros
  code/controllers/subsystems/input.dm
Labels: Currently Testmerged

#2470 CMF - Mining Transit Rework
  _maps/map_files/triumph/triumph-02-deck2.dmm
  maps/nsv_triumph/submaps/triumph_ships.dmm
  maps/nsv_triumph/triumph_areas2.dm
  maps/nsv_triumph/triumph_overmap.dm
  maps/nsv_triumph/triumph_shuttles.dm
Labels: Currently Testmerged, Map Edit

#2479 Pathfinders need normal-looking IDs.
  code/game/objects/items/weapons/id cards/sprite_stacks_cit.dm
Labels: Currently Testmerged, Fix

#2487 encourages interdepartmental cooperation
  code/datums/autolathe/arms.dm
  code/game/objects/structures/crates_lockers/closets/secure/explorer.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/ammunition/rounds.dm
  code/modules/projectiles/guns/projectile/caseless.dm
  code/modules/research/designs/weapons.dm
  maps/southern_cross/structures/closets/misc_vr.dm
Labels: Balance/Rebalance, Currently Testmerged

#2485 the "Use Your Eyes" update for mining: sand digging speed and yields, feedback messages mostly removed, ripley drill faster
  code/__DEFINES/mobs.dm
  code/game/mecha/equipment/tools/tools.dm
  code/game/objects/items/weapons/storage/bags.dm
  code/modules/mining/drilling/scanner.dm
  code/modules/mining/mine_items.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mining/satchel_ore_boxdm.dm
Labels: Currently Testmerged, Tweak

#2488 Maybe fixes default soulcatchers?
  code/modules/nifsoft/nif.dm
Labels: Fix, Removal

#2489 removes disarm harmbatonning
  code/game/objects/items/weapons/stunbaton.dm
Labels: Currently Testmerged, Removal

#2482 monkey patches in pixel shifting for soulcatcher projections
  code/modules/nifsoft/software/13_soulcatcher.dm
Labels: Currently Testmerged

#2480 fixes an issue with autonomous rig forcemove (alt title: a pr i thought got closed ACTUALLY got merged instead whoops)
  code/modules/clothing/spacesuits/rig/rig.dm
Labels: Currently Testmerged, Fix

#2491 Adds Shibari Undershirt Option
  code/datums/underwear/undershirts.dm
  icons/mob/human.dmi
Labels: Currently Testmerged, Sprites

#2492 Null Rod Tweaks/Buff
  code/game/objects/items/weapons/nullrod.dm
  code/modules/mob/living/simple_mob/subtypes/humanoid/cultist.dm
Labels: Currently Testmerged

#2494 something about slowdowns and item_slowdown_modifiers
  code/modules/mob/living/carbon/human/human_movement.dm
Labels: Balance/Rebalance, Currently Testmerged

#2496 Multiple issue fixes
  code/game/machinery/biogenerator.dm
  code/modules/clothing/chameleon.dm
  code/modules/reagents/reagent_containers/borghydro.dm
Labels: Currently Testmerged, Fix

#2495 Minor Tweaks and Updates - November Edition
  _maps/map_files/triumph/triumph-04-deck4.dmm
  code/datums/outfits/spec_op.dm
  code/game/objects/items/weapons/id cards/station_ids.dm
  code/game/objects/items/weapons/shields.dm
  code/game/objects/items/weapons/storage/belt.dm
  icons/obj/drinks.dmi
Labels: Currently Testmerged, Map Edit, Sprites

#2486 MAKES SPACE NOT ROOM TEMPERATURE
  code/game/turfs/space/space.dm
Labels: Currently Testmerged, FUCK, Priority: High

#2499 I Could Make You Care
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Currently Testmerged, Feature, Sprites

#2501 Enhanced Synth/Protogen Colouration & Enhances Snoot Boopability
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_races/cyberlimbs/c-tech/c_beast.dmi
  icons/mob/human_races/markings.dmi
Labels: Currently Testmerged, Sprites, Tweak

#2493 high-frequency machete ported from /vg/ because i thought it looked cool
  code/game/objects/items/weapons/melee/energy.dm
  code/game/sound.dm
  code/modules/clothing/under/accessories/holster.dm
  code/modules/projectiles/guns/projectile/caseless.dm
  icons/mob/items/lefthand_melee.dmi
  icons/mob/items/righthand_melee.dmi
  icons/obj/weapons.dmi
  sound/weapons/hf_machete/hfmachete0.ogg
  sound/weapons/hf_machete/hfmachete1.ogg
  sound/weapons/hf_machete/hfmachete_throw01.ogg
  sound/weapons/hf_machete/hfmachete_throw02.ogg
  sound/weapons/hf_machete/hfmachete_throw03.ogg
  sound/weapons/hf_machete/hfmachete_throw_hit01.ogg
  sound/weapons/hf_machete/hfmachete_throw_hit02.ogg
  sound/weapons/hf_machete/hfmachete_throw_hit03.ogg
  sound/weapons/hf_machete/machete_hit01.ogg
  sound/weapons/hf_machete/machete_hit02.ogg
  sound/weapons/hf_machete/machete_hit03.ogg
  sound/weapons/hf_machete/machete_hit04.ogg
  sound/weapons/hf_machete/machete_hit05.ogg
  sound/weapons/hf_machete/machete_hit06.ogg
  sound/weapons/hf_machete/machete_hit07.ogg
  sound/weapons/hf_machete/machete_hit08.ogg
  sound/weapons/hf_machete/machete_hit09.ogg
  sound/weapons/hf_machete/machete_hit10.ogg
Labels: Currently Testmerged, Feature, Sound, Sprites

#2504 Intern Reassignment Initiative
  code/game/jobs/job/assistant.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/exploration.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
Labels: Currently Testmerged

#2502 Central Command Shuttle and Pre-Staging
  _maps/map_files/triumph/triumph-02-deck2.dmm
  _maps/map_files/triumph/triumph-04-deck4.dmm
  _maps/map_files/triumph/triumph-05-flagship.dmm
Labels: Currently Testmerged, Map Edit

#2500 fixes some missing pixels on the demisock sprites
  icons/mob/human_races/markings.dmi
Labels: Currently Testmerged, Fix, Sprites

#2508 fixes floorlights
  code/game/machinery/floor_light.dm
Labels: Fix

#2507 fixes simple_mob ai but actually this time
  code/modules/ai/ai_holder.dm
  code/modules/ai/ai_holder_disabled.dm
  code/modules/mob/living/logout.dm
Labels: Currently Testmerged, Fix

#2512 fixes engineering tape
  code/game/objects/items/weapons/barrier_tape.dm
Labels: Currently Testmerged, Fix

#2514 fixes the cult sound volume
  code/modules/events/cult.dm
  code/modules/security levels/security levels.dm
Labels: Currently Testmerged, Fix

#2520 Adjusts teshari balance
  code/modules/mob/living/carbon/human/species/station/teshari.dm
Labels: Balance/Rebalance, Currently Testmerged

#2515 this should not have compiled
  code/game/objects/items/weapons/nullrod.dm
Labels: Currently Testmerged

#2516 shuttles can no longer crush ghosts ai eyes and other technical mobs
  code/modules/shuttles/shuttle.dm
Labels: Currently Testmerged

#2518 stops protean statpanel change on blobform change
  code/modules/mob/living/carbon/human/species/station/protean/protean_blob.dm
Labels: Currently Testmerged

#2519 fixes protean blobform material consumption whitelist
  code/modules/mob/living/carbon/human/species/station/protean/protean_blob.dm
Labels: Currently Testmerged

#2517 hair shapeshifting no longer balds you on cancel
  code/modules/mob/living/carbon/human/species/species_shapeshift.dm
Labels: Currently Testmerged

#2522 Ports shoe update from polaris/virgo
  code/datums/supplypacks/costumes.dm
  code/game/machinery/biogenerator.dm
  code/game/machinery/vending.dm
  code/game/objects/random/maintenance.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/game/objects/structures/loot_piles.dm
  code/game/objects/structures/trash_pile.dm
  code/modules/client/preference_setup/loadout/loadout_shoes.dm
  code/modules/clothing/shoes/boots.dm
  code/modules/clothing/shoes/colour.dm
  code/modules/clothing/shoes/miscellaneous.dm
  icons/mob/feet.dmi
  icons/mob/items/lefthand_shoes.dmi
  icons/mob/items/righthand_shoes.dmi
  icons/obj/clothing/shoes.dmi
Labels: Currently Testmerged, Feature, Sprites

#2526 fixes soulcatcher souls not being wiped on non admin-ghost, as well as runtimes from processing clientless mobs
  code/modules/nifsoft/software/13_soulcatcher.dm
Labels: Currently Testmerged, Priority: High

#2527 buffs teshari brute/burn damage resistaances to 10% vuln instead of 35%, and item slowdown mod to 1.25 from 2
  code/modules/mob/living/carbon/human/species/station/teshari.dm
Labels: Balance/Rebalance, Currently Testmerged

#2528 nerfs berserk from -1 slowdown to -0.75 giving avg 8 tiles runspeed instead of 10
  code/modules/mob/_modifiers/modifiers_misc.dm
Labels: Balance/Rebalance, Currently Testmerged

#2529 translocator malfunctions to unreachable locations now just puts it on recharge for 10 seconds instead of succeeding
  code/modules/vore/fluffstuff/custom_items.dm
Labels: Currently Testmerged, FUCK, Fix, Priority: High
