Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2020-06, with the labels that each got.

#2053 how the hell did this compile
  code/game/objects/items/weapons/RCD.dm
Labels: Priority: High

#2058 What the fuck
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
Labels: Priority: High

#2081 Exploration Shuttle Fix - No longer grabbing space and clouds on trips.
  maps/tether/submaps/aerostat/aerostat.dmm
  maps/tether/submaps/alienship/alienship.dmm
  maps/tether/submaps/beach/beach.dmm
Labels: Fix

#2080 Removes Long Distance Transmission from Inducers
  code/game/objects/items/weapons/inducer.dm
Labels: Removal

#2083 skeleton port of zlevel management system, staging to phase out map datums with map config and ztraits
  _maps/tether.json
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/maps.dm
  code/__DEFINES/misc.dm
  code/controllers/subsystems/mapping.dm
  code/modules/mapping/map_orientation_patterns.dm
  code/modules/mapping/map_template.dm
  code/modules/mapping/mapping_helpers/_mapping_helpers.dm
  code/modules/mapping/mapping_helpers/baseturf.dm
  code/modules/mapping/mapping_helpers/network_builder/_network_builder.dm
  code/modules/mapping/mapping_helpers/network_builder/atmos_pipe.dm
  code/modules/mapping/mapping_helpers/network_builder/power_cable.dm
  code/modules/mapping/preloader.dm
  code/modules/mapping/reader.dm
  code/modules/mapping/ruins.dm
  code/modules/mapping/space_management/multiz_helpers.dm
  code/modules/mapping/space_management/space_level.dm
  code/modules/mapping/space_management/space_reservation.dm
  code/modules/mapping/space_management/space_transition.dm
  code/modules/mapping/space_management/traits.dm
  code/modules/mapping/space_management/zlevel_manager.dm
  code/modules/mapping/verify.dm
  code/modules/maps/tg/map_template.dm
  icons/map/maploader_objects.dmi
  icons/map/mapping_helpers.dmi
  maps/tether/submaps/_tether_submaps.dm
  vorestation.dme
Labels: Map Edit, Sprites

#2091 fixes people not spawning with oxygen tanks
  code/modules/mob/living/carbon/human/species/species.dm
Labels: Priority: High

#2096 fixes vox breathtypes
  code/modules/mob/living/carbon/human/species/outsider/vox.dm
Labels: Priority: High

#2098 fixes large air internal tanks spawning with bad gas ids
  code/game/objects/items/weapons/tanks/tank_types.dm
Labels: Priority: High

#2099 Fixes supermatter polluting the environment with phantom gases
  code/modules/power/supermatter/supermatter.dm
Labels: Priority: High

#2102 Fixes what I broke
  modular_citadel/icons/mob/hud_jobs_cit.dmi
Labels: Fix, Sprites

#1995 potentially fixes ore box dragging by silicons
  code/modules/mining/mine_turfs.dm
Labels: Test Merge Candidate

#2088 Tesh additions 1
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/clothing/rings/rings.dm
  icons/mob/species/seromi/ears.dmi
  icons/mob/species/seromi/eyes.dmi
  icons/mob/species/seromi/gloves.dmi
  icons/mob/species/seromi/ties.dmi
  icons/mob/species/seromi/uniform.dmi
Labels: Feature, Fix, Sprites, Tweak

#2093 Misc Tweaks
  code/datums/uplink/ammunition.dm
  code/datums/uplink/medical_vr.dm
  code/datums/uplink/tools_vr.dm
  code/game/objects/items/weapons/storage/backpack_vr.dm
  code/game/objects/items/weapons/tanks/tank_types.dm
  code/game/objects/items/weapons/tanks/tank_types_vr.dm
  icons/obj/clothing/backpack.dmi
  icons/obj/storage.dmi
Labels: Sprites

#2087 Adjusting Language Understanding for Shells
  code/modules/mob/language/generic.dm
Labels: Fix

#2095 Removes smart internals gas type detection, internals automatically targets your active hand and then rig in priority, makes internal handling a bit saner and less complicated.
  code/_onclick/hud/screen_objects.dm
Labels: Removal

#2107 fixes internal tanks, woops.
  code/modules/mob/living/carbon/human/species/species.dm
Labels: Priority: High

#2092 Make Cells Appear to be Empty on Fabrication
  code/modules/power/cell.dm
  code/modules/power/cells/device_cells.dm
  code/modules/power/cells/power_cells.dm
  code/modules/research/designs.dm
  code/modules/research/designs/power_cells.dm
Labels: Fix

#2101 Vendor Assembly
  code/controllers/subsystems/circuits.dm
  code/modules/integrated_electronics/core/assemblies/generic.dm
  icons/obj/integrated_electronics/electronic_setups.dmi
Labels: Feature, Sprites

#2103 Updated Alert Sounds
  code/modules/security levels/security levels.dm
  sound/misc/deltakalaxon.ogg
  sound/misc/voyalert.ogg
  sound/misc/voybluealert.ogg
Labels: Code Improvement, Sound

#2114 Fixes Cells Spawning with No Charge
  _maps/map_files/Tether/tether-01-surface1.dmm
  _maps/map_files/Tether/tether-03-surface3.dmm
  _maps/map_files/Tether/tether-05-station1.dmm
  _maps/map_files/Tether/tether-06-station2.dmm
  _maps/map_files/Tether/tether-07-station3.dmm
  _maps/map_files/Tether/tether-10-colony.dmm
  code/modules/power/cell.dm
Labels: Map Edit

#2117 Oh god why did shuttle have to explode like that? -- Fixes multiple issues with exploration shuttle
  maps/tether/submaps/aerostat/aerostat.dmm
  maps/tether/submaps/alienship/alienship.dmm
  maps/tether/submaps/beach/beach.dmm
Labels: Fix, Priority: High

#2111 Xenochimera Status Icon
  code/_onclick/hud/_defines_vr.dm
  code/_onclick/hud/human.dm
  code/_onclick/hud/screen_objects_vr.dm
  code/modules/mob/living/carbon/human/species/station/station_special_vr.dm
  code/modules/mob/living/carbon/human/species/station/xenochimera_hud_vr.dm
  code/modules/mob/mob_defines_vr.dm
  config/admins.txt
  icons/mob/chimerahud.dmi
  vorestation.dme
Labels: Config Update, Feature, Sprites

#2119 Tesh additions 2
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/client/preference_setup/loadout/loadout_xeno.dm
  code/modules/clothing/suits/aliens/seromi.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/under/xenos/seromi.dm
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_races/markings.dmi
  icons/mob/species/seromi/suit.dmi
  icons/mob/species/seromi/uniform.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/species/seromi/suits.dmi
  icons/obj/clothing/species/seromi/uniform.dmi
  icons/obj/clothing/suits.dmi
Labels: Feature, Fix, Sprites

#2120 Fixes typo in solar storm announcement
  code/modules/events/solar_storm.dm
Labels: Grammar and Formatting

#2118 Update to Config Text for Alert Levels
  code/modules/security levels/security levels.dm
  config/legacy/config.txt
Labels: Config Update, Tweak

#2126 Donator item
  icons/obj/storage.dmi
  modular_citadel/code/game/objects/items/donator_item.dm
  modular_citadel/code/modules/client/preference_setup/loadout_donator.dm
Labels: Sprites

#2133 Donor item
  modular_citadel/code/modules/client/preference_setup/loadout_donator.dm
  modular_citadel/code/modules/clothing/donatorclothing.dm
  modular_citadel/icons/mob/donatorclothing.dmi
  modular_citadel/icons/obj/clothing/donatorclothing.dmi
Labels: Merge Conflict

#2121 Vulp mask sprite fix
  icons/mob/species/vulpkanin/helmet.dmi
  icons/mob/species/vulpkanin/mask.dmi
  icons/mob/species/vulpkanin/suit.dmi
Labels: Sprites

#2127 Adds Portable Shield Diffusor to Cargo
  _maps/map_files/Tether/tether-07-station3.dmm
Labels: Feature, Map Edit

#2125 Buff/updates to Under Dark spawns and loot. Increased Difficulty.
  maps/tether/submaps/underdark_pois/Corridor.dmm
  maps/tether/submaps/underdark_pois/abandonded_outpost.dmm
  maps/tether/submaps/underdark_pois/abandonedshelter.dmm
  maps/tether/submaps/underdark_pois/boss_mob.dmm
  maps/tether/submaps/underdark_pois/broken_engine.dmm
  maps/tether/submaps/underdark_pois/goldhall.dmm
  maps/tether/submaps/underdark_pois/phoron_rat_den.dmm
  maps/tether/submaps/underdark_pois/spider_nest.dmm
  maps/tether/submaps/underdark_pois/vault1.dmm
Labels: Balance/Rebalance

#2123 Mining Love, otherwise known as "Hey you get guns now"
  _maps/map_files/Tether/tether-01-surface1.dmm
Labels: Feature, Map Edit

#2122 Map fixing. Access for Robotics, Disposals for Exploration, MAYBE fix…
  _maps/map_files/Tether/tether-03-surface3.dmm
  _maps/map_files/Tether/tether-05-station1.dmm
Labels: Fix, Map Edit

#2116 Watch Assembly
  code/controllers/subsystems/circuits.dm
  code/modules/integrated_electronics/core/assemblies/clothing.dm
  icons/mob/hands.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/machines/mining_machines_vr.dmi
Labels: Feature, Sprites

#2140 !tgs endnotify is finally not admin only
  code/modules/admin/chat_commands.dm
Labels: Code Improvement

#2142 Fixes Shield Gen/Shield Capacitor ID Locking
  code/modules/shieldgen/shield_capacitor.dm
  code/modules/shieldgen/shield_gen.dm
Labels: Fix

#2137 Adds More Missing Sprites
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites

#2109 fixes dd.log
  code/game/world.dm
Labels: Priority: High

#2110 don't mind me, nothing to see here
  code/__DEFINES/atmospherics/gas_strings.dm
  code/controllers/subsystems/air.dm
  code/game/objects/items/weapons/storage/mre.dm
  code/game/turfs/flooring/flooring_premade.dm
  code/game/turfs/flooring/shuttle_vr.dm
  code/game/turfs/simulated/floor_types.dm
  code/game/turfs/simulated/outdoors/sky.dm
  code/game/turfs/space/space.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mob/living/carbon/alien/life.dm
  maps/southern_cross/turfs/outdoors.dm
  maps/tether/submaps/alienship/_alienship.dm
  maps/tether/tether_turfs.dm
Labels: Priority: High

#2135 fixes atmos leak rolling invalid gases
  code/modules/events/atmos_leak.dm
Labels: Priority: High

#2144 [2020-06-27T03:38:48] Runtime in mob_planes.dm, line 144: filter argument border not found
  code/__DEFINES/lighting.dm
Labels: Priority: High

#2106 Random Events Buffs (Take two) FFS TravisCL
  code/modules/events/hostile_migration_vr.dm
  code/modules/events/spider_infestation.dm
  code/modules/hydroponics/spreading/spreading.dm
  code/modules/hydroponics/spreading/spreading_growth.dm
  code/modules/hydroponics/spreading/spreading_response.dm
Labels: Balance/Rebalance

#2136 adds verb to auto bunker override on linked servers
  code/controllers/configuration/entries/comms.dm
  code/controllers/configuration_old/configuration.dm
  code/controllers/subsystems/ticker.dm
  code/datums/world_topic.dm
  code/game/gamemodes/game_mode.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/client/client_topic.dm
  code/modules/client/verbs/panic_bunker_player.dm
  code/modules/ext_scripts/github.dm
  code/modules/ext_scripts/irc.dm
  code/modules/ext_scripts/python.dm
  code/modules/mob/logout.dm
  vorestation.dme
Labels: Config Update, Feature
