Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2021-04, with the labels that each got.

#2908 Bone Hurting Juice
  code/__DEFINES/admin.dm
  code/modules/admin/verbs/smite.dm
Labels: Feature

#2928 Returns the missing core eject button to Bridge
  _maps/map_files/triumph/triumph-04-deck4.dmm
Labels: Fix, Map Edit

#2937 fixes lavaland
  _maps/planet_levels/140x140/lavaland.dmm
  code/modules/telesci/hyper_pad.dm
Labels: Map Edit

#2936 "the codebase never ceases to amaze me with its amazing ideas and piss-poor implementation": air injectors.
  code/__DEFINES/logging.dm
  code/modules/admin/admin_investigate.dm
  code/modules/atmospherics/components/unary/outlet_injector.dm
  vorestation.dme
Labels: Feature

#2929 Adds a message for everyone around you when you examine something. Also adds a preference to not show other people looking at the booba.
  code/modules/client/preference_setup/global/setting_datums.dm
  code/modules/mob/mob.dm
Labels: Feature

#2949 unsquishes minitest and adds emote stuff from main
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species/species.dm
  maps/citadel_minitest/citadel_minitest-1.dmm
  maps/citadel_minitest/citadel_minitest-sector-2.dmm
  maps/citadel_minitest/citadel_minitest-sector-3.dmm
  maps/citadel_minitest/citadel_minitest.dm
  maps/citadel_minitest/citadel_minitest_defines.dm
  maps/citadel_minitest/citadel_minitest_sectors.dm
  maps/citadel_minitest/citadel_minitest_shuttles.dm
  modular_citadel/sound/voice/catpeople/nyaha.ogg
  modular_citadel/sound/voice/catpeople/nyahaha1.ogg
  modular_citadel/sound/voice/catpeople/nyahaha2.ogg
  modular_citadel/sound/voice/catpeople/nyahehe.ogg
  modular_citadel/sound/voice/laughs/femlaugh.ogg
  modular_citadel/sound/voice/laughs/masclaugh1.ogg
  modular_citadel/sound/voice/laughs/masclaugh2.ogg
  modular_citadel/sound/voice/screams/sound_voice_scream_scream_f1.ogg
  modular_citadel/sound/voice/screams/sound_voice_scream_scream_f2.ogg
  modular_citadel/sound/voice/screams/sound_voice_scream_scream_f3.ogg
  modular_citadel/sound/voice/screams/sound_voice_scream_scream_m1.ogg
  modular_citadel/sound/voice/screams/sound_voice_scream_scream_m2.ogg
Labels: Feature, Fix, IGNORE TRAVIS

#2938 makes weapons sound beefier
  code/game/mecha/equipment/weapons/weapons.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/projectile/beams.dm
  code/modules/projectiles/projectile/bullets.dm
  sound/effects/weaponsounds_grenadelaunch.ogg
  sound/weapons/weaponsounds_alienlaser.ogg
  sound/weapons/weaponsounds_heavypistolshot.ogg
  sound/weapons/weaponsounds_heavyrifleshot.ogg
  sound/weapons/weaponsounds_lasermid.ogg
  sound/weapons/weaponsounds_laserstrong.ogg
  sound/weapons/weaponsounds_laserstrongALT.ogg
  sound/weapons/weaponsounds_laserweak.ogg
  sound/weapons/weaponsounds_pistolshot.ogg
  sound/weapons/weaponsounds_rifleshot.ogg
  sound/weapons/weaponsounds_shotgunshot.ogg
  sound/weapons/weaponsounds_smallpistolshot.ogg
Labels: IGNORE TRAVIS, Sound

#2956 fixes stack deletion issues
  code/game/objects/items/stacks/stack.dm
Labels: Priority: High

#2897 How to piss off engineers in one simple step
  code/modules/power/singularity/collector.dm
  code/modules/shieldgen/shield_gen.dm
Labels: Currently Testmerged

#2932 [RTM] Language Flags Clean up, _vr merging and speech_verbs can be lists now
  code/__DEFINES/species_languages.dm
  code/__DEFINES/species_languages_vr.dm
  code/__HELPERS/global_lists.dm
  code/modules/mob/language/generic.dm
  code/modules/mob/language/language.dm
  code/modules/mob/language/monkey.dm
  code/modules/mob/language/outsider.dm
  code/modules/mob/language/station.dm
  code/modules/mob/language/station_vr.dm
  code/modules/mob/living/say.dm
  code/modules/mob/say.dm
  vorestation.dme
Labels: Code Improvement, Do Not Merge, Refactor

#2959 makes area icons (objectively) significantly better
  code/game/area/Space Station 13 areas.dm
  icons/turf/areas.dmi
  maps/tether/tether_areas.dm
Labels: Sprites

#2968 more horror character design options
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_races/markings_vr.dmi
Labels: Sprites

#2962 toggle pain messages
  code/modules/client/preferences_toggle_procs.dm
  code/modules/organs/pain.dm
  code/modules/vore/eating/living_vr.dm
Labels: Feature

#2954 Fixes robotics labcoat icons
  icons/mob/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: Fix, Sprites

#2951 Makes fishing less fucking dogshit
  code/modules/fishing/fishing.dm
Labels: Removal

#2950 adds taur loafing
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/vore/appearance/sprite_accessories_taur_vr.dm
  code/modules/vore/appearance/sprite_accessories_vr.dm
  code/modules/vore/appearance/update_icons_vr.dm
  icons/mob/vore/taurs_vr.dmi
Labels: Feature, Sprites

#2898 Suplexes all barsigns before it
  icons/obj/barsigns.dmi
Labels: Currently Testmerged, Sprites

#2961 Update mob.dm
  code/modules/mob/mob.dm
Labels: IGNORE TRAVIS

#2976 adds unus (uno) because it isn't a joke anymore
  _maps/map_files/triumph/triumph-02-deck2.dmm
  _maps/map_files/triumph/triumph-04-deck4.dmm
  code/game/machinery/vending.dm
  code/modules/client/preference_setup/loadout/loadout_general.dm
  code/modules/games/unus.dm
  icons/obj/playing_cards.dmi
  vorestation.dme
Labels: Feature, Map Edit, Sprites

#2958 lets event managers+ delete mobs in a specified range
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/debug.dm
Labels: IGNORE TRAVIS

#2996 Revert "Update emote.dm"
  code/modules/mob/living/carbon/human/emote.dm
Labels: Revert

#2992 Adds floppy elf ears
  code/modules/vore/appearance/sprite_accessories_vr.dm
  icons/mob/vore/ears_vr.dmi
Labels: Currently Testmerged, Feature, Sprites

#2991 adds ashtrays to bar, soda dispenser to kitchen, and some other minor map stuff
  _maps/map_files/triumph/triumph-01-deck1.dmm
  _maps/map_files/triumph/triumph-02-deck2.dmm
  _maps/map_files/triumph/triumph-03-deck3.dmm
  _maps/map_files/triumph/triumph-04-deck4.dmm
Labels: Currently Testmerged, Feature, Fix, Map Edit

#2988 Ports RUS-T icons, tweaks stability, dynamically scales alpha with colour / Temperature.
  code/modules/power/fusion/core/_core.dm
  code/modules/power/fusion/core/core_field.dm
  icons/effects/160x160.dmi
  icons/effects/224x224.dmi
  icons/effects/288x288.dmi
  icons/effects/352x352.dmi
  icons/effects/416x416.dmi
  icons/effects/96x96.dmi
  icons/obj/machines/power/fusion.dmi
  icons/obj/machines/power/fusion_core.dmi
Labels: Code Improvement, Currently Testmerged, Feature, Sprites

#2986 makes minor rad weakness actually cause 25% more rads like it says instead of 35% more
  code/modules/mob/living/carbon/human/species/station/traits/negative.dm
Labels: Currently Testmerged

#2987 what if we removed the fusion environment heat cap..... haha...
  code/modules/power/fusion/core/core_field.dm
Labels: Currently Testmerged, Testmerge Only

#2989 fixes a bunch of things (borg attacks gravity etc combined pr)
  code/_onclick/cyborg.dm
  code/_onclick/item_attack.dm
  code/game/area/Space Station 13 areas.dm
  code/game/area/areas.dm
  code/game/atoms.dm
  code/game/turfs/turf.dm
  code/modules/mob/living/silicon/robot/robot_modules/station/medical.dm
  code/modules/multiz/movement.dm
Labels: Currently Testmerged

#2993 max mob size reduced to 150% from 200%
  code/modules/client/preference_setup/vore/02_size.dm
  code/modules/clothing/under/miscellaneous_vr.dm
  code/modules/mob/living/carbon/human/species/station/protean/protean_powers.dm
  code/modules/nifsoft/software/15_misc.dm
  code/modules/resleeving/designer.dm
  code/modules/vore/resizing/resize_vr.dm
Labels: Currently Testmerged

#2994 mannequins can no longer scream
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human_species.dm
Labels: Currently Testmerged

#2995 lets not spam THUNDERDOME.ogg indefinitely in the holodeck
  code/modules/holodeck/HolodeckControl.dm
  maps/nsv_triumph/triumph_things.dm
Labels: Currently Testmerged

#3004 Update's RUS-T Guide.
  code/game/objects/items/weapons/manuals.dm
Labels: Currently Testmerged, Fix

#2973 Changes to engine templates
  _maps/templates/engines/triumph/triumph_engine_fission.dmm
  _maps/templates/engines/triumph/triumph_engine_rust.dmm
  _maps/templates/engines/triumph/triumph_engine_sme.dmm
Labels: Fix, Map Edit

#2997 Exploration shuttle redesign
  _maps/map_files/triumph/triumph-04-deck4.dmm
  _maps/map_files/triumph/triumph_ships.dmm
  _maps/planet_levels/140x140/Class_D.dmm
  _maps/planet_levels/140x140/Class_H.dmm
  _maps/planet_levels/140x140/debrisfield.dmm
  _maps/planet_levels/140x140/frozen_planet.dmm
  _maps/planet_levels/140x140/mining_planet.dmm
  _maps/planet_levels/140x140/tradeport.dmm
Labels: Currently Testmerged, Map Edit, Test Merge Candidate

#2650 [MAINPORT] Adds an Age gate
  code/modules/client/preference_setup/global/setting_datums.dm
  code/modules/client/preferences_toggle_procs.dm
  code/modules/client/verbs/panic_bunker_player.dm
  code/modules/mob/mob.dm
  code/modules/mob/new_player/new_player.dm
Labels: Currently Testmerged, Feature, Testmerge Only

#2964 conveyor thing
  code/modules/recycling/conveyor2.dm
Labels: Needs Review

#2999 gives ce hardsuit magboots 0 slowdown just like the regular because you can just wear the regular anyways and the hardsuit one looks less awful
  code/modules/clothing/spacesuits/rig/suits/station.dm
Labels: Currently Testmerged

#3000 makes explorer pins work anywhere off station, not just on explorer levels sue me
  code/modules/projectiles/pins.dm
Labels: Balance/Rebalance, Currently Testmerged

#3001 science no longer gets free tasers (fixes xeno taser guns)
  code/modules/xenobio/items/weapons.dm
Labels: Currently Testmerged

#3003 fixes antimagic components, gives inversion beams 0.66x damage if someone is antimagic shielded
  code/__DEFINES/is_helpers.dm
  code/_onclick/telekinesis.dm
  code/game/gamemodes/changeling/powers/armblade.dm
  code/game/gamemodes/changeling/powers/armor.dm
  code/game/gamemodes/changeling/powers/bioelectrogenesis.dm
  code/game/gamemodes/changeling/powers/electric_lockpick.dm
  code/game/gamemodes/cult/construct_spells.dm
  code/game/gamemodes/cult/cult_items.dm
  code/game/gamemodes/technomancer/spell_objs.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/t_scanner.dm
  code/game/objects/items/storage/_storage.dm
  code/game/objects/items/storage/laundry_basket.dm
  code/game/objects/items/weapons/handcuffs.dm
  code/game/objects/items/weapons/material/knives.dm
  code/game/objects/items/weapons/melee/energy.dm
  code/game/objects/items/weapons/mop_deploy.dm
  code/game/objects/items/weapons/nullrod.dm
  code/game/objects/items/weapons/trays.dm
  code/game/objects/items/weapons/weaponry.dm
  code/modules/artifice/deadringer.dm
  code/modules/assembly/proximity.dm
  code/modules/blob/blob.dm
  code/modules/clothing/gloves/gauntlets.dm
  code/modules/clothing/suits/hooded.dm
  code/modules/clothing/under/accessories/accessory.dm
  code/modules/economy/retail_scanner.dm
  code/modules/games/cards.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_mob/defense.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_grab.dm
  code/modules/projectiles/projectile.dm
Labels: Balance/Rebalance, Currently Testmerged

#3005 hacky-ish thing to prevent nifs from wearing out from auto installed software
  code/modules/nifsoft/nif.dm
Labels: Currently Testmerged

#3007 moved the chef's soda machine because no one mentioned the spot was weird while the PR was still testmerged aaaaaa
  _maps/map_files/triumph/triumph-02-deck2.dmm
Labels: Map Edit

#3009 fixes modular weapons not updating after generatefiremodes somehow writing 5 lines of code to fix this doesn't change the fact this entire fire deserves to go in a trash fire
  code/modules/projectiles/guns/energy/modular/modulargun.dm
Labels: Priority: High

#3010 your lack of spellcheck is hindering my " productivy "
  code/modules/events/cult.dm
Labels: Grammar and Formatting

#3015 sometimes the only safe haven from shitcode is porting in status effects from main just to code a dagger for stabbing things with
  code/__DEFINES/flags/obj_flags.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/status_effects.dm
  code/_globalvars/bitfields.dm
  code/controllers/subsystems/processing/status_effects.dm
  code/datums/status_effects/debuffs/crusher_mark.dm
  code/datums/status_effects/neutral/crusher_track.dm
  code/datums/status_effects/status_effect.dm
  code/game/objects/objs.dm
  code/modules/mining/kinetic_crusher.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mining/ore_redemption_machine/equipment_vendor.dm
  code/modules/mining/ore_redemption_machine/survey_vendor.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/simple_mob/defense.dm
  code/modules/shieldgen/directional_shield.dm
  code/modules/spells/aoe_turf/conjure/forcewall.dm
  icons/mob/inhands/__inhand_template.dmi
  icons/mob/inhands/equipment/instruments_lefthand.dmi
  icons/mob/inhands/equipment/instruments_righthand.dmi
  icons/mob/inhands/weapons/hammers_lefthand.dmi
  icons/mob/inhands/weapons/hammers_righthand.dmi
  icons/obj/lavaland/artefacts.dmi
  icons/obj/mining.dmi
  sound/weapons/plasma_cutter.ogg
  vorestation.dme
Labels: Feature, Sound, Sprites

#3018 adds tagline config
  code/controllers/configuration/entries/general.dm
  code/game/world.dm
  config/config.txt
Labels: Config Update

#3021 fixes cataloguer point sharing
  code/modules/catalogue/cataloguer.dm
Labels: Priority: High

#3024 fixes inducer runtime, removes inducing smes because it's a blatant copypaste that is unnecessary
  code/game/objects/items/weapons/inducer.dm
Labels: Removal

#3026 Various aesthetic fixes and tweaks to Triumph, especially Security and D4.
  _maps/map_files/triumph/triumph-02-deck2.dmm
  _maps/map_files/triumph/triumph-03-deck3.dmm
  _maps/map_files/triumph/triumph-04-deck4.dmm
Labels: Map Edit

#3028 Replaces "Gaoler" with "Jailer" and removes the Senior Constable and Constable titles.
  code/game/jobs/job/security.dm
Labels: Removal

#3029 Removes more nonsensical alt-titles
  code/game/jobs/job/captain.dm
  code/game/jobs/job/medical.dm
Labels: Removal

#2952 Following an unfortunate incident where an employee was found drowned in a pool, NT has added appropriate safety measures.
  _maps/map_files/triumph/triumph-04-deck4.dmm
Labels: Map Edit

#3023 adjusts pain again, reverts pain toggle's delay tweaks and in general MAKES IT POSSIBLE TO FEEL PAIN MORE, WHICH IS IMPORTANT IF YOU ARE DYING!!!!!!!!
  code/modules/organs/pain.dm
Labels: Revert

#3040 removes fun - no more spawning in dust clouds :( and i guess faster/more organized overmaps init
  code/__DEFINES/controllers/_subsystems.dm
  code/controllers/subsystems/events.dm
  code/controllers/subsystems/overmap.dm
  code/modules/overmap/overmap_object.dm
  vorestation.dme
Labels: Removal

#3047 Re-Uploading Exploration Shuttle
  _maps/map_files/triumph/triumph-04-deck4.dmm
Labels: Map Edit
