Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2021-05, with the labels that each got.

#3045 fixes language colors
  code/modules/admin/admin.dm
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
  tgui/public/tgui-panel.bundle.css
Labels: UI

#3036 lazy ugly webedit to give science 2 bombsuits. i could have opened up sdmm and did this in a proper location but instead i'm going to stuff this into a corner with a noticeboard because it was easier for me to locate in text search.
  _maps/map_files/triumph/triumph-03-deck3.dmm
Labels: Map Edit

#3037 lets not sterilise entire solar systems every shift
  code/modules/events/solar_storm.dm
Labels: Fix

#3050 removes tgfont gitignore, tgui is now fully commited to repo
  tgui/packages/tgfont/.gitignore
  tgui/packages/tgfont/dist/tgfont.css
  tgui/packages/tgfont/dist/tgfont.eot
  tgui/packages/tgfont/dist/tgfont.woff2
Labels: Removal, UI

#3008 [READY] Yeet, Or, How I learned to stop hating resleeving and rework it entirely.
  _maps/map_files/triumph/triumph-03-deck3.dmm
  code/controllers/subsystems/transcore_vr.dm
  code/game/machinery/adv_med.dm
  code/game/machinery/vending.dm
  code/modules/client/preference_setup/general/03_body.dm
  code/modules/client/preference_setup/loadout/loadout_utility.dm
  code/modules/client/preference_setup/vore/08_nif.dm
  code/modules/client/preferences.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/resleeving/computers.dm
  code/modules/resleeving/machines.dm
  code/modules/resleeving/mirror.dm
  icons/obj/mirror.dmi
  nano/templates/adv_med.tmpl
  nano/templates/sleever.tmpl
  vorestation.dme
Labels: Do Not Merge, Feature, Map Edit, Removal, Sprites

#3051 Revert "makes sizegun standard with other size nerfs"
  code/modules/vore/resizing/sizegun_vr.dm
Labels: Revert

#3052 Revert "max mob size reduced to 150% from 200%"
  code/modules/client/preference_setup/vore/02_size.dm
  code/modules/clothing/under/miscellaneous_vr.dm
  code/modules/mob/living/carbon/human/species/station/protean/protean_powers.dm
  code/modules/nifsoft/software/15_misc.dm
  code/modules/resleeving/designer.dm
  code/modules/vore/resizing/resize_vr.dm
Labels: Revert

#3011 Adds an extremely important song to the jukebox
  config_static/jukebox.json
Labels: Config Update

#2998 ok fine you can pretend to be drunk
  code/modules/client/preferences_toggle_procs.dm
Labels: Feature

#3065 NERF's RUS-T's Manual
  code/game/objects/items/weapons/manuals.dm
Labels: Balance/Rebalance

#3049 Sound from washing mouth with soap
  code/game/objects/items/weapons/clown_items.dm
  sound/items/soapmouth.ogg
Labels: Sound

#3063 Adds a burn chamber engine submap
  _maps/templates/engines/triumph/triumph_engine_burnchamber.dmm
  maps/submaps/engine_submaps/engine.dm
Labels: Currently Testmerged, Feature, Map Edit

#3078 fixes one of the common random unit test failures because how did not a single mapper decide to investigate the issue of a chunk of a map literally being missing???
  _maps/submaps/level_specific/class_h/AuxiliaryResearchFacility.dmm
Labels: Priority: High

#3068 Mirror Update #1
  code/modules/mob/living/silicon/robot/dogborg/dog_modules_vr.dm
  code/modules/mob/living/silicon/robot/robot_modules/event_vr.dm
  code/modules/mob/living/silicon/robot/robot_modules/station/medical.dm
  code/modules/resleeving/computers.dm
  code/modules/resleeving/machines.dm
  code/modules/resleeving/mirror.dm
Labels: Feature, Fix

#3080 seriously how has this random stairwell been a black hole of darkness for this long after 14 million deck 4 remaps
  _maps/map_files/triumph/triumph-04-deck4.dmm
Labels: Map Edit

#3090 crazy fucking idea i know but maybe ALL The dorms should have light switches instead of just some??
  _maps/map_files/triumph/triumph-02-deck2.dmm
Labels: Currently Testmerged, Map Edit

#3086 don't you think timers should tick down 1 second every second instead of 1 second every 2 seconds?
  code/modules/assembly/timer.dm
Labels: Currently Testmerged

#3085 Why does the pathfinder have a fucking uzi which is a dogshit weapon from the 50s? WHO KNOWS BUT AT LEAST I CAN MAKE THE NAME FOR IT'S MAGS IN THE AUTOLATHE MAKE SENSE
  code/datums/autolathe/arms.dm
Labels: Currently Testmerged

#3083 makes rd suit not an eyesore
  icons/mob/spacesuit.dmi
Labels: Currently Testmerged, Sprites

#3082 ports every winter coat from main because man y'all missed 2/3 of them.
  code/game/machinery/vending.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/client/preference_setup/loadout/loadout_role_restricted.dm
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/clothing/head/hood.dm
  code/modules/clothing/suits/hooded.dm
  icons/mob/head.dmi
  icons/mob/items/lefthand.dmi
  icons/mob/items/lefthand_suits.dmi
  icons/mob/items/righthand_suits.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Currently Testmerged, Feature, Sprites

#3093 Apparently, removing extools loading from the code wasn't enough to stop the crashes, so let's take extools out of the codebase.
  byond-extools.dll
  dependencies.sh
  tools/tgs4_scripts/PreCompile.sh
Labels: Currently Testmerged, Tools

#3096 slight mirror refactor + additional error reporting
  code/game/machinery/cryopod.dm
  code/modules/nifsoft/software/05_health.dm
  code/modules/nifsoft/software/13_soulcatcher.dm
  code/modules/resleeving/mirror.dm
Labels: Currently Testmerged, Refactor

#3097 Adds moles to gas analyzer & allows ghosts to analyze pipes
  code/__HELPERS/atmospherics.dm
  code/game/machinery/atmoalter/canister.dm
  code/modules/atmospherics/pipes/pipe_base.dm
  nano/templates/canister.tmpl
Labels: Currently Testmerged, Feature

#3098 Speeds warming up of cooking machines & fixes "it is switched off." always appearing bug
  code/modules/food/kitchen/cooking_machines/_appliance.dm
  code/modules/food/kitchen/cooking_machines/_cooker.dm
Labels: Currently Testmerged, Fix

#3099 shitty fix to statue decon
  code/game/objects/structures/statues.dm
Labels: Currently Testmerged

#3076 Protean survivability changes part 2
  code/modules/mob/living/carbon/human/species/station/protean/protean_blob.dm
  code/modules/mob/living/carbon/human/species/station/protean/protean_species.dm
  code/modules/organs/subtypes/nano.dm
Labels: Balance/Rebalance, Currently Testmerged, Feature

#3101 Update fulton.dm
  code/modules/mining/fulton.dm
Labels: Currently Testmerged

#3102 mob AI no longer chase ghosts
  code/modules/ai/ai_holder_targeting.dm
Labels: Currently Testmerged

#3100 Knouli's Event Reward Item + Creating Event Reward Files
  code/modules/client/preference_setup/loadout/loadout_event_rewards.dm
  modular_citadel/code/modules/clothing/eventclothing.dm
  modular_citadel/icons/mob/eventclothing.dmi
  modular_citadel/icons/obj/clothing/eventclothing.dmi
  vorestation.dme
Labels: Code Improvement, Currently Testmerged, Feature

#3084 fixes xenoarcheology tools
  code/modules/xenoarcheaology/tools/tools.dm
Labels: Currently Testmerged, Needs Review

#3092 adds json topic api for manifest, players, revision, and status.
  code/datums/world_topic.dm
Labels: Currently Testmerged

#3110 fixes ambiguity in some boolean logic
  code/controllers/subsystems/jobs.dm
  code/game/machinery/adv_med.dm
  code/game/objects/items/devices/translator.dm
  code/game/verbs/who.dm
  code/modules/client/ui_style.dm
  code/modules/mining/mine_turfs.dm
  code/modules/power/fusion/core/core_control.dm
  code/modules/power/fusion/fuel_assembly/fuel_control.dm
  code/modules/power/fusion/gyrotron/gyrotron_control.dm
Labels: Currently Testmerged

#3109 adds _contents() wrapper for SELECT SDQL2 statements
  code/modules/admin/verbs/SDQL2/SDQL_2_wrappers.dm
Labels: Currently Testmerged

#3108 Ports black-eyed shadekins from Virgo (WHITELIST ONLY)
  code/__DEFINES/chemistry.dm
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/human/species/shadekin/shadekin.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/mob/new_player/sprite_accessories.dm
  code/modules/organs/subtypes/shadekin.dm
  code/modules/vore/appearance/sprite_accessories_taur_vr.dm
  code/modules/vore/appearance/sprite_accessories_vr.dm
Labels: Currently Testmerged, Feature

#3117 IP Reputation port from Vorestation & Return to menu >> Respawn
  code/_onclick/hud/ghost.dm
  code/controllers/configuration_old/configuration.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/panicbunker.dm
  code/modules/client/client procs_vr.dm
  code/modules/client/client_defines.dm
  code/modules/client/client_procs.dm
  code/modules/mob/mob.dm
  vorestation.dme
Labels: Administration, Config Update, Feature

#3119 Shinto Shrine Decorations Pack
  code/game/objects/items/godfigures.dm
  code/game/objects/items/weapons/nullrod.dm
  code/game/objects/structures/signs.dm
  icons/obj/chaplain.dmi
  icons/obj/decals.dmi
Labels: Currently Testmerged, Sprites

#3118 Adds Straight Jackets to Psych Ward, Fixes Exam Room 2 Bolt Button, and Gives Robotics Surgery a Biohazard Bin
  _maps/map_files/triumph/triumph-03-deck3.dmm
Labels: Currently Testmerged, Map Edit

#3114 Adds Fungoid Head Decals (Created by Hjorthorn) WIP
  code/modules/vore/appearance/sprite_accessories_vr.dm
  icons/mob/vore/ears_vr.dmi
Labels: Currently Testmerged, Sprites

#3087 Adds Library Scanner, Partially Fixes Bugged Tyrmalin Drinks, and Restores Vore Smites
  _maps/map_files/triumph/triumph-04-deck4.dmm
  code/__DEFINES/admin.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/smite_vr.dm
  code/modules/clothing/head/hood.dm
  code/modules/clothing/suits/hooded.dm
  code/modules/food/drinkingglass/metaglass.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  vorestation.dme
Labels: Config Update, Currently Testmerged, Map Edit, Sound, Sprites

#3121 TTS Devices can now be used in chairs, and by alt clicking from pockets.
  code/game/objects/items/devices/text_to_speech.dm
Labels: Currently Testmerged, Fix

#3120 exploration and command now renders properly in manifest checks
  code/datums/world_topic.dm
Labels: Currently Testmerged

#3012 Medicalborg Rework
  code/global.dm
  code/modules/mob/living/silicon/robot/dogborg/dog_modules_vr.dm
  code/modules/mob/living/silicon/robot/robot_modules/station.dm
  code/modules/mob/living/silicon/robot/robot_modules/station/medical.dm
  code/modules/mob/living/silicon/robot/robot_modules/station_vr.dm
  code/modules/reagents/reagent_containers/borghydro.dm
Labels: Currently Testmerged

#3122 finishes renaming return to menu back to respawn, adds return to menu as an alias to respawn
  code/modules/admin/admin.dm
  code/modules/mob/mob.dm
Labels: Currently Testmerged

#3125 commlinks automatically activate
  code/modules/nifsoft/software/14_commlink.dm
Labels: Currently Testmerged

#3127 tunes up human examine, gets rid of the extraneous 5 lines
  code/modules/mob/living/carbon/human/examine.dm
Labels: Currently Testmerged

#3124 client disconnections for byond version, blacklisted versions, and panic bunker now uses disconnect_with_message to hopefully get around the warning message never showing for new players
  code/modules/client/client_procs.dm
Labels: Currently Testmerged

#3129 Adds Colored Kimonos (Sprites by Keek) and New Communicator Sprites (WIP)
  code/game/machinery/vending.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/device.dmi
Labels: Currently Testmerged, Sprites

#3130 Revert "commlinks automatically activate"
  code/modules/nifsoft/software/14_commlink.dm
Labels: Currently Testmerged, Revert

#3131 >light power should never be above 1 >circuit lights can go up to 6
  code/modules/integrated_electronics/subtypes/output.dm
Labels: Currently Testmerged

#3126 shitcode to stop zlevel edges from eating people's jetpacks until space/overmaps are refactored or we get off this map
  code/game/turfs/space/space.dm
Labels: Currently Testmerged, Refactor

#3104 Adds a long rang analyzer to the game.
  code/game/objects/items/devices/scanners.dm
  code/game/objects/items/storage/belt.dm
  code/modules/research/designs/engineering.dm
Labels: Currently Testmerged, Feature

#3135 mobs can now break out of nets :)
  code/game/objects/items/weapons/weaponry.dm
Labels: Currently Testmerged
