Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2021-08, with the labels that each got.

#3306 Xenomorphs to Neomorphs
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
Labels: Fix, Refactor

#3299 Improvement of the Exploration Department
  _maps/map_files/tether/tether-05-station1.dmm
Labels: Currently Testmerged, Feature, Fix, Map Edit, Removal

#3263 TGUI for machines
  code/_onclick/ai.dm
  code/_onclick/cyborg.dm
  code/game/machinery/computer/RCON_Console.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/doors/door.dm
  code/modules/power/apc.dm
  code/modules/power/apc_vr.dm
  code/modules/power/generator.dm
  code/modules/power/port_gen.dm
  code/modules/power/smes.dm
  code/modules/power/supermatter/supermatter.dm
  code/modules/tgui/modules/rcon.dm
  code/modules/tgui/states/default.dm
  tgui/packages/tgui/interfaces/APC.js
  tgui/public/tgui.bundle.js
  vorestation.dme
Labels: Code Improvement, Fix, UI

#3308 ""small"" xenobio QoL update
  code/modules/food/kitchen/smartfridge.dm
  code/modules/xenobio/machinery/processor.dm
Labels: Currently Testmerged, Feature

#3310 Vermin Infestation Now Can Spawn Roaches
  code/modules/events/infestation.dm
Labels: Currently Testmerged

#3312 fixes rcon not obeyinig overmaps
  code/modules/nano/modules/rcon.dm
Labels: Currently Testmerged

#3313 fixes stack deletion bug (for the third time)
  code/game/objects/items/stacks/stack.dm
Labels: Currently Testmerged

#3319 Ports Triumph Desert World To V-4
  _maps/map_levels/140x140/virgo4_beach.dmm
  _maps/map_levels/140x140/virgo4_cave.dmm
  _maps/map_levels/140x140/virgo4_desert.dmm
  _maps/submaps/level_specific/class_h/AuxiliaryResearchFacility.dmm
  _maps/submaps/level_specific/class_h/BoneyardH.dmm
  _maps/submaps/level_specific/class_h/BunkerH.dmm
  _maps/submaps/level_specific/class_h/SupplyDrop1H.dmm
  _maps/submaps/level_specific/class_h/SupplyDrop2H.dmm
  _maps/submaps/level_specific/class_h/cave1H.dmm
  _maps/submaps/level_specific/class_h/cave3H.dmm
  _maps/submaps/level_specific/class_h/desertruins1H.dmm
  _maps/submaps/level_specific/class_h/desertruins2H.dmm
  _maps/submaps/level_specific/class_h/desertruins3H.dmm
  _maps/submaps/level_specific/class_h/desertruins4H.dmm
  _maps/submaps/level_specific/class_h/desertsaloon.dmm
  _maps/submaps/level_specific/class_h/farmsH.dmm
  _maps/submaps/level_specific/class_h/highnoonH.dmm
  _maps/submaps/level_specific/class_h/landing_padH.dmm
  _maps/submaps/level_specific/class_h/minesH.dmm
  _maps/submaps/level_specific/class_h/oasisH.dmm
  _maps/submaps/level_specific/class_h/ranchH.dmm
  _maps/submaps/level_specific/class_h/rocks1H.dmm
  _maps/submaps/level_specific/class_h/rocks2H.dmm
  _maps/submaps/level_specific/class_h/solar_farmH.dmm
  _maps/submaps/level_specific/class_h/springcaveH.dmm
  code/game/turfs/flooring/flooring_premade.dm
  code/modules/maps/tether/lateload.dm
  code/modules/maps/tether/levels/virgo4.dm
  code/modules/maps/triumph/submaps/class_h.dm
  maps/tether/submaps/_beach.dm
  maps/tether/tether_defines.dm
Labels: Currently Testmerged, Feature, Code Improvement, Map Edit

#3315 make it so digestion drops their mirror
  code/modules/vore/eating/belly_obj_vr.dm
Labels: Currently Testmerged

#3307 Why do we have two lists for shields?
  code/modules/shieldgen/shield_gen_external.dm
Labels: Currently Testmerged, Fix

#3314 Adds Tan Line Markings
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_races/markings.dmi
Labels: Currently Testmerged, Feature, Sprites

#3323 fixes line endings in codebase
  _maps/map_levels/140x140/virgo4_beach.dmm
  _maps/map_levels/140x140/virgo4_cave.dmm
  _maps/map_levels/140x140/virgo4_desert.dmm
  _maps/submaps/level_specific/class_h/AuxiliaryResearchFacility.dmm
  _maps/submaps/level_specific/class_h/BoneyardH.dmm
  _maps/submaps/level_specific/class_h/BunkerH.dmm
  _maps/submaps/level_specific/class_h/SupplyDrop1H.dmm
  _maps/submaps/level_specific/class_h/SupplyDrop2H.dmm
  _maps/submaps/level_specific/class_h/cave1H.dmm
  _maps/submaps/level_specific/class_h/cave3H.dmm
  _maps/submaps/level_specific/class_h/desertruins1H.dmm
  _maps/submaps/level_specific/class_h/desertruins2H.dmm
  _maps/submaps/level_specific/class_h/desertruins3H.dmm
  _maps/submaps/level_specific/class_h/desertruins4H.dmm
  _maps/submaps/level_specific/class_h/desertsaloon.dmm
  _maps/submaps/level_specific/class_h/farmsH.dmm
  _maps/submaps/level_specific/class_h/highnoonH.dmm
  _maps/submaps/level_specific/class_h/landing_padH.dmm
  _maps/submaps/level_specific/class_h/minesH.dmm
  _maps/submaps/level_specific/class_h/oasisH.dmm
  _maps/submaps/level_specific/class_h/ranchH.dmm
  _maps/submaps/level_specific/class_h/rocks1H.dmm
  _maps/submaps/level_specific/class_h/rocks2H.dmm
  _maps/submaps/level_specific/class_h/solar_farmH.dmm
  _maps/submaps/level_specific/class_h/springcaveH.dmm
Labels: Map Edit

#3321 hardsuit mesons now blocks supermatter hallucinations (while active)
  code/modules/power/supermatter/supermatter.dm
Labels: Currently Testmerged

#3322 fixes hand teles not randomly jaunting you on fail
  code/game/objects/effects/portals.dm
Labels: Currently Testmerged

#3320 Alt-Click Storage and Alt/Ctrl-Click Vehicles
  code/_onclick/click.dm
  code/game/objects/items/storage/_storage.dm
  code/modules/vehicles/bike.dm
  code/modules/vehicles/cargo_train.dm
Labels: Currently Testmerged, Feature

#3309 Bartending Drink Overhaul
  code/modules/food/drinkingglass/metaglass.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/reagents/Drink-Recipes.dm
  icons/obj/drinks.dmi
Labels: Currently Testmerged, Sprites

#3318 Tether Shuttle Dock Improvements
  _maps/map_files/tether/tether-05-station1.dmm
  _maps/map_files/tether/tether-06-station2.dmm
Labels: Currently Testmerged, Map Edit

#3329 Automatically fails any pull requests with bad line endings
  tools/ci/check_grep.sh
Labels: Currently Testmerged, Tools

#3331 no more announcing soulcatcher on cryogenics
  code/game/machinery/cryopod.dm
Labels: Currently Testmerged

#3330 Lets do backend stuff! Part 1 of IDK how many
  code/__DEFINES/_flags/_flags.dm
  code/__DEFINES/_flags/do_after.dm
  code/__DEFINES/_flags/interaction_flags.dm
  code/__DEFINES/_flags/item_flags.dm
  code/__DEFINES/_flags/movement.dm
  code/__DEFINES/_flags/obj_flags.dm
  code/__DEFINES/_flags/preferences.dm
  code/__DEFINES/color/color.dm
  code/__DEFINES/color/interface.dm
  code/__DEFINES/damage_organs.dm
  code/__DEFINES/flags.dm
  code/__DEFINES/misc.dm
  code/_onclick/hud/screen_objects.dm
  code/game/objects/effects/effect_system.dm
  code/game/objects/items/weapons/tanks/tanks.dm
  code/modules/atmospherics/zas/Phoron.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/masks/breath.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/clothing/spacesuits/alien.dm
  code/modules/clothing/spacesuits/plasman.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/clothing/spacesuits/rig/rig_pieces.dm
  code/modules/clothing/spacesuits/spacesuits.dm
  code/modules/examine/descriptions/armor.dm
  code/modules/mapping/map_helpers/_map_helpers.dm
  code/modules/mapping/ruins.dm
  code/modules/mob/living/carbon/breathe.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/spells/targeted/ethereal_jaunt.dm
  code/modules/vore/fluffstuff/custom_items.dm
  vorestation.dme
Labels: Currently Testmerged, Code Improvement

#3325 Hopefully Fixes Sunlight in the Desert, Fixes Roach Spawn
  code/modules/events/infestation.dm
  maps/tether/tether_virgo4.dm
Labels: Currently Testmerged, Fix

#3332 Fixes Xenochimera adapting abilities firing even if you cancel
  code/modules/mob/living/carbon/human/species/station/station_special.dm
Labels: Currently Testmerged, Fix

#3334 fixes slime processor autointake
  code/modules/xenobio/machinery/processor.dm
Labels: Currently Testmerged

#3327 Begins Expanding Midpoint
  _maps/map_files/tether/tether-04-transit.dmm
Labels: Currently Testmerged, Feature, Map Edit

#3324 Adds Squirt Guns
  code/game/machinery/computer3/computers/arcade.dm
  code/game/objects/structures/crates_lockers/closets/fitness.dm
  code/modules/reagents/reagent_containers/spray.dm
  icons/mob/items/lefthand.dmi
  icons/mob/items/lefthand_guns.dmi
  icons/mob/items/righthand.dmi
  icons/mob/items/righthand_guns.dmi
  icons/obj/toy.dmi
Labels: Currently Testmerged, Feature, Sprites

#3340 CMO Locker's were missing things, I fixed it.
  _maps/map_files/tether/tether-02-surface2.dmm
Labels: Currently Testmerged, Fix, Map Edit

#3339 defibs no longer instantly kill people on the first defib
  code/game/objects/items/devices/defib.dm
Labels: Currently Testmerged

#3343 Minor Bar Layout Change - Window Tint / Fixes Xenobot Access Reqs
  _maps/map_files/tether/tether-03-surface3.dmm
Labels: Currently Testmerged, Feature, Map Edit

#3346 Minor Xenobiology changes
  _maps/map_files/tether/tether-02-surface2.dmm
Labels: Currently Testmerged, Map Edit
