Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2021-03, with the labels that each got.

#2782 Traffic Control Updates & Hostile Migration Fix
  code/game/objects/banners.dm
  code/modules/busy_space/air_traffic.dm
  code/modules/busy_space/organizations.dm
  code/modules/catalogue/catalogue_data.dm
  code/modules/events/hostile_migration_vr.dm
Labels: Code Improvement, Currently Testmerged, Feature, Fix, Tweak

#2785 [WIP] Rod Change
  code/modules/power/fission/rods.dm
Labels: Balance/Rebalance, Currently Testmerged, Work in Progress

#2795 i hope whoever added this trait realizes that 24 kpa is higher than the partial pressure of oxygen in a standard atmosphere, meaning anyone taking this will die upon joining the round. go figure, powergaming coders who don't test their code.
  code/modules/mob/living/carbon/human/species/station/traits/negative.dm
Labels: Currently Testmerged, Removal

#2796 re-adds berets that vorestation removed
  code/modules/client/preference_setup/loadout/loadout_head.dm
Labels: Currently Testmerged

#2798 Improves The "Thigh-Length" and "Knee-Length" Jackboot Sprites, Fixes Invisible Digitigrade/Toeless Versions
  icons/mob/feet.dmi
  icons/obj/clothing/shoes.dmi
Labels: Currently Testmerged, Fix, Sprites

#2799 Adds donator item
  code/modules/client/preference_setup/loadout/loadout_donator.dm
  code/modules/clothing/masks/gasmask.dm
  icons/mob/mask.dmi
  icons/obj/clothing/masks.dmi
Labels: Currently Testmerged, Feature, Sprites

#2800 replaces a donator item
  code/game/objects/items/weapons/swords_axes_etc.dm
  code/modules/client/preference_setup/loadout/loadout_donator.dm
  icons/obj/furniture.dmi
Labels: Currently Testmerged, Sprites

#2792 Fixes Virology areas and removes loose disposal items from Triumph (Now in tgm)
  _maps/map_files/triumph/triumph-03-deck3.dmm
Labels: Map Edit, Removal

#2797 [Review Needed]Moves floor decals from LateInitialize() to Initialize(), fixing floorpainter
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/flooring/flooring_decals.dm
Labels: Currently Testmerged

#2802 Fixes The Newsfeed App On Communicators Being Broken
  code/game/machinery/newscaster.dm
  code/game/objects/items/devices/communicator/UI.dm
  code/game/objects/items/devices/communicator/communicator.dm
  code/game/objects/items/devices/communicator/helper.dm
  nano/templates/communicator.tmpl
Labels: Currently Testmerged, Fix

#2803 Adds New Types of Sushi
  code/modules/food/food/snacks.dm
  code/modules/food/recipes_microwave.dm
  code/modules/mob/living/simple_mob/subtypes/vore/horse.dm
Labels: Currently Testmerged

#2804 Allows Command Secretaries to spawn with the Command Bodysuit in loadout.
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
Labels: Currently Testmerged, Tweak

#2806 Cyborgs rejoice, your presence shall be known
  code/modules/mob/new_player/new_player.dm
Labels: Currently Testmerged, Fix

#2812 Revert "[Review Needed]Moves floor decals from LateInitialize() to Initialize(), fixing floorpainter"
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/flooring/flooring_decals.dm
Labels: Revert

#2807 let's actually delete the inventory when we call delete_inventory()
  code/modules/mob/inventory.dm
Labels: Currently Testmerged, Fix

#2809 moved synth cooling check so it won't interfere with heat status icon
  code/modules/mob/living/carbon/human/life.dm
Labels: Currently Testmerged, Fix

#2814 fixes not being able to switch briefcases between hands
  code/game/objects/items/storage/secure.dm
Labels: Currently Testmerged, Fix

#2811 adds custom species data to round logging so we can take a census
  code/controllers/subsystems/jobs.dm
Labels: Currently Testmerged

#2813 swaps out old c# midi2piano for latest python one from tg
  tools/midi2piano/README.txt
  tools/midi2piano/easygui/__init__.py
  tools/midi2piano/midi/__init__.py
  tools/midi2piano/midi/midi.py
  tools/midi2piano/midi2piano.py
  tools/midi2piano/midi2piano.sln
  tools/midi2piano/midi2piano/Form1.Designer.cs
  tools/midi2piano/midi2piano/Form1.cs
  tools/midi2piano/midi2piano/Form1.resx
  tools/midi2piano/midi2piano/Properties/AssemblyInfo.cs
  tools/midi2piano/midi2piano/Sanford.Multimedia.Midi.dll
  tools/midi2piano/midi2piano/bin/x86/Release/Sanford.Multimedia.Midi.dll
  tools/midi2piano/midi2piano/bin/x86/Release/midi2piano.exe
  tools/midi2piano/midi2piano/midi2piano.csproj
  tools/midi2piano/pyperclip/__init__.py
  tools/midi2piano/pyperclip/clipboards.py
  tools/midi2piano/pyperclip/exceptions.py
  tools/midi2piano/pyperclip/windows.py
Labels: Currently Testmerged, Tools

#2816 Fixes pain using SEND_SOUND instead of to_chat
  code/modules/organs/pain.dm
Labels: Currently Testmerged

#2815 Reduces the ungodly amount of lights on Triumph across all four decks
  _maps/map_files/triumph/triumph-01-deck1.dmm
  _maps/map_files/triumph/triumph-02-deck2.dmm
  _maps/map_files/triumph/triumph-03-deck3.dmm
  _maps/map_files/triumph/triumph-04-deck4.dmm
Labels: Currently Testmerged, Map Edit, Removal

#2818 fixes firelock examine
  code/game/machinery/doors/firedoor.dm
Labels: Currently Testmerged

#2817 Make Sex on the Beach Sexier
  code/modules/food/drinkingglass/metaglass.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/reagents/Drink-Recipes.dm
  icons/obj/drinks.dmi
Labels: Feature, Sprites, Tweak

#2819 VI's donator item, and a fix to secure briefcases included cus I'm scum and atomization is hard
  code/game/objects/items/storage/secure.dm
  code/modules/client/preference_setup/loadout/loadout_donator.dm
  icons/mob/back.dmi
  icons/obj/clothing/backpack.dmi
  modular_citadel/icons/mob/items/lefthand_storage.dmi
  modular_citadel/icons/mob/items/righthand_storage.dmi
Labels: Currently Testmerged, Feature, Fix, Sprites

#2820 Loadout Major Overhaul, Vox Sprite Fixes, Teshari Loadout Fixes, & Some New Clothes
  code/modules/client/preference_setup/loadout/loadout_accessories.dm
  code/modules/client/preference_setup/loadout/loadout_eyes.dm
  code/modules/client/preference_setup/loadout/loadout_gloves.dm
  code/modules/client/preference_setup/loadout/loadout_head.dm
  code/modules/client/preference_setup/loadout/loadout_role_restricted.dm
  code/modules/client/preference_setup/loadout/loadout_shoes.dm
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/client/preference_setup/loadout/loadout_utility.dm
  code/modules/client/preference_setup/loadout/loadout_xeno.dm
  code/modules/clothing/suits/hooded.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/clothing/under/xenos/teshari.dm
  icons/mob/species/teshari/head.dmi
  icons/mob/species/teshari/suit.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
  vorestation.dme
Labels: Code Improvement, Currently Testmerged, Feature, Fix, Grammar and Formatting, Removal, Sprites, Tweak

#2824 let's make machetes less busted
  code/game/objects/items/weapons/material/knives.dm
  code/modules/clothing/under/accessories/accessory.dm
  code/modules/clothing/under/accessories/holster.dm
Labels: Currently Testmerged, Fix

#2821 Fixes quantum leap pad not teleporting mechs.
  code/modules/telesci/hyper_pad.dm
Labels: Currently Testmerged

#2822 fixes portable scrubbers not properly updating icons (probably)
  code/game/machinery/atmoalter/portable_atmospherics.dm
Labels: Currently Testmerged

#2826 heaters now (should so testmerge this because this is a webedit pr) automatically calculate how much energy they need to put in to reach a target temperature instead of wildly overshooting and heating gas to the temperature of the surface of the sun.
  code/modules/atmospherics/components/unary/heat_source.dm
Labels: Currently Testmerged

#2828 fixes mining turfs creating mineral effects while not dense
  code/modules/mining/mine_turfs.dm
Labels: Currently Testmerged

#2827 bandaids mining turfs to properly recalculate lights when being dug pending full turf refactoring
  code/modules/mining/mine_turfs.dm
Labels: Currently Testmerged, Refactor

#2835 fixes linter probably speedmerge this lmao
  code/modules/clothing/under/accessories/holster.dm
Labels: Priority: High

#2830 replaces lighting system with modern tg/vglights
  code/__DEFINES/_planes+layers.dm
  code/__DEFINES/dcs/signals.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/lighting.dm
  code/__HELPERS/unsorted.dm
  code/controllers/configuration/entries/game_options.dm
  code/controllers/configuration_old/configuration.dm
  code/controllers/subsystems/lighting.dm
  code/controllers/subsystems/planets.dm
  code/controllers/subsystems/skybox.dm
  code/game/area/Off Station Areas.dm
  code/game/area/Space Station 13 areas.dm
  code/game/area/areas.dm
  code/game/atoms.dm
  code/game/objects/effects/misc.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/wall_attacks.dm
  code/game/turfs/simulated/wall_icon.dm
  code/game/turfs/simulated/walls.dm
  code/game/turfs/space/space.dm
  code/game/turfs/turf.dm
  code/game/turfs/turf_changing.dm
  code/modules/atmospherics/gasmixtures/gas_types.dm
  code/modules/lighting/__lighting_docs.dm
  code/modules/lighting/emissive_blocker.dm
  code/modules/lighting/lighting_area.dm
  code/modules/lighting/lighting_atom.dm
  code/modules/lighting/lighting_corner.dm
  code/modules/lighting/lighting_object.dm
  code/modules/lighting/lighting_overlay.dm
  code/modules/lighting/lighting_setup.dm
  code/modules/lighting/lighting_source.dm
  code/modules/lighting/lighting_turf.dm
  code/modules/lighting/~lighting_undefs.dm
  code/modules/turbolift/turbolift_map.dm
  config/config.txt
  config/game_options.txt
  icons/effects/alphacolors.dmi
  icons/effects/lighting_object.dmi
  icons/effects/lighting_overlay.dmi
  vorestation.dme
Labels: Config Update, Currently Testmerged, Sprites

#2831 Modernizes the CAG Decks
  code/modules/games/cah_black_cards.dm
  code/modules/games/cah_white_cards.dm
Labels: Currently Testmerged

#2834 Parts Lathe GUI update.
  nano/templates/partslathe.tmpl
Labels: Currently Testmerged

#2833 refactors areas a bit and fixes linter
  code/__DEFINES/_planes+layers.dm
  code/__HELPERS/areas.dm
  code/__HELPERS/unsorted.dm
  code/_globalvars/lists/mapping.dm
  code/_onclick/hud/fullscreen.dm
  code/controllers/subsystems/emergency_shuttle.dm
  code/controllers/subsystems/lighting.dm
  code/controllers/subsystems/mapping.dm
  code/game/area/areas.dm
  code/game/gamemodes/cult/hell_universe.dm
  code/game/gamemodes/endgame/supermatter_cascade/universe.dm
  code/game/gamemodes/events.dm
  code/game/machinery/turret_control.dm
  code/game/mecha/mech_fabricator.dm
  code/game/mecha/mech_prosthetics.dm
  code/game/objects/items/blueprints.dm
  code/global.dm
  code/modules/admin/secrets/random_events/gravity.dm
  code/modules/admin/verbs/adminjump.dm
  code/modules/admin/verbs/debug.dm
  code/modules/events/gravity.dm
  code/modules/events/prison_break.dm
  code/modules/gamemaster/actions/gravity.dm
  code/modules/gamemaster/actions/prison_break.dm
  code/modules/maps/tg/map_template.dm
  code/modules/maps/tg/reader.dm
  code/modules/mob/dead/observer/observer.dm
  code/unit_tests/map_tests.dm
  vorestation.dme
Labels: Currently Testmerged, Refactor

#2837 probably mostly definitely fixes busted pink squares for some inhand PAI sprites
  icons/mob/items/lefthand_holder.dmi
  icons/mob/items/righthand_holder.dmi
Labels: Currently Testmerged, Fix, Sprites

#2838 fixes turf runtimes
  code/game/turfs/simulated/walls.dm
Labels: Currently Testmerged

#2839 runs dmm2tgm on all triumph submaps
  maps/nsv_triumph/submaps/frozen_planet/HeadscientistHQ.dmm
  maps/nsv_triumph/submaps/frozen_planet/ruins1.dmm
  maps/nsv_triumph/submaps/frozen_planet/ruins2.dmm
  maps/nsv_triumph/submaps/frozen_planet/ruins3.dmm
  maps/nsv_triumph/submaps/frozen_planet/ruins4.dmm
  maps/nsv_triumph/submaps/frozen_planet/ruins5.dmm
  maps/nsv_triumph/submaps/gaia_planet/gaia_planet.dmm
  maps/nsv_triumph/submaps/poi_d/EpodD.dmm
  maps/nsv_triumph/submaps/poi_d/cave1D.dmm
  maps/nsv_triumph/submaps/poi_d/cave2D.dmm
  maps/nsv_triumph/submaps/poi_d/cave3D.dmm
  maps/nsv_triumph/submaps/poi_d/hiddenbunkerD.dmm
  maps/nsv_triumph/submaps/poi_d/landing_padD.dmm
  maps/nsv_triumph/submaps/poi_d/matdropD.dmm
  maps/nsv_triumph/submaps/poi_d/meteor.dmm
  maps/nsv_triumph/submaps/poi_d/solar_farmD.dmm
  maps/nsv_triumph/submaps/poi_d/vault1D.dmm
  maps/nsv_triumph/submaps/poi_h/AuxiliaryResearchFacility.dmm
  maps/nsv_triumph/submaps/poi_h/cave3H.dmm
Labels: Currently Testmerged

#2845 Aura's donator item
  code/modules/client/preference_setup/loadout/loadout_donator.dm
  code/modules/clothing/ears/ears.dm
  icons/mob/ears.dmi
  icons/mob/species/teshari/ears.dmi
  icons/obj/items.dmi
Labels: Currently Testmerged, Sprites

#2846 Updates a donor sprite
  code/modules/client/preference_setup/loadout/loadout_donator.dm
  icons/mob/back.dmi
  modular_citadel/icons/mob/items/lefthand_storage.dmi
  modular_citadel/icons/mob/items/righthand_storage.dmi
Labels: Currently Testmerged, Sprites

#2842 SKUB.
  code/game/objects/structures/loot_piles.dm
Labels: Currently Testmerged, Fix

#2844 adds new items to grippers, doesn't rename them cus captain hates funny
  code/modules/mob/living/silicon/robot/drone/drone_items.dm
Labels: Currently Testmerged

#2849 fixes meson eyepatch in loadout
  code/modules/client/preference_setup/loadout/loadout_role_restricted.dm
Labels: Currently Testmerged, Fix

#2848 Allows AI to use camera consoles cus it also allows cyborgs to
  code/game/machinery/computer/camera.dm
Labels: Currently Testmerged

#2850 YEET
  code/modules/admin/admin_verbs.dm
  code/modules/admin/player_panel.dm
  code/modules/keybindings/keybind/admin.dm
Labels: Currently Testmerged, Removal

#2851 nanotrasen has stopped putting black holes in their rings (rings no longer have material slowdown, because 2.2 slowdown from a silver ring is Bad.)
  code/game/objects/items/weapons/material/material_armor.dm
  code/modules/clothing/clothing.dm
Labels: Currently Testmerged

#2858 makes almost* every species able to wear protean rigsuits
  icons/mob/species/akula/helmet_vr.dmi
  icons/mob/species/akula/suit_vr.dmi
  icons/mob/species/fennec/helmet_vr.dmi
  icons/mob/species/fennec/suit_vr.dmi
  icons/mob/species/fox/helmet_vr.dmi
  icons/mob/species/fox/suit_vr.dmi
  icons/mob/species/nevrean/helmet_vr.dmi
  icons/mob/species/nevrean/suit_vr.dmi
  icons/mob/species/phoronoid/head.dmi
  icons/mob/species/phoronoid/suit.dmi
  icons/mob/species/sergal/helmet_vr.dmi
  icons/mob/species/sergal/suit_vr.dmi
  icons/mob/species/skrell/helmet.dmi
  icons/mob/species/skrell/suit.dmi
  icons/mob/species/tajaran/helmet.dmi
  icons/mob/species/tajaran/suit.dmi
  icons/mob/species/unathi/helmet.dmi
  icons/mob/species/unathi/suit.dmi
  icons/mob/species/vox/gloves.dmi
  icons/mob/species/vox/head.dmi
  icons/mob/species/vox/shoes.dmi
  icons/mob/species/vox/suit.dmi
  icons/mob/species/vulpkanin/helmet.dmi
  icons/mob/species/vulpkanin/suit.dmi
  icons/mob/species/zaddat/head.dmi
  icons/mob/species/zaddat/suit.dmi
Labels: Currently Testmerged, Sprites

#2841 Fixes a bunch of important bugs (ai examine poster placement overmap generation maybe traders maybe not who knows)
  code/__DEFINES/controllers/_subsystems.dm
  code/__HELPERS/global_lists.dm
  code/__HELPERS/unsorted.dm
  code/_globalvars/lists/mapping.dm
  code/controllers/subsystems/jobs.dm
  code/controllers/subsystems/mapping.dm
  code/controllers/subsystems/ticker.dm
  code/controllers/subsystems/vote.dm
  code/controllers/verbs.dm
  code/datums/mind.dm
  code/datums/uplink/uplink_items.dm
  code/game/antagonist/_antagonist_setup.dm
  code/game/antagonist/antagonist_place.dm
  code/game/antagonist/outsider/trader.dm
  code/game/area/areas.dm
  code/game/gamemodes/calamity/calamity.dm
  code/game/gamemodes/events.dm
  code/game/gamemodes/game_mode.dm
  code/game/jobs/job_controller.dm
  code/game/machinery/computer/specops_shuttle.dm
  code/game/machinery/computer/syndicate_specops_shuttle.dm
  code/game/machinery/teleporter.dm
  code/game/machinery/virtual_reality/vr_console.dm
  code/game/machinery/vr_console.dm
  code/game/objects/effects/decals/contraband.dm
  code/game/objects/effects/decals/posters/tgposters.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/items/antag_spawners.dm
  code/game/objects/items/devices/uplink_random_lists.dm
  code/game/objects/items/storage/bags.dm
  code/game/objects/structures/ghost_pods/human.dm
  code/game/turfs/simulated/walls.dm
  code/modules/admin/DB ban/functions.dm
  code/modules/admin/admin.dm
  code/modules/admin/player_panel.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/smite_vr.dm
  code/modules/awaymissions/zlevel.dm
  code/modules/economy/price_list.dm
  code/modules/events/apc_damage.dm
  code/modules/events/random_antagonist.dm
  code/modules/events/rogue_drones.dm
  code/modules/food/food/snacks.dm
  code/modules/gamemaster/actions/carp_migration.dm
  code/modules/gamemaster/actions/electrical_storm.dm
  code/modules/gamemaster/actions/random_antagonist.dm
  code/modules/gamemaster/actions/rogue_drones.dm
  code/modules/mob/freelook/ai/eye.dm
  code/modules/mob/living/silicon/ai/latejoin.dm
  code/modules/mob/transform_procs.dm
  code/modules/multiz/zshadow.dm
  code/modules/overmap/sectors.dm
  code/modules/random_map/drop/droppod.dm
  code/modules/shuttles/shuttle_specops.dm
  code/modules/turbolift/turbolift_map.dm
  code/modules/vore/eating/silicon_vr.dm
Labels: Currently Testmerged

#2855 Ports a bunch of wings from Vesta cus someone asked
  code/modules/vore/appearance/sprite_accessories_vr.dm
  icons/mob/vore/wings_vr.dmi
Labels: Currently Testmerged, Feature, Sprites

#2860 Removes unscrubbable fire hazards: lowers MINIMUM_MOLES_TO_FILTER to 0.01 (which is still too high, this is zone atmos not tile atmos there's zero excuse for it requiring this level of cheapskating for performance). 0.015 moles is now required for combustion.
  code/__DEFINES/machinery.dm
  code/modules/atmospherics/gasmixtures/reactions.dm
Labels: Currently Testmerged, Removal, Salt

#2862 adds diceroll <n> command on request
  code/modules/mob/mob.dm
Labels: Currently Testmerged

#2865 Vox's Delight No Longer Kills Vox [Fix]
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
Labels: Currently Testmerged, Fix

#2867 Moves the Medigun to Cargo and Adds Defib Sickness
  code/datums/supplypacks/medical.dm
  code/game/objects/items/devices/defib.dm
  code/modules/research/designs/medical.dm
Labels: Currently Testmerged

#2853 Locks SecVend Pistols to Rubber and Soft Nerfs Round Start PF Gear
  code/game/objects/items/gunbox.dm
  code/game/objects/items/gunbox_vr.dm
  code/game/objects/structures/crates_lockers/closets/secure/explorer.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  icons/obj/gun/ballistic.dmi
  vorestation.dme
Labels: Currently Testmerged, Sprites

#2852 Removes All Static Blood Red Hardsuit Spawns from POIs
  maps/nsv_triumph/submaps/frozen_planet/HeadscientistHQ.dmm
  maps/nsv_triumph/submaps/poi_d/SupplyDrop2D.dmm
  maps/nsv_triumph/submaps/poi_d/hiddenbunkerD.dmm
  maps/nsv_triumph/submaps/poi_h/highnoonH.dmm
Labels: Currently Testmerged, Removal

#2840 Removes SWAT Suits from Mercenary Gimmick Lockers
  code/game/objects/structures/crates_lockers/closets/gimmick.dm
Labels: Currently Testmerged, Removal

#2868 fixes bioprinters not printing organs beyond the basic list
  code/game/machinery/bioprinter.dm
Labels: Currently Testmerged, Fix

#2869 adds a new janiborg god i hate dogborgs
  code/modules/mob/living/silicon/robot/robot_modules/station/service.dm
  icons/mob/widerobot_vr.dmi
Labels: Currently Testmerged, Feature, Sprites

#2870 fixes some discrepancies with the biogenerators listed cost and actual cost
  code/game/machinery/biogenerator.dm
Labels: Currently Testmerged, Fix

#2861 moves panic bunker drop + db connection logging before most of client/New, maybe fixes no one getting the panic bunker drop message
  code/modules/client/client_procs.dm
Labels: Currently Testmerged

#2866 Adjustments to Ship Events, Spawning & Map
  _maps/map_files/triumph/triumph-01-deck1.dmm
  _maps/map_files/triumph/triumph-02-deck2.dmm
  _maps/map_files/triumph/triumph-03-deck3.dmm
  _maps/map_files/triumph/triumph-04-deck4.dmm
  code/modules/events/cult.dm
  code/modules/events/event_container_vr.dm
  code/modules/events/hostile_migration_vr.dm
Labels: Balance/Rebalance, Currently Testmerged, Feature, Map Edit, Removal

#2872 this should fix odd shadows near the lavaland base
  maps/nsv_triumph/submaps/lavaland/lavaland.dmm
Labels: Currently Testmerged

#2874 i want to see forever - for real this time
  icons/obj/clothing/glasses.dmi
Labels: Currently Testmerged, Fix, Sprites

#2856 ports a few loadout things from main
  code/modules/client/preference_setup/loadout/loadout_head.dm
  code/modules/vore/appearance/sprite_accessories_vr.dm
  icons/mob/vore/tails_vr.dmi
Labels: Feature, Sprites

#2881 fixes icecream initialization
  code/modules/food/kitchen/icecream.dm
Labels: Currently Testmerged

#2880 separates global and local narrates again .local narrates now require a target to use the view() of, because why would you kill the muscle memory of everyone who admins main like this
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/randomverbs.dm
Labels: Administration, Currently Testmerged

#2883 roller bed code continues to be a dumpster fire
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
Labels: Currently Testmerged

#2878 [MIGRATION PREPWORK] - NSB Adephagia Updated to Current Code (Core map files)
  code/game/area/Off Station Areas.dm
  code/modules/events/atmos_leak.dm
  maps/tether/submaps/submaps_readme.md
  maps/tether/submaps/underdark_pois/rykka_easter_egg.dmm
  maps/tether/tether-01-surface1.dmm
  maps/tether/tether-02-surface2.dmm
  maps/tether/tether-03-surface3.dmm
  maps/tether/tether-04-transit.dmm
  maps/tether/tether-05-station1.dmm
  maps/tether/tether-06-station2.dmm
  maps/tether/tether-07-station3.dmm
  maps/tether/tether-08-mining.dmm
  maps/tether/tether-09-solars.dmm
  maps/tether/tether-10-colony.dmm
  maps/tether/tether.dm
  maps/tether/tether_areas.dm
  maps/tether/tether_areas2.dm
  maps/tether/tether_defines.dm
  maps/tether/tether_jobs.dm
  maps/tether/tether_shuttle_defs.dm
  maps/tether/tether_things.dm
Labels: Currently Testmerged, Feature, Refactor

#2882 gives AR projections typing indicators (maybe, untested)
  code/modules/nifsoft/software/13_soulcatcher.dm
Labels: Currently Testmerged

#2875 The Art of Mimicry 2: The Floors Have Eyes
  code/modules/mob/living/simple_mob/subtypes/vore/mimic.dm
  icons/mob/mimic.dmi
Labels: Currently Testmerged, Feature, Fix, Sprites

#2885 NanoTrasen's 'Do Your Job' Corporate Initiative
  code/game/jobs/job/special.dm
Labels: Currently Testmerged

#2886 disruptor blade in mining borg emag modules (read: scrambled equips)
  code/modules/mob/living/silicon/robot/robot_modules/station/cargo.dm
Labels: Currently Testmerged, Feature

#2887 Map Start Reactor RNG - RUS-T / Fission / SuperMatter
  _maps/map_files/triumph/triumph-01-deck1.dmm
  _maps/map_files/triumph/triumph-04-deck4.dmm
  maps/submaps/engine_submaps/engine.dm
  maps/submaps/engine_submaps/tether_templates/engine_rust.dmm
  maps/submaps/engine_submaps/tether_templates/engine_singulo.dmm
  maps/submaps/engine_submaps/tether_templates/engine_sme.dmm
  maps/submaps/engine_submaps/tether_templates/engine_tesla.dmm
  maps/submaps/engine_submaps/triumph_engine_fission.dmm
  maps/submaps/engine_submaps/triumph_engine_rust.dmm
  maps/submaps/engine_submaps/triumph_engine_sme.dmm
Labels: Currently Testmerged, Feature, Map Edit

#2889 supermatter no longer makes synthetics, who cannot process synaptizine for the information, hallucinate.
  code/modules/power/supermatter/supermatter.dm
Labels: Balance/Rebalance, Currently Testmerged

#2891 overmap requires sensors again
  code/modules/overmap/turfs.dm
Labels: Currently Testmerged

#2892 [testmerge only, experimental] makes dynamic lighting overmaps allow sensor usage in dust clouds
  code/modules/lighting/lighting_source.dm
Labels: Currently Testmerged

#2902 fixes door assemblies not initializing
  code/game/objects/structures/door_assembly.dm
Labels: Currently Testmerged

#2896 makes rust slightly less awfully buggy (please stop destabilizing due to the abstract concept of lighting)
  code/modules/power/fusion/core/core_field.dm
Labels: Priority: High

#2914 sometimes life is cock and ball torture without the e
  code/modules/reagents/Topical-Recipes.dm
Labels: Fix

#2895 Remaps All of Triumph's Security, adds a lot of new maint to 4th deck
  _maps/map_files/triumph/triumph-04-deck4.dmm
Labels: Map Edit

#2923 removes instanced areas from Triumph
  _maps/map_files/triumph/triumph-02-deck2.dmm
  _maps/map_files/triumph/triumph-03-deck3.dmm
  _maps/map_files/triumph/triumph-04-deck4.dmm
  code/game/area/Space Station 13 areas.dm
Labels: Map Edit, Removal

#2911 shamelessly fixes ce and syndicate magboots having slowdown when they aren't supposed to be (and removes the stupid code copypaste) (once again untested webedit pr)
  code/modules/clothing/shoes/magboots.dm
Labels: Removal

#2910 adds engine loading weighting, defaulting to 40/40/20 supermatter/rust/fission (untested webedit PR that touches subsystems btw)
  code/controllers/configuration/entries/game_options.dm
  code/controllers/configuration_old/configuration_vr.dm
  code/controllers/subsystems/mapping.dm
  config/game_options.txt
  maps/submaps/engine_submaps/engine.dm
Labels: Config Update

#2901 the supermatter description should probably say that it delams at 5000K instead of 7000K so new players don't get baited by bad information
  code/modules/examine/descriptions/engineering.dm
Labels: Currently Testmerged, IGNORE TRAVIS
