Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2021-09, with the labels that each got.

#3356 sevensune lmao
  code/modules/vore/appearance/sprite_accessories_vr.dm
  icons/mob/vore/tails_vr.dmi
Labels: Feature, Sprites

#3341 Part 1/4 of my update to explo/cargo
  _maps/map_files/tether/tether-05-station1.dmm
  _maps/map_files/tether/tether-06-station2.dmm
Labels: Currently Testmerged, Map Edit

#3361 very complex fix for mouse traps
  code/__DEFINES/is_helpers.dm
Labels: Currently Testmerged

#3358 Adds Chest Bandages as a Bra Option
  code/datums/underwear/bottom.dm
  code/datums/underwear/top.dm
  icons/mob/human.dmi
Labels: Currently Testmerged, Sprites

#3354 Removes the Labcoat from Roboticists at Spawn, Repaths RD to Spawn with RD Labcoat, Repaths Scientist to Spawn with Science Labcoat.
  code/datums/autolathe/devices.dm
  code/datums/outfits/jobs/science.dm
  code/game/objects/items/devices/geiger.dm
Labels: Currently Testmerged, Removal

#3352 Adds a Mantis Thorax and Arms
  code/modules/vore/appearance/sprite_accessories_taur_vr.dm
  code/modules/vore/appearance/sprite_accessories_vr.dm
  icons/mob/vore/tails_vr.dmi
  icons/mob/vore/taurs_vr.dmi
  icons/mob/vore/wings_vr.dmi
Labels: Currently Testmerged, Feature, Sprites

#3349 Restores Some Hardsync Removals/Equipment Tweaks mk. 3
  _maps/map_files/tether/tether-01-surface1.dmm
  _maps/map_files/tether/tether-02-surface2.dmm
  _maps/map_files/tether/tether-03-surface3.dmm
  _maps/map_files/tether/tether_plains.dmm
  _maps/map_levels/140x140/talon/talon1.dmm
  _maps/map_levels/140x140/talon/talon2.dmm
  _maps/map_levels/140x140/virgo2_aerostat.dmm
  code/__DEFINES/chemistry.dm
  code/game/jobs/job/civilian_chaplain.dm
  code/game/machinery/vending.dm
  code/game/objects/items/trash.dm
  code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
  code/modules/clothing/suits/hooded.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/mob/living/carbon/human/species/station/station_special.dm
  code/modules/reagents/machinery/chem_master.dm
  code/modules/reagents/reagent_containers/hard_candy.dm
  code/modules/vore/fluffstuff/custom_boxes.dm
  icons/mob/mask.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/food.dmi
  tgui/packages/tgui/interfaces/ChemMaster.js
  tgui/packages/tgui/interfaces/ChemPress.js
  tgui/public/tgui.bundle.js
  vorestation.dme
Labels: Currently Testmerged, Feature, Sprites, UI, Map Edit

#3372 fixes runtime on cryoing out (goddamnit mirrors why)
  code/game/machinery/cryopod.dm
Labels: Currently Testmerged

#3370 (hopefully) fixes a severe memory leak with multiz mob rendering
  code/modules/multiz/zshadow.dm
Labels: Currently Testmerged

#3369 removes shared_vr.css
  code/modules/nano/nanoui.dm
Labels: Currently Testmerged, Removal

#3376 normal eva suits have 1 slowdown instead of 3
  code/modules/clothing/spacesuits/spacesuits.dm
Labels: Currently Testmerged

#3375 makes empty space levels accessible by players
  maps/~map_system/maps.dm
Labels: Currently Testmerged

#3335 Window melting fix
  code/game/objects/structures/window.dm
Labels: Currently Testmerged, Fix

#3362 Rearranges Shuttle Landmark to Account for Explo Shuttle.
  _maps/map_levels/140x140/debrisfield.dmm
Labels: Currently Testmerged, Map Edit

#3365 Skateboard Duping Fix and Assorted Bugfixes
  _maps/map_files/tether/tether-03-surface3.dmm
  code/datums/outfits/jobs/civilian.dm
  code/game/jobs/job/civilian.dm
  code/game/objects/items/weapons/melee/misc.dm
  code/modules/clothing/spacesuits/void/station.dm
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/vehicles/skateboard.dm
  code/modules/vore/appearance/sprite_accessories_vr.dm
Labels: Currently Testmerged, Fix, Map Edit

#3378 telescience now rounds
  code/modules/telesci/telesci_computer.dm
Labels: Currently Testmerged

#3377 Removes Pathfinder bowman headset ear protection
  code/game/objects/items/devices/radio/headset.dm
Labels: Currently Testmerged, Removal

#3374 removes id lock from mining point claiming
  code/modules/mining/machine_processing.dm
Labels: Currently Testmerged, Removal

#3379 Curbs your couches
  icons/obj/sofas.dmi
Labels: Currently Testmerged, Sprites

#3383 gives mining cyborgs a KA because literally WHY do they not have one
  code/modules/mob/living/silicon/robot/robot_modules/station/drone.dm
Labels: Currently Testmerged

#3384 removes telescience shielding from everything but the armory and vault
  code/game/area/Space Station 13 areas.dm
  code/game/area/ss13_deprecated_areas.dm
  code/modules/maps/tether/shuttles/itglight.dm
  code/modules/maps/tether/shuttles/shelter_6.dm
  maps/nsv_triumph/triumph_telecomms.dm
  maps/tether/tether_areas.dm
  maps/tether/tether_telecomms.dm
Labels: Currently Testmerged, Removal

#3388 Plant names, decon and construction
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/objects/structures/flora.dm
Labels: Currently Testmerged

#3368 Phoron Contamination Rework && Neomorph environmental resistances
  code/__DEFINES/species_languages.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species/outsider/vox.dm
  code/modules/mob/living/carbon/human/species/shadekin/shadekin.dm
  code/modules/mob/living/carbon/human/species/station/plasmen.dm
  code/modules/mob/living/carbon/human/species/station/protean/protean_species.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/mob/living/carbon/human/species/station/station_special.dm
Labels: Currently Testmerged, Fix, Balance/Rebalance

#3393 Reverts shield gen blocklist changes
  code/modules/shieldgen/emergency_shield.dm
  code/modules/shieldgen/shield_gen_external.dm
Labels: Currently Testmerged, Revert

#3392 fixes light fixture constructs (maybe)
  code/modules/power/lighting.dm
Labels: Currently Testmerged

#3391 Update tether-03-surface3.dmm
  _maps/map_files/tether/tether-03-surface3.dmm
Labels: Currently Testmerged, Fix, Map Edit

#3390 Mid September Bugfixes
  _maps/map_levels/140x140/frozen_planet.dmm
  _maps/submaps/level_specific/frozen_planet/HeadscientistHQ.dmm
  code/datums/autolathe/tools.dm
  code/datums/supplypacks/supply.dm
  code/game/objects/items/gunbox.dm
  code/game/objects/items/stacks/sandbag.dm
  code/modules/clothing/head/misc.dm
  code/modules/materials/fifty_spawner_mats.dm
  code/modules/materials/material_recipes.dm
  code/modules/materials/material_sheets.dm
  code/modules/materials/materials.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  code/modules/tables/presets.dm
  icons/mob/head.dmi
  icons/obj/stacks.dmi
  icons/obj/tables.dmi
  vorestation.dme
Labels: Currently Testmerged, Fix, Sprites, Removal, Map Edit

#3360 Creates: Apidaen/Vetalan Races, Potential Incoming Tweaks to Auril/Dremachir
  code/__DEFINES/chemistry.dm
  code/__DEFINES/mobs.dm
  code/datums/supplypacks/supply.dm
  code/game/machinery/suit_storage_unit.dm
  code/global.dm
  code/modules/catalogue/catalogue_data.dm
  code/modules/clothing/spacesuits/rig/rig_pieces.dm
  code/modules/clothing/spacesuits/void/void_vr.dm
  code/modules/mob/living/carbon/human/human_species.dm
  code/modules/mob/living/carbon/human/species/outsider/celestials.dm
  code/modules/mob/living/carbon/human/species/outsider/vetala.dm
  code/modules/mob/living/carbon/human/species/station/station_special.dm
  code/modules/mob/living/carbon/human/species/station/traits/neutral.dm
  code/modules/mob/new_player/sprite_accessories.dm
  code/modules/paperwork/photocopier.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
  code/modules/reagents/Misc-Recipes.dm
  code/modules/reagents/reagent_containers/organic.dm
  code/modules/reagents/reagent_containers/spray.dm
  code/modules/research/prosfab_designs.dm
  icons/mob/human_races/r_def_apidaen.dmi
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/chemical.dmi
  icons/obj/hydroponics_machines.dmi
  vorestation.dme
Labels: Currently Testmerged, Sprites

#3373 Updates our Gravity Generator to the Proper Sprite/Machine WIP
  _maps/map_files/tether/tether-05-station1.dmm
  code/modules/power/gravitygenerator.dm
Labels: Currently Testmerged, Map Edit

#3382 Loadout Implant Cost Reductions
  code/modules/client/preference_setup/loadout/loadout_utility.dm
Labels: Currently Testmerged, Balance/Rebalance

#3386 Fixes and Buffs Vermin Infestation
  code/modules/events/infestation.dm
  code/modules/gamemaster/actions/infestation.dm
  code/modules/mob/living/simple_mob/subtypes/animal/roach/roach.dm
  vorestation.dme
Labels: Currently Testmerged, Fix

#3395 Reworks Bodysuits to Interface with RIG and Voidsuits for Limited Utility
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Currently Testmerged, Sprites

#3397 Tears of The Armory
  _maps/map_files/tether/tether-02-surface2.dmm
Labels: Currently Testmerged, Feature, Map Edit

#3403 Doing the Github part of a map update
  _maps/map_levels/140x140/virgo4_beach.dmm
Labels: Currently Testmerged, Map Edit

#3401 Numbers and certain specieal characters are now allowed in Character Names
  code/__HELPERS/mobs.dm
  code/__HELPERS/text.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/modular_computers/file_system/programs/command/card.dm
  code/modules/surgery/robotics.dm
Labels: Currently Testmerged, Administration

#3396 Cargo maintinance and docking port prep
  _maps/map_files/tether/tether-05-station1.dmm
  _maps/map_files/tether/tether-06-station2.dmm
Labels: Currently Testmerged, Feature, Map Edit

#3402 Late September Bugfixes
  code/datums/supplypacks/materials.dm
  code/game/machinery/vending.dm
  code/game/objects/effects/spiders.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/client/preference_setup/loadout/loadout_accessories.dm
  code/modules/client/preference_setup/loadout/loadout_head.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/under/accessories/accessory.dm
  code/modules/events/infestation.dm
  code/modules/materials/material_recipes.dm
  code/modules/mob/living/silicon/robot/robot_modules/station/drone.dm
  code/modules/mob/living/simple_mob/subtypes/animal/roach/roach.dm
  icons/mob/head.dmi
  icons/mob/mask.dmi
  icons/mob/species/fennec/helmet_vr.dmi
  icons/mob/species/fennec/suit_vr.dmi
  icons/mob/species/fox/helmet_vr.dmi
  icons/mob/species/fox/suit_vr.dmi
  icons/mob/species/sergal/helmet_vr.dmi
  icons/mob/ties.dmi
  icons/obj/clothing/ties.dmi
Labels: Currently Testmerged, Sprites

#3404 Remaps the Armory - Replaces Specialized Armor Sets with Specialized Plate Carrier Sets
  _maps/map_files/tether/tether-02-surface2.dmm
  code/datums/supplypacks/security.dm
Labels: Currently Testmerged, Feature, Balance/Rebalance, Map Edit

#3412 fixes blob canpass
  code/modules/blob2/blobs/base_blob.dm
Labels: Currently Testmerged

#3409 sdbfrndfb
  code/modules/clothing/under/accessories/accessory.dm
  modular_citadel/code/modules/clothing/under/accessories/holster.dm
Labels: Currently Testmerged

#3411 HoS Protosuit
  _maps/map_files/tether/tether-03-surface3.dmm
Labels: Map Edit

#3417 particle focus qdel sanity
  code/modules/power/singularity/particle_accelerator/particle_smasher.dm
Labels: Currently Testmerged

#3418 fixes an edge case with protolathes
  code/modules/research/protolathe.dm
Labels: Currently Testmerged

#3419 Loadout Changes for Anodyne
  code/modules/client/preference_setup/loadout/loadout_role_restricted.dm
Labels: Currently Testmerged

#3420 fixes analyzers not working on zones
  code/__HELPERS/atmospherics.dm
Labels: Currently Testmerged

#3413 Touches up the Talon
  _maps/map_levels/140x140/talon/talon1.dmm
  _maps/map_levels/140x140/talon/talon2.dmm
Labels: Currently Testmerged, Map Edit

#3389 fixes 'sticky limbs' bug in character creation
  code/modules/client/preference_setup/general/03_body.dm
  code/modules/client/preferences.dm
  code/modules/mob/new_player/preferences_setup.dm
Labels: Currently Testmerged

#3422 Copper based circuits for the synthetic insurgeons
  code/game/mecha/micro/mechfab_designs_vr.dm
  code/game/objects/items/devices/communicator/communicator.dm
Labels: Currently Testmerged, Fix

#3415 Adds Headwear Function to Mouse Plushie / Adds Grey and White Variants
  code/game/objects/items/toys.dm
  icons/mob/head.dmi
  icons/obj/toy.dmi
Labels: Currently Testmerged, Feature, Sprites

#3426 Secvest sprite changes, holster typo fix, armor for the detective's locker for Anodyne
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/accessories/holster.dm
Labels: Currently Testmerged, Fix, Feature

#3425 Changes A2's depreciated sec maint area, changes the cargo status display to a supply subtype
  _maps/map_files/tether/tether-06-station2.dmm
Labels: Currently Testmerged, Fix, Removal, Map Edit

#3385 dark purple slime detonations now use an atmos floodfill instead of view()
  code/modules/mob/living/simple_mob/subtypes/slime/xenobio/subtypes.dm
Labels: Currently Testmerged

#3371 if you cannot code your air traffic spam right it does not deserve to exist
  code/modules/busy_space/air_traffic.dm
Labels: Currently Testmerged

#3428 Touchup the Fuel Station
  _maps/map_levels/140x140/fueldepot.dmm
Labels: Currently Testmerged, Feature, Map Edit
