Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2021-06, with the labels that each got.

#3111 despite making up only 3% of the population, nanite fetish blobs make up 75% of known bugs about speciescode
  code/modules/mob/living/carbon/human/death.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/station/protean/protean_blob.dm
  code/modules/mob/living/carbon/human/species/station/protean/protean_species.dm
  code/modules/mob/mob.dm
  code/modules/organs/subtypes/machine.dm
Labels: Currently Testmerged

#3138 I'm at the point where I look at harmless code used for roleplaying flavor and see exploits everywhere :)
  code/modules/mob/living/carbon/human/human.dm
Labels: Currently Testmerged

#3141 stupid fix for get_map_levels()
  maps/~map_system/maps.dm
Labels: Currently Testmerged

#3143 nerfs kinetic daggers
  code/__DEFINES/dcs/flags.dm
  code/__DEFINES/dcs/signals.dm
  code/datums/elements/conflict_checking.dm
  code/datums/looping_sounds/_looping_sound.dm
  code/modules/mining/kinetic_crusher.dm
  vorestation.dme
Labels: Balance/Rebalance, Currently Testmerged

#3144 de-lags mining by about 5 orders of magnitude
  code/modules/mining/machine_unloading.dm
  code/modules/mining/satchel_ore_boxdm.dm
Labels: Currently Testmerged

#3145 fixes a bug
  code/modules/overmap/spacetravel.dm
Labels: Currently Testmerged, Priority: High

#3139 fixes a bug with chemistry dispenser tgui. nerfs chem dispenser recharge to 20% because 5 units per tick, per chem, is ridiculous
  code/modules/reagents/machinery/dispenser/dispenser2_energy.dm
  code/modules/tgui/modal.dm
  tgui/packages/tgui/interfaces/common/ComplexModal.js
  tgui/public/tgui.bundle.js
Labels: Currently Testmerged, UI

#3142 asay linkificiation
  code/modules/admin/verbs/adminsay.dm
Labels: Currently Testmerged

#3140 makes it so mediborgs actually have burn kits (god i'm really dumb)
  code/modules/mob/living/silicon/robot/robot_modules/station/medical.dm
Labels: Currently Testmerged

#3147 Updates triumph_engine_burnchamber.dmm
  _maps/templates/engines/triumph/triumph_engine_burnchamber.dmm
Labels: Currently Testmerged, Map Edit

#3150 speeds up conveyors to 50 items/tick from 10
  code/modules/recycling/conveyor2.dm
Labels: Currently Testmerged

#3153 requested by sillycowns
  code/modules/catalogue/cataloguer.dm
Labels: Currently Testmerged

#3155 fixes mech equipment examining
  code/game/mecha/equipment/mecha_equipment.dm
Labels: Currently Testmerged

#3154 fixes mech examining
  code/game/mecha/mecha.dm
Labels: Currently Testmerged

#3094 I Have Certain Tastes That Some Might Consider...Unorthodox. (Adds Roach Burgers and Roach Mobs.)
  _maps/planet_levels/140x140/tradeport.dmm
  code/game/objects/structures/trash_pile.dm
  code/modules/ai/say_list.dm
  code/modules/events/hostile_migration_vr.dm
  code/modules/food/food/snacks.dm
  code/modules/food/recipes_microwave.dm
  code/modules/mob/holder.dm
  code/modules/mob/living/simple_mob/subtypes/animal/roach/roach.dm
  icons/mob/animal.dmi
  icons/obj/food.dmi
  vorestation.dme
Labels: Currently Testmerged, Map Edit, Sprites

#3148 Comments out the Brand Intelligence event
  code/modules/events/event_container.dm
Labels: Removal

#3157 ports new communicators from vorestation
  _maps/submaps/level_specific/class_h/AuxiliaryResearchFacility.dmm
  code/__DEFINES/flags/interaction_flags.dm
  code/_onclick/other_mobs.dm
  code/datums/datacore.dm
  code/datums/outfits/outfit.dm
  code/defines/obj.dm
  code/game/atoms.dm
  code/game/machinery/computer/card.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/security.dm
  code/game/machinery/computer/skills.dm
  code/game/machinery/computer3/computers/medical.dm
  code/game/machinery/computer3/computers/security.dm
  code/game/machinery/cryopod.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/communicator/UI.dm
  code/game/objects/items/devices/communicator/UI_tgui.dm
  code/game/objects/items/devices/communicator/cartridge.dm
  code/game/objects/items/devices/communicator/communicator.dm
  code/game/objects/items/devices/communicator/helper.dm
  code/game/objects/items/devices/communicator/messaging.dm
  code/game/objects/items/devices/communicator/phone.dm
  code/game/objects/items/weapons/melee/energy.dm
  code/game/objects/items/weapons/towels.dm
  code/modules/food/kitchen/cooking_machines/grill.dm
  code/modules/mob/dead/observer/free_vr.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/silicon/pai/software_modules.dm
  code/modules/nifsoft/software/14_commlink.dm
  code/modules/resleeving/infomorph_software.dm
  code/modules/shuttles/landmarks.dm
  code/modules/tgui/modules/admin_shuttle_controller.dm
  code/modules/tgui/modules/agentcard.dm
  code/modules/tgui/modules/alarm.dm
  code/modules/tgui/modules/appearance_changer.dm
  code/modules/tgui/modules/appearance_changer_vr.dm
  code/modules/tgui/modules/atmos_control.dm
  code/modules/tgui/modules/communications.dm
  code/modules/tgui/modules/crew_manifest.dm
  code/modules/tgui/modules/law_manager.dm
  code/modules/tgui/modules/ntos-only/cardmod.dm
  code/modules/tgui/modules/ntos-only/configurator.dm
  code/modules/tgui/modules/ntos-only/email.dm
  code/modules/tgui/modules/ntos-only/uav.dm
  code/modules/tgui/modules/overmap.dm
  code/modules/tgui/modules/power_monitor.dm
  code/modules/tgui/modules/rcon.dm
  code/modules/tgui/modules/teleporter.dm
  code/modules/tgui/states/vorepanel_vr.dm
  icons/obj/device.dmi
  icons/obj/device_alt.dmi
  maps/tether/tether_jobs.dm
  tgui/.gitignore
  tgui/packages/tgui/constants.js
  tgui/packages/tgui/interfaces/Communicator.js
  tgui/packages/tgui/interfaces/CrewManifest.js
  tgui/public/tgui-common.bundle.js
  tgui/public/tgui.bundle.js
  vorestation.dme
Labels: Currently Testmerged, Map Edit, Sprites, UI

#3158 Delete docker_publish.yml
  .github/workflows/docker_publish.yml
Labels: Currently Testmerged, GitHub

#3165 Replaces wood, steel, and glass with 2x50spawners
  _maps/map_files/triumph/triumph-01-deck1.dmm
Labels: Map Edit

#3167 Comments out Brand Intelligence part 2
  code/modules/events/event_container_vr.dm
Labels: Removal

#3162 JESUS CHRIST GRAMMAR CHECK YOUR CODE
  code/modules/busy_space/air_traffic.dm
Labels: Currently Testmerged

#3168 Adds a Colorable Leotard and Turtleneck Variant to the Underwear Selection
  code/datums/underwear/bottom.dm
  icons/mob/human.dmi
Labels: Currently Testmerged, Sprites

#3160 Early May Bugfixes
  code/game/objects/structures/trash_pile.dm
  code/modules/food/recipes_microwave.dm
Labels: Currently Testmerged

#3171 Updates nanoui assets to baystation12's version
  nano/css/icons.css
  nano/css/layout_default.css
  nano/css/shared.css
  nano/css/shared_vr.css
  nano/js/nano_base_callbacks.js
  nano/js/nano_base_helpers.js
  nano/js/nano_state.js
Labels: Code Improvement, Currently Testmerged

#3169 fixes communicators showing the wrong messages
  code/game/objects/items/devices/communicator/UI_tgui.dm
Labels: Currently Testmerged

#3174 Adds the Ability to Roll Colored Kimonos Up Like Miniskirts
  code/modules/clothing/clothing.dm
  icons/mob/uniform_rolled_down.dmi
Labels: Currently Testmerged, Sprites

#3172 adds music to jukebox
  config_static/jukebox.json
Labels: Config Update, Currently Testmerged, Feature

#3181 fix greater slime crystals and disposable teleporters
  code/__HELPERS/areas.dm
  code/game/area/areas.dm
Labels: Currently Testmerged

#3182 fixes some boolean logic
  code/modules/vore/eating/living_vr.dm
Labels: Currently Testmerged

#3184 Removes random frosted window in security showers
  _maps/map_files/triumph/triumph-04-deck4.dmm
Labels: Currently Testmerged, Map Edit, Removal

#3185 mark datum is now global
  code/modules/admin/view_variables/mark_datum.dm
Labels: Currently Testmerged

#3159 ports kinetic accelerators from main any% speedrun
  code/__DEFINES/atmospherics/atmospheres.dm
  code/__DEFINES/dcs/flags.dm
  code/datums/elements/conflict_checking.dm
  code/modules/atmospherics/atmosphere/_atmosphere.dm
  code/modules/mining/ore_redemption_machine/equipment_vendor.dm
  code/modules/power/cell.dm
  code/modules/power/cells/device_cells.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
Labels: Currently Testmerged, Sprites

#3136 The Relapse Update: Glukoz Pharmavendors and Bespoke Injectors
  _maps/planet_levels/140x140/tradeport.dmm
  code/datums/outfits/jobs/security.dm
  code/game/jobs/job/security.dm
  code/game/machinery/vending.dm
  code/game/objects/structures/loot_piles.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  icons/obj/syringe.dmi
  icons/obj/vending.dmi
Labels: Currently Testmerged, Map Edit, Sprites

#3178 [RFM]Off-duty command
  code/game/jobs/job/captain.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/offduty.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/game/machinery/computer/timeclock_vr.dm
Labels: Code Improvement, Currently Testmerged, Feature

#3179 Diona/no slip species fix
  code/game/area/areas.dm
  code/modules/hydroponics/grown.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
Labels: Currently Testmerged, Fix

#3187 soulcatchers can now examine
  code/_onclick/click.dm
  code/modules/mob/mob.dm
  code/modules/nifsoft/software/13_soulcatcher.dm
Labels: Currently Testmerged

#3189 Adds a requested song
  config_static/jukebox.json
Labels: Config Update, Currently Testmerged

#3188 Adds one new swimsuit
  code/modules/clothing/under/miscellaneous.dm
  code/modules/vore/fluffstuff/custom_boxes.dm
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Currently Testmerged, Feature, Sprites

#3192 cataloguers now have infinite point sharing range
  code/modules/catalogue/cataloguer.dm
Labels: Currently Testmerged

#3200 Tether: Compliable and Loading
  _maps/map_files/tether/tether-03-surface3.dmm
  _maps/map_files/tether/tether-05-station1.dmm
  _maps/map_files/tether/tether-06-station2.dmm
  _maps/map_files/tether/tether-07-station3.dmm
  _maps/map_files/tether/tether_misc.dmm
Labels: Fix, Map Edit

#3186 potential examine fix for soulcatchers let's see if this works if it doesn't uhhhh this'll be a bad time
  code/modules/mob/mob.dm
Labels: Currently Testmerged

#3190 fixes soulcatcher projections being visible to everyone
  code/modules/nifsoft/software/13_soulcatcher.dm
Labels: Currently Testmerged

#3196 fixes vore not working unless you have mobvore on
  modular_citadel/code/modules/vore/eating/living_vr.dm
  vorestation.dme
Labels: Currently Testmerged

#3197 Makes the cigarette but icon slightly larger which might look weird but I HATE clicking butts from assholes who leave them around everywhere
  icons/obj/clothing/masks.dmi
Labels: Sprites

#3199 adds 3 more songs to the jukebox (i'm not being held hostage)
  config_static/jukebox.json
Labels: Config Update, Currently Testmerged

#3204 Adds 27 New Emotes
  icons/emoji_32.dmi
Labels: Currently Testmerged, Feature, Sprites

#3203 Update items.dmi
  icons/obj/items.dmi
Labels: Currently Testmerged, Sprites

#3201 updates instrument toggle string to be more consistent with others
  code/modules/client/preferences_toggle_procs.dm
Labels: Currently Testmerged

#3198 [RFTM]Adds a way to obtain eggs so I can keep smashing Tys
  code/game/machinery/biogenerator.dm
Labels: Currently Testmerged, Feature

#3207 Removes stunswords from the sec armory
  _maps/map_files/triumph/triumph-04-deck4.dmm
Labels: Currently Testmerged, Map Edit, Removal

#3209 No com headset
  code/game/jobs/job/offduty.dm
Labels: Currently Testmerged, Fix

#3210 Allows buns and Modern to be tied
  code/modules/mob/new_player/sprite_accessories.dm
Labels: Currently Testmerged

#3212 fixes rsf plushie init
  code/game/objects/items/weapons/RSF.dm
Labels: Currently Testmerged

#3173 Changes to nutrition and fetish code
  code/__DEFINES/chemistry.dm
  code/modules/food/food/snacks.dm
  code/modules/mob/living/carbon/human/examine.dm
Labels: Code Improvement, Currently Testmerged, Removal, Testmerge Only, Work in Progress

#3202 Fixes Lavaland Atmos to Actually Work How It's Meant
  _maps/map_files/triumph/triumph-02-deck2.dmm
  _maps/planet_levels/140x140/lavaland.dmm
  _maps/submaps/mountains/quarantineshuttle.dmm
  code/game/objects/random/maintenance.dm
  code/game/objects/structures/loot_piles.dm
  code/game/objects/structures/trash_pile.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/xenoarcheaology/artifacts/replicator.dm
Labels: Currently Testmerged, Map Edit

#3191 Adds Curtains Between the Sauna and Pool, and adds an Onsen to Gaia
  _maps/map_files/triumph/triumph-04-deck4.dmm
  _maps/planet_levels/140x140/gaia_planet.dmm
Labels: Currently Testmerged, Map Edit
