Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2021-11, with the labels that each got.

#3578 TGMC Xenosprites and sprite changer
  code/game/objects/items/spritechanger.dm
  icons/2x2_Xenos.dmi
  vorestation.dme
Labels: Currently Testmerged, Feature, Sprites

#3575 Debloats the manifest
  code/game/jobs/job/captain.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/exploration.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/offduty.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
Labels: Currently Testmerged

#3586 XDUCMCUCM -- the name of this commit (it's a hair pr)
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
  icons/mob/human_face_m.dmi
Labels: Sprites

#3582 Resprites the medical Voidsuit, adds Navy jackets, a striped jacket, a smooth grey jumpsuit
  code/datums/supplypacks/voidsuits.dm
  code/game/machinery/vending.dm
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/clothing/spacesuits/void/station.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/accessories/clothing.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/head.dmi
  icons/mob/spacesuit.dmi
  icons/mob/suit.dmi
  icons/mob/ties.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/spacesuits.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/ties.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Currently Testmerged, Sprites

#3585 Revert "Debloats the manifest"
  code/game/jobs/job/captain.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/exploration.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/offduty.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
Labels: Revert

#3584 Fixes Roaches becoming Jesus
  code/modules/mob/living/simple_mob/subtypes/animal/roach/roach.dm
Labels: Currently Testmerged, Fix

#3580 Mountain (V4 Caves) POI Fixes. This time with less bad ayylien ship variables
  _maps/submaps/mountains/Cliff1.dmm
  _maps/submaps/mountains/Geyser1.dmm
  _maps/submaps/mountains/Geyser2.dmm
  _maps/submaps/mountains/Geyser3.dmm
  _maps/submaps/mountains/crashed_ufo.dmm
  _maps/submaps/mountains/crashed_ufo_frigate.dmm
  _maps/submaps/mountains/lava_trench.dmm
  _maps/submaps/mountains/vault6.dmm
  code/modules/maps/generic/submaps/mountains/mountains_areas.dm
Labels: Currently Testmerged, Map Edit

#3574 Adds meme gun
  code/game/objects/structures/trash_pile.dm
  code/modules/projectiles/guns/energy/sizegun_vr.dm
  vorestation.dme
Labels: Currently Testmerged, Refactor, Feature

#3487 [PORT] Atmospheric Retention Field Generators
  code/game/area/areas.dm
  code/game/machinery/atm_ret_field.dm
  code/game/machinery/frame.dm
  code/game/objects/items/stacks/sandbag.dm
  code/game/objects/items/weapons/circuitboards/frame.dm
  code/game/objects/structures.dm
  code/modules/research/designs/circuits/circuits.dm
  code/modules/tables/tables.dm
  icons/obj/atm_fieldgen.dmi
  icons/obj/stock_parts.dmi
  vorestation.dme
Labels: Currently Testmerged

#3579 Creates Virgo3b Atmos Subsets for Wood and Sifwood Turfs for POI Mapping.
  maps/tether/tether_turfs.dm
Labels: Currently Testmerged, Feature

#3590 Drink Vendor Additions
  code/game/machinery/vending.dm
  code/modules/food/food/cans.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  icons/obj/drinks.dmi
  sound/items/drop/ramunedrop.ogg
Labels: Currently Testmerged, Fix, Feature, Sprites, Sound

#3591 custom drink opening sound qol
  code/modules/food/food/drinks.dm
  code/modules/food/food/drinks/bottle.dm
Labels: Currently Testmerged

#3589 Class D Planet Reimplementation (Now Virgo 5!)
  _maps/map_levels/140x140/Class_D.dmm
  _maps/submaps/level_specific/class_d/DecoupledEngineD.dmm
  _maps/submaps/level_specific/class_d/EpodD.dmm
  _maps/submaps/level_specific/class_d/Possesed_mech_cave.dmm
  _maps/submaps/level_specific/class_d/SupplyDrop1D.dmm
  _maps/submaps/level_specific/class_d/SupplyDrop2D.dmm
  _maps/submaps/level_specific/class_d/broken_reactor_D.dmm
  _maps/submaps/level_specific/class_d/cave1D.dmm
  _maps/submaps/level_specific/class_d/cave2D.dmm
  _maps/submaps/level_specific/class_d/cave3D.dmm
  _maps/submaps/level_specific/class_d/drone_hive_D.dmm
  _maps/submaps/level_specific/class_d/hiddenbunkerD.dmm
  _maps/submaps/level_specific/class_d/landing_padD.dmm
  _maps/submaps/level_specific/class_d/matdropD.dmm
  _maps/submaps/level_specific/class_d/mechwreckD.dmm
  _maps/submaps/level_specific/class_d/meteor.dmm
  _maps/submaps/level_specific/class_d/solar_farmD.dmm
  _maps/submaps/level_specific/class_d/vault1D.dmm
  _maps/submaps/level_specific/class_d/vault2D.dmm
  _maps/submaps/level_specific/class_d/vault3D.dmm
  _maps/submaps/level_specific/class_d/vault4D.dmm
  _maps/submaps/level_specific/class_d/vault5D.dmm
  code/__DEFINES/atmospherics/atmospheres.dm
  code/game/area/Off Station Areas.dm
  code/modules/maps/misc_maps/planets/levels/classd.dm
  code/modules/maps/misc_maps/planets/submaps/class_d.dm
  code/modules/maps/misc_maps/planets/weather/class_d_weather_holder.dm
  code/modules/maps/tether/lateload.dm
  code/modules/maps/triumph/levels/classd.dm
  code/modules/mob/living/simple_mob/subtypes/humanoid/possessed.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/mecha/ripley.dm
  maps/nsv_triumph/triumph_overmap.dm
  maps/tether/tether.dm
  maps/tether/tether_class_d_weather_holder.dm
  maps/tether/tether_defines.dm
  vorestation.dme
Labels: Currently Testmerged, Map Edit

#3600 Fixes the custom species "moth fluff and antennae" ear types
  icons/mob/vore/ears_vr.dmi
Labels: Fix, Sprites

#3594 grrr talon grrrrrrr (more like grr whoever ported overmaps didn't port radio outage events properly grrr)
  code/modules/events/communications_blackout.dm
Labels: Currently Testmerged
