Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2021-07, with the labels that each got.

#3206 Removes contamination from Black-Eyed Shadekin
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
Labels: Currently Testmerged, Removal

#3208 Mitz's Culinary Adventures Vol. 1: M i l k and J u i c e
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/reagents/Drink-Recipes.dm
Labels: Feature, Fix, Grammar and Formatting

#3214 makes draketaur loaf sprite look mildly better
  icons/mob/vore/taurs_vr.dmi
Labels: Currently Testmerged, Sprites

#3215 Makes '*chuckle' to 'chuckles.' instead of laugh
  code/modules/mob/living/carbon/human/emote.dm
Labels: Currently Testmerged, Fix

#3216 Rainbow Station Thirteen: Siege
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/nuclear.dm
  code/modules/projectiles/guns/energy/particle.dm
  code/modules/projectiles/guns/energy/pulse.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/guns/energy/stun.dm
  code/modules/projectiles/guns/energy/temperature.dm
  code/modules/projectiles/guns/launcher/crossbow.dm
  code/modules/projectiles/guns/launcher/grenade_launcher.dm
  code/modules/projectiles/guns/launcher/pneumatic.dm
  code/modules/projectiles/guns/launcher/rocket.dm
  code/modules/projectiles/guns/magnetic/magnetic.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/boltaction.dm
  code/modules/projectiles/guns/projectile/caseless.dm
  code/modules/projectiles/guns/projectile/semiauto.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  code/modules/projectiles/guns/projectile/sniper.dm
Labels: Currently Testmerged

#3219 Dionea arent plants, they shouldnt suffer like one
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
Labels: Currently Testmerged, Fix

#3220 Adds Vulkan Brassworks Inc. Clockwork Prosthetics.
  code/modules/organs/robolimbs.dm
  icons/mob/human_races/cyberlimbs/_fluff_vr/brassworks.dmi
Labels: Currently Testmerged, Feature, Sprites

#3224 Exploration Edits
  _maps/map_files/tether/tether-06-station2.dmm
Labels: Map Edit

#3225 Update fueldepot.dmm
  _maps/map_levels/140x140/fueldepot.dmm
Labels: Fix, Map Edit

#3226 Prevents falling through catwalks and lattice,
  code/modules/multiz/movement.dm
Labels: Fix

#3228 Talon Changes and Additions
  _maps/map_levels/140x140/talon/talon1.dmm
  _maps/map_levels/140x140/talon/talon2.dmm
  code/modules/maps/talon/talon.dm
  code/modules/maps/talon/talon_areas.dm
Labels: Feature, Fix, Map Edit

#3229 properly uses the **right** name on the sponsor button
  .github/FUNDING.yml
Labels: GitHub

#3231 fixes synth bodyparts persisting between charslots (again)
  code/modules/client/preference_setup/general/03_body.dm
Labels: Fix

#3218 Adds One Hairstyle (Variation)
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_face.dmi
  icons/mob/human_face_m.dmi
Labels: Currently Testmerged, Feature, Sprites

#3221 fixes orbits on 514
  code/__DEFINES/dcs/signals.dm
  code/datums/components/orbiter.dm
  code/game/atoms_movable.dm
  code/modules/mob/dead/observer/observer.dm
Labels: Currently Testmerged

#3222 mobs are no longer HARDDEL_NOW for performance reasons because the occasional bugged player is a small price to pay for server speedups.
  code/modules/mob/mob.dm
Labels: Currently Testmerged

#3241 fixes issue #3227
  code/game/objects/items/devices/scanners.dm
Labels: Fix

#3244 this should fix issue #3213
  code/modules/food/recipes_microwave.dm
Labels: Fix

#3236 Hos suit
  _maps/map_files/tether/tether-03-surface3.dmm
Labels: Map Edit

#3242 Fixes a few issues with mirrors
  code/modules/mob/new_player/new_player.dm
  code/modules/resleeving/mirror.dm
  code/modules/surgery/implant.dm
Labels: Currently Testmerged

#3238 diagonal moves are now euclidean
  code/__DEFINES/math.dm
  code/modules/mob/mob_movement.dm
Labels: Balance/Rebalance, Currently Testmerged

#3245 rebalances proteans. again.
  code/modules/mob/living/carbon/human/species/station/protean/protean_blob.dm
  code/modules/mob/living/carbon/human/species/station/protean/protean_powers.dm
  code/modules/mob/living/carbon/human/species/station/protean/protean_species.dm
  code/modules/organs/organ_external.dm
  code/modules/organs/subtypes/nano.dm
Labels: Balance/Rebalance, Currently Testmerged

#3246 Changes to engine submap SMES units.
  _maps/map_files/tether/tether-05-station1.dmm
  _maps/templates/engines/tether/engine_rust.dmm
  _maps/templates/engines/tether/engine_singulo.dmm
  _maps/templates/engines/tether/engine_sme.dmm
  _maps/templates/engines/tether/engine_tesla.dmm
  code/modules/power/smes.dm
  code/modules/power/smes_construction.dm
Labels: Balance/Rebalance, Currently Testmerged, Feature, Map Edit

#3243 Players rejoice, non-client simplemobs no longer buzz doors they bump.
  code/game/machinery/doors/door.dm
Labels: Currently Testmerged

#3234 Removes R&D console access lock other than for locking and syncing
  code/modules/research/rdconsole.dm
Labels: Balance/Rebalance, Currently Testmerged, Removal

#3237 cyborg rechargers now charge 20 nutrition per tick instead of 10
  code/game/machinery/rechargestation.dm
Labels: Balance/Rebalance, Currently Testmerged

#3250 Various alt titles removed after being erroneously re-added or making…
  code/game/jobs/job/assistant.dm
  code/game/jobs/job/civilian_chaplain.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/exploration.dm
  code/game/jobs/job/security.dm
Labels: Currently Testmerged, Removal

#3251 silicons can now see AR projections
  code/modules/mob/living/silicon/login.dm
Labels: Currently Testmerged

#3248 Tether Re-Map Part 1 of X: Centcomm and the Tram
  _maps/map_files/tether/tether_misc.dmm
Labels: Currently Testmerged, Map Edit

#3253 make indoor fishing work??
  code/modules/fishing/fishing.dm
Labels: Currently Testmerged, Fix

#3254 Tether Re-Map Part 2 of X: Toxins, Solars and UD.
  _maps/map_files/tether/tether-08-mining.dmm
  _maps/map_files/tether/tether-09-solars.dmm
  _maps/map_files/tether/tether_underdark.dmm
Labels: Currently Testmerged, Map Edit

#3255 fixes singularities ignoring containment fields. singularities are now damaged by explosions. bags of holding now detonate upon being eaten by a singularity.
  code/__HELPERS/unsorted.dm
  code/game/objects/items/storage/backpack.dm
  code/modules/power/singularity/act.dm
  code/modules/power/singularity/singularity.dm
Labels: Currently Testmerged, Feature, Fix

#3261 maybe ZAS stun time shouldn't be 2x the ZAS stun cooldown, that kind of ruins the point of having a cooldown doesn't it?
  code/modules/atmospherics/zas/Airflow.dm
Labels: Currently Testmerged

#3264 Maint Pros Fab Replacement/fix
  _maps/map_files/tether/tether-02-surface2.dmm
Labels: Currently Testmerged, Good First PR, Map Edit

#3252 protean blobs can now see AR projections
  code/modules/mob/living/carbon/human/species/station/protean/protean_blob.dm
Labels: Currently Testmerged

#3233 Adds ear protection to every bowman headset
  code/game/objects/items/devices/radio/headset.dm
Labels: Currently Testmerged

#3267 Fix shuttle sensor console printing out blank paper
  code/modules/overmap/ships/computers/sensors.dm
Labels: Currently Testmerged, Fix

#3268 fixes ambient occlusion
  code/__DEFINES/lighting.dm
Labels: Currently Testmerged

#3258 make drills unload properly
  code/modules/mining/drilling/drill.dm
Labels: Currently Testmerged, Fix

#3272 welp. i'm done. rewrites protean damages again.
  code/modules/clothing/spacesuits/rig/suits/alien.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species/species_shapeshift.dm
  code/modules/mob/living/carbon/human/species/station/protean/protean_blob.dm
  code/modules/mob/living/carbon/human/species/station/protean/protean_powers.dm
  code/modules/mob/living/carbon/human/species/station/protean/protean_species.dm
  code/modules/organs/subtypes/nano.dm
Labels: Currently Testmerged

#3265 Disabled Nebula Gas Join Option (Z-Level Is Currently Disabled) / Adds Missing Spawn Points
  _maps/map_levels/140x140/talon/talon1.dmm
  code/game/trader_visit.dm
  code/modules/admin/admin_verbs.dm
Labels: Currently Testmerged, Feature, Map Edit, Removal

#3249 Removes Some Vestigial KHI References
  code/modules/looking_glass/lg_console.dm
  code/modules/vore/fluffstuff/guns/nsfw.dm
Labels: Currently Testmerged, Removal

#3274 Talon Restored/Tradified
  _maps/map_levels/140x140/talon/talon1.dmm
  _maps/map_levels/140x140/talon/talon2.dmm
Labels: Currently Testmerged, Map Edit

#3276 Teshari updates no-one asked for
  code/modules/mob/language/station.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/station/teshari.dm
  code/modules/mob/living/living.dm
  code/modules/multiz/movement.dm
  icons/mob/species/teshari/ties.dmi
Labels: Currently Testmerged, Feature, Sprites

#3269 Consolidates Asteroid into 2 Z Levels
  _maps/map_files/tether/tether-01-surface1.dmm
  _maps/map_files/tether/tether-02-surface2.dmm
  _maps/map_files/tether/tether-03-surface3.dmm
  _maps/map_files/tether/tether-04-transit.dmm
  _maps/map_files/tether/tether-05-station1.dmm
  _maps/map_files/tether/tether-06-station2.dmm
  _maps/map_files/tether/tether-07-station3.dmm
  _maps/map_files/tether/tether-08-mining.dmm
  _maps/tether.json
  icons/_nanomaps/tether_nanomap_z3.png
  icons/_nanomaps/tether_nanomap_z4.png
  icons/_nanomaps/tether_nanomap_z6.png
  icons/_nanomaps/tether_nanomap_z7.png
  maps/tether/tether.dm
  maps/tether/tether_areas.dm
  maps/tether/tether_defines.dm
  maps/tether/tether_things.dm
Labels: Currently Testmerged, Map Edit, Removal, Sprites

#3284 KAs now work at -10C instead of -20C, because tether is somehow -19.8C
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
Labels: Currently Testmerged

#3283 Fixes to the plantery day/night cycles and weather effects
  code/controllers/subsystems/planets.dm
  code/modules/multiz/turf.dm
  maps/tether/tether.dm
  maps/tether/tether_virgo3b.dm
  maps/tether/tether_virgo4.dm
  vorestation.dme
Labels: Currently Testmerged, Fix

#3287 removes a really weird song from the jukebox
  config_static/jukebox.json
Labels: Config Update, Removal

#3286 reverts shield power usage nerfs
  code/modules/shieldgen/shield_gen.dm
Labels: Currently Testmerged, Revert

#3271 (WIP) Oh god I finally caved and did it. I decided to change all the alcohol recipies.
  code/game/machinery/vending.dm
  code/modules/food/drinkingglass/metaglass.dm
  code/modules/food/food/drinks/bottle.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/reagents/Drink-Recipes.dm
  code/modules/reagents/machinery/dispenser/cartridge_presets.dm
  code/modules/reagents/machinery/dispenser/dispenser_presets.dm
  code/modules/reagents/machinery/dispenser/supply.dm
  icons/obj/drinks.dmi
Labels: Currently Testmerged, Sprites

#3290 wintercoats and epxlorer suits now have PHORONGUARD again
  code/modules/clothing/suits/hooded.dm
Labels: Currently Testmerged

#3291 Fixes Solar-Side UD Entrance
  _maps/map_files/tether/tether-09-solars.dmm
Labels: Currently Testmerged, Fix, Map Edit

#3277 Smell System
  code/modules/vore/eating/living_vr.dm
  code/modules/vore/eating/vore_vr.dm
  code/modules/vore/eating/vorepanel_vr.dm
Labels: Currently Testmerged, Feature, Fix

#3217 Ports /vg/station's Roomba and Maid Roomba Bots WIP
  code/modules/mob/living/bot/cleanbot.dm
  icons/obj/aibots.dmi
Labels: Currently Testmerged, Feature, Sprites

#3294 Update species_shapeshift.dm
  code/modules/mob/living/carbon/human/species/species_shapeshift.dm
Labels: Currently Testmerged, Priority: High

#3292 Fixes Lever Action Rifles
  code/modules/projectiles/guns/projectile/boltaction.dm
Labels: Currently Testmerged, Fix

#3289 Improving the Exploration Shuttle, the Exploration Hangar and the Pilot's Lounge
  _maps/map_files/tether/tether-06-station2.dmm
  code/game/turfs/simulated/floor_types_eris.dm
Labels: Balance/Rebalance, Currently Testmerged, Feature, Map Edit

#3285 Stand By for Funfall: Data Knives, Vox Plushies, Constructable Surgery Tables, Skateboards, and Dakis
  code/datums/supplypacks/misc.dm
  code/game/machinery/OpTable.dm
  code/game/machinery/frame.dm
  code/game/machinery/vending.dm
  code/game/objects/items/storage/misc.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/weapons/circuitboards/frame.dm
  code/game/objects/items/weapons/material/knives.dm
  code/game/objects/items/weapons/melee/misc.dm
  code/modules/clothing/head/helmet.dm
  code/modules/materials/material_recipes.dm
  code/modules/vehicles/skateboard.dm
  icons/mob/head.dmi
  icons/mob/items/lefthand_melee.dmi
  icons/mob/items/righthand_melee.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/items.dmi
  icons/obj/kitchen.dmi
  icons/obj/stock_parts.dmi
  icons/obj/toy.dmi
  icons/obj/vehicles.dmi
  icons/obj/weapons.dmi
  sound/weapons/skateboard_ollie.ogg
  sound/weapons/skateboard_roll.ogg
  vorestation.dme
Labels: Currently Testmerged, Feature, Sound, Sprites

#3296 Readded some lost alt_titles, added some new ones, and ported the Xenobotanist job
  code/game/jobs/access_datum.dm
  code/game/jobs/job/assistant.dm
  code/game/jobs/job/captain.dm
  code/game/jobs/job/cargo.dm
  code/game/jobs/job/civilian.dm
  code/game/jobs/job/civilian_chaplain.dm
  code/game/jobs/job/department.dm
  code/game/jobs/job/department_vr.dm
  code/game/jobs/job/engineering.dm
  code/game/jobs/job/exploration.dm
  code/game/jobs/job/job.dm
  code/game/jobs/job/medical.dm
  code/game/jobs/job/science.dm
  code/game/jobs/job/security.dm
  code/game/jobs/job/silicon.dm
  code/game/jobs/job/special.dm
Labels: Currently Testmerged, Feature, Fix, Removal

#3288 Tether Remap Part 3 of X: Surface Tether: Attempt 2
  _maps/map_files/tether/tether-01-surface1.dmm
  _maps/map_files/tether/tether-02-surface2.dmm
  _maps/map_files/tether/tether-03-surface3.dmm
  code/game/turfs/unsimulated/beach.dm
  code/modules/fishing/fishing.dm
  code/modules/mob/living/simple_mob/subtypes/vore/rat.dm
  maps/tether/tether_areas.dm
  maps/tether/tether_turfs.dm
Labels: Currently Testmerged, Map Edit

#3295 All-new Vey-Med AR-V Goggles™ (plus alterations to the zoom() proc)
  code/game/objects/items.dm
  code/game/objects/structures/crates_lockers/closets/secure/explorer.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/mining/ore_redemption_machine/survey_vendor.dm
  icons/mob/eyes.dmi
  icons/obj/clothing/glasses.dmi
Labels: Code Improvement, Currently Testmerged, Feature, Sprites

#3300 adds a tail from citmain
  code/modules/vore/appearance/sprite_accessories_vr.dm
  icons/mob/human_races/sprite_accessories/tails.dmi
  icons/mob/vore/tails_vr.dmi
Labels: Currently Testmerged, Feature, Sprites

#3298 Makes Shields Behave Less Stupidly
  code/modules/shieldgen/emergency_shield.dm
Labels: Currently Testmerged

#3301 QOL - What if we hold hands behind the Fit-Viewport verb 😳
  code/__HELPERS/view.dm
  code/modules/client/preferences.dm
  code/modules/client/verbs/ooc.dm
Labels: Code Improvement, Currently Testmerged, Feature

#3303 Restores Acid and Blood Turfs
  _maps/map_files/tether/tether-09-solars.dmm
  code/game/atoms_movable.dm
  code/game/turfs/simulated/water.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/living_defense.dm
  icons/mob/submerged.dmi
Labels: Currently Testmerged, Feature, Map Edit, Sprites
