Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2021-02, with the labels that each got.

#2672 fixes FBP issues some more
  code/modules/mob/living/carbon/human/life.dm
Labels: Currently Testmerged, Fix

#2671 Fixes backup implant HUD overlay and mobs resizing on rest.
  code/__DEFINES/mobs.dm
  code/__DEFINES/mobs_vr.dm
  code/modules/clothing/glasses/glasses.dm
  code/modules/clothing/glasses/glasses_vr.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/mob/living/living.dm
  vorestation.dme
Labels: Currently Testmerged

#2660 adds local narration
  code/modules/admin/verbs/randomverbs.dm
Labels: Currently Testmerged, Feature

#2673 lets fix runtimes
  _maps/map_files/triumph/triumph-01-deck1.dmm
  code/game/area/areas.dm
  code/game/machinery/embedded_controller/airlock_docking_controller.dm
  code/game/machinery/embedded_controller/docking_program.dm
  code/game/mecha/space/shuttle.dm
  code/modules/modular_computers/hardware/battery_module.dm
  code/modules/overmap/ships/landable.dm
  code/modules/planet/weather.dm
  code/modules/shuttles/shuttle_autodock.dm
Labels: Currently Testmerged, Map Edit

#2677 Adds 100+ New Songs To The Jukebox
  code/game/machinery/jukebox.dm
  code/game/machinery/jukebox.json
  code/game/machinery/jukebox.txt
Labels: Currently Testmerged, Sound, Tweak

#2680 Jay's Jukebox Collection Pack 1 - The Demo Tapes: Side A
  code/game/machinery/jukebox.json
Labels: Currently Testmerged, Feature

#2663 Autocorrect
  code/__HELPERS/text.dm
  code/modules/client/preference_setup/global/setting_datums.dm
  code/modules/mob/living/say.dm
Labels: Currently Testmerged, Feature

#2655 Nerfs Baymiss and Buffs Intrinsic Accuracy Across the Board
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/nuclear.dm
  code/modules/projectiles/guns/energy/particle.dm
  code/modules/projectiles/guns/energy/phase.dm
  code/modules/projectiles/guns/energy/pulse.dm
  code/modules/projectiles/guns/magic/staff.dm
  code/modules/projectiles/guns/magic/wand.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/boltaction.dm
  code/modules/projectiles/guns/projectile/semiauto.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  code/modules/projectiles/guns/projectile/sniper.dm
Labels: Currently Testmerged

#2658 Vox Captain Damage Buff and Vox Ion Mob Addition
  code/datums/outfits/pirates.dm
  code/modules/mob/living/simple_animal/corpse.dm
  code/modules/mob/living/simple_mob/subtypes/humanoid/mercs/mercs.dm
  icons/mob/animal.dmi
  maps/nsv_triumph/submaps/space/piratebase.dmm
Labels: Currently Testmerged, Sprites

#2664 Introduces Nano-Peridaxon
  code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/nurse.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
  code/modules/reagents/Chemistry-Recipes.dm
Labels: Currently Testmerged

#2668 Adds Sandstorm to Desert Weather Pool
  code/__DEFINES/planets.dm
  code/game/objects/items/weapons/storage/lockbox.dm
  code/modules/busy_space/organizations.dm
  code/modules/mining/ore_redemption_machine/survey_vendor.dm
  code/modules/planet/classh.dm
  icons/effects/weather.dmi
Labels: Currently Testmerged, Sprites

#2674 Shuttle Engines Now Use Fuel and Eleven Other Things
  _maps/map_files/triumph/triumph-02-deck2.dmm
  _maps/map_files/triumph/triumph-03-deck3.dmm
  _maps/map_files/triumph/triumph-04-deck4.dmm
  _maps/map_files/triumph/triumph-05-flagship.dmm
  code/datums/outfits/misc.dm
  code/game/objects/items/weapons/storage/belt.dm
  code/game/objects/structures/mirror.dm
  code/game/objects/structures/statues.dm
  code/game/turfs/simulated/outdoors/dirt.dm
  code/game/turfs/unsimulated/beach.dm
  code/modules/busy_space/organizations.dm
  code/modules/client/preference_setup/loadout/loadout_event_rewards.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/instruments/instruments/item.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mob/living/bot/farmbot.dm
  code/modules/mob/living/carbon/human/human_species.dm
  code/modules/mob/living/simple_animal/corpse.dm
  code/modules/overmap/ships/engines/gas_thruster.dm
  code/modules/reagents/reagent_containers/spray.dm
  icons/mob/belt.dmi
  icons/mob/head.dmi
  icons/mob/human_races/r_mannequin.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/belts.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/watercloset.dmi
  icons/turf/desert.dmi
  icons/turf/outdoors.dmi
  maps/nsv_triumph/submaps/poi_h/BoneyardH.dmm
  maps/nsv_triumph/submaps/poi_h/Class_H.dmm
  maps/nsv_triumph/submaps/poi_h/SupplyDrop1H.dmm
  maps/nsv_triumph/submaps/poi_h/cave1H.dmm
  maps/nsv_triumph/submaps/poi_h/desertruins1H.dmm
  maps/nsv_triumph/submaps/poi_h/desertruins2H.dmm
  maps/nsv_triumph/submaps/poi_h/desertruins3H.dmm
  maps/nsv_triumph/submaps/poi_h/desertruins4H.dmm
  maps/nsv_triumph/submaps/poi_h/farmsH.dmm
  maps/nsv_triumph/submaps/poi_h/h_world_things.dm
  maps/nsv_triumph/submaps/poi_h/highnoonH.dmm
  maps/nsv_triumph/submaps/poi_h/landing_padH.dmm
  maps/nsv_triumph/submaps/poi_h/minesH.dmm
  maps/nsv_triumph/submaps/poi_h/oasisH.dmm
  maps/nsv_triumph/submaps/poi_h/rocks1H.dmm
  maps/nsv_triumph/submaps/poi_h/rocks2H.dmm
  maps/nsv_triumph/submaps/poi_h/solar_farmH.dmm
  maps/nsv_triumph/submaps/poi_h/springcaveH.dmm
  maps/nsv_triumph/submaps/space/debris5.dmm
  maps/nsv_triumph/submaps/space/derelict.dmm
  maps/nsv_triumph/submaps/space/piratebase.dmm
  maps/nsv_triumph/submaps/space/trade_port/_tradeport.dm
  maps/nsv_triumph/submaps/space/trade_port/tradeport.dmm
  maps/nsv_triumph/triumph_overmap.dm
  maps/nsv_triumph/triumph_shuttle_defs.dm
Labels: Currently Testmerged, Map Edit, Sprites

#2682 adds lavaland
  _maps/map_files/triumph/triumph-02-deck2.dmm
  code/__DEFINES/atmospherics/atmospheres.dm
  code/__DEFINES/planets.dm
  code/__HELPERS/global_lists.dm
  code/game/objects/effects/landmarks.dm
  code/game/objects/explosion_recursive.dm
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/simulated/lava.dm
  code/modules/maps/tether/atmospheres/classd.dm
  code/modules/maps/tether/atmospheres/lavaland.dm
  code/modules/maps/tether/atmospheres/virgo3b.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mob/living/living_defense.dm
  code/modules/planet/lavaland.dm
  code/modules/random_map/automata/caves.dm
  icons/effects/effects.dmi
  icons/effects/weather.dmi
  maps/nsv_triumph/submaps/_triumph_submaps.dm
  maps/nsv_triumph/submaps/lavaland/_lavaland.dm
  maps/nsv_triumph/submaps/lavaland/_templates.dm
  maps/nsv_triumph/submaps/lavaland/boss1.dmm
  maps/nsv_triumph/submaps/lavaland/botany.dmm
  maps/nsv_triumph/submaps/lavaland/dogs.dmm
  maps/nsv_triumph/submaps/lavaland/horrors.dmm
  maps/nsv_triumph/submaps/lavaland/idleruins1.dmm
  maps/nsv_triumph/submaps/lavaland/idleruins2.dmm
  maps/nsv_triumph/submaps/lavaland/lavaland.dmm
  maps/nsv_triumph/submaps/lavaland/lavaland_atmos.dm
  maps/nsv_triumph/submaps/lavaland/shelter.dmm
  maps/nsv_triumph/submaps/poi_h/triumph/triumph-02-deck2.dmm
  maps/nsv_triumph/triumph_defines.dm
  maps/nsv_triumph/triumph_turfs.dm
  vorestation.dme
Labels: Currently Testmerged, Map Edit, Sprites

#2689 buffs dare dice
  modular_citadel/code/modules/games/dice.dm
Labels: Currently Testmerged, Fix

#2688 i'm not sure why the "power all apcs" button also drains the SMES but i'm annoyed enough to fix it
  code/game/gamemodes/events/power_failure.dm
  code/modules/power/smes.dm
Labels: Currently Testmerged, Fix

#2687 so about that one time someone got held down in dorms for 20 minutes in a neckgrab and got brain damage (removes oxygen damage from neck grabs, so only strangling will actually cause it)
  code/modules/mob/mob_grab.dm
Labels: Currently Testmerged, Removal

#2691 Bug fix
  _maps/map_files/triumph/triumph-01-deck1.dmm
  _maps/map_files/triumph/triumph-02-deck2.dmm
  _maps/map_files/triumph/triumph-03-deck3.dmm
  _maps/map_files/triumph/triumph-04-deck4.dmm
  maps/nsv_triumph/submaps/gaia_planet/gaia_planet.dmm
Labels: Currently Testmerged, Map Edit

#2685 Adds More Costumes
  code/datums/outfits/horror_killers.dm
  code/datums/supplypacks/costumes.dm
  code/datums/supplypacks/hydroponics.dm
  code/game/machinery/vending.dm
  code/game/objects/structures/crates_lockers/closets/job_closets.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/game/objects/structures/crates_lockers/closets/secure/engineering.dm
  code/game/objects/structures/crates_lockers/closets/secure/hydroponics.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/game/objects/structures/crates_lockers/closets/secure/scientist.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/client/preference_setup/loadout/loadout_head.dm
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/clothing/head/hood.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/shoes/magboots.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/bio.dm
  code/modules/clothing/suits/hooded.dm
  code/modules/clothing/suits/labcoat.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/color.dm
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/clothing/under/jobs/engineering.dm
  code/modules/clothing/under/jobs/medsci.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/clothing/under/shorts.dm
  code/modules/clothing/under/syndicate.dm
  code/modules/materials/material_recipes.dm
  code/modules/mob/living/carbon/human/human_species.dm
  icons/mob/feet.dmi
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Currently Testmerged, Sprites

#2692 salt pr: robots no longer have balls
  code/modules/mob/living/carbon/human/unarmed_attack.dm
Labels: Balance/Rebalance, Currently Testmerged

#2693 Rearranges the Kitchen
  _maps/map_files/triumph/triumph-02-deck2.dmm
Labels: Currently Testmerged, Map Edit

#2702 Relocates storage items into their own folder
  code/game/objects/items/storage/_storage.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/bags.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/bible.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/briefcase.dm
  code/game/objects/items/storage/fancy.dm
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/items/storage/internal.dm
  code/game/objects/items/storage/laundry_basket.dm
  code/game/objects/items/storage/lockbox.dm
  code/game/objects/items/storage/misc.dm
  code/game/objects/items/storage/mre.dm
  code/game/objects/items/storage/quickdraw.dm
  code/game/objects/items/storage/secure.dm
  code/game/objects/items/storage/toolbox.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/game/objects/items/storage/wallets.dm
  vorestation.dme
Labels: Currently Testmerged

#2700 Mild Protean un-fucky wucky-ing
  code/modules/mob/living/carbon/human/species/station/protean/protean_blob.dm
  code/modules/mob/living/carbon/human/species/station/protean/protean_powers.dm
  code/modules/mob/living/carbon/human/species/station/protean/protean_species.dm
Labels: Balance/Rebalance, Currently Testmerged, Feature, Tweak

#2696 changes NIF init order to make the soulcatcher/commlink hopefully AFTER the new character mob is spawned in, instead of before.
  code/modules/nifsoft/nif.dm
Labels: Currently Testmerged

#2695 makes soulcatcher verbs clientside
  code/modules/nifsoft/software/13_soulcatcher.dm
Labels: Currently Testmerged

#2694 fixes colormate matrix mode labels
  code/game/machinery/painter_vr.dm
Labels: Currently Testmerged

#2699 Adds a Recipe for Borg-O's.
  code/game/machinery/vending.dm
  code/game/objects/items/trash.dm
  code/game/objects/items/trash_vr.dm
  code/game/objects/items/weapons/id cards/station_ids.dm
  code/modules/client/preference_setup/loadout/loadout_head.dm
  code/modules/clothing/head/misc.dm
  code/modules/food/food/snacks.dm
  code/modules/food/food/snacks_vr.dm
  code/modules/food/recipes_microwave.dm
  icons/mob/head.dmi
  icons/obj/barsigns.dmi
  icons/obj/clothing/hats.dmi
  vorestation.dme
Labels: Currently Testmerged, Sprites

#2706 adds leotards to vendors
  code/game/machinery/vending.dm
Labels: Currently Testmerged

#2705 fixes bots and captive_brains not appearing in player panel
  code/__HELPERS/unsorted.dm
Labels: Currently Testmerged

#2711 Gives Vasilissans Intrinsic Numbing Venom
  code/modules/mob/living/carbon/human/species/station/station_special.dm
Labels: Currently Testmerged

#2720 fixes toxin weakness/resist traits causing runtimes
  code/modules/mob/living/carbon/human/species/station/traits/negative.dm
  code/modules/mob/living/carbon/human/species/station/traits/positive.dm
Labels: Currently Testmerged, Fix

#2716 Disables extools
  code/game/world.dm
Labels: Currently Testmerged

#2717 makes nanoui a namespaced asset to work on our web server
  code/modules/asset_cache/asset_list_items.dm
  code/modules/nano/nanoui.dm
Labels: Currently Testmerged

#2713 Reduces Armory Size & Armament
  _maps/map_files/triumph/triumph-04-deck4.dmm
  code/datums/supplypacks/security.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  icons/mob/items/lefthand_guns.dmi
  icons/mob/items/righthand_guns.dmi
  icons/obj/gun/ballistic.dmi
Labels: Currently Testmerged, Map Edit, Sprites

#2725 ports tritail kitsune tail
  code/modules/vore/appearance/sprite_accessories_vr.dm
  icons/mob/vore/tails_vr.dmi
Labels: Currently Testmerged, Feature, Sprites

#2721 fixes energy guns runtiming
  code/modules/projectiles/guns/energy.dm
Labels: Currently Testmerged

#2727 adds wooden circlets and all 4 types of flower crowns to the loadout by request
  code/modules/client/preference_setup/loadout/loadout_head.dm
Labels: Currently Testmerged, Feature

#2724 Adds the Vox sprites for wearing the CE Rig
  icons/mob/species/vox/head.dmi
  icons/mob/species/vox/suit.dmi
Labels: Currently Testmerged, Sprites

#2728 Couple of hair fixes
  icons/mob/human_face.dmi
  icons/mob/human_face_m.dmi
  icons/mob/human_face_or_vr.dmi
Labels: Currently Testmerged, Fix, Sprites

#2726 fixes proteans hunger rate 600% --> 80% per author request (woops)
  code/modules/mob/living/carbon/human/species/station/protean/protean_species.dm
Labels: Currently Testmerged, Tweak

#2733 minor autocorrect fix
  code/__HELPERS/text.dm
Labels: Currently Testmerged

#2734 kpa changes
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
Labels: Currently Testmerged, Tweak

#2729 what the fuck is atomization - fixes the last few tgui bugs
  code/game/objects/objs.dm
  code/modules/mob/emote.dm
  code/modules/mob/living/carbon/human/examine.dm
  tgui/packages/common/storage.js
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
  tgui/packages/tgui/interfaces/CrewMonitor.js
  tgui/public/tgui-common.chunk.js
  tgui/public/tgui-panel.bundle.css
  tgui/public/tgui.bundle.js
Labels: Currently Testmerged, Fix, UI

#2735 fixes tgui spamming the everloving fuck out of href logs
  code/modules/client/client_procs.dm
Labels: Currently Testmerged

#2732 Lavaland Should Spawn Rare Ore Now and Active Edge Fix?
  code/game/area/Off Station Areas.dm
  code/game/jobs/job/special.dm
  code/modules/maps/atmospheres/lavaland.dm
  code/modules/mob/living/simple_mob/subtypes/animal/space/bats.dm
  code/modules/mob/living/simple_mob/subtypes/humanoid/cultist.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/cyber_horror/cyber_horror.dm
  code/modules/mob/living/simple_mob/subtypes/occult/constructs/shade.dm
  code/modules/mob/living/simple_mob/subtypes/vore/corrupt_hounds.dm
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/guns/energy/stun.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  code/modules/vore/fluffstuff/custom_guns.dm
  icons/mob/items/lefthand_guns.dmi
  icons/mob/items/lefthand_guns_vr.dmi
  icons/mob/items/righthand_guns.dmi
  icons/mob/items/righthand_guns_vr.dmi
  icons/obj/gun/ballistic.dmi
  maps/nsv_triumph/submaps/lavaland/boss1.dmm
  maps/nsv_triumph/submaps/lavaland/botany.dmm
  maps/nsv_triumph/submaps/lavaland/dogs.dmm
  maps/nsv_triumph/submaps/lavaland/horrors.dmm
  maps/nsv_triumph/submaps/lavaland/idleruins1.dmm
  maps/nsv_triumph/submaps/lavaland/idleruins2.dmm
  maps/nsv_triumph/submaps/lavaland/lavaland.dmm
  maps/nsv_triumph/submaps/lavaland/shelter.dmm
  maps/nsv_triumph/submaps/space/derelict.dmm
  maps/nsv_triumph/submaps/space/ship_sci_overrun.dmm
Labels: Currently Testmerged, Sprites

#2697 [Touches Deck 3] Adds new exiting medicine for patches and replaces/reworks the old ones
  _maps/map_files/triumph/triumph-03-deck3.dmm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Topical.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/Topical-Recipes.dm
  code/modules/reagents/distilling/Distilling-Recipes.dm
  html/changelogs/AutoChangeLog-pr-2700.yml
  vorestation.dme
Labels: Currently Testmerged, Feature, Map Edit, Removal

#2737 radio chat colours darkmode readability improvements
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/public/tgui-panel.bundle.css
Labels: Currently Testmerged, Fix, UI

#2741 Removes R-UST 4 lines/second adminlog spam (on this episode of "shit coding practices, featuring log_debug")
  code/modules/power/fusion/core/core_field.dm
Labels: Currently Testmerged, Removal

#2736 replaces vorestation vore-vent preferences with a bitflagged event prefs with descriptions
  code/__DEFINES/flags/preferences.dm
  code/modules/admin/admin_verbs.dm
  code/modules/client/preference_setup/antagonism/02_candidacy.dm
  code/modules/client/preference_setup/vore/06_vantag.dm
  code/modules/client/preferences.dm
  vorestation.dme
Labels: Currently Testmerged, Feature

#2730 Map Updates - Deck 2 and 4. Now With 100% Less Pool-Shields
  _maps/map_files/triumph/triumph-02-deck2.dmm
  _maps/map_files/triumph/triumph-04-deck4.dmm
  code/datums/riding.dm
  code/game/turfs/simulated/water.dm
  code/game/turfs/turf.dm
  code/modules/maps/atmospheres/lavaland.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/simple_mob/simple_mob.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/leech.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Modifiers.dm
  code/modules/shieldgen/shield_gen_external.dm
  code/modules/vehicles/bike.dm
  code/modules/vehicles/quad.dm
  maps/submaps/surface_submaps/mountains/CaveTrench.dmm
  maps/submaps/surface_submaps/mountains/Cavelake.dmm
  maps/submaps/surface_submaps/mountains/SwordCave.dmm
  maps/submaps/surface_submaps/plains/PooledR.dmm
  maps/submaps/surface_submaps/plains/PooledR_vr.dmm
  maps/submaps/surface_submaps/plains/farm1.dmm
  maps/submaps/surface_submaps/plains/farm1_vr.dmm
  maps/submaps/surface_submaps/wilderness/DecoupledEngine.dmm
  maps/submaps/surface_submaps/wilderness/DoomP.dmm
  maps/submaps/surface_submaps/wilderness/Epod4.dmm
  maps/submaps/surface_submaps/wilderness/Flake.dmm
  maps/submaps/surface_submaps/wilderness/Rocky4.dmm
Labels: Currently Testmerged, Feature, Map Edit, Tweak

#2744 Adds fix-keybindings verb
  code/modules/keybindings/setup.dm
Labels: Currently Testmerged

#2747 note this will not fix emote italics - removes italics span from old stylesheet.dm's emotes
  interface/stylesheet.dm
Labels: Currently Testmerged, Removal

#2753 [Ready to merge]Removes Remnants of old touch chem recipes
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/distilling/Distilling-Recipes.dm
Labels: Code Improvement, Currently Testmerged, Removal

#2754 Adding 2 extra ear options for Species Customization
  code/modules/vore/appearance/sprite_accessories_vr.dm
  icons/mob/vore/ears_vr.dmi
Labels: Currently Testmerged, Feature, Sprites

#2755 Fixes overmap ships going 10 times slower than they should
  code/modules/overmap/ships/ship.dm
Labels: Currently Testmerged

#2756 lets randomize submap rotation less
  code/modules/maps/tg/map_template.dm
Labels: Currently Testmerged

#2748 might fix emote italics- rebuilds tgui
  tgui/public/tgui-panel.bundle.css
Labels: Currently Testmerged, Fix, UI

#2752 [RTM] Battery_Modules no longer override their battery on charge_to_full()
  code/modules/modular_computers/hardware/battery_module.dm
Labels: Currently Testmerged, Fix

#2757 Portals and Additions
  code/_onclick/click.dm
  code/datums/beam.dm
  code/game/atoms.dm
  code/game/objects/effects/chem/foam.dm
  code/game/objects/effects/decals/Cleanable/humans.dm
  code/game/objects/effects/effect_system.dm
  code/game/objects/effects/map_effects/portal.dm
  code/game/objects/effects/mines.dm
  code/game/objects/effects/step_triggers.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/toys.dm
  code/game/objects/items/weapons/clown_items.dm
  code/game/objects/items/weapons/material/shards.dm
  code/game/objects/items/weapons/traps.dm
  code/game/objects/structures/catwalk.dm
  code/modules/assembly/holder.dm
  code/modules/assembly/infrared.dm
  code/modules/assembly/mousetrap.dm
  code/modules/hydroponics/grown.dm
  code/modules/hydroponics/spreading/spreading_response.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species/shadekin/shadekin_abilities.dm
  code/modules/mob/living/simple_mob/subtypes/animal/passive/mouse.dm
  code/modules/mob/living/simple_mob/subtypes/vore/shadekin/shadekin.dm
  code/modules/multiz/movement.dm
  code/modules/projectiles/projectile.dm
  icons/effects/map_effects.dmi
  vorestation.dme
Labels: Currently Testmerged, Sprites

#2745 Apparently the last PR for Lavaland Broke It? Fixes that.
  code/game/objects/items/contraband.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/maps/atmospheres/lavaland.dm
  icons/mob/suit.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/items.dmi
  maps/nsv_triumph/submaps/lavaland/_lavaland.dm
  maps/nsv_triumph/submaps/lavaland/boss1.dmm
  maps/nsv_triumph/submaps/lavaland/lavaland.dmm
  maps/nsv_triumph/submaps/lavaland/shelter.dmm
  maps/nsv_triumph/submaps/mining_planet/mining_planet.dmm
  maps/nsv_triumph/triumph_turfs.dm
Labels: Currently Testmerged, Sprites

#2750 fixes an issue with proteans
  code/modules/mob/living/carbon/human/species/station/protean/protean_blob.dm
Labels: Fix

#2759 replaces sdql2 with main's sdql2 because that actually works
  code/modules/admin/verbs/SDQL2/SDQL_2.dm
  code/modules/admin/verbs/SDQL2/SDQL_2_parser.dm
  code/modules/admin/verbs/SDQL2/SDQL_2_wrappers.dm
Labels: Currently Testmerged

#2760 let's also replace cmd_admin_delete with main's because I just deleted someone on accident. Twice.
  code/modules/admin/verbs/randomverbs.dm
Labels: Currently Testmerged

#2749 adds matrix recolor gear tweaks to everything
  code/datums/browser/color_matrix_picker.dm
  code/modules/client/preference_setup/loadout/gear_tweaks.dm
  code/modules/client/preference_setup/loadout/loadout.dm
  vorestation.dme
Labels: Currently Testmerged, Feature

#2743 Taser Rework
  code/modules/projectiles/guns/energy/stun.dm
  code/modules/projectiles/projectile/beams.dm
  icons/mob/items/lefthand_guns.dmi
  icons/mob/items/righthand_guns.dmi
  icons/obj/projectiles.dmi
Labels: Currently Testmerged, Sprites

#2764 Adds Ursa's Off the Shoulder Undershirt
  code/datums/underwear/undershirts.dm
  icons/mob/human.dmi
Labels: Currently Testmerged, Sprites

#2766 masks no longer block your ability to use swabkits on hands
  code/modules/detectivework/tools/swabs.dm
Labels: Currently Testmerged, Fix, Tweak

#2767 protean temps
  code/modules/mob/living/carbon/human/life.dm
Labels: Currently Testmerged

#2770 Fixes Fishing for Deck Four
  _maps/map_files/triumph/triumph-04-deck4.dmm
  code/game/machinery/computer/communications.dm
  code/modules/client/preference_setup/loadout/loadout_eyes.dm
  code/modules/mining/ore_redemption_machine/survey_vendor.dm
Labels: Currently Testmerged, Map Edit

#2765 adds stop-sounds back
  code/modules/admin/admin_verbs.dm
Labels: Currently Testmerged

#2774 fixes #2597
  code/game/objects/items/weapons/melee/energy.dm
Labels: Currently Testmerged

#2768 Adding a couple of ruins and a file for ruin area consolidation.
  code/game/area/Ruin Areas.dm
  maps/nsv_triumph/submaps/frozen_planet/HeadscientistHQ.dmm
  maps/nsv_triumph/submaps/frozen_planet/_templates.dm
  maps/nsv_triumph/submaps/poi_h/AuxiliaryResearchFacility.dmm
  maps/nsv_triumph/submaps/poi_h/_templates.dm
  vorestation.dme
Labels: Currently Testmerged

#2773 adds some new shells by request of VI
  code/modules/mob/living/silicon/robot/robot_modules/station/cargo.dm
  code/modules/mob/living/silicon/robot/robot_modules/station/engineering.dm
  code/modules/mob/living/silicon/robot/robot_modules/station/medical.dm
  code/modules/mob/living/silicon/robot/robot_modules/station/misc.dm
  code/modules/mob/living/silicon/robot/robot_modules/station/science.dm
  code/modules/mob/living/silicon/robot/robot_modules/station/security.dm
  code/modules/mob/living/silicon/robot/robot_modules/station/service.dm
  icons/mob/robots.dmi
Labels: Currently Testmerged, Feature, Sprites

#2776 quick fix for drinks filling chem/condimasters when being put into them
  code/modules/food/food/drinks.dm
Labels: Currently Testmerged, Fix

#2778 makes codebase compile on 514 (wow one line)
  code/__DEFINES/spaceman_dmm.dm
  code/__HELPERS/lists/associations.dm
  code/game/world.dm
Labels: Currently Testmerged

#2779 fixes a pretty horrific memory leak
  code/__HELPERS/global_lists.dm
Labels: Currently Testmerged

#2777 Minor Remap of Triumph's Medbay (Treatment, Surgery, Break room, Entrances, decals)
  _maps/map_files/triumph/triumph-03-deck3.dmm
Labels: Currently Testmerged, Map Edit

#2781 fixes instrument min sustain being too low to work with exponential decay
  code/__DEFINES/instruments.dm
  code/modules/instruments/songs/_song.dm
Labels: Currently Testmerged

#2790 I have never experienced such pain
  _maps/map_files/triumph/triumph-03-deck3.dmm
Labels: Fix, Map Edit

#2784 now you dogeyed snowflakes can see with AR huds, congrats.
  code/modules/clothing/glasses/hud.dm
Labels: Currently Testmerged

#2783 AI shell users rejoice
  code/modules/mob/living/silicon/robot/drone/drone_items.dm
Labels: Currently Testmerged

#2791 Station lighting tubes are now very slightly less white.
  code/__DEFINES/lighting.dm
Labels: Currently Testmerged, Tweak

#2794 Adds the Detective Phoronoid suit and makes the game use the existing Phoronoid Assistant suit
  code/modules/clothing/spacesuits/plasman.dm
  code/modules/mob/living/carbon/human/species/station/plasmen.dm
  modular_citadel/icons/mob/plasmeme/helmet.dmi
  modular_citadel/icons/mob/plasmeme/suit.dmi
  modular_citadel/icons/obj/plasmeme/hats.dmi
  modular_citadel/icons/obj/plasmeme/suits.dmi
Labels: Currently Testmerged, Feature, Tweak
