Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2021-01, with the labels that each got.

#2606 Ports someone's donor item from main to RP
  code/modules/client/preference_setup/loadout/loadout_donator.dm
  modular_citadel/code/modules/clothing/donatorclothing.dm
  modular_citadel/icons/mob/donatorclothing.dmi
  modular_citadel/icons/obj/clothing/donatorclothing.dmi
Labels: Currently Testmerged

#2607 Minor Adjustments to Pathfinder Voidsuit and Airlocks
  _maps/map_files/triumph/triumph-02-deck2.dmm
  _maps/map_files/triumph/triumph-03-deck3.dmm
  _maps/map_files/triumph/triumph-04-deck4.dmm
  code/modules/clothing/spacesuits/void/station.dm
  icons/mob/head.dmi
  icons/mob/spacesuit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/spacesuits.dmi
Labels: Currently Testmerged, Map Edit, Sprites

#2610 Cafe re-comp, re-re-work
  _maps/map_files/triumph/triumph-02-deck2.dmm
  _maps/map_files/triumph/triumph-04-deck4.dmm
Labels: Currently Testmerged, Map Edit

#2614 NanoTrasen Ship Order: NSV Triumph 2565 Budget Adjustment Phase 1
  _maps/map_files/triumph/triumph-03-deck3.dmm
  _maps/map_files/triumph/triumph-04-deck4.dmm
Labels: Currently Testmerged, Feature, Map Edit, Tweak

#2612 Suit cycler paint job examination and Teshari Exploration cycler fix
  code/game/machinery/suit_storage_unit.dm
  icons/mob/species/teshari/head.dmi
  icons/mob/species/teshari/suit.dmi
  icons/obj/clothing/species/teshari/hats.dmi
  icons/obj/clothing/species/teshari/suits.dmi
Labels: Currently Testmerged, Fix, Sprites

#2615 Gaia planet rework
  maps/nsv_triumph/submaps/gaia_planet/gaia_planet.dmm
Labels: Currently Testmerged

#2621 New Markings & Ears, alt Short Hair 2, edited Ahoge.
  code/modules/mob/new_player/sprite_accessories.dm
  code/modules/vore/appearance/sprite_accessories_vr.dm
  icons/mob/human_face_vr.dmi
  icons/mob/human_face_vr_add.dmi
  icons/mob/human_races/markings_vr.dmi
  icons/mob/vore/ears_vr.dmi
Labels: Currently Testmerged, Feature, Sprites, Tweak

#2623 Fixed a very small thing with the ERT suit
  icons/mob/species/vox/uniform.dmi
Labels: Currently Testmerged, Sprites

#2622 Fixes / Adds Teshari Quartermaster Cloak Loadout
  code/modules/client/preference_setup/loadout/loadout_xeno.dm
Labels: Currently Testmerged, Feature

#2594 Gives the Chaplain a Holster for the Null Rod
  code/datums/outfits/spec_op.dm
  code/game/objects/items/weapons/nullrod.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/clothing/under/accessories/holster.dm
Labels: Currently Testmerged

#2596 Restores Dual E-Swords
  code/game/objects/items/weapons/material/twohanded.dm
  code/game/objects/items/weapons/melee/energy.dm
  icons/mob/items/lefthand_melee.dmi
  icons/mob/items/righthand_melee.dmi
  icons/obj/weapons.dmi
Labels: Currently Testmerged, Sprites

#2617 Grand Reopening: Nebula Gas Food Mart!
  _maps/map_files/triumph/triumph-02-deck2.dmm
  code/controllers/communications.dm
  code/game/antagonist/outsider/trader.dm
  code/game/machinery/telecomms/broadcaster.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/devices/radio/intercom.dm
  code/game/trader_visit.dm
  code/modules/economy/ATM.dm
  code/modules/economy/cash_register.dm
  code/modules/mob/living/say.dm
  maps/nsv_triumph/submaps/_triumph_submaps.dm
  maps/nsv_triumph/submaps/space/trade_port/_tradeport.dm
  maps/nsv_triumph/submaps/space/trade_port/tradeport.dmm
  maps/nsv_triumph/submaps/triumph_ships.dmm
  maps/nsv_triumph/triumph_areas2.dm
  maps/nsv_triumph/triumph_defines.dm
  maps/nsv_triumph/triumph_overmap.dm
  maps/nsv_triumph/triumph_shuttles.dm
  vorestation.dme
Labels: Currently Testmerged, Map Edit

#2620 Medical Gear Unhugbox - Infections
  _maps/map_files/triumph/triumph-02-deck2.dmm
  _maps/map_files/triumph/triumph-03-deck3.dmm
  _maps/map_files/triumph/triumph-04-deck4.dmm
  code/__DEFINES/damage_organs.dm
  code/game/machinery/vending.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/reagents/reagent_containers/syringes_vr.dm
  code/modules/virus2/biohazard destroyer.dm
  vorestation.dme
Labels: Balance/Rebalance, Currently Testmerged, Map Edit, Tweak

#2630 Gives Medical an EMT Shuttle and Restructures Deck 1
  _maps/map_files/triumph/triumph-01-deck1.dmm
  _maps/map_files/triumph/triumph-02-deck2.dmm
  _maps/map_files/triumph/triumph-03-deck3.dmm
  maps/nsv_triumph/submaps/space/debrisfield.dmm
  maps/nsv_triumph/submaps/space/trade_port/tradeport.dmm
  maps/nsv_triumph/submaps/triumph_ships.dmm
  maps/nsv_triumph/triumph_areas.dm
  maps/nsv_triumph/triumph_areas2.dm
  maps/nsv_triumph/triumph_overmap.dm
  maps/nsv_triumph/triumph_shuttles.dm
Labels: Currently Testmerged, Map Edit

#2631 Protean rad immunity, because it makes sense
  code/modules/mob/living/carbon/human/species/station/protean/protean_species.dm
Labels: Currently Testmerged

#2632 Merges _vr files for reagents, decentralises reagent recipes for better readability.
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks_vr.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Medicine_vr.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Vore_vr.dm
  code/modules/reagents/Chemistry-Reagents_vr.dm
  code/modules/reagents/Chemistry-Recipes.dm
  code/modules/reagents/Chemistry-Recipes_vr.dm
  code/modules/reagents/Drink-Recipes.dm
  code/modules/reagents/Food-Recipes.dm
  code/modules/reagents/Misc-Recipes.dm
  code/modules/xenobio/items/extracts.dm
  vorestation.dme
Labels: Code Improvement, Currently Testmerged

#2626 Splits Exploration From the Research Department
  code/datums/outfits/jobs/civilian.dm
  code/game/jobs/access_datum.dm
  code/game/jobs/access_datum_vr.dm
  code/game/jobs/job/exploration.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/structures/crates_lockers/closets/secure/explorer.dm
  code/modules/mining/ore_redemption_machine/survey_vendor.dm
  icons/obj/radio.dmi
  icons/obj/radio_vr.dmi
  vorestation.dme
Labels: Currently Testmerged, Sprites

#2636 Status Indicators
  code/__DEFINES/_planes+layers.dm
  code/__DEFINES/mobs.dm
  code/game/atoms_movable.dm
  code/game/gamemodes/technomancer/spells/audible_deception.dm
  code/game/machinery/cryo.dm
  code/game/machinery/jukebox.dm
  code/game/mecha/equipment/weapons/weapons.dm
  code/game/objects/items/devices/megaphone.dm
  code/modules/admin/admin.dm
  code/modules/client/preference_setup/global/setting_datums.dm
  code/modules/client/preferences_toggle_procs.dm
  code/modules/flufftext/Hallucination.dm
  code/modules/mob/living/bot/bot.dm
  code/modules/mob/living/carbon/alien/life.dm
  code/modules/mob/living/carbon/brain/login.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/login.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/living/simple_mob/subtypes/animal/space/alien.dm
  code/modules/mob/living/simple_mob/subtypes/animal/space/carp.dm
  code/modules/mob/living/simple_mob/subtypes/occult/constructs/juggernaut.dm
  code/modules/mob/living/status_indicators.dm
  code/modules/mob/login.dm
  code/modules/mob/mob_planes.dm
  code/modules/organs/pain.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Dispenser.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
  code/modules/virus2/effect.dm
  code/modules/xenoarcheaology/finds/special.dm
  code/modules/xenoarcheaology/tools/suspension_generator.dm
  icons/mob/status_indicators.dmi
  vorestation.dme
Labels: Administration, Code Improvement, Currently Testmerged, Feature, Sprites

#2625 Buffs/Adjustments to Anti-Cult Weaponry
  code/game/objects/items/weapons/nullrod.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/projectile/bullets.dm
Labels: Currently Testmerged

#2627 Security Level Hierarchy Adjustments
  code/__DEFINES/gamemode.dm
  code/controllers/configuration_old/configuration.dm
  code/game/machinery/computer/communications.dm
  code/modules/admin/admin_verbs.dm
  code/modules/security levels/security levels.dm
Labels: Currently Testmerged

#2638 Adds Hyper Pads, Aka Quantum Leap pads, for mappers.
  code/datums/helper_datums/teleport.dm
  code/game/objects/effects/effect_system.dm
  code/modules/telesci/hyper_pad.dm
  code/modules/telesci/quantum_pad.dm
  icons/effects/effects.dmi
  icons/obj/telescience.dmi
  vorestation.dme
Labels: Currently Testmerged, Sprites

#2633 NSV Triumph Re-Fitting - Service Area
  _maps/map_files/triumph/triumph-02-deck2.dmm
  _maps/map_files/triumph/triumph-03-deck3.dmm
  _maps/map_files/triumph/triumph-04-deck4.dmm
Labels: Currently Testmerged, Feature, Map Edit, Tweak

#2637 Engine Fuel Economy, A Few Ian Clothing Items, and Trade Port Updates
  code/game/objects/items/devices/radio/radio.dm
  code/modules/busy_space/organizations.dm
  code/modules/events/cult.dm
  code/modules/events/hostile_migration_vr.dm
  code/modules/overmap/ships/engines/gas_thruster.dm
  code/modules/overmap/ships/engines/ion_thruster.dm
  icons/mob/corgi_back.dmi
  icons/mob/corgi_head.dmi
  maps/nsv_triumph/submaps/frozen_planet/frozen_planet.dmm
  maps/nsv_triumph/submaps/mining_planet/mining_planet.dmm
  maps/nsv_triumph/submaps/poi_d/Class_D.dmm
  maps/nsv_triumph/submaps/space/piratebase.dmm
  maps/nsv_triumph/submaps/space/trade_port/_tradeport.dm
  maps/nsv_triumph/submaps/space/trade_port/tradeport.dmm
  maps/nsv_triumph/triumph_areas2.dm
Labels: Currently Testmerged, Sprites

#2618 Operation Cap icons renamed to work.
  icons/mob/head.dmi
Labels: Currently Testmerged, Fix, Sprites

#2641 More Cosmetics 2 Electric Boogaloo
  code/modules/mob/new_player/sprite_accessories.dm
  code/modules/vore/appearance/sprite_accessories_vr.dm
  icons/mob/human_face_vr.dmi
  icons/mob/human_face_vr_add.dmi
  icons/mob/human_races/markings_vr.dmi
  icons/mob/vore/ears_vr.dmi
Labels: Currently Testmerged, Feature, Sprites

#2640 Mech and Rig UI and buttons.
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/action.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/rigmech.dm
  code/game/mecha/combat/durand.dm
  code/game/mecha/combat/gorilla.dm
  code/game/mecha/combat/gygax.dm
  code/game/mecha/combat/marauder.dm
  code/game/mecha/combat/phazon.dm
  code/game/mecha/equipment/tools/tools.dm
  code/game/mecha/mecha.dm
  code/game/mecha/mecha_actions.dm
  code/game/mecha/micro/security.dm
  code/game/mecha/micro/utility.dm
  code/modules/clothing/spacesuits/rig/rig.dm
  code/modules/mob/mob_defines.dm
  icons/effects/actions_mecha.dmi
  icons/mecha/actions_mecha.dmi
  icons/mob/screen_rigmech.dmi
  vorestation.dme
Labels: Currently Testmerged, Feature, Sprites

#2645 Refining general decks
  _maps/map_files/triumph/triumph-01-deck1.dmm
  _maps/map_files/triumph/triumph-02-deck2.dmm
  _maps/map_files/triumph/triumph-03-deck3.dmm
  _maps/map_files/triumph/triumph-04-deck4.dmm
  code/modules/food/kitchen/smartfridge.dm
Labels: Currently Testmerged, Map Edit

#2649 Fixes merchant IDs
  code/datums/outfits/misc.dm
  code/game/objects/items/weapons/id cards/station_ids.dm
Labels: Currently Testmerged

#2646 Fix: Sleep Indicator being stuck after Surgery
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/living.dm
Labels: Currently Testmerged, Fix

#2652 Reduce spider Cocoon health from 60 to 10
  code/game/objects/effects/spiders.dm
Labels: Currently Testmerged

#2653 Makes The Frontier Phasers Sound Like Guns, Not Slide-Whistles (and the PDW sounds nicer, too)
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/vore/fluffstuff/custom_guns.dm
  sound/weapons/energy_heavy.wav
  sound/weapons/gunshot/gunshot_uzi.wav
  sound/weapons/laser_holdout_1.wav
  sound/weapons/laser_rifle_1.wav
Labels: Currently Testmerged, Sound, Tweak

#2639 Bugfix Round Up - January (Cakes and Cloaks)
  code/modules/client/preference_setup/loadout/loadout_xeno.dm
  code/modules/food/kitchen/cooking_machines/container.dm
Labels: Currently Testmerged

#2644 Suits and Gear Additions/Adjustments
  code/datums/components/crafting/recipes.dm
  code/datums/outfits/horror_killers.dm
  code/datums/outfits/misc.dm
  code/datums/outfits/spec_op.dm
  code/datums/supplypacks/engineering.dm
  code/datums/underwear/bottom.dm
  code/defines/obj/weapon.dm
  code/game/antagonist/outsider/trader.dm
  code/game/machinery/vending.dm
  code/game/objects/items/devices/gps.dm
  code/game/objects/items/weapons/bones.dm
  code/game/objects/items/weapons/material/knives.dm
  code/game/objects/items/weapons/material/material_armor.dm
  code/game/objects/items/weapons/storage/misc.dm
  code/game/objects/structures/crates_lockers/closets/secure/explorer.dm
  code/modules/busy_space/organizations.dm
  code/modules/client/preference_setup/loadout/loadout_head.dm
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/hood.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/clothing/spacesuits/void/merc.dm
  code/modules/clothing/spacesuits/void/station.dm
  code/modules/clothing/spacesuits/void/wizard.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/hooded.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/accessories/armor.dm
  code/modules/clothing/under/accessories/badges.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/mining/mine_turfs.dm
  code/modules/paperwork/paper.dm
  code/modules/vore/fluffstuff/custom_boxes.dm
  icons/mob/head.dmi
  icons/mob/human.dmi
  icons/mob/light_overlays.dmi
  icons/mob/mask.dmi
  icons/mob/spacesuit.dmi
  icons/mob/suit.dmi
  icons/mob/ties.dmi
  icons/mob/uniform.dmi
  icons/mob/uniform_sleeves_rolled.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/clothing/spacesuits.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/ties.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/device.dmi
  maps/nsv_triumph/submaps/space/trade_port/tradeport.dmm
Labels: Currently Testmerged, Sprites

#2656 Livin' In a Box/Adds Large Cardboard Box.
  code/game/objects/structures/crates_lockers/closets/gimmick.dm
  code/modules/materials/material_recipes.dm
  modular_citadel/icons/obj/closet.dmi
  sound/misc/boxclose.ogg
  sound/misc/boxopen.ogg
  sound/misc/boxtear.ogg
Labels: Currently Testmerged, Sound

#2662 [Event Reward] - Adds that Event Reward Gameboy I've been waiting on forever.
  code/modules/client/preference_setup/loadout/loadout_event_rewards.dm
  code/modules/instruments/instruments/item.dm
  icons/mob/inhands/equipment/instruments_lefthand.dmi
  icons/mob/inhands/equipment/instruments_righthand.dmi
  icons/obj/musician.dmi
  sound/weapons/gboy.ogg
Labels: Currently Testmerged, Feature, Sound, Sprites

#2667 re-adds a previously present PR
  code/_onclick/hud/human.dm
  code/game/objects/items/devices/translator.dm
  code/modules/atmospherics/zas/Phoron.dm
  code/modules/mob/_modifiers/modifiers_misc.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/mob_defines.dm
Labels: Currently Testmerged
