Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2022-11, with the labels that each got.

#4610 Dynamic Sizing Viewport
  citadel.dme
  code/__DEFINES/math.dm
  code/__HELPERS/view.dm
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/ability_screen_objects.dm
  code/_onclick/hud/actions/_action.dm
  code/_onclick/hud/hud.dm
  code/_onclick/hud/movable_screen_objects.dm
  code/_rendering/mob.dm
  code/controllers/configuration/entries/game_options.dm
  code/controllers/configuration_old/configuration.dm
  code/datums/components/storage/storage.dm
  code/datums/perspective.dm
  code/game/mecha/mecha_actions.dm
  code/game/objects/_items.dm
  code/game/objects/items/storage/_storage.dm
  code/modules/admin/verbs/buildmode.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/client/client_procs.dm
  code/modules/client/preference_setup/global/setting_datums.dm
  code/modules/client/preferences.dm
  code/modules/client/preferences_toggle_procs.dm
  code/modules/client/viewport.dm
  code/modules/clothing/head/pilot_helmet.dm
  code/modules/mob/mob_planes.dm
  code/modules/mob/new_player/login.dm
  code/modules/mob/perspective.dm
  code/modules/overmap/ships/computers/ship.dm
  code/modules/rigsuits/_rig.dm
  code/modules/tgui/modules/overmap.dm
  config/entries/game_options.txt
  interface/skin.dmf
Labels: Test Merge Candidate, hacktoberfest-accepted

#4633 [Ready for Full merge pending Approval] Western Cavern, Mining outpost Overhaul, Gateway
  _maps/map_files/rift/rift-07-west_base.dmm
  _maps/map_files/rift/rift-08-west_deep.dmm
  _maps/map_files/rift/rift-09-west_caves.dmm
  _maps/map_files/rift/rift-10-west_plains.dmm
  _maps/submaps/lythios_rift/map_makers_pallet.dmm
  citadel.dme
  code/game/area/Space Station 13 areas.dm
  code/game/objects/effects/map_effects/effect_emitter.dm
  code/game/objects/explosion_recursive.dm
  code/game/turfs/simulated/floors/lava.dm
  code/modules/maps/rift/levels/lavaland.dm
  code/modules/maps/tether/levels/tether_turfs.dm
  code/modules/maps/triumph/levels/lavaland.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mining/mine_turfs_vr.dm
  maps/rift/rift_areas2.dm
  maps/rift/rift_turfs.dm
Labels: Blocked - Code Quality

#4652 Crewkin Abilities v1
  citadel.dme
  code/__DEFINES/species/species.dm
  code/modules/mob/living/carbon/human/human_powers.dm
  code/modules/organs/internal/species/shadekin.dm
  code/modules/species/shadekin/crew_shadekin_abilities.dm
  code/modules/species/shadekin/crew_shadekin_hud.dm
  code/modules/species/shadekin/shadekin.dm
  code/modules/species/shadekin/shadekin_abilities.dm
  code/modules/species/shadekin/shadekin_blackeyed.dm
Labels: hacktoberfest-accepted

#4658 Adds small unathi ritual room in maintenance
  _maps/map_files/rift/rift-03-underground1.dmm
Labels: hacktoberfest-accepted

#4702 temporarily removes infection damage from the dead
  code/modules/organs/external/_external.dm
Labels: Fix

#4729 makes brig timers use REALTIMEOFDAY
  code/game/machinery/doors/brigdoors.dm
Labels: Test Merge Candidate

#4752 adds a donator item
  code/game/objects/donator_rewards/backpack.dm
  code/modules/donatorreskins/donatorclothing.dm
  code/modules/preferences/preference_setup/loadout/loadout_donator.dm
  icons/donator/jackson_backpack.dmi
Labels: hacktoberfest-accepted

#4673 Matriarch Drone Port
  _maps/map_files/rift/rift-03-underground1.dmm
  citadel.dme
  code/__DEFINES/_lists.dm
  code/__DEFINES/is_helpers.dm
  code/datums/ai_law_sets.dm
  code/game/machinery/rechargestation.dm
  code/modules/mob/living/silicon/robot/drone/_defines.dm
  code/modules/mob/living/silicon/robot/drone/drone.dm
  code/modules/mob/living/silicon/robot/drone/drone_manufacturer.dm
  code/modules/mob/living/silicon/robot/drone/matrix_hive.dm
  code/modules/mob/living/silicon/robot/drone/matrix_powers.dm
  code/modules/mob/living/silicon/robot/drone/~defines.dm
  code/modules/mob/living/silicon/robot/robot_modules/station/drone.dm
Labels: hacktoberfest-accepted
