Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2022-04, with the labels that each got.

#3843 The Great Pirate Reskin
  code/modules/client/preference_setup/loadout/loadout_donator.dm
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/oricon.dm
  code/modules/events/pirate.dm
  code/modules/mob/living/simple_mob/corpse.dm
  code/modules/mob/living/simple_mob/subtypes/humanoid/pirates.dm
  icons/mob/head.dmi
  icons/mob/pirate.dmi
  icons/mob/suit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Currently Testmerged, Sprites, Mechanic

#3848 Jukebox Update - Courtesy of Pear
  config_static/jukebox.json
Labels: Currently Testmerged, Config Update, Mechanic

#3854 Spessmen are now capable of succ through mechanical means
  code/modules/reagents/reagent_containers/hard_candy.dm
Labels: Currently Testmerged, Fix

#3846 New knives. New spirits. What could go wrong?
  code/game/machinery/vending.dm
  code/game/objects/items/weapons/material/knives.dm
  code/modules/clothing/clothing.dm
  code/modules/economy/price_list.dm
  code/modules/examine/descriptions/containers.dm
  code/modules/food/food/drinks/bottle.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  icons/obj/drinks.dmi
  icons/obj/weapons.dmi
Labels: Currently Testmerged, Sprites, Mechanic

#3857 Snowflakes the PF's Gun Again, Reorders Gun .dmi files.
  _maps/away_missions/archive/zresearchlabs.dmm
  _maps/map_files/triumph/triumph-05-flagship.dmm
  code/datums/outfits/jobs/special.dm
  code/datums/outfits/spec_op.dm
  code/datums/supplypacks/misc.dm
  code/game/antagonist/outsider/deathsquad.dm
  code/game/mecha/equipment/tools/syringe_gun.dm
  code/game/objects/items/devices/aicard.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/random/guns_and_ammo.dm
  code/game/objects/random/misc.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/guns/energy/nuclear.dm
  code/modules/projectiles/guns/energy/pulse.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  code/modules/projectiles/guns/projectile/revolver.dm
  code/modules/research/designs/weapons.dm
  icons/obj/ammo.dmi
  icons/obj/gun.dmi
  icons/obj/gun/ballistic.dmi
  icons/obj/gun/energy.dmi
  icons/obj/gun/unused.dmi
  icons/obj/gun2.dmi
Labels: Currently Testmerged, Sprites, Map Edit, Mechanic

#3855 Adds Pariah Jacket and Fixes Minor Culture Bugs
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/food/food/snacks.dm
  code/modules/mining/mine_items.dm
  code/modules/projectiles/guns/projectile/rocket.dm
  icons/mob/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: Currently Testmerged, Fix, Sprites, Mechanic

#3858 Energy_Field Patch and Shield Generator TGUI
  _maps/map_files/triumph/triumph-01-deck1.dmm
  _maps/map_levels/140x140/talon/talon2.dmm
  _maps/templates/admin/dhael_centcom.dmm
  _maps/templates/admin/ert.dmm
  _maps/templates/admin/ert_base.dmm
  _maps/templates/admin/kk_mercship.dmm
  _maps/templates/shuttles/overmaps/generic/abductor.dmm
  _maps/templates/shuttles/overmaps/generic/cruiser.dmm
  _maps/templates/shuttles/overmaps/generic/curashuttle.dmm
  _maps/templates/shuttles/overmaps/generic/mercship.dmm
  _maps/templates/shuttles/overmaps/generic/vespa.dmm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/machinery.dm
  code/__DEFINES/shields.dm
  code/controllers/subsystems/openspace.dm
  code/game/turfs/simulated/floor_icon.dm
  code/modules/mining/shelters.dm
  code/modules/multiz/hoist.dm
  code/modules/multiz/movement.dm
  code/modules/multiz/structures.dm
  code/modules/multiz/turf.dm
  code/modules/multiz/turf_obj_hooks.dm
  code/modules/overmap/ships/engines/gas_thruster.dm
  code/modules/shieldgen/energy_shield.dm
  code/modules/shieldgen/shield_generator.dm
  code/modules/shuttles/shuttle.dm
  icons/obj/machines/shielding_vr.dmi
  nano/templates/shield_generator.tmpl
  tgui/public/tgui.bundle.css
Labels: Currently Testmerged, Sprites, UI, Map Edit, Mechanic

#3861 Teshari Wintercloak Update
  code/modules/clothing/suits/aliens/teshari.dm
Labels: Currently Testmerged

#3856 Reduces sizeshift trait cost to 2
  code/modules/mob/living/carbon/human/species/station/traits/neutral.dm
  code/modules/mob/living/carbon/human/species/station/traits/positive.dm
Labels: Currently Testmerged, Balance/Rebalance

#3866 fixes communicators just randomly breaking
  code/game/machinery/exonet_node.dm
  code/game/objects/items/devices/communicator/communicator.dm
Labels: Currently Testmerged

#3869 Change alert descriptions to be config options
  code/controllers/configuration/entries/game_options.dm
  code/controllers/configuration_old/configuration.dm
  code/modules/security levels/security levels.dm
  config/entries/game_options.txt
Labels: Currently Testmerged, Config Update

#3868 Add tactical and speed reloads to projectile weapons
  code/modules/projectiles/guns/projectile.dm
  code/modules/projectiles/guns/projectile/automatic.dm
Labels: Currently Testmerged, Mechanic

#3865 Port radio sounds from Baystation
  code/game/objects/items/devices/radio/radio.dm
  code/modules/mob/hear_say.dm
  code/modules/mob/mob_defines.dm
  sound/effects/radiochatter.ogg
  sound/effects/walkietalkie.ogg
Labels: Currently Testmerged, Sound, Good First PR, Mechanic

#3864 Pasta's Agonizing Audio Emotes
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/silicon/robot/emote.dm
  sound/machines/synth_error.ogg
  sound/machines/synth_gameover.ogg
  sound/machines/synth_shutdown.ogg
  sound/machines/synth_startup.ogg
  sound/voice/anime_moan.ogg
  sound/voice/ara_ara1.ogg
  sound/voice/ara_ara2.ogg
  sound/voice/catpeople/nya-1.ogg
  sound/voice/catpeople/nya-2.ogg
  sound/voice/nya1.ogg
  sound/voice/nya2.ogg
  sound/voice/uwu.ogg
Labels: Currently Testmerged, Sound, Mechanic

#3867 Breaking News: Donk CEO Announces DONKsoft Relaunch!
  code/datums/supplypacks/recreation.dm
  code/game/machinery/vending.dm
  code/game/objects/items/gunbox.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/weapons/material/foam.dm
  code/game/objects/items/weapons/shields.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/spacesuits/void/outsider.dm
  code/modules/clothing/suits/armor.dm
  code/modules/food/food/snacks.dm
  code/modules/materials/fifty_spawner_mats.dm
  code/modules/materials/material_sheets.dm
  code/modules/mob/living/silicon/ai/icons.dm
  code/modules/mob/new_player/sprite_accessories.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/ammunition/rounds.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  code/modules/projectiles/projectile/reusable.dm
  code/modules/reagents/Food-Recipes.dm
  icons/mecha/mecha.dmi
  icons/mob/AI.dmi
  icons/mob/head.dmi
  icons/mob/items/lefthand_melee.dmi
  icons/mob/items/righthand_melee.dmi
  icons/mob/spacesuit.dmi
  icons/mob/suit.dmi
  icons/obj/ammo.dmi
  icons/obj/barsigns.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/spacesuits.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/gun/ballistic.dmi
  icons/obj/items.dmi
  icons/obj/storage.dmi
  icons/obj/toy.dmi
  icons/obj/weapons.dmi
Labels: Currently Testmerged, Fix, Sprites, Mechanic

#3859 Borg Shielding Nerf
  code/modules/mob/living/silicon/robot/robot_items.dm
Labels: Currently Testmerged, Balance/Rebalance

#3872 Add alert status to MOTD
  code/modules/client/verbs/ooc.dm
  code/modules/mob/new_player/login.dm
Labels: Mechanic

#3873 Fixed the supply channel's color on dark mode.
  code/controllers/communications.dm
  interface/stylesheet.dm
  nano/templates/radio_basic.tmpl
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
  tgui/public/tgui-panel.bundle.css
Labels: Fix, UI

#3871 Nerfs the HoP
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
Labels: Removal

#3878 fixes resin nests being not buckleable
  code/modules/mob/living/carbon/human/species/station/xenomorph_hybrids/hybrid_resin.dm
Labels: Fix

#3877 Should prevent energy sinks
  code/modules/atmospherics/components/binary_devices/heat_pump.dm
Labels: Fix

#3875 Comment out skills
  code/game/machinery/computer/skills.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/client/preference_setup/preference_setup.dm
  code/modules/client/preference_setup/skills/skills.dm
  vorestation.dme
Labels: Removal

#3885 New REAL!(TM) Chess Set!
  code/game/objects/items/toys.dm
  icons/obj/chess.dmi
Labels: Currently Testmerged, Sprites

#3879 Update status effect HUD icons and add thirst
  code/__DEFINES/chemistry.dm
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/human.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/mob_defines.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Core.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Dispenser.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  icons/mob/status_hunger.dmi
  icons/mob/status_indicators_hud.dmi
Labels: Currently Testmerged, Sprites, Mechanic

#3884 [BOUNTY] Teshari can now use some two-handed weapons
  code/game/objects/items.dm
  code/game/objects/items/weapons/material/twohanded.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/modular/gunframes.dm
  code/modules/projectiles/guns/energy/nuclear.dm
  code/modules/projectiles/guns/energy/particle.dm
  code/modules/projectiles/guns/energy/phase.dm
  code/modules/projectiles/guns/energy/pulse.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/guns/launcher/grenade_launcher.dm
  code/modules/projectiles/guns/launcher/pneumatic.dm
  code/modules/projectiles/guns/magnetic/magnetic_railgun.dm
  code/modules/projectiles/guns/modular_guns.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/boltaction.dm
  code/modules/projectiles/guns/projectile/contender.dm
  code/modules/projectiles/guns/projectile/rocket.dm
  code/modules/projectiles/guns/projectile/semiauto.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  code/modules/projectiles/guns/projectile/sniper.dm
  code/modules/projectiles/guns/vox.dm
Labels: Currently Testmerged

#3891 Adds Green and Red Multitools
  code/game/objects/items/devices/multitool.dm
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/obj/device.dmi
Labels: Sprites, Mechanic

#3893 get rid of computer3
  code/game/machinery/computer3/NTOS.dm
  code/game/machinery/computer3/bios.dm
  code/game/machinery/computer3/buildandrepair.dm
  code/game/machinery/computer3/component.dm
  code/game/machinery/computer3/computer.dm
  code/game/machinery/computer3/computer3_notes.dm
  code/game/machinery/computer3/computers/HolodeckControl.dm
  code/game/machinery/computer3/computers/Operating.dm
  code/game/machinery/computer3/computers/arcade.dm
  code/game/machinery/computer3/computers/atmos_alert.dm
  code/game/machinery/computer3/computers/camera.dm
  code/game/machinery/computer3/computers/card.dm
  code/game/machinery/computer3/computers/communications.dm
  code/game/machinery/computer3/computers/crew.dm
  code/game/machinery/computer3/computers/customs.dm
  code/game/machinery/computer3/computers/law.dm
  code/game/machinery/computer3/computers/medical.dm
  code/game/machinery/computer3/computers/power.dm
  code/game/machinery/computer3/computers/prisoner.dm
  code/game/machinery/computer3/computers/robot.dm
  code/game/machinery/computer3/computers/security.dm
  code/game/machinery/computer3/computers/welcome.dm
  code/game/machinery/computer3/file.dm
  code/game/machinery/computer3/laptop.dm
  code/game/machinery/computer3/lapvend.dm
  code/game/machinery/computer3/networking.dm
  code/game/machinery/computer3/program.dm
  code/game/machinery/computer3/program_disks.dm
  code/game/machinery/computer3/server.dm
  code/game/machinery/computer3/storage.dm
Labels: Priority: High

#3882 Add safeties to guns
  code/modules/client/preference_setup/global/setting_datums.dm
  code/modules/client/preferences_toggle_procs.dm
  code/modules/clothing/under/accessories/holster.dm
  code/modules/keybindings/keybind/human.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/launcher/crossbow.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  code/modules/projectiles/targeting/targeting_triggers.dm
  icons/obj/gun/gui.dmi
Labels: Currently Testmerged, Sprites, Removal, Mechanic

#3888 makes mobs not process with high priority on default
  code/controllers/subsystems/ai.dm
  code/modules/mob/mob_defines.dm
Labels: Currently Testmerged, Fix

#3889 Change autohiss to a character pref
  code/modules/client/preference_setup/vore/04_autohiss.dm
  code/modules/client/preference_setup/vore/05_resleeving.dm
  code/modules/client/preference_setup/vore/06_persistence.dm
  code/modules/client/preference_setup/vore/07_vantag.dm
  code/modules/client/preference_setup/vore/08_traits.dm
  code/modules/client/preference_setup/vore/09_nif.dm
  code/modules/client/preference_setup/vore/10_misc.dm
  code/modules/mob/living/autohiss.dm
  vorestation.dme
Labels: Currently Testmerged, Removal

#3890 Adds Water Bottles to MREs
  code/game/objects/items/storage/mre.dm
Labels: Currently Testmerged, Mechanic

#3896 Add back autohiss verbs, add type discrimination
  code/modules/client/preference_setup/vore/04_autohiss.dm
  code/modules/mob/living/autohiss.dm
  code/modules/mob/living/carbon/human/species/station/station_special.dm
Labels: Removal, Mechanic

#3897 Allows grav and space adapted humans to wear standard human voidsuits
  code/__DEFINES/mobs.dm
  code/modules/clothing/clothing.dm
  code/modules/mob/living/carbon/human/species/station/human_subspecies.dm
Labels: Fix

#3902 Removes 'Containment Specialist' as an exploration job title
  code/game/jobs/job/exploration.dm
Labels: Revert, Removal

#3904 fix misspelled name in crew transfer
  maps/nsv_triumph/triumph_defines.dm
Labels: Currently Testmerged, Grammar and Formatting

#3907 Fix nutrition I think
  code/modules/mob/living/carbon/human/life.dm
Labels: Fix

#3908 Nutrition clean up
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/species/station/diona.dm
  code/modules/organs/internal/adherent.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
Labels: Refactor, Fix

#3883 The Vegan Vampire Update
  code/datums/soul_link.dm
  code/game/machinery/vending.dm
  code/modules/food/food/drinks.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/station/custom_species.dm
  code/modules/mob/living/carbon/human/species/station/station_special_abilities.dm
  code/modules/mob/living/carbon/human/species/station/traits/neutral.dm
  code/modules/reagents/Chemistry-Reagents.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Core.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Dispenser.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/reagents/reagent_containers/blood_pack.dm
  code/modules/reagents/reagent_containers/blood_pack_vr.dm
  icons/obj/drinks.dmi
Labels: Currently Testmerged, Sprites, Grammar and Formatting, Mechanic

#3910 Pirate Event Diversity: Now Featureing RATS and Vox
  code/modules/events/pirate.dm
  code/modules/mob/living/simple_mob/subtypes/humanoid/mercs/mercs.dm
Labels: Currently Testmerged, Fix, Mechanic

#3912 makes lighting objects work with spin view
  icons/effects/lighting_object.dmi
Labels: Currently Testmerged, Sprites

#3916 cleans up fire garbage collection
  code/game/turfs/turf_changing.dm
  code/modules/atmospherics/environmental/zas/fire.dm
Labels: Currently Testmerged

#3915 separates subsystem and timer flags from flags var, defines bitfields for them
  code/__DEFINES/MC.dm
  code/__DEFINES/controllers/_subsystems.dm
  code/__DEFINES/controllers/timer.dm
  code/controllers/master.dm
  code/controllers/subsystem.dm
  code/controllers/subsystems/ai.dm
  code/controllers/subsystems/air.dm
  code/controllers/subsystems/airflow.dm
  code/controllers/subsystems/assets.dm
  code/controllers/subsystems/atoms.dm
  code/controllers/subsystems/bellies_vr.dm
  code/controllers/subsystems/character_setup.dm
  code/controllers/subsystems/chat.dm
  code/controllers/subsystems/circuits.dm
  code/controllers/subsystems/dcs.dm
  code/controllers/subsystems/events.dm
  code/controllers/subsystems/fail2topic.dm
  code/controllers/subsystems/garbage.dm
  code/controllers/subsystems/holomaps.dm
  code/controllers/subsystems/icon_smooth.dm
  code/controllers/subsystems/inactivity.dm
  code/controllers/subsystems/input.dm
  code/controllers/subsystems/jobs.dm
  code/controllers/subsystems/lighting.dm
  code/controllers/subsystems/machines.dm
  code/controllers/subsystems/mapping/_mapping.dm
  code/controllers/subsystems/minimaps.dm
  code/controllers/subsystems/mobs.dm
  code/controllers/subsystems/networks/_networks.dm
  code/controllers/subsystems/nightshift.dm
  code/controllers/subsystems/overlays.dm
  code/controllers/subsystems/overmap.dm
  code/controllers/subsystems/persist_vr.dm
  code/controllers/subsystems/persistence/_persistence.dm
  code/controllers/subsystems/planets.dm
  code/controllers/subsystems/processing/chemistry.dm
  code/controllers/subsystems/processing/instruments.dm
  code/controllers/subsystems/processing/obj.dm
  code/controllers/subsystems/processing/processing.dm
  code/controllers/subsystems/processing/projectiles.dm
  code/controllers/subsystems/processing/status_effects.dm
  code/controllers/subsystems/radiation.dm
  code/controllers/subsystems/server_maint.dm
  code/controllers/subsystems/shuttles.dm
  code/controllers/subsystems/skybox.dm
  code/controllers/subsystems/sounds.dm
  code/controllers/subsystems/spacedrift.dm
  code/controllers/subsystems/tgui.dm
  code/controllers/subsystems/ticker.dm
  code/controllers/subsystems/time_track.dm
  code/controllers/subsystems/timer.dm
  code/controllers/subsystems/transcore_vr.dm
  code/controllers/subsystems/turbolift.dm
  code/controllers/subsystems/vote.dm
  code/controllers/subsystems/xenoarch.dm
  code/modules/unit_tests/subsystem_init.dm
  vorestation.dme
Labels: Currently Testmerged

#3918 Swimsuit salt
  code/modules/client/preference_setup/loadout/loadout_general.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
Labels: Currently Testmerged, Fix, Mechanic

#3911 Fixes Bad Math in Tyrmalin Mining Code
  code/game/objects/items/weapons/grenades/explosive.dm
Labels: Currently Testmerged, Fix

#3905 Port: Promethean Blobform
  code/modules/mob/living/carbon/human/species/station/promethean_blob.dm
  code/modules/mob/living/carbon/human/species/station/prometheans.dm
  vorestation.dme
Labels: Currently Testmerged, Good First PR, Mechanic

#3919 once again, looking at the research department's code makes me get unwise
  code/game/machinery/telecomms/telecomunications.dm
  code/modules/research/designs.dm
  code/modules/research/research.dm
  code/modules/research/server.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/research_tests.dm
Labels: Currently Testmerged

#3903 Adds an Akula language, Olelo Mano, and rearranges 2x lang keys.
  code/__DEFINES/species_languages.dm
  code/game/objects/items/robot/robot_upgrades.dm
  code/modules/mob/language/outsider.dm
  code/modules/mob/language/station.dm
  code/modules/mob/living/silicon/ai/ai.dm
  interface/stylesheet.dm
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
Labels: Currently Testmerged, Removal, UI, Mechanic

#3921 attack_hand is called attack HAND for a reason, not "unhandled item attack, assume they used their bare hands"
  code/game/turfs/simulated/wall_attacks.dm
Labels: Currently Testmerged

#3929 Swimsuit Salt Hotfix/Reassertion
  code/modules/client/preference_setup/loadout/loadout_general.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
Labels: Fix

#3920 Creates Modular Limb Plates
  code/game/objects/items/storage/lockbox.dm
  code/game/objects/structures/crates_lockers/closets/secure/medical.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/accessories/armor.dm
  icons/mob/ties.dmi
  icons/obj/clothing/ties.dmi
Labels: Currently Testmerged, Sprites, Mechanic

#3926 fixes nifsoft huds
  code/_rendering/atom_huds/atom_hud.dm
  code/modules/nifsoft/software/01_vision.dm
  icons/hud/atom_hud/job.dmi
Labels: Sprites

#3922 Post SciTGUI Patches
  code/__DEFINES/chemistry.dm
  code/__DEFINES/spans.dm
  code/_onclick/hud/screen_objects.dm
  code/datums/components/crafting/crafting.dm
  code/game/machinery/autolathe.dm
  code/game/machinery/computer/Operating.dm
  code/game/machinery/cryopod.dm
  code/game/machinery/door_control.dm
  code/game/machinery/pipe/pipe_dispenser.dm
  code/game/machinery/pipe/pipe_recipes.dm
  code/game/machinery/recharger.dm
  code/game/machinery/telecomms/telecomunications.dm
  code/game/machinery/teleporter/pad.dm
  code/game/objects/items/devices/tvcamera.dm
  code/modules/atmospherics/components/trinary_devices/filter.dm
  code/modules/integrated_electronics/core/assemblies.dm
  code/modules/integrated_electronics/core/assemblies/device.dm
  code/modules/integrated_electronics/core/integrated_circuit.dm
  code/modules/integrated_electronics/core/pins.dm
  code/modules/integrated_electronics/core/printer.dm
  code/modules/integrated_electronics/core/special_pins/char_pin.dm
  code/modules/integrated_electronics/core/special_pins/color_pin.dm
  code/modules/integrated_electronics/core/special_pins/dir_pin.dm
  code/modules/integrated_electronics/core/special_pins/list_pin.dm
  code/modules/integrated_electronics/core/special_pins/number_pin.dm
  code/modules/integrated_electronics/core/special_pins/ref_pin.dm
  code/modules/integrated_electronics/core/special_pins/string_pin.dm
  code/modules/integrated_electronics/core/tools.dm
  code/modules/integrated_electronics/subtypes/input.dm
  code/modules/integrated_electronics/subtypes/memory.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/nifsoft/nif.dm
  code/modules/nifsoft/nif_tgui.dm
  code/modules/nifsoft/nifsoft.dm
  code/modules/nifsoft/software/01_vision.dm
  code/modules/reagents/Chemistry-Machinery.dm
  code/modules/reagents/machinery/chem_master.dm
  icons/obj/machines/fabricators/autolathe.dmi
  icons/obj/stationobjs.dmi
  icons/obj/stationobjs_vr.dmi
  interface/stylesheet.dm
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
  tgui/public/tgui-panel.bundle.css
Labels: Currently Testmerged, Fix, Sprites, UI

#3927 fixes zasfire again
  code/game/turfs/turf_changing.dm
  code/modules/atmospherics/environmental/zas/fire.dm
Labels: Currently Testmerged

#3932 hud cleanup again
  code/_rendering/atom_huds/data_huds.dm
  code/game/gamemodes/changeling/powers/revive.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/living.dm
Labels: Currently Testmerged

#3937 The Hotfix To the Hotfix
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/clothing/under/miscellaneous.dm
Labels: Currently Testmerged, Fix

#3930 Makes My Preferred Hairstyle Able to be Tied
  code/modules/mob/new_player/sprite_accessories.dm
Labels: Currently Testmerged

#3935 fixes nifsoft shop logo not being an AR visual
  code/modules/nifsoft/augmented_holder.dm
Labels: Currently Testmerged

#3939 Some code cleaning.
  code/__DEFINES/_lists.dm
  code/__DEFINES/controllers/_subsystems.dm
  code/__DEFINES/dcs/signals.dm
  code/__HELPERS/unsorted.dm
  code/datums/datum.dm
  code/game/area/areas.dm
  code/game/atoms.dm
  code/game/turfs/simulated/walls.dm
  code/game/turfs/turf.dm
  code/game/turfs/unsimulated/walls.dm
  code/modules/mob/login.dm
  code/modules/mob/mob.dm
Labels: Currently Testmerged

#3923 Adds high performance gas/heat pumps
  _maps/map_files/triumph/triumph-01-deck1.dmm
  code/game/objects/items/weapons/circuitboards/circuitboards_vr.dm
  code/modules/atmospherics/_atmospherics_helpers.dm
  code/modules/atmospherics/components/binary_devices/heat_pump.dm
  code/modules/atmospherics/components/binary_devices/massive_gas_pump.dm
  code/modules/atmospherics/components/binary_devices/massive_heat_pump.dm
  code/modules/atmospherics/components/binary_devices/pump.dm
  code/modules/power/powersupply.dm
  code/modules/research/designs/circuits/circuits.dm
  icons/obj/machines/massive_pumps.dmi
  tgui/packages/tgui/interfaces/MassiveGasPump.js
  tgui/packages/tgui/interfaces/MassiveHeatPump.js
  tgui/public/tgui.bundle.js
  vorestation.dme
Labels: Currently Testmerged, Sprites, UI, Map Edit, Mechanic

#3940 Adds the Mekkyaku Coat
  code/modules/client/preference_setup/loadout/loadout_accessories.dm
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/accessories/clothing.dm
  icons/mob/suit.dmi
  icons/mob/ties.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/ties.dmi
Labels: Currently Testmerged, Sprites, Mechanic

#3943 emergency hotfix - mob refs are all the same
  code/modules/mob/mob_defines.dm
Labels: Currently Testmerged

#3947 I am the Globglogabgalab (Engineering Buff 2.0)
  _maps/map_files/triumph/triumph-01-deck1.dmm
  _maps/map_files/triumph/triumph-04-deck4.dmm
  code/game/objects/items/weapons/manuals.dm
Labels: Fix, Balance/Rebalance, Map Edit

#3944 minor transparency tweaks
  icons/mob/eyes.dmi
  icons/obj/chess.dmi
Labels: Currently Testmerged, Sprites

#3949 Engine Submap Adjustments and FTL/Shunt Core Rooms
  _maps/map_files/triumph/triumph-01-deck1.dmm
  _maps/templates/engines/triumph/triumph_engine_burnchamber.dmm
  _maps/templates/engines/triumph/triumph_engine_fission.dmm
  _maps/templates/engines/triumph/triumph_engine_rust.dmm
  _maps/templates/engines/triumph/triumph_engine_sme.dmm
  code/game/area/Space Station 13 areas.dm
Labels: Currently Testmerged, Map Edit, Mechanic

#3948 Captain's Closet Adjustments
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/game/objects/structures/crates_lockers/closets/wardrobe.dm
  code/modules/clothing/suits/miscellaneous.dm
  icons/mob/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: Currently Testmerged, Sprites, Mechanic

#3951 fixes ghosts not seeing other ghosts
  code/modules/mob/dead/observer/observer.dm
Labels: Currently Testmerged

#3950 grinders start with beakers again
  code/modules/reagents/Chemistry-Machinery.dm
Labels: Currently Testmerged

#3952 More organ development.
  code/__DEFINES/damage_organs.dm
  code/_onclick/cyborg.dm
  code/game/dna/dna2.dm
  code/game/dna/dna2_helpers.dm
  code/game/gamemodes/changeling/powers/escape_restraints.dm
  code/game/gamemodes/changeling/powers/revive.dm
  code/game/machinery/computer/arcade.dm
  code/game/objects/items/devices/defib.dm
  code/game/objects/items/weapons/handcuffs.dm
  code/game/objects/items/weapons/implants/implantcase.dm
  code/game/objects/items/weapons/implants/implanter.dm
  code/game/objects/items/weapons/implants/implantfreedom.dm
  code/game/objects/items/weapons/implants/implantrestrainingbolt.dm
  code/game/objects/items/weapons/tools/wirecutters.dm
  code/game/objects/objs.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/modules/cargo/supplypacks/robotics.dm
  code/modules/client/preference_setup/vore/01_ears.dm
  code/modules/food/food/drinks.dm
  code/modules/mob/holder.dm
  code/modules/mob/living/bot/secbot.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/carbon/human/human_modular_limbs.dm
  code/modules/mob/living/carbon/human/human_powers.dm
  code/modules/mob/living/carbon/human/human_resist.dm
  code/modules/mob/living/carbon/human/inventory.dm
  code/modules/mob/living/carbon/human/species/outsider/event.dm
  code/modules/mob/living/carbon/human/species/species.dm
  code/modules/mob/living/carbon/human/species/species_shapeshift.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/carbon/resist.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_movement.dm
  code/modules/mob/new_player/sprite_accessories.dm
  code/modules/organs/internal/augment.dm
  code/modules/organs/internal/brain.dm
  code/modules/organs/organ_external.dm
  code/modules/organs/organ_icon.dm
  code/modules/organs/robolimbs.dm
  code/modules/organs/subtypes/standard.dm
  code/modules/vore/appearance/sprite_accessories_vr.dm
  code/modules/vore/appearance/update_icons_vr.dm
  icons/mob/vore/ears_32x64.dmi
  icons/mob/vore/ears_uneven.dmi
  icons/mob/vore/ears_vr.dmi
  icons/mob/vore/tails_vr.dmi
  icons/mob/vore/taurs_vr.dmi
  icons/mob/vore/wings_vr.dmi
  vorestation.dme
Labels: Currently Testmerged, Fix, Sprites, Mechanic

#3954 nukes outfit /decl's from orbit
  code/__HELPERS/_lists_tg.dm
  code/__HELPERS/sorts/comparators.dm
  code/datums/category.dm
  code/datums/hierarchy.dm
  code/datums/outfits/costumes/costume.dm
  code/datums/outfits/costumes/halloween.dm
  code/datums/outfits/horror_killers.dm
  code/datums/outfits/jobs/cargo.dm
  code/datums/outfits/jobs/civilian.dm
  code/datums/outfits/jobs/command.dm
  code/datums/outfits/jobs/engineering.dm
  code/datums/outfits/jobs/job.dm
  code/datums/outfits/jobs/medical.dm
  code/datums/outfits/jobs/misc.dm
  code/datums/outfits/jobs/science.dm
  code/datums/outfits/jobs/security.dm
  code/datums/outfits/jobs/special.dm
  code/datums/outfits/military/fleet.dm
  code/datums/outfits/military/marines.dm
  code/datums/outfits/military/military.dm
  code/datums/outfits/military/sysguard.dm
  code/datums/outfits/misc.dm
  code/datums/outfits/nanotrasen.dm
  code/datums/outfits/outfit.dm
  code/datums/outfits/pirates.dm
  code/datums/outfits/spec_op.dm
  code/datums/outfits/tournament.dm
  code/datums/outfits/wizardry.dm
  code/modules/admin/verbs/debug.dm
  code/modules/client/preference_setup/preference_setup.dm
  code/modules/jobs/job.dm
  code/modules/jobs/job_types/assistant.dm
  code/modules/jobs/job_types/captain.dm
  code/modules/jobs/job_types/cargo.dm
  code/modules/jobs/job_types/civilian.dm
  code/modules/jobs/job_types/civilian_chaplain.dm
  code/modules/jobs/job_types/engineering.dm
  code/modules/jobs/job_types/exploration.dm
  code/modules/jobs/job_types/medical.dm
  code/modules/jobs/job_types/offduty.dm
  code/modules/jobs/job_types/science.dm
  code/modules/jobs/job_types/security.dm
  code/modules/jobs/job_types/silicon.dm
  code/modules/jobs/job_types/special.dm
  code/modules/maps/misc_maps/trade/trade_station_jobs.dm
  code/modules/maps/talon/talon_jobs.dm
Labels: Currently Testmerged

#3955 fixes roundstart being a black screen
  code/datums/perspective.dm
Labels: Currently Testmerged, P1: High

#3956 fixes lobby being a black screen
  code/modules/mob/new_player/login.dm
  code/modules/mob/new_player/logout.dm
  code/modules/mob/new_player/new_player.dm
Labels: Currently Testmerged
