Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2022-03, with the labels that each got.

#3764 Adds songs to the country/western genre in jukebox
  config_static/jukebox.json
Labels: Currently Testmerged, Config Update, Mechanic

#3766 Fixes Weather, Enables Dynamic Lighting
  code/game/area/Off Station Areas.dm
  maps/nsv_triumph/triumph_defines.dm
  vorestation.dme
Labels: Currently Testmerged, Fix

#3761 Bugfix: Exploration Locker Icon States, Weather Icon States, Tweaks and Additions
  _maps/map_files/triumph/triumph-04-deck4.dmm
  _maps/map_levels/140x140/frozen_planet.dmm
  _maps/map_levels/140x140/gaia_planet.dmm
  code/_onclick/hud/_defines.dm
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/game/machinery/biogenerator.dm
  code/game/machinery/suit_storage/suit_storage_prepared.dm
  code/game/objects/items/stacks/sandbag.dm
  code/game/objects/items/weapons/material/chainsaw.dm
  code/game/objects/items/weapons/melee/misc.dm
  code/game/objects/items/weapons/nullrod.dm
  code/modules/maps/misc_maps/space/levels/trade_station.dm
  code/modules/maps/triumph/levels/frozen_planet.dm
  code/modules/maps/triumph/levels/gaia_planet.dm
  code/modules/xenoarcheaology/artifacts/artifact.dm
  icons/effects/weather.dmi
  icons/obj/closet.dmi
  icons/obj/items.dmi
  icons/obj/weapons.dmi
Labels: Currently Testmerged, Fix, Sprites, Map Edit

#3768 Adds wooden panelling
  code/game/objects/items/weapons/material/shards.dm
  code/game/objects/structures/window.dm
  code/modules/materials/material_recipes.dm
  icons/obj/structures.dmi
  icons/obj/structures_vr.dmi
Labels: Currently Testmerged, Sprites, Mechanic

#3767 [Minor] Re-cleaning and Re-implementing lost Teshari sprites
  code/modules/clothing/clothing.dm
  code/modules/clothing/spacesuits/void/void_vr.dm
  code/modules/clothing/suits/aliens/teshari.dm
  code/modules/clothing/under/accessories/accessory.dm
  code/modules/food/food/snacks.dm
  icons/mob/species/teshari/deptjacket.dmi
  icons/mob/species/teshari/ears.dmi
  icons/mob/species/teshari/eyes.dmi
  icons/mob/species/teshari/head.dmi
  icons/mob/species/teshari/helmet_vr.dmi
  icons/mob/species/teshari/masks.dmi
  icons/mob/species/teshari/masks_vr.dmi
  icons/mob/species/teshari/suit.dmi
  icons/mob/species/teshari/suit_vr.dmi
  icons/mob/species/teshari/teshari_hood_vr.dmi
  icons/mob/species/teshari/teshari_uniform.dmi
  icons/mob/species/teshari/ties_vr.dmi
  icons/mob/species/teshari/uniform.dmi
  icons/obj/clothing/collars.dmi
  icons/obj/clothing/species/teshari/suits.dmi
  icons/obj/clothing/species/teshari/uniform.dmi
Labels: Currently Testmerged, Fix, Sprites

#3734 removes smes power alerts
  _maps/map_levels/140x140/Class_D.dmm
  _maps/map_levels/140x140/frozen_planet.dmm
  _maps/submaps/level_specific/virgo2/CrashedSmuggler.dmm
  code/modules/power/smes.dm
Labels: Removal, Map Edit

#3770 Actual Planetary Dynamic Lighting
  code/game/area/Off Station Areas.dm
  maps/nsv_triumph/classh.dm
  maps/nsv_triumph/frozen_planet.dm
  maps/nsv_triumph/gaia_planet.dm
  maps/nsv_triumph/lavaland.dm
  maps/nsv_triumph/triumph.dm
  vorestation.dme
Labels: Currently Testmerged, Fix

#3757 Operation Ashen Tremor
  _maps/lavaland.json
  _maps/map_levels/140x140/lavaland.dmm
  _maps/map_levels/140x140/lavaland_dungeon.dmm
  _maps/map_levels/140x140/lavaland_east.dmm
  _maps/submaps/level_specific/lavaland/boss1.dmm
  _maps/submaps/level_specific/lavaland/botany.dmm
  _maps/submaps/level_specific/lavaland/dogs.dmm
  _maps/submaps/level_specific/lavaland/horrors.dmm
  _maps/submaps/level_specific/lavaland/idleruins1.dmm
  _maps/submaps/level_specific/lavaland/idleruins2.dmm
  _maps/submaps/level_specific/lavaland/shelter.dmm
  code/game/area/Off Station Areas.dm
  code/game/machinery/event.dm
  code/game/objects/items/weapons/circuitboards/machinery/event.dm
  code/game/objects/items/weapons/melee/misc.dm
  code/game/turfs/flooring/flooring.dm
  code/game/turfs/flooring/flooring_traps.dm
  code/modules/maps/triumph/levels/lavaland.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/cyber_horror/cyber_horror.dm
  code/modules/paperwork/paper.dm
  code/modules/planet/lavaland.dm
  icons/mecha/mech_construct.dmi
  icons/mob/64x64.dmi
  icons/obj/machines/event.dmi
  icons/obj/stock_parts.dmi
  icons/obj/weapons.dmi
  icons/turf/outdoors_edge.dmi
  maps/nsv_triumph/lavaland.dm
  maps/nsv_triumph/submaps/_triumph_submaps.dm
  maps/nsv_triumph/submaps/lavaland/_lavaland.dm
  maps/nsv_triumph/triumph_defines.dm
  maps/~map_system/maps.dm
Labels: Currently Testmerged, Sprites, Map Edit, Mechanic

#3772 Cleans up vey-med skrell prosthetics
  code/modules/organs/robolimbs.dm
Labels: Currently Testmerged

#3777 Yarn-TGUI Dependecies
  tgui/public/tgui-common.bundle.js
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.js
  tgui/yarn.lock
Labels: Currently Testmerged, UI

#3776 Fixes Autoinjector Bug
  code/modules/reagents/machinery/chem_master.dm
Labels: Currently Testmerged, Fix

#3775 Fixes Atmos for Class D
  _maps/map_levels/140x140/mining_planet.dmm
  code/__DEFINES/atmospherics/atmospheres.dm
  code/modules/maps/misc_maps/planets/levels/classd.dm
  code/modules/maps/triumph/levels/mining_planet.dm
  vorestation.dme
Labels: Currently Testmerged, Fix, Map Edit

#3778 Salt PR: Moves the R&D Sulphuric Acid Dispenser over one tile so it stops blocking thrown items. Also adds a door to the circuitry room so I don't have to walk all the way around into a garden to access it.
  _maps/map_files/triumph/triumph-03-deck3.dmm
Labels: Currently Testmerged, Map Edit

#3786 Buffs Clear Sky Time on Surt
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  maps/nsv_triumph/lavaland.dm
Labels: Currently Testmerged

#3783 Fixes sprites and unused sprite linking.
  code/modules/client/preference_setup/loadout/loadout_role_restricted.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/clothing/under/color.dm
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/clothing/under/jobs/engineering.dm
  code/modules/clothing/under/jobs/medsci.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/human_races/r_human_vr.dmi
  icons/mob/ties.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Currently Testmerged, Sprites, Code Improvement, Grammar and Formatting

#3787 Gives default-named glasses names and descriptions
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
Labels: Currently Testmerged, Fix

#3790 Adds the Latex Swimsuit
  code/game/machinery/vending.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/vore/fluffstuff/custom_boxes.dm
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites, Mechanic

#3788 Anti-Drone Map Edit, Also Adds Community Theater
  _maps/map_files/triumph/triumph-01-deck1.dmm
  _maps/map_files/triumph/triumph-02-deck2.dmm
  _maps/map_files/triumph/triumph-03-deck3.dmm
  _maps/map_files/triumph/triumph-04-deck4.dmm
Labels: Removal, Map Edit, Mechanic

#3737 [RFM] Xenomorph hybrids get a bunch of abilities from our xenomorph and two extras
  code/__DEFINES/chemistry.dm
  code/game/objects/structures/stool_bed_chair_nest/alien_nests.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/mob/living/carbon/human/species/station/xenomorph_hybrids/hybrid_abilities.dm
  code/modules/mob/living/carbon/human/species/station/xenomorph_hybrids/hybrid_resin.dm
  code/modules/mob/living/carbon/human/species/station/xenomorph_hybrids/xeno_hybrids.dm
  code/modules/organs/subtypes/xenos.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Toxins.dm
  vorestation.dme
Labels: Currently Testmerged, Mechanic

#3780 Adds a New RIG Backpack Type
  code/__HELPERS/global_lists.dm
  code/datums/outfits/outfit.dm
  code/game/jobs/job/job.dm
  code/game/objects/items/storage/backpack.dm
  code/modules/client/preference_setup/general/04_equipment.dm
  code/modules/mob/new_player/preferences_setup.dm
  icons/mob/back.dmi
  icons/obj/clothing/backpack.dmi
Labels: Currently Testmerged, Sprites, Mechanic

#3792 Pasta's premium gendered sprites/sprite fixes/loadout cleanup
  _maps/away_missions/140x140/snow_outpost.dmm
  _maps/submaps/level_specific/debrisfield/ship_sup_exploded.dmm
  _maps/submaps/level_specific/debrisfield_vr/ship_sup_exploded.dmm
  _maps/submaps/level_specific/virgo2/Epod4.dmm
  _maps/submaps/mountains/quarantineshuttle.dmm
  _maps/submaps/wilderness/Epod4.dmm
  _maps/templates/shuttles/overmaps/generic/vespa.dmm
  code/game/machinery/vending.dm
  code/modules/client/preference_setup/loadout/loadout_role_restricted.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/clothing/under/jobs/civilian.dm
  code/modules/clothing/under/jobs/engineering.dm
  code/modules/clothing/under/jobs/medsci.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites, Grammar and Formatting, Map Edit, Mechanic

#3793 Solarmoff draining and synth nutrition
  code/modules/mob/living/carbon/human/species/station/station_special_abilities.dm
  code/modules/vore/eating/bellymodes_vr.dm
Labels: Mechanic

#3779 Coin Update
  code/datums/wires/coinbank.dm
  code/game/objects/random/misc.dm
  code/modules/food/food/snacks.dm
  code/modules/mining/abandonedcrates.dm
  code/modules/mining/coins.dm
  code/modules/mining/mint.dm
  code/modules/mining/money_bag.dm
  icons/obj/items.dmi
  icons/obj/vending.dmi
  vorestation.dme
Labels: Currently Testmerged, Sprites, Mechanic

#3798 Adds the Vainglorious Hoodie, a Certain Jacket, and Short Elf Ears
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/clothing/head/hood.dm
  code/modules/clothing/suits/hooded.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/suits/storage.dm
  code/modules/vore/appearance/sprite_accessories_vr.dm
  icons/mob/head.dmi
  icons/mob/suit.dmi
  icons/mob/vore/ears_vr.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: Currently Testmerged, Sprites, Mechanic

#3799 Hotline Triumph Update
  code/datums/supplypacks/misc.dm
  code/game/objects/items/storage/boxes.dm
  code/modules/power/lighting.dm
  icons/obj/storage.dmi
Labels: Currently Testmerged, Sprites, Mechanic

#3800 Fixes the pleated skirt sprite not appearing
  icons/mob/uniform.dmi
Labels: Currently Testmerged, Fix, Sprites

#3797 Creates new item type, cleans up code, fixes unintentional buff
  code/modules/client/preference_setup/loadout/loadout_donator.dm
  code/modules/clothing/ears/ears.dm
  code/modules/clothing/ears/speakrock.dm
  vorestation.dme
Labels: Currently Testmerged, Fix, Removal, Mechanic

#3801 Changes RD console sync range from 3 to 5 tiles
  code/modules/research/rdconsole.dm
Labels: Currently Testmerged

#3802 Maint drones now die if you ghost from them, no more pseudo alive drones!
  code/modules/mob/living/silicon/robot/drone/drone.dm
  code/modules/mob/living/silicon/robot/drone/drone_vr.dm
  vorestation.dme
Labels: Currently Testmerged, Fix

#3803 gives lizards steroids
  code/modules/gamemaster/actions/infestation.dm
Labels: Currently Testmerged, Fix

#3806 fixes medbot construction
  code/modules/mob/living/bot/medbot.dm
Labels: Currently Testmerged

#3804 Containment Specialist as alt title
  code/game/jobs/job/exploration.dm
Labels: Currently Testmerged

#3808 adds relative layer shifting + pointing animations
  code/__DEFINES/_planes+layers.dm
  code/game/atom_vv.dm
  code/game/atoms.dm
  code/modules/mob/death.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/living_powers.dm
  code/modules/mob/living/simple_mob/simple_mob_vr.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_grab.dm
Labels: Currently Testmerged

#3811 Class P CI Hotfix
  _maps/map_levels/140x140/Class_P.dmm
  _maps/submaps/level_specific/class_p/archaictemple.dmm
Labels: Fix, Map Edit

#3813 Removes Gravitons from R&D Protolathe
  code/modules/research/designs/HUDs.dm
Labels: Currently Testmerged, Removal

#3814 Fixes Alloying Brass to Actually Produce Brass
  code/datums/components/crafting/recipes/recipes_misc.dm
  code/modules/mining/alloys.dm
Labels: Currently Testmerged, Fix

#3809 Explo Nerf #635 - Give Medbay A Job Again Expansion
  _maps/map_files/triumph/triumph-04-deck4.dmm
  code/game/machinery/suit_storage/suit_storage_prepared.dm
Labels: Currently Testmerged, Map Edit

#3816 fixes logging
  code/modules/mob/mob.dm
Labels: Currently Testmerged

#3812 lighting subsystem is slightly more bulletproof
  code/controllers/subsystems/lighting.dm
Labels: Currently Testmerged

#3820 updates icon smoothing tgui
  tgui/public/tgui.bundle.js
Labels: Sprites, UI

#3819 Lets allow Super old species to have an older min_age
  code/modules/client/preference_setup/preference_setup.dm
Labels: Currently Testmerged, Fix

#3818 Adds a New Drink - Goliath Spit + Adds Classic Lavaland Mob Sprites + Starts Laying Groundwork to Add Goliaths
  code/modules/food/drinkingglass/metaglass.dm
  code/modules/materials/material_recipes.dm
  code/modules/mob/living/simple_mob/subtypes/lavaland/goliath.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/reagents/Drink-Recipes.dm
  icons/mob/lavaland/64x64megafauna.dmi
  icons/mob/lavaland/96x96megafauna.dmi
  icons/mob/lavaland/hierophant.dmi
  icons/mob/lavaland/hierophant_new.dmi
  icons/mob/lavaland/lavaland_elites.dmi
  icons/mob/lavaland/lavaland_mobs.dmi
  icons/mob/lavaland/watcher.dmi
  icons/obj/drinks.dmi
Labels: Currently Testmerged, Sprites, Mechanic

#3821 Automated suit storage closets
  _maps/map_files/triumph/triumph-04-deck4.dmm
  code/game/machinery/suit_storage/suit_storage_massive.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/species/station/xenomorph_hybrids/xeno_hybrids.dm
Labels: Currently Testmerged, Fix, Map Edit

#3815 Pear's Beruang Trade Ship Overhaul
  _maps/map_files/triumph/triumph-02-deck2.dmm
  _maps/map_levels/140x140/tradeport.dmm
  _maps/submaps/level_specific/class_p/archaictemple.dmm
  code/game/mecha/mech_prosthetics.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/random/guns_and_ammo.dm
  code/modules/projectiles/guns/energy/stun.dm
  code/modules/research/prosfab_designs.dm
Labels: Currently Testmerged, Map Edit

#3817 Ports Nightshift from Paradise
  code/__DEFINES/controllers/_subsystems.dm
  code/__DEFINES/lighting.dm
  code/__HELPERS/time.dm
  code/_globalvars/misc.dm
  code/controllers/configuration/entries/game_options.dm
  code/controllers/configuration_old/configuration.dm
  code/controllers/subsystems/game_master.dm
  code/controllers/subsystems/nightshift.dm
  code/controllers/subsystems/planets.dm
  code/controllers/subsystems/transfer.dm
  code/game/gamemodes/cult/hell_universe.dm
  code/game/gamemodes/cult/ritual.dm
  code/game/gamemodes/endgame/supermatter_cascade/universe.dm
  code/game/gamemodes/events.dm
  code/game/gamemodes/events/power_failure.dm
  code/game/gamemodes/game_mode_latespawn.dm
  code/game/gamemodes/malfunction/newmalf_ability_trees/HELPERS.dm
  code/game/gamemodes/malfunction/newmalf_ability_trees/tree_networking.dm
  code/game/machinery/exonet_node.dm
  code/game/machinery/newscaster.dm
  code/game/world.dm
  code/modules/admin/verbs/debug.dm
  code/modules/events/ion_storm.dm
  code/modules/integrated_electronics/subtypes/time.dm
  code/modules/modular_computers/file_system/programs/engineering/rcon_console.dm
  code/modules/power/apc.dm
  code/modules/power/cells/power_cells.dm
  code/modules/power/lighting.dm
  code/modules/security levels/security levels.dm
  code/modules/xenoarcheaology/effects/cellcharge.dm
  code/modules/xenoarcheaology/effects/celldrain.dm
  config/entries/game_options.txt
  maps/~map_system/maps.dm
  tgui/packages/tgui/interfaces/APC.js
  tgui/public/tgui.bundle.css
  tgui/public/tgui.bundle.js
  vorestation.dme
Labels: Currently Testmerged, Refactor, UI, Config Update, Mechanic

#3824 Adds My Snowflake Cigarettes as a Real Brand, Adds Another New Drink
  code/game/machinery/vending.dm
  code/game/objects/items/storage/fancy.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/modules/examine/descriptions/smokeables.dm
  code/modules/food/drinkingglass/metaglass.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/reagents/Drink-Recipes.dm
  icons/mob/mask.dmi
  icons/obj/cigarettes.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/drinks.dmi
Labels: Currently Testmerged, Sprites, Mechanic

#3826 The gamemode announcement at round start now tells what engine is used, additional to the gamemode
  code/controllers/subsystems/mapping/_mapping.dm
  code/game/gamemodes/game_mode.dm
Labels: Currently Testmerged

#3827 fixes chargesword combining
  code/game/objects/items/weapons/melee/energy.dm
  html/changelog.html
  html/changelogs/.all_changelog.yml
Labels: Currently Testmerged

#3833 Fixes Water Breathing Trait, Gives Akula Water Movement, and Removes Vore Wiki Links from Race Blurbs
  code/game/turfs/simulated/water.dm
  code/modules/mob/living/carbon/human/species/station/diona.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
  code/modules/mob/living/carbon/human/species/station/teshari.dm
Labels: Currently Testmerged

#3835 Adds 13 New Recipes
  code/modules/food/food/snacks.dm
  code/modules/food/recipes_fryer.dm
  code/modules/food/recipes_microwave.dm
  code/modules/food/recipes_oven.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/reagents/Food-Recipes.dm
  icons/obj/food.dmi
Labels: Currently Testmerged, Sprites, Mechanic

#3837 adds doll plushi
  code/game/objects/items/toys.dm
  icons/obj/toy.dmi
Labels: Currently Testmerged, Sprites

#3841 Adds universal enzyme to the biogenerator
  code/game/machinery/biogenerator.dm
Labels: Currently Testmerged

#3838 smokeweedeveryday.mp4
  code/game/machinery/vending.dm
  code/game/objects/items/storage/fancy.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  icons/mob/mask.dmi
  icons/obj/clothing/masks.dmi
Labels: Sprites, Mechanic

#3828 She Does It for Free
  _maps/map_files/triumph/triumph-02-deck2.dmm
  code/__DEFINES/misc.dm
  code/game/machinery/vending.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/random/misc.dm
  code/game/objects/structures/morgue.dm
  code/modules/client/preference_setup/loadout/loadout_accessories.dm
  code/modules/client/preference_setup/loadout/loadout_gloves.dm
  code/modules/client/preference_setup/loadout/loadout_head.dm
  code/modules/client/preference_setup/loadout/loadout_shoes.dm
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/head/hood.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/suits/hooded.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/accessories/clothing.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/materials/material_recipes.dm
  icons/mob/back.dmi
  icons/mob/feet.dmi
  icons/mob/hands.dmi
  icons/mob/head.dmi
  icons/mob/mask.dmi
  icons/mob/suit.dmi
  icons/mob/ties.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/backpack.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/masks.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/ties.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/items.dmi
  icons/obj/storage.dmi
Labels: Currently Testmerged, Sprites, Map Edit, Mechanic

#3831 [RFM]"CRyP70 - 9er" content
  _maps/map_files/triumph/triumph-01-deck1.dmm
  code/datums/supplypacks/engineering.dm
  code/game/machinery/computer/supply.dm
  code/game/objects/items/holosign_creator.dm
  code/game/objects/items/weapons/id cards/station_ids.dm
  code/game/objects/structures/holosign.dm
  code/modules/atmospherics/gasmixtures/gas_types.dm
  code/modules/mining/ore_redemption_machine/engineering_points_vendor.dm
  code/modules/mining/ore_redemption_machine/equipment_vendor.dm
  code/modules/mining/ore_redemption_machine/mine_point_items.dm
  code/modules/mining/ore_redemption_machine/survey_vendor.dm
  code/modules/power/crypto_miner.dm
  icons/effects/atmospherics.dmi
  icons/effects/effects.dmi
  icons/misc/Consoles_and_Servers.dmi
  icons/obj/machines/mining_machines.dmi
  icons/obj/tank_vr.dmi
  icons/obj/vouchers.dmi
  vorestation.dme
Labels: Currently Testmerged, Sprites, Map Edit, Mechanic

#3844 why would you put an eject button you'd wanna hit fast behind reinforced borosilicate glass tho
  _maps/templates/engines/triumph/triumph_engine_fission.dmm
Labels: Map Edit

#3842 The Apidean Update
  code/game/objects/items/stacks/tiles/fifty_spawner_tiles.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/turfs/flooring/flooring.dm
  code/modules/food/drinkingglass/metaglass.dm
  code/modules/food/food/snacks.dm
  code/modules/food/recipes_fryer.dm
  code/modules/food/recipes_microwave.dm
  code/modules/food/recipes_oven.dm
  code/modules/hydroponics/beekeeping/beehive.dm
  code/modules/materials/fifty_spawner_mats.dm
  code/modules/materials/material_recipes.dm
  code/modules/materials/material_sheets.dm
  code/modules/materials/materials.dm
  code/modules/projectiles/ammunition/magazines.dm
  code/modules/projectiles/ammunition/rounds.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  code/modules/projectiles/guns/projectile/semiauto.dm
  code/modules/projectiles/projectile/special.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/reagents/Drink-Recipes.dm
  icons/obj/ammo.dmi
  icons/obj/beekeeping.dmi
  icons/obj/drinks.dmi
  icons/obj/food.dmi
  icons/obj/gun/ballistic.dmi
  icons/obj/gun/energy.dmi
  icons/obj/stacks.dmi
  icons/turf/flooring/misc.dmi
Labels: Currently Testmerged, Sprites, Mechanic
