Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2022-05, with the labels that each got.

#3957 adds holy water to cargo
  code/modules/cargo/supplypacks/misc.dm
Labels: Currently Testmerged

#3961 ghostroles
  SpacemanDMM.toml
  code/__DEFINES/auxtools.dm
  code/__DEFINES/dcs/signals/signals_atom/signals_atom_attack.dm
  code/__DEFINES/rendering/alert.dm
  code/__DEFINES/spaceman_dmm.dm
  code/__DEFINES/traits.dm
  code/__HELPERS/lists/json.dm
  code/_onclick/hud/_defines.dm
  code/_onclick/hud/alert.dm
  code/_onclick/hud/ghost.dm
  code/_onclick/observer.dm
  code/datums/mind.dm
  code/game/gamemodes/endgame/supermatter_cascade/blob.dm
  code/game/machinery/adv_med.dm
  code/game/machinery/atmoalter/pump.dm
  code/game/machinery/atmoalter/scrubber.dm
  code/game/machinery/computer/law.dm
  code/game/machinery/doors/airlock.dm
  code/game/machinery/teleporter/pad.dm
  code/game/objects/structures/catwalk.dm
  code/game/objects/structures/crates_lockers/closets.dm
  code/game/objects/structures/ghost_pods/ghost_pods.dm
  code/game/objects/structures/window_spawner.dm
  code/game/world.dm
  code/modules/atmospherics/components/binary_devices/pump.dm
  code/modules/client/client_procs.dm
  code/modules/ghostroles/instantiator.dm
  code/modules/ghostroles/menu.dm
  code/modules/ghostroles/role.dm
  code/modules/ghostroles/roles/ash_lizard.dm
  code/modules/ghostroles/roles/cybersun_cruiser.dm
  code/modules/ghostroles/roles/demonic_friend.dm
  code/modules/ghostroles/roles/fugitives.dm
  code/modules/ghostroles/roles/ghost_cafe.dm
  code/modules/ghostroles/roles/golem.dm
  code/modules/ghostroles/roles/hermit.dm
  code/modules/ghostroles/roles/hotel.dm
  code/modules/ghostroles/roles/lifebringer.dm
  code/modules/ghostroles/roles/oldresearch.dm
  code/modules/ghostroles/roles/pirate.dm
  code/modules/ghostroles/roles/prisoner.dm
  code/modules/ghostroles/roles/timeless_prison.dm
  code/modules/ghostroles/roles/vet.dm
  code/modules/ghostroles/spawner.dm
  code/modules/ghostroles/spawnpoint.dm
  code/modules/hydroponics/trays/tray.dm
  code/modules/mining/ore_redemption_machine/equipment_vendor.dm
  code/modules/mob/mob_helpers.dm
  code/modules/modular_computers/computers/modular_computer/interaction.dm
  code/modules/multiz/ladder.dm
  code/modules/overmap/ships/computers/computer_shims.dm
  code/modules/power/cable.dm
  code/modules/reagents/machinery/dispenser/dispenser2.dm
  code/modules/turbolift/turbolift_console.dm
  icons/hud/common/observer.dmi
  icons/obj/spawners.dmi
  tgui/packages/tgui/interfaces/GhostRoleMenu.js
  tgui/public/tgui.bundle.js
  vorestation.dme
Labels: Sprites, UI, Mechanic

#3960 stun beams no longer play laser impact sfx
  code/modules/projectiles/projectile/beam/beams.dm
Labels: Fix

#3962 removes infinite recursion bug on acid_act
  code/game/atoms_movable.dm
Labels: Priority 1: High, Removal

#3964 Deletes dmdoc workflow
  .github/workflows/generate_documentation.yml
Labels: GitHub

#3967 Fixes mecha locking clent.eye to it on exit
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/login.dm
  code/modules/mob/perspective.dm
Labels: Priority 1: High

#3945 new vampire trait + why could literally anyone with hands drain IV packs and get nutrients from it
  code/modules/mob/living/carbon/human/species/station/traits/neutral.dm
  code/modules/reagents/reagent_containers/blood_pack_vr.dm
Labels: Currently Testmerged, Fix, Mechanic

#3959 adds mechanical blindness, deafness, muteness, as opt in traits
  code/__DEFINES/traits.dm
  code/modules/mob/living/carbon/human/say.dm
  code/modules/mob/living/carbon/human/traits/_trait.dm
  code/modules/mob/living/carbon/human/traits/negative.dm
  code/modules/mob/living/carbon/human/traits/neutral.dm
  code/modules/mob/living/carbon/human/traits/positive.dm
  code/modules/mob/living/carbon/human/traits/weaver_objs.dm
  code/modules/mob/living/carbon/human/traits/weaver_recipies.dm
  code/modules/mob/living/carbon/metroid/life.dm
  code/modules/mob/living/life.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defense.dm
  code/modules/mob/living/say.dm
  code/modules/mob/living/silicon/robot/life.dm
  vorestation.dme
Labels: Mechanic

#3974 Adds a gun overlay for Science-Hounds (and maybe science borgs?)
  code/modules/mob/living/silicon/robot/robot_vr.dm
Labels: Currently Testmerged, Fix

#3987 bandaid patch to a very old and very horribly coded line
  code/game/area/areas.dm
Labels: Currently Testmerged

#3979 unified economy api
  code/__DEFINES/dcs/signals/signals_item/signals_item_economy.dm
  code/__DEFINES/economy/economy.dm
  code/__DEFINES/economy/payment.dm
  code/__DEFINES/economy/worth.dm
  code/__DEFINES/misc.dm
  code/game/machinery/vending.dm
  code/global.dm
  code/modules/economy/currency.dm
  code/modules/economy/economy_misc.dm
  code/modules/economy/items/EFTPOS.dm
  code/modules/economy/items/bank_card.dm
  code/modules/economy/items/cash.dm
  code/modules/economy/items/coins.dm
  code/modules/economy/items/retail_scanner.dm
  code/modules/economy/machines/ATM.dm
  code/modules/economy/machines/Accounts_DB.dm
  code/modules/economy/machines/cash_register.dm
  code/modules/economy/machines/mint.dm
  code/modules/economy/money_bag.dm
  code/modules/economy/worth.dm
  code/modules/multiz/zshadow.dm
  vorestation.dme
Labels: Currently Testmerged, Refactor

#3977 Reactivates the Autosave Smite
  code/modules/admin/verbs/smite_vr.dm
Labels: Currently Testmerged, Mechanic

#3978 Adds Inmon Tattoo Marking
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_races/markings.dmi
Labels: Currently Testmerged, Sprites

#3988 Hub refresh 2022 - Cleans up hub desc code, adds some more config options, and more!
  code/_globalvars/lists/misc.dm
  code/controllers/configuration/entries/general.dm
  code/game/world.dm
  config/config.txt
  config/entries/hub.txt
  config/strings/server_taglines.txt
Labels: Config Update, good first pr, Mechanic

#3994 actually fixes observers spawning in space
  code/game/landmarks/landmarks.dm
Labels: IGNORE TRAVIS, Fix

#3997 fixes wall construction ChangeTurf --> PlaceOnTop
  code/game/objects/structures/girders.dm
Labels: IGNORE TRAVIS, Priority 1: High

#3996 fixes admin buildmode walls not leaving plating baseturfs
  code/modules/admin/verbs/buildmode.dm
Labels: IGNORE TRAVIS, Priority 1: High, Fix

#3998 fixes baseturf issue
  code/game/turfs/simulated/floor.dm
Labels: IGNORE TRAVIS, Priority 1: High

#3999 fixes baseturf issue x2
  code/game/turfs/simulated/walls.dm
Labels: IGNORE TRAVIS, Priority 1: High

#4000 fixes baseturf issue x3
  code/game/turfs/turf.dm
Labels: IGNORE TRAVIS, Priority 1: High

#4001 Regexes /obj/storage/toolbox/surgery to /obj/storage/firstaid/surgery
  _maps/away_missions/140x140/snow_outpost.dmm
  _maps/map_files/tether/tether-03-surface3.dmm
  _maps/map_files/tether/tether_misc.dmm
  _maps/map_files/triumph/triumph-03-deck3.dmm
  _maps/map_files/triumph/triumph-05-flagship.dmm
  _maps/map_levels/140x140/lavaland_east.dmm
  _maps/map_levels/140x140/talon/talon1.dmm
  _maps/map_levels/140x140/tradeport.dmm
  _maps/submaps/level_specific/class_d/Possesed_mech_cave.dmm
  _maps/submaps/level_specific/virgo2/Blackshuttledown.dmm
  _maps/submaps/wilderness/Blackshuttledown.dmm
  _maps/submaps/wilderness/Blueshuttledown.dmm
  _maps/templates/admin/dhael_centcom.dmm
  _maps/templates/admin/ert.dmm
  _maps/templates/admin/ert_base.dmm
  _maps/templates/admin/kk_mercship.dmm
  _maps/templates/shelters/shelter_4.dmm
  _maps/templates/shuttles/overmaps/generic/cruiser.dmm
  _maps/templates/shuttles/overmaps/generic/curashuttle.dmm
  _maps/templates/shuttles/overmaps/generic/itglight.dmm
  _maps/templates/shuttles/overmaps/generic/mercenarybase.dmm
  _maps/templates/shuttles/overmaps/generic/mercship.dmm
  _maps/templates/shuttles/overmaps/generic/shelter_6.dmm
  _maps/templates/shuttles/overmaps/generic/vespa.dmm
  code/datums/uplink/medical.dm
  code/game/objects/items/storage/firstaid.dm
  code/modules/mob/living/bot/floorbot.dm
Labels: Priority 1: High, Map Edit

#4005 fixes frostlocks, maint changes
  _maps/map_files/rift/rift-02-underground1.dmm
  _maps/map_files/rift/rift-03-surface1.dmm
  _maps/map_files/rift/rift-05-surface3.dmm
Labels: Map Edit

#3989 Makes Sergals great Again
  code/__DEFINES/carbon/species.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
Labels: enhancement, Currently Testmerged, FUCK, Code Improvement, Balance/Rebalance, Removal, Salt, Stale

#4010 fixes the airlocks for real (hopefully), adds a gantry to sec observation
  _maps/map_files/rift/rift-03-surface1.dmm
  _maps/map_files/rift/rift-04-surface2.dmm
  _maps/map_files/rift/rift-05-surface3.dmm
Labels: Map Edit

#3995 Tweaks Red Armory Weaponry
  _maps/map_files/triumph/triumph-04-deck4.dmm
Labels: Map Edit, Mechanic

#4008 monkey patches space heaters to actually be usable
  code/game/machinery/spaceheater.dm
Labels: Ready for Review

#4007 fixes turbolifts tearing holes into space
  code/__HELPERS/unsorted.dm
Labels: IGNORE TRAVIS, Ready for Review

#4004 bumps midi2piano max line limit and length to match server sanitization limits
  tools/midi2piano/midi2piano.py
Labels: Tools

#4003 makes sdql2 usable by people on laptops
  code/modules/admin/verbs/SDQL2/SDQL_2.dm
Labels: IGNORE TRAVIS, Ready for Review

#4002 fast optimization pass
  code/controllers/subsystem/planets.dm
  code/game/machinery/floorlayer.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/floor_attackby.dm
  code/game/turfs/simulated/floor_icon.dm
  code/game/turfs/simulated/lava.dm
  code/game/turfs/simulated/outdoors/outdoors.dm
  code/game/turfs/simulated/outdoors/sky.dm
  code/game/turfs/simulated/water.dm
  code/game/turfs/space/space.dm
  code/game/turfs/unsimulated/planetary.dm
  code/modules/maps/tether/levels/tether_turfs.dm
  code/modules/mining/mine_turfs.dm
  code/modules/multiz/turf.dm
Labels: IGNORE TRAVIS, Ready for Review

#4009 maybe fixes defib?
  code/game/objects/items/devices/defib.dm
Labels: Fix

#4014 fix airlocks platinum redux fix harder edition
  _maps/map_files/rift/rift-01-underground2.dmm
  _maps/map_files/rift/rift-03-surface1.dmm
  _maps/map_files/rift/rift-04-surface2.dmm
  _maps/map_files/rift/rift-05-surface3.dmm
Labels: Map Edit

#4020 Removes Protean Ventcrawl - For Real This Time
  code/modules/mob/living/carbon/human/species/station/protean/protean_blob.dm
Labels: Removal

#4024 Lets fix some CI things I missed
  tgui/yarn.lock
  tools/deploy.sh
Labels: Tools, UI

#4016 Adds in a few moth clothing icons
  icons/mob/human_races/markings.dmi
  icons/mob/species/moth/moth_uniforms.dmi
Labels: Sprites

#4033 Adds cameras, fixes the AI bunker blast doors, updates the command bunker
  _maps/map_files/rift/rift-04-surface2.dmm
  _maps/map_files/rift/rift-05-surface3.dmm
Labels: Map Edit

#4034 sweater_fem
  code/modules/clothing/under/miscellaneous.dm
Labels: Grammar and Formatting

#4038 Stonks
  code/datums/browser/_browser.dm
  code/game/objects/items/weapons/circuitboards/computer/computer.dm
  code/modules/stockmarket/articles.dm
  code/modules/stockmarket/computer.dm
  code/modules/stockmarket/events.dm
  code/modules/stockmarket/industries.dm
  code/modules/stockmarket/logs.dm
  code/modules/stockmarket/stockmarket.dm
  code/modules/stockmarket/stocks.dm
  icons/obj/computer.dmi
  maps/citadel_minitest/citadel_minitest_defines.dm
  tgui/packages/tgui/interfaces/StockExchange.js
  tgui/public/tgui.bundle.js
  vorestation.dme
Labels: Sprites, UI, Mechanic

#4041 Bugfix: IC memory circuits & power cells
  code/modules/integrated_electronics/core/assemblies.dm
  code/modules/integrated_electronics/subtypes/memory.dm
Labels: Fix

#3992 adds/fixes mapping helpers for: windows, power lines
  _maps/map_files/tether/tether-01-surface1.dmm
  _maps/map_files/tether/tether-03-surface3.dmm
  _maps/map_files/tether/tether-05-station1.dmm
  _maps/map_files/tether/tether-06-station2.dmm
  _maps/map_files/triumph/triumph-01-deck1.dmm
  _maps/map_files/triumph/triumph-02-deck2.dmm
  _maps/map_files/triumph/triumph-03-deck3.dmm
  _maps/map_files/triumph/triumph-04-deck4.dmm
  _maps/map_levels/140x140/lavaland.dmm
  _maps/map_levels/140x140/talon/talon1.dmm
  _maps/map_levels/140x140/talon/talon2.dmm
  _maps/map_levels/140x140/tradeport.dmm
  _maps/submaps/level_specific/class_d/hiddenbunkerD.dmm
  _maps/submaps/level_specific/debrisfield_vr/gecko_cr_wreck.dmm
  _maps/submaps/level_specific/debrisfield_vr/mackerel_lc_wreck.dmm
  _maps/submaps/level_specific/debrisfield_vr/salamander_wreck.dmm
  _maps/submaps/level_specific/debrisfield_vr/tinycarrier.dmm
  _maps/templates/admin/dojo.dmm
  _maps/templates/admin/ert.dmm
  _maps/templates/admin/kk_mercship.dmm
  _maps/templates/shuttles/overmaps/generic/bearcat.dmm
  _maps/templates/shuttles/overmaps/generic/gecko_cr.dmm
  _maps/templates/shuttles/overmaps/generic/gecko_sh.dmm
  _maps/templates/shuttles/overmaps/generic/generic_shuttle.dmm
  _maps/templates/shuttles/overmaps/generic/itglight.dmm
  _maps/templates/shuttles/overmaps/generic/mackerel_hc.dmm
  _maps/templates/shuttles/overmaps/generic/mackerel_hc_skel.dmm
  _maps/templates/shuttles/overmaps/generic/mackerel_lc.dmm
  _maps/templates/shuttles/overmaps/generic/mackerel_sh.dmm
  _maps/templates/shuttles/overmaps/generic/salamander.dmm
  _maps/templates/shuttles/overmaps/generic/shelter_5.dmm
  _maps/templates/shuttles/overmaps/generic/shelter_6.dmm
  code/__DEFINES/directional.dm
  code/game/machinery/embedded_controller/mapping_helpers.dm
  code/modules/mapping/map_helpers/_map_helpers.dm
  code/modules/mapping/map_helpers/network_builder/_network_builder.dm
  code/modules/mapping/map_helpers/network_builder/atmos_pipe.dm
  code/modules/mapping/map_helpers/network_builder/power_cable.dm
  code/modules/mapping/spawner/_spawner.dm
  code/modules/mapping/spawner/window.dm
  code/modules/power/cable.dm
  icons/mapping/spawners/map_effects.dmi
  icons/mapping/spawners/spawners.dmi
  icons/mapping/spawners/windows.dmi
  maps/REGEXING_MAP_PORTS.md
  vorestation.dme
Labels: Sprites, Map Edit, Mechanic

#4040 PCUs and SR Connected Computers
  code/game/machinery/computer/arcade.dm
  code/game/machinery/computer/atmos_control.dm
  code/game/machinery/computer/computer.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/skills.dm
  code/game/objects/items/weapons/circuitboards/computer/computer.dm
  code/modules/modular_computers/computers/modular_computer/core.dm
  code/modules/modular_computers/computers/modular_computer/damage.dm
  code/modules/modular_computers/computers/modular_computer/hardware.dm
  code/modules/modular_computers/computers/modular_computer/interaction.dm
  code/modules/modular_computers/computers/modular_computer/power.dm
  code/modules/modular_computers/computers/modular_computer/ui.dm
  code/modules/modular_computers/computers/modular_computer/variables.dm
  code/modules/modular_computers/computers/subtypes/dev_console.dm
  code/modules/modular_computers/computers/subtypes/dev_tablet.dm
  code/modules/modular_computers/file_system/computer_file.dm
  code/modules/modular_computers/file_system/data.dm
  code/modules/modular_computers/file_system/news_article.dm
  code/modules/modular_computers/file_system/program.dm
  code/modules/modular_computers/file_system/program_events.dm
  code/modules/modular_computers/hardware/_hardware.dm
  code/modules/overmap/bluespace_rift.dm
  code/modules/overmap/bluespace_rift_vr.dm
  code/modules/overmap/disperser/disperser_console.dm
  code/modules/overmap/overmap_object.dm
  code/modules/overmap/ships/computers/computer_shims.dm
  code/modules/overmap/ships/computers/engine_control.dm
  code/modules/overmap/ships/computers/helm.dm
  code/modules/overmap/ships/computers/sensors.dm
  code/modules/overmap/ships/computers/ship.dm
  code/modules/overmap/ships/computers/ship_vr.dm
  code/modules/overmap/ships/ship.dm
  code/modules/resleeving/designer.dm
  icons/obj/computer.dmi
  icons/obj/computer_vr.dmi
  icons/obj/modular_console.dmi
  icons/obj/modular_console_vr.dmi
  icons/obj/modular_laptop.dmi
  vorestation.dme
Labels: Sprites, Code Improvement, Mechanic

#4051 fixes levelupdate not being called
  code/game/turfs/simulated/floor.dm
Labels: Priority 1: High

#4049 fixes a few things
  code/controllers/subsystem/job/spawnpoints.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/projectiles/gun.dm
  icons/obj/gun/common.dmi
Labels: Fix, Sprites

#4053 [Ready] Fixing CI and Linting shit
  README.md
  code/controllers/configuration/configuration.dm
  code/controllers/configuration/entries/dbconfig.dm
  code/controllers/configuration_old/configuration.dm
  code/controllers/subsystem/ticker.dm
  code/datums/helper_datums/getrev.dm
  code/game/magic/archived_book.dm
  code/game/world.dm
  code/modules/admin/verbs/panicbunker.dm
  code/modules/admin/view_variables/topic.dm
  code/modules/hydroponics/seed.dm
  code/modules/mob/dead/observer/observer_vr.dm
  code/modules/mob/living/simple_mob/simple_mob_vr.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/vore/eating/simple_animal_vr.dm
  code/modules/xenoarcheaology/finds/find_spawning.dm
  config/legacy/config.txt
  config/legacy/dbconfig.txt
  config/moderators.txt
  vorestation.dme
Labels: Config Update

#4052 Sec EVA Equipment, Cafe improvements, various bugfixes
  _maps/map_files/rift/rift-02-underground1.dmm
  _maps/map_files/rift/rift-03-surface1.dmm
  _maps/map_files/rift/rift-04-surface2.dmm
  _maps/map_files/rift/rift-05-surface3.dmm
Labels: Sprites, Map Edit, Mechanic

#4054 fixes tgui soft ping
  code/modules/tgui/tgui_window.dm
Labels: Fix

#4064 adds dev-atlas to ci branches
  .github/workflows/ci_suite.yml
Labels: GitHub

#4057 fixes errored space tiles, adds linter checks to forbid fuckups
  _maps/map_files/rift/rift-05-surface3.dmm
  tools/ci/check_grep.sh
Labels: Tools, Map Edit

#4058 adds invalid turf .dmm checks to linter
  tools/ci/check_grep.sh
Labels: Tools

#4060 damn, ruins the point of having a security token if everyone gets sent it on connect
  code/modules/mob/new_player/new_player.dm
Labels: Priority 1: High

#4063 stool fix
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/game/objects/structures/stool_bed_chair_nest/stools.dm
Labels: Priority 1: High, Fix

#4067 fixes stack deletion bug after being reminded of it for about a year and a half
  code/game/objects/items/stacks/stack.dm
Labels: Fix

#4073 Returns old functionality to Teleporters and cleans up their code
  code/game/machinery/teleporter/console.dm
  code/game/machinery/teleporter/old_teleporter.dm
  code/game/machinery/teleporter/pad.dm
  code/game/machinery/teleporter/projector.dm
  code/game/objects/items/devices/radio/beacon.dm
  code/game/objects/items/weapons/circuitboards/frame.dm
Labels: Fix

#4080 Clothing item added properly
  .vs/Citadel-Station-13-RP/v16/Browse.VC.db
  .vs/ProjectSettings.json
  .vs/VSWorkspaceState.json
  .vs/slnx.sqlite
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/clothing/suits/miscellaneous.dm
  icons/mob/suit.dmi
  icons/obj/clothing/suits.dmi
Labels: Sprites

#4089 Adds a handheld ⚡tazer⚡to HoP and FD
  code/game/objects/items/weapons/stunbaton.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  icons/mob/items/lefthand_melee.dmi
  icons/mob/items/righthand_melee.dmi
  icons/obj/weapons.dmi
  sound/effects/shocked_marv.ogg
Labels: Sprites, Sound, Mechanic

#4090 Update rift-03-surface1.dmm
  _maps/map_files/rift/rift-03-surface1.dmm
Labels: Map Edit

#4084 Adds toolsets for RIGs
  code/game/objects/items/weapons/tools/crowbar.dm
  code/game/objects/items/weapons/tools/screwdriver.dm
  code/game/objects/items/weapons/tools/weldingtool.dm
  code/game/objects/items/weapons/tools/wirecutters.dm
  code/game/objects/items/weapons/tools/wrench.dm
  code/modules/clothing/spacesuits/rig/modules/utility.dm
  code/modules/clothing/spacesuits/rig/suits/alien.dm
  code/modules/clothing/spacesuits/rig/suits/station.dm
  code/modules/research/rigs_vr.dm
Labels: Mechanic

#4085 Bot refresh - Light cleanup of bot code, allows the TGS bot to ping the reboot role
  code/__HELPERS/chat.dm
  code/__HELPERS/unsorted.dm
  code/controllers/configuration/entries/bot.dm
  code/controllers/subsystem/ticker.dm
  config/entries/bot.txt
  vorestation.dme
Labels: Config Update, Mechanic

#4096 Adds Moth Shoe Sprites
  icons/mob/species/moth/moth_shoes.dmi
Labels: Sprites

#4094 Corg-Clothing: Adds Utility Fur Set
  .vs/Citadel-Station-13-RP/FileContentIndex/f78bcef1-f415-488c-8401-6d80f3826726.vsidx
  code/modules/client/preference_setup/loadout/loadout_gloves.dm
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/hands.dmi
  icons/mob/suit.dmi
  icons/mob/uniform.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
Labels: Sprites

#4097 Forgot to update the changelog action...
  .github/workflows/compile_changelogs.yml
Labels: Priority 1: High, Fix, GitHub

#4101 TGUI: Citadel Theme
  tgui/packages/tgui/assets/bg-citadel.svg
  tgui/packages/tgui/index.js
  tgui/packages/tgui/styles/themes/citadel.scss
Labels: Currently Testmerged, Sprites, UI

#4100 monkey patches defibs to work again until we can refactor twohanding
  code/game/objects/items/devices/defib.dm
Labels: Currently Testmerged, Refactor

#4110 Added four songs to the Jukebox.
  config_static/jukebox.json
Labels: Config Update, Mechanic

#4111 fixes admin ai interact
  code/_onclick/other_mobs.dm
Labels: Priority 1: High

#4113 Clean some unneeded files.
  .vs/Citadel-Station-13-RP/FileContentIndex/f78bcef1-f415-488c-8401-6d80f3826726.vsidx
  .vscode/tasks.json
  citadel.dme
  tgui/packages/tgfont/dist/tgfont.css
  tgui/packages/tgfont/dist/tgfont.eot
  tgui/packages/tgfont/dist/tgfont.woff2
  tgui/public/tgui-common.bundle.js
Labels: UI

#4105 Adds Moth Clothes to the Loadout
  citadel.dme
  code/modules/client/preference_setup/loadout/loadout_xeno.dm
  code/modules/clothing/shoes/moth_boots.dm
  code/modules/clothing/under/xenos/moth.dm
  icons/mob/clothing/species/moth/moth_shoes.dmi
  icons/mob/clothing/species/moth/moth_uniforms.dmi
Labels: Sprites, Mechanic

#4115 Fixes colored carpet icons and names
  code/game/objects/items/stacks/tiles/fifty_spawner_tiles.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/modules/cargo/supplypacks/materials.dm
  icons/obj/stacks.dmi
Labels: Fix, Sprites, Mechanic

#4116 fixes tgui, but for how long?
  code/game/machinery/air_alarm.dm
  code/modules/reagents/machinery/chem_master.dm
  tgui/packages/tgui/constants.js
  tgui/packages/tgui/interfaces/Autolathe.js
  tgui/packages/tgui/interfaces/ChemDispenser.js
  tgui/packages/tgui/interfaces/ChemMaster.js
  tgui/packages/tgui/interfaces/CrewManifest.js
  tgui/packages/tgui/interfaces/DestinationTagger.js
  tgui/packages/tgui/interfaces/DestinationTagger.tsx
  tgui/packages/tgui/interfaces/ExosuitFabricator.js
  tgui/packages/tgui/interfaces/RCON.js
  tgui/packages/tgui/interfaces/Radio.js
  tgui/packages/tgui/interfaces/ResearchConsole.js
  tgui/packages/tgui/interfaces/Smes.js
  tgui/packages/tgui/interfaces/common/AtmosControls.js
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.js
Labels: UI

#4120 POV i am forced to fuck with TGUI because science coders are, just like historically, lacking in brain cells
  code/__DEFINES/tgui.dm
  code/modules/research/rdconsole_tgui.dm
  code/modules/tgui/external.dm
  code/modules/tgui/tgui.dm
  tgui/packages/tgui/backend.ts
  tgui/packages/tgui/constants.js
  tgui/packages/tgui/debug/middleware.js
  tgui/packages/tgui/interfaces/ResearchConsole.js
  tgui/packages/tgui/interfaces/common/BeakerContents.js
  tgui/packages/tgui/routes.js
  tgui/packages/tgui/store.js
  tgui/public/tgui-panel.bundle.js
  tgui/public/tgui.bundle.js
Labels: UI

#4133 Charles wedge atlas livestock
  _maps/rift.json
  citadel.dme
  code/modules/cargo/supplypacks/hydroponics.dm
  code/modules/mob/living/simple_mob/subtypes/animal/farm animals/lythios.dm
  icons/mob/animal.dmi
Labels: Sprites, Map Edit, Mechanic

#4137 Makes pews buildable
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/modules/materials/material_recipes.dm
  icons/obj/sofas.dmi
Labels: Sprites, Mechanic
