Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2022-01, with the labels that each got.

#3645 Fixes and improves Xenochimera morph abilities, makes them have 5 alt languages, additional minor tweaks
  code/modules/mob/living/carbon/human/human_powers.dm
  code/modules/mob/living/carbon/human/species/station/station_special.dm
Labels: Feature

#3641 woops accidentally made proteans unable to regen at all oh well maybe they deserve it
  code/modules/mob/living/carbon/human/species/station/protean/protean_powers.dm
Labels: Currently Testmerged

#3644 amongus
  code/modules/mob/mob_helpers.dm
Labels: Currently Testmerged, Feature, Removal

#3646 Makes the trash bin wrenchable, adds a portable secure briefcase to loadout,
  code/game/objects/items/storage/secure.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/modules/client/preference_setup/loadout/loadout_utility.dm
Labels: Currently Testmerged, Fix, Feature

#3647 adds *dwoop and *scary
  code/modules/mob/living/carbon/human/emote.dm
  sound/machines/dwoop.ogg
  sound/machines/synth_scary.ogg
Labels: Currently Testmerged, Sound

#3651 Fixes the math behind Turf thermal conductivity
  code/modules/atmospherics/datum_pipeline.dm
Labels: Fix

#3643 how many coders does it take to fix atmos bugs with windows?
  code/game/objects/structures/window.dm
Labels: Currently Testmerged

#3650 Allows for catwalk construction on lava
  code/game/turfs/simulated/lava.dm
Labels: Feature

#3652 Adds a closed curtain to the lavaland bar to save jerry
  _maps/map_levels/140x140/lavaland.dmm
Labels: Feature, Map Edit

#3654 chameleon clothing now works properly for default_worn_icon
  code/modules/clothing/chameleon.dm
Labels: Fix

#3665 Moves Xenochimera to /shapeshifter/, gives them passive regen akin to prommies, reworks commune verb, gives proteans 2 more languages
  code/_onclick/hud/screen_objects.dm
  code/game/dna/dna2.dm
  code/game/dna/dna2_helpers.dm
  code/modules/mob/living/carbon/human/human_powers.dm
  code/modules/mob/living/carbon/human/species/outsider/replicant.dm
  code/modules/mob/living/carbon/human/species/species_shapeshift.dm
  code/modules/mob/living/carbon/human/species/station/prometheans.dm
  code/modules/mob/living/carbon/human/species/station/protean/protean_species.dm
  code/modules/mob/living/carbon/human/species/station/station_special.dm
  code/modules/mob/living/carbon/human/species/station/station_special_abilities.dm
Labels: Feature

#3664 woops, i accidentally tossed out an init proc for genes
  code/game/dna/dna2.dm
  code/game/dna/dna2_domutcheck.dm
  code/game/dna/genes/disabilities.dm
  code/game/dna/genes/gene.dm
  code/game/dna/genes/monkey.dm
  code/game/dna/genes/powers.dm
  code/game/gamemodes/setupgame.dm
  code/game/world.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  tgui/public/tgui.bundle.js
Labels: Currently Testmerged, UI

#3663 fixes vv not using the correct list key checks
  code/modules/admin/view_variables/modify_variables.dm
Labels: Currently Testmerged, Priority: High

#3662 AR-B is now AR. oh and gives hud eyepatches AR too
  code/modules/clothing/glasses/hud.dm
Labels: Currently Testmerged

#3661 fixes movement keybind defaults
  code/modules/keybindings/keybind/movement.dm
Labels: Currently Testmerged

#3660 SDQL_var microoptimizations (experimental)
  code/modules/admin/verbs/SDQL2/SDQL_2.dm
Labels: Currently Testmerged, Test Merge Candidate

#3656 reverts skeleton crew head sprite to pre-2019 vorecode
  icons/mob/human_races/cyberlimbs/morpheus/morpheus_alt2.dmi
Labels: Currently Testmerged, Sprites, Revert

#3679 fixes locker welding race condition
  code/game/objects/structures/crates_lockers/closets.dm
Labels: Currently Testmerged

#3673 [WIP][Ready for testmerge] Suitstorage overhaul
  code/game/machinery/suit_storage/suit_cycler.dm
  code/game/machinery/suit_storage/suit_storage_massive.dm
  code/game/machinery/suit_storage/suit_storage_prepared.dm
  code/game/machinery/suit_storage/suit_storage_unit.dm
  code/game/objects/stumble_into_vr.dm
  icons/obj/suitstorage.dmi
  tgui/packages/tgui/interfaces/SuitStorageUnit.js
  tgui/public/tgui.bundle.js
  vorestation.dme
Labels: Currently Testmerged, Fix, Feature, Sprites, Code Improvement, UI

#3685 Revert "SDQL_var microoptimizations (experimental)"
  code/modules/admin/verbs/SDQL2/SDQL_2.dm
Labels: Priority: High, Revert

#3669 refactors infrared beams
  code/modules/assembly/infrared.dm
Labels: Refactor

#3688 Dogborg boop enabled
  code/modules/mob/living/silicon/robot/dogborg/dog_modules_vr.dm
Labels: Currently Testmerged, Feature

#3686 Mediborg NIF install
  code/modules/mob/living/silicon/robot/drone/drone_items.dm
  code/modules/surgery/implant.dm
Labels: Currently Testmerged

#3689 [Ready for Merge]Adds a hybrid dome, again......
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_face_vr.dmi
  icons/mob/human_face_vr_add.dmi
Labels: Currently Testmerged, Sprites

#3691 Adds Nebula Gas types without most effects
  code/game/machinery/atmoalter/canister.dm
  code/modules/atmospherics/gasmixtures/gas_types.dm
Labels: Feature

#3692 Dogborg, tell me the weather.
  code/modules/mob/living/silicon/robot/emote.dm
Labels: Feature

#3697 Neomorphs back to xenomorph hybrid
  code/__DEFINES/mobs.dm
  code/modules/mob/living/carbon/human/species/station/station.dm
Labels: Currently Testmerged, Fix, Config Update, Administration

#3696 welding a shard while holding it no longer embeds a pane of glass in your body
  code/game/objects/items/weapons/material/shards.dm
Labels: Currently Testmerged

#3698 Triumph Fixes, R-CON Improvements, Other Stuff
  _maps/map_files/triumph/triumph-01-deck1.dmm
  _maps/map_files/triumph/triumph-02-deck2.dmm
  _maps/map_files/triumph/triumph-03-deck3.dmm
  _maps/map_files/triumph/triumph-04-deck4.dmm
Labels: Fix, Feature, Map Edit

#3701 Minor Species Age Alterations
  code/modules/mob/living/carbon/human/species/outsider/event.dm
  code/modules/mob/living/carbon/human/species/outsider/replicant.dm
  code/modules/mob/living/carbon/human/species/outsider/skeleton.dm
  code/modules/mob/living/carbon/human/species/station/teshari.dm
Labels: Currently Testmerged

#3700 Fixes Gendered Icon Enforcement - Female Gendered Characters Now Have Female Bodies
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/new_player/sprite_accessories.dm
  icons/mob/human_races/markings.dmi
Labels: Currently Testmerged, Fix, Sprites
