Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2022-09, with the labels that each got.

#4386 Hopefully fixes simple mobs dropping organs
  code/modules/mob/living/butchering.dm
  code/modules/mob/living/organs.dm
  code/modules/mob/living/simple_mob/simple_mob.dm
Labels: Currently Testmerged

#4390 Removes AR-V Goggles From Pathfinder Locker and Survey Vendor
  code/game/objects/structures/crates_lockers/closets/secure/explorer.dm
  code/modules/mining/ore_redemption_machine/survey_vendor.dm
Labels: Removal

#4369 adds visibility toggle/blacklist/whitelist to soulcatchers
  code/modules/mob/dead/observer/observer_vr.dm
  code/modules/nifsoft/software/13_soulcatcher.dm
Labels: Currently Testmerged, Tweak

#4394 Integrated circuit fixes
  code/game/objects/stumble_into_vr.dm
  code/modules/integrated_electronics/core/assemblies.dm
  code/modules/integrated_electronics/core/assemblies/clothing.dm
  code/modules/integrated_electronics/core/tools.dm
  icons/obj/integrated_electronics/electronic_setups.dmi
Labels: Fix, Sprites, Removal

#4398 Salvation for Engineering
  _maps/map_files/rift/rift-06-surface3.dmm
Labels: Fix, Tweak, Map Edit

#4406 Removes Unsimulated Turf from Engineering
  _maps/map_files/rift/rift-03-underground1.dmm
Labels: Fix, Removal, Map Edit

#4408 Muskets by Ruskit
  citadel.dme
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/game/objects/items/storage/lockbox.dm
  code/modules/projectiles/ammunition/rounds.dm
  code/modules/projectiles/guns/projectile/musket.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/reagents/Chemistry-Reagents/Chemistry-Reagents-Other.dm
  code/modules/reagents/Misc-Recipes.dm
  icons/mob/items/lefthand_guns.dmi
  icons/mob/items/righthand_guns.dmi
  icons/obj/ammo.dmi
  icons/obj/gun/ballistic.dmi
  sound/weapons/gunshot/musket.ogg
Labels: Sprites, Sound, Tweak, Mechanic

#4405 ssoverlays
  citadel.dme
  code/__DEFINES/_planes+layers.dm
  code/__DEFINES/controllers/_subsystems.dm
  code/__DEFINES/controllers/overlays.dm
  code/__DEFINES/icon_smoothing.dm
  code/__DEFINES/rendering/atom_huds.dm
  code/_rendering/atom_huds/alternate_appearance.dm
  code/controllers/subsystem/openspace.dm
  code/controllers/subsystem/overlays.dm
  code/datums/datacore.dm
  code/game/atoms.dm
  code/game/objects/explosion_recursive.dm
  code/game/objects/items.dm
  code/game/objects/items/spritechanger.dm
  code/game/turfs/simulated.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/floor_icon.dm
  code/game/turfs/simulated/floors/outdoors.dm
  code/game/turfs/simulated/floors/snow.dm
  code/game/turfs/simulated/wall.dm
  code/game/world.dm
  code/global.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mob/inventory/rendering.dm
  code/modules/mob/living/simple_mob/subtypes/blob/spore.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/typing_indicator.dm
  code/modules/multiz/turf.dm
  code/modules/species/station/adherent.dm
  icons/testing/greyscale_error.dmi
Labels: Sprites

#4268 Adds the Ashlander Ghost Role
  _maps/submaps/level_specific/lavaland/ashlandercamp.dmm
  citadel.dme
  code/__DEFINES/species/species.dm
  code/datums/outfits/nanotrasen.dm
  code/game/antagonist/outsider/deathsquad.dm
  code/game/area/Off Station Areas.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/misc.dm
  code/game/objects/items/weapons/material/foam.dm
  code/game/objects/items/weapons/material/misc.dm
  code/game/objects/items/weapons/material/twohanded.dm
  code/game/objects/items/weapons/swords_axes_etc.dm
  code/global.dm
  code/modules/awaymissions/corpse.dm
  code/modules/catalogue/catalogue_data.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/suits/labcoat.dm
  code/modules/clothing/under/jobs/centcom.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/ghostroles/instantiator.dm
  code/modules/ghostroles/role.dm
  code/modules/ghostroles/roles/ash_lizard.dm
  code/modules/ghostroles/roles/ashlander.dm
  code/modules/ghostroles/roles/hermit.dm
  code/modules/ghostroles/spawnpoint.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/hydroponics/seed_packets.dm
  code/modules/hydroponics/trays/tray_tools.dm
  code/modules/maps/triumph/submaps/lavaland.dm
  code/modules/mining/kinetic_crusher.dm
  code/modules/mining/mine_items.dm
  code/modules/species/outsider/scori.dm
  icons/mob/lavaland/lavaland_mobs.dmi
  icons/obj/items.dmi
  icons/obj/storage.dmi
  icons/obj/tools.dmi
  maps/nsv_triumph/submaps/lavaland/_lavaland.dm
  maps/rift/submaps/lavaland/_lavaland.dm
  strings/cas_black.txt
Labels: Fix, Sprites, Map Edit, Mechanic

#4418 Fixes snake tails
  icons/mob/sprite_accessories/tails.dmi
Labels: Sprites

#4416 fixes ai examine
  code/modules/vore/eating/silicon_vr.dm
Labels: Priority 0: CRITICAL

#4413 Fixes a Typo In Handcuffs
  code/game/objects/items/weapons/handcuffs.dm
Labels: Fix

#4399 Chlorine Cosmetics, Courser Corrections, and Creepy Coronas
  citadel.dme
  code/datums/components/horror_aura.dm
  code/game/machinery/vending.dm
  code/modules/atmospherics/gasmixtures/gas_types.dm
  code/modules/mob/living/simple_mob/subtypes/horror/horror .dm
  code/modules/mob/living/simple_mob/subtypes/occult/constructs/_construct.dm
  code/modules/mob/living/simple_mob/subtypes/occult/creature.dm
  code/modules/mob/living/simple_mob/subtypes/occult/faithless.dm
  icons/effects/atmospherics.dmi
  maps/rift/rift_shuttles.dm
Labels: Sprites, Mechanic

#4414 Allows people with synthetic voiceboxes to use synthetic emotes
  code/modules/mob/living/carbon/human/emote.dm
Labels: Tweak

#4419 Adds die Konigin-63 Compact
  code/game/antagonist/station/renegade.dm
  code/game/objects/random/guns_and_ammo.dm
  code/game/objects/random/misc.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  icons/obj/gun/ballistic.dmi
Labels: Sprites, Mechanic

#4393 Adds an Experimental Virology Facility
  _maps/map_files/rift/rift-04-surface1.dmm
  code/game/area/Space Station 13 areas.dm
  code/game/objects/structures/transit_tubes.dm
  code/modules/atmospherics/machinery/pipes/tank.dm
  icons/atmos/tank_vr.dmi
Labels: Sprites, Map Edit, Mechanic

#4422 Fixes Underground Weather, adds mining outpost, tweaks that weird mining elevator on station, touches ALL the rocks
  _maps/map_files/rift/rift-01-underground3.dmm
  _maps/map_files/rift/rift-02-underground2.dmm
  _maps/map_files/rift/rift-03-underground1.dmm
  _maps/map_files/rift/rift-04-surface1.dmm
  _maps/map_files/rift/rift-05-surface2.dmm
  _maps/map_files/rift/rift-06-surface3.dmm
  _maps/map_files/rift/rift-07-west_base.dmm
  _maps/map_files/rift/rift-08-west_deep.dmm
  _maps/map_files/rift/rift-09-west_caves.dmm
  _maps/map_files/rift/rift-10-west_plains.dmm
  _maps/submaps/lythios_rift/caves/west_caves_cavern1.dmm
  _maps/submaps/lythios_rift/caves/west_caves_cavern2.dmm
  _maps/submaps/lythios_rift/caves/west_caves_cavern3.dmm
  _maps/submaps/lythios_rift/caves/west_caves_cavern4.dmm
  _maps/submaps/lythios_rift/caves/west_caves_rock1.dmm
  _maps/submaps/lythios_rift/caves/west_caves_small_crystal___.dmm
  _maps/submaps/lythios_rift/caves/west_caves_survival_cave__.dmm
  _maps/submaps/lythios_rift/geothermal_vent.dmm
  _maps/submaps/lythios_rift/map_makers_pallet.dmm
  citadel.dme
  code/modules/maps/generic/submaps/lythios_rift/lyhtios.dm
  code/modules/maps/generic/submaps/lythios_rift/lythios_areas.dm
  code/modules/maps/rift/levels/_lythios43c.dm
  code/modules/mining/mine_turfs.dm
  code/modules/multiz/ladder.dm
  code/modules/random_map/automata/map_specific/rift_automata.dm
  maps/rift/rift_areas.dm
  maps/rift/rift_areas2.dm
  maps/rift/rift_defines.dm
  maps/rift/rift_turfs.dm
Labels: Fix, Tweak, Code Improvement, Map Edit, Mechanic

#3781 [TEST ONLY PLEASE]Floating Messages 2, the sequel.
  citadel.dme
  code/__HELPERS/animations.dm
  code/__HELPERS/game.dm
  code/_macros.dm
  code/game/atoms.dm
  code/game/objects/items/devices/text_to_speech.dm
  code/modules/client/preference_setup/global/setting_datums.dm
  code/modules/client/preferences_toggle_procs.dm
  code/modules/mob/emote.dm
  code/modules/mob/floating_message.dm
  code/modules/mob/hear_say.dm
  code/modules/mob/living/say.dm
  code/modules/mob/mob_helpers.dm
  code/modules/mob/say.dm
  interface/skin.dmf
  interface/stylesheet.dm
Labels: Currently Testmerged, Mechanic

#4430 Removes Cult Mobs from Surt
  _maps/map_levels/192x192/lavaland.dmm
Labels: Removal, Map Edit

#4433 Tyrmalin Heavy Charges Now Have to be Crafted
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
  code/modules/cargo/supplypacks/supply.dm
Labels: Balance/Rebalance

#4434 funny brains in cans!!!
  code/game/machinery/vending.dm
  code/game/objects/items/trash.dm
  code/modules/food/food/snacks.dm
  icons/obj/food.dmi
  icons/obj/trash.dmi
Labels: Sprites, Mechanic

#4445 [s] hardsuit fix
  code/__HELPERS/do_after.dm
  code/modules/rigsuits/_rig.dm
  nano/templates/hardsuit.tmpl
Labels: Priority 1: High

#4432 Adds an Open Space Pitfall Trap
  code/game/objects/effects/traps.dm
Labels: Mechanic

#4443 Fixes Bone Plantcutter Icon Issue
  _maps/submaps/level_specific/lavaland/ashlandercamp.dmm
  code/modules/hydroponics/trays/tray_tools.dm
Labels: Fix, Map Edit

#4446 fixes some issues
  code/game/machinery/pipe/construction.dm
  code/game/objects/items/devices/multitool.dm
Labels: Priority 1: High

#4427 On the Edge
  code/datums/components/cyberpsychosis.dm
  code/game/objects/items/storage/belt.dm
  code/modules/client/preference_setup/loadout/loadout_donator.dm
  code/modules/client/preference_setup/loadout/loadout_shoes.dm
  code/modules/client/preference_setup/loadout/loadout_suit.dm
  code/modules/client/preference_setup/loadout/loadout_uniform.dm
  code/modules/clothing/head/hood.dm
  code/modules/clothing/shoes/boots.dm
  code/modules/clothing/suits/hooded.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/mob/living/carbon/human/traits/neutral.dm
  code/modules/organs/internal/augment.dm
  code/modules/organs/internal/augment/bio.dm
  code/modules/projectiles/ammunition/rounds.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/guns/projectile/shotgun.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/projectiles/projectile/scatter.dm
  code/modules/species/species.dm
  icons/mob/clothing/feet.dmi
  icons/mob/clothing/head.dmi
  icons/mob/clothing/suits.dmi
  icons/mob/clothing/uniform.dmi
  icons/mob/items/lefthand_guns.dmi
  icons/mob/items/righthand_guns.dmi
  icons/obj/ammo.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/gun/ballistic.dmi
Labels: Sprites, Mechanic

#4447 Reduces Cost of Tyrmalin Heavy Charge Crafting
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
Labels: Tweak

#4448 The Final Skyfall Fix - Big Thanks to Kevin and Free!!!
  code/game/turfs/unsimulated/sky_vr.dm
Labels: Fix

#4449 Mining unloading speedup
  code/modules/mining/machine_processing.dm
  code/modules/mining/machine_unloading.dm
  code/modules/recycling/conveyor2.dm
Labels: Tweak

#4453 a thousand curses upon the coders of eld
  code/modules/xenoarcheaology/finds/special.dm
Labels: Priority 0: CRITICAL

#4456 Fixes Chainsaw Activation Proc
  code/game/objects/items/weapons/material/chainsaw.dm
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
Labels: Fix, Sprites

#4455 Raises the Tyrmalin Mining Crate Cost
  code/modules/cargo/supplypacks/supply.dm
Labels: Tweak

#4454 Adjusts Horror Aura Subtyping
  code/modules/mob/living/simple_mob/subtypes/horror/Eddy.dm
  code/modules/mob/living/simple_mob/subtypes/horror/Master.dm
  code/modules/mob/living/simple_mob/subtypes/horror/Rickey.dm
  code/modules/mob/living/simple_mob/subtypes/horror/Smiley.dm
  code/modules/mob/living/simple_mob/subtypes/horror/Steve.dm
  code/modules/mob/living/simple_mob/subtypes/horror/Willy.dm
  code/modules/mob/living/simple_mob/subtypes/horror/bradley.dm
  code/modules/mob/living/simple_mob/subtypes/horror/horror .dm
  code/modules/mob/living/simple_mob/subtypes/horror/sally.dm
  code/modules/mob/living/simple_mob/subtypes/horror/shittytim.dm
  code/modules/mob/living/simple_mob/subtypes/horror/timling.dm
  code/modules/mob/living/simple_mob/subtypes/occult/constructs/_construct.dm
  code/modules/mob/living/simple_mob/subtypes/occult/constructs/artificer.dm
  code/modules/mob/living/simple_mob/subtypes/occult/constructs/harvester.dm
  code/modules/mob/living/simple_mob/subtypes/occult/constructs/juggernaut.dm
  code/modules/mob/living/simple_mob/subtypes/occult/constructs/proteon.dm
  code/modules/mob/living/simple_mob/subtypes/occult/constructs/shade.dm
  code/modules/mob/living/simple_mob/subtypes/occult/constructs/wraith.dm
Labels: Mechanic

#4452 Lower Mining Access fix and airlock fix
  _maps/map_files/rift/rift-01-underground3.dmm
  _maps/map_files/rift/rift-02-underground2.dmm
  code/game/area/Space Station 13 areas.dm
  code/game/machinery/doors/phoronlocks.dm
  maps/rift/rift_areas.dm
Labels: Fix, Map Edit

#4458 Adds elevator, belter shuttle, and more to west side
  _maps/map_files/rift/rift-07-west_base.dmm
  _maps/map_files/rift/rift-08-west_deep.dmm
  _maps/map_files/rift/rift-09-west_caves.dmm
  _maps/map_files/rift/rift-10-west_plains.dmm
  maps/Generic/turbolifts.dm
  maps/rift/rift_areas.dm
  maps/rift/rift_defines.dm
  maps/rift/rift_shuttle_defs.dm
  maps/rift/submaps/_rift_submaps.dm
Labels: Map Edit

#4465 Fixes Pariah "Hood" and Missing Duffel of Holding Mob Sprite
  code/modules/clothing/head/hood.dm
  icons/mob/clothing/back.dmi
  icons/mob/clothing/head.dmi
  icons/obj/clothing/hats.dmi
Labels: Sprites, Mechanic
