Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2023-05, with the labels that each got.

#5457 protean blob fixes
  code/modules/species/protean/protean_blob.dm
Labels: Priority 1: High, size/XS

#5454 fixes ssd indicator visuals appearing below mobs that are laying down/appearing on death
  code/__HELPERS/matrices/transform_matrix.dm
  code/modules/mob/death.dm
  code/modules/mob/ssd.dm
Labels: size/S

#5466 fixes firemanning
  code/modules/mob/living/mobility.dm
Labels: size/XS

#5464 fixes compliance disks *vomit
  code/modules/nifsoft/nifsoft.dm
Labels: size/XS

#5463 removes chamo projector from cargo
  code/modules/cargo/supplypacks/contraband.dm
Labels: size/XS

#5462 fixes collectors
  code/modules/power/singularity/collector.dm
Labels: size/XS

#5472 Gives Security Cadets a job description
  code/modules/jobs/job_types/station/security/security_officer.dm
Labels: size/XS

#5459 Adds Auril cultures and abilities, tweaks flight and toggle agility
  citadel.dme
  code/__DEFINES/species/category.dm
  code/__DEFINES/species/species.dm
  code/datums/ability.dm
  code/modules/lore_hardcoded/_hardcoded.dm
  code/modules/lore_hardcoded/species/auril.dm
  code/modules/mob/living/carbon/human/traits/positive.dm
  code/modules/multiz/movement.dm
  code/modules/species/abilites.dm
  code/modules/species/outsider/celestials.dm
  code/modules/species/protean/protean.dm
  code/modules/species/species.dm
  code/modules/species/station/apidaen.dm
  code/modules/species/station/rapala.dm
  code/modules/species/station/standard/harpy.dm
  code/modules/species/station/standard/moth.dm
  code/modules/species/station/standard/nevrean.dm
  code/modules/species/station/standard/teshari.dm
  code/modules/species/station/station_special_abilities.dm
  code/modules/species/station/xenochimera.dm
  code/modules/species/station/xenomorph_hybrids/xeno_hybrids.dm
  icons/screen/actions/actions.dmi
Labels: size/L

#5452 Changes to Ashlander Forge
  code/game/objects/items/stacks/sheets/leather.dm
  code/game/objects/structures/ashlander.dm
  maps/map_levels/192x192/lavaland_east.dmm
Labels: size/L

#5460 Blueshield QOL
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/nifsoft/nifsoft.dm
  code/modules/preferences/preference_setup/loadout/loadout_ears.dm
  code/modules/preferences/preference_setup/loadout/loadout_role_restricted.dm
Labels: size/S

#5476 Beneath the Mask on the jukebox
  config_static/jukebox.json
Labels: size/XS

#5475 makes mobs red in sonar
  code/__HELPERS/misc/sonar.dm
Labels: size/XS

#5477 fixes regeneration caring about being upright
  code/modules/mob/living/carbon/human/human_powers.dm
Labels: size/XS

#5479 stops drinks saying they need to be opened if target is not something that can be poured into
  code/modules/food/food/drinks.dm
Labels: size/XS

#5461 fixes knockout traits not working
  code/modules/mob/living/health.dm
Labels: size/XS

#5473 Removal of Cult RNG Attack
  code/modules/events/event_container_vr.dm
Labels: size/XS

#5474 Updates chemical dispenser crates
  code/modules/reagents/machinery/dispenser/supply.dm
Labels: size/XS

#5481 fixes runtime spam
  code/modules/mob/status_procs.dm
Labels: size/XS

#5480 minor mapping issues in sec
  code/game/area/rift_areas.dm
  maps/map_files/rift/rift-05-surface2.dmm
Labels: size/M

#5471 fixes proteans getting a buff from the armor update
  code/modules/rigsuits/suits/species/protean.dm
Labels: size/XS

#5485 The New Player Panel automatically updates when the round starts
  code/controllers/subsystem/ticker.dm
Labels: size/M

#5484 Improves tail layering support and adds my tail. and only my tail.
  code/modules/sprite_accessories/tail/species/teshari.dm
  code/modules/vore/appearance/update_icons_vr.dm
  icons/mob/sprite_accessories/tails.dmi
Labels: size/XS

#5486 Pinnace costs less plasteel
  code/modules/research/mechfab_designs.dm
Labels: size/S

#5488 Adding two new digi unathi tails
  code/modules/sprite_accessories/tail/scalies.dm
  icons/mob/sprite_accessories/tails.dmi
Labels: size/S

#5490 readds prescription glasses
  code/modules/preferences/preference_setup/loadout/loadout_eyes.dm
Labels: size/XS

#5401 Nerfs upgraded borg speed
  code/game/objects/items/robot/robot_upgrades.dm
Labels: size/XS

#5467 Finally fixes Naramadi language
  code/modules/language/languages/species/naramadi.dm
Labels: size/XS

#5494 speeds up sonar for the client
  code/__HELPERS/datastructs/armor.dm
  code/__HELPERS/misc/sonar.dm
  code/modules/automata/__automata.dm
  code/modules/automata/sonar.dm
  code/modules/client/client_procs.dm
Labels: size/L

#5497 Custom Tajaran tails are now animated
  code/modules/sprite_accessories/tail/species/tajaran.dm
  icons/effects/species_tails_vr.dmi
Labels: size/S

#5499 Armor Rebalance/fix
  code/datums/armor/clothing/armor.dm
  code/datums/armor/clothing/uniform.dm
  code/datums/armor/outsider/merc.dm
  code/datums/armor/station/armor.dm
  code/datums/armor/station/security.dm
  code/game/objects/items/gunbox.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/cargo/supplypacks/security.dm
  code/modules/clothing/gloves/arm_guards.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/hood.dm
  code/modules/clothing/shoes/boots.dm
  code/modules/clothing/shoes/leg_guards.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/spacesuits/void/station.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/hooded.dm
  code/modules/clothing/suits/jobs.dm
  code/modules/clothing/under/accessories/armor.dm
  code/modules/clothing/under/jobs/security.dm
  code/modules/clothing/under/nanotrasen_vr.dm
  code/modules/clothing/under/oricon/_oricon.dm
  code/modules/clothing/under/oricon/crew.dm
  code/modules/clothing/under/shorts.dm
  code/modules/maps/overmap/space/talon/talon.dm
  code/modules/mob/living/simple_mob/subtypes/humanoid/pirates.dm
  code/modules/paperwork/paper/paper.dm
  code/modules/random_map/drop/drop_types.dm
  code/modules/vore/fluffstuff/custom_clothes.dm
  icons/mob/clothing/modular_armor.dmi
  icons/obj/clothing/modular_armor.dmi
  icons/turf/flooring/decals.dmi
  maps/map_files/rift/rift-05-surface2.dmm
  maps/map_files/tether/tether-02-surface2.dmm
  maps/map_files/triumph/triumph-04-deck4.dmm
  maps/map_files/triumph/triumph-05-flagship.dmm
  maps/templates/admin/dhael_centcom.dmm
  maps/templates/admin/mercbase.dmm
  maps/templates/shuttles/overmaps/generic/cruiser.dmm
  maps/templates/shuttles/overmaps/generic/mercenarybase.dmm
  maps/templates/shuttles/overmaps/generic/shelter_6.dmm
  maps/templates/shuttles/overmaps/generic/vespa.dmm
Labels: size/XXL

#5498 Socks, Shorts, and a Crown
  code/datums/underwear/bottom.dm
  code/datums/underwear/socks.dm
  code/datums/underwear/top.dm
  code/datums/underwear/undershirts.dm
  code/modules/clothing/accessories/halo.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/accessories/accessory.dm
  code/modules/clothing/under/accessories/clothing.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/preferences/preference_setup/loadout/loadout_accessories.dm
  code/modules/preferences/preference_setup/loadout/loadout_suit.dm
  code/modules/preferences/preference_setup/loadout/loadout_uniform.dm
  icons/clothing/accessories/halo_projector.dmi
  icons/mob/clothing/suits.dmi
  icons/mob/clothing/ties.dmi
  icons/mob/clothing/uniform.dmi
  icons/mob/human.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
Labels: size/L

#5489 Bridge teleporter fix, and more beacons.
  code/modules/xenoarcheaology/misc.dm
  maps/map_files/rift/rift-04-surface1.dmm
  maps/map_files/rift/rift-05-surface2.dmm
  maps/map_files/rift/rift-06-surface3.dmm
  maps/map_files/rift/rift-08-west_deep.dmm
Labels: size/M

#5487 killhouse templates
  code/game/area/Off Station Areas.dm
  code/modules/maps/templates/badmin_misc/fun.dm
  code/modules/maps/templates/badmin_misc/templates.dm
  code/modules/maps/turf_makers/planet_station_turfs/_lythios43c.dm
  maps/templates/admin/killhouse1.dmm
  maps/templates/admin/killhouse2.dmm
  maps/templates/admin/killhouseteleporter.dmm
Labels: size/XXL

#5502 Shifts Expeditionary Guns & Names Around
  code/game/objects/structures/crates_lockers/closets/secure/guncabinet.dm
  code/modules/vore/fluffstuff/custom_guns.dm
Labels: size/XS

#5506 Detective PTO
  code/modules/jobs/job_types/station/security/detective.dm
Labels: size/XS

#4678 [Ready to Merge] [MDB IGNORE] [DNM] NLV Euthenia
  citadel.dme
  code/game/area/Ship_Station_Areas.dm
  code/game/area/Space Station 13 areas.dm
  code/game/machinery/doorbell_vr.dm
  code/game/machinery/telecomms/presets.dm
  code/game/objects/structures/window.dm
  code/modules/atmospherics/machinery/components/unary/wall_mounted_pump.dm
  code/modules/mapping/spawner/window.dm
  code/modules/maps/generic/shuttles/station_shuttles/transport.dm
  code/modules/power/apc.dm
  maps/map_files/NSV_Euthenia/Euthenia_Deck_1.dmm
  maps/map_files/NSV_Euthenia/Euthenia_Deck_2.dmm
  maps/map_files/NSV_Euthenia/Euthenia_Deck_3.dmm
  maps/map_files/NSV_Euthenia/Euthenia_Deck_4.dmm
  maps/map_files/NSV_Euthenia/Euthenia_Flight_Deck.dmm
  maps/map_files/NSV_Euthenia/Euthenia_Misc.dmm
  maps/map_files/NSV_Euthenia/lazy_overmap.dmm
  maps/map_files/NSV_Euthenia/multizship.dmm
  maps/nsv_euthenia/euthenia.dm
  maps/nsv_euthenia/euthenia_defines.dm
Labels: size/XXL, Stale Exempt

#5505 fixes a warning about unused variable
  code/modules/mining/mine_turfs.dm
Labels: size/XS

#5500 fixes worn style for stuff with multiple overlays on render
  code/modules/clothing/clothing.dm
Labels: size/XS

#5501 Explo Vendor Adjustments/Organization
  code/modules/mining/ore_redemption_machine/survey_vendor.dm
Labels: size/M

#5504 reworks staggering effects
  citadel.dme
  code/__DEFINES/traits/sources.dm
  code/datums/status_effects/basic/staggered.dm
  code/datums/status_effects/grouped.dm
  code/datums/status_effects/grouped/staggered.dm
  code/game/objects/items/devices/flash.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/status_procs.dm
Labels: size/L

#5492 Forgot a wire on the coursar ship Fix
  maps/map_files/rift/rift-06-surface3.dmm
Labels: size/S

#5518 Blueshield beret loadout option
  code/modules/preferences/preference_setup/loadout/loadout_head.dm
Labels: size/XS

#5512 Security Armor Vests
  code/game/objects/items/gunbox.dm
  maps/map_files/rift/rift-05-surface2.dmm
Labels: size/M

#5508 fixes labcoats
  code/modules/clothing/suits/labcoat.dm
  icons/clothing/suit/coats/labcoats.dmi
  icons/obj/clothing/suits.dmi
Labels: size/XS

#5495 abilitiese Sonar pulse
  code/modules/mob/living/carbon/human/human_powers.dm
  code/modules/species/abilites.dm
  code/modules/species/protean/protean.dm
  code/modules/species/station/standard/teshari.dm
  code/modules/species/station/xenochimera.dm
  code/modules/species/station/xenomorph_hybrids/xeno_hybrids.dm
Labels: size/M

#5514 buffs bioadaptive NIF durability, adds veymed variant of bioadaptive NIF
  code/__DEFINES/items/nifs.dm
  code/modules/admin/verbs/debug.dm
  code/modules/nifsoft/nif.dm
Labels: size/M

#5513 Fixes ushanka and beanie cold protection
  code/modules/clothing/head/misc.dm
  code/modules/clothing/head/misc_special.dm
Labels: size/XS

#5516 Changes SMES Units to use more modern icons
  code/modules/power/smes/smes.dm
Labels: size/S

#5522 Ports wagging sharktails from Main
  code/modules/sprite_accessories/tail/species/akula.dm
  icons/effects/species_tails_vr.dmi
Labels: size/XS

#5526 Fixes Heph robotics not being able to go off-duty
  code/modules/lore_hardcoded/faction.dm
Labels: size/XS

#5511 Finally, Spicy Cheese
  code/__DEFINES/chemistry.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/species/station/standard/naramadi.dm
Labels: size/XS

#5529 Alraune can now grow grass
  code/global.dm
Labels: good first pr, size/XS

#5503 Preference Defaults and Keybinding support/defaults
  code/modules/keybindings/keybind/living.dm
  code/modules/keybindings/keybind/mob.dm
  code/modules/keybindings/keybind/movement.dm
  code/modules/preferences/_preferences.dm
Labels: size/S

#5510 Dropping magazines
  code/modules/projectiles/guns/ballistic.dm
Labels: size/XS

#5521 Tajaran Wears (LOTS OF STUFF) (Lore maintainer review needed!)
  citadel.dme
  code/game/objects/items/weapons/cigs_lighters.dm
  code/modules/awaymissions/corpse.dm
  code/modules/cargo/supplypacks/costumes.dm
  code/modules/clothing/gloves/xeno/tajara.dm
  code/modules/clothing/head/xeno/tajara.dm
  code/modules/clothing/shoes/xeno/tajara.dm
  code/modules/clothing/spacesuits/void/xeno/tajara.dm
  code/modules/clothing/suits/aliens/tajara.dm
  code/modules/clothing/under/accessories/xeno/tajara.dm
  code/modules/clothing/under/xenos/tajaran.dm
  code/modules/preferences/preference_setup/loadout/loadout_accessories.dm
  code/modules/preferences/preference_setup/loadout/loadout_head.dm
  code/modules/preferences/preference_setup/loadout/loadout_suit.dm
  code/modules/preferences/preference_setup/loadout/loadout_uniform.dm
  code/modules/preferences/preference_setup/loadout/loadout_xeno.dm
  icons/mob/clothing/species/tajaran/coats.dmi
  icons/mob/clothing/species/tajaran/gloves.dmi
  icons/mob/clothing/species/tajaran/helmet.dmi
  icons/mob/clothing/species/tajaran/shoes.dmi
  icons/mob/clothing/species/tajaran/suits.dmi
  icons/mob/clothing/species/tajaran/ties.dmi
  icons/mob/clothing/species/tajaran/uniform.dmi
  icons/mob/sprite_accessories/markings/taj.dmi
  icons/obj/clothing/species/tajaran/coats.dmi
  icons/obj/clothing/species/tajaran/hats.dmi
  icons/obj/clothing/species/tajaran/suits.dmi
  icons/obj/clothing/species/tajaran/ties.dmi
  maps/map_files/rift/rift-03-underground1.dmm
  maps/map_files/rift/rift-06-surface3.dmm
  maps/map_files/rift/rift-07-west_base.dmm
  maps/submaps/lythios_rift/caves/west_caves_buriedstructure_1.dmm
Labels: size/XXL

#5523 Insignia Accessory Selection
  code/modules/clothing/under/accessories/oricon.dm
  code/modules/clothing/under/accessories/torch.dm
  code/modules/preferences/preference_setup/loadout/loadout_accessories.dm
Labels: size/L

#5535 HOS office touchups
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  maps/map_files/rift/rift-05-surface2.dmm
Labels: size/L

#5530 Remove Teshari xeno wear restriction
  code/modules/preferences/preference_setup/loadout/loadout_xeno.dm
Labels: size/XS

#5531 Armor gunbox touchups
  code/game/objects/items/gunbox.dm
  code/modules/clothing/suits/hooded.dm
  code/modules/clothing/under/accessories/holster.dm
Labels: size/S

#5534 Euthenia_Deck_1 minor change
  maps/map_files/NSV_Euthenia/Euthenia_Deck_1.dmm
Labels: size/XL

#5517 [Salt PR?] Shut the FUCK up about milk nourishment.
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Dispenser.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Other.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Toxins.dm
Labels: size/S

#5525 Character Profiles
  citadel.dme
  code/datums/character_profile.dm
  code/game/verbs/character_profile_verbs.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/admin_set_headshot.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/living_defines.dm
  code/modules/preferences/_preferences.dm
  code/modules/preferences/preference_setup/general/01_basic.dm
  icons/404_profile_not_found.dmi
  tgui/packages/tgui/assets/headshot_not_found.png
  tgui/packages/tgui/interfaces/CharacterProfile.tsx
Labels: size/L

#5536 adminheal/revive changes
  citadel.dme
  code/_globals/lists/mobs.dm
  code/_globals/mobs.dm
  code/controllers/configuration_old/configuration.dm
  code/datums/soul_link.dm
  code/game/gamemodes/changeling/powers/rapid_regen.dm
  code/game/gamemodes/changeling/powers/revive.dm
  code/game/gamemodes/cult/runes.dm
  code/game/objects/items/devices/defib.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/randomverbs.dm
  code/modules/mob/freelook/ai/update_triggers.dm
  code/modules/mob/freelook/mask/update_triggers.dm
  code/modules/mob/health.dm
  code/modules/mob/inventory.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/carbon/health.dm
  code/modules/mob/living/carbon/human/health.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/health.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/ai/death.dm
  code/modules/mob/living/silicon/ai/health.dm
  code/modules/mob/living/silicon/ai/life.dm
  code/modules/mob/living/simple_mob/subtypes/animal/borer/borer_powers.dm
  code/modules/mob/living/simple_mob/subtypes/slime/slime.dm
  code/modules/mob/mob.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/mob/status_procs.dm
  code/modules/organs/internal/subtypes/brain.dm
  code/modules/projectiles/unsorted/magic.dm
  code/modules/species/station/xenochimera.dm
  code/modules/spells/artifacts.dm
  code/modules/spells/targeted/chimera_spells.dm
Labels: size/XL

#5545 Fixes the chem dispenser in medical taking drinks subtype containers
  code/modules/reagents/machinery/dispenser/dispenser.dm
Labels: size/XS
