Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2023-11, with the labels that each got.

#6104 Adds 40k Themed Weapons and Costume Armor
  code/datums/armor/clothing/armor.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/shoes/boots.dm
  code/modules/clothing/suits/armor.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  code/modules/projectiles/magazines/unsorted.dm
  icons/clothing/suit/armor/baroque.dmi
  icons/mob/items/lefthand_guns.dmi
  icons/mob/items/righthand_guns.dmi
  icons/obj/ammo.dmi
  icons/obj/gun/ballistic.dmi
  sound/weapons/gunshot/gunshot_bolter.ogg
Labels: size/L

#6105 Makes the Bone Knife Craftable
  code/datums/recipe/crafting_recipes/recipes_primal.dm
Labels: size/XS

#6112 Adds Cage Hat for Costumes
  code/modules/clothing/head/misc_special.dm
  icons/clothing/head/cage_32x48.dmi
  icons/obj/clothing/hats.dmi
Labels: size/S

#6115 Makes the Tcomms SMES start with input on
  code/modules/power/smes/smes.dm
Labels: size/XS

#6116 Fixes fluency error in atom_say() proc
  code/game/atoms/say.dm
Labels: size/XS

#6117 Adds a new Antediluvian outfit, a new hairstyle and a new body marking (alternate body toning)
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/under/accessories/clothing.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/loadout/loadout_accessories.dm
  code/modules/loadout/loadout_gloves.dm
  code/modules/loadout/loadout_uniform.dm
  code/modules/sprite_accessories/hair/_hair.dm
  code/modules/sprite_accessories/markings/_markings.dm
  icons/clothing/gloves/ante_gloves.dmi
  icons/clothing/uniform/misc/ante_boobflap.dmi
  icons/mob/clothing/ties.dmi
  icons/mob/human_face_vr.dmi
  icons/mob/human_face_vr_add.dmi
  icons/mob/sprite_accessories/markings.dmi
  icons/obj/clothing/ties.dmi
Labels: size/M

#6114 Bugfixes 10/23 Round Two
  code/game/objects/items/storage/misc.dm
  code/game/objects/items/weapons/swords_axes_etc.dm
  code/modules/donatorreskins/donatoruniform.dm
  code/modules/jobs/job_types/station/engineering/station_engineer.dm
  code/modules/loadout/loadout_role_restricted.dm
  code/modules/mining/ore_redemption_machine/equipment_vendor.dm
  code/modules/mob/living/silicon/emote.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules/station.dm
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/reagents/machinery/dispenser/synthesizer.dm
  code/modules/research/designs/mining_toys.dm
  code/modules/vore/fluffstuff/custom_items.dm
  config/custom_items.txt
  icons/clothing/donator/uniform/chayse.dmi
  icons/mob/clothing/donatorclothing.dmi
  icons/mob/items/64x64_lefthand.dmi
  icons/mob/items/64x64_righthand.dmi
  icons/obj/clothing/donatorclothing.dmi
Labels: size/L

#6119 Fixes a runtime in powered atmos machines
  code/modules/atmospherics/machinery/portable/powered.dm
Labels: size/XS

#6118 Fixes Mapped Directional Sprites, Adds Pet, General Mapping Bug Fixes
  code/modules/mob/living/simple_mob/subtypes/animal/sif/racoon.dm
  code/modules/tables/presets.dm
  maps/rift/levels/rift-04-surface1.dmm
  maps/rift/levels/rift-05-surface2.dmm
  maps/rift/levels/rift-06-surface3.dmm
Labels: size/L

#6123 removes automatic diona nymph death
  code/modules/organs/external/species/diona.dm
Labels: size/XS

#6121 Service Borg Drink Fab upgrade
  code/modules/reagents/reagent_containers/borghydro.dm
Labels: size/XS

#6128 fixes hammer heads being called forks
  code/datums/recipe/material_recipes/tools.dm
Labels: size/XS

#6125 CI: Skipping is native feature
  .github/workflows/ci_suite.yml
Labels: size/XS

#6127 Replikant Apparel, Armor, Leg Markings and 2nd Gen prosthetics.
  code/modules/clothing/head/misc.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/accessories/accessory.dm
  code/modules/clothing/under/accessories/clothing_cit.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/loadout/loadout_accessories.dm
  code/modules/loadout/loadout_head.dm
  code/modules/loadout/loadout_uniform.dm
  code/modules/loadout/loadout_utility.dm
  code/modules/organs/external/robolimbs.dm
  code/modules/sprite_accessories/markings/synth_stuff.dm
  icons/clothing/suit/armor/replika.dmi
  icons/clothing/uniform/misc/replika.dmi
  icons/mob/clothing/head.dmi
  icons/mob/clothing/ties.dmi
  icons/mob/cyberlimbs/replikant/replikant2.dmi
  icons/mob/items/lefthand_hats.dmi
  icons/mob/items/righthand_hats.dmi
  icons/mob/sprite_accessories/markings/synth_stuff.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/ties.dmi
Labels: size/L

#6132 Tridot body marking (forehead)
  code/modules/sprite_accessories/markings/eye_stuff.dm
  icons/mob/sprite_accessories/markings/eye_stuff.dmi
Labels: size/S

#6139 Replika Armor in Loadout (no defense stats)
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/accessories/clothing.dm
  code/modules/loadout/loadout_suit.dm
  icons/mob/clothing/suits.dmi
  icons/obj/clothing/suits.dmi
Labels: size/M

#6137 Adds Replika Specific Body Marking
  code/modules/sprite_accessories/markings/synth_stuff.dm
  icons/mob/sprite_accessories/markings/synth_stuff.dmi
Labels: size/S

#6135 fixes gpses breaking on flight
  code/game/atoms/atom.dm
  code/game/objects/items/devices/gps.dm
  code/modules/multiz/movement.dm
Labels: size/S

#6130 Removes old duplicate backpack of holding singularity_act
  code/modules/power/singularity/act.dm
Labels: size/XS

#6129 Destroys the Universe
  citadel.dme
  code/controllers/subsystem/emergency_shuttle.dm
  code/controllers/subsystem/ticker.dm
  code/game/gamemodes/cult/hell_universe.dm
  code/game/gamemodes/cult/narsie.dm
  code/game/gamemodes/cult/runes.dm
  code/game/gamemodes/endgame/endgame.dm
  code/game/gamemodes/endgame/supermatter_cascade/blob.dm
  code/game/gamemodes/endgame/supermatter_cascade/portal.dm
  code/game/gamemodes/endgame/supermatter_cascade/universe.dm
  code/game/machinery/computer/communications.dm
  code/global.dm
  code/modules/admin/secrets/final_solutions/supermatter_cascade.dm
  code/modules/mob/animations.dm
  code/modules/power/singularity/act.dm
Labels: size/XL

#6126 Subtypes Corporate Crates, Fixes Mapped Biohazard Crate, Renames Advanced Voidsuit
  code/game/objects/random/mapping.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/modules/cargo/supplypacks/costumes.dm
  code/modules/cargo/supplypacks/engineering.dm
  code/modules/cargo/supplypacks/hospitality.dm
  code/modules/cargo/supplypacks/medical.dm
  code/modules/cargo/supplypacks/misc.dm
  code/modules/cargo/supplypacks/munitions.dm
  code/modules/cargo/supplypacks/recreation.dm
  code/modules/cargo/supplypacks/robotics.dm
  code/modules/cargo/supplypacks/security.dm
  code/modules/cargo/supplypacks/supply.dm
  code/modules/cargo/supplypacks/voidsuits.dm
  code/modules/hardsuits/suits/station/engineering.dm
  code/modules/mining/ore_redemption_machine/engineering_points_vendor.dm
  icons/obj/storage.dmi
  maps/euthenia/levels/deck1.dmm
  maps/euthenia/levels/deck2.dmm
  maps/euthenia/levels/deck3.dmm
  maps/euthenia/levels/deck4.dmm
  maps/rift/levels/rift-02-underground2.dmm
  maps/rift/levels/rift-03-underground1.dmm
  maps/rift/levels/rift-04-surface1.dmm
  maps/sectors/lavaland_140/levels/lavaland_140_east.dmm
  maps/templates/shuttles/overmaps/generic/bearcat.dmm
  maps/templates/shuttles/overmaps/generic/gecko_sh.dmm
Labels: size/XL

#6131 Adjusts Alarms on Shuttles
  maps/templates/shuttles/overmaps/generic/curashuttle.dmm
  maps/templates/shuttles/overmaps/generic/mercship.dmm
  maps/templates/shuttles/overmaps/generic/vespa.dmm
Labels: size/L

#6143 Backpacks in Loadout
  code/modules/loadout/loadout_role_restricted.dm
  code/modules/loadout/loadout_utility.dm
Labels: size/M

#6141 Hypokit placeable on Belt Slot
  code/game/objects/items/storage/medical/hypokit.dm
Labels: size/XS

#6138 various fixes + tweaks
  code/controllers/subsystem/planets.dm
  code/datums/unarmed_attack.dm
  code/game/machinery/pipe/construction.dm
  code/game/objects/effects/chem/foam.dm
  code/game/objects/structures/inflatable.dm
  code/game/objects/structures/low_wall.dm
  code/game/objects/structures/tables/bench.dm
  code/game/objects/structures/tables/rack.dm
  code/game/objects/structures/tables/table.dm
  code/modules/atmospherics/machinery/air_alarm.dm
  code/modules/atmospherics/machinery/components/unary/vent_scrubber.dm
  code/modules/food/food/snacks.dm
  code/modules/mob/living/simple_mob/combat.dm
  code/modules/mob/living/simple_mob/simple_mob.dm
  code/modules/mob/living/simple_mob/subtypes/slime/slime.dm
  code/modules/mob/living/simple_mob/subtypes/slime/xenobio/xenobio.dm
  code/modules/mob/observer/observer.dm
  code/modules/planet/planet.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/species/protean/protean_blob.dm
  tgui/packages/tgui/interfaces/common/Materials.tsx
Labels: Fix, size/L

#6140 buffs borg lights
  code/modules/mob/living/silicon/robot/robot.dm
Labels: size/XS

#6142 minor inv fixes
  code/modules/mob/inventory/inventory.dm
  code/modules/mob/inventory/items.dm
  code/modules/mob/inventory/slot_meta.dm
Labels: size/XS

#6146 fixes storage not dropping contents on destruction
  code/game/objects/items/storage/_storage.dm
Labels: size/XS

#6144 Objectifies Fish
  code/__DEFINES/fishing/fishing.dm
  code/modules/fishing/fish/fish_types.dm
  code/modules/fishing/legacy.dm
  code/modules/fishing/sources/ocean.dm
  icons/modules/fishing/fish.dmi
Labels: size/L

#6113 Updates the Description for CentCom Memorials
  code/game/objects/structures/statues.dm
  icons/obj/structures.dmi
  maps/rift/levels/rift-11-orbital.dmm
  maps/triumph/levels/flagship.dmm
Labels: size/S

#6148 Removes Carpotoxin from Fish-Based Dishes
  code/modules/food/food/snacks.dm
Labels: size/XS

#6150 Fixes Broken Empty Gun Sprites
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/semiauto.dm
  icons/obj/gun/ballistic.dmi
Labels: size/XS

#6149 kevlar upgrades no longer make you immortal
  code/game/objects/items/upgradekit.dm
Labels: size/S

#6157 Fixes Auril Castes not being able to wear hardsuits
  code/__DEFINES/species/species.dm
  code/game/machinery/suit_storage/suit_cycler.dm
Labels: size/XS

#6153 Skrell Update
  code/modules/species/station/standard/skrell.dm
  code/modules/sprite_accessories/hair/skrell.dm
  code/modules/sprite_accessories/markings/_markings.dm
  icons/mob/human_face.dmi
  icons/mob/human_face_m.dmi
  icons/mob/species/eyes.dmi
  icons/mob/species/skrell/body_greyscale.dmi
  icons/mob/species/skrell/eyes.dmi
  icons/mob/species/skrell/preview.dmi
  icons/mob/sprite_accessories/markings.dmi
  icons/screen/actions/actions.dmi
Labels: size/M

#6154 Makes cups of water not cups of.. what?
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Core.dm
Labels: size/XS

#6147 Mar (Adds *mar emote)
  code/modules/mob/living/carbon/human/emote.dm
  sound/voice/mar.ogg
Labels: size/XS

#6160 adds a cropped sweater
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/accessories/clothing.dm
  code/modules/loadout/loadout_suit.dm
  icons/clothing/suit/misc/cropped.dmi
  icons/mob/clothing/ties.dmi
  icons/obj/clothing/ties.dmi
Labels: size/M

#6152 pet peeve solved
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Food-Drinks.dm
Labels: size/XS

#6165 various bugfixes
  citadel.dme
  code/__DEFINES/_bitfields.dm
  code/__DEFINES/movespeed_modification.dm
  code/game/objects/structures/crates_lockers/closets/coffin.dm
  code/game/turfs/simulated/floor_types/water.dm
  code/modules/atmospherics/environmental/atom.dm
  code/modules/atmospherics/environmental/turf.dm
  code/modules/clothing/under/accessories/accessory.dm
  code/modules/clothing/under/accessories/bracelets/_bracelets.dm
  code/modules/clothing/under/accessories/bracelets/material.dm
  code/modules/integrated_electronics/core/integrated_circuit.dm
  code/modules/integrated_electronics/core/tools.dm
  code/modules/integrated_electronics/subtypes/output.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/movement.dm
  code/modules/movespeed/modifiers/mob.dm
  code/modules/movespeed/movespeed_modifier.dm
  code/modules/power/fission/rods.dm
Labels: size/L

#6159 bandaids hypospray
  code/modules/reagents/items/hypospray.dm
Labels: size/XS

#6155 Reverts reinforced windows dropping metal rods
  code/game/objects/structures/window.dm
Labels: size/XS

#6168 Byond lists start at 1
  code/game/dna/dna2.dm
Labels: size/XS

#6170 fixes tables & poewrnet
  code/game/objects/structures/tables/materials.dm
  code/modules/power/cable.dm
Labels: size/S

#6166 small CI system rewrite
  .github/workflows/ci_suite.yml
  code/__DEFINES/rust_g.dm
  code/modules/materials/definitions/metals/uranium.dm
  code/modules/materials/definitions/special/supermatter.dm
  code/modules/materials/material.dm
  code/modules/materials/traits/glow.dm
  code/modules/materials/traits/radioactive.dm
  dependencies.sh
  tools/CreditsTool/CreditsTool.csproj
  tools/CreditsTool/CreditsTool.exe
  tools/CreditsTool/Program.cs
  tools/CreditsTool/UpdateCreditsDMI.sh
  tools/CreditsTool/remappings.txt
  tools/README.md
  tools/Upload tgstation.rsc to external FTP/upload_rsc.bat
  tools/autowiki/autowiki.js
  tools/autowiki/package-lock.json
  tools/autowiki/package.json
  tools/bootstrap/README.md
  tools/bootstrap/common.ps1
  tools/bootstrap/common.sh
  tools/bootstrap/node
  tools/bootstrap/node.bat
  tools/bootstrap/node_.ps1
  tools/bootstrap/python37._pth
  tools/bootstrap/python_.ps1
  tools/build/build.js
  tools/ci/build.ps1
  tools/ci/build_spaceman_dmm.sh
  tools/ci/install/install_byond.sh
  tools/ci/install/install_rust_g.sh
  tools/ci/install/install_spaceman_dmm.sh
  tools/ci/install_node.sh
  tools/ci/new_check_grep.sh
  tools/ci/run_server.sh
  tools/common/functions.ps1
  tools/common/functions.sh
  tools/requirements.txt
Labels: FUCK, size/XXL
