Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2023-09, with the labels that each got.

#5935 Fixes climbing interruptions letting you climb anyway
  code/game/objects/objs.dm
Labels: size/XS

#5931 better admin tooling and character profiles
  code/datums/character_profile.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/admin_set_headshot.dm
  code/modules/mob/living/living_defines.dm
  code/modules/preferences/_preferences.dm
  code/modules/preferences/preference_setup/general/01_basic.dm
Labels: size/L

#5942 disables tether holomap smooshing
  maps/tether/tether.dm
Labels: size/M

#5940 The Hive Awakens
  code/game/objects/random/mob.dm
  code/modules/maps/overmap/planets/virgo2.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/hivebot/hivebot.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/hivebot/ranged_damage.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/hivebot/ranged_damage_vr.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/hivebot/support.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/hivebot/support_vr.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/hivebot/tank.dm
  icons/mob/hivebot.dmi
  maps/away_missions/140x140/snow_outpost.dmm
  maps/submaps/level_specific/debrisfield_vr/ship_mining_drone.dmm
  maps/submaps/wilderness/Drugden.dmm
Labels: size/L

#5937 fixes gas reagents + action buttons when dead
  code/modules/atmospherics/gasmixtures/gas_types_hardcoded.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/login.dm
Labels: size/S

#5945 Restores CentCom (Demeter) Landmark
  maps/rift/levels/rift-11-orbital.dmm
Labels: size/XS

#5952 fixes nitrogen breathing
  code/modules/mob/living/carbon/human/traits/neutral.dm
Labels: Priority 0: CRITICAL, size/XS

#5957 fixes a list referencing oopsie
  code/modules/atmospherics/machinery/air_alarm.dm
Labels: FUCK, Priority 0: CRITICAL, size/XS

#5955 biogenerator fixes
  code/game/machinery/biogenerator.dm
  tgui/packages/tgui/interfaces/Biogenerator.js
Labels: size/XS

#5954 Fixes and creates variants of the Opaque Gas Mask
  code/modules/clothing/masks/gasmask.dm
  code/modules/loadout/loadout_mask.dm
Labels: size/S

#5953 fixes hf machete
  code/game/objects/items/weapons/melee/energy.dm
Labels: size/XS

#5947 Mortar Hivebot Nerf Hotfix
  code/modules/mob/living/simple_mob/subtypes/mechanical/hivebot/ranged_damage.dm
Labels: size/XS

#5941 Caliber updates
  code/datums/design/designs/ammo/lmg.dm
  code/datums/design/designs/ammo/rife.dm
  code/datums/uplink/ammunition.dm
  code/datums/uplink/visible_weapons.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/uplink_kits.dm
  code/game/objects/random/guns_and_ammo.dm
  code/game/objects/random/misc.dm
  code/modules/awaymissions/loot_vr.dm
  code/modules/mob/living/simple_mob/subtypes/humanoid/mercs/mercs.dm
  code/modules/mob/living/simple_mob/subtypes/vore/corrupt_hounds.dm
  code/modules/projectiles/ammunition/rounds.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  code/modules/projectiles/guns/projectile/sniper.dm
  code/modules/projectiles/magazines/unsorted.dm
  code/modules/projectiles/projectile/bullets.dm
  maps/rift/levels/rift-11-orbital.dmm
  maps/templates/admin/dhael_centcom.dmm
  maps/templates/admin/ert.dmm
  maps/templates/admin/ert_base.dmm
  maps/templates/admin/kk_mercship.dmm
  maps/templates/admin/mercbase.dmm
  maps/templates/shelters/shelter_4.dmm
  maps/templates/shuttles/overmaps/generic/cruiser.dmm
  maps/templates/shuttles/overmaps/generic/shelter_6.dmm
  maps/triumph/levels/flagship.dmm
Labels: size/XL

#5956 Replaces Surt Emergency Double Airlock
  maps/sectors/lavaland_192/levels/lavaland_192.dmm
Labels: size/S

#5951 Restores Old Crate Sprites, Leaves New Render System Intact
  code/game/objects/structures/crates_lockers/crates.dm
Labels: size/L

#5946 Fixes Graves
  code/game/objects/structures/crates_lockers/closets/coffin.dm
  icons/obj/closets/grave.dmi
Labels: size/XS

#5933 Refinements to Violet Protocol
  code/__DEFINES/atmospherics/machinery/scrubber.dm
  code/controllers/subsystem/air.dm
  code/modules/atmospherics/gasmixtures/gas_types_hardcoded.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Toxins.dm
  maps/rift/levels/rift-04-surface1.dmm
Labels: size/L

#5967 makes sonar pulses cooldown faster
  code/modules/species/abilites.dm
Labels: size/XS

#5968 adds (steals) a few new hairs (from skyrat and bubber)
  code/modules/sprite_accessories/hair/_hair.dm
  icons/mob/human_face.dmi
  icons/mob/human_face_m.dmi
Labels: size/M

#5973 Replaces Erroneously Mapped Bins with Biohazard Bins
  maps/rift/levels/rift-05-surface2.dmm
  maps/triumph/levels/deck3.dmm
Labels: size/L

#5976 allows -1 in air alarm tlv again
  code/modules/atmospherics/machinery/air_alarm.dm
Labels: size/XS

#5970 adds fishernets as undershirts
  code/datums/underwear/undershirts.dm
Labels: size/S

#5963 Fixes Engineers being unable to select pleated skirts
  code/modules/loadout/loadout_role_restricted.dm
Labels: size/XS

#5959 tidy the xenochimera species file
  code/modules/species/station/xenochimera.dm
Labels: size/L

#5966 Updates Tajaran lore to match more to what the wiki has currently
  code/__DEFINES/languages/legacy.dm
  code/modules/language/languages/species/tajaran.dm
  code/modules/species/station/standard/tajaran.dm
Labels: size/M

#5969 blobform reworks
  code/__DEFINES/inventory/procs.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/devices/radio/radio.dm
  code/modules/hardsuits/_rig.dm
  code/modules/hardsuits/rig_attackby.dm
  code/modules/hardsuits/suits/species/protean.dm
  code/modules/mob/inventory/inventory.dm
  code/modules/mob/inventory/mobs.dm
  code/modules/mob/inventory/stripping.dm
  code/modules/mob/living/simple_mob/simple_mob_vr.dm
  code/modules/organs/organ.dm
  code/modules/species/promethean/promethean_blob.dm
  code/modules/species/protean/protean.dm
  code/modules/species/protean/protean_blob.dm
Labels: size/L

#5936 [READY] Porting VORE's Xenobiology fixes & extract rewards + some Citadel bonuses
  citadel.dme
  code/__HELPERS/global_lists.dm
  code/game/machinery/biogenerator.dm
  code/game/objects/items/circuitboards/machinery/research.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/storage/bags.dm
  code/modules/ai/aI_holder_subtypes/slime_xenobio_ai.dm
  code/modules/ghostroles/instantiator.dm
  code/modules/ghostroles/role.dm
  code/modules/ghostroles/roles/sapient_mob.dm
  code/modules/ghostroles/spawnpoint.dm
  code/modules/mob/_modifiers/modifiers.dm
  code/modules/mob/living/bot/secbot.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/death.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_mob/defense.dm
  code/modules/mob/living/simple_mob/subtypes/slime/slime.dm
  code/modules/mob/living/simple_mob/subtypes/slime/xenobio/subtypes.dm
  code/modules/mob/living/simple_mob/subtypes/slime/xenobio/xenobio.dm
  code/modules/reagents/Misc-Recipes.dm
  code/modules/research/designs/circuits/circuits.dm
  code/modules/species/promethean/promethean.dm
  code/modules/xenobio/items/extracts.dm
  code/modules/xenobio/items/slime_objects.dm
  code/modules/xenobio/items/slimepotions.dm
  code/modules/xenobio/machinery/processor.dm
  icons/mob/clothing/back.dmi
  icons/mob/slimes.dmi
  icons/obj/clothing/backpack.dmi
  icons/obj/kitchen.dmi
  icons/obj/storage.dmi
  maps/rift/levels/rift-05-surface2.dmm
  maps/submaps/level_specific/debrisfield/ship_sci_overrun.dmm
  maps/submaps/level_specific/debrisfield_vr/ship_sci_overrun.dmm
  maps/tether/levels/surface2.dmm
  maps/triumph/levels/deck3.dmm
Labels: size/XXL

#5972 improves admin set headshots a bit
  code/modules/admin/verbs/admin_set_headshot.dm
Labels: size/XS

#5978 Adds An Outfit and Hairstyle [IDB IGNORE]
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/shoes/boots.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/holidays/halloween_loadout.dm
  code/modules/sprite_accessories/hair/_hair.dm
  icons/clothing/gloves/darkcleric.dmi
  icons/clothing/head/darkcleric.dmi
  icons/clothing/shoes/boots/darkcleric.dmi
  icons/clothing/uniform/costume/darkcleric.dmi
  icons/mob/human_face.dmi
  icons/mob/human_face_alt.dmi
  icons/mob/human_face_m.dmi
Labels: size/M

#5977 rig fixes
  code/modules/hardsuits/_rig.dm
  code/modules/hardsuits/rig.dm
Labels: Priority 1: High, size/XXL

#5975 removes automatic material scaling on /obj/item/material
  code/game/objects/items/weapons/material/material_weapons.dm
Labels: size/XS

#5980 removes a singular stray white pixel from the blueshield's satchel
  icons/mob/clothing/back.dmi
Labels: size/XS

#5982 fixes a bug
  code/modules/species/protean/protean.dm
Labels: size/XS

#5981 Removes wolfgirl crates from Cargo
  code/modules/cargo/supplypacks/contraband.dm
Labels: size/XS

#5962 Integrated circuits fixes and changes
  code/controllers/subsystem/pathfinder.dm
  code/modules/integrated_electronics/core/assemblies.dm
  code/modules/integrated_electronics/core/helpers.dm
  code/modules/integrated_electronics/subtypes/converters.dm
  code/modules/integrated_electronics/subtypes/input.dm
  code/modules/integrated_electronics/subtypes/output.dm
  code/modules/integrated_electronics/subtypes/smart.dm
Labels: size/L

#5979 Fixes disposal outlets not throwing objects/mobs
  code/modules/recycling/disposal.dm
Labels: size/XS

#5983 Adds Classic Fish Back to the Fishing List
  code/modules/fishing/sources/ocean.dm
Labels: size/XS

#5984 Fixes Blueshield Experimental Carrier Missing Sprite
  icons/mob/clothing/modular_armor.dmi
Labels: size/XS

#5985 Fortuna/Desertrose clothing port
  code/modules/clothing/under/miscellaneous.dm
  code/modules/loadout/loadout_uniform.dm
  icons/mob/clothing/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: size/M

#5988 add a confirmation to using hatch stasis
  code/modules/species/station/xenochimera.dm
Labels: size/XS

#5995 Adds a unit test to squash alcoholic drinks made with only non-alcoholic reagents
  code/modules/food/drinkingglass/metaglass.dm
  code/modules/reagents/Drink-Recipes.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/unit_tests/_unit_tests.dm
  code/modules/unit_tests/bad_alcohol_reagents.dm
Labels: size/M

#5990 Adds Promethean Biolinguistics language
  citadel.dme
  code/__DEFINES/languages/ids.dm
  code/__DEFINES/languages/legacy.dm
  code/modules/language/languages/species/promethean.dm
  code/modules/mob/living/simple_mob/subtypes/slime/slime.dm
  code/modules/species/promethean/promethean.dm
  code/modules/species/promethean/promethean_blob.dm
  code/modules/species/species.dm
  code/modules/species/station/standard/akula.dm
  code/modules/species/station/standard/human.dm
  code/modules/species/station/standard/skrell.dm
  code/modules/species/station/standard/zaddat.dm
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
Labels: size/M

#5987 disables air alarm sounds
  code/modules/atmospherics/machinery/air_alarm.dm
Labels: size/XS

#5989 puts a mutex on protean blob transforms
  code/modules/species/protean/protean_blob.dm
Labels: Priority 1: High, size/XS

#5992 fixes alignment issues with macros/micros/etc
  code/game/atoms/atom.dm
  code/game/atoms/movable/movable.dm
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/mob.dm
  code/modules/vore/resizing/resize_vr.dm
Labels: size/M

#5994 Explorer Radio format changes/fixes & Entertainment Radio format fixes
  code/__DEFINES/spans.dm
  interface/stylesheet.dm
  tgui/packages/tgui-panel/chat/constants.js
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
Labels: size/S

#6002 Fixes prommie slimes dying instantly to water
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Core.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Medicine.dm
  code/modules/species/promethean/promethean_blob.dm
Labels: size/S

#6003 Adds a couple of uniforms
  code/game/machinery/vending.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/loadout/loadout_uniform.dm
  icons/mob/clothing/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: size/M

#6006 fixes a direct armor access
  code/modules/clothing/suits/hooded.dm
Labels: size/XS

#6005 Renames Icons and Fixes MG42
  code/modules/projectiles/guns/projectile/automatic.dm
  icons/obj/ammo.dmi
Labels: size/XS

#6004 Adds Seraph Wings
  code/modules/sprite_accessories/wings/feathered.dm
  icons/mob/sprite_accessories/wings.dmi
  icons/mob/sprite_accessories/wings_64x48.dmi
Labels: size/S

#6001 Rearranges Surt Jump Pads For Accessibility
  maps/rift/levels/rift-02-underground2.dmm
  maps/sectors/lavaland_140/levels/lavaland_140.dmm
  maps/sectors/lavaland_192/levels/lavaland_192.dmm
  maps/triumph/levels/deck2.dmm
Labels: size/XXL

#5998 Let That Sink In (Adds A Sink to Triumph Robotics Surgery)
  maps/triumph/levels/deck3.dmm
Labels: size/XS

#6007 no more ai loadout spawns
  code/controllers/subsystem/job/_legacy_job_stuff.dm
Labels: size/S

#5997 Pilk :^)
  code/modules/food/drinkingglass/metaglass.dm
  code/modules/reagents/Drink-Recipes.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Food-Drinks.dm
  icons/obj/drinks.dmi
Labels: size/M

#5965 ODST Voidsuits
  code/modules/cargo/supplypacks/voidsuits.dm
  code/modules/clothing/spacesuits/void/merc.dm
  icons/mob/clothing/head.dmi
  icons/mob/clothing/suits.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/spacesuits.dmi
Labels: size/L

#5991 Re-adds security RIGsuits
  maps/tether/levels/surface2.dmm
  maps/tether/levels/surface3.dmm
  maps/triumph/levels/deck4.dmm
Labels: size/M

#6013 the bridge officer title update
  code/modules/jobs/job_types/station/command/command_secretary.dm
Labels: size/S

#6008 ais, pais, and cyborgs can all speak translation class level 1 languages now
  code/modules/mob/living/silicon/silicon.dm
Labels: size/XS

#6011 Tonight on Fix+QoL Gear....
  code/game/objects/items/stock_parts/part_replacer.dm
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/modules/food/food/cans.dm
  code/modules/research/designs/circuits/circuits.dm
  code/modules/research/designs/mechfab_designs.dm
Labels: size/M

#6016 changes emag orion trail reward from a 1,2,4 explosion to a 0,0,2 explosion
  code/game/machinery/computer/arcade/orion.dm
Labels: size/XS

#6000 General Map Triage 09/23
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  icons/mob/clothing/head.dmi
  maps/triumph/levels/deck3.dmm
  maps/triumph/levels/deck4.dmm
  maps/triumph/levels/flagship.dmm
Labels: size/XXL

#5949 Tradeport Visitor Prefix
  code/modules/maps/overmap/space/trade_station/trade_station.dm
  maps/sectors/tradeport/shuttles.dm
  maps/sectors/tradeport_192/levels/tradeport_192.dmm
Labels: size/XXL

#6021 fixes a stackcrafting issue
  code/datums/recipe/material_recipe.dm
  code/datums/recipe/material_recipes/furniture.dm
  code/datums/recipe/material_recipes/structures.dm
  code/datums/recipe/material_recipes/tools.dm
  code/datums/recipe/stack_recipe.dm
  code/datums/recipe/stack_recipes/misc.dm
  code/datums/recipe/stack_recipes/structures.dm
Labels: Priority 1: High, size/L

#6020 Separates solar and lunar moth sprites
  code/modules/mob/living/simple_mob/subtypes/vore/solarmoth_ch.dm
  icons/mob/solarmoth.dmi
Labels: size/XS

#6022 Fixes Latex Maid Outfit
  code/modules/vore/fluffstuff/custom_clothes.dm
Labels: size/XS

#6018 Makes bananium, silencium actually spawnable - retypes chitin to be a material
  citadel.dme
  code/datums/recipe/crafting_recipes/recipes_primal.dm
  code/game/objects/items/stacks/sheets/leather.dm
  code/modules/materials/definitions/crystals/diamond.dm
  code/modules/materials/definitions/crystals/glass.dm
  code/modules/materials/definitions/metals/copper.dm
  code/modules/materials/definitions/metals/durasteel.dm
  code/modules/materials/definitions/metals/gold.dm
  code/modules/materials/definitions/metals/hydrogens.dm
  code/modules/materials/definitions/metals/iron.dm
  code/modules/materials/definitions/metals/lead.dm
  code/modules/materials/definitions/metals/osmium.dm
  code/modules/materials/definitions/metals/plasteel.dm
  code/modules/materials/definitions/metals/platinum.dm
  code/modules/materials/definitions/metals/silver.dm
  code/modules/materials/definitions/metals/steel.dm
  code/modules/materials/definitions/metals/titanium.dm
  code/modules/materials/definitions/metals/uranium.dm
  code/modules/materials/definitions/organic/chitin.dm
  code/modules/materials/definitions/special/clown_planet.dm
  code/modules/materials/definitions/special/morphium.dm
  code/modules/materials/definitions/special/phoron.dm
  code/modules/materials/definitions/special/supermatter.dm
  code/modules/materials/definitions/special/valhollide.dm
  code/modules/materials/definitions/special/verdantium.dm
  code/modules/materials/fifty_spawner_mats.dm
  code/modules/materials/material_sheets.dm
  code/modules/mob/living/simple_mob/subtypes/lavaland/gutshank.dm
Labels: size/L

#6009 Adjusts Improvised Weapon Fail Rates and Adds Improved Tyrmalin Rokkit Launcher
  code/modules/projectiles/ammunition/rounds.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/guns/projectile/contender.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  code/modules/projectiles/guns/projectile/rocket.dm
  icons/obj/gun/ballistic.dmi
  icons/obj/items.dmi
Labels: size/L

#6019 Minor Layout Adjustment to Archaic Temple and Statue Component Bugfix
  code/datums/components/unobserved_actor.dm
  code/game/objects/effects/traps.dm
  code/modules/clothing/shoes/boots.dm
  code/modules/mob/living/simple_mob/subtypes/occult/living_statue.dm
  icons/mob/clothing/back.dmi
  icons/mob/clothing/feet.dmi
  icons/mob/clothing/hands.dmi
  icons/mob/clothing/suits.dmi
  icons/obj/clothing/backpack.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/shoes.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/statue.dmi
  maps/submaps/level_specific/class_p/archaictemple.dmm
Labels: size/L

#6017 Canonizes the LiquidFood Straw, Adds Opening Proc to Foods For Snack Purposes, Seals Snack Foods
  code/game/machinery/vending.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/storage/single_use/mre.dm
  code/game/objects/items/weapons/gift_wrappaper.dm
  code/game/objects/random/mapping.dm
  code/game/objects/random/misc.dm
  code/game/objects/structures/crates_lockers/closets/secure/explorer.dm
  code/game/objects/structures/loot_piles.dm
  code/game/objects/structures/trash_pile.dm
  code/modules/cargo/supplypacks/hospitality.dm
  code/modules/cargo/supplypacks/misc.dm
  code/modules/examine/descriptions/food.dm
  code/modules/food/food/lunch.dm
  code/modules/food/food/snacks.dm
  code/modules/species/promethean/promethean.dm
  icons/obj/food.dmi
  maps/minitest/levels/sector2.dmm
  maps/sectors/piratebase_192/levels/piratebase_192.dmm
  maps/sectors/tradeport_140/levels/tradeport_140.dmm
  maps/sectors/tradeport_192/levels/tradeport_192.dmm
  maps/submaps/level_specific/class_d/landing_padD.dmm
  maps/submaps/level_specific/class_h/landing_padH.dmm
  maps/submaps/level_specific/virgo2/DJOutpost1.dmm
  maps/submaps/mountains/quarantineshuttle.dmm
  maps/submaps/plains/Boathouse.dmm
  maps/submaps/plains/Boathouse_vr.dmm
  maps/submaps/plains/Mechpt.dmm
  maps/submaps/plains/Oldhouse.dmm
  maps/submaps/plains/Oldhouse_vr.dmm
  maps/submaps/plains/Smol3.dmm
  maps/submaps/wilderness/DJOutpost1.dmm
  maps/submaps/wilderness/DJOutpost3.dmm
  maps/submaps/wilderness/DJOutpost4.dmm
  maps/templates/admin/dhael_centcom.dmm
  maps/templates/admin/ert.dmm
  maps/templates/admin/ert_base.dmm
  maps/templates/shelters/shelter_4.dmm
  maps/templates/shelters/shelter_a.dmm
  maps/templates/shuttles/overmaps/generic/cruiser.dmm
  maps/templates/shuttles/overmaps/generic/itglight.dmm
  maps/templates/shuttles/overmaps/generic/shelter_6.dmm
  maps/tether/levels/misc.dmm
  maps/tether/levels/station1.dmm
Labels: size/XL

#6012 RPED 2: You mean I can fast replace cells and beakers with this?
  code/game/machinery/_machinery.dm
  code/game/objects/items.dm
  code/game/objects/items/stock_parts/part_replacer.dm
  code/modules/power/cell.dm
  code/modules/power/cells/power_cells.dm
  code/modules/reagents/reagent_containers/glass.dm
Labels: size/M

#6026 Makes the TEG soundloop not go through walls
  code/modules/power/generator.dm
Labels: size/XS

#6025 buffs death alarms
  code/game/objects/items/weapons/implants/implant.dm
Labels: size/S

#6010 Reworks Atlas Wiring to not be Cancer
  code/game/area/Space Station 13 areas.dm
  maps/rift/levels/rift-02-underground2.dmm
  maps/rift/levels/rift-03-underground1.dmm
  maps/rift/levels/rift-04-surface1.dmm
  maps/rift/levels/rift-05-surface2.dmm
  maps/rift/levels/rift-06-surface3.dmm
Labels: size/XXL

#6015 More Moneysinks, plus some stock moved around.
  code/game/objects/items/contraband.dm
  code/modules/cargo/supplypacks/contraband.dm
Labels: size/L

#6030 Makes the power monitor display supply/draw correctly
  tgui/packages/tgui/interfaces/PowerMonitor.js
Labels: size/XS

#5996 Ports virgo's Jukebox interface / overhauls the old one, portable music players and more jukebox songs / some fixes (Oh my!)
  citadel.dme
  code/__DEFINES/controllers/_subsystems.dm
  code/__HELPERS/sorts/comparators.dm
  code/controllers/subsystem/media_tracks.dm
  code/game/machinery/jukebox.dm
  code/game/machinery/vending.dm
  code/game/sound.dm
  code/modules/cargo/supplypacks/misc.dm
  code/modules/loadout/loadout_utility.dm
  code/modules/media/media_tracks.dm
  code/modules/media/walkpod.dm
  config/entries/general.txt
  config_static/jukebox.json
  tgui/packages/tgui/interfaces/Jukebox.js
Labels: size/XXL

#6027 Mecha Lore Revisions, Retcons, and General Edits
  citadel.dme
  code/game/mecha/combat/gygax.dm
  code/game/mecha/combat/honker.dm
  code/game/mecha/combat/marauder.dm
  code/game/mecha/combat/phazon.dm
  code/game/mecha/working/ripley.dm
  code/game/objects/items/paintkit.dm
  code/modules/clothing/head/oricon.dm
  code/modules/examine/descriptions/mecha.dm
  code/modules/lore_codex/robutt_data/bybrand.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/mecha/adv_dark_gygax.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/mecha/durand.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/mecha/gygax.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/mecha/honker.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/mecha/hoverpod.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/mecha/marauder.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/mecha/odysseus.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/mecha/phazon.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/mecha/reticent.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/mecha/ripley.dm
  icons/mecha/mecha.dmi
Labels: size/L
