Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2023-12, with the labels that each got.

#6167 Renames A Soda Brand
  code/game/machinery/vending.dm
  code/modules/food/food/cans.dm
  code/modules/reagents/Drink-Recipes.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Food-Drinks.dm
Labels: size/L

#6174 what'soever
  code/__HELPERS/text.dm
Labels: size/XS

#6184 downgrades pyhton to 3.9.0
  dependencies.sh
Labels: size/XS

#6177 Ports a large snake tail from Skyrat
  code/modules/sprite_accessories/tail/scalies.dm
  icons/mob/sprite_accessories/tails.dmi
Labels: size/M

#6175 fixes chaplain alt title 'Counselor'
  code/modules/jobs/job_types/station/civillian/chaplain.dm
Labels: size/XS

#6173 Buffs Borg'Os
  code/modules/mob/living/silicon/robot/dogborg/dog_modules_vr.dm
Labels: size/XS

#6172 KyoCola Hotfix
  code/modules/food/food/cans.dm
  icons/obj/drinks.dmi
Labels: size/XS

#6178 adds meatsicles, made by mixing protein and ice
  code/modules/food/food/snacks.dm
  code/modules/reagents/Food-Recipes.dm
  icons/obj/food.dmi
Labels: size/S

#6180 makes it so you can always move through ghosts
  code/modules/mob/observer/mobility.dm
Labels: size/XS

#6183 smacks the CI suite with the if: always()
  .github/workflows/ci_suite.yml
Labels: size/S

#6182 Adds a relay spawner that autoconnects to the station comms
  citadel.dme
  code/modules/mapping/spawner/tcomms_relay.dm
Labels: size/S

#6186 Fixes black duffelbags not being lightweight
  code/game/objects/items/storage/backpack.dm
Labels: size/XS

#6188 stop drying racks taking more than one sheet of leather at a time
  code/modules/food/kitchen/smartfridge.dm
Labels: size/XS

#6187 Adds plantpeople physiologies, buffs alraune in snow and water turfs, turf slowdown fixes & additions
  code/__DEFINES/inventory/carry_weight.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/mob/living/carbon/human/movement.dm
  code/modules/species/station/alraune.dm
  code/modules/species/station/diona.dm
Labels: size/S

#6164 Heat pump rebalance (TESTMERGE)
  code/modules/atmospherics/machinery/components/binary_devices/heat_pump.dm
Labels: size/S

#6196 Adds a coffee dispenser crate to cargo
  code/modules/reagents/machinery/dispenser/supply.dm
Labels: size/S

#6190 Jukebox Additions Part Two
  config_static/jukebox.json
Labels: size/XL

#6192 shark ear port from virgo
  citadel.dme
  code/modules/sprite_accessories/ears/animal/shark.dm
  icons/mob/sprite_accessories/ears.dmi
Labels: size/S

#6200 Reduce the amount of mobspawners in trashpiles by 50%
  code/game/objects/structures/trash_pile.dm
Labels: size/S

#6198 Gaia floorlighting starts offline
  code/game/machinery/floor_light.dm
Labels: size/XS

#6203 Adds Mimosas
  code/modules/food/drinkingglass/metaglass.dm
  code/modules/reagents/Drink-Recipes.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Food-Drinks.dm
  icons/obj/drinks.dmi
Labels: size/S

#6199 fixes traits applying to observers
  code/modules/mob/living/carbon/human/traits/_trait.dm
Labels: size/XS

#6205 A few fixes for bots
  code/modules/ai/aI_holder_subtypes/slime_xenobio_ai.dm
  code/modules/mob/living/bot/SLed209bot.dm
  code/modules/mob/living/bot/cleanbot.dm
  code/modules/mob/living/bot/floorbot.dm
  code/modules/mob/living/bot/secbot.dm
Labels: size/M

#6204 Job icon fixes, Job blurb spelling correction
  code/modules/jobs/job_types/station/civillian/librarian.dm
  code/modules/jobs/job_types/station/engineering/atmospherics_technician.dm
  code/modules/jobs/job_types/station/engineering/senior_engineer.dm
  code/modules/jobs/job_types/station/engineering/station_engineer.dm
  code/modules/jobs/job_types/station/medical/head_nurse.dm
  code/modules/jobs/job_types/station/medical/medical_doctor.dm
  code/modules/jobs/job_types/station/science/research_director.dm
  code/modules/jobs/job_types/station/science/scientist.dm
  code/modules/jobs/job_types/station/science/senior_researcher.dm
  code/modules/loadout/loadout_role_restricted.dm
  icons/screen/atom_hud/job.dmi
Labels: size/M

#6189 Adds bluespace mining satchels + BS mining satchel upgrade for minerborgs
  code/game/objects/items/robot/robot_upgrades.dm
  code/game/objects/items/storage/bags.dm
  code/game/objects/random/mapping.dm
  code/game/objects/random/misc.dm
  code/game/objects/random/underdark.dm
  code/modules/loot/packs/gear.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/research/designs/mining_toys.dm
  code/modules/research/designs/prosfab_designs.dm
Labels: size/M

#6193 [TESTMERGE ONLY] Revert "Makes radiation wave decay inverse square instead of exponential"
  code/datums/radiation_wave.dm
Labels: FUCK, Testmerge Only, size/XS

#6176 stop large hypovials going in non-advanced hyposprays
  code/modules/reagents/items/hypospray.dm
Labels: size/XS

#6208 Fixes Borg-O Recipe
  code/modules/food/recipes_microwave.dm
Labels: size/XS

#6201 Autosave duration is now configureable
  code/modules/admin/verbs/smite.dm
Labels: size/S

#6207 Nightshift v2
  citadel.dme
  code/__DEFINES/color/lights.dm
  code/__DEFINES/misc/nightshift.dm
  code/__HELPERS/datastructs/priority_queue.dm
  code/__HELPERS/graphs/astar.dm
  code/__HELPERS/pathfinding/astar.dm
  code/__HELPERS/pathfinding/jps.dm
  code/__HELPERS/sorts/comparators.dm
  code/controllers/configuration/config_entry.dm
  code/controllers/configuration/entries/game.dm
  code/controllers/subsystem/nightshift.dm
  code/game/area/Space Station 13 areas.dm
  code/game/area/area.dm
  code/modules/power/lighting/lighting.dm
  code/modules/power/lighting/lights.dm
  code/modules/unit_tests/core/priority_queue.dm
  config/entries/game.txt
Labels: size/L

#6213 Replaces the RnG of electric shocks with a more sane calculation
  code/modules/power/cell.dm
  code/modules/power/powernet.dm
Labels: size/M

#6211 when loading into a pAI card you can now choose to use a saved name and description
  code/game/click/observer.dm
  code/game/objects/items/devices/paicard.dm
Labels: size/M

#6210 add action buttons for various pAI things, clean pAI code up a bit more
  citadel.dme
  code/datums/action.dm
  code/game/objects/items/devices/paicard.dm
  code/modules/mob/living/defense.dm
  code/modules/mob/living/silicon/pai/actions.dm
  code/modules/mob/living/silicon/pai/mobility.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/living/silicon/pai/verbs.dm
  icons/screen/actions/pai.dmi
Labels: size/L

#6206 Firelocks & Firealarm mapping fixes, Firelock animation fix n' some other stuff
  code/game/machinery/doors/firedoor.dm
  maps/map_levels/140x140/talon/talon2.dmm
  maps/rift/levels/rift-01-underground3.dmm
  maps/rift/levels/rift-02-underground2.dmm
  maps/rift/levels/rift-03-underground1.dmm
  maps/rift/levels/rift-04-surface1.dmm
  maps/rift/levels/rift-05-surface2.dmm
  maps/rift/levels/rift-06-surface3.dmm
  maps/rift/levels/rift-08-west_deep.dmm
  maps/rift/levels/rift-09-west_caves.dmm
  maps/rift/levels/rift-10-west_plains.dmm
  maps/rift/levels/rift-11-orbital.dmm
  maps/sectors/lavaland_140/levels/lavaland_140.dmm
  maps/sectors/lavaland_192/levels/lavaland_192.dmm
  maps/sectors/piratebase_192/levels/piratebase_192.dmm
  maps/sectors/tradeport_140/levels/tradeport_140.dmm
  maps/sectors/tradeport_192/levels/tradeport_192.dmm
  maps/submaps/level_specific/debrisfield_vr/salamander_wreck.dmm
  maps/templates/admin/dhael_centcom.dmm
  maps/templates/admin/ert.dmm
  maps/templates/admin/kk_mercship.dmm
  maps/templates/shuttles/overmaps/generic/salamander.dmm
  maps/tether/levels/misc.dmm
  maps/tether/levels/station1.dmm
  maps/tether/levels/station2.dmm
  maps/tether/levels/surface1.dmm
  maps/tether/levels/surface2.dmm
  maps/tether/levels/surface3.dmm
  maps/triumph/engines/burn.dmm
  maps/triumph/engines/rust.dmm
  maps/triumph/engines/sme.dmm
  maps/triumph/levels/deck1.dmm
  maps/triumph/levels/deck3.dmm
  maps/triumph/levels/flagship.dmm
Labels: size/XXL

#6214 Fixes stationary portable scrubbers, and the phoronlock statemachine
  .vscode/settings.json
  _mapload/minitest.dm
  code/game/machinery/doors/airlock/airlock_control.dm
  code/game/machinery/doors/airlock/phoronlocks.dm
  code/modules/atmospherics/machinery/portable/scrubber.dm
  maps/minitest/levels/minitest.dmm
  tgui/packages/tgui/interfaces/EmbeddedController.js
Labels: size/XXL

#6223 removes access locks from engi rigsuits on triumph
  maps/triumph/levels/deck1.dmm
Labels: size/S

#6218 fixes ghostrole spawners spawning empty mobs when requirements arent met
  code/modules/ghostroles/instantiator.dm
Labels: size/XS

#6220 Adds a new sound for custom votes, to prevent people from thinking they are transfer votes
  code/controllers/subsystem/vote.dm
  sound/custom_vote.ogg
Labels: size/XS

#6216 fixes the tether supply shuttle not loading in properly when ordered
  maps/tether/levels/misc.dmm
Labels: size/XXL

#6226 fixes a machine thing
  code/game/machinery/_machinery.dm
  code/game/machinery/_machinery_construction.dm
Labels: Priority 1: High, size/XS

#6224 Makes the Dataknife Fit Boots
  code/modules/clothing/shoes/_shoes.dm
Labels: size/XS

#6209 door tint fix & door overlay fix
  code/datums/wires/airlock.dm
  code/game/machinery/buttons.dm
  code/game/machinery/doors/airlock/airlock.dm
  code/game/machinery/doors/airlock/airlock_subtypes.dm
  code/game/machinery/doors/airlock/airlock_vr.dm
  code/game/machinery/doors/door.dm
  code/game/machinery/doors/door_vr.dm
  code/game/machinery/doors/firedoor.dm
  code/game/machinery/doors/multi_tile.dm
  code/game/machinery/doors/multi_tile_vr.dm
  code/game/objects/structures/window.dm
  code/modules/examine/descriptions/engineering.dm
  code/modules/turbolift/turbolift_door.dm
  icons/obj/doors/double/door.dmi
  icons/obj/doors/double/lights_deny.dmi
  icons/obj/doors/external/door.dmi
  icons/obj/doors/external/lights_deny.dmi
  icons/obj/doors/hatch/door.dmi
  icons/obj/doors/hatch/lights_deny.dmi
  icons/obj/doors/station/door.dmi
  icons/obj/doors/station/lights_deny.dmi
  icons/obj/doors/vault/door.dmi
  icons/obj/doors/vault/panel.dmi
  maps/sectors/tradeport_140/levels/tradeport_140.dmm
  maps/sectors/tradeport_192/levels/tradeport_192.dmm
  maps/submaps/mountains/crashed_ufo.dmm
  maps/triumph/engines/rust.dmm
Labels: size/L

#6225 Baywallifies tether surface 2
  maps/tether/levels/surface2.dmm
Labels: size/XXL

#6228 Adapts Tether astroid level 2 for New walls and windows
  maps/tether/levels/station2.dmm
Labels: size/XXL
