Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2023-03, with the labels that each got.

#5113 multiz movement now hooks onTransitZ properly
  code/modules/multiz/movement.dm
Labels: size/XS

#5109 fixes slimebatons
  code/modules/xenobio/items/weapons.dm
Labels: size/XS

#5106 fixes department accounts on job.dm
  code/modules/jobs/job.dm
Labels: size/XS

#5110 fixes respirocytes
  code/modules/nifsoft/software/05_health.dm
Labels: size/XS

#5111 powercreeps the cult coats
  code/modules/clothing/suits/hooded.dm
Labels: size/XS

#5104 Updates Roach AI
  code/modules/mob/living/simple_mob/subtypes/animal/roach/roach.dm
Labels: size/XS

#5095 lore updates from sentre
  _maps/map_files/rift/rift-11-orbital.dmm
  citadel.dme
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/items/weapons/material/bats.dm
  code/game/objects/items/weapons/material/chainsaw.dm
  code/game/objects/items/weapons/material/knives.dm
  code/game/objects/items/weapons/material/material_armor.dm
  code/game/objects/items/weapons/material/misc.dm
  code/game/objects/items/weapons/material/swords.dm
  code/game/objects/items/weapons/material/twohanded.dm
  code/modules/projectiles/guns/energy.dm
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/particle.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/caseless.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  code/modules/projectiles/guns/projectile/revolver.dm
  code/modules/projectiles/guns/projectile/semiauto.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/reagents/reagent_containers/patch.dm
  code/modules/reagents/reagent_containers/syringes.dm
  code/modules/vore/fluffstuff/guns/cell_loaded/medigun.dm
  code/modules/vore/fluffstuff/guns/cell_loaded/medigun_cells.dm
  code/modules/vore/fluffstuff/guns/cell_loaded/revolver.dm
  code/modules/vore/fluffstuff/guns/cell_loaded/revolver_cells.dm
  code/modules/vore/fluffstuff/guns/nsfw.dm
Labels: size/L

#5077 Gets S_base to actually work :)
  code/game/dna/dna2.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/organs/external/_external_icons.dm
  code/modules/organs/organ.dm
  code/modules/preferences/preference_setup/general/03_body.dm
  code/modules/species/station/adherent.dm
  code/modules/species/station/xenomorph_hybrids/xeno_hybrids.dm
  code/modules/vore/eating/transforming_vr.dm
  icons/mob/species/xenohybrid/body.dmi
Labels: size/M

#5119 Couch Rotation
  _maps/map_files/rift/rift-06-surface3.dmm
Labels: size/L

#5117 [s] statpanel modification
  code/modules/client/statpanel.dm
Labels: size/XS

#5115 Documents spacemanDMM defines
  code/__DEFINES/spaceman_dmm.dm
Labels: size/M

#5102 fucky wucky
  citadel.dme
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/debug/fucky_wucky.dm
  code/modules/asset_cache/assets/debug/fucky_wucky.dm
  icons/runtime/assets/debug/fuckywucky.png
  sound/misc/fuckywucky.ogg
Labels: size/S

#5122 adds OOC bans + stubs for new banning backend
  citadel.dme
  code/__DEFINES/admin/bans.dm
  code/__DEFINES/controllers/persistence.dm
  code/__DEFINES/jobs/jobs.dm
  code/_globals/lists/clients.dm
  code/controllers/subsystem/persistence/objects/characters.dm
  code/modules/admin/DB ban/functions.dm
  code/modules/admin/admin.dm
  code/modules/admin/ban/ban_system.dm
  code/modules/admin/ban/role_ban.dm
  code/modules/admin/ban/server_ban.dm
  code/modules/admin/topic.dm
  code/modules/client/verbs/ooc.dm
  code/modules/mob/say.dm
Labels: size/L

#5125 tajaran lore update + adds yet another lore culture thing
  citadel.dme
  code/__DEFINES/preferences/data_keys_character.dm
  code/__DEFINES/species/species_flags.dm
  code/__DEFINES/turfs/type_generation.dm
  code/controllers/subsystem/characters/backgrounds.dm
  code/datums/mind.dm
  code/modules/lore_hardcoded/_hardcoded.dm
  code/modules/lore_hardcoded/citizenship.dm
  code/modules/lore_hardcoded/culture.dm
  code/modules/lore_hardcoded/religion.dm
  code/modules/lore_hardcoded/species/species.dm
  code/modules/lore_hardcoded/species/tajaran/_base.dm
  code/modules/lore_hardcoded/species/tajaran/citizenship.dm
  code/modules/lore_hardcoded/species/tajaran/culture.dm
  code/modules/lore_hardcoded/species/tajaran/origin.dm
  code/modules/lore_hardcoded/species/tajaran/religion.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/preferences/preference_setup/background/_background.dm
  code/modules/preferences/preference_setup/background/citizenship.dm
  code/modules/preferences/preference_setup/background/culture.dm
  code/modules/preferences/preference_setup/background/faction.dm
  code/modules/preferences/preference_setup/background/origin.dm
  code/modules/preferences/preference_setup/background/religion.dm
  code/modules/species/character_species.dm
  code/modules/species/outsider/vox.dm
  code/modules/species/species.dm
  code/modules/species/species_getters.dm
  code/modules/species/station/standard/tajaran.dm
Labels: size/L

#5131 Adds atom worth preliminary backend
  citadel.dme
  code/__DEFINES/economy/worth.dm
  code/game/atoms/atoms.dm
  code/game/objects/items.dm
  code/game/objects/objs.dm
  code/modules/economy/worth.dm
  code/modules/materials/_materials.dm
  code/modules/mob/mob_defines.dm
  code/modules/reagents/chemistry/reagent.dm
Labels: size/XL

#5129 adds a revolutionary ability to ACTUALLY build NTNet Quantum Relays.
  code/game/objects/items/circuitboards/machinery/research.dm
Labels: size/XS

#5128 sets the odds of gravity failure and solar storm events to 0
  code/modules/events/event_container.dm
  code/modules/events/event_container_vr.dm
Labels: size/XS

#5133 Fusion Cargo Fix
  code/modules/cargo/supplypacks/engineering.dm
Labels: size/S

#5130 Rad insulation for material walls
  code/game/objects/structures/girders.dm
  code/game/turfs/simulated/wall.dm
Labels: good first pr, size/XS

#5126 fixes hooded clothing not syncing color
  code/modules/clothing/suits/hooded.dm
Labels: size/XS

#5138 fixes lanterns
  code/game/objects/items/devices/flashlight.dm
  code/modules/mining/mine_items.dm
Labels: size/XS

#5135 Fix Keek's Offset Sprites Finally
  icons/mob/clothing/suits.dmi
  icons/mob/clothing/uniform.dmi
  icons/mob/clothing/uniform_rolled_down.dmi
Labels: size/XS

#5134 Widens pool rec room, adds a wrench, adds cooler weight lifters, adds…
  _maps/map_files/rift/rift-05-surface2.dmm
Labels: size/M

#5144 fixes a lot of gc issues with vines
  code/modules/hydroponics/spreading/spreading.dm
  code/modules/hydroponics/spreading/spreading_growth.dm
Labels: Priority 1: High, size/XS

#5136 Good Feng Shui in the Bar
  _maps/map_files/rift/rift-05-surface2.dmm
  _maps/map_files/rift/rift-06-surface3.dmm
Labels: size/M

#5050 RASC Spectre Robotic/Prosthetic Body (Updated Version)
  code/modules/organs/external/robolimbs.dm
  icons/mob/cyberlimbs/hoffman_tech/spectre.dmi
Labels: Merge Conflict, size/XS

#5114 Initial QOL changes for mirrors and their respective tools.
  _maps/map_files/rift/rift-05-surface2.dmm
  code/modules/resleeving/computers.dm
  code/modules/resleeving/mirror.dm
Labels: size/L

#5139 Wooden Leg Sprite Fix
  icons/mob/cyberlimbs/prosthesis/wooden.dmi
Labels: size/XS

#5149 Adds donor request
  code/modules/preferences/preference_setup/loadout/loadout_donator.dm
Labels: size/XS

#5127 Small changes to fix the never functional ATC Relay toggle.
  code/controllers/subsystem/emergency_shuttle.dm
  code/game/machinery/computer/communications.dm
  code/modules/busy_space/air_traffic.dm
  code/modules/security levels/security levels.dm
Labels: size/S

#5137 more cursed movespeed rebalancing (teshari buff), slightly, slightly buffs custom species trait selection temporarily
  code/__DEFINES/misc.dm
  code/modules/mob/living/carbon/human/traits/positive.dm
  code/modules/species/station/standard/teshari.dm
Labels: size/XS

#5146 Nose and head markings for humans
  code/modules/sprite_accessories/markings/_markings.dm
  icons/mob/sprite_accessories/markings.dmi
Labels: size/XS

#5142 Pasta found more weird shit in the attic
  code/modules/sprite_accessories/hair/_hair.dm
  icons/mob/human_face_m.dmi
Labels: size/L

#5148 Update synth_stuff.dm
  code/modules/sprite_accessories/markings/synth_stuff.dm
Labels: size/XS

#5140 LOOC bans now only effect players who are dead.
  code/modules/client/verbs/ooc.dm
Labels: size/XS

#5147 phoron tank dispenser added to engineering
  _maps/map_files/rift/rift-02-underground2.dmm
Labels: size/XS

#5008 Adds a dice roll emote
  code/modules/mob/living/carbon/human/emote.dm
Labels: Stale, size/M

#5159 Fixes donor request
  code/modules/preferences/preference_setup/loadout/loadout_donator.dm
Labels: size/XS

#5154 That looks good to me
  .github/workflows/stale.yml
Labels: size/XS

#5150 Thin colorable prosthetics2
  code/modules/organs/external/robolimbs.dm
  icons/mob/cyberlimbs/replikant/replikant.dmi
Labels: size/S

#5121 Fixes Proteans loosing their PAN when playing an RD
  code/modules/jobs/job_types/station/science/research_director.dm
Labels: size/XS

#5151 Xenohybrid Lore Background
  citadel.dme
  code/modules/lore_hardcoded/species/xenomorph_hybrid/_base.dm
  code/modules/lore_hardcoded/species/xenomorph_hybrid/citizenship.dm
  code/modules/lore_hardcoded/species/xenomorph_hybrid/culture.dm
  code/modules/lore_hardcoded/species/xenomorph_hybrid/origin.dm
  code/modules/lore_hardcoded/species/xenomorph_hybrid/religion.dm
Labels: size/M

#5164 Deleting those accidental map duplicates commited to master
  _maps/rift-07-west_base.dmm
  _maps/rift-08-west_deep.dmm
  _maps/rift-09-west_caves.dmm
  _maps/rift-10-west_plains.dmm
Labels: FUCK, size/XXL

#5165 fixes chemistry regressions
  code/modules/reagents/machinery/dispenser/dispenser.dm
  code/modules/reagents/machinery/dispenser/synthesizer.dm
  tgui/packages/tgui/interfaces/ChemDispenser.tsx
Labels: Priority 1: High, Fix, FUCK, size/M

#5157 Movement types
  code/__DEFINES/_flags/atom_flags.dm
  code/__DEFINES/traits/atoms.dm
  code/_globals/traits.dm
  code/datums/components/caltrop.dm
  code/datums/components/chasm.dm
  code/datums/components/footstep.dm
  code/datums/components/mood.dm
  code/datums/components/shrink.dm
  code/datums/elements/snail_crawl.dm
  code/game/atoms/atoms_movable.dm
  code/game/atoms/atoms_movable_movement.dm
  code/game/atoms/atoms_movement.dm
  code/game/turfs/turf_movement.dm
  code/modules/movespeed/movespeed_modifier.dm
  code/modules/multiz/open_turf.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/arc.dm
  code/modules/species/shadekin/shadekin_abilities.dm
  code/modules/unit_tests/projectiles.dm
Labels: size/XL

#5166 fixes inserting synthesizers into chemistry dispensers
  code/modules/reagents/machinery/dispenser/dispenser.dm
Labels: size/XS

#5161 fixes shotguns
  code/modules/projectiles/guns/projectile/shotgun.dm
Labels: size/XS

#5153 fixes smes construction deleting coils
  code/modules/power/smes/smes_construction.dm
Labels: size/XS

#5170 fixes ai interaction with dispensers
  code/modules/reagents/machinery/dispenser/dispenser.dm
Labels: size/XS

#5160 A bunch of sprites (labcoats, new jackets, new hairstyle)
  citadel.dme
  code/modules/clothing/head/hood.dm
  code/modules/clothing/suits/hooded.dm
  code/modules/clothing/suits/labcoat.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/accessories/clothing.dm
  code/modules/holidays/halloween_loadout.dm
  code/modules/preferences/preference_setup/loadout/loadout_role_restricted.dm
  code/modules/preferences/preference_setup/loadout/loadout_suit.dm
  code/modules/sprite_accessories/hair/_hair.dm
  icons/clothing/suit/coats/bladerunner.dmi
  icons/clothing/suit/coats/cyberpunk.dmi
  icons/clothing/suit/coats/furcoat.dmi
  icons/clothing/suit/coats/noble.dmi
  icons/clothing/suit/coats/overcoat.dmi
  icons/clothing/suit/coats/trenchcoat.dmi
  icons/clothing/suit/coats/triadkillers.dmi
  icons/clothing/suit/jackets/drive.dmi
  icons/clothing/suit/jackets/furbomber.dmi
  icons/clothing/suit/jackets/motojacket.dmi
  icons/clothing/suit/jackets/tunnelsnake.dmi
  icons/mob/clothing/head.dmi
  icons/mob/clothing/species/teshari/suits.dmi
  icons/mob/clothing/suits.dmi
  icons/mob/clothing/ties.dmi
  icons/mob/human_face_vr.dmi
  icons/mob/human_face_vr_add.dmi
  icons/mob/species/human/hair.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
Labels: size/L

#5175 Scattershot nerfs
  code/modules/projectiles/projectile/scatter.dm
Labels: size/S

#5162 Subsystem Sort Fix + Documenting
  code/controllers/controller.dm
  code/controllers/failsafe.dm
  code/controllers/globals.dm
  code/controllers/master.dm
  code/controllers/subsystem.dm
Labels: size/XL

#5174 Buffs Excav Laser Module
  code/modules/projectiles/projectile/beam/beams.dm
Labels: size/XS

#5163 maybe fixes statpanel clicking to be better at it
  code/modules/admin/verbs/SDQL2/SDQL_2.dm
  html/statbrowser.html
Labels: size/M

#5167 fixes not being able to swap back onto the original title of a job
  code/game/machinery/computer/timeclock_vr.dm
  code/modules/jobs/job.dm
Labels: size/S

#5169 fixes farmbots
  code/modules/mob/living/bot/farmbot.dm
Labels: size/S

#5171 fixes chemistry dispenser macros
  code/modules/reagents/machinery/dispenser/dispenser.dm
  tgui/packages/tgui/interfaces/ChemDispenser.tsx
Labels: size/M

#5173 Disables most of modular weaponry.
  code/modules/research/designs/weapons.dm
Labels: size/M

#5177 fixes gun firemode toggles
  code/modules/projectiles/guns/ballistic.dm
  code/modules/projectiles/guns/projectile/automatic.dm
Labels: size/XS

#5185 fixes costless synth
  code/modules/reagents/machinery/dispenser/supply.dm
Labels: Priority 1: High, size/XS

#5152 reformats PDA spawning to check more than one place before deleting the PDA
  code/datums/outfits/outfit.dm
Labels: size/S

#5183 fixes robot interaction with dispensers
  code/modules/reagents/machinery/dispenser/dispenser.dm
Labels: size/XS

#5181 In The News 2/13/2023
  code/modules/lore_codex/news_data/main.dm
Labels: size/L

#5155 Blueshields
  _maps/map_files/rift/rift-06-surface3.dmm
  citadel.dme
  code/__DEFINES/access.dm
  code/__DEFINES/jobs/jobs.dm
  code/game/area/Space Station 13 areas.dm
  code/game/landmarks/spawnpoint/station/jobs.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/gps.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/id_cards/sprite_stacks_cit.dm
  code/game/objects/items/id_cards/station_ids.dm
  code/game/objects/items/storage/backpack.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/head/jobs.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/accessories/oricon.dm
  code/modules/clothing/under/accessories/torch.dm
  code/modules/clothing/under/oricon/crew.dm
  code/modules/jobs/job_types/station/command/blueshield.dm
  code/modules/jobs/jobs.dm
  icons/clothing/uniform/rank/utility.dmi
  icons/clothing/uniform/rank/utility/blueshield.dmi
  icons/mob/clothing/back.dmi
  icons/mob/clothing/head.dmi
  icons/mob/clothing/suits.dmi
  icons/mob/clothing/suits_solgov.dmi
  icons/mob/items/lefthand_storage.dmi
  icons/mob/items/righthand_storage.dmi
  icons/obj/clothing/backpack.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/suits_solgov.dmi
  icons/screen/atom_hud/job.dmi
Labels: size/XL

#5168 Matterforge Recipe expansion
  code/modules/power/singularity/particle_accelerator/particle_smasher.dm
Labels: size/L

#5192 fixes gunboxes
  code/game/objects/items/gunbox.dm
Labels: size/S

#5187 fixes dispensers ignoring charge setting
  code/modules/reagents/machinery/dispenser/dispenser.dm
Labels: size/XS

#5193 fixes MMI
  code/modules/mob/living/carbon/brain/MMI.dm
Labels: size/XS

#5197 Adds Round ID to jsonstatus
  code/datums/world_topic.dm
Labels: size/XS

#5189 Craftable Dataknife
  code/datums/components/crafting/recipes/recipes_weapon_and_ammo.dm
Labels: size/S

#5195 Ports more jackets from Eris, fixes bugs with existing ones
  code/modules/clothing/suits/labcoat.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/preferences/preference_setup/loadout/loadout_suit.dm
  icons/clothing/suit/armor/traumateam.dmi
  icons/clothing/suit/coats/cyberpunk.dmi
  icons/clothing/suit/coats/labcoats.dmi
  icons/clothing/suit/coats/onestar.dmi
  icons/clothing/suit/jackets/bomj.dmi
  icons/clothing/suit/jackets/drive.dmi
  icons/clothing/suit/jackets/jamrock.dmi
  icons/clothing/suit/jackets/khaki.dmi
  icons/clothing/suit/jackets/punkvest.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/ties.dmi
Labels: size/L

#5145 [Ready for review] Adherent are so broken it's unbelievable.
  _maps/map_files/rift/rift-03-underground1.dmm
  code/__DEFINES/species/species_flags.dm
  code/game/machinery/vending.dm
  code/game/objects/items/devices/multitool.dm
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/storage/toolbox.dm
  code/game/objects/items/tools/crowbar.dm
  code/game/objects/items/tools/screwdriver.dm
  code/game/objects/items/tools/weldingtool.dm
  code/game/objects/items/tools/wirecutters.dm
  code/game/objects/items/tools/wrench.dm
  code/modules/mob/living/living_defense.dm
  code/modules/organs/external/species/adherent.dm
  code/modules/species/station/adherent.dm
  icons/obj/clothing/belts.dmi
  icons/obj/crystal_tools.dmi
  icons/obj/storage.dmi
  icons/obj/vending.dmi
Labels: size/L

#5199 fixes mediguns
  code/modules/vore/fluffstuff/guns/cell_loaded/cell_loaded.dm
Labels: size/XS

#5198 fixes syringes
  code/modules/reagents/reagent_containers/syringes.dm
Labels: size/XS

#5190 whitelists scori
  code/modules/language/languages/species/scori.dm
Labels: size/XS

#5211 *fullsalute emote
  code/modules/mob/living/carbon/human/emote.dm
  sound/misc/salute.ogg
Labels: size/S

#5200 quick and dirty fix to making stuff tweakable
  code/modules/preferences/preference_setup/loadout/loadout_gloves.dm
  code/modules/preferences/preference_setup/loadout/loadout_role_restricted.dm
  code/modules/preferences/preference_setup/loadout/loadout_shoes.dm
  code/modules/preferences/preference_setup/loadout/loadout_uniform.dm
Labels: size/M

#5191 Ports folding chairs and chair towers from CM13
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  icons/mob/items/lefthand_material.dmi
  icons/mob/items/righthand_material.dmi
  icons/obj/furniture.dmi
  icons/obj/furniture_vr.dmi
  icons/obj/objects.dmi
  icons/obj/weapons.dmi
  sound/effects/metal_chair_clang.ogg
  sound/effects/metal_chair_crash.ogg
  sound/effects/metal_chair_slam.ogg
Labels: size/L

#5201 nerfs pain / health slowdown
  code/modules/mob/living/carbon/human/human_movement.dm
Labels: size/XS

#5207 fixes dispenser bashing
  code/modules/reagents/machinery/dispenser/dispenser.dm
Labels: size/XS

#5206 fixes inducer rates
  code/game/objects/items/inducer.dm
Labels: size/XS

#5205 fixes combat shields
  code/modules/shieldgen/directional_shield.dm
Labels: size/XS

#5196 Update Shadekin energy regenerations
  code/modules/species/shadekin/shadekin_traits.dm
Labels: size/M

#5204 Creates and adds the Mining Carbine
  code/modules/clothing/suits/hooded.dm
  code/modules/mining/ore_redemption_machine/equipment_vendor.dm
  code/modules/projectiles/guns/energy/nuclear.dm
  code/modules/projectiles/projectile/beam/beams.dm
  code/modules/projectiles/projectile/scatter.dm
Labels: size/M

#5218 fixes EMT labcoat missing icon
  icons/clothing/suit/coats/labcoats.dmi
Labels: size/XS

#5208 Greyscaled Human Torso Touchup
  icons/mob/species/human/body_greyscale.dmi
Labels: size/XS

#5214 Minor Tweaks to Horror Aura
  code/datums/components/horror_aura.dm
Labels: size/S

#5212 Blueshield HUD icon fix
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  icons/screen/atom_hud/job.dmi
Labels: size/XS

#5217 Fixes: Spray bottles, Pepperspray and Super Soakers
  code/modules/reagents/reagent_containers/spray.dm
Labels: size/XS

#5179 makes AI experience not fullbright and fixes AI runtiming because they receive a mirror implant
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/robot/life.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/resleeving/mirror.dm
Labels: size/M

#5227 fixes projectiles adding overlays to mined turfs
  code/modules/mining/mine_turfs.dm
Labels: size/XS

#5219 removes AI-controlled mob vore
  code/modules/mob/living/simple_mob/simple_mob_vr.dm
  code/modules/mob/living/simple_mob/subtypes/animal/space/gaslamp_vr.dm
  code/modules/species/protean/protean_blob.dm
  code/modules/vore/eating/living_vr.dm
  code/modules/vore/eating/simple_animal_vr.dm
  code/modules/vore/eating/vore_vr.dm
  code/modules/vore/eating/vorepanel_vr.dm
Labels: size/M

#5223 fixes something with coolant tanks
  code/modules/xenoarcheaology/tools/coolant_tank.dm
Labels: Priority 0: CRITICAL, size/XS

#5215 removes off duty from command
  code/modules/jobs/job_types/station/offduty/command.dm
Labels: size/XS

#5226 makes xenomorph tails properly colorable
  code/modules/sprite_accessories/tail/species/xenomorph.dm
  icons/effects/species_tails_vr.dmi
Labels: size/XS

#5178 Under construction telescience facility, Secure science storage
  _maps/map_files/rift/rift-02-underground2.dmm
  _maps/map_files/rift/rift-03-underground1.dmm
  _maps/map_files/rift/rift-04-surface1.dmm
  _maps/map_files/rift/rift-05-surface2.dmm
  _maps/map_files/rift/rift-06-surface3.dmm
  code/game/area/Space Station 13 areas.dm
Labels: size/XXL

#5229 fixes mousetraps
  code/modules/assembly/mousetrap.dm
Labels: size/XS

#5213 you can now do surgery without a literal surgical table / roller bed. synth repairs can now be done anywhere.
  code/game/objects/structures/stool_bed_chair_nest/bed.dm
  code/modules/surgery/robotics.dm
  code/modules/surgery/surgery.dm
Labels: size/S

#5230 fixes lighters
  code/game/objects/items/weapons/cigs_lighters.dm
Labels: size/S

#5224 stops accidental world reboots
  code/game/world.dm
Labels: size/XS

#5225 fixes syringes actually
  code/modules/reagents/reagent_containers/syringes_vr.dm
Labels: size/XS

#5220 Cyborg-KA
  code/modules/mob/living/silicon/robot/robot_modules/station/cargo.dm
Labels: size/XS

#5231 tunes up chem ui
  tgui/packages/tgui/interfaces/ChemDispenser.tsx
Labels: size/L

#5239 proteans now always drop brains on death, fixes runtime
  code/modules/species/protean/protean_species.dm
Labels: size/XS

#5237 fixes windoors/whatever blocking particles
  code/modules/power/singularity/particle_accelerator/particle.dm
Labels: size/S

#5236 ports wolf tail and labrador ears from main
  code/modules/sprite_accessories/ears/animal/canid.dm
  code/modules/sprite_accessories/tail/canid.dm
  icons/mob/sprite_accessories/ears.dmi
  icons/mob/sprite_accessories/tails.dmi
Labels: size/S

#5243 fixes holodeck basketball hoop issue
  code/modules/holodeck/HolodeckObjects.dm
Labels: size/XS

#5244 fixes chem grenade beaker removal
  code/game/objects/items/weapons/grenades/chem_grenade.dm
Labels: size/XS

#5246 fixes magclaws
  code/modules/clothing/shoes/magboots.dm
Labels: size/XS

#5248 Fixes *roll so you can't roll zeroes anymore.
  code/modules/mob/living/carbon/human/emote.dm
Labels: size/XS

#5238 makes painkillers not stack on themselves
  code/game/gamemodes/changeling/powers/epinephrine_overdose.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Medicine.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Toxins.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Topical.dm
Labels: size/M

#5245 fixes accelerated particles but actually
  code/modules/power/singularity/particle_accelerator/particle.dm
Labels: size/S

#5253 fixes matrix orientation
  code/datums/browser/color_matrix_picker.dm
Labels: size/S

#5221 radiation v3
  citadel.dme
  code/__DEFINES/dcs/signals/signals_atom/signals_atom_radiation.dm
  code/__DEFINES/dcs/signals/signals_atom/signals_atom_x_act.dm
  code/__DEFINES/radiation/simulation.dm
  code/__HELPERS/unsorted/radiation.dm
  code/controllers/subsystem/radiation.dm
  code/datums/components/atoms/latently_radioactive.dm
  code/datums/components/atoms/radiation_listener.dm
  code/datums/components/atoms/radioactive.dm
  code/datums/components/rad_insulation.dm
  code/datums/radiation_wave.dm
  code/game/atoms/atom.dm
  code/game/atoms/movable/vv.dm
  code/game/objects/effects/map_effects/radiation_emitter.dm
  code/game/objects/items/devices/geiger.dm
  code/game/turfs/simulated.dm
  code/game/turfs/turf.dm
  code/game/turfs/turf_movement.dm
  code/modules/mob/living/defense.dm
  code/modules/mob/living/living.dm
  code/modules/multiz/zmimic/mimic_turf.dm
Labels: size/XL

#5256 Nanite chamber room
  code/game/area/Space Station 13 areas.dm
  code/game/objects/structures/signs.dm
  icons/obj/decals.dmi
  maps/map_files/rift/rift-03-underground1.dmm
Labels: size/L
