Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2023-01, with the labels that each got.

#4921 fixes snow memory leak
  code/game/turfs/simulated/floors/snow.dm
Labels: size/S

#4915 overmap no longer uses a list for movement speed
  citadel.dme
  code/__DEFINES/overmaps/misc.dm
  code/__DEFINES/overmaps/overmap.dm
  code/controllers/subsystem/parallax.dm
  code/modules/events/meteors.dm
  code/modules/overmap/entity/physics.dm
  code/modules/overmap/ships/computers/helm.dm
  code/modules/overmap/ships/ship.dm
  code/modules/tgui/modules/overmap.dm
Labels: size/L

#4910 fixes bodytypes struct double compiles runtiming
  code/__HELPERS/datastructs/bodytypes.dm
Labels: size/XS

#4919 More Workflow stuff
  .github/guides/MAPS.md
  .github/workflows/auto_changelong.yml
  .github/workflows/ci_suite.yml
  .github/workflows/compile_changelogs.yml
  .github/workflows/conflicts.yml
  .github/workflows/update_tgs_dmapi.yml
  _maps/_basemap.dm
  tools/validate_dme.py
Labels: Priority 1: High, size/L

#4925 ohfuck
  .github/workflows/ci_suite.yml
Labels: Priority 0: CRITICAL, size/XS

#4926 Fixes CI Suite
  .github/workflows/ci_suite.yml
Labels: size/S

#4927 Fixes pathfinder PDA bug
  code/game/objects/items/devices/PDA/PDA.dm
Labels: size/XS

#4923 Psychic Whisper extention
  code/modules/mob/living/carbon/human/human_powers.dm
Labels: size/S

#4922 Z-Mimic: Fix runtime w/ upward movement + AO fix
  code/___compile_options.dm
  code/modules/multiz/zmimic/mimic_movable.dm
Labels: size/XS

#4924 Soothes the Teshari Hivemind
  code/modules/materials/material_recipes.dm
Labels: size/XS

#4887 zas fixes, movement fixes, tweaks, etc
  citadel.dme
  code/__DEFINES/_flags/atom_flags.dm
  code/__DEFINES/atmospherics/gasmixtures.dm
  code/controllers/subsystem/job/_legacy_job_stuff.dm
  code/game/machinery/atmoalter/pump.dm
  code/game/objects/structures.dm
  code/game/objects/structures/ledges.dm
  code/game/objects/structures/plasticflaps.dm
  code/game/objects/structures/railing.dm
  code/modules/atmospherics/gasmixtures/gas_mixture.dm
  code/modules/atmospherics/gasmixtures/transfer_helpers.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/movement.dm
  code/modules/tables/tables.dm
Labels: Priority 1: High, size/XL

#4928 Updating Update Paths.bat
  tools/UpdatePaths/__main__.py
  tools/UpdatePaths/readme.md
  tools/UpdatePaths/scripts/old/apc_pixel_offsets.txt
  tools/UpdatePaths/scripts/old/clothingunderrepath.txt
  tools/UpdatePaths/scripts/old/cornersfix.txt
  tools/UpdatePaths/scripts/old/turfs2decals.txt
Labels: size/L

#4913 Changing Almost all windows to window Spawners, fixes a few map issues I saw, etc
  _maps/map_files/rift/rift-02-underground2.dmm
  _maps/map_files/rift/rift-03-underground1.dmm
  _maps/map_files/rift/rift-04-surface1.dmm
  _maps/map_files/rift/rift-05-surface2.dmm
  _maps/map_files/rift/rift-06-surface3.dmm
  _maps/map_files/rift/rift-07-west_base.dmm
  _maps/map_files/rift/rift-08-west_deep.dmm
  _maps/map_files/rift/rift-09-west_caves.dmm
  _maps/map_files/rift/rift-10-west_plains.dmm
  _maps/map_files/rift/rift-11-orbital.dmm
Labels: size/XXL

#4934 fixes beartraps not allowing unbuckle & nanoui runtime spam
  code/game/objects/items/weapons/traps.dm
  code/modules/nano/interaction/default.dm
Labels: size/S

#4907 Bitmask Smoothed Walls
  citadel.dme
  code/controllers/subsystem/materials.dm
  code/game/objects/explosion_recursive.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/map_blocker.dm
  code/game/objects/structures/props/pushpuzzle.dm
  code/game/objects/structures/props/puzzledoor.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/misc/fancy_shuttles.dm
  code/game/turfs/simulated/wall.dm
  code/game/turfs/simulated/wall_attacks.dm
  code/game/turfs/simulated/wall_composition.dm
  code/game/turfs/simulated/wall_icon.dm
  code/game/turfs/simulated/wall_types.dm
  code/game/turfs/simulated/walls/dungeon.dm
  code/game/turfs/unsimulated.dm
  code/modules/materials/_materials.dm
  code/modules/materials/definitions/debug.dm
  code/modules/materials/definitions/special.dm
  code/modules/materials/definitions/unsorted_materials.dm
  code/modules/materials/material_recipes.dm
  code/modules/mining/mine_turfs.dm
  code/modules/tables/presets.dm
  code/modules/tables/tables.dm
  icons/obj/tables.dmi
  icons/turf/wall_masks.dmi
  icons/turf/wall_masks_old.dmi
  icons/turf/wall_masks_vr.dmi
  icons/turf/walls.dmi
  icons/turf/walls/_construction_overlays.dmi
  icons/turf/walls/_previews.dmi
  icons/turf/walls/bone.dmi
  icons/turf/walls/brick.dmi
  icons/turf/walls/cult.dmi
  icons/turf/walls/curvy.dmi
  icons/turf/walls/damage_masks.dmi
  icons/turf/walls/debug.dmi
  icons/turf/walls/diona.dmi
  icons/turf/walls/dungeon.dmi
  icons/turf/walls/hull.dmi
  icons/turf/walls/jaggy.dmi
  icons/turf/walls/log.dmi
  icons/turf/walls/metal.dmi
  icons/turf/walls/reinforced_cult.dmi
  icons/turf/walls/reinforced_debug.dmi
  icons/turf/walls/reinforced_mesh.dmi
  icons/turf/walls/reinforced_metal.dmi
  icons/turf/walls/reinforced_solid.dmi
  icons/turf/walls/reinforced_stone.dmi
  icons/turf/walls/resin.dmi
  icons/turf/walls/rock.dmi
  icons/turf/walls/rock_mossy.dmi
  icons/turf/walls/solid.dmi
  icons/turf/walls/stone.dmi
  icons/turf/walls/wood.dmi
Labels: size/XXL

#4937 gives robot eal hardcoded again
  code/modules/mob/living/silicon/robot/robot.dm
Labels: size/XS

#4936 [Ready for Merge] Minor xenochimera adjustments
  .github/CODEOWNERS
  code/modules/mob/living/carbon/human/human_powers.dm
  code/modules/species/xenochimera/xenochimera.dm
Labels: size/S

#4931 optimizing turf/Initialize(), ChangeTurf, and assemble_baseturfs
  code/__HELPERS/lists/string_lists.dm
  code/controllers/subsystem/zmimic.dm
  code/game/turfs/baseturfs.dm
  code/game/turfs/change_turf.dm
  code/game/turfs/simulated/floor_types.dm
  code/game/turfs/simulated/misc/fancy_shuttles.dm
  code/game/turfs/turf.dm
  code/game/turfs/unsimulated.dm
  code/modules/mapping/map_helpers/baseturf.dm
  code/modules/multiz/open_turf.dm
Labels: FUCK, size/L

#4932 buffs radiation
  code/__DEFINES/radiation/simulation.dm
Labels: size/XS

#4945 Altevians are not canon, why didn't anybody replace them?
  code/modules/busy_space/organizations.dm
Labels: size/M

#4944 Lythios Event Weathers
  code/modules/maps/weather/rift_lythios-43c.dm
Labels: size/M

#4942 Adds a couple of halo "ears"
  citadel.dme
  code/modules/sprite_accessories/ears/fictional/halo.dm
  icons/mob/sprite_accessories/ears.dmi
Labels: size/M

#4941 tgui_input_list for the loadout
  code/modules/preferences/preference_setup/general/01_basic.dm
  code/modules/preferences/preference_setup/general/03_body.dm
  code/modules/preferences/preference_setup/general/04_equipment.dm
  code/modules/preferences/preference_setup/general/05_background.dm
  code/modules/preferences/preference_setup/global/01_ui.dm
  code/modules/preferences/preference_setup/vore/01_ears.dm
  code/modules/preferences/preference_setup/vore/03_egg.dm
  code/modules/preferences/preference_setup/vore/08_traits.dm
  code/modules/preferences/preference_setup/vore/10_misc.dm
Labels: size/L

#4938 Fix species display in character directory
  code/game/verbs/character_directory.dm
Labels: size/XS

#4909 Operation Waterlogged Sparrow (Introduction of Pirate Ghost Role)
  _maps/map_levels/192x192/piratebase.dmm
  _maps/submaps/level_specific/class_h/covert_post.dmm
  _maps/submaps/level_specific/class_h/desertsaloon.dmm
  _maps/submaps/level_specific/class_h/highnoonH.dmm
  _maps/submaps/level_specific/class_p/HeadscientistHQ.dmm
  citadel.dme
  code/controllers/communications.dm
  code/game/area/Off Station Areas.dm
  code/game/machinery/suit_storage/suit_cycler.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/devices/radio/intercom.dm
  code/game/objects/items/id_cards/station_ids.dm
  code/game/turfs/simulated/flooring/flooring_premade.dm
  code/modules/clothing/spacesuits/void/outsider.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/ghostroles/role.dm
  code/modules/ghostroles/roles/ashlander.dm
  code/modules/ghostroles/roles/pirate.dm
  code/modules/jobs/access_datum.dm
  code/modules/maps/README.md
  code/modules/maps/lateload/generic/space_lateload.dm
  code/modules/maps/overmap/planets/_lythios43c.dm
  code/modules/maps/overmap/space/pirate_base.dm
  code/modules/maps/templates/misc_presets/rift_shuttle_landmarks.dm
  code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/electric.dm
  code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/giant_spider_vr.dm
  code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/ion.dm
  code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/nurse.dm
  code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/webslinger.dm
  code/modules/species/shadekin/shadekin.dm
  icons/mob/clothing/uniform.dmi
  icons/obj/card_cit.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/spacesuits.dmi
  icons/obj/clothing/suits.dmi
  icons/obj/clothing/uniforms.dmi
  icons/obj/radio.dmi
  icons/obj/structures.dmi
  maps/nsv_triumph/triumph_defines.dm
  maps/nsv_triumph/triumph_overmap.dm
  maps/overmap/shuttles/pirateskiff.dm
  maps/overmap/shuttles/skipjack.dm
  maps/rift/rift_defines.dm
  maps/tether/tether_defines.dm
Labels: size/XXL

#4930 reworks gps
  citadel.dme
  code/__DEFINES/dcs/signals/signals_atom/signals_atom_movable.dm
  code/__HELPERS/mobs.dm
  code/__HELPERS/text.dm
  code/_onclick/hud/objects/waypoint_tracker.dm
  code/_onclick/observer.dm
  code/controllers/subsystem/mapping/_mapping.dm
  code/controllers/subsystem/mapping/_shims.dm
  code/controllers/verbs.dm
  code/datums/components/gps.dm
  code/datums/components/gps_signal.dm
  code/datums/components/spooky.dm
  code/datums/datum.dm
  code/game/atoms/atoms.dm
  code/game/atoms/atoms_movable_vv.dm
  code/game/objects/items/devices/gps.dm
  code/game/objects/items/weapons/material/knives.dm
  code/game/world.dm
  code/modules/mob/vv.dm
  code/modules/preferences/preference_setup/general/01_basic.dm
  code/modules/preferences/preference_setup/general/03_body.dm
  code/modules/preferences/preference_setup/preference_item_new.dm
  code/modules/species/species.dm
  icons/screen/objects/arrows_32.dmi
  icons/screen/objects/arrows_48.dmi
  icons/screen/objects/compass_32.dmi
  tgui/packages/tgui/interfaces/Gps.js
  tgui/packages/tgui/interfaces/Gps.tsx
  tgui/packages/tgui/interfaces/SpeciesPicker.tsx
Labels: size/XXL

#4949 Replaces DSI with OSS
  code/modules/organs/robolimbs.dm
Labels: size/M

#4956 yandere developer
  code/game/objects/items/stacks/marker_beacons.dm
Labels: Priority 0: CRITICAL, size/XS

#4935 IN_MAP_EDITOR
  code/__DEFINES/_planes+layers.dm
  code/___compile_options.dm
  code/game/machinery/doors/firedoor.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/flooring/flooring_decals.dm
  code/game/turfs/simulated/wall.dm
  code/modules/atmospherics/machinery/pipes/cap.dm
  code/modules/atmospherics/machinery/pipes/manifold4w.dm
  code/modules/atmospherics/machinery/pipes/pipe_base.dm
  code/modules/atmospherics/machinery/pipes/simple.dm
  code/modules/power/cable_heavyduty.dm
  code/modules/recycling/disposal.dm
Labels: size/M

#4951 Z-Mimic: Add missing deletion hook
  code/controllers/subsystem/zmimic.dm
  code/game/atoms/atoms_movable.dm
Labels: size/XS

#4947 hot cheetoes v4: finally properly merged edition
  code/game/machinery/vending.dm
  code/game/objects/items/trash.dm
  code/game/objects/structures/loot_piles.dm
  code/modules/economy/price_list.dm
  code/modules/examine/descriptions/food.dm
  code/modules/food/food/snacks.dm
  icons/obj/food.dmi
  icons/obj/trash.dmi
Labels: size/S

#4959 Make blood overlay caching not completely insane
  code/game/objects/items.dm
Labels: size/S

#4955 Adds an adminbus event
  citadel.dme
  code/modules/events/event_container_vr.dm
  code/modules/events/infestation.dm
  code/modules/events/xenoinfestation.dm
  code/modules/mob/living/simple_mob/subtypes/animal/space/alien.dm
Labels: size/L

#4953 Fixes Hardwood tables
  code/modules/materials/definitions/unsorted_materials.dm
Labels: size/XS

#4950 Gps hotfix for tracking
  code/_onclick/hud/objects/waypoint_tracker.dm
  code/game/objects/items/devices/gps.dm
Labels: size/XS

#4948 SSoverlays tweaks + audit
  code/__HELPERS/icon_smoothing.dm
  code/_onclick/hud/radial.dm
  code/_onclick/telekinesis.dm
  code/controllers/subsystem/overlays.dm
  code/game/atoms/atoms.dm
  code/game/atoms/atoms_movable.dm
  code/game/machinery/computer/computer.dm
  code/game/machinery/doors/brigdoors.dm
  code/game/machinery/newscaster.dm
  code/game/machinery/nuclear_bomb.dm
  code/game/machinery/status_display_ai.dm
  code/game/objects/items/devices/aicard.dm
  code/game/objects/items/devices/t_scanner.dm
  code/game/objects/items/storage/_storage.dm
  code/game/objects/items/storage/fancy.dm
  code/game/objects/items/storage/firstaid.dm
  code/game/objects/items/storage/misc.dm
  code/game/objects/items/storage/secure.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/lightpost.dm
  code/game/objects/structures/railing.dm
  code/modules/atmospherics/machinery/components/omni_devices/omni_base.dm
  code/modules/atmospherics/machinery/pipes/cap.dm
  code/modules/mob/living/bot/medibot.dm
  code/modules/mob/typing_indicator.dm
  code/modules/multiz/zmimic/mimic_movable.dm
  code/modules/resleeving/sleevecard.dm
  code/modules/shieldgen/energy_shield.dm
  code/modules/xenoarcheaology/misc.dm
  code/modules/xenoarcheaology/tools/artifact_analyser.dm
  code/modules/xenoarcheaology/tools/geosample_scanner.dm
Labels: size/XL

#4958 makes subtleRs distinct, removes spawn, fixes an obscure xenochimera bug
  code/modules/mob/say_vr.dm
  code/modules/species/xenochimera/xenochimera.dm
Labels: size/M

#4957 Fixes Wall Edges
  code/__DEFINES/_planes+layers.dm
  code/game/turfs/simulated/walls/dungeon.dm
  code/modules/mining/mine_turfs.dm
Labels: size/S

#4963 Fixes mineturfs not updating Turf AO
  code/modules/mining/mine_turfs.dm
Labels: size/XS

#4961 gives human subspecies the same bodytype as human
  code/modules/species/station/standard/human.dm
Labels: size/XS

#4960 Adds Three Afterlife Drinks
  code/game/machinery/vending.dm
  code/modules/economy/price_list.dm
  code/modules/food/drinkingglass/metaglass.dm
  code/modules/food/food/cans.dm
  code/modules/reagents/Drink-Recipes.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Food-Drinks.dm
  icons/obj/drinks.dmi
Labels: size/L

#4939 Adds ERT Shuttle & CentCom Landmark, Repaths & Adds some LMGs, Adds more NT Special Snowflake Gear
  _maps/away_missions/archive/challenge.dmm
  _maps/map_files/rift/rift-06-surface3.dmm
  _maps/map_files/rift/rift-11-orbital.dmm
  _maps/templates/admin/dhael_centcom.dmm
  _maps/templates/admin/ert.dmm
  _maps/templates/admin/ert_base.dmm
  _maps/templates/shuttles/overmaps/generic/cruise_ship.dmm
  _maps/templates/shuttles/overmaps/generic/cruiser.dmm
  _maps/templates/shuttles/overmaps/generic/shelter_6.dmm
  citadel.dme
  code/datums/outfits/spec_op.dm
  code/game/antagonist/outsider/commando.dm
  code/game/area/Space Station 13 areas.dm
  code/game/objects/random/misc.dm
  code/modules/awaymissions/loot_vr.dm
  code/modules/cargo/supplypacks/recreation.dm
  code/modules/clothing/under/syndicate.dm
  code/modules/maps/lateload/generic/space_lateload.dm
  code/modules/maps/overmap/planets/_lythios43c.dm
  code/modules/maps/overmap/space/centcom.dm
  code/modules/maps/templates/misc_presets/rift_shuttle_landmarks.dm
  code/modules/maps/templates/shuttles/admin_spawn/cruise_ship.dm
  code/modules/mob/living/simple_mob/subtypes/humanoid/mercs/mercs.dm
  code/modules/projectiles/guns/energy/laser.dm
  code/modules/projectiles/guns/energy/nuclear.dm
  code/modules/projectiles/guns/energy/pulse.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/revolver.dm
  code/modules/projectiles/magazines/unsorted.dm
  code/modules/shuttles/landmarks.dm
  icons/mob/clothing/back.dmi
  icons/mob/items/lefthand_guns.dmi
  icons/mob/items/righthand_guns.dmi
  icons/obj/ammo.dmi
  icons/obj/gun/ballistic.dmi
  icons/obj/gun/energy.dmi
  icons/obj/gun/unused.dmi
  icons/obj/toy.dmi
  maps/overmap/shuttles/specialops.dm
  maps/rift/rift_defines.dm
Labels: size/XXL

#4965 Overlays fixes
  code/controllers/subsystem/overlays.dm
Labels: size/XS

#4966 Busy_space code is dumb and requires an empty space coded in
  code/modules/busy_space/organizations.dm
Labels: size/XS

#4968 ghost tag improvement
  code/game/atoms/atoms_movable.dm
Labels: size/XS

#4969 Bugfix 98
  code/game/objects/items/devices/gps.dm
  code/game/objects/items/stacks/stack.dm
  code/modules/organs/internal/species/alraune.dm
  tgui/packages/tgui/interfaces/Gps.tsx
  tgui/packages/tgui/interfaces/OvermapHelm.js
Labels: size/L

#4971 fixes infinite loop in overmaps
  code/modules/mob/living/carbon/human/life.dm
  code/modules/overmap/ships/computers/ship.dm
Labels: Test Merge Candidate, size/S

#4973 fixes throwing people through doors
  code/game/machinery/doors/door.dm
Labels: size/XS

#4974 fixes movement cost
  code/game/turfs/simulated/floors/lava.dm
  code/game/turfs/simulated/floors/snow.dm
  code/game/turfs/simulated/floors/water.dm
  code/game/turfs/turf.dm
  code/modules/mob/living/carbon/human/human_movement.dm
  code/modules/mob/living/simple_mob/simple_mob.dm
  code/modules/multiz/open_turf.dm
Labels: size/M

#4980 Adds coffee-related canned drinks. Tweaks water bottle description.
  code/game/machinery/vending.dm
  code/modules/economy/price_list.dm
  code/modules/food/food/cans.dm
  code/modules/reagents/Drink-Recipes.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Food-Drinks.dm
  icons/obj/drinks.dmi
Labels: size/M

#4972 adds a medical beret
  code/modules/clothing/head/jobs.dm
  code/modules/preferences/preference_setup/loadout/loadout_head.dm
  icons/mob/clothing/head.dmi
  icons/mob/items/lefthand_hats.dmi
  icons/mob/items/righthand_hats.dmi
  icons/obj/clothing/hats.dmi
Labels: size/S

#4954 Cleaned/Merged turf DMI files
  _maps/away_missions/140x140/zoo.dmm
  _maps/away_missions/archive/labyrinth.dmm
  _maps/map_files/rift/rift-11-orbital.dmm
  _maps/map_files/tether/tether_misc.dmm
  _maps/map_files/triumph/triumph-01-deck1.dmm
  _maps/map_files/triumph/triumph-05-flagship.dmm
  _maps/map_files/triumph/triumph_misc.dmm
  _maps/map_levels/140x140/Class_P.dmm
  _maps/map_levels/192x192/Class_P.dmm
  _maps/submaps/level_specific/class_p/ruins1.dmm
  _maps/submaps/level_specific/class_p/ruins2.dmm
  _maps/submaps/level_specific/class_p/ruins5.dmm
  _maps/templates/admin/dhael_centcom.dmm
  _maps/templates/admin/thunderdome.dmm
  _maps/templates/admin/wizard.dmm
  _maps/templates/archive/tradeship.dmm
  citadel.dme
  code/__DEFINES/_planes+layers.dm
  code/__DEFINES/turfs.dm
  code/game/objects/structures/charge_pylon.dm
  code/game/objects/structures/signs.dm
  code/game/turfs/simulated/floor.dm
  code/game/turfs/simulated/floor_attackby.dm
  code/game/turfs/simulated/floor_damage.dm
  code/game/turfs/simulated/floor_icon.dm
  code/game/turfs/simulated/floor_types_eris.dm
  code/game/turfs/simulated/flooring/_flooring.dm
  code/game/turfs/simulated/flooring/flooring_decals.dm
  code/game/turfs/simulated/flooring/flooring_premade.dm
  code/game/turfs/simulated/floors/sky.dm
  code/game/turfs/simulated/misc/fancy_shuttles.dm
  code/game/turfs/simulated/sky.dm
  code/game/turfs/simulated/wall_attacks.dm
  code/game/turfs/turf_ao.dm
  code/game/turfs/unsimulated/floor.dm
  code/game/turfs/unsimulated/mask.dm
  code/modules/awaymissions/loot_vr.dm
  code/modules/holomap/station_holomap.dm
  code/modules/maps/tg/reader.dm
  code/modules/power/singularity/act.dm
  icons/turf/flooring/damage.dmi
  icons/turf/flooring/decals.dmi
  icons/turf/flooring/decals_old.dmi
  icons/turf/flooring/decals_vr.dmi
  icons/turf/flooring/misc.dmi
  icons/turf/flooring/misc_vr.dmi
  icons/turf/flooring/plating_old.dmi
  icons/turf/flooring/plating_vr.dmi
  icons/turf/flooring/shadows.dmi
  icons/turf/flooring/techfloor_vr.dmi
  icons/turf/flooring/tiles.dmi
  icons/turf/flooring/tiles_old.dmi
  icons/turf/flooring/tiles_vr.dmi
  icons/turf/flooring/wood.dmi
  icons/turf/flooring/wood_vr.dmi
  icons/turf/floors.dmi
  icons/turf/floors_vr.dmi
  icons/turf/sky.dmi
Labels: size/XXL

#4978 SSao Tweaks
  code/controllers/subsystem/ao.dm
Labels: size/M

#5001 removes as null|anything from set default lang
  code/modules/mob/living/default_language.dm
Labels: size/XS

#4994 Start Now verb queues during server init
  code/modules/admin/admin.dm
Labels: size/S

#4995 AI will now properly spawn in core at roundstart
  code/game/landmarks/spawnpoint/station/jobs.dm
  code/modules/mob/transform_procs.dm
Labels: size/XS

#4993 Underwear port
  code/datums/underwear/bottom.dm
  code/datums/underwear/socks.dm
  code/datums/underwear/top.dm
  code/datums/underwear/undershirts.dm
  icons/mob/human.dmi
Labels: size/L

#4992 fixes a few things
  code/__HELPERS/view.dm
  code/_rendering/clickcatcher/clickcatcher.dm
  code/_rendering/fullscreen/fullscreen.dm
  code/_rendering/parallax/parallax_object.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/structures/railing.dm
  code/modules/client/client_procs.dm
  code/modules/materials/definitions/unsorted_materials.dm
  code/modules/mining/ore_redemption_machine/engineering_points_vendor.dm
  code/modules/overmap/ships/computers/ship.dm
  code/modules/tgui/modules/overmap.dm
Labels: size/M

#4999 fixes guns & not being able to climb over railings
  code/_onclick/click.dm
  code/_onclick/items.dm
  code/game/atoms/atoms_movable_movement.dm
  code/game/objects/structures.dm
  code/game/objects/structures/railing.dm
Labels: size/S

#4982 fixes toggle hotkey button maybe
  code/modules/keybindings/setup.dm
  interface/interface.dm
  interface/skin.dmf
Labels: size/S

#4987 Enables Helmet Cams on Exploration Voidsuit Helmets
  code/__DEFINES/machinery.dm
  code/modules/clothing/spacesuits/void/station.dm
  maps/rift/rift_defines.dm
Labels: size/XS

#4981 Tweaks Wall Rendering & Fixes Damage Overlays
  code/game/turfs/simulated/wall.dm
  code/game/turfs/simulated/wall_attacks.dm
  code/game/turfs/simulated/wall_icon.dm
Labels: size/M

#4998 Trying to pull something you're pulling will stop pulling it
  code/game/atoms/atoms_movable_pulling.dm
  code/modules/mob/mob_pull.dm
Labels: size/XS

#4996 Whitelist backend changes
  code/__DEFINES/species/species.dm
  code/__DEFINES/species/species_flags.dm
  code/controllers/configuration/whitelists.dm
  code/controllers/subsystem/characters/species.dm
  code/game/objects/structures/mirror.dm
  code/modules/mob/living/carbon/human/appearance.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/preferences/preference_setup/background/species.dm
  code/modules/species/character_species.dm
  code/modules/species/protean/protean_powers.dm
  code/modules/species/shadekin/shadekin_traits.dm
  code/modules/species/species.dm
  code/modules/species/station/adherent.dm
  code/modules/species/station/alraune.dm
  code/modules/species/station/apidaen.dm
  code/modules/species/station/custom_species.dm
  code/modules/species/station/diona.dm
  code/modules/species/station/golem.dm
  code/modules/species/station/monkey.dm
  code/modules/species/station/phoronoids.dm
  code/modules/species/station/rapala.dm
  code/modules/species/station/standard/akula.dm
  code/modules/species/station/standard/harpy.dm
  code/modules/species/station/standard/human_subspecies.dm
  code/modules/species/station/standard/naramadi.dm
  code/modules/species/station/standard/nevrean.dm
  code/modules/species/station/standard/shadekin.dm
  code/modules/species/station/standard/skrell.dm
  code/modules/species/station/standard/tajaran.dm
  code/modules/species/station/standard/teshari.dm
  code/modules/species/station/standard/unathi.dm
  code/modules/species/station/standard/unathidigi.dm
  code/modules/species/station/standard/vulpkanin.dm
  code/modules/species/station/standard/zaddat.dm
  code/modules/species/station/standard/zorren.dm
  code/modules/species/station/vasilissan.dm
  code/modules/species/station/werebeast.dm
  code/modules/species/station/xenomorph_hybrids/xeno_hybrids.dm
  code/modules/species/virtual_reality/opaque_form.dm
  code/modules/species/xenochimera/xenochimera.dm
Labels: size/L

#5000 Statpanel buttons fix
  html/statbrowser.html
Labels: size/S

#4976 [Ready for merge] Balances the infestation event
  code/modules/events/event_container_vr.dm
  code/modules/events/xenoinfestation.dm
Labels: size/S

#5012 Fixing ship name capitalization
  code/modules/busy_space/organizations.dm
Labels: size/S

#4979 Z-Mimic: Automatic Plane Mangling
  code/__DEFINES/rendering/zmimic.dm
  code/controllers/subsystem/overlays.dm
  code/controllers/subsystem/zmimic.dm
  code/game/machinery/lightswitch.dm
  code/modules/mining/mine_items.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/multiz/zmimic/mimic_movable.dm
  code/modules/multiz/zmimic/mimic_turf.dm
Labels: size/L

#4964 (WIP) AR-B Employment Records
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human.dm
Labels: Stale, size/M

#5004 fixes human subspecies paths
  code/modules/mob/living/carbon/human/human.dm
Labels: size/XS

#5011 Changes area designation in Atmos hallway
  _maps/map_files/rift/rift-03-underground1.dmm
Labels: size/L

#4985 Cyborg init refactor + other tweaks/fixes
  citadel.dme
  code/game/objects/items/trash.dm
  code/global.dm
  code/modules/mob/living/silicon/robot/dogborg/dog_modules_vr.dm
  code/modules/mob/living/silicon/robot/emote.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_modules/_robot_modules_defs.dm
  code/modules/mob/living/silicon/robot/robot_modules/event.dm
  code/modules/mob/living/silicon/robot/robot_modules/event_vr.dm
  code/modules/mob/living/silicon/robot/robot_modules/station.dm
  code/modules/mob/living/silicon/robot/robot_modules/station/cargo.dm
  code/modules/mob/living/silicon/robot/robot_modules/station/drone.dm
  code/modules/mob/living/silicon/robot/robot_modules/station/engineering.dm
  code/modules/mob/living/silicon/robot/robot_modules/station/medical.dm
  code/modules/mob/living/silicon/robot/robot_modules/station/misc.dm
  code/modules/mob/living/silicon/robot/robot_modules/station/science.dm
  code/modules/mob/living/silicon/robot/robot_modules/station/security.dm
  code/modules/mob/living/silicon/robot/robot_modules/station/service.dm
  code/modules/mob/living/silicon/robot/robot_modules/swarm.dm
  code/modules/mob/living/silicon/robot/robot_modules/syndicate.dm
  code/modules/mob/living/silicon/robot/robot_movement.dm
  code/modules/mob/living/silicon/robot/subtypes/lost_drone_vr.dm
  code/modules/nano/interaction/default.dm
Labels: size/XXL

#5017 Fixes gun packs spawning with incorrect crate type
  code/modules/cargo/supplypacks/security.dm
Labels: size/XS

#5003 Spawn will no longer lock up
  code/modules/admin/admin.dm
Labels: size/XS

#5016 Fixes borg descriptions being duplicated
  code/modules/mob/living/silicon/robot/examine.dm
Labels: size/XS

#5007 Storage Opening QOL
  code/game/objects/items/storage/_storage.dm
Labels: size/XS

#5006 Holodeck chess fix
  _maps/map_files/rift/rift-11-orbital.dmm
  icons/obj/chess.dmi
Labels: size/L

#5023 ERT can now be called before roundend
  code/game/response_team.dm
Labels: size/XS

#4984 [Rfm] adds new xenomorph hybrid subspecies
  .github/CODEOWNERS
  citadel.dme
  code/__DEFINES/species/species.dm
  code/modules/preferences/preference_setup/helpers/species_pick.dm
  code/modules/species/station/xenomorph_hybrids/xeno_hybrids.dm
  code/modules/sprite_accessories/ears/xenomorph.dm
  code/modules/sprite_accessories/hair/xenomorph.dm
  code/modules/sprite_accessories/tail/species/xenomorph.dm
  code/modules/sprite_accessories/wings/xenomorph.dm
  icons/mob/species/xenohybrid/xeno_parts_greyscale.dmi
  icons/mob/sprite_accessories/wings.dmi
  icons/mob/sprite_accessories/xeno_parts.dmi
  icons/mob/sprite_accessories/xeno_parts_darkend.dmi
Labels: size/M
