Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2023-07, with the labels that each got.

#5661 The Catskinner Event Wrap-up
  code/modules/clothing/under/accessories/medals.dm
  code/modules/lore_codex/news_data/main.dm
  code/modules/preferences/preference_setup/loadout/loadout_event_rewards.dm
  icons/mob/clothing/ties.dmi
  icons/obj/clothing/ties.dmi
Labels: size/L

#5663 fixes singularity clipping out of fieldgens when diagonally moving
  code/modules/power/singularity/singularity.dm
Labels: size/XS

#5662 ATM Triage Patch
  code/modules/economy/machines/ATM.dm
Labels: size/M

#5669 Catskinnner Wrap-Up Hotfix
  code/modules/preferences/preference_setup/loadout/loadout_event_rewards.dm
Labels: size/XS

#5655 bumps projectile speed up
  code/modules/projectiles/projectile.dm
Labels: size/XS

#5667 Pilot suit tweak
  code/datums/armor/station/exploration.dm
Labels: size/XS

#5664 buffs singularity radiation
  code/modules/power/singularity/singularity.dm
Labels: size/XS

#5668 fixes a bunch of bugs
  code/__DEFINES/misc.dm
  code/modules/clothing/under/oricon/utility.dm
  code/modules/economy/items/retail_scanner.dm
  code/modules/mob/freelook/ai/eye.dm
  maps/rift/levels/rift-11-orbital.dmm
  maps/tether/levels/misc.dmm
Labels: size/XXL

#5665 pAI cleanup + shell changes
  citadel.dme
  code/game/objects/effects/temporary_visuals/miscellaneous.dm
  code/modules/mob/living/silicon/pai/defense.dm
  code/modules/mob/living/silicon/pai/life.dm
  code/modules/mob/living/silicon/pai/mobility.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/living/silicon/pai/pai_vr.dm
  code/modules/mob/living/silicon/pai/savefile.dm
  code/modules/mob/living/silicon/pai/software_modules.dm
  code/modules/mob/living/silicon/pai/software_modules/_software_module.dm
  code/modules/mob/living/silicon/pai/software_modules/atmosphere_sensor.dm
  code/modules/mob/living/silicon/pai/software_modules/crew_manifest.dm
  code/modules/mob/living/silicon/pai/software_modules/directives.dm
  code/modules/mob/living/silicon/pai/software_modules/door_jack.dm
  code/modules/mob/living/silicon/pai/software_modules/messenger.dm
  code/modules/mob/living/silicon/pai/software_modules/radio_config.dm
  code/modules/mob/living/silicon/pai/software_modules/signaller.dm
  code/modules/mob/living/silicon/pai/verbs.dm
Labels: size/XXL

#5666 ATM TGUI Overhaul
  code/modules/economy/Accounts.dm
  code/modules/economy/machines/ATM.dm
  tgui/packages/tgui/interfaces/ATM.tsx
Labels: size/XL

#5670 slight gripper refactor
  citadel.dme
  code/__DEFINES/procs/clickcode.dm
  code/_onclick/items.dm
  code/game/objects/items/robot/gripper.dm
  code/modules/mob/living/silicon/robot/drone/drone_items.dm
Labels: size/XL

#5676 Ancient Event Reward
  code/modules/preferences/preference_setup/loadout/loadout_event_rewards.dm
Labels: size/XS

#5647 TGUI Voting panel
  code/controllers/subsystem/ticker.dm
  code/controllers/subsystem/vote.dm
  tgui/packages/tgui/interfaces/Vote.tsx
  tgui/packages/tgui/interfaces/VotePanel.tsx
Labels: size/XL

#5683 Fixes Triumph Atmos Spacing
  maps/triumph/levels/deck1.dmm
  maps/triumph/levels/deck2.dmm
  maps/triumph/levels/deck3.dmm
  maps/triumph/levels/deck4.dmm
Labels: size/XL

#5679 small patch to TGUI modules
  tgui/docs/component-reference.md
  tgui/packages/tgui/backend.ts
  tgui/packages/tgui/components/Module.tsx
  tgui/packages/tgui/layouts/Modular.tsx
Labels: size/S

#5678 fixes a tgui cardmod issue
  code/modules/tgui/modules/general/cardmod.dm
Labels: Priority 0: CRITICAL, size/XS

#5681 fixes sdql not asyncing calls
  code/modules/admin/verbs/SDQL2/SDQL_2.dm
Labels: size/XS

#5672 Adds Drake Taur Wings
  code/modules/sprite_accessories/wings/draconic_furries.dm
  icons/mob/sprite_accessories/wings.dmi
Labels: size/XS

#5685 Baywall Bugfixing
  code/game/objects/items/bodybag.dm
  code/game/objects/structures/crates_lockers/__closet.dm
  code/game/objects/structures/crates_lockers/closets/coffin.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/low_wall.dm
  code/game/objects/structures/window.dm
  code/modules/mining/mine_items.dm
  code/modules/power/lighting/lighting.dm
  icons/obj/closets/grave.dmi
Labels: size/L

#5684 Cafefix
  icons/turf/flooring/decals.dmi
  maps/rift/levels/rift-05-surface2.dmm
  maps/rift/levels/rift-06-surface3.dmm
Labels: size/XL

#5688 Baywalls Color-Correction Pass
  code/__DEFINES/color/color.dm
  code/game/machinery/doors/airlock_subtypes.dm
  code/game/objects/structures/crates_lockers/_closet_appearance_definitions.dm
  code/game/turfs/simulated/wall_types.dm
  code/modules/mapping/paint.dm
  icons/obj/doors/double/fill_stripe.dmi
  icons/obj/doors/double/stripe.dmi
  icons/obj/doors/station/fill_stripe.dmi
  icons/obj/doors/station/stripe.dmi
  icons/turf/walls/neighbor_stripe.dmi
  icons/turf/walls/wall_stripe.dmi
Labels: size/M

#5691 adds hypospray vials to chemistry bags
  code/game/objects/items/storage/bags.dm
Labels: size/XS

#5687 small hotfix to get map levels
  code/modules/mapping/map.dm
Labels: size/XS

#5686 readds rd/sar rigs, adds a rig to the CMO, repaths modules/rigsuits to modules/hardsuits in preparation for the rig update
  citadel.dme
  code/modules/hardsuits/_rig.dm
  code/modules/hardsuits/activation.dm
  code/modules/hardsuits/defense.dm
  code/modules/hardsuits/modules/combat.dm
  code/modules/hardsuits/modules/combat_vr.dm
  code/modules/hardsuits/modules/computer.dm
  code/modules/hardsuits/modules/modules.dm
  code/modules/hardsuits/modules/ninja.dm
  code/modules/hardsuits/modules/utility.dm
  code/modules/hardsuits/modules/utility_vr.dm
  code/modules/hardsuits/modules/vision.dm
  code/modules/hardsuits/pieces.dm
  code/modules/hardsuits/rig.dm
  code/modules/hardsuits/rig_attackby.dm
  code/modules/hardsuits/rig_pieces.dm
  code/modules/hardsuits/rig_verbs.dm
  code/modules/hardsuits/rig_wiring.dm
  code/modules/hardsuits/suits/combat.dm
  code/modules/hardsuits/suits/ert.dm
  code/modules/hardsuits/suits/light.dm
  code/modules/hardsuits/suits/merc.dm
  code/modules/hardsuits/suits/pmc.dm
  code/modules/hardsuits/suits/species/protean.dm
  code/modules/hardsuits/suits/species/unathi.dm
  code/modules/hardsuits/suits/species/vox.dm
  code/modules/hardsuits/suits/station/cargo.dm
  code/modules/hardsuits/suits/station/engineering.dm
  code/modules/hardsuits/suits/station/medical.dm
  code/modules/hardsuits/suits/station/misc.dm
  code/modules/hardsuits/suits/station/science.dm
  code/modules/hardsuits/suits/station/security.dm
  maps/rift/levels/rift-04-surface1.dmm
  maps/rift/levels/rift-05-surface2.dmm
Labels: size/M

#5690 fixes lathe grammar in insert item
  code/game/machinery/lathes/lathe.dm
Labels: size/XS

#5701 fixes apc overlays
  code/modules/power/apc.dm
Labels: size/XS

#5697 comments out triumph's fission engine until its fixed (it never will be)
  maps/triumph/engines.dm
Labels: size/XS

#5695 fixes chem dispensers swapping
  code/modules/reagents/machinery/dispenser/dispenser.dm
Labels: size/XS

#5696 fixes particle accelerator move runtime
  code/modules/power/singularity/particle_accelerator/particle.dm
Labels: size/S

#5693 fixes triumph beltmining
  maps/triumph/triumph.dm
Labels: size/XS

#5702 fixes closets being wonky
  code/game/objects/structures/crates_lockers/__closet.dm
  code/game/objects/structures/crates_lockers/closets/utility_closets.dm
  code/game/objects/structures/crates_lockers/crates.dm
Labels: size/XS

#5705 Plain Spline Corners
  code/game/turfs/simulated/flooring/flooring_decals.dm
  icons/turf/flooring/decals.dmi
Labels: size/XS

#5698 Follow menu now shows AI and robots/cyborgs
  code/modules/mob/observer/dead/orbit.dm
Labels: size/XS

#5704 HOS combat coat
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/suits/armor.dm
  icons/mob/clothing/suits.dmi
  icons/obj/clothing/suits.dmi
Labels: size/S

#5699 silly bandaid fix to rust and some stuff
  code/modules/power/pacman2.dm
  code/modules/power/port_gen.dm
  maps/triumph/engines/rust.dmm
  tgui/packages/tgui/interfaces/PortableGenerator.js
Labels: size/L

#5710 zm: Fix space parallax
  code/modules/multiz/zmimic/mimic_movable.dm
Labels: size/XS

#5703 glass door bugfix
  code/game/machinery/doors/airlock_subtypes.dm
Labels: size/XS

#5709 Speedmergable Ckey fix
  code/modules/preferences/preference_setup/loadout/loadout_event_rewards.dm
Labels: Merge Conflict, size/XS

#5715 fixes potential cargo race condition
  code/controllers/subsystem/supply.dm
Labels: size/XS

#5712 Adds the Well-Worn Varsity Jacket.
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/preferences/preference_setup/loadout/loadout_suit.dm
  icons/clothing/suit/jackets/varsity.dmi
  icons/mob/clothing/suits.dmi
  icons/obj/clothing/suits.dmi
Labels: size/S

#5706 SSmapping now writes next map immediately when admin-verb change map'd
  code/controllers/subsystem/mapping/maps.dm
Labels: size/XS

#5714 triumph fixes
  code/game/turfs/change_turf.dm
  code/modules/admin/verbs/buildmode.dm
  code/modules/overmap/legacy/spacetravel.dm
  code/modules/rogueminer_vr/controller.dm
  code/modules/shuttles/shuttle_console.dm
  maps/triumph/triumph.dm
Labels: size/M

#5711 Gives the AI a Jukebox
  maps/rift/levels/rift-06-surface3.dmm
Labels: size/L

#5608 reworks xenomorph hybrid healing
  code/__DEFINES/ability.dm
  code/datums/ability.dm
  code/modules/mob/mob_helpers.dm
  code/modules/organs/internal/species/xenos.dm
  code/modules/species/station/xenomorph_hybrids/hybrid_abilities.dm
  code/modules/species/station/xenomorph_hybrids/xeno_hybrids.dm
  code/modules/species/xenomorphs/alien_species.dm
  icons/screen/actions/actions.dmi
  icons/screen/actions/xenomorph.dmi
Labels: size/L

#5719 pAI clothing (god is dead and i killed him)
  code/modules/mob/living/silicon/pai/defense.dm
  code/modules/mob/living/silicon/pai/mobility.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/living/silicon/pai/verbs.dm
Labels: size/L

#5692 dynamic climbing and object heights
  code/__DEFINES/_flags/atom_flags.dm
  code/__DEFINES/_flags/obj_flags.dm
  code/__DEFINES/procs/do_after.dm
  code/game/machinery/computer/atmos_control.dm
  code/game/machinery/computer/computer.dm
  code/game/machinery/computer/medical.dm
  code/game/machinery/computer/skills.dm
  code/game/machinery/computer/timeclock_vr.dm
  code/game/machinery/cryopod.dm
  code/game/machinery/holopad.dm
  code/game/machinery/lathes/lathe.dm
  code/game/objects/items.dm
  code/game/objects/items/poi_items.dm
  code/game/objects/objs.dm
  code/game/objects/structures.dm
  code/game/objects/structures/cliff.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/fence.dm
  code/game/objects/structures/girders.dm
  code/game/objects/structures/gravemarker.dm
  code/game/objects/structures/janicart.dm
  code/game/objects/structures/ledges.dm
  code/game/objects/structures/low_wall.dm
  code/game/objects/structures/mop_bucket.dm
  code/game/objects/structures/railing.dm
  code/game/objects/structures/statues.dm
  code/game/turfs/turf.dm
  code/modules/atmospherics/machinery/machinery.dm
  code/modules/events/meteor_strike_vr.dm
  code/modules/holomap/station_holomap.dm
  code/modules/mining/mine_outcrops.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/movement.dm
  code/modules/mob/movement.dm
  code/modules/multiz/structures.dm
  code/modules/overmap/legacy/ships/computers/helm.dm
  code/modules/projectiles/projectile.dm
  code/modules/tables/flipping.dm
  code/modules/tables/tables.dm
Labels: size/XL

#5729 fixes guest pass consoles being climbable
  code/game/machinery/computer/guestpass.dm
Labels: size/XS

#5723 fixes smartfridges not updating icon on load
  code/modules/food/kitchen/smartfridge.dm
Labels: size/XS

#5724 fxies triumph spawnpoints
  maps/triumph/levels/deck3.dmm
  maps/triumph/levels/deck4.dmm
Labels: size/S

#5708 adds navy blue armpads, legpads + large pouches to armory
  maps/rift/levels/rift-05-surface2.dmm
Labels: size/S

#5713 TRIUMPH SECURITY EQUIPMENT STORAGE, ARMORY, AND FIGHTER BAY REWORK
  maps/triumph/levels/deck4.dmm
Labels: good first pr, size/XXL

#5721 New Carpets
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/turfs/simulated/flooring/_flooring.dm
  code/game/turfs/simulated/flooring/flooring_premade.dm
  icons/obj/stacks.dmi
  icons/turf/flooring/carpet.dmi
Labels: size/L

#5727 pAI clothing adjustments
  code/modules/mob/living/silicon/pai/defense.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/living/silicon/pai/verbs.dm
Labels: size/M

#5728 TRIUMPH central command floor fix
  maps/triumph/levels/flagship.dmm
Labels: size/L

#5726 adds vore subtle verb
  code/__HELPERS/_logging.dm
  code/modules/mob/say_vr.dm
Labels: size/M

#5736 some fixes
  code/datums/material_container.dm
  code/modules/tgui/modules/specific/lathe_control.dm
Labels: Priority 0: CRITICAL, size/S

#5732 fixes inducers deleting cells
  code/game/objects/items/inducer.dm
Labels: size/XS

#5731 circulators are no longer underfloor+can be climbed on
  code/modules/atmospherics/machinery/components/binary_devices/circulator.dm
Labels: size/XS

#5722 message range update to visible_action_feedback, and makes subtles make a, well, subtly-does-something message for people within range instead of being completely silent
  citadel.dme
  code/__DEFINES/spans.dm
  code/game/atoms/action_feedback.dm
  code/game/atoms/atom.dm
  code/modules/fishing/aquarium/aquarium.dm
  code/modules/mob/action_feedback.dm
  code/modules/mob/observer/dead/dead.dm
  code/modules/mob/say_vr.dm
  code/modules/reagents/items/hypospray.dm
  code/modules/reagents/machinery/dispenser/dispenser.dm
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
  tgui/packages/tgui-panel/styles/goon/chat.scss
Labels: size/L

#5738 Turnstile Access Prefabs
  code/__DEFINES/access.dm
  code/game/machinery/turnstile.dm
Labels: size/XS

#5735 changes the open simulated turf to be SOMETHING NOT HORRIBLY EYE SEARING
  code/modules/multiz/open_turf.dm
  icons/turf/space.dmi
Labels: size/XS

#5734 Add horse satyr legs to character creation
  code/modules/sprite_accessories/tail/bovine.dm
  icons/mob/sprite_accessories/tails.dmi
Labels: size/S

#5717 codebase reorganization of some folders
  citadel.dme
  code/__DEFINES/screen.dm
  code/game/click/adjacency.dm
  code/game/click/adjacency_legacy.dm
  code/game/click/ai.dm
  code/game/click/click.dm
  code/game/click/cyborg.dm
  code/game/click/drag_drop.dm
  code/game/click/item_attack.dm
  code/game/click/items.dm
  code/game/click/mobs.dm
  code/game/click/observer.dm
  code/game/click/other_mobs.dm
  code/game/click/reachability.dm
  code/game/click/rig.dm
  code/game/click/telekinesis.dm
  code/game/legacy_html_uis/byjax.dm
  code/game/legacy_html_uis/menus.dm
  code/game/rendering/atom_huds/alternate_appearance.dm
  code/game/rendering/atom_huds/atom_hud.dm
  code/game/rendering/atom_huds/data_huds.dm
  code/game/rendering/atom_huds/other_huds.dm
  code/game/rendering/clickcatcher/clickcatcher.dm
  code/game/rendering/client.dm
  code/game/rendering/fullscreen/fullscreen.dm
  code/game/rendering/legacy/ability_screen_objects.dm
  code/game/rendering/legacy/ai.dm
  code/game/rendering/legacy/alert.dm
  code/game/rendering/legacy/alien_larva.dm
  code/game/rendering/legacy/ghost.dm
  code/game/rendering/legacy/gun_mode.dm
  code/game/rendering/legacy/hud.dm
  code/game/rendering/legacy/hud_object.dm
  code/game/rendering/legacy/human.dm
  code/game/rendering/legacy/intents/throwing.dm
  code/game/rendering/legacy/inventory/inventory.dm
  code/game/rendering/legacy/map_popups.dm
  code/game/rendering/legacy/movable_screen_objects.dm
  code/game/rendering/legacy/objects/waypoint_tracker.dm
  code/game/rendering/legacy/other_mobs.dm
  code/game/rendering/legacy/radial.dm
  code/game/rendering/legacy/radial_persistent.dm
  code/game/rendering/legacy/render.dm
  code/game/rendering/legacy/rigmech.dm
  code/game/rendering/legacy/robot.dm
  code/game/rendering/legacy/spell_screen_objects.dm
  code/game/rendering/mob.dm
  code/game/rendering/parallax/parallax.dm
  code/game/rendering/parallax/parallax_holder.dm
  code/game/rendering/parallax/parallax_object.dm
  code/game/rendering/parallax/types/space.dm
  code/game/rendering/perspectives/darksight.dm
  code/game/rendering/perspectives/perspective.dm
  code/game/rendering/perspectives/vision.dm
  code/game/rendering/plane_masters/plane_holder.dm
  code/game/rendering/plane_masters/plane_master.dm
  code/game/rendering/plane_masters/plane_render.dm
  code/game/rendering/screen.dm
  code/game/world.dm
  code/world.dm
Labels: size/L

#5740 mrrp (emote)
  code/modules/mob/living/carbon/human/emote.dm
  sound/voice/mrrp.ogg
Labels: size/XS

#5741 Triumph central command floor fix
  maps/triumph/levels/flagship.dmm
Labels: size/L

#5739 lathe search
  tgui/packages/tgui/interfaces/modules/TGUILatheControl.tsx
Labels: size/M

#5742 fixes using items on lathes like rpeds
  code/game/machinery/lathes/lathe.dm
Labels: size/XS

#5744 fixes gun unloading failing if hands are full
  code/modules/projectiles/guns/ballistic.dm
Labels: Priority 1: High, size/XS

#5745 adds maint access to most jobs and reorganizes + shuffles some access
  code/controllers/configuration/entries/game.dm
  code/modules/jobs/job.dm
  code/modules/jobs/job_types/station/civillian/chaplain.dm
  code/modules/jobs/job_types/station/civillian/clown.dm
  code/modules/jobs/job_types/station/civillian/entertainer.dm
  code/modules/jobs/job_types/station/civillian/internals_affairs_agent.dm
  code/modules/jobs/job_types/station/civillian/librarian.dm
  code/modules/jobs/job_types/station/civillian/mime.dm
  code/modules/jobs/job_types/station/civillian/pilot.dm
  code/modules/jobs/job_types/station/command/command_secretary.dm
  code/modules/jobs/job_types/station/engineering/atmospherics_technician.dm
  code/modules/jobs/job_types/station/engineering/senior_engineer.dm
  code/modules/jobs/job_types/station/engineering/station_engineer.dm
  code/modules/jobs/job_types/station/exploration/explorer.dm
  code/modules/jobs/job_types/station/exploration/field_medic.dm
  code/modules/jobs/job_types/station/exploration/pathfinder.dm
  code/modules/jobs/job_types/station/medical/chemist.dm
  code/modules/jobs/job_types/station/medical/head_nurse.dm
  code/modules/jobs/job_types/station/medical/medical_doctor.dm
  code/modules/jobs/job_types/station/medical/paramedic.dm
  code/modules/jobs/job_types/station/medical/psychiatrist.dm
  code/modules/jobs/job_types/station/offduty/civillian.dm
  code/modules/jobs/job_types/station/offduty/command.dm
  code/modules/jobs/job_types/station/offduty/engineering.dm
  code/modules/jobs/job_types/station/offduty/exploration.dm
  code/modules/jobs/job_types/station/offduty/medical.dm
  code/modules/jobs/job_types/station/offduty/science.dm
  code/modules/jobs/job_types/station/offduty/security.dm
  code/modules/jobs/job_types/station/offduty/supply.dm
  code/modules/jobs/job_types/station/science/research_director.dm
  code/modules/jobs/job_types/station/science/roboticist.dm
  code/modules/jobs/job_types/station/science/scientist.dm
  code/modules/jobs/job_types/station/science/senior_researcher.dm
  code/modules/jobs/job_types/station/security/detective.dm
  code/modules/jobs/job_types/station/security/head_of_security.dm
  code/modules/jobs/job_types/station/security/security_officer.dm
  code/modules/jobs/job_types/station/security/warden.dm
  code/modules/jobs/job_types/station/service/bartender.dm
  code/modules/jobs/job_types/station/service/botanist.dm
  code/modules/jobs/job_types/station/service/chef.dm
  code/modules/jobs/job_types/station/service/janitor.dm
  code/modules/jobs/job_types/station/supply/cargo_technician.dm
  code/modules/jobs/job_types/station/supply/shaft_miner.dm
  config/entries/game.txt
Labels: size/L

#5750 fixes infinite loop
  code/game/objects/effects/alien/aliens.dm
Labels: Priority 0: CRITICAL, size/XS

#5743 triumph 192x192 + adds atlas levels instead of triumph levels
  code/controllers/subsystem/mapping/maps.dm
  code/modules/mapping/map.dm
  code/modules/rogueminer_vr/controller.dm
  maps/triumph/triumph.dm
Labels: size/M

#5753 fixes translation context memory leak
  code/modules/language/translation.dm
Labels: Priority 0: CRITICAL, size/XS

#5733 guestpass console tgui
  citadel.dme
  code/__HELPERS/time.dm
  code/game/machinery/computer/guestpass.dm
  code/game/objects/items/id_cards/guest.dm
  tgui/packages/tgui/interfaces/common/Access.tsx
  tgui/packages/tgui/interfaces/computers/GuestPassTerminal.tsx
Labels: size/XL

#5542 Modular Computer Revival
  citadel.dme
  code/__DEFINES/access.dm
  code/__DEFINES/misc.dm
  code/modules/hydroponics/trays/tray_tools.dm
  code/modules/modular_computers/NTNet/NTNet.dm
  code/modules/modular_computers/README.md
  code/modules/modular_computers/computers/modular_computer/core.dm
  code/modules/modular_computers/computers/modular_computer/interaction.dm
  code/modules/modular_computers/computers/modular_computer/ui.dm
  code/modules/modular_computers/file_system/computer_file.dm
  code/modules/modular_computers/file_system/data.dm
  code/modules/modular_computers/file_system/news_article.dm
  code/modules/modular_computers/file_system/program.dm
  code/modules/modular_computers/file_system/program_events.dm
  code/modules/modular_computers/file_system/programs/antagonist/access_decrypter.dm
  code/modules/modular_computers/file_system/programs/antagonist/dos.dm
  code/modules/modular_computers/file_system/programs/antagonist/hacked_camera.dm
  code/modules/modular_computers/file_system/programs/antagonist/revelation.dm
  code/modules/modular_computers/file_system/programs/command/card.dm
  code/modules/modular_computers/file_system/programs/command/comm.dm
  code/modules/modular_computers/file_system/programs/engineering/alarm_monitor.dm
  code/modules/modular_computers/file_system/programs/engineering/atmos_control.dm
  code/modules/modular_computers/file_system/programs/engineering/power_monitor.dm
  code/modules/modular_computers/file_system/programs/engineering/rcon_console.dm
  code/modules/modular_computers/file_system/programs/engineering/shutoff_monitor.dm
  code/modules/modular_computers/file_system/programs/engineering/supermatter_monitor.dm
  code/modules/modular_computers/file_system/programs/generic/camera.dm
  code/modules/modular_computers/file_system/programs/generic/configurator.dm
  code/modules/modular_computers/file_system/programs/generic/email_client.dm
  code/modules/modular_computers/file_system/programs/generic/file_browser.dm
  code/modules/modular_computers/file_system/programs/generic/game.dm
  code/modules/modular_computers/file_system/programs/generic/news_browser.dm
  code/modules/modular_computers/file_system/programs/generic/ntdownloader.dm
  code/modules/modular_computers/file_system/programs/generic/ntnrc_client.dm
  code/modules/modular_computers/file_system/programs/generic/nttransfer.dm
  code/modules/modular_computers/file_system/programs/generic/uav.dm
  code/modules/modular_computers/file_system/programs/generic/wordprocessor.dm
  code/modules/modular_computers/file_system/programs/research/email_administration.dm
  code/modules/modular_computers/file_system/programs/research/ntmonitor.dm
  code/modules/modular_computers/file_system/programs/security/alarm_monitor.dm
  code/modules/modular_computers/file_system/programs/security/digitalwarrant.dm
  code/modules/nano/modules/alarm_monitor.dm
  code/modules/nifsoft/nif_tgui.dm
  code/modules/power/antimatter/computer.dm
  code/modules/power/breaker_box.dm
  code/modules/power/smes/smes_construction.dm
  code/modules/tgui/modules/communications.dm
  code/modules/tgui/modules/general/cardmod.dm
  code/modules/tgui/modules/ntos-only/cardmod.dm
  code/modules/tgui/modules/rcon.dm
  config/access levels.txt
  tgui/packages/tgui/interfaces/CameraConsole.js
  tgui/packages/tgui/interfaces/CommunicationsConsole.js
  tgui/packages/tgui/interfaces/NtosCameraConsole.js
  tgui/packages/tgui/interfaces/NtosIdentificationComputer.js
  tgui/packages/tgui/interfaces/NtosIdentificationComputer.tsx
  tgui/packages/tgui/interfaces/NtosNetDownloader.js
Labels: size/XXL

#5748 Deck one baywallification
  maps/triumph/levels/deck1.dmm
Labels: size/XXL

#5747 Deck two Baywallification
  maps/triumph/levels/deck2.dmm
Labels: size/XXL

#5759 follow menu performance hotfix
  code/modules/mob/observer/dead/orbit.dm
  tgui/packages/tgui/interfaces/Orbit.tsx
Labels: size/XS

#5761 fixes shuttle ceilings causing active edges
  code/modules/shuttles/shuttle.dm
Labels: size/XS

#5762 relicenses a bunch of files written entirely by me to MIT
  code/controllers/subsystem/characters/_characters.dm
  code/controllers/subsystem/characters/character_species.dm
  code/controllers/subsystem/characters/storage.dm
  code/controllers/subsystem/job/access.dm
  code/controllers/subsystem/job/job_manager.dm
  code/controllers/subsystem/job/spawnpoints.dm
  code/controllers/subsystem/mapping/allocation.dm
  code/controllers/subsystem/mapping/boot.dm
  code/controllers/subsystem/mapping/level_helpers/air.dm
  code/controllers/subsystem/mapping/level_helpers/attributes.dm
  code/controllers/subsystem/mapping/level_helpers/baseturf.dm
  code/controllers/subsystem/mapping/level_helpers/linkage.dm
  code/controllers/subsystem/mapping/level_helpers/lookup.dm
  code/controllers/subsystem/mapping/level_helpers/traits.dm
  code/controllers/subsystem/mapping/levels.dm
  code/controllers/subsystem/mapping/maps.dm
  code/controllers/subsystem/mapping/obfuscation.dm
  code/controllers/subsystem/mapping/reservations.dm
  code/controllers/subsystem/persistence/_persistence.dm
  code/controllers/subsystem/persistence/bunker.dm
  code/controllers/subsystem/persistence/objects.dm
  code/controllers/subsystem/persistence/objects/unique_string.dm
Labels: size/M

#5765 mimic fix
  code/modules/mob/living/simple_mob/subtypes/vore/mimic.dm
Labels: size/S

#5755 fixes chameleon gun sprite disappearing when fired
  code/modules/clothing/chameleon.dm
Labels: size/XS

#5768 adds angel wings
  code/modules/sprite_accessories/wings/feathered.dm
  icons/mob/sprite_accessories/wings.dmi
Labels: size/XS

#5769 no alien coil stack split
  code/modules/power/cable.dm
Labels: size/XS

#5764 fix mute trait not working
  code/modules/mob/living/say.dm
Labels: size/XS

#5756 fixes firefighter building
  code/game/mecha/mecha_construction_paths.dm
Labels: size/XS

#5760 fix evidence bags
  code/modules/detectivework/tools/evidencebag.dm
Labels: size/XS

#5758 Deck three fixes windows and baywalls
  maps/triumph/levels/deck3.dmm
Labels: size/XXL

#5757 Fixes CC active edges, and halfwall windows
  maps/triumph/levels/flagship.dmm
Labels: size/XL

#5774 fix rped usage on lathe/dispenser
  code/game/machinery/_machinery.dm
  code/game/objects/items/stock_parts/part_replacer.dm
Labels: size/S

#5771 hopefully fixes pda gc
  code/game/objects/items/devices/PDA/cart.dm
  code/game/objects/items/devices/PDA/radio.dm
Labels: size/S

#5770 nanoui no longer strips im/proper
  code/modules/nano/nanoui.dm
Labels: size/XS

#5751 converts get_exonet_node to use GLOB
  code/game/machinery/exonet_node.dm
Labels: size/S

#5775 Warrant projectors in SO locker
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
Labels: size/XS

#5772 Adds sprites for 3 tile wide colorable airlock doors
  icons/obj/doors/triple/color.dmi
  icons/obj/doors/triple/door.dmi
  icons/obj/doors/triple/emag.dmi
  icons/obj/doors/triple/fill_color.dmi
  icons/obj/doors/triple/fill_glass.dmi
  icons/obj/doors/triple/fill_steel.dmi
  icons/obj/doors/triple/fill_stripe.dmi
  icons/obj/doors/triple/lights_bolts.dmi
  icons/obj/doors/triple/lights_deny.dmi
  icons/obj/doors/triple/lights_green.dmi
  icons/obj/doors/triple/panel.dmi
  icons/obj/doors/triple/stripe.dmi
  icons/obj/doors/triple/welded.dmi
Labels: size/XS

#5749 pAI qol and bugfixes
  citadel.dme
  code/_globals/lists/clothing.dm
  code/game/objects/items/devices/paicard.dm
  code/modules/clothing/chameleon.dm
  code/modules/mob/living/silicon/emote.dm
  code/modules/mob/living/silicon/pai/defense.dm
  code/modules/mob/living/silicon/pai/life.dm
  code/modules/mob/living/silicon/pai/mobility.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/living/silicon/pai/software.dm
  code/modules/mob/living/silicon/pai/verbs.dm
  code/modules/mob/observer/dead/dead.dm
  code/modules/mob/observer/dead/orbit.dm
  code/modules/vore/eating/digest_act_vr.dm
  icons/obj/pda.dmi
  icons/obj/pda_vr.dmi
  nano/templates/pai_interface.tmpl
Labels: size/L

#5752 adds hiding verbs for most species tails/horn/wings
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/human_powers.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/species/outsider/celestials.dm
  code/modules/species/outsider/scori.dm
  code/modules/species/outsider/vox.dm
  code/modules/species/protean/protean.dm
  code/modules/species/station/alraune.dm
  code/modules/species/station/apidaen.dm
  code/modules/species/station/custom_species.dm
  code/modules/species/station/rapala.dm
  code/modules/species/station/standard/akula.dm
  code/modules/species/station/standard/harpy.dm
  code/modules/species/station/standard/human.dm
  code/modules/species/station/standard/moth.dm
  code/modules/species/station/standard/naramadi.dm
  code/modules/species/station/standard/nevrean.dm
  code/modules/species/station/standard/tajaran.dm
  code/modules/species/station/standard/teshari.dm
  code/modules/species/station/standard/unathi.dm
  code/modules/species/station/standard/vulpkanin.dm
  code/modules/species/station/standard/zorren.dm
  code/modules/species/station/vasilissan.dm
  code/modules/species/station/xenochimera.dm
  code/modules/species/station/xenomorph_hybrids/xeno_hybrids.dm
  code/modules/sprite_accessories/sprite_accessories.dm
  code/modules/sprite_accessories/tail/taurs.dm
Labels: size/L

#5754 Character Profile Tweaks
  code/datums/character_profile.dm
  code/game/machinery/holopad.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/admin_set_headshot.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/robot/examine.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/preferences/_preferences.dm
  code/modules/preferences/preference_setup/general/01_basic.dm
  code/modules/vore/eating/living_vr.dm
  tgui/packages/tgui/interfaces/CharacterProfile.tsx
Labels: size/L

#5784 Triumph Atmospherics Rework
  citadel.dme
  code/game/objects/structures/atmos_tanks.dm
  code/modules/mapping/map_helpers/network_builder/power_cable.dm
  icons/obj/atmos_tanks/5x5/tank_5x5_color.dmi
  icons/obj/atmos_tanks/5x5/tank_5x5_color2.dmi
  icons/obj/atmos_tanks/5x5/tank_5x5_glass.dmi
  icons/obj/atmos_tanks/5x5/tank_5x5_preview.dmi
  icons/obj/atmos_tanks/5x5/tank_5x5_supports.dmi
  maps/triumph/levels/deck1.dmm
Labels: size/XXL

#5776 Saddlebag fix + Draketaur wing tweak
  code/game/objects/items/storage/backpack.dm
  code/modules/loadout/loadout_xeno.dm
  icons/mob/clothing/back_taur.dmi
  icons/mob/sprite_accessories/wings.dmi
Labels: size/M

#5785 Makes nano printer ask before recycling paper
  code/modules/modular_computers/hardware/nano_printer.dm
Labels: size/XS

#5789 Prepwork for mapping modular laptops/helmcams
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  code/modules/clothing/under/accessories/armor.dm
  code/modules/modular_computers/computers/subtypes/preset_laptop.dm
  code/modules/modular_computers/computers/subtypes/preset_tablet.dm
  code/modules/tgui/modules/camera.dm
  icons/obj/clothing/Sprite-0002.dmi
  icons/obj/clothing/modular_armor.dmi
Labels: size/M

#5767 makes holopad interface not utterly horrifying
  tgui/packages/tgui/interfaces/machines/Holopad.tsx
Labels: size/L

#5782 fixes some runtimes
  code/datums/status_effects/grouped/crusher_mark.dm
  code/modules/integrated_electronics/subtypes/reagents.dm
  code/modules/mining/kinetic_crusher.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mining/shelters.dm
  code/modules/preferences/preference_setup/global/02_settings.dm
  code/modules/projectiles/guns/magnetic/magnetic.dm
Labels: size/M

#5790 fixes a small bug in circuits
  code/modules/integrated_electronics/subtypes/manipulation.dm
Labels: size/XS

#5783 fix depth pixel offsets
  code/modules/mob/living/living.dm
Labels: size/S

#5778 Deck 4:Baywallification, window halfwalling and firelocks
  maps/triumph/levels/deck4.dmm
Labels: size/XXL

#5797 fixes loadout error on invalid color strings
  tgui/packages/tgui/interfaces/common/Color.tsx
Labels: size/XS

#5801 fixes a colormate bug
  code/game/machinery/colormate.dm
Labels: size/XS

#5795 Removes all mimics from the triumph
  maps/triumph/levels/deck1.dmm
  maps/triumph/levels/deck3.dmm
  maps/triumph/levels/deck4.dmm
Labels: size/XS

#5803 low wall coloring on deck 1 and plating under the atmos windows
  maps/triumph/levels/deck1.dmm
Labels: size/XL

#5802 Ghosts can follow overmap shuttles
  code/modules/mob/observer/dead/orbit.dm
Labels: size/S

#5805 makes the wings box sprite point to food.dmi instead of storage.dmi
  code/modules/food/food/snacks.dm
Labels: size/XS

#5808 Makes alcohol intolerance slightly less intolerable
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Dispenser.dm
Labels: size/XS

#5798 TRIUMPH - Secquipment storage fix - slight HoS office edit - sec shuttle replacement
  maps/triumph/levels/deck4.dmm
Labels: size/XL
