Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2023-02, with the labels that each got.

#5020 Literally just removing var/ in the args for reagent procs
  code/game/gamemodes/changeling/powers/epinephrine_overdose.dm
  code/modules/reagents/Food-Recipes.dm
  code/modules/reagents/Misc-Recipes.dm
  code/modules/reagents/chemistry/_readme.dm
  code/modules/reagents/chemistry/chemical_reactions.dm
  code/modules/reagents/chemistry/helpers.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/reagents/chemistry/reagents.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Core.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Dispenser.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Medicine.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Modifiers.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Other.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Toxins.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Topical.dm
  code/modules/reagents/chemistry/reagents/other/cleaner.dm
  code/modules/reagents/chemistry/reagents/pyrotechnics/thermite.dm
  code/modules/reagents/distilling/Distilling-Recipes.dm
Labels: size/XL

#5029 Cleans up white pixels on the edges
  icons/mob/sprite_accessories/wings.dmi
Labels: size/XS

#5019 Ambient Lights: Multiple-Source Ambience
  citadel.dme
  code/__DEFINES/color/color.dm
  code/__DEFINES/rendering/lighting.dm
  code/controllers/subsystem/ambient_lighting.dm
  code/controllers/subsystem/lighting.dm
  code/controllers/subsystem/planets.dm
  code/game/turfs/change_turf.dm
  code/game/turfs/simulated/floor_types.dm
  code/game/turfs/simulated/floors/lava.dm
  code/game/turfs/space/space.dm
  code/game/turfs/turf.dm
  code/modules/lighting/lighting_corner.dm
  code/modules/lighting/lighting_overlay.dm
  code/modules/lighting/lighting_setup.dm
  code/modules/lighting/lighting_source.dm
  code/modules/lighting/lighting_turf.dm
  code/modules/maps/weather/classd.dm
  code/modules/maps/weather/classg.dm
  code/modules/maps/weather/classh.dm
  code/modules/maps/weather/classm.dm
  code/modules/maps/weather/classp.dm
  code/modules/maps/weather/lavaland.dm
  code/modules/maps/weather/rift_lythios-43c.dm
  code/modules/maps/weather/tether_virgo3b.dm
  code/modules/maps/weather/virgo4.dm
  code/modules/mob/_modifiers/traits_phobias.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/planet/planet.dm
  code/modules/planet/sif.dm
Labels: size/L

#5032 temporary hotfix* for people screaming while unconscious
  code/modules/organs/external/_external.dm
Labels: size/XS

#5033 buffs the everloving heck out of corpsemend surgeries
  code/modules/surgery/external_repair.dm
Labels: size/S

#5028 Removes all egg sacks from Spider Cave
  _maps/map_files/rift/rift-06-surface3.dmm
Labels: Blocked - Administrative, ✔️Approved - Administrative, size/M

#5015 We Are Not In Virgo Anymore: Miaphus'irra
  _maps/map_levels/192x192/miaphus_beach.dmm
  _maps/map_levels/192x192/miaphus_cave.dmm
  _maps/map_levels/192x192/miaphus_desert.dmm
  citadel.dme
  code/game/turfs/simulated/flooring/flooring_decals.dm
  code/modules/maps/lateload/generic/planets_lateload.dm
  code/modules/maps/overmap/planets/miaphus.dm
  code/modules/maps/weather/miaphus.dm
  code/modules/paperwork/faxmachine.dm
  icons/turf/flooring/maglevs.dmi
  maps/rift/rift_defines.dm
  maps/rift/rift_weather.dm
Labels: size/XXL

#5024 Actually fixes statbrowser button text backgrounds
  html/statbrowser.html
Labels: size/XS

#5027 Faction Contractors - Detective Edition
  code/modules/lore_hardcoded/faction.dm
Labels: size/XS

#5037 Fixes Cryo Rooms being fullbright and not smoothing.
  _maps/map_files/rift/rift-02-underground2.dmm
  code/game/area/Space Station 13 areas.dm
Labels: size/M

#5041 fixes a tiny bug with GPS
  code/game/objects/items/devices/gps.dm
  tgui/packages/tgui/interfaces/Gps.tsx
Labels: size/XS

#5039 fixes the extra argument that causes runtime error
  code/modules/maps/weather/miaphus.dm
Labels: size/XS

#5046 Pepperspray and smoke effects
  code/modules/mob/living/carbon/human/human.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Food-Drinks.dm
Labels: size/XS

#5036 Species Id rather than Name for checks
  code/__HELPERS/global_lists.dm
  code/game/machinery/virtual_reality/ar_console.dm
  code/game/machinery/virtual_reality/vr_console.dm
  code/game/machinery/vr_console.dm
  code/game/objects/structures/charge_pylon.dm
  code/game/objects/structures/mineral_bath.dm
  code/modules/ai/aI_holder_subtypes/slime_xenobio_ai.dm
  code/modules/clothing/under/accessories/accessory.dm
  code/modules/clothing/under/accessories/clothing.dm
  code/modules/mob/_modifiers/modifiers_misc.dm
  code/modules/mob/_modifiers/unholy.dm
  code/modules/mob/living/carbon/alien/diona/diona_powers.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/carbon/human/human_powers.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/carbon/metroid/life.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Toxins.dm
  code/modules/species/xenomorphs/alien_powers.dm
  code/modules/virus2/effect.dm
  code/modules/vore/eating/leave_remains_vr.dm
  code/modules/vore/fluffstuff/custom_clothes.dm
  code/modules/xenobio/items/extracts.dm
  code/modules/xenobio/items/weapons.dm
Labels: Ready for Review, The Massive Refactor of The Week, Review - Code Quality, size/L

#5042 Cyberpsychosis Count Correction
  code/datums/components/cyberpsychosis.dm
Labels: size/XS

#5043 Map Adjustment: Armory Tweak/Nerf Edition
  _maps/map_files/rift/rift-05-surface2.dmm
Labels: size/M

#5057 Makes AltXenoes Able to Wear Suits (v2)
  code/modules/species/station/xenomorph_hybrids/xeno_hybrids.dm
Labels: size/XS

#5051 Makes Adjustments to Surt & Ashlanders
  _maps/map_levels/192x192/lavaland.dmm
  _maps/map_levels/192x192/lavaland_east.dmm
  code/modules/species/outsider/scori.dm
Labels: size/XXL

#5045 invoke_async performance boost
  code/__DEFINES/callbacks.dm
  code/datums/callback.dm
  code/game/objects/items/weapons/nullrod.dm
Labels: size/S

#5062 makes background restricted alt titles far less awful
  code/datums/mind.dm
  code/game/machinery/computer/timeclock_vr.dm
  code/modules/jobs/alt_title.dm
  code/modules/jobs/job.dm
  code/modules/preferences/preference_setup/occupation/occupation.dm
Labels: size/L

#5054 adds pumps to cargo
  code/modules/cargo/supplypacks/engineering.dm
Labels: size/XS

#5047 Adds Cobra Hood (Inner) Marking and Alternate Colorable Naga Tail
  code/modules/sprite_accessories/markings/unathi.dm
  code/modules/sprite_accessories/tail/taurs.dm
  icons/mob/sprite_accessories/markings/unathi_stuff.dmi
  icons/mob/sprite_accessories/taurs.dmi
Labels: size/S

#5056 fixes radiation mod & makes shadekin rad immune again
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/species/shadekin/shadekin.dm
  code/modules/species/shadekin/shadekin_blackeyed.dm
Labels: size/XS

#5044 TTS Devices now alert people when the user has started typing
  code/game/objects/items/devices/text_to_speech.dm
  sound/items/tts/started_type.ogg
  sound/items/tts/stopped_type.ogg
Labels: size/XS

#5053 buffs bags again
  code/game/objects/items/storage/bags.dm
Labels: size/XS

#5059 Renames a single Cargo supplypack
  code/modules/cargo/supplypacks/hospitality.dm
Labels: size/XS

#5038 Holomap performance tweaks
  code/modules/holomap/generate_holomap.dm
  code/modules/holomap/holomap_area.dm
Labels: size/L

#5063 Fixes Xenomorph tail sprites
  icons/mob/sprite_accessories/xeno_parts.dmi
  icons/mob/sprite_accessories/xeno_parts_darkend.dmi
Labels: size/XS

#5066 [CRITICAL ] Updates webpack to latest
  tgui/package.json
  tgui/yarn.lock
Labels: Priority 0: CRITICAL, size/L

#5058 Botany tweaks (also map)
  _maps/map_files/rift/rift-06-surface3.dmm
  code/game/objects/structures/crates_lockers/closets/secure/hydroponics.dm
Labels: size/XXL

#5009 Experimental AO Rewrite
  code/__DEFINES/rendering/ao.dm
  code/controllers/subsystem/ao.dm
  code/controllers/subsystem/zmimic.dm
  code/game/turfs/change_turf.dm
  code/game/turfs/turf_ao.dm
  icons/turf/flooring/shadows.dmi
Labels: Stale, size/L

#5061 Restricted Alt Titles: OSS&NECROPOLIS and Naramadi Guilds
  code/modules/jobs/job_types/station/engineering/atmospherics_technician.dm
  code/modules/jobs/job_types/station/engineering/senior_engineer.dm
  code/modules/jobs/job_types/station/engineering/station_engineer.dm
  code/modules/jobs/job_types/station/medical/chemist.dm
  code/modules/jobs/job_types/station/medical/head_nurse.dm
  code/modules/jobs/job_types/station/medical/medical_doctor.dm
  code/modules/jobs/job_types/station/medical/paramedic.dm
  code/modules/jobs/job_types/station/science/roboticist.dm
  code/modules/jobs/job_types/station/security/detective.dm
  code/modules/jobs/job_types/station/supply/cargo_technician.dm
  code/modules/jobs/job_types/station/supply/quartermaster.dm
Labels: Blocked by The Massive Refactor of The Week, size/L

#5067 Lore changes - Faction system
  code/modules/lore_hardcoded/faction.dm
Labels: size/M

#5079 Fix RnD Access
  _maps/map_files/rift/rift-05-surface2.dmm
Labels: size/S

#5068 Changes the seed vendor in Xenobotany to the Xenobotany variation
  _maps/map_files/rift/rift-04-surface1.dmm
Labels: size/XS

#5071 Replaces Voidsuit Units With Cryosuits (Aesthetic), Removes Infinite Powergen from Lythios Trade Store.
  _maps/map_files/rift/rift-02-underground2.dmm
  _maps/map_files/rift/rift-04-surface1.dmm
  _maps/map_files/rift/rift-05-surface2.dmm
  _maps/map_files/rift/rift-06-surface3.dmm
  _maps/map_files/rift/rift-09-west_caves.dmm
  _maps/map_files/rift/rift-11-orbital.dmm
  code/game/machinery/suit_storage/suit_storage_prepared.dm
Labels: size/XXL

#5075 Veymed S&R
  code/modules/lore_hardcoded/faction.dm
Labels: size/XS

#5097 Fix quad nanopaste
  code/modules/mob/living/silicon/robot/robot_modules/_robot_modules_defs.dm
  code/modules/mob/living/silicon/robot/robot_modules/station/science.dm
Labels: size/XS

#5096 Borg Lights 'n Sprites
  citadel.dme
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/mob/living/silicon/robot/robot_flashlights.dm
  code/modules/mob/living/silicon/robot/robot_modules/station/cargo.dm
  code/modules/mob/living/silicon/robot/robot_modules/station/engineering.dm
  code/modules/mob/living/silicon/robot/robot_modules/station/medical.dm
  code/modules/mob/living/silicon/robot/robot_modules/station/security.dm
  code/modules/mob/living/silicon/robot/robot_modules/station/service.dm
  icons/mob/robots_wide.dmi
  icons/mob/robots_wide_drake_credit.dmi
Labels: size/L

#5069 changes the warning prompt for character setup to only trigger on ready, rather than unready
  code/modules/mob/new_player/new_player.dm
Labels: size/S

#5078 disables maintenance hatch locks from circuitry
  code/modules/integrated_electronics/subtypes/manipulation.dm
Labels: size/XS

#5072 adds loot table system, reworks abandoned crates to be (slightly) less useless
  _maps/map_files/rift/rift-02-underground2.dmm
  _maps/map_files/rift/rift-04-surface1.dmm
  _maps/map_files/rift/rift-05-surface2.dmm
  _maps/map_files/tether/tether-01-surface1.dmm
  _maps/map_files/tether/tether-02-surface2.dmm
  _maps/map_files/tether/tether-05-station1.dmm
  _maps/map_files/tether/tether-06-station2.dmm
  _maps/map_files/triumph/triumph-01-deck1.dmm
  _maps/map_files/triumph/triumph-03-deck3.dmm
  _maps/templates/shuttles/overmaps/generic/cruiser.dmm
  citadel.dme
  code/__DEFINES/_lists.dm
  code/datums/prototype.dm
  code/modules/loot/pack.dm
  code/modules/loot/packs/archeology.dm
  code/modules/loot/packs/chemistry.dm
  code/modules/loot/packs/clothing.dm
  code/modules/loot/packs/gear.dm
  code/modules/loot/packs/hydroponics.dm
  code/modules/loot/packs/misc.dm
  code/modules/loot/packs/money.dm
  code/modules/loot/packs/ore.dm
  code/modules/loot/packs/science.dm
  code/modules/loot/packs/toys.dm
  code/modules/loot/packs/weapons.dm
  code/modules/loot/table.dm
  code/modules/loot/tables/crates.dm
  code/modules/mining/abandonedcrates.dm
  code/modules/rigsuits/_rig.dm
  code/modules/rigsuits/suits/station.dm
  code/modules/rigsuits/suits/station_vr.dm
  code/modules/unit_tests/prototypes.dm
Labels: size/XL

#5073 maybe fixes ai holders targeting asleep people who are allies
  code/modules/ai/ai_holder_targeting.dm
Labels: size/XS

#5100 Triangulation + Bioscanners
  _maps/map_files/rift/rift-01-underground3.dmm
  _maps/map_files/rift/rift-02-underground2.dmm
  _maps/map_files/rift/rift-03-underground1.dmm
  _maps/map_files/rift/rift-04-surface1.dmm
  _maps/map_files/rift/rift-05-surface2.dmm
  _maps/map_files/rift/rift-06-surface3.dmm
  _maps/map_files/rift/rift-07-west_base.dmm
  _maps/map_files/rift/rift-08-west_deep.dmm
  _maps/map_files/rift/rift-09-west_caves.dmm
  _maps/map_files/rift/rift-10-west_plains.dmm
  citadel.dme
  code/__DEFINES/_cooldowns.dm
  code/__DEFINES/misc/message_ranges.dm
  code/controllers/subsystem/mapping/obfuscation.dm
  code/game/atoms/atoms.dm
  code/game/atoms/atoms_appearance.dm
  code/game/atoms/say.dm
  code/game/machinery/_machinery.dm
  code/game/machinery/computer/misc/bioscan.dm
  code/game/machinery/misc/bioscan_antenna.dm
  code/game/machinery/telecomms/_telecomms.dm
  code/game/machinery/telecomms/allinone.dm
  code/game/machinery/telecomms/broadcaster.dm
  code/game/machinery/telecomms/broadcaster_vr.dm
  code/game/machinery/telecomms/bus.dm
  code/game/machinery/telecomms/hub.dm
  code/game/machinery/telecomms/logbrowser.dm
  code/game/machinery/telecomms/processor.dm
  code/game/machinery/telecomms/receiver.dm
  code/game/machinery/telecomms/relay.dm
  code/game/machinery/telecomms/server.dm
  code/game/machinery/telecomms/telecomunications.dm
  code/game/objects/items/circuitboards/computer/_computer.dm
  code/game/objects/items/circuitboards/computer/misc.dm
  code/game/objects/items/circuitboards/machinery/_machine.dm
  code/game/objects/items/circuitboards/machinery/misc.dm
  code/modules/automata/sonar.dm
  code/modules/research/designs/circuits/circuit.dm
  code/modules/research/designs/circuits/computer.dm
  code/modules/research/designs/circuits/computers/misc.dm
  code/modules/research/designs/circuits/machine.dm
  code/modules/research/designs/circuits/machines/misc.dm
  code/modules/tgui/tgui_input_text.dm
  icons/README.md
  icons/machinery/bioscan.dmi
  tgui/package.json
  tgui/packages/tgui/backend.ts
  tgui/packages/tgui/components/Collapsible.tsx
  tgui/packages/tgui/interfaces/README.md
  tgui/packages/tgui/interfaces/TelecommsLogBrowser.tsx
  tgui/packages/tgui/interfaces/computers/BioscanConsole.tsx
  tgui/packages/tgui/routes.js
  tgui/webpack.config.js
  tgui/yarn.lock
Labels: size/XXL

#5099 makes the radiocarbon spectrometer 10x faster
  code/modules/xenoarcheaology/tools/geosample_scanner.dm
Labels: size/XS

#5065 Sends a toast notification when initializations complete.
  citadel.dme
  code/controllers/configuration/entries/compile.dm
  code/controllers/master.dm
  config/config.txt
  icons/CS13_16.png
  tools/initToast/initToast.ps1
Labels: size/M

#5074 Adds a symbol replacement option for languages instead of syllables, adds Keisani language
  citadel.dme
  code/__DEFINES/languages/ids.dm
  code/__DEFINES/languages/legacy.dm
  code/__HELPERS/text.dm
  code/modules/language/language.dm
  code/modules/language/languages/species/keisani.dm
  interface/stylesheet.dm
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
Labels: size/L
