Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2023-06, with the labels that each got.

#5541 two minor fixes
  code/modules/jobs/job_types/station/command/command_secretary.dm
  code/modules/organs/internal/species/diona.dm
  code/modules/species/abilites.dm
  code/modules/species/protean/protean.dm
  code/modules/species/station/standard/teshari.dm
Labels: size/S

#5540 Adds Some Monotiles
  code/game/turfs/simulated/flooring/_flooring.dm
  code/game/turfs/simulated/flooring/flooring_premade.dm
  icons/turf/flooring/techfloor.dmi
  icons/turf/flooring/tiles.dmi
Labels: size/S

#5553 Clarifies major trojan event to be clearer.
  code/modules/events/prison_break.dm
Labels: size/XS

#5551 Adds the Braided Sidetail hairstyle.
  code/modules/sprite_accessories/hair/_hair.dm
  icons/mob/human_face_vr.dmi
  icons/mob/human_face_vr_add.dmi
Labels: size/XS

#5552 Removing a few non-standard pets
  maps/map_files/rift/rift-02-underground2.dmm
  maps/map_files/rift/rift-05-surface2.dmm
  maps/map_files/rift/rift-06-surface3.dmm
  maps/map_levels/192x192/lavaland.dmm
Labels: size/M

#5550 Snowtile fix
  maps/map_files/rift/rift-05-surface2.dmm
Labels: size/XS

#5546 sec maint floor door
  maps/map_files/rift/rift-05-surface2.dmm
Labels: size/S

#5554 Tajaran hunger increase
  code/modules/species/station/standard/tajaran.dm
Labels: size/XS

#5557 Fixes master
  code/modules/events/prison_break.dm
Labels: size/XS

#5558 Sapient Species Food Removal
  code/modules/food/food/snacks.dm
  code/modules/food/recipes_microwave.dm
  code/modules/food/recipes_oven.dm
  maps/map_files/rift/rift-03-underground1.dmm
  maps/map_levels/140x140/piratebase.dmm
Labels: Removal, size/M

#5548 Dissonant Shriek nerf
  code/modules/species/station/xenochimera.dm
Labels: size/XS

#5556 Helmet Cameras
  code/__DEFINES/inventory/accessories.dm
  code/__DEFINES/machinery.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/spacesuits/void/station.dm
  code/modules/clothing/under/accessories/armor.dm
  code/modules/modular_computers/computers/subtypes/preset_laptop.dm
  code/modules/modular_computers/file_system/programs/generic/camera.dm
  code/modules/tgui/modules/camera.dm
  icons/mob/clothing/ties.dmi
  icons/obj/clothing/Sprite-0002.dmi
  icons/obj/clothing/modular_armor.dmi
  maps/map_files/rift/rift-05-surface2.dmm
  maps/rift/rift_defines.dm
Labels: size/L

#5563 fixes a lighting bug
  code/modules/lighting/lighting_atom.dm
Labels: size/S

#5559 New roundstart sounds, picked at random
  code/controllers/subsystem/ticker.dm
  sound/roundStart/original_startup.ogg
  sound/roundStart/start_up_1.ogg
  sound/roundStart/start_up_2.ogg
  sound/roundStart/start_up_3.ogg
  sound/roundStart/start_up_4.ogg
Labels: size/S

#5564 removes precursor tech from the equipment vendors
  code/modules/mining/ore_redemption_machine/engineering_points_vendor.dm
  code/modules/mining/ore_redemption_machine/survey_vendor.dm
Labels: size/XS

#5561 ghost follow selection
  citadel.dme
  code/game/objects/items/devices/communicator/phone.dm
  code/modules/mob/observer/dead/dead.dm
  code/modules/mob/observer/dead/orbit.dm
  tgui/packages/tgui/interfaces/Orbit.js
  tgui/packages/tgui/interfaces/Orbit.tsx
Labels: size/XL

#5565 Adds a trim check for admin announcements
  code/modules/admin/admin.dm
Labels: size/XS

#5573 improvements to the ghost follow selection
  code/modules/mob/observer/dead/orbit.dm
  tgui/packages/tgui/interfaces/Orbit.tsx
Labels: size/S

#5566 Allure resprite and first modkit
  code/game/mecha/combat/fighter.dm
  code/game/objects/items/paintkit.dm
  icons/mecha/fighters64x64.dmi
Labels: size/S

#5555 Moghes Immunities: Hexaisin Edition
  code/modules/cargo/supplypacks/contraband.dm
  code/modules/cargo/supplypacks/hospitality.dm
  code/modules/food/food/snacks.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/species/station/standard/unathidigi.dm
Labels: size/L

#5576 removes admins being able to see subtlers
  code/modules/mob/say_vr.dm
Labels: size/S

#5580 Finally fixes the encryption reinforcing heater
  code/modules/power/crypto_miner.dm
Labels: size/S

#5574 prbt
  code/modules/mob/living/carbon/human/emote.dm
  sound/misc/prbt.ogg
Labels: size/XS

#5569 Cannibalnt
  code/game/objects/random/misc.dm
  code/modules/food/food/snacks.dm
  code/modules/food/recipes_oven.dm
  maps/map_levels/140x140/tradeport.dmm
  maps/map_levels/192x192/tradeport.dmm
Labels: size/M

#5572 Fighter landing mode
  code/__DEFINES/research/exosuit_fab.dm
  code/game/mecha/combat/fighter.dm
  code/game/mecha/mech_fabricator.dm
  code/game/mecha/mech_prosthetics.dm
  code/game/mecha/mecha_construction_paths.dm
  code/game/mecha/mecha_parts.dm
  code/game/objects/items/circuitboards/mecha.dm
  code/modules/research/designs/circuits/circuits.dm
  code/modules/research/mechfab_designs.dm
  icons/mecha/fighters_construct64x64.dmi
  icons/mecha/fighters_construction64x64.dmi
  sound/mecha/fighter/engine_mid_boost_01.ogg
  sound/mecha/fighter/engine_mid_fighter_move.ogg
Labels: Merge Conflict, size/XL

#5584 stupid DMI compatibility fix for #5572
  icons/mecha/fighters64x64.dmi
Labels: size/XS

#5577 Supermatter Monitoring Computer Graphs
  code/modules/power/supermatter/supermatter.dm
  code/modules/tgui/modules/supermatter_monitor.dm
  tgui/packages/tgui/interfaces/SupermatterMonitor.js
Labels: size/L

#5579 Hammerhead and Fighter Transit Tunnel
  code/game/area/Space Station 13 areas.dm
  code/game/area/rift_areas.dm
  code/modules/turbolift/turbolift_map.dm
  code/modules/vehicles/ridden/three_wheel_carts.dm
  maps/Generic/turbolifts.dm
  maps/map_files/rift/rift-01-underground3.dmm
  maps/map_files/rift/rift-02-underground2.dmm
  maps/map_files/rift/rift-03-underground1.dmm
  maps/map_files/rift/rift-04-surface1.dmm
  maps/map_files/rift/rift-05-surface2.dmm
  maps/map_files/rift/rift-06-surface3.dmm
  maps/map_files/rift/rift-07-west_base.dmm
  maps/map_files/rift/rift-08-west_deep.dmm
  maps/map_files/rift/rift-09-west_caves.dmm
  maps/map_files/rift/rift-10-west_plains.dmm
  maps/map_files/rift/rift-11-orbital.dmm
  maps/rift/rift_shuttles.dm
  maps/templates/admin/kk_mercship.dmm
Labels: size/XXL

#5519 adds shotgun slug holders + variants
  code/datums/autolathe/arms.dm
  code/modules/clothing/under/accessories/armor.dm
  code/modules/projectiles/magazines/unsorted.dm
  icons/mob/clothing/modular_armor.dmi
  icons/obj/ammo.dmi
  icons/obj/clothing/modular_armor.dmi
Labels: ✔️Approved - Code Quality, size/M

#5578 fixes a bunch of bugs
  code/modules/mob/living/simple_mob/simple_mob.dm
  code/modules/preferences/preference_setup/general/06_flavor.dm
Labels: size/XS

#5582 Ports canister sprites from bay
  icons/obj/atmos.dmi
Labels: size/XS

#5586 fixes some runtimes
  code/_rendering/plane_masters/plane_master.dm
  code/game/turfs/change_turf.dm
  code/game/turfs/turf.dm
  code/modules/clothing/glasses/_glasses.dm
Labels: size/S

#5592 fixes random hood runtime
  code/modules/clothing/suits/hooded.dm
Labels: size/XS

#5585 more cryptominer changes, because my PR got speed merged :)
  code/modules/cargo/supplypacks/atmospherics.dm
  code/modules/mining/ore_redemption_machine/engineering_points_vendor.dm
  code/modules/power/crypto_miner.dm
Labels: size/S

#5581 Teleporter half-rework
  code/game/machinery/teleporter/console.dm
  code/game/machinery/teleporter/pad.dm
  code/game/machinery/teleporter/projector.dm
  code/game/objects/items/circuitboards/frame.dm
  code/game/objects/items/devices/radio/beacon.dm
  maps/map_files/rift/rift-06-surface3.dmm
  tgui/packages/tgui/interfaces/TeleporterConsole.tsx
Labels: size/L

#5588 Duke+Awareness+Fervor Fighters
  code/__DEFINES/research/exosuit_fab.dm
  code/game/mecha/combat/fighter.dm
  code/game/mecha/mech_fabricator.dm
  code/game/mecha/mech_prosthetics.dm
  code/game/mecha/mecha_construction_paths.dm
  code/game/mecha/mecha_parts.dm
  code/game/objects/items/circuitboards/mecha.dm
  code/game/objects/items/paintkit.dm
  code/modules/research/designs/circuits/circuits.dm
  code/modules/research/mechfab_designs.dm
  code/modules/vehicles/ridden/three_wheel_carts.dm
  icons/mecha/fighters64x64.dmi
  icons/mecha/fighters_construct64x64.dmi
  icons/mecha/fighters_construction64x64.dmi
Labels: size/XL

#5593 removes unnecessary bit of perspectives
  code/_rendering/perspectives/perspective.dm
Labels: size/XS

#5599 Dark Green Cheongsam
  code/game/machinery/vending.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/mob/clothing/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: size/XS

#5602 Makes Proteans pretty again
  code/modules/species/protean/protean.dm
Labels: size/XS

#5598 Tail fixes
  code/modules/sprite_accessories/tail/feline.dm
  icons/mob/sprite_accessories/tails.dmi
Labels: size/XS

#5601 Take 2: Some fixes and QoL
  code/game/objects/items/circuitboards/machinery/mining_drill.dm
  code/modules/mining/drilling/drill.dm
  code/modules/mining/ore_datum.dm
  code/modules/research/designs/xenobio_toys.dm
Labels: size/M

#5611 fixes the recipe for mocha bubbletea
  code/modules/reagents/Drink-Recipes.dm
Labels: size/XS

#5609 Vetalan darksight "fix"
  code/modules/mob/living/carbon/human/traits/neutral.dm
Labels: size/XS

#5605 Adds orderable reflectors
  code/game/objects/structures/props/beam_prism.dm
  code/modules/cargo/supplypacks/engineering.dm
  code/modules/mining/ore_redemption_machine/engineering_points_vendor.dm
  icons/obj/reflector.dmi
Labels: size/M

#5614 adds donator item for rainbyplays (myself)
  code/modules/donatorreskins/donatorclothing.dm
  code/modules/preferences/preference_setup/loadout/loadout_donator.dm
  icons/mob/clothing/donatorclothing.dmi
Labels: size/S

#5610 adds medical exoframe accessory
  code/modules/clothing/under/accessories/accessory.dm
  code/modules/preferences/preference_setup/loadout/loadout_accessories.dm
  icons/mob/clothing/ties.dmi
  icons/obj/clothing/ties.dmi
Labels: size/S

#5613 client onboarding update
  citadel.dme
  code/__HELPERS/_logging.dm
  code/controllers/configuration/entries/shadowban.dm
  code/controllers/subsystem/job/roundstart.dm
  code/game/objects/items/devices/communicator/messaging.dm
  code/modules/admin/verbs/adminhelp.dm
  code/modules/client/client_data.dm
  code/modules/client/verbs/ooc.dm
  code/modules/ghostroles/role.dm
  code/modules/mob/living/silicon/robot/drone/drone_manufacturer.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/mob/observer/dead/dead.dm
  code/modules/mob/say.dm
Labels: MEME PR, size/M

#5619 updates euthenia to use new map format
  maps/euthenia/euthenia.dm
  maps/euthenia/levels/deck1.dmm
  maps/euthenia/levels/deck2.dmm
  maps/euthenia/levels/deck3.dmm
  maps/euthenia/levels/deck4.dmm
  maps/euthenia/levels/deck5.dmm
  maps/euthenia/levels/misc.dmm
  maps/map_files/NSV_Euthenia/lazy_overmap.dmm
  maps/map_files/NSV_Euthenia/multizship.dmm
  maps/nsv_euthenia/euthenia.dm
  maps/nsv_euthenia/euthenia_defines.dm
Labels: size/XXL

#5625 Ports 15 or so SPLURT hairs
  code/modules/sprite_accessories/hair/_hair.dm
  icons/mob/human_face_vr.dmi
  icons/mob/human_face_vr_add.dmi
Labels: size/L

#5612 Navy Jumpsuit+blindfold changes
  code/modules/clothing/glasses/_glasses.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/preferences/preference_setup/loadout/loadout_eyes.dm
  icons/clothing/uniform/rank/utility.dmi
  icons/mob/clothing/uniform.dmi
  icons/obj/clothing/uniforms.dmi
Labels: size/M

#5623 fixes loadout bug with donatornoahcloak
  code/modules/donatorreskins/donatorclothing.dm
  code/modules/preferences/preference_setup/loadout/loadout_donator.dm
Labels: size/XS

#5629 Navy grey jumpsuit fix
  code/modules/clothing/under/miscellaneous.dm
  icons/clothing/uniform/rank/utility.dmi
Labels: size/XS

#5618 buffs wallflowering
  code/__DEFINES/mobs/mobs.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/movement.dm
Labels: size/M

#5626 fixes cazz's donator item not being compiled in
  citadel.dme
Labels: size/XS

#5615 create_photo is now more adminbussable
  code/modules/photography/photo.dm
Labels: size/XS

#5616 changes loadout categories to use defines / removes some redundant lines of code in loadout code
  citadel.dme
  code/__DEFINES/loadout.dm
  code/modules/holidays/christmas_loadout.dm
  code/modules/holidays/halloween_loadout.dm
  code/modules/preferences/preference_setup/loadout/loadout.dm
  code/modules/preferences/preference_setup/loadout/loadout_accessories.dm
  code/modules/preferences/preference_setup/loadout/loadout_cosmetics.dm
  code/modules/preferences/preference_setup/loadout/loadout_donator.dm
  code/modules/preferences/preference_setup/loadout/loadout_ears.dm
  code/modules/preferences/preference_setup/loadout/loadout_event_rewards.dm
  code/modules/preferences/preference_setup/loadout/loadout_eyes.dm
  code/modules/preferences/preference_setup/loadout/loadout_gloves.dm
  code/modules/preferences/preference_setup/loadout/loadout_head.dm
  code/modules/preferences/preference_setup/loadout/loadout_mask.dm
  code/modules/preferences/preference_setup/loadout/loadout_role_restricted.dm
  code/modules/preferences/preference_setup/loadout/loadout_seasonal.dm
  code/modules/preferences/preference_setup/loadout/loadout_shoes.dm
  code/modules/preferences/preference_setup/loadout/loadout_suit.dm
  code/modules/preferences/preference_setup/loadout/loadout_uniform.dm
  code/modules/preferences/preference_setup/loadout/loadout_utility.dm
  code/modules/preferences/preference_setup/loadout/loadout_xeno.dm
Labels: size/M

#5631 makes the instant pick up pref actually work
  code/modules/vore/resizing/resize_vr.dm
Labels: size/S

#5633 fixes the reaper scythe nullrod held item sprite not appearing
  icons/mob/items/lefthand_melee.dmi
  icons/mob/items/righthand_melee.dmi
Labels: size/XS

#5622 small memory optimziations
  code/modules/random_map/noise/ore.dm
  maps/sectors/miaphus_192/miaphus_192.dm
Labels: size/S

#5630 fixes ReplaceWithLattice
  code/game/turfs/change_turf.dm
Labels: size/XS

#5637 fixes observers not having the right invis values
  code/modules/mob/observer/observer.dm
Labels: size/XS

#5639 Fixes SM ejection vent button
  maps/rift/levels/rift-02-underground2.dmm
Labels: size/XS

#5627 make cryo player use tgui list select
  code/modules/admin/verbs/randomverbs.dm
Labels: size/XS

#5636 Makes medical belts able to hold hypospray vials.
  code/game/objects/items/storage/belt.dm
Labels: size/XS

#5635 fixes a handful of missing sprites
  code/game/machinery/Sleeper.dm
  code/game/objects/items/weapons/tanks/tank_types.dm
  code/game/objects/structures/statues.dm
  icons/turf/flooring/plating.dmi
  maps/rift/levels/rift-11-orbital.dmm
Labels: size/M

#5638 adds a limit to the number of markings you can have (30)
  code/__DEFINES/preferences/misc.dm
  code/modules/preferences/preference_setup/general/03_body.dm
Labels: size/XS

#5641 Ports blast door and shutter sound effects from Baystation
  code/game/machinery/doors/blast_door.dm
  sound/machines/blastdoor_close.ogg
  sound/machines/blastdoor_open.ogg
  sound/machines/shutters_close.ogg
  sound/machines/shutters_open.ogg
Labels: size/XS

#5640 You can now handcuff a lying mob
  code/game/objects/items/weapons/handcuffs.dm
Labels: size/XS

#5632 removes the wood recipe for the (bone) horse post
  code/modules/materials/material_recipes.dm
Labels: size/XS

#5590 Aether Displacement Engine
  citadel.dme
  code/game/machinery/vitruvius/anti_heater.dm
  icons/machinery/vitruvius/iris.dmi
Labels: Work in Progress, size/M

#5645 removes windows build from actions / ci_suite
  .github/workflows/ci_suite.yml
Labels: size/M

#5643 some tiny optimizations/shifting things around, removes 2 unused files
  citadel.dme
  code/__DEFINES/controllers/_subsystems.dm
  code/__HELPERS/icons.dm
  code/__HELPERS/lists/types_typecaches.dm
  code/_globals/lists/names.dm
  code/_globals/lists/typecache.dm
  code/controllers/subsystem/early_init.dm
  code/datums/locations/locations.dm
  code/datums/locations/nyx.dm
  code/datums/locations/qerrvallis.dm
  code/datums/locations/s_randarr.dm
  code/datums/locations/sol.dm
  code/datums/locations/tau_ceti.dm
  code/datums/locations/uueoa_esa.dm
  code/datums/locations/vir.dm
  code/game/gamemodes/changeling/changeling_powers.dm
  code/game/gamemodes/changeling/modularchangling.dm
  code/game/gamemodes/technomancer/catalog.dm
  code/game/sd_Alert.dm
  code/game/trader_visit.dm
  code/modules/admin/admin_verbs.dm
  code/modules/mob/inventory/slot_meta.dm
  code/modules/mob/living/carbon/give.dm
  code/modules/mob/living/simple_mob/subtypes/vore/morph/morph.dm
  code/modules/mob/living/simple_mob/subtypes/vore/solargrub_larva.dm
  code/modules/nanites/chamber.dm
  code/modules/spells/spell_code.dm
  interface/interface.dm
  interface/menus/main.dm
Labels: size/XL

#5648 Remove deadzone at the start of blastdoor open
  sound/machines/blastdoor_open.ogg
Labels: size/XS

#5646 makes markings transfer over when ahealed/regenerating + aheals dont remove NIFs
  code/modules/mob/living/carbon/human/health.dm
  code/modules/organs/organ.dm
  code/modules/species/species.dm
  code/modules/species/station/xenochimera.dm
Labels: size/M

#5652 fixes a bug
  code/modules/admin/secrets/admin_secrets/admin_logs.dm
Labels: Priority 0: CRITICAL, size/XS

#5621 Nightshift Color/Brightness
  code/__DEFINES/color/lights.dm
  code/controllers/subsystem/nightshift.dm
  code/modules/power/lighting/lights.dm
  maps/rift/levels/rift-05-surface2.dmm
  maps/rift/levels/rift-06-surface3.dmm
Labels: size/M

#5653 gc fixes
  code/___compile_options.dm
  code/controllers/subsystem/garbage.dm
  code/modules/admin/view_variables/reference_tracking.dm
  maps/minitest/levels/minitest.dmm
Labels: size/M

#5651 fixes a bunch of runtimes
  code/controllers/subsystem/characters/species.dm
  code/game/atoms/movable/throwing.dm
  code/game/machinery/computer/atmos_alert.dm
  code/game/machinery/computer/station_alert.dm
  code/modules/atmospherics/machinery/components/binary_devices/valve.dm
  code/modules/clothing/clothing_accessories.dm
  code/modules/clothing/suits/eventclothing.dm
  code/modules/clothing/under/accessories/holster.dm
  code/modules/tgui/modules/general/cardmod.dm
Labels: size/M

#5650 t3 darksight is actually fullscreen now
  code/__DEFINES/rendering/darksight.dm
Labels: size/XS

#5660 Navy Pcarrier Pouches
  maps/rift/levels/rift-05-surface2.dmm
Labels: size/M

#5659 fixes planet generation
  code/controllers/subsystem/mapping/levels.dm
Labels: Priority 0: CRITICAL, size/XS
