Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2023-10, with the labels that each got.

#6028 fixes canisters not closing valve on eject
  code/modules/atmospherics/machinery/portable/canister.dm
  code/modules/atmospherics/machinery/portable/portable_atmospherics.dm
Labels: size/S

#6031 Makes banana mama/silencer non-alcoholic
  code/modules/food/drinkingglass/metaglass.dm
  code/modules/reagents/Drink-Recipes.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Food-Drinks.dm
Labels: size/S

#6034 fixes a prosthetics printing bug
  code/modules/research/designs/prosfab_designs.dm
Labels: hacktoberfest-accepted, size/XS

#6037 Airalarms now tolerate small amounts of toxic gas
  code/__DEFINES/atmospherics/machinery/alarm.dm
Labels: size/XS

#6038 allows admins to make cast votes invisible to normal users
  code/controllers/subsystem/vote.dm
  tgui/packages/tgui/interfaces/Vote.tsx
Labels: size/S

#6041 Adds Fake Changeling Claw Gloves to Masquerade
  code/modules/holidays/halloween_loadout_masquarade.dm
Labels: size/S

#6036 life crystals need to be equiped by their owner
  citadel.dme
  code/modules/vore/fluffstuff/custom_items.dm
  code/modules/vore/fluffstuff/life_crystals.dm
Labels: size/L

#6047 fixes wood recipe gen
  code/modules/materials/definitions/organic/wood/plank.dm
Labels: size/S

#6049 Fixes Various Icon Bugs
  code/game/gamemodes/cult/cult_items.dm
  code/game/gamemodes/cult/runes.dm
  code/game/objects/items/weapons/material/foam.dm
  code/game/objects/random/mapping.dm
  code/modules/clothing/head/hood.dm
  code/modules/clothing/suits/hooded.dm
  code/modules/food/recipes_microwave.dm
  code/modules/holidays/halloween_loadout_masquarade.dm
  code/modules/maps/away_missions/archive/labyrinth.dm
  code/modules/xenoarcheaology/finds/find_spawning.dm
  icons/clothing/suit/antag/cult.dmi
  icons/clothing/suit/antag/heretic.dmi
  icons/clothing/suit/armor/cult.dmi
  icons/clothing/suit/armor/traumateam.dmi
  icons/mob/clothing/head.dmi
  icons/mob/clothing/suits.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/suits.dmi
  maps/rift/levels/rift-11-orbital.dmm
Labels: size/L

#6043 actually makes alcohol visible in reagent containers
  code/modules/food/food/drinks.dm
Labels: size/XS

#6045 adds mermaid and alt mermaid taur parts, also an alt version of the naga taur with a tailmaw
  code/modules/sprite_accessories/tail/taurs.dm
  icons/mob/sprite_accessories/taurs.dmi
Labels: size/S

#6051 fixes tables
  code/modules/materials/definitions/legacy.dm
  code/modules/tables/tables.dm
  icons/obj/tables.dmi
Labels: size/XS

#6048 Fixes Openable Snack Traits Passing to Fruit
  code/modules/food/food/snacks.dm
Labels: size/M

#6053 Makes Mecha Components Recyclable
  code/game/mecha/components/actuators.dm
  code/game/mecha/components/armor.dm
  code/game/mecha/components/electrical.dm
  code/game/mecha/components/hull.dm
  code/game/mecha/components/lifesupport.dm
Labels: size/XS

#6042 Adds Aquiline Enforcer Helmet and Tourist Costume (October 2023 General Costume Addition PR)
  code/game/machinery/vending.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/holidays/halloween_loadout.dm
  code/modules/loadout/loadout_shoes.dm
  code/modules/loadout/loadout_uniform.dm
  icons/clothing/uniform/costume/aquiline.dmi
  icons/clothing/uniform/misc/tourist.dmi
Labels: size/M

#6035 Makes air alarms tolerate tiny amounts of phoron
  code/modules/atmospherics/gasmixtures/gas_types/core.dm
Labels: hacktoberfest-accepted, size/XS

#6061 Adds Janitor ERT Obj Icon
  icons/obj/rig_modules.dmi
Labels: size/XS

#6060 Adds the Kenjyu Kimono Donator Item
  code/modules/donatorreskins/donatorclothing.dm
  donator/legacy.dm
  icons/clothing/donator/uniform/desu.dmi
  icons/clothing/donator/uniform/hedduh.dmi
  icons/clothing/donator/uniform/phish.dmi
  icons/clothing/donator/uniform/soda.dmi
  icons/mob/clothing/donatorclothing.dmi
  icons/obj/clothing/donatorclothing.dmi
Labels: size/L

#6059 Fixes Sealed Food Inheritance
  code/modules/food/food/snacks.dm
Labels: size/S

#6057 Antediluvian dress + more heels
  code/modules/clothing/shoes/miscellaneous.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/loadout/loadout_shoes.dm
  code/modules/loadout/loadout_uniform.dm
  icons/clothing/shoes/ante_aziru.dmi
  icons/clothing/uniform/misc/ante_aziru.dmi
Labels: size/M

#6039 bellydancer outfit in halloween loadout
  code/modules/holidays/halloween_loadout.dm
Labels: Do Not Merge, size/S

#6054 Fixes Toy Sword Icon & Rewrites It to Use E-Sword Procs.
  code/game/objects/items/toys.dm
Labels: size/M

#6055 Returns Security Vest and Helmet to Lockers
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
Labels: size/XS

#6040 Adds an Invisible Satchel to the Seasonal Halloween Loadout
  code/game/objects/items/storage/backpack.dm
  code/modules/holidays/halloween_loadout_masquarade.dm
  code/modules/preferences/preference_setup/general/04_equipment.dm
Labels: size/S

#6063 fixes stasis bag attack hand, makes stasis bags reusable
  code/game/objects/items/bodybag.dm
  code/game/objects/items/robobag.dm
Labels: size/M

#6064 Fixes inflatables being inflatable when torn
  code/game/objects/structures/inflatable.dm
Labels: size/S

#6071 [s] fixes subtler
  code/modules/mob/say_vr.dm
Labels: size/XS

#6067 fixes holopad signing
  code/modules/mob/living/say.dm
Labels: size/XS

#6074 fixes vore prefbreaks
  code/modules/vore/eating/living_vr.dm
Labels: size/XS

#6075 fixes faxes not showing up in command consoles
  code/modules/modular_computers/file_system/programs/command/comm.dm
Labels: size/S

#6077 adds a range (3 tiles) to subtle notification message
  code/modules/mob/say_vr.dm
Labels: size/XS

#6069 Adds the Cosmic Winter Coat to the Loadout System
  code/modules/loadout/loadout_suit.dm
Labels: size/XS

#6078 Belly dancer outfit as halloween costume
  code/modules/holidays/halloween_loadout_masquarade.dm
Labels: size/M

#6080 fixes signlang
  code/modules/mob/living/say.dm
Labels: size/XS

#6079 Connects Lower Medbay Maint, adds CE/CMO request consoles
  maps/rift/levels/rift-02-underground2.dmm
  maps/rift/levels/rift-04-surface1.dmm
Labels: size/M

#6073 carry weight fixes
  code/__DEFINES/inventory/carry_weight.dm
  code/game/objects/items.dm
  code/modules/movespeed/movespeed_modifier.dm
Labels: size/S

#6081 Gives the Triumph SMES room expansion wires
  maps/triumph/levels/deck1.dmm
Labels: size/M

#6085 stops lowwall window stacking
  code/game/objects/structures/low_wall.dm
Labels: size/XS

#6062 The Krisitik Species
  citadel.dme
  code/__DEFINES/inventory/bodytypes.dm
  code/__DEFINES/languages/ids.dm
  code/__DEFINES/species/species.dm
  code/game/machinery/suit_storage/suit_cycler.dm
  code/modules/catalogue/catalogue_data.dm
  code/modules/hardsuits/rig_pieces.dm
  code/modules/language/languages/species/altevian.dm
  code/modules/language/languages/species/krisitik.dm
  code/modules/mob/living/carbon/human/human_species.dm
  code/modules/species/station/standard/krisitik.dm
  icons/mob/species/krisitik/body.dmi
  icons/mob/species/krisitik/husk.dmi
  icons/mob/species/krisitik/preview.dmi
Labels: size/L

#6087 Spooky Races and Krisitik Renormalizing
  code/modules/mob/living/carbon/human/human_species.dm
  code/modules/species/station/standard/krisitik.dm
Labels: size/L

#6070 Adds Two More Gimmick Drink Flavors
  code/game/machinery/vending.dm
  code/modules/food/food/cans.dm
  code/modules/reagents/Drink-Recipes.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Food-Drinks.dm
  icons/obj/drinks.dmi
Labels: size/M

#6072 Adjusts Silencer Code and Adds 9mm Compact Double Stack
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/ballistic.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  code/modules/projectiles/guns/projectile/semiauto.dm
  code/modules/projectiles/guns/projectile/sniper.dm
  code/modules/projectiles/magazines/unsorted.dm
  code/modules/vore/fluffstuff/custom_guns.dm
  icons/mob/items/lefthand_guns.dmi
  icons/mob/items/righthand_guns.dmi
  icons/obj/gun/ballistic.dmi
  icons/obj/toy.dmi
Labels: size/L

#6083 Makes more fish count as fish for fishing
  code/__DEFINES/fishing/fishing.dm
  code/modules/fishing/equipment/hook.dm
Labels: size/XS

#6090 Make gas analyzers show volume
  code/modules/atmospherics/gasmixtures/gas_mixture.dm
Labels: size/XS

#6089 Gives the tcomms substations starting power
  code/modules/power/smes/smes.dm
  maps/rift/levels/rift-03-underground1.dmm
  maps/tether/levels/surface2.dmm
  maps/triumph/levels/deck1.dmm
Labels: size/XL

#6056 Removes redundant and misleading alt-titles, adds title_blurbs to a lot that remain, adds one or two more alt-titles
  code/game/landmarks/spawnpoint/station/jobs.dm
  code/modules/jobs/job_types/station/civillian/assistant.dm
  code/modules/jobs/job_types/station/civillian/chaplain.dm
  code/modules/jobs/job_types/station/civillian/internals_affairs_agent.dm
  code/modules/jobs/job_types/station/civillian/pilot.dm
  code/modules/jobs/job_types/station/command/captain.dm
  code/modules/jobs/job_types/station/command/command_secretary.dm
  code/modules/jobs/job_types/station/command/head_of_personnel.dm
  code/modules/jobs/job_types/station/engineering/atmospherics_technician.dm
  code/modules/jobs/job_types/station/engineering/chief_engineer.dm
  code/modules/jobs/job_types/station/engineering/senior_engineer.dm
  code/modules/jobs/job_types/station/engineering/station_engineer.dm
  code/modules/jobs/job_types/station/exploration/explorer.dm
  code/modules/jobs/job_types/station/exploration/field_medic.dm
  code/modules/jobs/job_types/station/exploration/pathfinder.dm
  code/modules/jobs/job_types/station/medical/chief_medical_officer.dm
  code/modules/jobs/job_types/station/medical/head_nurse.dm
  code/modules/jobs/job_types/station/medical/medical_doctor.dm
  code/modules/jobs/job_types/station/medical/paramedic.dm
  code/modules/jobs/job_types/station/medical/psychiatrist.dm
  code/modules/jobs/job_types/station/science/research_director.dm
  code/modules/jobs/job_types/station/science/roboticist.dm
  code/modules/jobs/job_types/station/science/scientist.dm
  code/modules/jobs/job_types/station/science/senior_researcher.dm
  code/modules/jobs/job_types/station/security/detective.dm
  code/modules/jobs/job_types/station/security/warden.dm
  code/modules/jobs/job_types/station/supply/quartermaster.dm
  code/modules/jobs/job_types/station/supply/shaft_miner.dm
Labels: size/L

#6068 Woah! Nice Clock(work tools)!
  code/__DEFINES/spans.dm
  code/datums/recipe/crafting_recipes/recipes_misc.dm
  code/datums/wires/wires.dm
  code/game/objects/items/devices/multitool.dm
  code/game/objects/items/tools/crowbar.dm
  code/game/objects/items/tools/screwdriver.dm
  code/game/objects/items/tools/weldingtool.dm
  code/game/objects/items/tools/wirecutters.dm
  code/game/objects/items/tools/wrench.dm
  code/game/objects/random/misc.dm
  icons/obj/clockwork.dmi
Labels: size/L

#6084 Adds Quicksilver to Triumph Central Command
  code/modules/maps/overmap/space/centcom.dm
  code/modules/maps/overmap/space/triumph/triumph.dm
  code/modules/maps/templates/misc_presets/triumph_shuttle_landmarks.dm
  maps/rift/levels/rift-11-orbital.dmm
  maps/triumph/levels/deck2.dmm
  maps/triumph/levels/deck4.dmm
  maps/triumph/levels/flagship.dmm
  maps/triumph/levels/transit.dmm
Labels: size/XXL

#6088 Adds New Apidean Chair & Fixes Utilitarian Helmet
  code/game/objects/structures/stool_bed_chair_nest/chairs.dm
  code/modules/materials/definitions/misc/wax.dm
  icons/clothing/suit/armor/utilitarian.dmi
  icons/obj/furniture_vr.dmi
Labels: size/S

#6093 adds fingerless gloves (as gloves)
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/loadout/loadout_gloves.dm
  icons/clothing/gloves/fingerless.dmi
Labels: size/S

#6096 Gives senior engineer access to some loadout entries
  code/modules/loadout/loadout_role_restricted.dm
  code/modules/loadout/loadout_xeno.dm
Labels: size/S

#6091 Jukebox Repair
  config_static/jukebox.json
Labels: size/L

#6092 Fixes Gygax Paint Kits and North-Facing Pew Center Seats
  code/game/objects/items/paintkit.dm
  icons/obj/sofas.dmi
Labels: size/XS

#6086 Nerfs Pyro Mouse and Tweaks/Buffs Living Statue
  code/modules/mob/living/simple_mob/subtypes/animal/space/mouse_army.dm
  code/modules/mob/living/simple_mob/subtypes/occult/living_statue.dm
  code/modules/projectiles/projectile/bullets.dm
Labels: size/M

#6095 fixes captain ids
  code/game/objects/items/id_cards/station_ids.dm
Labels: size/S

#6094 darkens hair
  icons/mob/human_face.dmi
Labels: size/XS

#6097 Krisitik Origins
  citadel.dme
  code/modules/lore_hardcoded/species/krisitik/_base.dm
  code/modules/lore_hardcoded/species/krisitik/citizenship.dm
  code/modules/lore_hardcoded/species/krisitik/culture.dm
  code/modules/lore_hardcoded/species/krisitik/origin.dm
  code/modules/lore_hardcoded/species/krisitik/religion.dm
Labels: size/M

#6100 Fixes Abstract Bug for Wrapped Snack Subtype
  code/modules/food/food/snacks.dm
Labels: size/XS

#6108 General Bugfixes 10/23
  code/game/objects/items/id_cards/station_ids.dm
  code/game/objects/items/weapons/material/misc.dm
  code/modules/power/solar.dm
  icons/mob/animal.dmi
  icons/obj/weapons.dmi
Labels: size/S

#6107 Reverts 6056's changes to Facility Director
  code/modules/jobs/job_types/station/command/captain.dm
Labels: size/S

#6102 Jukebox Update
  config_static/jukebox.json
Labels: size/XL

#6109 Adds 8 SIGNALIS-Inspired hairstyles
  code/modules/sprite_accessories/hair/_hair.dm
  icons/mob/human_face_vr.dmi
  icons/mob/human_face_vr_add.dmi
Labels: size/M

#6110 bugfixes
  code/game/machinery/lathes/lathe.dm
  code/game/mecha/equipment/tools/passenger.dm
  code/game/objects/items/stacks/stack.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/head/helmet.dm
  code/modules/clothing/head/hood.dm
  code/modules/clothing/head/pilot_helmet.dm
  code/modules/clothing/spacesuits/alien.dm
  code/modules/clothing/spacesuits/miscellaneous.dm
  code/modules/clothing/spacesuits/spacesuits.dm
  code/modules/clothing/suits/armor.dm
  code/modules/clothing/suits/bio.dm
  code/modules/clothing/suits/hooded.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/suits/utility.dm
  code/modules/hardsuits/rig_pieces.dm
  code/modules/hardsuits/suits/light.dm
  code/modules/hardsuits/suits/species/vox.dm
  code/modules/jobs/job_types/station/science/roboticist.dm
  code/modules/nifsoft/software/06_screens.dm
  code/modules/power/cable.dm
  code/modules/reagents/items/hypospray.dm
  tgui/packages/tgui/interfaces/common/Materials.tsx
Labels: size/L

#6111 fixes stasis bags
  code/game/objects/items/bodybag.dm
Labels: size/XS
