Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2024-05, with the labels that each got.

#6408 Fixes Nebula Docking issues.
  code/modules/maps/overmap/space/trade_station/trade_station.dm
  maps/sectors/tradeport/shuttles.dm
  maps/sectors/tradeport_192/levels/tradeport_192.dmm
Labels: size/XL

#6416 promethean number tweaks
  code/modules/organs/external/species/slime.dm
  code/modules/species/promethean/promethean.dm
Labels: size/S

#6417 adds 2 new plushies, makes snowflake plushies show the player name on the loadout
  code/modules/loadout/loadout_general.dm
  fluff/plushies/plushies.dm
  fluff/plushies/plushies.dmi
Labels: size/S

#6419 removes weird ooc 'Craft me!' scanner module in atlas geothermal, replaces with note
  maps/rift/levels/rift-09-west_caves.dmm
Labels: size/S

#6423 Prevents vines from infinitely spreading from below
  code/modules/hydroponics/spreading/spreading_growth.dm
Labels: size/XS

#6418 Reduces chance of paroxetine hallucination
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Medicine.dm
Labels: size/XS

#6424 fixes emps, tweaks protean balancing number sagain
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/organs/external/external.dm
  code/modules/organs/subtypes/nano.dm
  code/modules/power/cell.dm
  code/modules/projectiles/projectile/special.dm
  code/modules/species/protean/protean.dm
  code/modules/species/protean/protean_blob.dm
Labels: size/M

#6395 Atlas Engine Rotation
  citadel.dme
  maps/rift/engines.dm
  maps/rift/engines/burn.dmm
  maps/rift/engines/rust.dmm
  maps/rift/engines/sme.dmm
  maps/rift/levels/rift-02-underground2.dmm
  maps/rift/levels/rift-03-underground1.dmm
Labels: size/XXL

#6429 Chimera space fix
  code/modules/species/station/xenochimera.dm
Labels: size/XS

#6422 Blowing your head no longer runtimes the server
  code/modules/organs/external/subtypes/standard.dm
Labels: size/XS

#6426 Ponchos and Gaiters, oh my!
  code/modules/clothing/under/accessories/accessory.dm
  code/modules/clothing/under/accessories/clothing.dm
  code/modules/loadout/loadout_suit.dm
  icons/mob/clothing/mask.dmi
  icons/mob/clothing/ties.dmi
  icons/obj/clothing/ties.dmi
Labels: size/M

#6432 About the life of a xenomorph Part 1
  citadel.dme
  code/modules/library/hardcode_library/reference/xenomorph_facts.dm
Labels: size/L

#6431 fixes the waggable xenomorph tail
  code/modules/sprite_accessories/tail/species/xenomorph.dm
Labels: size/XS

#6433 changes heat exchanger density so they dont just look like you cant walk over them
  code/modules/atmospherics/machinery/components/unary/heat_exchanger.dm
Labels: size/XS

#6434 Fluff Licenses!
  code/game/objects/items/id_cards/cards.dm
  code/modules/loadout/loadout_general.dm
  icons/obj/card_fluff.dmi
Labels: size/L

#6427 JSDF Rifle unloaded state fix
  code/modules/vore/fluffstuff/custom_guns.dm
Labels: size/S

#6438 fixes the sensors console double initing papers
  code/modules/overmap/legacy/ships/computers/sensors.dm
Labels: size/XS

#6436 removes bypassing disposalpipe that prevents stuff from being shiped to bar
  maps/rift/levels/rift-06-surface3.dmm
Labels: size/XS

#6430 Overhaul of alcohol to use proof instead of vague "strength", stack different, last longer (?)
  code/modules/organs/internal/subtypes/liver.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Dispenser.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Food-Drinks.dm
Labels: size/XL

#6367 Attempt to Add a second civilian shuttle on atlas
  code/game/area/station/shuttle_area.dm
  code/modules/maps/overmap/planets/_lythios43c.dm
  code/modules/maps/templates/misc_presets/rift_shuttle_landmarks.dm
  maps/rift/levels/rift-06-surface3.dmm
  maps/rift/levels/rift-11-orbital.dmm
  maps/rift/shuttles.dm
Labels: size/XXL

#6444 Makes canes/crutches usable for amputees
  code/modules/loadout/loadout_general.dm
  code/modules/mob/living/carbon/human/human_organs.dm
Labels: Currently Testmerged, Test Merge Candidate, size/XS

#6435 makes Planetary solars use the local time and weather for calculations, instead of some random subsystem in the background
  code/datums/sun.dm
  code/modules/power/solar.dm
Labels: Currently Testmerged, Test Merge Candidate, size/L

#6425 caseless rifle bonanza
  code/game/objects/random/guns_and_ammo.dm
  code/modules/projectiles/ammunition/rounds.dm
  code/modules/projectiles/guns/projectile/caseless.dm
  code/modules/projectiles/magazines/unsorted.dm
  code/modules/projectiles/projectile/bullets.dm
  icons/mob/items/lefthand_guns.dmi
  icons/mob/items/righthand_guns.dmi
  icons/obj/ammo.dmi
  icons/obj/gun/ballistic.dmi
Labels: Currently Testmerged, Test Merge Candidate, size/L

#6442 adds trees to atlas
  maps/rift/levels/rift-03-underground1.dmm
  maps/rift/levels/rift-04-surface1.dmm
  maps/rift/levels/rift-05-surface2.dmm
  maps/rift/levels/rift-06-surface3.dmm
  maps/rift/levels/rift-10-west_plains.dmm
Labels: size/XXL

#6443 adds a bookshelf that spawns with a number of random lore books
  citadel.dme
  code/game/objects/random/books.dm
  code/modules/library/lib_items.dm
  maps/rift/levels/rift-04-surface1.dmm
Labels: Currently Testmerged, Test Merge Candidate, size/M

#6445 tweaked minor thing on the latejoin panel
  tgui/packages/tgui/interfaces/JoinMenu.tsx
Labels: Currently Testmerged, Test Merge Candidate, size/M

#6440 Minilathe for medical, it produces syringes, empty auto injectors, beakers, gloves, surgical masks, and some other things
  citadel.dme
  code/controllers/subsystem/research.dm
  code/datums/design/designs/medical/chemistry.dm
  code/datums/design/designs/medical/consumables.dm
  code/datums/design/designs/medical/sterile_wear.dm
  code/game/machinery/lathes/medical_lathe.dm
  code/game/objects/items/storage/medical/firstaid.dm
  code/game/objects/items/weapons/material/armor.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/masks/miscellaneous.dm
  code/modules/reagents/items/hypovial.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  code/modules/reagents/reagent_containers/syringes.dm
  icons/machinery/lathe/microlathe.dmi
  maps/rift/levels/rift-05-surface2.dmm
  maps/tether/levels/surface3.dmm
  maps/triumph/levels/deck3.dmm
Labels: Currently Testmerged, Test Merge Candidate, size/L

#6420 Bugfix /obj/structure/closet close() and open() icon issue
  code/game/objects/structures/crates_lockers/__closet.dm
  code/game/objects/structures/crates_lockers/crates.dm
Labels: Currently Testmerged, Test Merge Candidate, size/XS

#6451 moving MRE vendors-ATLAS version (WIP)
  maps/rift/levels/rift-04-surface1.dmm
  maps/rift/levels/rift-06-surface3.dmm
  maps/triumph/levels/deck2.dmm
  maps/triumph/levels/deck4.dmm
Labels: size/XL

#6452 Goodbye Questionable Buttons inside Walls and Bins, Hello Atlas Engineering Autolathe
  maps/rift/levels/rift-02-underground2.dmm
Labels: size/S

#6450 walking around doesnt draw additional hunger
  code/modules/mob/living/carbon/carbon_movement.dm
  code/modules/mob/living/carbon/human/movement.dm
Labels: Test Merge Candidate, size/S

#6448 Makes the playernote selection from the player notes admin verb use tgui list selector instead of old browse
  code/modules/admin/admin.dm
Labels: Test Merge Candidate, size/S

#6447 Ports a few hairstyles from SR (~16) - also repaths (and adds documentation) to hair files
  citadel.dme
  code/modules/sprite_accessories/hair/hair.dm
  code/modules/sprite_accessories/hair/legacy.dm
  code/modules/sprite_accessories/hair/simple.dm
  icons/mob/sprite_accessory/hair/hair.dmi
Labels: Currently Testmerged, Test Merge Candidate, size/L

#6446 Atom hud refactor
  citadel.dme
  code/__DEFINES/dcs/signals/global_signals.dm
  code/__DEFINES/dcs/signals/signals_atom/signals_atom_main.dm
  code/__DEFINES/dcs/signals/signals_global.dm
  code/__DEFINES/dcs/signals/signals_global_object.dm
  code/__DEFINES/rendering/atom_huds.dm
  code/controllers/subsystem/overlays.dm
  code/datums/components/_component.dm
  code/datums/elements/items/hud_granter.dm
  code/game/atoms/atom.dm
  code/game/rendering/atom_huds/README.md
  code/game/rendering/atom_huds/alternate_appearance.dm
  code/game/rendering/atom_huds/atom_hud.dm
  code/game/rendering/atom_huds/atom_hud_provider.dm
  code/game/rendering/atom_huds/data_huds.dm
  code/game/rendering/atom_huds/legacy.dm
  code/game/rendering/atom_huds/other_huds.dm
  code/game/rendering/perspectives/README.md
  code/game/rendering/perspectives/perspective.dm
  code/modules/client/client.dm
  code/modules/client/client_procs.dm
  code/modules/clothing/glasses/_glasses.dm
  code/modules/clothing/glasses/hud.dm
  code/modules/integrated_electronics/core/assemblies.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/carbon/human/rendering.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/silicon/silicon.dm
  code/modules/mob/login.dm
  code/modules/mob/mob.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/observer/dead/dead.dm
  code/modules/nifsoft/software/01_vision.dm
  code/modules/nifsoft/software/13_soulcatcher.dm
  code/modules/nifsoft/software/15_misc.dm
  code/modules/vore/resizing/resize_vr.dm
Labels: size/XXL

#6457 access helper system + airlock access helpers
  citadel.dme
  code/__DEFINES/access.dm
  code/controllers/subsystem/mapping/maps.dm
  code/modules/mapping/map_helpers/_map_helpers.dm
  code/modules/mapping/map_helpers/access_helper/access_helper.dm
  code/modules/mapping/map_helpers/access_helper/airlock.dm
  icons/mapping/helpers/access_helpers.dmi
  maps/rift/levels/rift-05-surface2.dmm
  maps/rift/rift.dm
Labels: size/L

#6460 Adds proper icons to newly-added access helpers
  code/modules/mapping/map_helpers/access_helper/airlock.dm
  icons/mapping/helpers/access_helpers.dmi
Labels: size/XS

#6455 adds a mask that warms breath as you take it
  citadel.dme
  code/game/machinery/vending/loadout.dm
  code/modules/clothing/masks/_mask.dm
  code/modules/clothing/masks/breath_warmer.dm
  code/modules/clothing/masks/gasmask.dm
  code/modules/mob/living/carbon/breathe.dm
  code/modules/mob/mob_defines.dm
  maps/rift/levels/rift-04-surface1.dmm
  maps/sectors/frozen_192/levels/frozen_192.dmm
Labels: size/M

#6453 Replaces the Atlas EMT Shuttle with a new variant of the Triumph's EMT Dart
  maps/rift/levels/rift-06-surface3.dmm
  maps/sectors/miaphus_192/levels/miaphus_192_beach.dmm
  maps/sectors/piratebase_192/levels/piratebase_192.dmm
  maps/sectors/tradeport_192/levels/tradeport_192.dmm
Labels: Currently Testmerged, Test Merge Candidate, size/XXL

#6472 Fixes life crystals not detecting gibbed owners
  code/modules/vore/fluffstuff/life_crystals.dm
Labels: size/XS

#6471 Adds water, iced tea, and sugar to the cafe synthesizer
  code/modules/reagents/machinery/dispenser/synthesizer.dm
Labels: size/XS

#6467 Adds shaft miner to jobs available for FTU contractors
  code/modules/lore_hardcoded/faction.dm
Labels: size/XS

#6469 Fixes entertainer job HUD icon by giving it a job icon
  icons/screen/atom_hud/job.dmi
Labels: size/XS

#6468 Adds apprentice titles for shaft miners and roboticists
  code/modules/jobs/job_types/station/science/roboticist.dm
  code/modules/jobs/job_types/station/supply/shaft_miner.dm
Labels: size/S

#6465 adds highlander hair
  code/modules/sprite_accessories/hair/hair.dm
  icons/mob/sprite_accessory/hair/hair.dmi
Labels: size/XS

#6474 Fixes atmos retention fields meant to stay on turning off after atmospheric alarms are settled
  code/game/area/area.dm
Labels: size/XS

#6473 Fixes biogenerator not properly updating storage cache for bags
  code/game/machinery/biogenerator.dm
Labels: size/S

#6466 Triumph Emergency Shuttle Handrails and Lights
  maps/triumph/levels/flagship.dmm
Labels: Currently Testmerged, Test Merge Candidate, size/M

#6476 Bleat
  code/modules/mob/living/carbon/human/emote.dm
Labels: size/S

#6478 fixes some severe frame bugs
  code/modules/frames/frame.dm
  code/modules/frames/item.dm
Labels: size/S

#6475 Allows station-bound silicons to nudge pulled things around
  code/game/turfs/turf.dm
Labels: size/XS

#6477 I blame Kynde.
  citadel.dme
  code/game/objects/effects/decals/posters/citadel.dm
  icons/obj/contraband.dmi
Labels: size/XS
