Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2024-09, with the labels that each got.

#6711 ups sanitize line breaks allowed
  code/__HELPERS/text.dm
Labels: size/XS

#6705 Stops xenoarcheology talking objects from annoying ghosts
  code/modules/xenoarcheaology/finds/talking.dm
Labels: size/XS

#6707 racks construct costs 2 steel
  code/modules/materials/definitions/metals/steel.dm
Labels: size/XS

#6710 replicator fix (v2)
  icons/obj/xenoarchaeology.dmi
Labels: size/XS

#6708 Fix vox scales marking covering the eyes
  icons/mob/sprite_accessories/markings/vox_stuff.dmi
Labels: size/XS

#6694 Adds Teshari Eyes Marking
  code/modules/sprite_accessories/markings/tesh.dm
  icons/mob/sprite_accessories/markings/tesh_stuff.dmi
Labels: size/XS

#6698 Electrochromic Helpers, Placing Said Helpers in Atlas, and fixing Cargo's Conveyor ID's
  citadel.dme
  code/modules/mapping/map_helpers/electrochromatic_linker.dm
  icons/mapping/helpers/electrochromatic_helper.dmi
  maps/rift/levels/rift-02-underground2.dmm
  maps/rift/levels/rift-04-surface1.dmm
  maps/rift/levels/rift-05-surface2.dmm
  maps/rift/levels/rift-06-surface3.dmm
Labels: size/L

#6713 removes simplemob shadekins
  citadel.dme
  code/game/rendering/screen.dm
  code/modules/maps/_shim/away_spawner.dm
  code/modules/mob/living/simple_mob/subtypes/vore/shadekin/ability_objects.dm
  code/modules/mob/living/simple_mob/subtypes/vore/shadekin/ability_procs.dm
  code/modules/mob/living/simple_mob/subtypes/vore/shadekin/shadekin.dm
  code/modules/mob/living/simple_mob/subtypes/vore/shadekin/types.dm
  code/modules/species/shadekin/crew_shadekin_abilities.dm
  code/modules/species/shadekin/shadekin_abilities.dm
Labels: size/XXL

#6712 shrapnel is no longer rng + u can pick what to grab
  code/game/objects/items/weapons/implants/implant.dm
  code/modules/mob/living/simple_mob/subtypes/animal/borer/borer.dm
  code/modules/resleeving/mirror.dm
  code/modules/surgery/implant.dm
Labels: size/M

#6722 fixs sign language circuit
  code/modules/integrated_electronics/subtypes/input.dm
Labels: size/XS

#6715 more loadout slots
  code/__DEFINES/loadout.dm
Labels: size/XS

#6686 snowflakes tts more so it works with headsets
  code/game/objects/items/devices/text_to_speech.dm
  code/modules/mob/living/say.dm
Labels: size/S

#6703 mob ai: movable tracking
  citadel.dme
  code/__HELPERS/lists/string.dm
  code/controllers/subsystem/air.dm
  code/game/atoms/movable/movable-movement.dm
  code/game/atoms/movable/movable-throw.dm
  code/game/atoms/movable/movable.dm
  code/modules/ai/ai_pathing.dm
  code/modules/ai/ai_tracking.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/movement.dm
  code/modules/movespeed/movespeed_modifier.dm
Labels: size/L

#6706 preliminary reorganization of conveyors, disposals, packaging, etc
  citadel.dme
  code/__DEFINES/turfs/turfs.dm
  code/modules/industry/README.md
  code/modules/industry/conveyors/conveyor.dm
  code/modules/industry/conveyors/conveyor_switch.dm
  code/modules/industry/destination_tagger.dm
  code/modules/industry/disposals/disposal.dm
  code/modules/industry/disposals/disposal/chute.dm
  code/modules/industry/disposals/disposal/intake.dm
  code/modules/industry/disposals/disposal/outlet.dm
  code/modules/industry/disposals/disposal_frame.dm
  code/modules/industry/disposals/disposal_holder.dm
  code/modules/industry/disposals/disposal_pipe.dm
  code/modules/industry/disposals/disposal_pipe/broken.dm
  code/modules/industry/disposals/disposal_pipe/down.dm
  code/modules/industry/disposals/disposal_pipe/junction.dm
  code/modules/industry/disposals/disposal_pipe/segment.dm
  code/modules/industry/disposals/disposal_pipe/sortjunction.dm
  code/modules/industry/disposals/disposal_pipe/tagger.dm
  code/modules/industry/disposals/disposal_pipe/trunk.dm
  code/modules/industry/disposals/disposal_pipe/up.dm
  code/modules/industry/package_wrapper.dm
  code/modules/industry/packages/large_parcel.dm
  code/modules/industry/packages/small_parcel.dm
  code/modules/mining/machine_unloading.dm
  code/modules/recycling/disposal.dm
  code/modules/recycling/sortingmachinery.dm
Labels: size/XXL

#6709 fixes compile on latest byond
  code/datums/mutable_appearance.dm
  code/game/rendering/legacy/radial.dm
  code/game/rendering/parallax/parallax_object.dm
  code/modules/admin/verbs/SDQL2/SDQL_2_wrappers.dm
  code/modules/overmap/bounds.dm
Labels: size/S

#6721 item interaction API
  citadel.dme
  code/__DEFINES/dcs/signals/signals_atom/signals_atom-clickchain.dm
  code/__DEFINES/dcs/signals/signals_item/signals_item-clickchain.dm
  code/datums/event_args/clickchain.dm
  code/game/click/items-item_attack_chain.dm
  code/game/click/items.dm
Labels: size/M

#6729 lets mechs open blast doors
  code/modules/vehicles/sealed/mecha/mecha.dm
Labels: size/XS

#6726 atmosphere retention field touch message is now toucher only
  code/game/machinery/atm_ret_field.dm
Labels: size/XS

#6723 Nebula Air Supply
  maps/sectors/tradeport_192/levels/tradeport_192.dmm
Labels: size/S

#6731 fixes floor underlays
  code/game/turfs/simulated/floor/floor_types.dm
Labels: size/XS

#6727 fixs point defense registering
  code/game/machinery/pointdefense.dm
Labels: size/XS

#6724 Enigma wills it, Phase 4 Enigma Units Part 1: Sprites
  icons/mob/enigma.dmi
Labels: size/XS

#6718 reorganizes gateway into its own module
  citadel.dme
  code/modules/awaymissions/gateway.dm
  code/modules/gateway/README.md
  code/modules/gateway/stargate/stargate-away.dm
  code/modules/gateway/stargate/stargate-destination.dm
  code/modules/gateway/stargate/stargate-station.dm
  code/modules/gateway/stargate/stargate.dm
Labels: size/XL

#6730 lints against turf overlaying
  maps/away_missions/140x140/snow_outpost.dmm
  maps/away_missions/archive/blackmarketpackers.dmm
  maps/away_missions/archive/jungle.dmm
  maps/away_missions/archive/spacebattle.dmm
  maps/away_missions/archive/stationCollision.dmm
  maps/minitest/levels/minitest.dmm
  maps/rift/engines/burn.dmm
  maps/rift/engines/rust.dmm
  maps/sectors/admin_planets_192/croatoan.dmm
  maps/submaps/level_specific/debrisfield_vr/tinycarrier.dmm
  maps/submaps/level_specific/virgo2/Blackshuttledown.dmm
  maps/submaps/wilderness/Blackshuttledown.dmm
  maps/submaps/wilderness/Blueshuttledown.dmm
  maps/templates/admin/ert_base.dmm
  maps/templates/admin/mercbase.dmm
  maps/templates/admin/skipjack.dmm
  maps/templates/archive/tradeship.dmm
  maps/templates/shuttles/overmaps/generic/curashuttle.dmm
  maps/templates/shuttles/overmaps/generic/generic_shuttle.dmm
  maps/tether/levels/misc.dmm
  maps/tether/levels/station2.dmm
  maps/tether/levels/surface3.dmm
  maps/triumph/levels/flagship.dmm
  maps/triumph/levels/misc.dmm
  tools/ci/check_grep.sh
Labels: size/L

#6657 remaps the bar and moves the cafe
  code/game/area/Space Station 13 areas.dm
  code/modules/power/lighting/lighting.dm
  maps/rift/levels/rift-03-underground1.dmm
  maps/rift/levels/rift-04-surface1.dmm
  maps/rift/levels/rift-05-surface2.dmm
  maps/rift/levels/rift-06-surface3.dmm
Labels: size/XXL

#6738 fixes a bunch of bugs
  code/modules/mob/mob-iff.dm
  code/modules/mob/mob_defines.dm
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
  code/modules/projectiles/projectile/projectile.dm
  code/modules/projectiles/projectile/subtypes/magnetic.dm
  code/modules/xenobio/items/slimepotions.dm
Labels: size/M

#6736 xenobotany requirement traits stop water / nutriment depletion.
  code/modules/hydroponics/trays/tray_process.dm
Labels: size/S

#6732 Soldiers are made, not born -- Introduces Enigmas P4 Wraith unit and Banshee unit
  code/modules/mob/living/simple_mob/subtypes/mechanical/hivebot/enigma_hivebot.dm
  code/modules/projectiles/projectile/subtypes/beam/beams.dm
  sound/weapons/Dissolverray.ogg
  sound/weapons/Phasecoilengage.ogg
  sound/weapons/SuperHeavyLaser.ogg
Labels: size/L

#6745 Fixes cost of some Mecha weapons in the Exosuit Fab
  code/modules/research/designs/mechfab_designs.dm
Labels: size/XS

#6744 fixes a cam dir in engineering of triumph
  maps/triumph/levels/deck1.dmm
Labels: size/XS

#6743 moves the broken xeno domes from ears to hair, and fixes them
  citadel.dme
  code/modules/sprite_accessories/ears/xenomorph.dm
  code/modules/sprite_accessories/hair/species/xenomorph.dm
Labels: size/M

#6742 Damtype regex
  code/game/atoms/atom-defense.dm
  code/game/click/items.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/melee/types/misc.dm
  code/game/objects/items/melee/types/transforming.dm
  code/game/objects/items/storage/boxes.dm
  code/game/objects/items/tools/weldingtool.dm
  code/game/objects/items/weapons/cigs_lighters.dm
  code/game/objects/items/weapons/nullrod.dm
  code/game/objects/items/weapons/surgery_tools.dm
  code/game/objects/items/weapons/swords_axes_etc.dm
  code/game/objects/obj-defense.dm
  code/game/objects/obj.dm
  code/game/objects/structures/props/projectile_lock.dm
  code/game/objects/structures/props/puzzledoor.dm
  code/game/turfs/simulated/wall/wall-defense.dm
  code/modules/blob2/blobs/base_blob.dm
  code/modules/clothing/head/misc_special.dm
  code/modules/holodeck/HolodeckControl.dm
  code/modules/holodeck/HolodeckObjects.dm
  code/modules/mining/tools/mine_items.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/carbon/human/human-defense-legacy.dm
  code/modules/mob/living/living-defense-legacy.dm
  code/modules/mob/living/simple_mob/defense.dm
  code/modules/mob/living/simple_mob/subtypes/slime/xenobio/subtypes.dm
  code/modules/paperwork/pen.dm
  code/modules/projectiles/projectile/projectile.dm
  code/modules/shieldgen/energy_shield.dm
  code/modules/spells/artifacts.dm
  code/modules/vehicles/sealed/mecha/equipment/tools/drill.dm
  code/modules/vehicles/sealed/mecha/mecha.dm
  code/modules/vehicles_legacy/vehicle.dm
  code/modules/vore/fluffstuff/custom_items.dm
Labels: size/L

#6749 electrochromatic linker fix
  maps/rift/levels/rift-05-surface2.dmm
  maps/rift/levels/rift-06-surface3.dmm
Labels: size/L

#6748 lets security access genpop doors
  maps/rift/levels/rift-04-surface1.dmm
Labels: size/XS

#6746 bioprinter circuit in circuit imprinter
  code/modules/research/designs/circuits/machines/misc.dm
Labels: size/XS

#6751 Adds size standardization bracelets to protolathe
  code/modules/research/designs/misc.dm
Labels: size/XS

#6750 fix paper logos
  citadel.dme
  code/modules/asset_cache/assets/logos.dm
  code/modules/paperwork/paper/paper.dm
  html/images/loading.gif
  html/images/paper_bg.png
  html/images/talisman.png
  icons/interface/logos/nanotrasen-blue.png
  icons/interface/logos/nanotrasen-red.png
  icons/interface/logos/solgov.png
Labels: size/M

#6741 Projectiles reorganization and cleanup, impact effects, subtle EMP tweaks
  citadel.dme
  code/game/atoms/defense_old.dm
  code/game/machinery/turrets/subtypes/lasertag.dm
  code/game/machinery/turrets/turret-ai_holder.dm
  code/game/machinery/virtual_reality/vr_console.dm
  code/game/objects/empulse.dm
  code/game/objects/explosion.dm
  code/game/objects/items/weapons/implants/implant.dm
  code/game/objects/items/weapons/implants/neuralbasic.dm
  code/modules/ai/holders/polaris/ai_holder_combat.dm
  code/modules/mob/living/silicon/pai/defense.dm
  code/modules/modular_computers/computers/modular_computer/damage.dm
  code/modules/organs/external/external.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/launcher.dm
  code/modules/projectiles/guns/magic.dm
  code/modules/projectiles/guns/magic/staff.dm
  code/modules/projectiles/guns/magic/wand.dm
  code/modules/projectiles/projectile/arc.dm
  code/modules/projectiles/projectile/projectile-tracing.dm
  code/modules/projectiles/projectile/projectile.dm
  code/modules/projectiles/projectile/projectile_effect/detonation.dm
  code/modules/projectiles/projectile/projectile_effect/detonation/legacy_emp.dm
  code/modules/projectiles/projectile/projectile_effect/detonation/legacy_explosion.dm
  code/modules/projectiles/projectile/subtypes/animate.dm
  code/modules/projectiles/projectile/subtypes/arc.dm
  code/modules/projectiles/projectile/subtypes/arc/arc.dm
  code/modules/projectiles/projectile/subtypes/beam.dm
  code/modules/projectiles/projectile/subtypes/beam/beams.dm
  code/modules/projectiles/projectile/subtypes/bullet/bullets.dm
  code/modules/projectiles/projectile/subtypes/bullet/bullets_vr.dm
  code/modules/projectiles/projectile/subtypes/bullet/magnetic.dm
  code/modules/projectiles/projectile/subtypes/bullet/reusable.dm
  code/modules/projectiles/projectile/subtypes/bullet/srmrocket.dm
  code/modules/projectiles/projectile/subtypes/bullets.dm
  code/modules/projectiles/projectile/subtypes/energy.dm
  code/modules/projectiles/projectile/subtypes/energy/blob.dm
  code/modules/projectiles/projectile/subtypes/energy/energy.dm
  code/modules/projectiles/projectile/subtypes/energy/energy_vr.dm
  code/modules/projectiles/projectile/subtypes/energy/hook.dm
  code/modules/projectiles/projectile/subtypes/forcebolt.dm
  code/modules/projectiles/projectile/subtypes/ion.dm
  code/modules/projectiles/projectile/subtypes/magic.dm
  code/modules/projectiles/projectile/subtypes/pellet.dm
  code/modules/projectiles/projectile/subtypes/scatter.dm
  code/modules/projectiles/projectile/subtypes/trace.dm
  code/modules/projectiles/projectile/subtypes/unsorted.dm
  code/modules/vehicles/sealed/mecha/equipment/tools/armor_ranged.dm
  code/modules/vehicles/sealed/mecha/mecha.dm
Labels: Merge Conflict, size/XXL

#6753 rwall fix
  code/game/turfs/simulated/wall_types/material.dm
Labels: size/XS

#6758 href update
  code/modules/preferences/preference_setup/general/06_flavor.dm
Labels: size/XS

#6759 Removes an currently unused Enigma Sprite I added
  icons/mob/enigma.dmi
Labels: size/XS

#6755 shuttle templates and some ports from shuttles branch
  citadel.dme
  code/__DEFINES/_flags/turf_flags.dm
  code/__DEFINES/_planes+layers.dm
  code/__HELPERS/game/turfs/blocks.dm
  code/__HELPERS/game/turfs/line.dm
  code/__HELPERS/game/turfs/offsets.dm
  code/controllers/subsystem/mapping/reservations.dm
  code/game/area/area.dm
  code/game/objects/effects/misc.dm
  code/modules/mapping/turf_reservation.dm
  code/modules/shuttles/effects/shuttle_landing.dm
  code/modules/shuttles/shuttle.dm
  code/modules/shuttles/shuttle/shuttle.dm
  code/modules/shuttles/shuttle/shuttle_anchor.dm
  code/modules/shuttles/shuttle/shuttle_area.dm
  code/modules/shuttles/shuttle/shuttle_descriptor.dm
  code/modules/shuttles/shuttle/shuttle_port.dm
  code/modules/shuttles/shuttle/shuttle_template.dm
  icons/effects/effects.dmi
  icons/modules/shuttles/bounding_3x3.dmi
  icons/modules/shuttles/effects/shuttle_landing.dmi
  icons/modules/shuttles/shuttle_anchor.dmi
  icons/modules/shuttles/shuttle_anchor_2x2.dmi
  icons/modules/shuttles/shuttle_anchor_3x3.dmi
  maps/shuttles/README.md
  maps/shuttles/factions/corporations/nanotrasen/drone_prototype.dm
  maps/shuttles/factions/corporations/nanotrasen/drone_prototype.dmm
  maps/shuttles/factions/corporations/nanotrasen/sci_vector.dm
  maps/shuttles/factions/corporations/nanotrasen/sci_vector.dmm
Labels: size/XXL

#6762 Victory branch
  _mapload/victory.dm
  citadel.dme
  code/game/area/Off Station Areas.dm
  code/game/area/Space Station 13 areas.dm
  code/modules/maps/overmap/space/centcom.dm
  code/modules/maps/overmap/space/trade_station/trade_station.dm
  maps/generic/turbolifts.dm
  maps/sectors/tradeport_140/levels/tradeport_140.dmm
  maps/sectors/tradeport_192/levels/tradeport_192.dmm
  maps/triumph/triumph-overmap.dm
  maps/triumph/triumph-sectors.dm
  maps/triumph/triumph-shuttle-landmarks.dm
  maps/triumph/triumph-turbolifts.dm
  maps/victory/engines.dm
  maps/victory/engines/burn.dmm
  maps/victory/engines/fission.dmm
  maps/victory/engines/rust.dmm
  maps/victory/engines/sme.dmm
  maps/victory/levels/deck1.dmm
  maps/victory/levels/deck2.dmm
  maps/victory/levels/deck3.dmm
  maps/victory/levels/deck4.dmm
  maps/victory/levels/flagship.dmm
  maps/victory/levels/misc.dmm
  maps/victory/levels/transit.dmm
  maps/victory/sectors.dm
  maps/victory/shuttles.dm
  maps/victory/telecomms.dm
  maps/victory/victory-areas.dm
  maps/victory/victory-overmap.dm
  maps/victory/victory-sectors.dm
  maps/victory/victory-shuttle-landmarks.dm
  maps/victory/victory-turbolifts.dm
  maps/victory/victory.dm
Labels: size/XXL

#6737 On The Shoulders of Giants
  citadel.dme
  code/game/content/factions/derelict/derelict.dm/derelict_flora.dm
  code/game/content/factions/derelict/derelict.dm/derelict_horrors.dm
  code/game/content/factions/derelict/derelict.dm/derelict_props.dm
  code/game/content/factions/derelict/derelict.dm/derelict_structures.dm
  code/game/content/factions/derelict/derelict.dmi/32x32 props.dmi
  code/game/content/factions/derelict/derelict.dmi/64x64 props.dmi
  code/game/content/factions/derelict/derelict.dmi/96x96 props.dmi
  code/game/content/factions/derelict/derelict.dmi/cave_walls.dmi
  code/game/content/factions/derelict/derelict.dmi/derelict_doors 96x96.dmi
  code/game/content/factions/derelict/derelict.dmi/derelict_doors.dmi
  code/game/content/factions/derelict/derelict.dmi/derelict_flora.dmi
  code/game/content/factions/derelict/derelict.dmi/derelict_horrors.dmi
  code/game/content/factions/derelict/derelict.dmi/derelict_props.dmi
  code/game/content/factions/derelict/derelict.dmi/derelict_tiles.dmi
  code/game/content/factions/derelict/derelict.dmi/derelict_walls.dmi
Labels: size/XXL

#6752 Triumph's Atmos Pipe Colours and Accident Prone Supermatter
  code/game/machinery/doors/airlock/airlock.dm
  maps/triumph/engines/burn.dmm
  maps/triumph/engines/rust.dmm
  maps/triumph/engines/sme.dmm
  maps/triumph/levels/deck1.dmm
Labels: size/XL

#6763 makes distilling not require 1000 pressure for temp changes
  code/modules/reagents/distilling/distilling.dm
Labels: size/XS

#6764 Makes TEG Circulator bidirectional
  code/modules/atmospherics/machinery/components/binary_devices/circulator.dm
  code/modules/power/generator.dm
Labels: size/S

#6761 Adjusts Adherent maintenance areas and machines to be less inviting to get hurt
  code/game/objects/structures/charge_pylon.dm
  code/game/objects/structures/mineral_bath.dm
  maps/rift/levels/rift-03-underground1.dmm
  maps/triumph/levels/deck2.dmm
Labels: size/L

#6766 changes vore deaths to be logged rather than yelled at every online admin
  code/modules/vore/eating/belly_obj_vr.dm
Labels: size/XS

#6765 Euthenia map stuff
  code/game/machinery/atm_ret_field.dm
  maps/euthenia/levels/deck0.dmm
  maps/euthenia/levels/deck1.dmm
  maps/euthenia/levels/deck2.dmm
  maps/euthenia/levels/deck3.dmm
  maps/euthenia/levels/deck4.dmm
Labels: size/XXL

#6757 transfer vote ties now always extend and there is a message for randomly chosen results
  code/controllers/subsystem/vote.dm
Labels: size/XS

#6772 rewords bad comment
  code/modules/food/recipes_microwave.dm
Labels: good first pr, size/XS
