Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2024-01, with the labels that each got.

#6233 fixes commune not letting you commune to someone 2 tiles away
  code/modules/species/station/xenochimera.dm
Labels: size/S

#6236 stops tape recorder attempting to play when nothing is recorded
  code/game/objects/items/devices/tape_recorder/tape_recorder.dm
Labels: size/XS

#6235 Replaces "capsaicin" with "wasabi" in wasabi peas' taste description
  code/modules/food/food/snacks.dm
Labels: size/XS

#6237 fixes a girder runtime
  code/game/objects/structures/girders.dm
Labels: size/XS

#6239 Gives xenochimeras set_size
  code/modules/species/station/xenochimera.dm
Labels: size/XS

#6227 Allows silicons(our headcoder) to hide
  code/modules/mob/observer/dead/orbit.dm
Labels: size/XS

#6240 Adapt Surface 1
  maps/tether/levels/mining.dmm
  maps/tether/levels/plains.dmm
  maps/tether/levels/surface1.dmm
Labels: size/XXL

#6238 adaptation of tether surface 3 for new walls and windows
  maps/tether/levels/surface3.dmm
Labels: size/XXL

#6219 baywallify station1 on tether
  maps/tether/engines.dm
  maps/tether/engines/rust.dmm
  maps/tether/engines/sme.dmm
  maps/tether/engines/tesla.dmm
  maps/tether/levels/station1.dmm
Labels: size/XXL

#6217 qol changes for TTS
  code/__DEFINES/dcs/signals/signals_mob/signals_mob_main.dm
  code/game/objects/items/devices/text_to_speech.dm
  code/modules/mob/living/say.dm
  icons/obj/integrated_electronics/electronic_setups.dmi
Labels: size/M

#6241 Allows negative traits to be available for everyone (+ makes a few disabilities available to all + related tweaks)
  code/__HELPERS/global_lists.dm
  code/modules/mob/living/carbon/human/traits/negative.dm
  code/modules/preferences/preference_setup/vore/08_traits.dm
Labels: size/M

#6246 Adapt tether midpoint
  maps/tether/levels/midpoint.dmm
Labels: size/L

#6243 Various (mostly) mining-related map alterations
  maps/rift/levels/rift-08-west_deep.dmm
  maps/sectors/lavaland_192/levels/lavaland_192.dmm
  maps/tether/levels/mining.dmm
  maps/tether/levels/station2.dmm
  maps/triumph/levels/deck2.dmm
  maps/triumph/levels/deck3.dmm
Labels: size/XXL

#6244 Adds a confirmation prompt for hiding items in food
  code/modules/food/food/snacks.dm
Labels: size/XS

#6247 Toggle cover verb for borgs
  code/modules/mob/living/silicon/robot/robot.dm
Labels: Salt, size/XS

#6245 Mining Drill QOL changes and fixes
  code/game/objects/items/storage/bags.dm
  code/modules/mining/drilling/drill.dm
  maps/euthenia/levels/deck4.dmm
  maps/sectors/miaphus_192/levels/miaphus_192_beach.dmm
  maps/submaps/level_specific/class_d/Possesed_mech_cave.dmm
  maps/tether/levels/mining.dmm
Labels: size/M

#5958 [IDB IGNORE] [MDB IGNORE] Euthenia final stretch
  _mapload/euthenia.dm
  citadel.dme
  code/game/area/Ship_Station_Areas.dm
  code/game/area/Space Station 13 areas.dm
  code/game/machinery/turnstile.dm
  code/game/objects/structures/transit_tubes.dm
  code/game/turfs/simulated/flooring/flooring_premade.dm
  code/modules/atmospherics/machinery/components/unary/vent_pump.dm
  code/modules/atmospherics/machinery/components/unary/vent_scrubber.dm
  code/modules/atmospherics/machinery/mainspipe.dm
  code/modules/maps/generic/shuttles/station_shuttles/euthenia_shuttles.dm
  code/modules/power/lighting/lighting.dm
  code/modules/recycling/conveyor2.dm
  code/modules/recycling/disposal.dm
  maps/euthenia/levels/deck0.dmm
  maps/euthenia/levels/deck1.dmm
  maps/euthenia/levels/deck2.dmm
  maps/euthenia/levels/deck3.dmm
  maps/euthenia/levels/deck4.dmm
  maps/euthenia/levels/misc.dmm
  maps/euthenia/shuttle_stub.dm
  maps/generic/turbolifts.dm
Labels: size/XXL

#6252 various fixes
  code/controllers/subsystem/input.dm
  code/controllers/subsystem/parallax.dm
  code/controllers/subsystem/ping.dm
  code/controllers/subsystem/throwing.dm
  code/datums/components/turfs/transition_border.dm
  code/datums/recipe/stack_recipe.dm
  code/game/atoms/movable/movement.dm
  code/game/dna/dna_modifier.dm
  code/game/dna/genes/monkey.dm
  code/game/gamemodes/changeling/powers/lesser_form.dm
  code/game/mecha/working/ripley.dm
  code/game/mecha/working/working.dm
  code/game/objects/effects/spiders.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/PDA/PDA.dm
  code/game/objects/items/devices/chameleonproj.dm
  code/game/objects/items/devices/gps.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/glassjar.dm
  code/game/objects/items/robot/robot_parts.dm
  code/game/objects/items/tools/weldingtool.dm
  code/game/objects/items/weapons/hydroponics.dm
  code/game/objects/items/weapons/scrolls.dm
  code/game/objects/structures/bedsheet_bin.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/transit_tubes.dm
  code/game/objects/structures/watercloset.dm
  code/game/verbs/advanced_who.dm
  code/game/verbs/character_directory.dm
  code/game/verbs/who.dm
  code/modules/admin/admin_verbs.dm
  code/modules/asset_cache/asset_cache_client.dm
  code/modules/client/client_procs.dm
  code/modules/client/data/client_data.dm
  code/modules/client/onboarding/_onboarding.dm
  code/modules/client/onboarding/age_verification.dm
  code/modules/client/onboarding/security_checks.dm
  code/modules/client/security.dm
  code/modules/client/verbs/ooc.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/login.dm
  code/modules/mob/logout.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/nano/nanoui.dm
  code/modules/organs/external/external.dm
  code/modules/sculpting/sculpting_block.dm
  code/modules/vore/eating/vore_vr.dm
  code/modules/vore/hook-defs_vr.dm
  interface/interface.dm
Labels: Priority 1: High, size/XL

#6248 Adds river turfs
  citadel.dme
  code/game/objects/structures/catwalk.dm
  code/game/turfs/simulated/floor_types/river.dm
  code/game/turfs/simulated/floor_types/water.dm
  code/game/turfs/simulated/flooring/flooring_decals.dm
  icons/turf/outdoors.dmi
  icons/turf/river.dmi
  maps/sectors/gaia_192/levels/gaia_192.dmm
Labels: size/XXL

#6249 Floor mounted inflatables that deploy when firedoors close
  citadel.dme
  code/game/area/area.dm
  code/game/machinery/floor_inflatables.dm
  icons/obj/doors/hazard/floor_inflatables.dmi
Labels: size/M

#6253 removes the cache appearance verb because it's not used anymore
  citadel.dme
  code/datums/character_profile.dm
  code/game/verbs/character_profile_verbs.dm
Labels: size/S

#6257 Fixes the tense on some attack verbs
  code/game/objects/items/weapons/nullrod.dm
  code/modules/instruments/instruments/item.dm
Labels: size/XS

#6251 ports Aurora tattoos, adds asym. socks
  code/datums/underwear/socks.dm
  code/modules/sprite_accessories/markings/tattoo.dm
  icons/mob/human.dmi
  icons/mob/sprite_accessories/markings/tatoos.dmi
Labels: size/L

#6259 Makes a couple variables not arbitrarily converted to strings for no reason (??)
  code/modules/clothing/masks/miscellaneous.dm
Labels: size/XS

#6256 Makes phoronlocks go to 20C instead of 22
  code/game/machinery/doors/airlock/phoronlocks.dm
Labels: size/XS

#6250 Refactoring Baywalls and tweaking smoothing code
  code/__HELPERS/icon_smoothing.dm
  code/game/objects/structures/low_wall.dm
  code/game/turfs/simulated/wall/materials.dm
  code/game/turfs/simulated/wall/wall.dm
  code/game/turfs/simulated/wall/wall_icon.dm
  code/game/turfs/simulated/wall_types/wall_types.dm
  code/modules/mapping/map_helpers/paint.dm
Labels: size/L

#6260 TGUIifies Material Processor Console
  code/modules/mining/machine_processing.dm
  tgui/packages/tgui/interfaces/ExosuitFabricator.js
  tgui/packages/tgui/interfaces/MaterialProcessor.tsx
Labels: size/L

#6267 Adds the Neko Maid Uniform
  code/modules/clothing/under/miscellaneous.dm
  icons/clothing/uniform/misc/neko.dmi
Labels: size/XS

#6265 Shrinking the hammerhead (slightly)
  maps/rift/levels/rift-05-surface2.dmm
Labels: size/XXL

#6258 superheated epic gas cave now has a warning sign and also lava instead of water
  maps/rift/levels/rift-08-west_deep.dmm
Labels: size/S

#6263 disposal fixes
  code/modules/recycling/disposal.dm
Labels: size/S

#6274 fixes & standardizes emitter integrity
  code/modules/power/singularity/emitter.dm
Labels: size/M

#6275 fixes ghosts blocking people
  code/modules/mob/observer/dead/observer_movement.dm
Labels: size/XS

#6269 Add a second mime slot
  code/modules/jobs/job_types/station/civillian/clown.dm
  code/modules/jobs/job_types/station/civillian/mime.dm
Labels: size/XS

#6276 Adds a new robe
  code/modules/clothing/head/hood.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/loadout/loadout_head.dm
  code/modules/loadout/loadout_suit.dm
  icons/clothing/head/aureate.dmi
  icons/clothing/suit/coats/aureate_kimono.dmi
Labels: size/S

#6277 small change to throwing
  code/game/atoms/movable/throwing.dm
  code/game/objects/items.dm
  code/modules/mob/inventory/items.dm
  code/modules/mob/living/throwing.dm
Labels: size/XS

#6273 adds more protogen faces, and a flat screen head
  code/modules/organs/external/robolimbs.dm
  icons/mob/cyberlimbs/c-tech/c_beast_flat.dmi
  icons/mob/monitor_icons.dmi
Labels: size/S

#6281 Fixes blueshields being red
  code/modules/clothing/under/accessories/armor.dm
Labels: size/XS

#6261 protean blob chameleon clothing
  code/_globals/lists/clothing.dm
  code/modules/mob/holder.dm
  code/modules/species/protean/protean_blob.dm
  icons/mob/clothing/back.dmi
  icons/mob/clothing/ears.dmi
  icons/mob/clothing/eyes.dmi
  icons/mob/clothing/feet.dmi
  icons/mob/clothing/hands.dmi
Labels: size/L

#6282 adds a second elevator to tether
  code/game/area/Tether_areas.dm
  code/modules/turbolift/turbolift_map.dm
  maps/generic/turbolifts.dm
  maps/tether/levels/midpoint.dmm
  maps/tether/levels/station1.dmm
  maps/tether/levels/station2.dmm
  maps/tether/levels/surface1.dmm
  maps/tether/levels/surface2.dmm
  maps/tether/levels/surface3.dmm
Labels: size/XXL

#6271 Reworks airlock programs
  citadel.dme
  code/__DEFINES/machines/airlock_states.dm
  code/game/machinery/doors/airlock/airlock_control.dm
  code/game/machinery/doors/airlock/phoronlocks.dm
  code/game/machinery/embedded_controller/airlock_controllers.dm
  code/game/machinery/embedded_controller/airlock_docking_controller.dm
  code/game/machinery/embedded_controller/airlock_program.dm
  code/game/machinery/embedded_controller/docking_program_multi.dm
  code/game/machinery/embedded_controller/mapping_helpers.dm
  code/modules/atmospherics/machinery/components/unary/vent_pump.dm
  maps/away_missions/140x140/carpfarm.dmm
  maps/euthenia/levels/deck1.dmm
  maps/euthenia/levels/deck3.dmm
  maps/map_levels/140x140/talon/talon1.dmm
  maps/minitest/levels/minitest.dmm
  maps/minitest/levels/sector1.dmm
  maps/rift/levels/rift-04-surface1.dmm
  maps/rift/levels/rift-06-surface3.dmm
  maps/sectors/piratebase_192/levels/piratebase_192.dmm
  maps/sectors/tradeport_140/levels/tradeport_140.dmm
  maps/sectors/tradeport_192/levels/tradeport_192.dmm
  maps/templates/admin/dojo.dmm
  maps/templates/admin/ert_base.dmm
  maps/templates/admin/mercbase.dmm
  maps/templates/admin/skipjack.dmm
  maps/templates/archive/tradeship.dmm
  maps/templates/shuttles/overmaps/generic/cruiser.dmm
  maps/templates/shuttles/overmaps/generic/generic_shuttle.dmm
  maps/templates/shuttles/overmaps/generic/itglight.dmm
  maps/templates/shuttles/overmaps/generic/shelter_5.dmm
  maps/templates/shuttles/overmaps/generic/shelter_6.dmm
  maps/tether/engines/singulo.dmm
  maps/tether/engines/tesla.dmm
  maps/tether/levels/mining.dmm
  maps/tether/levels/station1.dmm
  maps/tether/levels/station2.dmm
  maps/tether/levels/surface1.dmm
  maps/tether/levels/surface3.dmm
  maps/triumph/levels/deck2.dmm
  maps/triumph/levels/deck3.dmm
  maps/triumph/levels/deck4.dmm
Labels: size/XL

#6242 Adds Ability targeting
  citadel.dme
  code/__DEFINES/ability.dm
  code/datums/ability.dm
  code/datums/ability_handler.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/species/species.dm
  code/modules/species/station/xenochimera.dm
Labels: size/M

#6283 I went through food/drinks and fixed as I scrolled
  code/modules/reagents/Drink-Recipes.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Food-Drinks.dm
Labels: size/L

#6280 fixes two walls under doors
  maps/tether/levels/surface1.dmm
  maps/tether/levels/surface2.dmm
Labels: size/XS

#6285 minor robe / hood tweaks
  icons/clothing/head/aureate.dmi
  icons/clothing/suit/coats/aureate_kimono.dmi
Labels: size/XS

#6286 Adds examin texts for previously hidden features, as well as power pr…
  code/modules/power/geothermal_power.dm
Labels: size/XS

#6288 access controll airlocks have a simplified process proc
  code/game/machinery/embedded_controller/airlock_controllers.dm
  code/game/machinery/embedded_controller/airlock_program.dm
Labels: size/M

#6287 Adds mapping helpers for scrubbers in airlocks, and tweaks their receive signal proc
  code/game/machinery/embedded_controller/mapping_helpers.dm
  code/modules/atmospherics/machinery/components/unary/vent_scrubber.dm
  icons/misc/map_helpers.dmi
  maps/minitest/levels/minitest.dmm
Labels: size/L

#6290 Fixes airlock overlays not appearing
  code/game/machinery/doors/airlock/airlock.dm
Labels: size/XS

#6292 Adds "Hush (ft. Mizz Fish") by kroh to the hacked jukebox songs
  config_static/jukebox.json
Labels: size/S

#6293 Changes around some engi points vendor options
  code/modules/mining/ore_redemption_machine/engineering_points_vendor.dm
Labels: size/XS

#6294 Minor Fixes to Chaplain Equipment
  code/game/objects/items/weapons/candle.dm
  code/game/objects/items/weapons/nullrod.dm
Labels: size/S

#6295 Fixes Stormdrifter Bull Melee Immunity Bug
  code/modules/mob/living/simple_mob/subtypes/lavaland/stormdrifter.dm
Labels: size/S
