Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2024-02, with the labels that each got.

#6309 Melee trait fix and balance
  code/modules/mob/living/carbon/human/traits/positive.dm
  code/modules/species/species_attack.dm
Labels: size/M

#6304 Makes intolerance values way more "logical", easier to follow
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Dispenser.dm
Labels: size/XS

#6301 Corrects Cargo Cow Crate Conundrum
  code/modules/cargo/supplypacks/hydroponics.dm
Labels: size/XS

#6300 Makes table unflipping actually fail if it fails
  code/game/objects/structures/tables/flipping.dm
Labels: size/XS

#6306 Makes sonar go over blindness
  code/__DEFINES/_planes+layers.dm
  code/modules/automata/sonar.dm
Labels: size/S

#6312 slicing fruits and pizza works with kitchen knifes again
  code/modules/food/food/snacks.dm
  code/modules/hydroponics/grown.dm
Labels: size/XS

#6297 Adds a heatpump that works between utility pipe and environment
  citadel.dme
  code/game/machinery/doors/airlock/phoronlocks.dm
  code/game/machinery/embedded_controller/airlock_controllers.dm
  code/game/machinery/embedded_controller/airlock_program.dm
  code/game/machinery/embedded_controller/mapping_helpers.dm
  code/modules/atmospherics/machinery/components/unary/env_heat_pump.dm
  icons/mapping/helpers/mapping_helpers.dmi
  icons/misc/map_helpers.dmi
  icons/obj/atmos.dmi
  maps/minitest/levels/minitest.dmm
Labels: size/XL

#6315 Minor Tradeport Fixes.
  maps/sectors/tradeport_192/levels/tradeport_192.dmm
Labels: size/L

#6308 smes deconstruction is faster
  code/modules/power/smes/smes_construction.dm
Labels: size/XS

#6311 fixes temperature stabilization killing people in atmos voidsuits
  code/__DEFINES/mobs/life.dm
  code/modules/mob/living/carbon/human/life.dm
Labels: size/S

#6298 Pilot office and Planetary sensors
  citadel.dme
  code/game/area/Space Station 13 areas.dm
  code/game/area/station/exporation.dm
  code/game/objects/structures/crates_lockers/_closet_appearance_definitions.dm
  code/game/objects/structures/crates_lockers/closets/secure/explorer.dm
  code/modules/jobs/job_types/station/civillian/pilot.dm
  code/modules/overmap/legacy/sectors.dm
  code/modules/overmap/legacy/ships/computers/sensors.dm
  icons/obj/closets/decals/closet.dmi
  maps/rift/levels/rift-06-surface3.dmm
Labels: size/XXL

#6319 Adds Airlock Electronics to Autolathe
  code/datums/design/designs/machines/circuits.dm
Labels: size/XS

#6316 Fixes fishing in pools
  code/game/turfs/simulated/floor_types/water.dm
Labels: size/XS

#6318 Makes beer batter shrooms not "alcoholic" tasting
  code/modules/food/food/snacks.dm
Labels: size/XS

#6321 storage hotfix - i should have tested carry weight
  code/game/objects/items.dm
  code/game/objects/items/weapons/material/armor.dm
  code/game/objects/systems/storage.dm
  code/modules/clothing/head/helmet.dm
Labels: size/M

#6302 Hammerhead Upgrade + Rigsuits + Baron Integrity Increase
  code/game/mecha/combat/fighter.dm
  code/game/turfs/simulated/wall_types/wall_types.dm
  code/modules/power/apc.dm
  code/modules/power/lighting/lighting.dm
  maps/rift/levels/rift-05-surface2.dmm
Labels: Stale, size/XXL
