Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2024-07, with the labels that each got.

#6555 medibeam stream projectors
  citadel.dme
  code/__DEFINES/_bitfields.dm
  code/__DEFINES/datums/beam.dm
  code/__DEFINES/dcs/signals/datums/signals_beam.dm
  code/__DEFINES/dcs/signals/datums/signals_beam_legacy.dm
  code/__DEFINES/dcs/signals/modules/signals_module_fishing.dm
  code/__DEFINES/dcs/signals/signals_mob/signals_mob_main.dm
  code/__DEFINES/mobs/biology.dm
  code/__DEFINES/movement.dm
  code/datums/beam.dm
  code/datums/beam_legacy.dm
  code/datums/components/_component.dm
  code/datums/components/atoms/radiation_listener.dm
  code/game/atoms/movable/movable.dm
  code/game/atoms/movable/special/render.dm
  code/game/mecha/equipment/tools/orescanner.dm
  code/game/mecha/equipment/tools/syringe_gun.dm
  code/game/mecha/equipment/tools/weldinglaser.dm
  code/game/objects/effects/map_effects/beam_point.dm
  code/game/objects/effects/temporary_visuals/projectiles/tracer.dm
  code/game/objects/items/inducer.dm
  code/game/objects/items/stream_projector/medichine.dm
  code/game/objects/items/stream_projector/stream_projector.dm
  code/game/objects/items/weapons/RCD.dm
  code/game/objects/structures/props/swarm.dm
  code/modules/catalogue/cataloguer.dm
  code/modules/fishing/equipment/rod.dm
  code/modules/fishing/minigame/fishing_minigame.dm
  code/modules/integrated_electronics/subtypes/output.dm
  code/modules/mob/life.dm
  code/modules/mob/living/carbon/damage_procs.dm
  code/modules/mob/living/carbon/life.dm
  code/modules/mob/living/damage_procs.dm
  code/modules/mob/living/simple_mob/damage_procs.dm
  code/modules/mob/mob_helpers.dm
  code/modules/organs/organ.dm
  code/modules/projectiles/projectile.dm
  icons/items/stream_projector/medichine.dmi
Labels: size/XXL

#6533 Adds new RPED, some fixes, some QoL, other part related tweaks
  code/game/machinery/_frame.dm
  code/game/machinery/_machinery.dm
  code/game/machinery/constructable_frame.dm
  code/game/objects/items/stock_parts/part_replacer.dm
  code/modules/reagents/reagent_containers/glass.dm
  code/modules/research/designs/stock_parts.dm
  icons/mob/items/lefthand_storage.dmi
  icons/mob/items/righthand_storage.dmi
  icons/obj/storage.dmi
Labels: size/L

#6523 explo equipment stuff no 1: emp bow / hardlight bow
  code/modules/vore/fluffstuff/custom_guns.dm
  icons/obj/gun/energy.dmi
  maps/rift/levels/rift-06-surface3.dmm
  maps/triumph/levels/deck4.dmm
  sound/weapons/hardlight_bow_charge.ogg
Labels: size/L

#6548 adds size standardization bracelets
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/loadout/loadout_utility.dm
  code/modules/vore/resizing/resize_vr.dm
  icons/mob/clothing/hands.dmi
  icons/obj/clothing/gloves.dmi
Labels: size/M

#6561 Allows doors/airlocks to be bump-opened when their panel is open
  code/game/machinery/doors/door.dm
Labels: size/XS

#6559 Misc helper cleanup
  citadel.dme
  code/__DEFINES/inventory/bodytypes.dm
  code/__DEFINES/tgui.dm
  code/__DEFINES/typeids.dm
  code/__HELPERS/datastructs/bodytypes.dm
  code/__HELPERS/datastructs/filters.dm
  code/__HELPERS/datastructs/generators.dm
  code/__HELPERS/datastructs/typelists.dm
  code/__HELPERS/text/sanitize.dm
  code/__HELPERS/unsorted.dm
  code/__HELPERS/vector.dm
  code/modules/admin/verbs/SDQL2/SDQL_2_wrappers.dm
Labels: size/L

#6560 prototype ids
  citadel.dme
  code/controllers/subsystem/persistence/persistence.dm
  code/controllers/subsystem/persistence/prototype_lookup.dm
  code/game/atoms/atom.dm
  code/game/objects/items/id_cards/emag.dm
  code/game/objects/items/stream_projector/medichine.dm
  code/game/objects/items/stream_projector/stream_projector.dm
  code/game/objects/items/toys.dm
Labels: size/M

#6563 coloration system
  citadel.dme
  code/__DEFINES/coloration.dm
  code/__HELPERS/coloration.dm
  code/game/objects/objs.dm
Labels: size/L

#6553 Temporary/silent pose setting
  code/modules/mob/living/carbon/human/emote.dm
Labels: size/M

#6565 being blocked by a wall on overmaps kills motion
  code/modules/overmap/entity/physics.dm
Labels: size/XS

#6558 Facility Director's/Officer's Sabre changes
  code/game/objects/items/storage/belt.dm
  code/game/objects/items/weapons/material/swords.dm
  code/game/objects/items/weapons/melee/misc.dm
Labels: size/M

#6564 Fixes relating to hallucinations, and prommie blobform
  code/datums/components/horror_aura.dm
  code/game/gamemodes/changeling/powers/lsd_sting.dm
  code/game/gamemodes/cult/runes.dm
  code/game/machinery/computer/arcade/orion_event.dm
  code/modules/mob/living/carbon/brain/life.dm
  code/modules/mob/living/carbon/human/human_damage.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/living.dm
  code/modules/power/fusion/fusion_reactions.dm
  code/modules/power/supermatter/supermatter.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Dispenser.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Medicine.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Other.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Toxins.dm
  code/modules/species/promethean/promethean_blob.dm
  code/modules/virus2/effect.dm
Labels: size/M

#6566 Adds Donut & Condiment Supply Packs for Cargo
  code/modules/cargo/supplypacks/hospitality.dm
Labels: size/M

#6567 Adds spray bottle & more glasses to autolathe
  code/datums/design/designs/medical/chemistry.dm
  code/datums/design/designs/misc/drinking_glass.dm
  code/modules/food/drinkingglass/glass1.dm
  code/modules/food/drinkingglass/metaglass.dm
  code/modules/food/drinkingglass/shaker.dm
  code/modules/reagents/reagent_containers/spray.dm
  code/modules/research/designs/weapons.dm
Labels: size/M

#6556 Makes restrained mobs carriable
  code/datums/components/riding/mob/human.dm
Labels: size/XS

#6573 Fixes a copy+paste typo causing royal jelly to be mead and mead to be nothing
  code/modules/food/drinks/bottle.dm
Labels: size/XS

#6568 Adds a link to the examine tab when examining things that have extra examine info
  code/game/atoms/atom.dm
  code/modules/client/statpanel.dm
Labels: Salt, size/S

#6570 Hey. Wanna listen to some TUNES?
  config_static/jukebox.json
Labels: size/M

#6544 projectiles v8 - raycasting
  citadel.dme
  code/__DEFINES/_flags/atom_flags.dm
  code/__DEFINES/math.dm
  code/__HELPERS/game/turfs/line.dm
  code/__HELPERS/game/turfs/offsets.dm
  code/__HELPERS/math/multipliers.dm
  code/__HELPERS/time.dm
  code/___compile_options.dm
  code/controllers/subsystem/processing/processing.dm
  code/controllers/subsystem/processing/projectiles.dm
  code/datums/components/turfs/transition_border.dm
  code/datums/position_point_vector.dm
  code/game/gamemodes/technomancer/spells/energy_siphon.dm
  code/game/objects/effects/temporary_visuals/projectiles/projectile_effects.dm
  code/game/objects/effects/temporary_visuals/projectiles/tracer.dm
  code/game/objects/objs.dm
  code/game/objects/structures/girders.dm
  code/modules/materials/dynamics.dm
  code/modules/mining/kinetic_crusher.dm
  code/modules/mob/living/simple_mob/subtypes/humanoid/possessed.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/mecha/adv_dark_gygax.dm
  code/modules/mob/living/simple_mob/subtypes/slime/feral/feral.dm
  code/modules/overmap/entity/physics.dm
  code/modules/overmap/legacy/ships/ship.dm
  code/modules/projectiles/ammunition/ammo_casing.dm
  code/modules/projectiles/guns/energy/kinetic_accelerator.dm
  code/modules/projectiles/guns/projectile/dartgun.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/arc.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/projectiles/projectile/bullets_vr.dm
  code/modules/projectiles/projectile/energy.dm
  code/modules/projectiles/projectile/hook.dm
  code/modules/projectiles/projectile/magnetic.dm
  code/modules/projectiles/projectile/reusable.dm
  code/modules/projectiles/projectile/scatter.dm
  code/modules/projectiles/projectile/special.dm
  code/modules/projectiles/projectile/trace.dm
  code/modules/projectiles/unsorted/magic.dm
  code/modules/spells/spell_projectile.dm
  code/modules/spells/targeted/projectile/projectile.dm
  code/modules/vore/fluffstuff/guns/pummeler.dm
  code/modules/vore/fluffstuff/guns/secutor.dm
  code/modules/vore/fluffstuff/guns/sickshot.dm
  icons/obj/projectiles_impact.dmi
  icons/obj/projectiles_muzzle.dmi
  icons/system/color_32x32.dmi
Labels: size/XXL

#6574 Mining Base additions/changes, fix medical access to telepad
  code/modules/mapping/map_helpers/access_helper/airlock.dm
  maps/sectors/lavaland_192/levels/lavaland_192.dmm
Labels: size/L

#6572 Lunchbox additions, fixes liquid ration problem
  code/game/machinery/vending/drinks.dm
  code/game/objects/random/maintenance.dm
  code/modules/awaymissions/loot_vr.dm
  code/modules/examine/descriptions/food.dm
  code/modules/food/drinks/carton.dm
  code/modules/food/food/lunch.dm
  code/modules/food/food/snacks.dm
  code/modules/maps/overmap/space/talon/talon.dm
  code/modules/random_map/drop/drop_types.dm
  maps/away_missions/140x140/zoo.dmm
  maps/away_missions/archive/desertbase.dmm
  maps/map_levels/140x140/alienship.dmm
  maps/rift/levels/rift-11-orbital.dmm
  maps/submaps/mountains/cultmine.dmm
  maps/templates/admin/mercbase.dmm
  maps/triumph/levels/flagship.dmm
Labels: size/L

#6577 misc fixes
  citadel.dme
  code/__DEFINES/inventory/accessories.dm
  code/controllers/master.dm
  code/game/machinery/doors/airlock/airlock.dm
  code/game/machinery/turnstile.dm
  code/game/objects/items.dm
  code/game/objects/objs.dm
  code/game/objects/structures/simple_doors.dm
  code/game/objects/systems/storage.dm
  code/modules/atmospherics/machinery/components/omni_devices/omni_base.dm
  code/modules/atmospherics/machinery/components/unary/gas_freezer.dm
  code/modules/atmospherics/machinery/components/unary/gas_heater.dm
  code/modules/atmospherics/machinery/machinery.dm
  code/modules/clothing/under/accessories/holster.dm
  code/modules/mob/inventory/inventory.dm
Labels: size/L

#6580 Update money_spam.dm
  code/modules/gamemaster/actions/money_spam.dm
Labels: FUCK, size/XS

#6578 misc projectiles raycasting tweaks, makes projectiles faster
  code/controllers/configuration_old/configuration.dm
  code/controllers/subsystem/processing/projectiles.dm
  code/modules/admin/verbs/ticklag.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/mecha/adv_dark_gygax.dm
  code/modules/mob/living/simple_mob/subtypes/slime/feral/feral.dm
  code/modules/projectiles/projectile.dm
  code/modules/projectiles/projectile/arc.dm
  code/modules/projectiles/projectile/bullets.dm
  code/modules/projectiles/projectile/hook.dm
Labels: size/M

#6571 GAIA STATION: Since Abundant Earthlike Resort Planets Isn't Very Immersive
  code/__DEFINES/access.dm
  code/game/area/Off Station Areas.dm
  code/game/machinery/turnstile.dm
  code/game/machinery/vending/misc.dm
  code/game/objects/items/id_cards/station_ids.dm
  code/modules/economy/machines/cash_register.dm
  code/modules/mapping/map_helpers/access_helper/airlock.dm
  code/modules/maps/overmap/planets/classm.dm
  code/modules/maps/weather/classm.dm
  icons/obj/card_cit.dmi
  icons/obj/vending.dmi
  maps/sectors/gaia_192/gaia_192.dm
  maps/sectors/gaia_192/levels/gaia_192.dmm
Labels: size/XXL

#6584 Fixes every projectile hard deleting a list instead of just nulling it when it hits
  code/modules/projectiles/projectile.dm
Labels: size/XS

#6582 Fix bracelet crafting, allows wallets to hold jewelery
  code/datums/recipe/material_recipes/tools.dm
  code/game/objects/items/storage/wallets.dm
  code/modules/clothing/under/accessories/bracelets/material.dm
Labels: size/S

#6576 Makes some things attackable via melee, code tweaks
  code/game/machinery/floodlight.dm
  code/game/machinery/fossilrevive.dm
  code/game/machinery/holoposter.dm
  code/game/objects/structures/curtains.dm
  code/game/objects/structures/dancepole.dm
  code/game/objects/structures/fence.dm
  code/game/objects/structures/flora.dm
  code/game/objects/structures/flora/rocks.dm
  code/modules/mining/mine_outcrops.dm
Labels: size/M

#6554 Swaps Riftmap's AI Uplink areas to the correct configuration and replaces the engineering sign in atmospherics to atmospherics
  maps/rift/levels/rift-03-underground1.dmm
  maps/rift/levels/rift-04-surface1.dmm
  maps/rift/levels/rift-06-surface3.dmm
Labels: size/M

#6550 overmaps 1 - generation & spatial
  citadel.dme
  code/controllers/subsystem/mapping/_mapping.dm
  code/controllers/subsystem/mapping/obfuscation.dm
  code/controllers/subsystem/overmap.dm
  code/controllers/subsystem/spatial_grids.dm
  code/datums/components/turfs/reservation_border.dm
  code/game/atoms/movable/movable.dm
  code/game/gamemodes/events/dust.dm
  code/game/machinery/nuclear_bomb.dm
  code/game/mecha/combat/fighter.dm
  code/game/turfs/space/space.dm
  code/modules/admin/admin_verbs.dm
  code/modules/mapping/map.dm
  code/modules/mapping/turf_reservation.dm
  code/modules/media/mediamanager.dm
  code/modules/overmap/entity/entity.dm
  code/modules/overmap/entity/physics.dm
  code/modules/overmap/events/event_handler.dm
  code/modules/overmap/legacy/sectors.dm
  code/modules/overmap/legacy/ships/computers/helm.dm
  code/modules/overmap/legacy/spacetravel.dm
  code/modules/overmap/map/area.dm
  code/modules/overmap/map/overmap.dm
  code/modules/overmap/map/overmap_template.dm
  code/modules/overmap/map/overmap_template_layer.dm
  code/modules/overmap/map/template_layers/legacy_events.dm
  code/modules/overmap/map/turf.dm
  code/modules/overmap/object.dm
  code/modules/power/supermatter/supermatter.dm
  code/modules/tgui/modules/overmap.dm
  icons/effects/numbers_unused.dmi
  icons/modules/overmap/area.dmi
  icons/modules/overmap/turf.dmi
Labels: size/XXL

#6589 Fix hovering fire alarms, refactor DMM rotation code
  code/game/atoms/atom.dm
  code/game/machinery/doors/multi_tile.dm
  code/game/machinery/fire_alarm.dm
  code/modules/mapping/dmm_suite/dmm_context.dm
  code/modules/mapping/dmm_suite/dmm_parsed.dm
  code/modules/mapping/dmm_suite/dmm_preloader.dm
  code/modules/multiz/structures/stairs.dm
  code/modules/turbolift/turbolift_map.dm
Labels: size/L

#6595 ID rework - trait information on IDs, confidential information toggle, and more
  code/datums/outfits/outfit.dm
  code/datums/uplink/announcements.dm
  code/game/objects/items/id_cards/contractor_ids.dm
  code/game/objects/items/id_cards/guest.dm
  code/game/objects/items/id_cards/station_ids.dm
  code/game/objects/items/id_cards/syndicate_ids.dm
  code/modules/mob/living/carbon/human/traits/_trait.dm
  code/modules/mob/living/carbon/human/traits/negative.dm
  code/modules/mob/living/carbon/human/traits/neutral.dm
  code/modules/mob/living/carbon/human/traits/positive.dm
  code/modules/preferences/_preferences.dm
  code/modules/preferences/preference_setup/vore/08_traits.dm
  code/modules/vore/fluffstuff/custom_items.dm
  maps/submaps/mountains/crashedcontainmentshuttle.dmm
  maps/submaps/mountains/crashedcontainmentshuttle_vr.dmm
Labels: size/L

#6590 Pre-burns the mineral planet
  code/modules/maps/weather/classg.dm
Labels: size/XS

#6587 fixes trader access
  code/__DEFINES/access.dm
Labels: size/XS

#6585 adds a ztrait to ban xray vision of any sort
  code/__DEFINES/mapping/levels.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/species/abilites.dm
Labels: size/S

#6591 Makes lighters require oxidizer
  code/game/objects/items/weapons/cigs_lighters.dm
  code/modules/atmospherics/environmental/atom.dm
Labels: size/S

#6592 Fixes tiles with var/color from permanently staining the floor
  code/game/turfs/simulated/floor/floor.dm
Labels: size/XS

#6583 Atlas cafe rework, + beefing up usability of other cafes
  code/game/machinery/vending/service.dm
  code/modules/reagents/machinery/dispenser/synthesizer.dm
  icons/obj/vending.dmi
  maps/rift/levels/rift-05-surface2.dmm
  maps/rift/levels/rift-06-surface3.dmm
  maps/tether/levels/station1.dmm
  maps/tether/levels/surface1.dmm
  maps/triumph/levels/deck2.dmm
Labels: size/L

#6586 experimental maploader changes
  code/__HELPERS/files/paths.dm
  code/modules/mapping/dmm_suite/dmm_parsed.dm
Labels: Test Merge Candidate, FUCK, Priority 0: CRITICAL, size/L

#6588 fixes rigsuit maintenance_while_online not working on removals
  code/modules/hardsuits/rig_attackby.dm
Labels: size/XS

#6594 overmaps - physics
  citadel.dme
  code/__DEFINES/overmaps/misc.dm
  code/__HELPERS/icon_smoothing.dm
  code/controllers/subsystem/overmap.dm
  code/controllers/subsystem/overmap_physics.dm
  code/controllers/subsystem/spatial_grids.dm
  code/game/atoms/movable/movable.dm
  code/game/atoms/movable/movement.dm
  code/game/atoms/movable/vv.dm
  code/game/machinery/telecomms/allinone.dm
  code/game/machinery/telecomms/broadcaster.dm
  code/game/machinery/telecomms/receiver.dm
  code/game/turfs/simulated/floor/floor_icon.dm
  code/game/turfs/turf_movement.dm
  code/game/world.dm
  code/modules/mapping/map.dm
  code/modules/overmap/bounds.dm
  code/modules/overmap/entity/entity.dm
  code/modules/overmap/entity/physics.dm
  code/modules/overmap/events/event_handler.dm
  code/modules/overmap/legacy/overmap_shuttle.dm
  code/modules/overmap/legacy/ships/engines/ion_thruster.dm
  code/modules/overmap/legacy/ships/landable.dm
  code/modules/overmap/legacy/ships/ship.dm
  code/modules/overmap/map/overmap.dm
  code/modules/overmap/map/turf.dm
  code/modules/overmap/object.dm
  code/modules/overmap/tiled/tiled.dm
  code/modules/projectiles/targeting/targeting_mob.dm
Labels: size/XL

#6546 non-tgui age gate
  code/modules/client/client_procs.dm
  code/modules/client/onboarding/age_verification.dm
Labels: size/M

#6421 New features, New wrappers for cell_slot system.
  code/game/objects/items/inducer.dm
  code/game/objects/systems/cell_slot.dm
Labels: size/L

#6596 Triumph PowerNet Sensor noding, duplicate engine output sensor
  maps/rift/levels/rift-03-underground1.dmm
  maps/rift/levels/rift-04-surface1.dmm
  maps/triumph/engines/burn.dmm
  maps/triumph/levels/deck1.dmm
  maps/triumph/levels/deck2.dmm
  maps/triumph/levels/deck4.dmm
Labels: size/M

#6618 Circuit advanced signaler changes
  code/modules/integrated_electronics/subtypes/input.dm
Labels: size/S

#6616 IC Fuel cell ref push and blood fix
  code/modules/integrated_electronics/passive/power.dm
Labels: size/S

#6617 Circuit demux fix & data to pin ref fixes
  code/modules/integrated_electronics/core/helpers.dm
  code/modules/integrated_electronics/core/pins.dm
  code/modules/integrated_electronics/subtypes/converters.dm
  code/modules/integrated_electronics/subtypes/data_transfer.dm
Labels: size/S

#6613 Integrated circuit removal bug
  code/modules/integrated_electronics/core/integrated_circuit.dm
Labels: size/XS

#6614 non standard circuit support
  code/__DEFINES/research/integrated_circuits.dm
  code/controllers/subsystem/processing/circuits.dm
  code/modules/integrated_electronics/core/saved_circuits.dm
Labels: size/M

#6615 Circuit component blueprint name validation fix
  code/modules/integrated_electronics/core/saved_circuits.dm
Labels: size/XS

#6612 Circuit interaction input fixes.
  code/modules/integrated_electronics/subtypes/input.dm
  code/modules/integrated_electronics/subtypes/manipulation.dm
  code/modules/integrated_electronics/subtypes/reagents.dm
Labels: size/S

#6611 circuit debugger ref copy UI fixes
  code/modules/integrated_electronics/core/assemblies.dm
  code/modules/integrated_electronics/core/integrated_circuit.dm
Labels: size/XS

#6609 Circuit debugger list functionality
  code/modules/integrated_electronics/core/tools.dm
Labels: size/M

#6610 circuit move to bottom fix
  code/modules/integrated_electronics/core/assemblies.dm
Labels: size/XS

#6608 Circuit displayed name fixes & tweaks
  code/modules/integrated_electronics/core/integrated_circuit.dm
  tgui/packages/tgui/interfaces/ICCircuit.js
Labels: size/S

#6603 floor wiring fix
  code/modules/power/cable.dm
Labels: size/XS

#6602 [s] integrated circuit stuff
  code/modules/integrated_electronics/core/printer.dm
Labels: size/XS

#6598 Tidy up traits
  citadel.dme
  code/__HELPERS/global_lists.dm
  code/modules/mob/living/carbon/human/traits/_trait.dm
  code/modules/mob/living/carbon/human/traits/_trait_group.dm
  code/modules/mob/living/carbon/human/traits/negative.dm
  code/modules/mob/living/carbon/human/traits/neutral.dm
  code/modules/mob/living/carbon/human/traits/positive.dm
  code/modules/mob/living/carbon/human/traits/trait_groups.dm
  code/modules/preferences/preference_setup/vore/08_traits.dm
  code/modules/species/shadekin/shadekin_traits.dm
  tgui/packages/tgui/interfaces/TraitSelectorModal.tsx
  tgui/packages/tgui/interfaces/common/InputButtons.tsx
  tgui/packages/tgui/styles/components/Button.scss
Labels: size/XXL

#6623 A variety of circuit fucky wuckys fixes.
  code/modules/integrated_electronics/core/helpers.dm
  code/modules/integrated_electronics/core/pins.dm
  code/modules/integrated_electronics/core/saved_circuits.dm
  code/modules/integrated_electronics/core/special_pins/lists_pin.dm
  code/modules/integrated_electronics/core/special_pins/ref_pin.dm
  code/modules/integrated_electronics/subtypes/filters.dm
  code/modules/integrated_electronics/subtypes/input.dm
  code/modules/integrated_electronics/subtypes/lists.dm
  code/modules/integrated_electronics/subtypes/logic.dm
  code/modules/integrated_electronics/subtypes/manipulation.dm
  code/modules/integrated_electronics/subtypes/memory.dm
  code/modules/integrated_electronics/subtypes/reagents.dm
  tgui/packages/tgui/interfaces/ICCircuit.js
Labels: size/L

#6626 Ore Silo door accessible by Science :3
  maps/rift/levels/rift-02-underground2.dmm
Labels: size/XS

#6620 Electronic Clothing now displays on action bar.
  code/modules/integrated_electronics/core/assemblies/clothing.dm
Labels: size/S

#6604 Use Node 20
  dependencies.sh
Labels: size/XS

#6601 MC: subsystem time dilation tracking, scheduling tweaks
  code/__DEFINES/MC.dm
  code/__DEFINES/controllers/_subsystems.dm
  code/controllers/master.dm
  code/controllers/subsystem.dm
  code/controllers/subsystem/air.dm
  code/controllers/subsystem/asset_loading.dm
  code/controllers/subsystem/events.dm
  code/controllers/subsystem/input.dm
  code/controllers/subsystem/machines.dm
  code/controllers/subsystem/materials.dm
  code/controllers/subsystem/mobs.dm
  code/controllers/subsystem/overmap_physics.dm
  code/controllers/subsystem/planets.dm
  code/controllers/subsystem/radiation.dm
  code/controllers/subsystem/ticker.dm
  code/modules/client/client_procs.dm
Labels: FUCK, size/L

#6621 Random Assortment of Atlas Fixes
  maps/rift/engines/burn.dmm
  maps/rift/levels/rift-04-surface1.dmm
  maps/rift/levels/rift-05-surface2.dmm
Labels: size/M

#6625 fix long hair alt 3
  citadel.dme
  icons/mob/human_face.dmi
Labels: size/XS

#6607 Botany things
  citadel.dme
  code/__DEFINES/materials/misc.dm
  code/game/turfs/simulated/wall_types/wall_types.dm
  code/modules/cargo/supplypacks/hydroponics.dm
  code/modules/hydroponics/seed_datums.dm
  code/modules/hydroponics/seed_packets.dm
  code/modules/lore_hardcoded/species/alraune/_base.dm
  code/modules/lore_hardcoded/species/alraune/citizenship.dm
  code/modules/lore_hardcoded/species/alraune/origin.dm
  code/modules/lore_hardcoded/species/krisitik/culture.dm
  code/modules/lore_hardcoded/species/krisitik/origin.dm
  code/modules/lore_hardcoded/species/krisitik/religion.dm
  code/modules/materials/definitions/organic/wood/log.dm
  code/modules/materials/definitions/organic/wood/plank.dm
  code/modules/materials/fifty_spawner_mats.dm
  code/modules/materials/material_sheets.dm
Labels: ✔️Approved - Code Quality, size/L, Blocked - Lore

#6631 fix hybrid resin doors being invisible
  code/modules/species/station/xenomorph_hybrids/hybrid_resin.dm
Labels: size/XS

#6630 admin stealth mode now works while deadminned
  citadel.dme
  code/__HELPERS/_logging.dm
  code/__HELPERS/unsorted.dm
  code/datums/variable_settings/variable_setting_controller.dm
  code/datums/world_topic.dm
  code/game/verbs/advanced_who.dm
  code/game/verbs/who.dm
  code/modules/admin/admin.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/holder2.dm
  code/modules/admin/verbs/antag-ooc.dm
  code/modules/admin/verbs/deadsay.dm
  code/modules/admin/verbs/server/admin_reboot.dm
  code/modules/admin/view_variables/topic.dm
  code/modules/admin/view_variables/topic_basic.dm
  code/modules/client/client-admin.dm
  code/modules/client/verbs/ooc.dm
  code/modules/mob/mob_helpers.dm
Labels: size/L

#6629 mech hydraulic clamps & others now work on fighters on all adjacent tiles
  citadel.dme
  code/modules/vehicles/sealed/mecha/equipment/mecha_equipment.dm
  code/modules/vehicles/sealed/mecha/equipment/tools/hydraulic_clamp.dm
  code/modules/vehicles/sealed/mecha/mecha.dm
  code/modules/vehicles/vehicle-physics.dm
Labels: size/S

#6619 Revert some IC balance from Virgo
  code/modules/integrated_electronics/passive/power.dm
  code/modules/integrated_electronics/subtypes/lists.dm
Labels: size/S

#6624 fixes some coats not having a sprite while the hood is up
  code/modules/clothing/suits/hooded.dm
Labels: size/XS

#6634 Backspaced out old dna lock system from guns
  citadel.dme
  code/modules/projectiles/dnalocking.dm
  code/modules/projectiles/gun.dm
  code/modules/projectiles/guns/magnetic/magnetic_railgun.dm
  code/modules/vore/fluffstuff/guns/dominator.dm
Labels: Test Merge Candidate, size/L
