Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2024-10, with the labels that each got.

#6782 Victory branch
  code/game/turfs/simulated/flooring/flooring_decals.dm
  maps/victory/levels/deck1.dmm
  maps/victory/levels/deck2.dmm
  maps/victory/levels/deck3.dmm
  maps/victory/levels/deck4.dmm
Labels: size/XXL

#6769 New power for lavaland base, and some mining locker cleanup
  code/game/objects/structures/crates_lockers/closets/secure/cargo.dm
  code/modules/power/geothermal_power.dm
  maps/rift/levels/rift-02-underground2.dmm
  maps/rift/levels/rift-09-west_caves.dmm
  maps/sectors/lavaland_192/levels/lavaland_192.dmm
  maps/tether/levels/mining.dmm
  maps/tether/levels/station2.dmm
  maps/triumph/levels/deck2.dmm
Labels: size/XXL

#6770 moves the broken xeno domes from ears to hair, and fixes them
  code/modules/sprite_accessories/hair/species/xenomorph.dm
Labels: size/XS

#6771 Adds Skeleton Corpse Spawner
  code/modules/awaymissions/corpse.dm
Labels: size/S

#6774 Re-adds Atlas SM ejection and moves eject to monitoring room
  maps/rift/engines/burn.dmm
  maps/rift/engines/rust.dmm
  maps/rift/engines/sme.dmm
  maps/rift/levels/rift-01-underground3.dmm
  maps/rift/levels/rift-02-underground2.dmm
Labels: size/L

#6775 Halloween Event Map 1: A somewhat spooky ship
  citadel.dme
  code/modules/maps/templates/shuttles/admin_spawn/ghostship.dm
  maps/templates/shuttles/overmaps/generic/ghostship.dmm
Labels: size/XXL

#6780 Replaces Exploration's M1A Garand Sniper with the Expeditionary Reconnaissance Rifle
  code/game/objects/items/gunbox.dm
  code/modules/projectiles/guns/projectile/semiauto.dm
  icons/mob/clothing/back.dmi
  icons/mob/items/lefthand_guns.dmi
  icons/mob/items/righthand_guns.dmi
  icons/obj/gun/ballistic.dmi
Labels: size/M

#6776 Lamps separated into on and off, Library lamps start on and Mining Gateway Medikits aren't empty
  code/game/objects/items/devices/flashlight.dm
  maps/rift/levels/rift-02-underground2.dmm
  maps/rift/levels/rift-04-surface1.dmm
  maps/triumph/levels/deck2.dmm
  maps/triumph/levels/deck4.dmm
Labels: size/M

#6773 Fire/atmosphere alarm reasons
  code/__DEFINES/atmospherics/machinery/alarm.dm
  code/datums/wires/alarm.dm
  code/game/area/area.dm
  code/game/machinery/fire_alarm.dm
  code/modules/alarm/alarm.dm
  code/modules/alarm/alarm_handler.dm
  code/modules/atmospherics/machinery/air_alarm.dm
  code/modules/tgui/modules/alarm.dm
Labels: size/M

#6778 Rewords many event announcements & some medical things
  code/game/objects/items/weapons/autopsy.dm
  code/modules/events/carp_migration.dm
  code/modules/events/cult.dm
  code/modules/events/dust.dm
  code/modules/events/gravity.dm
  code/modules/events/meteors.dm
  code/modules/events/rogue_drones.dm
  nano/templates/dish_incubator.tmpl
  tgui/packages/tgui/interfaces/DishIncubator.js
Labels: size/S

#6777 Adds a striped skinsuit and a cropped turtleneck
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/loadout/loadout_suit.dm
  code/modules/loadout/loadout_uniform.dm
  icons/clothing/suit/misc/turtle_crop.dmi
  icons/clothing/uniform/misc/skin_taped.dmi
Labels: size/S

#6786 Revert "Makes TEG Circulator bidirectional"
  code/modules/atmospherics/machinery/components/binary_devices/circulator.dm
  code/modules/power/generator.dm
Labels: size/S

#6787 The Void Horrors, Xenomorph Expansion
  citadel.dme
  code/__HELPERS/global_lists.dm
  code/game/objects/mob_spawner.dm
  code/game/objects/structures/crates_lockers/largecrate.dm
  code/modules/awaymissions/loot_vr.dm
  code/modules/events/xenoinfestation.dm
  code/modules/mob/living/simple_mob/subtypes/animal/space/alien.dm
  code/modules/mob/living/simple_mob/subtypes/animal/xenomorph/xenomorph.dm
  code/modules/mob/living/simple_mob/subtypes/animal/xenomorph/xenomorph_abilities.dm
  code/modules/mob/living/simple_mob/subtypes/animal/xenomorph/xenomorph_catalogue.dm
  code/modules/rogueminer_vr/asteroid.dm
  code/modules/xenoarcheaology/artifacts/autocloner.dm
  icons/mob/biomorphs/berserker.dmi
  icons/mob/biomorphs/burster.dmi
  icons/mob/biomorphs/inferno.dmi
  icons/mob/biomorphs/sprinter.dmi
  maps/away_missions/140x140/zoo.dmm
  maps/away_missions/archive/stationCollision.dmm
  maps/submaps/level_specific/class_d/cave2D.dmm
  maps/submaps/level_specific/class_d/vault4D.dmm
  maps/submaps/level_specific/class_d/vault5D.dmm
  maps/submaps/level_specific/debrisfield_vr/new_escapepod_xeno.dmm
  maps/submaps/level_specific/virgo2/CrashedSmuggler.dmm
  maps/submaps/mountains/crashed_ufo_frigate.dmm
  maps/submaps/mountains/vault3.dmm
  maps/submaps/mountains/vault4.dmm
  maps/submaps/mountains/vault5.dmm
Labels: size/XXL

#6783 makes the alt naga tail (dual colour) go behind clothing instead of over it
  code/modules/sprite_accessories/tail/taurs.dm
  icons/mob/sprite_accessories/taurs.dmi
Labels: size/XS

#6788 My best attempts at clothing
  code/modules/clothing/under/accessories/clothing.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/loadout/loadout_accessories.dm
  code/modules/loadout/loadout_uniform.dm
  icons/mob/clothing/ties.dmi
  icons/mob/clothing/uniform.dmi
  icons/obj/clothing/ties.dmi
  icons/obj/clothing/uniforms.dmi
Labels: size/S

#6789 Victory branch
  citadel.dme
  code/game/area/victory_areas.dm
  maps/victory/levels/deck1.dmm
  maps/victory/levels/deck2.dmm
  maps/victory/levels/deck3.dmm
  maps/victory/levels/deck4.dmm
Labels: size/XXL

#6779 Fixes Ranged Roach Attack Speed
  code/modules/mob/living/simple_mob/subtypes/animal/roach/roach.dm
Labels: size/XS

#6768 refactors simple_networks
  citadel.dme
  code/controllers/subsystem/networks/_networks.dm
  code/controllers/subsystem/networks/simple.dm
  code/controllers/subsystem/simple_networks.dm
  code/game/objects/effects/traps.dm
  code/game/turfs/simulated/flooring/flooring_traps.dm
  code/modules/networks/simple/atom.dm
  code/modules/networks/simple/datum.dm
  code/modules/networks/simple/element.dm
  code/modules/networks/simple/helpers.dm
Labels: Stale, size/L

#6767 adds a vv option to offer a mob to ghosts to take control of
  citadel.dme
  code/__DEFINES/role_preferences.dm
  code/__DEFINES/vv.dm
  code/__HELPERS/game.dm
  code/datums/ghost_query.dm
  code/modules/mob/mob_helpers.dm
  code/modules/mob/physiology.dm
  code/modules/mob/vv.dm
Labels: size/L

#6792 Reorient the victory's decks to make the deck numbers make sense
  maps/victory/engines/fission.dmm
  maps/victory/engines/rust.dmm
  maps/victory/levels/deck1.dmm
  maps/victory/levels/deck2.dmm
  maps/victory/levels/deck3.dmm
  maps/victory/levels/deck4.dmm
  maps/victory/victory.dm
Labels: size/XXL

#6793 fixes the victory elevator
  maps/victory/victory.dm
Labels: size/XS

#6785 Halloween Week 2: Ghosts in the Geiger Counter
  citadel.dme
  code/modules/mob/living/simple_mob/subtypes/occult/constructs/nuclear/burning.dm
  code/modules/mob/living/simple_mob/subtypes/occult/constructs/nuclear/charred.dm
  code/modules/mob/living/simple_mob/subtypes/occult/constructs/nuclear/demoncore.dm
  code/modules/mob/living/simple_mob/subtypes/occult/constructs/nuclear/gammawraith.dm
  icons/mob/cult.dmi
Labels: size/L

#6796 Nsv victory final stages
  code/__DEFINES/color/color.dm
  code/game/area/victory_areas.dm
  code/game/objects/structures/crates_lockers/closets/secure/explorer.dm
  code/game/turfs/simulated/flooring/flooring_decals.dm
  maps/victory/engines.dm
  maps/victory/engines/rust.dmm
  maps/victory/levels/Dropship.dmm
  maps/victory/levels/deck1.dmm
  maps/victory/levels/deck2.dmm
  maps/victory/levels/deck3.dmm
  maps/victory/levels/deck4.dmm
Labels: size/XXL

#6797 Exploration Mapping Tweaks
  maps/rift/levels/rift-06-surface3.dmm
  maps/triumph/levels/deck4.dmm
Labels: size/M

#6794 Z-Mimic: Speculative fixes for glass turfs
  code/controllers/subsystem/zcopy.dm
  code/modules/multiz/zmimic/mimic_movable.dm
Labels: size/S

#6807 blacklists Drinks That Kill You from flasks
  code/modules/food/food/lunch.dm
Labels: size/XS

#6800 instruments in loadout
  citadel.dme
  code/__DEFINES/loadout.dm
  code/modules/loadout/loadout_entry.dm
  code/modules/loadout/loadout_instruments.dm
Labels: size/M

#6802 Fixes crematoriums disintegrating
  code/game/objects/structures/morgue.dm
Labels: size/S

#6781 Silver Ammunition & Related Resprites
  code/datums/design/designs/ammo/pistol.dm
  code/datums/design/designs/ammo/revolver.dm
  code/datums/design/designs/ammo/rife.dm
  code/datums/design/designs/ammo/shotgun.dm
  code/game/objects/items/weapons/swords_axes_etc.dm
  code/modules/mob/living/simple_mob/subtypes/animal/space/alien.dm
  code/modules/mob/living/simple_mob/subtypes/animal/xenomorph/xenomorph.dm
  code/modules/projectiles/ammunition/ammo_magazine.dm
  code/modules/projectiles/ammunition/calibers/normal/a10g.dm
  code/modules/projectiles/ammunition/calibers/normal/a12g.dm
  code/modules/projectiles/ammunition/calibers/normal/a357.dm
  code/modules/projectiles/ammunition/calibers/normal/a38.dm
  code/modules/projectiles/ammunition/calibers/normal/a44.dm
  code/modules/projectiles/ammunition/calibers/normal/a45.dm
  code/modules/projectiles/ammunition/calibers/normal/a5_56mm.dm
  code/modules/projectiles/ammunition/calibers/normal/a7_62mm.dm
  code/modules/projectiles/ammunition/calibers/normal/a9mm.dm
  code/modules/projectiles/ammunition/calibers/special/blunderbuss.dm
  code/modules/projectiles/ammunition/calibers/special/musket.dm
  code/modules/projectiles/guns/energy/special.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/projectile/subtypes/bullet/bullets.dm
  code/modules/species/xenomorphs/alien_facehugger.dm
  icons/modules/projectiles/casings/a12g.dmi
  icons/modules/projectiles/casings/slim.dmi
  icons/modules/projectiles/magazines/old_magazine_stick.dmi
  icons/modules/projectiles/magazines/old_speedloader_6.dmi
  icons/modules/projectiles/magazines/old_speedloader_7.dmi
  icons/modules/projectiles/magazines/old_stripper.dmi
Labels: size/XXL

#6819 Add a requirement of one player ready for the round to start
  code/controllers/subsystem/ticker.dm
Labels: size/S

#6806 Nsv endeavour
  code/game/area/endeavour_areas.dm
  maps/endeavour/engines/rust.dmm
  maps/endeavour/levels/deck1.dmm
  maps/endeavour/levels/deck2.dmm
  maps/endeavour/levels/deck3.dmm
  maps/endeavour/levels/deck4.dmm
  maps/rift/levels/rift-06-surface3.dmm
Labels: size/XXL

#6821 Lowers the recoil on the JSDF Rifle because it makes JSDF rifle users motion sick
  code/modules/projectiles/guns/legacy_vr_guns/custom_guns.dm
Labels: size/XS

#6817 adds honeydragon's cybersun jacket
  citadel.dme
  code/game/content/factions/corporations/cybersun/clothing/jackets.dm
  code/modules/loadout/loadout_suit.dm
  icons/content/factions/corporations/cybersun/clothing/jackets.dmi
Labels: size/M

#6818 makes the SM delam chamber not a pipe bomb
  maps/rift/levels/rift-01-underground3.dmm
Labels: size/XS

#6820 [s] fixes client security autobans
  code/modules/client/security.dm
Labels: size/XS

#6805 Optimize circuit examiner and revert CD
  code/modules/integrated_electronics/subtypes/input.dm
Labels: size/XS

#6814 yanks MIT headers from atmos
  code/modules/atmospherics/atmosphere/atmosphere.dm
  code/modules/atmospherics/environmental/public.dm
  code/modules/atmospherics/environmental/turf-share.dm
  code/modules/atmospherics/gasmixtures/_helpers-transfer.dm
  code/modules/atmospherics/gasmixtures/gas.dm
  code/modules/atmospherics/gasmixtures/gas_data.dm
  code/modules/atmospherics/gasmixtures/gas_types/core.dm
  code/modules/atmospherics/gasmixtures/procedural_gas.dm
Labels: size/S

#6799 Andromeda Haven
  citadel.dme
  code/modules/maps/overmap/planets/admin_andromeda.dm
  maps/sectors/admin_planets_192/andromeda.dmm
Labels: size/XXL

#6824 Nsv endeavour Fixes 1
  maps/endeavour/endeavour.dm
  maps/endeavour/levels/deck1.dmm
  maps/endeavour/levels/deck2.dmm
  maps/endeavour/levels/deck3.dmm
  maps/endeavour/levels/deck4.dmm
Labels: size/XXL
