Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2024-06, with the labels that each got.

#6485 Fixes north wheelchair sprite missing
  icons/obj/wheelchair.dmi
Labels: size/XS

#6483 fixes the blue trimmed labcoat not having an icon sprite
  code/modules/clothing/suits/labcoat.dm
Labels: size/XS

#6480 Fixes all the "on your in your" with internals
  code/game/rendering/screen.dm
Labels: size/XS

#6461 Adds dry monster tamer, some sodas to mining vendor
  code/modules/mining/ore_redemption_machine/equipment_vendor.dm
  code/modules/reagents/Drink-Recipes.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Food-Drinks.dm
Labels: size/M

#6458 adds basic helper procs for doing thermal calculations
  citadel.dme
  code/__HELPERS/thermal.dm
Labels: size/M

#6456 makes standard atmos proc, pump_heat()
  code/modules/atmospherics/machinery/_atmospherics_helpers.dm
  code/modules/atmospherics/machinery/components/binary_devices/heat_pump.dm
  code/modules/atmospherics/machinery/components/binary_devices/massive_heat_pump.dm
  code/modules/atmospherics/machinery/components/unary/env_heat_pump.dm
Labels: size/M

#6454 Makes the R-UST tell you that turning it off makes it explode
  code/modules/power/fusion/core/core_control.dm
Labels: size/XS

#6441 Tweak some alcohol numbers to be less egregious
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Dispenser.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Food-Drinks.dm
Labels: Currently Testmerged, Test Merge Candidate, size/M

#6486 linter fixes
  code/__DEFINES/dcs/signals/signals_NTNet.dm
  code/__DEFINES/dcs/signals/signals_adventure.dm
  code/__DEFINES/dcs/signals/signals_bot.dm
  code/__DEFINES/dcs/signals/signals_changeling.dm
  code/__DEFINES/dcs/signals/signals_circuit.dm
  code/__DEFINES/dcs/signals/signals_clothing.dm
  code/__DEFINES/dcs/signals/signals_container.dm
  code/__DEFINES/dcs/signals/signals_customizable.dm
  code/__DEFINES/dcs/signals/signals_cytology.dm
  code/__DEFINES/dcs/signals/signals_food.dm
  code/__DEFINES/dcs/signals/signals_gib.dm
  code/__DEFINES/dcs/signals/signals_greyscale.dm
  code/__DEFINES/dcs/signals/signals_heretic.dm
  code/__DEFINES/dcs/signals/signals_hydroponic.dm
  code/__DEFINES/dcs/signals/signals_janitor.dm
  code/__DEFINES/dcs/signals/signals_ladder.dm
  code/__DEFINES/dcs/signals/signals_light_eater.dm
  code/__DEFINES/dcs/signals/signals_medical.dm
  code/__DEFINES/dcs/signals/signals_mind.dm
  code/__DEFINES/dcs/signals/signals_modsuit.dm
  code/__DEFINES/dcs/signals/signals_mood.dm
  code/__DEFINES/dcs/signals/signals_moveloop.dm
  code/__DEFINES/dcs/signals/signals_movetype.dm
  code/__DEFINES/dcs/signals/signals_music.dm
  code/__DEFINES/dcs/signals/signals_operating_computer.dm
  code/__DEFINES/dcs/signals/signals_painting.dm
  code/__DEFINES/dcs/signals/signals_reagent.dm
  code/__DEFINES/dcs/signals/signals_restaurant.dm
  code/__DEFINES/dcs/signals/signals_scangate.dm
  code/__DEFINES/dcs/signals/signals_screentips.dm
  code/__DEFINES/dcs/signals/signals_spatial_grid.dm
  code/__DEFINES/dcs/signals/signals_species.dm
  code/__DEFINES/dcs/signals/signals_subsystem.dm
  code/__DEFINES/dcs/signals/signals_swab.dm
  code/__DEFINES/dcs/signals/signals_techweb.dm
  code/__DEFINES/dcs/signals/signals_traitor.dm
  code/__DEFINES/dcs/signals/signals_tram.dm
  code/__DEFINES/dcs/signals/signals_transform.dm
  code/__DEFINES/dcs/signals/signals_vehicle.dm
  code/__DEFINES/dcs/signals/signals_wash.dm
  code/__DEFINES/dcs/signals/signals_xeno_control.dm
  code/game/dna/dna2.dm
  code/game/machinery/vending/vending.dm
  code/game/mecha/mecha.dm
  code/game/objects/effects/particles/_particles.dm
  code/game/sound.dm
  code/modules/mob/_modifiers/modifiers.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/mob/living/silicon/ai/ai.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/organs/external/external.dm
  code/modules/organs/organ.dm
  code/modules/preferences/_preferences.dm
Labels: Priority 0: CRITICAL, size/XL

#6491 Fixes silicons being able to telepathically push walls
  code/game/turfs/turf.dm
Labels: size/XS

#6492 tries to make age verify menu more stable and reliable
  code/modules/client/onboarding/age_verification.dm
Labels: size/XS

#6489 Alraune internals fix and some buffs
  code/__DEFINES/inventory/carry_weight.dm
  code/modules/species/station/alraune.dm
Labels: size/M

#6464 shuttles/storytellers - maploader injections and context
  citadel.dme
  code/__DEFINES/controllers/persistence.dm
  code/__HELPERS/lists/merge.dm
  code/__HELPERS/lists/pick.dm
  code/controllers/master.dm
  code/controllers/subsystem/mapping/_mapping.dm
  code/controllers/subsystem/mapping/levels.dm
  code/controllers/subsystem/mapping/maps.dm
  code/controllers/subsystem/mapping/obfuscation.dm
  code/controllers/subsystem/persistence/modules/spatial_metadata.dm
  code/game/area/area.dm
  code/game/atoms/atom.dm
  code/game/atoms/movement.dm
  code/game/machinery/cloning.dm
  code/game/machinery/computer/misc/bioscan.dm
  code/game/machinery/doors/multi_tile.dm
  code/game/machinery/fire_alarm.dm
  code/game/machinery/misc/bioscan_antenna.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/structures/crates_lockers/__closet.dm
  code/game/turfs/change_turf.dm
  code/game/turfs/space/space.dm
  code/modules/admin/verbs/mapping.dm
  code/modules/awaymissions/loot_vr.dm
  code/modules/lighting/lighting_overlay.dm
  code/modules/mapping/README.md
  code/modules/mapping/dmm_suite/dmm_context.dm
  code/modules/mapping/dmm_suite/dmm_orientation.dm
  code/modules/mapping/dmm_suite/dmm_parsed.dm
  code/modules/mapping/dmm_suite/dmm_preloader.dm
  code/modules/mapping/dmm_suite/dmm_report.dm
  code/modules/mapping/dmm_suite/utility_types.dm
  code/modules/mapping/dmm_suite/wrappers.dm
  code/modules/mapping/map.dm
  code/modules/mapping/map_helpers/_map_helpers.dm
  code/modules/mapping/map_helpers/engine_loader.dm
  code/modules/mapping/map_helpers/gear_marker.dm
  code/modules/mapping/map_helpers/role_marker.dm
  code/modules/mapping/map_injection/map_injection.dm
  code/modules/mapping/map_injection/starting_gear.dm
  code/modules/mapping/map_level.dm
  code/modules/mapping/map_template.dm
  code/modules/mapping/utility/merge_conflict_marker.dm
  code/modules/mining/drilling/drill.dm
  code/modules/mining/machine_input_output_plates.dm
  code/modules/multiz/structures/stairs.dm
  code/modules/multiz/zmimic/mimic_movable.dm
  code/modules/networks/simple/helpers.dm
  code/modules/species/xenomorphs/alien_embryo.dm
  code/modules/turbolift/turbolift_map.dm
  code/modules/unit_tests/unit_test.dm
  icons/mapping/helpers/gear_marker.dmi
  icons/mapping/helpers/role_marker.dmi
Labels: size/XXL

#6462 Replaces airlocks access vars with access helpers on Rift (1/3)
  code/modules/mapping/map_helpers/access_helper/airlock.dm
  icons/mapping/helpers/access_helpers.dmi
  maps/rift/engines/rust.dmm
  maps/rift/engines/sme.dmm
  maps/rift/levels/rift-01-underground3.dmm
  maps/rift/levels/rift-02-underground2.dmm
  maps/rift/levels/rift-03-underground1.dmm
  maps/rift/levels/rift-04-surface1.dmm
  maps/rift/levels/rift-05-surface2.dmm
  maps/rift/levels/rift-06-surface3.dmm
  maps/rift/levels/rift-07-west_base.dmm
  maps/rift/levels/rift-08-west_deep.dmm
  maps/rift/levels/rift-09-west_caves.dmm
  maps/rift/levels/rift-10-west_plains.dmm
  maps/rift/levels/rift-11-orbital.dmm
Labels: Test Merge Candidate, Testmerge Only, size/XXL

#6494 fixes infinite loop in map system
  code/controllers/subsystem/mapping/levels.dm
Labels: FUCK, Priority 0: CRITICAL, size/XS

#6481 Makes blood no longer toxic to consume for all except skrell
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Core.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Food-Drinks.dm
Labels: Ready for Review, size/M

#6482 Lets hardsuits and radio headsets be used in the colormate
  code/game/machinery/colormate.dm
  code/modules/hardsuits/_rig.dm
Labels: Ready for Review, size/S

#6495 Make set pose only show adjust when appropriate
  code/modules/mob/living/carbon/human/emote.dm
Labels: size/XS

#6496 fixes tooltips & iv drips
  code/game/machinery/iv_drip.dm
  code/modules/asset_cache/asset_pack.dm
  code/modules/mob/living/carbon/human/blood.dm
  code/modules/tooltip/tooltip.dm
Labels: size/S

#6501 Library Curtain, Backwall Light, and Asteroid/Cult Event Volume
  code/modules/events/cult.dm
  code/modules/events/meteors.dm
  maps/rift/levels/rift-04-surface1.dmm
Labels: size/S

#6504 Fixes ice cream carts
  code/modules/food/food/ice_cream.dm
  code/modules/food/structures/icecream_cart.dm
Labels: size/XS

#6507 adds dark versions of aureate stuff
  code/modules/clothing/glasses/_glasses.dm
  code/modules/clothing/head/hood.dm
  code/modules/clothing/suits/miscellaneous.dm
  code/modules/loadout/loadout_eyes.dm
  code/modules/loadout/loadout_head.dm
  code/modules/loadout/loadout_suit.dm
  icons/clothing/head/aureate.dmi
  icons/clothing/suit/coats/aureate_kimono.dmi
Labels: size/S

#6503 fixes ice cream being unfillable, marks minitest as no-random-draw, adds more CI logging
  code/__HELPERS/_logging.dm
  code/modules/food/food/ice_cream.dm
  code/modules/food/structures/icecream_cart.dm
  maps/minitest/minitest.dm
Labels: size/XS

#6502 Makes the font for a vote notification more noticeable
  code/__DEFINES/spans.dm
  code/controllers/subsystem/vote.dm
  interface/stylesheet.dm
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
Labels: size/M

#6512 Buff floor dirtying to take 75 steps instead of 500.
  code/game/turfs/simulated.dm
Labels: size/XS

#6509 Adds Cargo-only permission to the entrance into Mining Refinery on Atlas
  maps/rift/levels/rift-02-underground2.dmm
Labels: size/S

#6499 Fixes icons: clown dufflebag, cigboxes, trashbags
  code/game/objects/items/storage/bags.dm
  code/game/objects/items/storage/misc_legacy/fancy.dm
  icons/obj/clothing/backpack.dmi
Labels: size/XS

#6497 Replaces airlocks access vars with access helpers on Triumph (2/3)
  code/modules/mapping/map_helpers/access_helper/airlock.dm
  maps/rift/levels/rift-05-surface2.dmm
  maps/triumph/engines/burn.dmm
  maps/triumph/engines/fission.dmm
  maps/triumph/engines/rust.dmm
  maps/triumph/engines/sme.dmm
  maps/triumph/levels/deck1.dmm
  maps/triumph/levels/deck2.dmm
  maps/triumph/levels/deck3.dmm
  maps/triumph/levels/deck4.dmm
  maps/triumph/levels/flagship.dmm
  maps/triumph/levels/misc.dmm
Labels: Priority 1: High, size/XXL

#6510 fixes some airlocks looking like they dont have glass while they should
  code/game/machinery/doors/airlock/airlock.dm
Labels: size/XS

#6511 Updates 2x1 door windows to grey from blue
  icons/obj/doors/double/fill_glass.dmi
Labels: good first pr, size/XS

#6505 maybe fixes timer issues, tweaks world fps, timers, etc
  citadel.dme
  code/__HELPERS/math/fractions.dm
  code/___compile_options.dm
  code/controllers/subsystem/timer.dm
  code/datums/looping_sounds/_looping_sound.dm
  code/game/world.dm
Labels: Test Merge Candidate, Priority 0: CRITICAL, size/L

#6500 Fix wall locker + fridge sprites
  code/game/objects/structures/crates_lockers/_closet_appearance_definitions.dm
  code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
  code/game/objects/structures/crates_lockers/closets/walllocker.dm
  icons/obj/closets/bases/fridge.dmi
  icons/obj/closets/fridge.dmi
Labels: size/S

#6437 [Ready to Merge]Fluff Planets: Discoverable Overmap Objects
  citadel.dme
  code/modules/lore_codex/news_data/main.dm
  code/modules/overmap/events/fluff_planets.dm
  code/modules/overmap/events/generation.dm
  code/modules/overmap/legacy/disperser/disperser_fire.dm
  code/modules/overmap/legacy/ships/computers/sensors.dm
  icons/modules/overmap/entity.dmi
  maps/tether/tether.dm
Labels: size/L

#6519 Nerf floor scuffs to 125 steps to dirty.
  code/game/turfs/simulated.dm
Labels: size/XS

#6526 fixes airlock runtimes that are breaking CI
  code/game/machinery/doors/airlock/airlock.dm
Labels: size/XS

#6516 Replaces airlocks access vars with access helpers on Tether (3/3)
  code/modules/mapping/map_helpers/access_helper/airlock.dm
  maps/tether/engines/rust.dmm
  maps/tether/engines/singulo.dmm
  maps/tether/engines/sme.dmm
  maps/tether/engines/tesla.dmm
  maps/tether/levels/midpoint.dmm
  maps/tether/levels/mining.dmm
  maps/tether/levels/misc.dmm
  maps/tether/levels/station1.dmm
  maps/tether/levels/station2.dmm
  maps/tether/levels/surface1.dmm
  maps/tether/levels/surface2.dmm
  maps/tether/levels/surface3.dmm
  maps/tether/levels/underdark.dmm
Labels: size/XXL

#6524 Makes a few font settings brighter in dark mode
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
Labels: size/XS

#6521 Spatial Grids
  citadel.dme
  code/__DEFINES/controllers/_subsystems.dm
  code/__DEFINES/controllers/spatial_grids.dm
  code/__HELPERS/_logging.dm
  code/controllers/subsystem/ao.dm
  code/controllers/subsystem/mapping/_mapping.dm
  code/controllers/subsystem/mapping/maps.dm
  code/controllers/subsystem/spatial_grids.dm
  code/datums/components/movable/spatial_grid.dm
  code/modules/mob/living/living.dm
Labels: size/L

#6525 OBJ_ALLOW_THROW_THROUGH + mob throw damage
  code/__DEFINES/_flags/obj_flags.dm
  code/controllers/subsystem/throwing.dm
  code/game/atoms/movable/throwing.dm
  code/game/objects/defense.dm
  code/game/objects/structures/grille.dm
  code/game/objects/structures/low_wall.dm
  code/game/objects/structures/window.dm
  code/game/turfs/simulated/wall/defense.dm
  code/modules/mob/living/carbon/human/human_defense.dm
  code/modules/mob/living/defense.dm
  code/modules/mob/living/living_defines.dm
Labels: size/M

#6527 "Nitrogen Filling my Engines", AI Upload Floating Camera and Noded Engine PowerNet Sensors
  maps/rift/engines/burn.dmm
  maps/rift/engines/rust.dmm
  maps/rift/engines/sme.dmm
  maps/rift/levels/rift-06-surface3.dmm
Labels: size/L

#6515 Makes encryption heater "efficiency" actually reduce efficiency (and power use)
  code/modules/power/crypto_miner.dm
Labels: size/S

#6532 fast turf reservation lookups & aligned spatial grid lookups
  code/__DEFINES/mapping/system.dm
  code/controllers/subsystem/mapping/allocation.dm
  code/controllers/subsystem/mapping/boot.dm
  code/controllers/subsystem/mapping/levels.dm
  code/controllers/subsystem/mapping/reservations.dm
  code/controllers/subsystem/spatial_grids.dm
  code/datums/components/movable/spatial_grid.dm
  code/modules/mapping/turf_reservation.dm
Labels: size/L

#6534 Fixes bad maps being picked in CI (real)
  code/controllers/subsystem/mapping/maps.dm
Labels: FUCK, Priority 0: CRITICAL, size/XS

#6522 Fixes scorian production structures
  code/game/objects/structures/ashlander.dm
Labels: size/M

#6537 SSgrids
  citadel.dme
  code/__DEFINES/_planes+layers.dm
  code/__DEFINES/bound_proc.dm
  code/__DEFINES/controllers/grids.dm
  code/__DEFINES/turfs/change_turf.dm
  code/__HELPERS/game/turfs/offsets.dm
  code/controllers/subsystem/grids.dm
  code/datums/bound_proc.dm
  code/game/area/area.dm
  code/game/turfs/change_turf.dm
  code/game/turfs/simulated.dm
Labels: size/XL

#6538 backpacks are no longer lead lined
  code/game/objects/items/storage/storage.dm
Labels: size/XS

#6531 factions cleanup - removes most factions from station
  code/controllers/subsystem/mapping/maps.dm
  code/modules/jobs/job_types/station/engineering/atmospherics_technician.dm
  code/modules/jobs/job_types/station/engineering/senior_engineer.dm
  code/modules/jobs/job_types/station/engineering/station_engineer.dm
  code/modules/jobs/job_types/station/medical/chemist.dm
  code/modules/jobs/job_types/station/medical/head_nurse.dm
  code/modules/jobs/job_types/station/medical/medical_doctor.dm
  code/modules/jobs/job_types/station/medical/paramedic.dm
  code/modules/jobs/job_types/station/science/roboticist.dm
  code/modules/jobs/job_types/station/supply/cargo_technician.dm
  code/modules/jobs/job_types/station/supply/quartermaster.dm
  code/modules/lore_hardcoded/faction.dm
Labels: size/L

#6541 [s] crayon logging
  code/modules/artwork/items/crayon.dm
Labels: size/XS

#6539 rig backpacks are no longer lead lined
  code/modules/hardsuits/_rig.dm
Labels: size/XS

#6536 turf reservations - borders
  citadel.dme
  code/__DEFINES/controllers/spatial_grids.dm
  code/controllers/subsystem/mapping/reservations.dm
  code/controllers/subsystem/spatial_grids.dm
  code/datums/components/turfs/reservation_border.dm
  code/datums/components/turfs/transition_border.dm
  code/modules/mapping/turf_reservation.dm
Labels: size/L

#6549 squishimals!
  code/game/machinery/vending/misc.dm
  code/game/objects/items/toys.dm
  icons/obj/toy.dmi
Labels: size/M

#6542 fixes underfloor + atmos pipe placement
  code/__DEFINES/objects/objects.dm
  code/game/machinery/beacon.dm
  code/game/machinery/magnet.dm
  code/game/machinery/navbeacon.dm
  code/game/objects/items/devices/radio/beacon.dm
  code/game/objects/objs.dm
  code/game/objects/structures/safe.dm
  code/modules/atmospherics/machinery/machinery.dm
  code/modules/atmospherics/machinery/pipes/pipe_base.dm
  code/modules/atmospherics/machinery/pipes/tank.dm
  code/modules/shieldgen/shield_diffuser.dm
Labels: size/M

#6547 Hiding the Engine's Pipes Again
  maps/rift/engines/burn.dmm
  maps/rift/engines/rust.dmm
  maps/rift/engines/sme.dmm
Labels: size/M

#6552 Turns off the scrubbers in the nacelles on Triumph
  maps/triumph/levels/deck1.dmm
Labels: size/XS

#6545 Fixes curtains not being anchored by default
  code/game/objects/structures/curtains.dm
Labels: size/XS
