Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2024-11, with the labels that each got.

#6835 radio cleanup 1
  citadel.dme
  code/__DEFINES/radio.dm
  code/__HELPERS/radio.dm
  code/__HELPERS/unsorted.dm
  code/controllers/communications.dm
  code/game/antagonist/antagonist_create.dm
  code/game/antagonist/outsider/commando.dm
  code/game/antagonist/outsider/deathsquad.dm
  code/game/antagonist/outsider/mercenary.dm
  code/game/antagonist/outsider/raider.dm
  code/game/antagonist/outsider/trader.dm
  code/game/antagonist/station/traitor.dm
  code/game/machinery/computer/arcade/orion.dm
  code/game/machinery/computer/camera.dm
  code/game/machinery/computer/communications.dm
  code/game/machinery/computer/supply.dm
  code/game/machinery/status_display.dm
  code/game/machinery/telecomms/broadcaster.dm
  code/game/machinery/telecomms/presets.dm
  code/game/objects/items/devices/PDA/cart.dm
  code/game/objects/items/devices/PDA/radio.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/devices/radio/intercom.dm
  code/game/objects/items/devices/radio/radio.dm
  code/game/objects/items/devices/tvcamera.dm
  code/game/objects/items/weapons/teleportation.dm
  code/modules/assembly/signaler.dm
  code/modules/mapping/map.dm
  code/modules/maps/overmap/space/talon/talon.dm
  code/modules/mob/living/silicon/pai/software_modules/signaller.dm
  code/modules/overmap/legacy/sectors.dm
  code/modules/resleeving/infomorph_software.dm
  code/modules/shuttles/shuttle_supply.dm
  code/modules/tgui/modules/communications.dm
  code/modules/vehicles/sealed/mecha/mecha.dm
  code/modules/xenoarcheaology/tools/tools.dm
  maps/endeavour/telecomms.dm
  maps/rift/telecomms.dm
  maps/tether/telecomms.dm
  maps/triumph/telecomms.dm
Labels: size/L

#6831 gateway spawner
  citadel.dme
  code/__DEFINES/vv.dm
  code/modules/gateway/stargate/stargate-station.dm
  code/modules/mapping/spawner/gateway.dm
  code/modules/mapping/spawner/tcomms_relay.dm
Labels: size/M

#6811 update ci again
  .github/workflows/ci_suite.yml
  code/__DEFINES/damage_organs.dm
  code/datums/components/turfs/reservation_border.dm
  code/datums/components/turfs/transition_border.dm
  code/game/objects/items/devices/PDA/radio.dm
  code/game/objects/items/id_cards/cards.dm
  code/game/objects/items/storage/misc_legacy/misc.dm
  code/modules/integrated_electronics/subtypes/manipulation.dm
  code/modules/mob/say_vr.dm
  code/modules/species/shadekin/shadekin.dm
  code/modules/species/shadekin/shadekin_blackeyed.dm
  code/modules/species/station/xenochimera.dm
  dependencies.sh
  maps/away_missions/140x140/snow_outpost.dmm
  maps/away_missions/archive/blackmarketpackers.dmm
  maps/away_missions/archive/example.dmm
  maps/away_missions/archive/jungle.dmm
  maps/away_missions/archive/spacebattle.dmm
  maps/away_missions/archive/wildwest.dmm
  maps/away_missions/archive/zresearchlabs.dmm
  maps/euthenia/levels/misc.dmm
  maps/map_levels/140x140/talon/talon2.dmm
  maps/sectors/admin_planets_192/croatoan.dmm
  maps/submaps/level_specific/class_p/HeadscientistHQ.dmm
  maps/submaps/level_specific/debrisfield_vr/debris14.dmm
  maps/submaps/mountains/BlastMine1.dmm
  maps/submaps/mountains/quarantineshuttle.dmm
  maps/submaps/wilderness/Blackshuttledown.dmm
  maps/submaps/wilderness/Blueshuttledown.dmm
  maps/templates/admin/ert.dmm
  maps/templates/admin/kk_mercship.dmm
  maps/templates/shuttles/overmaps/generic/bearcat.dmm
  maps/templates/shuttles/overmaps/generic/curashuttle.dmm
  maps/tether/levels/misc.dmm
  maps/tether/levels/surface3.dmm
  maps/triumph/levels/flagship.dmm
  maps/triumph/levels/misc.dmm
  maps/triumph/levels/transit.dmm
  tools/bootstrap/node
  tools/bootstrap/node.bat
  tools/bootstrap/node_.ps1
  tools/ci/annotate_dm.sh
  tools/ci/build.ps1
  tools/ci/check_grep.sh
  tools/ci/ci_dependencies.sh
  tools/ci/install_node.sh
  tools/ci/install_ripgrep.sh
  tools/dm_annotator/__main__.py
  tools/mapmerge2/dmm.py
Labels: Stale, size/XXL

#6834 shello & playsound
  code/__DEFINES/_cooldowns.dm
  code/__DEFINES/math.dm
  code/__HELPERS/shell.dm
  code/__HELPERS/time.dm
  code/modules/admin/verbs/playsound.dm
Labels: size/L

#6836 update filter
  citadel.dme
  code/__HELPERS/matrices/transform_matrix.dm
  code/__HELPERS/sorts/TimSort.dm
  code/__HELPERS/visual_effects.dm
  code/datums/datum.dm
  code/game/atoms/_atom.dm
Labels: size/L

#6841 Fix linters
  maps/endeavour/levels/deck1.dmm
Labels: size/XS

#6838 Adds xenomeat back to xenomorphs
  code/modules/mob/living/simple_mob/subtypes/animal/xenomorph/xenomorph.dm
Labels: size/XS

#6840 Soulcatcher projections no longer have their overlays explode when a new one is added.
  code/modules/nifsoft/software/13_soulcatcher.dm
Labels: size/XS

#6837 Buffs Gammawraith and Demoncore
  code/modules/mob/living/simple_mob/subtypes/occult/constructs/nuclear/demoncore.dm
  code/modules/mob/living/simple_mob/subtypes/occult/constructs/nuclear/gammawraith.dm
Labels: size/S

#6839 make circuit error slightly more verbose
  code/modules/integrated_electronics/core/printer.dm
  code/modules/integrated_electronics/core/saved_circuits.dm
Labels: size/XS

#6827 prevents jitter while dead, and collects some /mob variables from various files
  code/game/click/click.dm
  code/game/gamemodes/cult/cultify/mob.dm
  code/game/rendering/legacy/alert.dm
  code/game/verbs/suicide.dm
  code/modules/admin/admin_attack_log.dm
  code/modules/atmospherics/environmental/zas/airflow.dm
  code/modules/catalogue/atoms.dm
  code/modules/detectivework/tools/rag.dm
  code/modules/keybindings/focus.dm
  code/modules/mob/animations.dm
  code/modules/mob/freelook/eye.dm
  code/modules/mob/living/carbon/human/pain.dm
  code/modules/mob/mob_defines.dm
  code/modules/nano/nanoexternal.dm
  code/modules/preferences/preferences_toggle_procs.dm
Labels: size/L

#6852 adds starting attachment functionality to guns
  code/modules/projectiles/gun.dm
Labels: size/S

#6849 fixes h90k mags
  code/modules/projectiles/ammunition/calibers/normal/a5_7mm.dm
Labels: size/XS

#6825 Metrics API (hollow)
  citadel.dme
  code/global.dm
  code/modules/legacy_metric/activity.dm
  code/modules/legacy_metric/count.dm
  code/modules/legacy_metric/department.dm
  code/modules/legacy_metric/metric.dm
  code/modules/metrics/README.md
  code/modules/metrics/api.dm
  code/modules/metrics/metric.dm
  code/modules/metrics/metric_base.dm
Labels: size/L

#6853 circuit injector fix and adjustment
  code/modules/integrated_electronics/subtypes/reagents.dm
Labels: size/XS

#6848 Fixes R&D related access, some Atlas Science access, and a button's access in Surt
  code/modules/mapping/map_helpers/access_helper/airlock.dm
  maps/rift/levels/rift-02-underground2.dmm
  maps/rift/levels/rift-04-surface1.dmm
  maps/sectors/lavaland_192/levels/lavaland_192.dmm
Labels: size/M

#6854 In the News - 11/11/2024
  code/modules/lore_codex/news_data/main.dm
Labels: size/L

#6859 Ticking reactions will now proper begin & distillery QoL
  code/modules/reagents/chemistry/reagent_holder-reactions.dm
  code/modules/reagents/distilling/Distilling-Recipes.dm
  code/modules/reagents/distilling/distilling.dm
Labels: size/M

#6830 Ahem.. NSV Endeavour Fixes 2
  _mapload/endeavour.dm
  code/game/area/Space Station 13 areas.dm
  code/game/area/endeavour_areas.dm
  maps/endeavour/endeavour-overmap.dm
  maps/endeavour/endeavour-turbolifts.dm
  maps/endeavour/endeavour.dm
  maps/endeavour/engines/rust.dmm
  maps/endeavour/levels/deck1.dmm
  maps/endeavour/levels/deck2.dmm
  maps/endeavour/levels/deck3.dmm
  maps/endeavour/levels/deck4.dmm
  maps/sectors/tradeport_192/levels/tradeport_192.dmm
Labels: size/XXL

#6829 Adds a new model of NT handgun.
  code/datums/design/designs/ammo/pistol.dm
  code/datums/uplink/ammunition.dm
  code/game/content/factions/corporations/nanotrasen/nanotrasen-supply/contraband.dm
  code/game/machinery/vending/security.dm
  code/game/objects/effects/decals/posters/citadel.dm
  code/game/objects/items/gunbox.dm
  code/game/objects/items/storage/lockbox.dm
  code/game/objects/random/guns_and_ammo.dm
  code/game/objects/random/misc.dm
  code/modules/awaymissions/loot_vr.dm
  code/modules/mining/ore_redemption_machine/survey_vendor.dm
  code/modules/projectiles/ammunition/calibers/normal/a45.dm
  code/modules/projectiles/ammunition/calibers/normal/a9mm.dm
  code/modules/projectiles/guns/attachments/flashlight.dm
  code/modules/projectiles/guns/attachments/harness.dm
  code/modules/projectiles/guns/gun_attachment.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  code/modules/random_map/drop/drop_types.dm
  icons/modules/projectiles/attachments/harness.dmi
  icons/modules/projectiles/magazines/old_magazine_stick.dmi
  icons/obj/contraband.dmi
  icons/obj/gun/ballistic.dmi
  icons/obj/storage.dmi
  maps/templates/admin/kk_mercship.dmm
  maps/templates/admin/mercbase.dmm
  maps/tether/levels/surface1.dmm
  maps/tether/levels/surface2.dmm
Labels: size/L

#6863 removes weight gain/loss mechanics
  code/modules/mob/living/carbon/human/life.dm
  code/modules/preferences/preference_setup/vore/02_size.dm
  code/modules/vore/eating/living_vr.dm
  code/modules/vore/persist/persist_vr.dm
  code/modules/vore/weight/fitness_machines_vr.dm
Labels: size/M

#6870 tgui fix
  code/modules/tgui/tgui.dm
Labels: size/XS

#6873 atmos update_values() enforcement
  code/game/objects/items/weapons/flamethrower.dm
  code/modules/admin/verbs/debug.dm
  code/modules/atmospherics/environmental/zas/edges/edge-simulated.dm
  code/modules/atmospherics/gasmixtures/gas_mixture.dm
  code/modules/atmospherics/machinery/portable/canister.dm
  code/modules/events/atmos_leak.dm
  code/modules/gamemaster/actions/atmos_leak.dm
  code/modules/vore/eating/living_vr.dm
Labels: size/M

#6874 readds blu's crates
  code/game/content/factions/corporations/nanotrasen/nanotrasen-supply/hospitality.dm
  code/modules/food/food/snacks.dm
Labels: size/M

#6866 reagent filter backend
  code/__DEFINES/reagents/reagent.dm
  code/game/machinery/Sleeper.dm
  code/modules/reagents/chemistry/reagent.dm
  code/modules/reagents/chemistry/reagent_holder.dm
Labels: size/M

#6876 only send delay message once
  code/controllers/subsystem/ticker.dm
Labels: size/XS

#6878 storage bugfixes
  code/__DEFINES/_planes+layers.dm
  code/game/objects/systems/storage/storage-screen_object.dm
  code/game/rendering/actor_huds/huds/inventory-screen_object.dm
  code/game/rendering/actor_huds/huds/inventory.dm
  code/modules/mob/inventory/inventory-hands-get.dm
  code/modules/mob/living/carbon/carbon.dm
  code/modules/mob/living/living-inventory.dm
  code/modules/mob/living/silicon/robot/robot.dm
  icons/mob/screen/orange.dmi
  icons/mob/screen/white.dmi
  icons/screen/hud/orange/inventory-slot.dmi
  icons/screen/hud/white/inventory-slot.dmi
Labels: size/M

#6879 language bugfixes
  code/modules/language/language.dm
  code/modules/mob/living/silicon/silicon.dm
Labels: size/XS

#6881 design categories / subcategories tags
  code/__DEFINES/datums/design.dm
  code/datums/design/design.dm
  code/modules/research/designs/HUDs.dm
  code/modules/research/designs/ai_holders.dm
  code/modules/research/designs/bag_of_holding.dm
  code/modules/research/designs/beakers.dm
  code/modules/research/designs/bio_devices.dm
  code/modules/research/designs/circuit_assembly.dm
  code/modules/research/designs/circuits/ai_modules.dm
  code/modules/research/designs/circuits/circuits.dm
  code/modules/research/designs/circuits/circuits_vr.dm
  code/modules/research/designs/circuits/computers/misc.dm
  code/modules/research/designs/circuits/disks.dm
  code/modules/research/designs/circuits/machines/chemistry.dm
  code/modules/research/designs/circuits/machines/misc.dm
  code/modules/research/designs/engineering.dm
  code/modules/research/designs/implants.dm
  code/modules/research/designs/locator_devices.dm
  code/modules/research/designs/mechfab_designs.dm
  code/modules/research/designs/medical.dm
  code/modules/research/designs/mining_toys.dm
  code/modules/research/designs/misc.dm
  code/modules/research/designs/modular_computer.dm
  code/modules/research/designs/power_cells.dm
  code/modules/research/designs/precursor.dm
  code/modules/research/designs/prosfab_designs.dm
  code/modules/research/designs/rigs_vr.dm
  code/modules/research/designs/stock_parts.dm
  code/modules/research/designs/subspace_parts.dm
  code/modules/research/designs/tech_disks.dm
  code/modules/research/designs/teleport_vr.dm
  code/modules/research/designs/weapons.dm
  code/modules/research/designs/xenoarch_toys.dm
  code/modules/research/designs/xenobio_toys.dm
Labels: size/L

#6877 fix filterrific
  code/modules/admin/view_variables/filteriffic.dm
Labels: size/XS

#6862 update nightshift
  code/__DEFINES/controllers/_subsystem-init.dm
  code/__DEFINES/controllers/_subsystem-priority.dm
  code/controllers/subsystem/nightshift.dm
  code/modules/power/apc.dm
Labels: size/M

#6886 removes character species, combines BES with normal shadekin
  citadel.dme
  code/controllers/subsystem/characters/character_species.dm
  code/modules/lore_hardcoded/_hardcoded.dm
  code/modules/lore_hardcoded/citizenship.dm
  code/modules/lore_hardcoded/culture.dm
  code/modules/lore_hardcoded/faction.dm
  code/modules/lore_hardcoded/origin.dm
  code/modules/lore_hardcoded/religion.dm
  code/modules/mob/living/carbon/human/human_powers.dm
  code/modules/preferences/migration.dm
  code/modules/preferences/preference_setup/background/citizenship.dm
  code/modules/preferences/preference_setup/background/culture.dm
  code/modules/preferences/preference_setup/background/faction.dm
  code/modules/preferences/preference_setup/background/language.dm
  code/modules/preferences/preference_setup/background/origin.dm
  code/modules/preferences/preference_setup/background/religion.dm
  code/modules/preferences/preference_setup/background/species.dm
  code/modules/preferences/preference_setup/helpers/language_pick.dm
  code/modules/preferences/preference_setup/helpers/species_pick.dm
  code/modules/species/character_species.dm
  code/modules/species/shadekin/blackeyed.dm
  code/modules/species/shadekin/crew_shadekin_abilities.dm
  code/modules/species/shadekin/crew_shadekin_hud.dm
  code/modules/species/shadekin/shadekin.dm
  code/modules/species/shadekin/shadekin_abilities.dm
  code/modules/species/shadekin/shadekin_blackeyed.dm
  code/modules/species/species.dm
  code/modules/species/station/standard/shadekin.dm
  code/unit_tests/human/species.dm
Labels: size/XL

#6851 removes synth defib kits
  citadel.dme
  code/__DEFINES/items/defib.dm
  code/__DEFINES/items/inducer.dm
  code/game/content/factions/corporations/nanotrasen/nanotrasen-supply/robotics.dm
  code/game/objects/items/defib/defib_kit.dm
  code/game/objects/items/defib/shockpaddles.dm
  code/modules/mob/living/silicon/robot/dogborg/dog_modules_vr.dm
  code/modules/mob/living/silicon/robot/robot_modules/station/science.dm
  code/modules/mob/living/silicon/robot/robot_modules/syndicate.dm
  maps/endeavour/levels/deck1.dmm
  maps/endeavour/levels/deck2.dmm
  maps/endeavour/levels/flagship.dmm
  maps/euthenia/levels/deck3.dmm
  maps/map_levels/140x140/talon/talon1.dmm
  maps/rift/levels/rift-05-surface2.dmm
  maps/sectors/admin_planets_192/andromeda.dmm
  maps/sectors/tradeport_192/levels/tradeport_192.dmm
  maps/templates/admin/dhael_centcom.dmm
  maps/templates/shuttles/overmaps/generic/cruiser.dmm
  maps/templates/shuttles/overmaps/generic/curashuttle.dmm
  maps/templates/shuttles/overmaps/generic/shelter_6.dmm
  maps/tether/levels/surface3.dmm
  maps/triumph/levels/deck3.dmm
  maps/triumph/levels/flagship.dmm
Labels: Merge Conflict, size/L

#6887 replaces DME PD turret sprite
  code/game/machinery/pointdefense.dm
  icons/obj/pointdefense.dmi
Labels: size/XS

#6890 fixes OR Windows
  maps/rift/levels/rift-05-surface2.dmm
Labels: size/XS

#6889 Gives everyone to drink from blood bags(blood is still toxic to non-v…
  citadel.dme
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Core.dm
  code/modules/reagents/reagent_containers/blood_pack.dm
  code/modules/reagents/reagent_containers/blood_pack_vr.dm
Labels: size/L

#6880 snowball fix
  code/game/objects/items/weapons/material/misc.dm
Labels: size/XS

#6882 Stop Dying Glacicorns
  code/modules/mob/living/simple_mob/subtypes/animal/farm animals/lythios.dm
Labels: size/XS

#6868 Endeavour Fixes Round 3!
  code/game/area/Space Station 13 areas.dm
  maps/endeavour/levels/deck1.dmm
  maps/endeavour/levels/deck2.dmm
  maps/endeavour/levels/deck3.dmm
  maps/endeavour/levels/deck4.dmm
Labels: size/XXL

#6883 flooring rework
  citadel.dme
  code/__DEFINES/icon_smoothing.dm
  code/__DEFINES/turfs/flooring.dm
  code/controllers/repository/flooring.dm
  code/datums/event_args/actor.dm
  code/datums/prototype.dm
  code/game/atoms/_atom.dm
  code/game/atoms/atom-examine.dm
  code/game/atoms/atom-logging.dm
  code/game/atoms/movable/movable-logging.dm
  code/game/machinery/CableLayer.dm
  code/game/machinery/floorlayer.dm
  code/game/objects/items/devices/floor_painter.dm
  code/game/objects/structures/charge_pylon.dm
  code/game/turfs/simulated/floor/floor-construction.dm
  code/game/turfs/simulated/floor/floor-flooring.dm
  code/game/turfs/simulated/floor/floor.dm
  code/game/turfs/simulated/floor/floor_acts.dm
  code/game/turfs/simulated/floor/floor_attackby.dm
  code/game/turfs/simulated/floor/floor_damage.dm
  code/game/turfs/simulated/floor/floor_icon.dm
  code/game/turfs/simulated/floor/floor_types_eris.dm
  code/game/turfs/simulated/floor_types/concrete.dm
  code/game/turfs/simulated/floor_types/dirt.dm
  code/game/turfs/simulated/floor_types/glass.dm
  code/game/turfs/simulated/floor_types/grass.dm
  code/game/turfs/simulated/floor_types/snow.dm
  code/game/turfs/simulated/floor_types/water.dm
  code/game/turfs/simulated/flooring/flooring.dm
  code/game/turfs/simulated/flooring/flooring_premade.dm
  code/game/turfs/simulated/flooring/flooring_types.dm
  code/game/turfs/simulated/flooring/types/grass.dm
  code/game/turfs/simulated/flooring/types/linoleum.dm
  code/game/turfs/simulated/wall/wall.dm
  code/game/turfs/turf.dm
  code/game/turfs/unsimulated/beach.dm
  code/game/world.dm
  code/modules/admin/verbs/smite.dm
  code/modules/holodeck/HolodeckObjects.dm
  code/modules/logging/api/construction.dm
  code/modules/maps/turf_makers/planetary_turfs.dm
  code/modules/mob/living/bot/floorbot.dm
  code/modules/power/singularity/act.dm
  code/modules/tools/_tool_system.dm
  code/modules/tools/wrappers.dm
  code/modules/vehicles/sealed/mecha/equipment/tools/cable_layer.dm
Labels: size/XXL
