Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2024-03, with the labels that each got.

#6314 Stops dual esword users from accidentally tripping on accident infront of the enemy
  code/game/objects/items/weapons/melee/energy.dm
Labels: Stale, size/S

#6328 Fixes Debris Field POI Spawning
  code/modules/maps/templates/submaps/debrisfield/debrisfield_submaptemplate.dm
  maps/sectors/debrisfield_192/debrisfield_192.dm
  maps/submaps/level_specific/debrisfield_vr/clownship.dmm
Labels: size/XXL

#6324 Makes alcohol intolerance work properly with blood
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Dispenser.dm
Labels: size/XS

#6327 storage re-refactor
  code/controllers/globals.dm
  code/game/objects/items.dm
  code/game/objects/objs.dm
  code/game/objects/systems/storage.dm
  code/modules/admin/verbs/SDQL2/SDQL_2_wrappers.dm
Labels: size/L

#6329 bugfixes
  code/__DEFINES/dcs/signals/signals_atom/signals_atom_throwing.dm
  code/controllers/subsystem/persistence/persistence.dm
  code/controllers/subsystem/ticker.dm
  code/datums/recipe/stack_recipe.dm
  code/datums/soundbytes/effects/sparks.dm
  code/game/gamemodes/technomancer/spells/audible_deception.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/door_control.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/machinery/suit_storage/suit_storage_unit.dm
  code/game/mecha/combat/combat.dm
  code/game/objects/effects/effect_system.dm
  code/game/objects/effects/map_effects/beam_point.dm
  code/game/objects/items.dm
  code/game/objects/items/devices/lightreplacer.dm
  code/game/objects/items/devices/tape_recorder/tape_iterator.dm
  code/game/objects/items/storage/lockbox.dm
  code/game/objects/items/storage/misc_legacy/fancy.dm
  code/game/objects/items/storage/misc_legacy/misc.dm
  code/game/objects/items/storage/secure.dm
  code/game/objects/items/weapons/melee/misc.dm
  code/game/objects/items/weapons/shields.dm
  code/game/objects/items/weapons/stunbaton.dm
  code/game/objects/structures/crates_lockers/__closet.dm
  code/game/objects/structures/crates_lockers/closets/secure/personal.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/turfs/initialization/maintenance.dm
  code/game/turfs/simulated/wall/wall_attacks.dm
  code/modules/assembly/assembly.dm
  code/modules/clothing/suits/armor.dm
  code/modules/economy/items/retail_scanner.dm
  code/modules/economy/machines/cash_register.dm
  code/modules/food/food.dm
  code/modules/food/food/snacks.dm
  code/modules/hardsuits/modules/ninja.dm
  code/modules/hardsuits/modules/utility.dm
  code/modules/mapping/map_helpers/network_builder/_network_builder.dm
  code/modules/mapping/map_helpers/network_builder/power_cable.dm
  code/modules/mob/holder.dm
  code/modules/mob/living/bot/floorbot.dm
  code/modules/mob/living/carbon/carbon_defense.dm
  code/modules/mob/living/movement.dm
  code/modules/mob/living/simple_mob/defense.dm
  code/modules/mob/mob_defines.dm
  code/modules/mob/movement.dm
  code/modules/reagents/chemistry/holder.dm
  code/modules/recycling/disposal.dm
  code/modules/tgui/datum.dm
  code/modules/vore/fluffstuff/custom_items.dm
Labels: Test Merge Candidate, Fix, size/L

#6331 Updates Miaphus: 8 New POIs, Better Transitions!
  code/modules/maps/overmap/planets/miaphus.dm
  code/modules/maps/templates/submaps/class_h/class_h.dm
  maps/sectors/miaphus_192/levels/miaphus_192_beach.dmm
  maps/sectors/miaphus_192/levels/miaphus_192_cave.dmm
  maps/sectors/miaphus_192/levels/miaphus_192_desert.dmm
  maps/submaps/level_specific/class_h/huntercamp.dmm
  maps/submaps/level_specific/class_h/miningcamp.dmm
  maps/submaps/level_specific/class_h/oilwellH.dmm
  maps/submaps/level_specific/class_h/piratehideout.dmm
  maps/submaps/level_specific/class_h/refinery.dmm
  maps/submaps/level_specific/class_h/snipernest.dmm
  maps/submaps/level_specific/class_h/turretnest.dmm
  maps/submaps/level_specific/class_h/wastedump.dmm
Labels: size/XXL

#6335 maybe fixes travis
  code/controllers/subsystem/mapping/maps.dm
  code/modules/mapping/map.dm
  maps/euthenia/euthenia.dm
Labels: size/S

#6332 adds a shaking noise and message to the shaker
  code/modules/food/drinks/shaker.dm
  sound/items/shaker.ogg
Labels: size/S

#6346 fixes prisoner IDs not having genpop entry permissions
  code/game/objects/items/id_cards/station_ids.dm
  code/game/objects/structures/crates_lockers/closets/secure/genpop.dm
Labels: size/XS

#6347 fixes CI
  code/game/objects/random/mob.dm
Labels: size/XS

#6341 adds 4 new hivebots
  code/game/objects/random/mob.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/hivebot/hivebot.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/hivebot/ranged_damage.dm
  code/modules/mob/living/simple_mob/subtypes/mechanical/hivebot/ranged_damage_vr.dm
  icons/mob/hivebot.dmi
Labels: size/L

#6352 fixes wrong fake stairs on miaphus beach
  code/game/objects/effects/debris/cleanable/blood.dm
  code/modules/mapping/submaps_legacy.dm
  code/modules/maps/overmap/space/debrisfield.dm
  maps/sectors/miaphus_192/levels/miaphus_192_beach.dmm
  maps/submaps/level_specific/debrisfield_vr/debris14.dmm
Labels: size/M

#6345 Ghost weight, transfer obfuscation
  code/controllers/subsystem/vote.dm
  config/config.txt
  config/entries/vote.txt
  tgui/packages/tgui/interfaces/Vote.tsx
Labels: size/L

#6339 Atlas Genpop
  citadel.dme
  code/game/area/Space Station 13 areas.dm
  code/game/area/station/security_areas.dm
  code/game/objects/structures/curtains.dm
  maps/rift/levels/rift-02-underground2.dmm
  maps/rift/levels/rift-03-underground1.dmm
  maps/rift/levels/rift-04-surface1.dmm
  maps/rift/levels/rift-05-surface2.dmm
  maps/rift/levels/rift-06-surface3.dmm
  maps/rift/levels/rift-09-west_caves.dmm
  maps/rift/levels/rift-10-west_plains.dmm
  maps/rift/levels/rift-11-orbital.dmm
Labels: size/XXL

#6344 fix centcom names in map strings
  citadel.dme
  code/modules/mapping/merge_conflicts.dm
  icons/effects/mapping_helpers.dmi
  maps/rift/levels/rift-11-orbital.dmm
  maps/templates/admin/dhael_centcom.dmm
  maps/templates/shuttles/overmaps/generic/cruiser.dmm
  maps/tether/levels/misc.dmm
  maps/triumph/levels/flagship.dmm
  tools/mapmerge2/__init__.py
  tools/mapmerge2/merge_driver.py
Labels: size/M

#6351 Debrisfield Hotfix
  code/modules/maps/overmap/space/debrisfield.dm
Labels: size/S

#6355 one star jumpsuit and hat
  code/modules/clothing/head/misc.dm
  code/modules/clothing/under/misc.dm
  code/modules/loadout/loadout_head.dm
  code/modules/loadout/loadout_uniform.dm
  icons/clothing/head/onestar.dmi
  icons/clothing/uniform/misc/onestar.dmi
Labels: size/S

#6356 max name length 52 >> 64
  code/__DEFINES/misc.dm
Labels: size/XS

#6353 adds persistent sheet silos to mining
  citadel.dme
  code/__DEFINES/controllers/persistence.dm
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/materials/flags.dm
  code/controllers/subsystem/persistence/modules/level_objects.dm
  code/controllers/subsystem/persistence/modules/spatial_metadata.dm
  code/datums/datum.dm
  code/game/atoms/atom.dm
  code/game/atoms/movable/movable.dm
  code/game/objects/objs.dm
  code/modules/admin/verbs/debug/reestablish_db_connection.dm
  code/modules/mining/machine_processing.dm
  code/modules/mining/machine_stacking.dm
  code/modules/mining/machine_unloading.dm
  code/modules/mining/machinery/sheet_silo.dm
  code/modules/mining/machinery/sheet_silo_loader.dm
  code/modules/mining/ore_redemption_machine/survey_vendor.dm
  code/modules/mob/characteristics/holder.dm
  code/modules/modular_computers/file_system/computer_file.dm
  code/modules/modular_computers/file_system/programs/generic/file_browser.dm
  code/modules/species/species.dm
  icons/modules/mining/machinery/sheet_silo.dmi
  icons/modules/mining/machinery/sheet_silo_loader.dmi
  icons/obj/machines/mining_machines.dmi
  icons/obj/machines/mining_machines_vr.dmi
  maps/minitest/levels/minitest.dmm
  maps/rift/levels/rift-02-underground2.dmm
  maps/rift/levels/rift-08-west_deep.dmm
  maps/tether/levels/station2.dmm
  maps/triumph/levels/deck2.dmm
  tgui/packages/tgui/interfaces/machines/SheetSilo.tsx
Labels: size/XXL

#6360 Update skateboard injuries
  code/modules/vehicles_legacy/skateboard.dm
Labels: size/S

#6361 Minor update to prisoner IDs
  code/game/objects/items/id_cards/station_ids.dm
Labels: size/S

#6359 genpop QOL updates
  maps/rift/levels/rift-03-underground1.dmm
  maps/rift/levels/rift-04-surface1.dmm
  maps/rift/levels/rift-05-surface2.dmm
Labels: size/XL

#6362 Vending additions
  citadel.dme
  code/game/machinery/vending.dm
  code/game/machinery/vending/drinks.dm
  code/game/machinery/vending/engineering.dm
  code/game/machinery/vending/loadout.dm
  code/game/machinery/vending/medical.dm
  code/game/machinery/vending/misc.dm
  code/game/machinery/vending/plants.dm
  code/game/machinery/vending/research.dm
  code/game/machinery/vending/security.dm
  code/game/machinery/vending/service.dm
  code/game/machinery/vending/snacks.dm
  code/game/machinery/vending/vending.dm
  code/game/objects/items/storage/single_use/mre.dm
  icons/obj/vending.dmi
  maps/rift/levels/rift-06-surface3.dmm
  maps/sectors/gaia_192/levels/gaia_192.dmm
  maps/tether/levels/surface3.dmm
  maps/triumph/levels/deck2.dmm
Labels: size/XXL

#6363 allows pAIs to place up to 5 holograms of things they have scanned
  citadel.dme
  code/game/click/other_mobs.dm
  code/game/objects/items/devices/paicard.dm
  code/modules/mob/living/silicon/pai/actions.dm
  code/modules/mob/living/silicon/pai/death.dm
  code/modules/mob/living/silicon/pai/hologram_effect.dm
  code/modules/mob/living/silicon/pai/pai.dm
  code/modules/mob/living/silicon/pai/verbs.dm
  icons/screen/actions/pai.dmi
Labels: size/L

#6343 git-blame-ignore-revs
  .git-blame-ignore-revs
Labels: size/S
