Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2024-04, with the labels that each got.

#6364 Cryo cell fluid changes opacity
  code/game/machinery/cryo.dm
Labels: size/XS

#6365 remove's pAI suicide verb because they already have the wipe-software verb which handles pAI 'suicide' properly
  code/game/verbs/suicide.dm
Labels: size/S

#6368 NSB Croatoan Map Template
  citadel.dme
  code/modules/maps/overmap/planets/admin_croatoan.dm
  maps/sectors/admin_planets_192/croatoan.dmm
Labels: size/XXL

#6372 fixes game prefs
  tgui/packages/tgui/interfaces/GamePreferences/GamePreferenceEntry.tsx
Labels: size/XS

#6375 NSB Croatoan Map Template Edit-2
  maps/sectors/admin_planets_192/croatoan.dmm
Labels: size/L

#6376 fixes autowire and mapped in wire interference on the euthenia
  maps/euthenia/levels/deck1.dmm
  maps/euthenia/levels/deck2.dmm
  maps/euthenia/levels/deck3.dmm
  maps/euthenia/levels/deck4.dmm
Labels: size/XL

#6377 adds the actual location to the runtime message of the networkbuilder…
  code/modules/mapping/map_helpers/network_builder/_network_builder.dm
Labels: size/XS

#6371 Z-Mimic Season Pass 1
  citadel.dme
  code/__DEFINES/rendering/zmimic.dm
  code/controllers/subsystem/zcopy.dm
  code/game/atoms/movable/movement.dm
  code/modules/admin/verbs/mapping.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/silicon/robot/robot.dm
  code/modules/multiz/turf.dm
  code/modules/multiz/turfs/open.dm
  code/modules/multiz/zmimic/mimic_movable.dm
  code/modules/multiz/zmimic/mimic_turf.dm
Labels: size/XL

#6378 Add vulpkanin background info
  code/modules/lore_hardcoded/citizenship.dm
  code/modules/lore_hardcoded/origin.dm
  code/modules/lore_hardcoded/religion.dm
Labels: size/S

#6380 "Re"adds medical hardsuit to triumph
  maps/triumph/levels/deck3.dmm
Labels: size/XS

#6387 print map when starting Mapping init
  code/controllers/subsystem/mapping/_mapping.dm
Labels: size/XS

#6381 Adds Sponge
  code/modules/detectivework/tools/rag.dm
  icons/obj/sponge.dmi
  maps/rift/levels/rift-04-surface1.dmm
  maps/triumph/levels/deck2.dmm
Labels: size/S

#6384 maybe fixes carpet
  code/modules/hydroponics/seed_datums.dm
Labels: size/XS

#6383 fixes limb damage & slight promethean rebalance
  code/modules/organs/external/external.dm
  code/modules/organs/external/species/slime.dm
  code/modules/species/promethean/promethean.dm
Labels: Priority 0: CRITICAL, size/M

#6382 fixes prefs early init issue
  code/controllers/subsystem/preferences.dm
  code/modules/client/client_procs.dm
Labels: size/S

#6388 Adds a 'Mega Milk' shirt
  code/game/machinery/vending/loadout.dm
  code/modules/clothing/under/accessories/clothing.dm
  icons/mob/clothing/ties.dmi
Labels: size/S

#6390 Fixes the subtler hotkey opening up the subtle textbox
  code/modules/keybindings/keybind/mob.dm
  code/modules/mob/say.dm
Labels: size/XS

#6389 Modernizes the hair gradient 'vsplit' (along with all of its 2 variants)
  icons/mob/hair_gradients.dmi
Labels: size/XS

#6394 Fixes gimlet recipe
  code/modules/reagents/Drink-Recipes.dm
Labels: size/XS

#6398 fixes potential race condition in prefs
  code/controllers/subsystem/preferences.dm
Labels: Priority 1: High, size/XS

#6400 Fixes Mega Milk shirt's missing icon
  icons/obj/clothing/ties.dmi
Labels: size/XS

#6399 Fixes disposals hiding permanently
  code/modules/recycling/disposal.dm
Labels: size/S

#6386 does stuff to tether nobody asked for, and some stuff people asked for
  code/game/machinery/embedded_controller/airlock_program.dm
  code/game/machinery/suit_storage/suit_storage_prepared.dm
  code/modules/atmospherics/machinery/components/unary/vent_scrubber.dm
  code/modules/maps/overmap/planets/_virgo3b.dm
  code/modules/power/tesla/coil.dm
  icons/obj/atmos.dmi
  maps/tether/engines/rust.dmm
  maps/tether/levels/mining.dmm
  maps/tether/levels/plains.dmm
  maps/tether/levels/station1.dmm
  maps/tether/levels/station2.dmm
  maps/tether/levels/surface1.dmm
  maps/tether/levels/surface2.dmm
  maps/tether/levels/surface3.dmm
  maps/tether/levels/underdark.dmm
  maps/tether/tether.dm
Labels: size/XXL

#6392 Sponge 2.0 just a week away
  code/modules/detectivework/tools/rag.dm
  icons/obj/sponge.dmi
Labels: size/S

#6404 adds a couple of player plushies
  citadel.dme
  code/modules/loadout/loadout_general.dm
  fluff/donator/djkouta/donator_cloak.dm
  fluff/donator/djkouta/donator_cloak.dmi
  fluff/donator/legacy.dm
  fluff/donator/timothytea/donator_bedsheet.dm
  fluff/donator/timothytea/donator_bedsheet.dmi
  fluff/donator/unclebourbon/pmc_mask.dm
  fluff/donator/unclebourbon/pmc_mask.dmi
  fluff/plushies/plushies.dm
  fluff/plushies/plushies.dmi
Labels: size/M

#6405 Removes the PTO (NOT OFF DUTY) system
  SQL/database_schema.sql
  citadel.dme
  code/controllers/configuration_old/configuration_vr.dm
  code/controllers/subsystem/persist_vr.dm
  code/game/machinery/computer/timeclock_vr.dm
  code/modules/client/client.dm
  code/modules/client/client_procs.dm
  code/modules/client/legacy.dm
  code/modules/jobs/job.dm
  code/modules/jobs/job_types/station/civillian/assistant.dm
  code/modules/jobs/job_types/station/offduty/_offduty.dm
  code/modules/jobs/job_types/station/offduty/command.dm
  tgui/packages/tgui/interfaces/TimeClock.js
Labels: size/L

#6406 we are now a 515 server
  dependencies.sh
Labels: size/XS

#6410 Update fucky_wucky.dm
  code/modules/admin/verbs/debug/fucky_wucky.dm
Labels: size/XS

#6409 generic obj rotation system
  code/__DEFINES/_flags/obj_flags.dm
  code/game/objects/objs.dm
  code/modules/reagents/machinery/dispenser/dispenser.dm
  code/modules/vehicles_legacy/vehicle.dm
Labels: size/M

#6412 Replaces the cig vendor in the marksman bar/grill with a hacked MRE vendor
  maps/triumph/levels/flagship.dmm
Labels: size/XS

#6407 fixes cryotubes
  code/__DEFINES/traits/mob.dm
  code/__DEFINES/traits/sources.dm
  code/game/machinery/cryo.dm
  code/modules/mob/living/carbon/human/life.dm
  code/modules/mob/living/health.dm
  code/modules/mob/living/mobility.dm
Labels: size/M

#6411 tesh plushie
  fluff/plushies/plushies.dm
  fluff/plushies/plushies.dmi
Labels: size/XS

#6413 Makes exsanguination not make blood uninjectable
  code/modules/mob/living/carbon/human/blood.dm
Labels: size/S

#6414 Ports 4 types of undershirts from Skyrat; turtlenecks! (and removes the old ones)
  code/datums/underwear/undershirts.dm
  icons/mob/human.dmi
Labels: size/S
