Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2025-07, with the labels that each got.

#7160 fixes reboot verb
  code/game/world.dm
Labels: size/S

#7226 SDF part 2 : Mistakes fix
  code/game/objects/items/id_cards/station_ids.dm
  code/modules/ghostroles/roles/sdf.dm
  html/changelogs/AutoChangeLog-pr-7227.yml
  maps/endeavour/levels/deck4.dmm
  maps/sectors/miaphus/levels/miaphus_beach.dmm
  maps/sectors/miaphus/miaphus-shuttles.dm
Labels: size/XXL

#7233 Adjacency groups
  citadel.dme
  code/__DEFINES/directional.dm
  code/__DEFINES/objects/object_systems/adjacency_group.dm
  code/__DEFINES/objects/objects.dm
  code/__DEFINES/traits/objects.dm
  code/game/objects/systems/adjacency_group.dm
  code/modules/automata/types/wave.dm
Labels: size/L

#7236 SDF : StrongDmm Trolled me.
  code/modules/ghostroles/roles/sdf.dm
  maps/sectors/miaphus/levels/miaphus_beach.dmm
Labels: size/M

#7237 fixes erroneous revert of endeavour files
  maps/endeavour/levels/deck1.dmm
  maps/endeavour/levels/deck3.dmm
  maps/endeavour/levels/deck4.dmm
Labels: size/XXL

#7232 stair fix at the sky planet town
  maps/sectors/sky_planet/levels/sky_planet_sky_west.dmm
Labels: size/S

#7224 playtime viewer
  citadel.dme
  code/__DEFINES/_cooldowns.dm
  code/controllers/subsystem/playtime.dm
  code/modules/client/client.dm
  code/modules/client/data/client_data.dm
  code/modules/client/verbs/view_playtime.dm
  dependencies.sh
  tgui/packages/tgui/interfaces/client/ClientPlaytime.tsx
Labels: size/L

#7243 Lythios Caves POIs
  code/modules/maps/templates/submaps/lythios_rift/lyhtios.dm
  maps/rift/levels/rift-07-west_base.dmm
  maps/rift/levels/rift-08-west_deep.dmm
  maps/rift/levels/rift-09-west_caves.dmm
  maps/rift/rift.dm
  maps/submaps/lythios_rift/caves/west_caves_buriedhangar.dmm
  maps/submaps/lythios_rift/caves/west_caves_buriedstructure_1.dmm
  maps/submaps/lythios_rift/caves/west_caves_buriedstructure_2.dmm
  maps/submaps/lythios_rift/caves/west_caves_cavern_minefield.dmm
  maps/submaps/lythios_rift/caves/west_caves_firingrange.dmm
  maps/submaps/lythios_rift/caves/west_caves_garage.dmm
  maps/submaps/lythios_rift/caves/west_caves_massgrave.dmm
  maps/submaps/lythios_rift/caves/west_caves_massgrave_cursed.dmm
  maps/submaps/lythios_rift/caves/west_caves_mines.dmm
  maps/submaps/lythios_rift/caves/west_caves_radcoffin.dmm
  maps/submaps/lythios_rift/caves/west_caves_radcoffin_cursed.dmm
  maps/submaps/lythios_rift/caves/west_caves_vehicle_graveyard.dmm
Labels: size/XXL

#7241 Additions and fixes on the Strelka
  maps/strelka/levels/flagship.dmm
  maps/strelka/levels/strelka_deck1.dmm
  maps/strelka/levels/strelka_deck2.dmm
  maps/strelka/levels/strelka_deck3.dmm
  maps/strelka/levels/strelka_deck4.dmm
  maps/strelka/strelka-shuttles.dm
Labels: size/XXL

#7246 The Delta Dav Fixing things added moment
  code/__DEFINES/radio.dm
  code/controllers/communications.dm
  code/datums/outfits/ghostrole.dm
  code/game/objects/items/devices/radio/encryptionkey.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/devices/radio/radio.dm
  code/modules/ghostroles/roles/sdf.dm
  code/modules/mob/living/say.dm
  interface/stylesheet.dm
  maps/sectors/miaphus/levels/miaphus_beach.dmm
  maps/sectors/nebula_tradeport/levels/nebula_tradeport.dmm
  maps/strelka/levels/flagship.dmm
  maps/strelka/levels/strelka_deck1.dmm
  maps/strelka/levels/strelka_deck2.dmm
  maps/strelka/levels/strelka_deck3.dmm
  maps/strelka/levels/strelka_deck4.dmm
  maps/submaps/level_specific/debrisfield_vr/mining_drones.dmm
  nano/templates/radio_basic.tmpl
  tgui/packages/tgui-panel/chat/constants.ts
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
Labels: size/XXL

#7251 rt_medieval wall smoothing
  code/game/turfs/simulated/wall/subtypes/rt_medieval.dm
  code/game/turfs/simulated/wall/wall.dm
  icon_cutter_templates/README.md
  icon_cutter_templates/bitmask/cardinal_32x32.toml
  icon_cutter_templates/bitmask/diagonal_32x32.toml
  icon_cutter_templates/bitmask/wall_32x32.toml
  icon_cutter_templates/impl/README.md
  icon_cutter_templates/impl/wall/rt_medieval.toml
  icon_cutter_templates/impl/wall_default.toml
  icons/turf/walls/rt_medieval/boss.dmi
  icons/turf/walls/rt_medieval/boss.png
  icons/turf/walls/rt_medieval/boss.png.toml
  icons/turf/walls/rt_medieval/brick.dmi
  icons/turf/walls/rt_medieval/stone.dmi
  icons/turf/walls/rt_medieval/stone.png
  icons/turf/walls/rt_medieval/stone.png.toml
  icons/turf/walls/rt_medieval/stone/brick.dmi
  icons/turf/walls/rt_medieval/stone/brick.png
  icons/turf/walls/rt_medieval/stone/brick.png.toml
  icons/turf/walls/rt_medieval/stone/craft.dmi
  icons/turf/walls/rt_medieval/stone/craft.png
  icons/turf/walls/rt_medieval/stone/craft.png.toml
  icons/turf/walls/rt_medieval/stone/moss_blue.dmi
  icons/turf/walls/rt_medieval/stone/moss_blue.png
  icons/turf/walls/rt_medieval/stone/moss_blue.png.toml
  icons/turf/walls/rt_medieval/stone/moss_green.dmi
  icons/turf/walls/rt_medieval/stone/moss_green.png
  icons/turf/walls/rt_medieval/stone/moss_green.png.toml
  icons/turf/walls/rt_medieval/stone/moss_red.dmi
  icons/turf/walls/rt_medieval/stone/moss_red.png
  icons/turf/walls/rt_medieval/stone/moss_red.png.toml
  icons/turf/walls/rt_medieval/wood.dmi
  icons/turf/walls/rt_medieval/wood.png
  icons/turf/walls/rt_medieval/wood.png.toml
  tools/build/build.js
Labels: size/L

#7152 Scrubbing fix
  code/modules/mob/living/silicon/robot/robot.dm
Labels: size/M
