Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2025-02, with the labels that each got.

#6982 stops gibbing people killing them twice
  code/modules/mob/living/carbon/human/death.dm
  code/modules/organs/organ.dm
Labels: size/XS

#6981 Effectivly gives xenochimera the weaving trait
  code/modules/organs/internal/species/xenochimera.dm
  code/modules/species/station/xenochimera.dm
Labels: size/S

#6984 Enigma Tweaks
  code/modules/mob/living/simple_mob/subtypes/mechanical/hivebot/enigma_hivebot.dm
Labels: size/M

#6962 Create hangarbase.dmm
  maps/overmap/POIs/hangarbase.dmm
Labels: size/XXL

#6985 Tajaran Speed Nerf
  code/modules/species/station/standard/tajaran.dm
Labels: size/XS

#6972 Guerilla Bandits and Insurgents Oh My!: Adhomai's Cold War comes in Hot!
  citadel.dme
  code/__DEFINES/mobs/iff.dm
  code/game/content/factions/tajara/_generic/guns.dm
  code/game/content/factions/tajara/dra/guns.dm
  code/game/content/factions/tajara/nka/guns.dm
  code/game/content/factions/tajara/pra/guns.dm
  code/modules/ai/holders/polaris/say_list.dm
  code/modules/awaymissions/corpse.dm
  code/modules/mob/living/simple_mob/subtypes/humanoid/mercs/taj_guerilla.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  code/modules/projectiles/guns/projectile/boltaction.dm
  code/modules/projectiles/guns/projectile/contender.dm
  code/modules/projectiles/guns/projectile/musket.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  code/modules/projectiles/guns/projectile/revolver.dm
  code/modules/projectiles/guns/projectile/sniper.dm
  icons/content/factions/orion/iwl/items/guns/k25.dmi
  icons/content/factions/tajara/items/guns/taj_arifle.dmi
  icons/content/factions/tajara/items/guns/taj_automat.dmi
  icons/content/factions/tajara/items/guns/taj_boltaction.dmi
  icons/content/factions/tajara/items/guns/taj_colt.dmi
  icons/content/factions/tajara/items/guns/taj_deagle.dmi
  icons/content/factions/tajara/items/guns/taj_duelinglaser.dmi
  icons/content/factions/tajara/items/guns/taj_fal.dmi
  icons/content/factions/tajara/items/guns/taj_k25.dmi
  icons/content/factions/tajara/items/guns/taj_musket.dmi
  icons/content/factions/tajara/items/guns/taj_pockrifle.dmi
  icons/content/factions/tajara/items/guns/taj_revolver.dmi
  icons/content/factions/tajara/items/guns/taj_svd.dmi
  icons/content/factions/tajara/items/guns/taj_uzi.dmi
  icons/mob/taj_guerilla.dmi
Labels: size/XL

#6983 dropkick ie8 from tgui
  tgui/.eslintignore
  tgui/.eslintrc-sonar.yml
  tgui/.eslintrc.yml
  tgui/babel.config.js
  tgui/package.json
  tgui/packages/tgui-polyfill/00-html5shiv.js
  tgui/packages/tgui-polyfill/01-ie8.js
  tgui/packages/tgui-polyfill/02-dom4.js
  tgui/packages/tgui-polyfill/03-css-om.js
  tgui/packages/tgui-polyfill/1-misc.js
  tgui/packages/tgui-polyfill/10-misc.js
  tgui/packages/tgui-polyfill/package.json
  tgui/public/tgui-polyfill.min.js
  tgui/tsconfig.json
  tgui/webpack.config.js
  tgui/yarn.lock
Labels: size/XXL

#6979 IC filter fix plus additions
  code/modules/integrated_electronics/subtypes/filters.dm
  code/modules/integrated_electronics/subtypes/input.dm
  code/modules/integrated_electronics/subtypes/reagents.dm
Labels: Stale, size/L

#6992 Mech sleeper update
  code/modules/vehicles/sealed/mecha/equipment/tools/sleeper.dm
Labels: size/L

#6987 maptext fonts
  citadel.dme
  code/__DEFINES/fonts.dm
  code/__DEFINES/machinery.dm
  code/__DEFINES/mobs/mobs.dm
  code/__DEFINES/text.dm
  code/game/atoms/movable/movable.dm
  code/game/rendering/legacy/ability_screen_objects.dm
  code/game/rendering/legacy/movable_screen_objects.dm
  code/modules/automata/types/wave.dm
  code/modules/clothing/under/gear_harness.dm
  interface/fonts/Grand9K_Pixel.ttf
  interface/fonts/Pixellari.ttf
  interface/fonts/SpessFont.ttf
  interface/fonts/TinyUnicode.ttf
  interface/fonts/VCR_OSD_Mono.ttf
  interface/fonts/fonts_datum.dm
  interface/fonts/grand_9k.dm
  interface/fonts/license.txt
  interface/fonts/pixellari.dm
  interface/fonts/spess_font.dm
  interface/fonts/tiny_unicode.dm
  interface/fonts/vcr_osd_mono.dm
  interface/skin.dmf
Labels: size/XXL

#6980 Show contractors Employing Company+Allow alt titles
  code/game/objects/items/id_cards/contractor_ids.dm
Labels: size/S

#6988 fixes canister sprites, BES energy, and keybinds
  code/game/rendering/actor_huds/huds/inventory.dm
  code/modules/atmospherics/machinery/portable/canister.dm
  code/modules/species/shadekin/blackeyed.dm
  icons/modules/atmospherics/portable/canister.dmi
  icons/obj/atmos.dmi
  tgui/packages/tgui/interfaces/GamePreferences/GamePreferenceKeybinds.tsx
Labels: size/L

#6994 Fixes for : The Old Century Shuttle (Powerwise/Light wise) / Library scanner on Atlas / Scoophead
  code/game/area/station/shuttle_area.dm
  maps/rift/levels/rift-04-surface1.dmm
  maps/rift/levels/rift-06-surface3.dmm
  maps/rift/shuttles.dm
  maps/sectors/nebula_tradeport/levels/nebula_tradeport.dmm
  maps/sectors/nebula_tradeport/nebula_tradeport-shuttles.dm
Labels: size/L

#6993 Fixes some off-model bodysuits
  icons/clothing/uniform/misc/bodysuit_alt.dmi
  icons/clothing/uniform/misc/replika.dmi
  icons/mob/cyberlimbs/replikant/replikant2.dmi
  icons/mob/sprite_accessories/markings/synth_stuff.dmi
Labels: size/XS

#6995 Fixes Xenohybrid nests being pitch black
  code/modules/species/station/xenomorph_hybrids/hybrid_resin.dm
Labels: size/XS

#6996 Adjusting Mining Points to Thaler ratio
  code/modules/mining/ore_redemption_machine/equipment_vendor.dm
Labels: size/XS

#6998 IC bug fix and new sink siphon
  code/modules/integrated_electronics/subtypes/input.dm
  code/modules/integrated_electronics/subtypes/reagents.dm
Labels: size/M

#7008 bugfixes
  code/game/objects/items/weapons/material/twohanded.dm
  code/modules/mining/machinery/sheet_silo.dm
  code/modules/projectiles/guns/gun-firing.dm
  code/modules/xenobio/items/weapons.dm
Labels: size/M

#7015 Removal of the fighter event
  code/modules/events/event_container.dm
  code/modules/events/event_container_vr.dm
Labels: size/XS

#7014 Non-Nt workers now get their chosen title in the manifest
  code/datums/datacore.dm
Labels: size/XS

#7013 Gives station reporters a press badge and tape recorder
  code/modules/jobs/job_types/station/civillian/librarian.dm
Labels: size/XS

#7012 ejecting a tank from a canister only warns your, if you would endanger yourself
  code/modules/atmospherics/machinery/portable/canister.dm
Labels: size/XS
