Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2025-03, with the labels that each got.

#6939 Outlaw faction shuttle (map)
  citadel.dme
  maps/shuttles/factions/generic/outlaw/reaver.dm
  maps/shuttles/factions/generic/outlaw/reaver.dmm
Labels: size/XXL

#7011 holosphere fixes (autohiss support, survival box, nanopaste, speaking EAL)
  code/__DEFINES/species/species_flags.dm
  code/game/machinery/rechargestation.dm
  code/game/objects/items/stacks/nanopaste.dm
  code/modules/language/language.dm
  code/modules/mob/living/autohiss.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/mob/living/say.dm
  code/modules/power/cells/power_cells.dm
  code/modules/species/holosphere/holosphere.dm
  code/modules/species/holosphere/holosphere_shell.dm
Labels: size/M

#7005 refactors point redemption vendors
  citadel.dme
  code/__DEFINES/misc/point_redemption.dm
  code/__DEFINES/procs/clickcode.dm
  code/game/machinery/computer/command/card.dm
  code/game/machinery/point_redemption_vendor/construction.dm
  code/game/machinery/point_redemption_vendor/point_redemption_item.dm
  code/game/machinery/point_redemption_vendor/point_redemption_vendor.dm
  code/game/machinery/point_redemption_vendor/point_redemption_voucher.dm
  code/game/machinery/point_redemption_vendor/types/engineering.dm
  code/game/machinery/point_redemption_vendor/types/mining.dm
  code/game/machinery/point_redemption_vendor/types/survey.dm
  code/game/machinery/point_redemption_vendor/unsorted_please_sort_these.dm
  code/game/objects/items/id_cards/station_ids.dm
  code/game/objects/structures/crates_lockers/closets/secure/explorer.dm
  code/modules/catalogue/cataloguer.dm
  code/modules/mining/machinery/machine_processing.dm
  code/modules/mining/ore_redemption_machine/engineering_points_vendor.dm
  code/modules/mining/ore_redemption_machine/equipment_vendor.dm
  code/modules/mining/ore_redemption_machine/mine_point_items.dm
  code/modules/mining/ore_redemption_machine/survey_vendor.dm
  code/modules/modular_computers/file_system/programs/command/card.dm
  code/modules/power/crypto_miner.dm
  code/modules/tgui/datum.dm
  code/modules/tgui/tgui.dm
  icons/machinery/point_redemption_vendor/engineering.dmi
  icons/machinery/point_redemption_vendor/mining.dmi
  icons/machinery/point_redemption_vendor/survey.dmi
  icons/obj/card_new.dmi
  icons/obj/card_new_vr.dmi
  icons/obj/machines/mining_machines.dmi
  maps/endeavour/levels/deck1.dmm
  maps/endeavour/levels/deck3.dmm
  maps/endeavour/levels/deck4.dmm
  maps/euthenia/levels/deck2.dmm
  maps/euthenia/levels/deck4.dmm
  maps/rift/levels/rift-02-underground2.dmm
  maps/rift/levels/rift-06-surface3.dmm
  maps/rift/levels/rift-08-west_deep.dmm
  maps/rift/levels/rift-09-west_caves.dmm
  maps/sectors/miaphus/levels/miaphus_beach.dmm
  maps/sectors/surt/levels/surt_west.dmm
  maps/templates/shuttles/overmaps/generic/shelter_6.dmm
  maps/templates/shuttles/overmaps/generic/vespa.dmm
  maps/tether/levels/station1.dmm
  maps/tether/levels/station2.dmm
  maps/triumph/levels/deck1.dmm
  maps/triumph/levels/deck2.dmm
  maps/triumph/levels/deck4.dmm
  tgui/packages/tgui/interfaces/machines/PointRedemptionVendor.tsx
  tgui/packages/tgui/routes.tsx
Labels: size/XXL

#7020 Makes cigarette butts go to hand instead of drop by default
  code/game/objects/items/weapons/cigs_lighters.dm
Labels: Test Merge Candidate, size/XS

#7023 holosphere fixes
  code/modules/organs/external/external.dm
  code/modules/species/holosphere/appearance.dm
  code/modules/species/holosphere/holosphere_shell.dm
Labels: Test Merge Candidate, size/S

#7022 Fix cannister sprites after removing a tank
  code/modules/atmospherics/machinery/portable/canister.dm
  code/modules/atmospherics/machinery/portable/portable_atmospherics.dm
Labels: size/S

#7027 Fixes Surt Mob Factions
  code/game/objects/mob_spawner.dm
Labels: size/XS

#7032 fixes revolver
  code/modules/projectiles/guns/gun/projectile/ballistic.dm
Labels: size/XS

#7035 ballistics hotfix
  code/modules/projectiles/guns/gun.dm
  code/modules/projectiles/guns/gun/projectile/ballistic-interaction.dm
Labels: size/S

#7037 removes suicide from carbons and suicide_act
  code/game/gamemodes/changeling/powers/armblade.dm
  code/game/objects/items.dm
  code/game/objects/items/melee/types/misc.dm
  code/game/objects/items/tools/screwdriver.dm
  code/game/objects/items/weapons/RPD.dm
  code/game/objects/items/weapons/material/chainsaw.dm
  code/game/objects/items/weapons/material/knives.dm
  code/game/objects/items/weapons/material/shards.dm
  code/game/objects/items/weapons/material/swords.dm
  code/game/objects/items/weapons/stunbaton.dm
  code/game/objects/items/weapons/surgery_tools.dm
  code/game/objects/items/weapons/traps.dm
  code/game/verbs/suicide.dm
  code/modules/instruments/instruments/item.dm
  code/modules/paperwork/clipboard.dm
  code/modules/paperwork/folders.dm
  code/modules/power/cable.dm
  code/modules/power/cell.dm
  code/modules/projectiles/guns/gun/vr_legacy/gunsword.dm
  code/modules/spells/artifacts.dm
  code/modules/vore/fluffstuff/custom_items.dm
Labels: size/L

#7026 'Asymetric' Sweater
  code/modules/clothing/under/accessories/clothing.dm
  code/modules/clothing/under/shorts.dm
  icons/mob/clothing/sweaters.dmi
  icons/mob/clothing/ties.dmi
  icons/mob/clothing/uniform_rolled_down.dmi
Labels: size/S

#7038 Makes "Give" verb show a message if you clicked it and it's showing a prompt
  code/modules/mob/living/carbon/give.dm
Labels: size/XS

#7043 The Lythios Colonist Ghost Role: Invasion of the Cat People
  citadel.dme
  code/__DEFINES/recipes.dm
  code/datums/components/crafting/crafting.dm
  code/datums/outfits/ghostrole.dm
  code/datums/recipe/crafting_recipes/recipes_misc.dm
  code/datums/recipe/crafting_recipes/recipes_special.dm
  code/game/objects/items/id_cards/station_ids.dm
  code/game/objects/items/stacks/sheets/leather.dm
  code/game/objects/items/weapons/material/twohanded.dm
  code/game/objects/items/weapons/swords_axes_etc.dm
  code/game/objects/random/mapping.dm
  code/game/objects/structures/flora.dm
  code/modules/clothing/suits/aliens/tajara.dm
  code/modules/clothing/under/accessories/permits.dm
  code/modules/food/drinks/can.dm
  code/modules/food/drinks/flask.dm
  code/modules/food/food/snacks.dm
  code/modules/ghostroles/roles/lythios_colonist.dm
  code/modules/mob/living/simple_mob/simple_mob.dm
  code/modules/mob/living/simple_mob/subtypes/animal/farm animals/lythios.dm
  code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/_giant_spider.dm
  code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/carrier.dm
  code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/electric.dm
  code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/frost.dm
  code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/hunter.dm
  code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/ion.dm
  code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/lurker.dm
  code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/nurse.dm
  code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/pepper.dm
  code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/phorogenic.dm
  code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/thermic.dm
  code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/tunneler.dm
  code/modules/mob/living/simple_mob/subtypes/animal/giant_spider/webslinger.dm
  code/modules/projectiles/guns/gun/projectile/ballistic/musket.dm
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Food-Drinks.dm
  code/modules/reagents/items/spray.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  icons/obj/card_cit.dmi
  icons/obj/drinks.dmi
  icons/obj/flora/snowflora.dmi
  icons/obj/food.dmi
  icons/obj/medical/chemical.dmi
  icons/obj/medical/syringe.dmi
  icons/obj/weapons.dmi
  maps/rift/levels/rift-03-underground1.dmm
Labels: size/XL

#7045 fix flares not turning off properly
  code/game/objects/items/devices/flashlight.dm
Labels: size/XS

#7047 Fixes shrimp cocktail recipe
  code/modules/food/recipes_microwave.dm
Labels: size/XS

#7049 readds blob ID
  code/modules/species/protean/protean_blob.dm
Labels: size/S

#7050 Loadout webbing preview
  code/modules/loadout/loadout_utility.dm
Labels: size/XS

#7039 fix turrets
  code/game/machinery/turrets/turret.dm
Labels: size/S

#7046 Don't drown while flying over the water
  code/game/turfs/simulated/floor_types/water.dm
Labels: size/XS

#7041 Casino Fixes
  maps/sectors/delerict_casino/levels/delerict_casino.dmm
Labels: size/XXL

#7048 Touches up xenochimera adaptations
  code/modules/species/station/xenochimera.dm
Labels: size/L

#7060 Fixes grave digging not checking do_after
  code/game/turfs/simulated/floor_types/snow.dm
  code/game/turfs/unsimulated/beach.dm
  code/modules/mining/mine_turfs.dm
Labels: size/S

#7058 Correct title for the Floral Shoppe Album Song
  code/modules/mob/living/living-defense.dm
  config_static/jukebox.json
Labels: size/XS

#7057 you no longer visually bleed if you have no blood
  code/modules/mob/living/carbon/human/human-defense-legacy.dm
Labels: size/XS
