Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2025-06, with the labels that each got.

#7193 Post DDOS Linter Fixes
  code/__HELPERS/lists/merge.dm
  tools/ci/download_byond.sh
  tools/ci/install/install_byond.sh
Labels: size/S

#7194 fixes maps
  maps/templates/admin/shipcave.dmm
Labels: Priority 1: High, size/XS

#7192 Shadekin-Spacekin-Futureproofing
  code/modules/species/shadekin/shadekin.dm
  code/modules/species/shadekin/shadekin_traits.dm
Labels: size/S

#7201 plane fix
  code/game/rendering/plane_masters/plane_render.dm
Labels: size/XS

#7204 Patches remaining TGUI ghost interactions
  code/game/machinery/computer/misc/bioscan.dm
  code/game/machinery/holopad.dm
  code/game/machinery/teleporter/console.dm
  code/modules/economy/machines/ATM.dm
  code/modules/nanites/chamber_control.dm
  code/modules/tgui/modules/general/cardmod.dm
Labels: size/S

#7203 Further Pallet Jack Tweaks (MIT licensing because i mcfuckin Forgot, and also random-colored pallet jacks)
  code/game/objects/structures/palletjack.dm
Labels: size/XS

#7191 oops, I forgot to migrate shadekin on ID change
  code/__DEFINES/preferences/savefiles.dm
  code/modules/preferences/migration.dm
Labels: size/XS

#7190 New Endeavour Explo Shuttle
  maps/endeavour/levels/deck1.dmm
  maps/endeavour/shuttles.dm
Labels: size/XXL

#7205 computers no longer block clicks
  code/game/machinery/computer/computer.dm
Labels: size/XS

#7210 Fixes another CI issue
  code/controllers/toml_config/toml_configuration.dm
Labels: size/XS

#7213 shuttles no longer add sector name infront of the Landingpoint name, landingpoints should do that themselves
  code/modules/overmap/legacy/overmap_shuttle.dm
  code/modules/overmap/legacy/ships/computers/shuttle.dm
Labels: size/XS

#7218 gives protean blobs matrix recolor for themselves + fixes holder onmobs
  citadel.dme
  code/modules/clothing/chameleon.dm
  code/modules/mob/holder.dm
  code/modules/species/protean/blob_recolor.dm
  code/modules/species/protean/protean_blob.dm
Labels: size/L

#7223 Strelka fix
  maps/strelka/levels/strelka_deck1.dmm
  maps/strelka/levels/strelka_deck2.dmm
  maps/strelka/levels/strelka_deck3.dmm
  maps/strelka/levels/strelka_deck4.dmm
  maps/strelka/strelka-papers.dm
Labels: size/XXL

#7225 inflict agony actually inflicts agony/hallos
  code/modules/projectiles/projectile/projectile.dm
Labels: size/XS

#7216 Sometimes I need sense slapped into me
  maps/endeavour/endeavour.dm
  maps/endeavour/levels/deck1.dmm
  maps/endeavour/levels/deck2.dmm
  maps/endeavour/levels/deck3.dmm
Labels: size/XL

#7217 Ghostrole : Haddi's Folley System Defence Force
  citadel.dme
  code/__DEFINES/access.dm
  code/datums/outfits/ghostrole.dm
  code/game/objects/items/id_cards/station_ids.dm
  code/modules/clothing/under/xenos/tajaran.dm
  code/modules/ghostroles/roles/sdf.dm
  code/modules/mapping/map_helpers/access_helper/airlock.dm
  icons/mob/clothing/species/tajaran/uniform.dmi
  icons/obj/card_cit.dmi
  icons/obj/structures/miaphus_structure.dmi
  maps/sectors/miaphus/levels/miaphus_beach.dmm
  maps/sectors/miaphus/miaphus-areas.dm
  maps/sectors/miaphus/miaphus-misc.dm
  maps/sectors/miaphus/miaphus-shuttles.dm
  maps/sectors/miaphus/miaphus.dm
  maps/sectors/sky_planet/sky_planet-misc.dm
Labels: size/XXL

#7209 Adds Security Ticket Printers
  citadel.dme
  code/game/objects/items/devices/ticket_printer.dm
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  icons/obj/bureaucracy.dmi
  icons/obj/device_vr.dmi
  sound/items/ticket_printer.ogg
Labels: size/M

#7208 adds a clicker toy
  citadel.dme
  code/datums/soundbytes/defs/clicker.dm
  code/game/content/factions/corporations/nanotrasen/nanotrasen-supply/recreation.dm
  code/game/objects/items/theatrical/bike_horn.dm
  code/modules/loadout/loadout_general.dm
  icons/items/noisemaker.dmi
  sound/soundbytes/effects/clicker.ogg
Labels: size/M
