Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2025-04, with the labels that each got.

#7029 reworks chaplain/psych alt titles
  code/modules/jobs/job_types/station/civillian/chaplain.dm
  code/modules/jobs/job_types/station/medical/psychiatrist.dm
Labels: Stale, size/S

#7064 Update jukebox.json
  config_static/jukebox.json
Labels: size/L

#7031 Minor atlas security improvements
  code/game/objects/structures/crates_lockers/closets/secure/security.dm
  maps/rift/levels/rift-05-surface2.dmm
Labels: size/L

#7056 Lythios Colonist Hotfixes [Ready To Merge]
  code/datums/outfits/ghostrole.dm
  code/datums/recipe/crafting_recipes/recipes_misc.dm
  code/datums/recipe/crafting_recipes/recipes_special.dm
  code/game/objects/random/mapping.dm
  code/modules/food/food/snacks.dm
  code/modules/ghostroles/roles/lythios_colonist.dm
  code/modules/reagents/items/spray.dm
  code/modules/reagents/reagent_containers/hypospray.dm
  icons/obj/food.dmi
  icons/obj/medical/syringe.dmi
  icons/obj/structures.dmi
  icons/obj/weapons.dmi
  maps/rift/levels/rift-03-underground1.dmm
Labels: size/M

#7062 Allows holospheres to be used with the hardsuit IIS Module
  code/modules/hardsuits/modules/computer.dm
  code/modules/mob/holder.dm
  code/modules/species/holosphere/actions.dm
Labels: size/S

#7034 shapeshifter copy and reset verb
  code/modules/mob/living/carbon/human/human_defines.dm
  code/modules/species/protean/protean.dm
  code/modules/species/protean/protean_blob.dm
  code/modules/species/protean/protean_powers.dm
  code/modules/species/species_shapeshift.dm
  code/modules/species/station/xenochimera.dm
Labels: size/L

#7066 Pet Treats Custom Food
  code/modules/food/machinery/appliance/_cooker_output.dm
  code/modules/food/machinery/appliance/oven.dm
  icons/obj/food_custom.dmi
Labels: size/S

#7068 Fixes Fryers not working at all
  code/modules/food/machinery/appliance/fryer.dm
Labels: size/XS

#7061 random backend updates
  citadel.dme
  code/__DEFINES/_core.dm
  code/__DEFINES/_lists.dm
  code/__DEFINES/admin_verb.dm
  code/__DEFINES/html_assistant.dm
  code/__DEFINES/stack_trace.dm
  code/__DEFINES/stat_tracking.dm
  code/__DEFINES/vv.dm
  code/__HELPERS/do_after.dm
  code/__HELPERS/game.dm
  code/__HELPERS/icons.dm
  code/__HELPERS/mobs.dm
  code/__HELPERS/stack_trace.dm
  code/__HELPERS/stat_tracking.dm
  code/__HELPERS/unsorted.dm
  code/_globals/lists/misc.dm
  code/datums/browser/_browser.dm
  code/datums/browser/_onclose.dm
  code/datums/browser/alert.dm
  code/datums/browser/listpicker.dm
  code/datums/browser/preflikepicker.dm
  code/datums/callback.dm
  code/datums/components/_component.dm
  code/datums/progressbar.dm
  code/datums/weakref.dm
  code/datums/world_topic.dm
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/debug.dm
  code/modules/artwork/structures/sculpting_block.dm
  code/modules/error_handler/error_handler.dm
  code/modules/error_handler/error_viewer.dm
  code/modules/mob/mob_defines.dm
  code/modules/stockmarket/computer.dm
  code/modules/tgs_impl/tgs_event_handler.dm
  html/browser/common.css
Labels: size/XXL

#7069 Some Atlas Fixes + Virology Morgue
  code/game/area/rift_areas.dm
  maps/rift/engines/burn.dmm
  maps/rift/engines/rust.dmm
  maps/rift/engines/sme.dmm
  maps/rift/levels/rift-02-underground2.dmm
  maps/rift/levels/rift-04-surface1.dmm
  maps/rift/levels/rift-06-surface3.dmm
  maps/rift/levels/rift-10-west_plains.dmm
Labels: size/L

#7070 Science Voidsuit (Hazard Bypass Suit)
  citadel.dme
  code/datums/armor/station/science.dm
  code/modules/clothing/spacesuits/void/station/science.dm
  icons/mob/clothing/head.dmi
  icons/mob/clothing/suits.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/spacesuits.dmi
Labels: size/M

#7072 half the slowdown from holospheres getting hungry
  code/modules/mob/living/carbon/human/movement.dm
  code/modules/species/holosphere/holosphere.dm
  code/modules/species/species.dm
Labels: size/XS

#7067 Allows leash laws to be enforced
  citadel.dme
  code/game/machinery/vending/loadout.dm
  code/game/objects/items/leash.dm
  code/modules/loadout/loadout_general.dm
  icons/obj/leash.dmi
Labels: size/L

#7073 Music Addition
  config_static/README.md.txt
  config_static/jukebox.json
Labels: size/L

#7078 fix do-after bar
  code/__HELPERS/do_after.dm
Labels: size/XS

#7079 do after tweak
  code/__HELPERS/do_after.dm
  code/datums/progressbar.dm
  code/modules/atmospherics/machinery/components/component.dm
  code/modules/tools/_tool_system.dm
Labels: size/S

#7080 Hazard Bypass Suit Crates
  code/game/content/factions/corporations/nanotrasen/nanotrasen-supply/voidsuits.dm
  code/modules/clothing/spacesuits/void/station/science.dm
Labels: size/S

#7076 Nobody likes people with long names >:(
  code/__DEFINES/misc.dm
Labels: size/XS

#7083 Fixes darksight
  code/game/rendering/plane_masters/plane_render.dm
Labels: size/XS

#7077 makes drones not die inside cryo
  code/modules/mob/living/silicon/robot/drone/drone.dm
Labels: size/XS

#7082 copy holosphere factions over to holosphere shell
  code/modules/species/holosphere/holosphere.dm
Labels: size/XS

#7084 Two fixes for hardsuits IIS
  code/game/click/rig.dm
  code/modules/hardsuits/_rig.dm
Labels: size/XS

#7086 colorgate fix
  code/game/machinery/gear_painter.dm
Labels: size/XS

#7081 Don't disable chimera eyeglow if they use thermal sight
  code/modules/species/station/xenochimera.dm
Labels: size/S

#7085 Fixes the pitch black darkness of darksight being offset
  code/game/rendering/plane_masters/plane_render.dm
Labels: size/XS

#7095 Fast lazy fix for drawing or erasing blood
  code/modules/reagents/chemistry/reagents/blood/blood_holder.dm
Labels: size/XS

#7089 Offstation Fixes (Gaia + Casino)
  maps/sectors/delerict_casino/levels/delerict_casino.dmm
  maps/sectors/gaia_192/levels/gaia_192.dmm
Labels: size/XXL

#7092 No runtime if the blood_holder is empty
  code/modules/reagents/chemistry/reagents/blood/blood_holder.dm
Labels: size/XS

#7090 Allows the lick wounds ability to target oneself
  code/modules/vore/lick_wounds.dm
Labels: size/XS

#7097 Adds gradient limb markings
  code/modules/sprite_accessories/markings/_markings.dm
  icons/mob/sprite_accessories/markings.dmi
Labels: size/S

#6989 Murphy marvelous musings on remodeling
  2025-03-15 10
  code/game/area/Space Station 13 areas.dm
  code/game/area/endeavour_areas.dm
  maps/endeavour/endeavour-overmap.dm
  maps/endeavour/endeavour-sectors.dm
  maps/endeavour/endeavour.dm
  maps/endeavour/engines/rust.dmm
  maps/endeavour/levels/Dropship.dmm
  maps/endeavour/levels/deck1.dmm
  maps/endeavour/levels/deck2.dmm
  maps/endeavour/levels/deck3.dmm
  maps/endeavour/levels/deck4.dmm
  maps/endeavour/levels/flagship.dmm
Labels: size/XXL

#7105 !!!OH SHIT!!! fix
  maps/endeavour/engines/rust.dmm
  maps/endeavour/levels/deck1.dmm
  maps/endeavour/levels/deck2.dmm
  maps/endeavour/levels/deck4.dmm
Labels: size/XXL

#7093 Allows implant augments to be used
  code/game/objects/items/melee/types/transforming/energy/ionic_rapier.dm
  code/game/objects/items/melee/types/transforming/energy/saber.dm
  code/modules/mob/inventory/inventory-hands-put.dm
  code/modules/organs/internal/augment/armmounted.dm
  code/modules/organs/internal/subtypes/augment.dm
Labels: size/M

#7094 fluff plushies
  fluff/plushies/plushies.dm
  fluff/plushies/plushies.dmi
Labels: size/S

#7100 Lets handheld translator work if owner can't hear, even if they understand the language
  code/game/objects/items/devices/translator.dm
Labels: size/XS

#7091 Less invasive chimera regenerate
  code/modules/mob/living/carbon/human/human-damage-legacy.dm
  code/modules/species/station/xenochimera.dm
Labels: size/M

#7075 it was literally, just this
  code/__DEFINES/color/color.dm
  code/modules/mapping/map_helpers/paint.dm
  maps/rift/levels/rift-02-underground2.dmm
  maps/rift/levels/rift-03-underground1.dmm
  maps/rift/levels/rift-04-surface1.dmm
  maps/rift/levels/rift-05-surface2.dmm
  maps/rift/levels/rift-06-surface3.dmm
Labels: size/L

#7096 Jukebox hack require title edits/additions
  config_static/jukebox.json
Labels: size/M

#7104 Small gun fixes
  code/modules/projectiles/guns/gun/launcher.dm
  code/modules/projectiles/guns/gun/launcher/crossbow.dm
  code/modules/projectiles/guns/gun/projectile/ballistic.dm
  code/modules/projectiles/guns/gun/projectile/ballistic/shotgun.dm
Labels: size/S

#7099 Fix cursor icon bug in datum/ability_handler/proc/process_ability()
  code/datums/ability_handler.dm
Labels: size/XS

#7109 add dump_harddel_info to progbar
  code/controllers/subsystem/garbage.dm
  code/datums/progressbar.dm
Labels: size/S

#7110 update failsafe
  citadel.dme
  code/controllers/failsafe.dm
  code/controllers/master.dm
  code/datums/helper_datums/stack_end_detector.dm
Labels: size/L

#7111 phoronoid changes
  citadel.dme
  code/__DEFINES/languages/ids.dm
  code/__DEFINES/languages/legacy.dm
  code/datums/armor/species/phoronoid.dm
  code/game/content/factions/corporations/nanotrasen/nanotrasen-supply/miscellaneous.dm
  code/modules/atmospherics/machinery/analyzer_hooks.dm
  code/modules/clothing/spacesuits/plasman.dm
  code/modules/clothing/spacesuits/void/void.dm
  code/modules/clothing/spacesuits/void/xeno/plasman.dm
  code/modules/language/languages/species/phoronoid.dm
  code/modules/loadout/loadout_xeno.dm
  code/modules/species/station/phoronoids.dm
  icons/obj/plasmeme/hats.dmi
  maps/sectors/admin_planets_192/croatoan.dmm
  maps/sectors/sky_planet/levels/sky_planet_upper_sky_west.dmm
  tgui/packages/tgui-panel/styles/goon/chat-dark.scss
  tgui/packages/tgui-panel/styles/goon/chat-light.scss
Labels: size/XL

#7106 Endeavour Engines FULL PR
  citadel.dme
  code/game/turfs/simulated/flooring/flooring_decals.dm
  code/modules/power/engines/rust/fusion_reactions.dm
  code/modules/reagents/machinery/reagent_dispenser/hydrogen.dm
  icons/turf/flooring/decals.dmi
  maps/endeavour/engines.dm
  maps/endeavour/engines/rust.dmm
  maps/endeavour/engines/sme.dmm
  maps/endeavour/levels/deck1.dmm
  maps/endeavour/levels/deck2.dmm
  maps/endeavour/levels/deck3.dmm
  maps/endeavour/levels/deck4.dmm
Labels: size/XXL

#7114 change micro mech size requirement to <= 50% instead of <50%
  code/modules/vehicles/sealed/mecha/subtypes/micro.dm
Labels: size/XS

#7117 make records scrollable again
  tgui/packages/tgui/interfaces/GeneralRecords.js
  tgui/packages/tgui/interfaces/MedicalRecords.js
Labels: size/XS

#7118 protean infinite loop
  code/modules/species/protean/protean.dm
Labels: size/XS

#7116 wield update
  code/datums/components/items/wielding.dm
  code/game/content/factions/corporations/nanotrasen/guns/nt_protolaser.dm
  code/game/objects/items/offhand.dm
  code/modules/keybindings/keybind/item.dm
  code/modules/keybindings/keybind/mob.dm
  code/modules/mob/mob-keybind-triggers.dm
Labels: size/L

#7121 some bugfixes
  citadel.dme
  code/__DEFINES/_nameof.dm
  code/__DEFINES/access.dm
  code/__DEFINES/inventory/slots.dm
  code/__DEFINES/movespeed_modification.dm
  code/__DEFINES/projectiles/ammo_magazine.dm
  code/controllers/configuration/config_entry.dm
  code/datums/status_effects/grouped/staggered.dm
  code/game/content/factions/corporations/nanotrasen/guns/nt_expedition-heavy_sidearm.dm
  code/game/content/factions/corporations/nanotrasen/guns/nt_expedition-light_sidearm.dm
  code/game/content/factions/corporations/nanotrasen/guns/nt_protolaser.dm
  code/game/content/factions/corporations/nanotrasen/guns/nt_protomag.dm
  code/game/objects/items/weapons/handcuffs.dm
  code/game/rendering/actor_huds/huds/inventory-screen_object.dm
  code/game/rendering/actor_huds/huds/inventory.dm
  code/game/turfs/turf.dm
  code/modules/integrated_electronics/core/assemblies.dm
  code/modules/integrated_electronics/core/tools.dm
  code/modules/integrated_electronics/tools/analyzer.dm
  code/modules/integrated_electronics/tools/debugger.dm
  code/modules/integrated_electronics/tools/wirer.dm
  code/modules/jobs/job_types/station/science/research_director.dm
  code/modules/jobs/job_types/station/science/senior_researcher.dm
  code/modules/mob/living/living-inventory.dm
  code/modules/movespeed/movespeed_modifier.dm
  code/modules/paperwork/paper_bin.dm
  code/modules/reagents/chemistry/chemical_reaction.dm
  code/modules/reagents/chemistry/reagent_holder-application.dm
  code/modules/reagents/chemistry/reagent_holder-helpers.dm
  code/modules/reagents/chemistry/reagent_holder-legacy.dm
  code/modules/reagents/chemistry/reagent_holder-reactions.dm
  code/modules/reagents/chemistry/reagent_holder.dm
  code/modules/reagents/chemistry/reagents/blood/blood_holder.dm
  icons/items/handcuffs.dmi
  icons/mob/items/lefthand.dmi
  icons/mob/items/righthand.dmi
  icons/mob/mob.dmi
  icons/obj/items.dmi
  icons/obj/mining.dmi
Labels: size/XL

#7127 minor changes from melee refactor branch
  citadel.dme
  code/__DEFINES/dcs/signals/signals_atom/signals_atom-throwing.dm
  code/__DEFINES/dcs/signals/signals_atom/signals_movable-update_icon.dm
  code/__DEFINES/dcs/signals/signals_item/signals_item-interaction.dm
  code/__DEFINES/dcs/signals/signals_mob/signals_mob-inventory.dm
  code/__DEFINES/dcs/signals/signals_mob/signals_mob_defense.dm
  code/__DEFINES/materials/misc.dm
  code/__HELPERS/animations/attack.dm
  code/__HELPERS/text/format.dm
  code/datums/components/_component.dm
  code/datums/components/items/wielding.dm
  code/datums/event_args/_event_args.dm
  code/datums/event_args/actor.dm
  code/datums/event_args/examine.dm
  code/datums/soundbytes/effects/combat.dm
  code/datums/status_effects/stacking.dm
Labels: size/M

#7125 move atom radiation code to its own file
  citadel.dme
  code/game/atoms/_atom.dm
  code/game/atoms/atom-radiation.dm
Labels: size/M

#7124 rename soundbyte/grouped/sparks to soundbyte/sparks
  code/datums/soundbytes/effects/sparks.dm
  code/game/gamemodes/technomancer/spells/audible_deception.dm
  code/game/gamemodes/technomancer/spells/mark_recall.dm
  code/game/machinery/camera/camera.dm
  code/game/machinery/door_control.dm
  code/game/machinery/doors/windowdoor.dm
  code/game/machinery/suit_storage/suit_storage_unit.dm
  code/game/machinery/telecomms/logbrowser.dm
  code/game/machinery/telecomms/telemonitor.dm
  code/game/machinery/telecomms/traffic_control.dm
  code/game/objects/effects/effect_system.dm
  code/game/objects/effects/map_effects/beam_point.dm
  code/game/objects/items/devices/flashlight.dm
  code/game/objects/items/devices/lightreplacer.dm
  code/game/objects/items/melee/types/misc.dm
  code/game/objects/items/storage/lockbox.dm
  code/game/objects/items/storage/secure.dm
  code/game/objects/items/tools/weldingtool.dm
  code/game/objects/items/weapons/stunbaton.dm
  code/game/objects/structures/crates_lockers/__closet.dm
  code/game/objects/structures/crates_lockers/closets/secure/personal.dm
  code/game/objects/structures/crates_lockers/crates.dm
  code/game/objects/structures/window.dm
  code/game/turfs/simulated/wall/wall_attacks.dm
  code/modules/clothing/suits/armor.dm
  code/modules/economy/items/retail_scanner.dm
  code/modules/economy/machines/cash_register.dm
  code/modules/hardsuits/modules/computer.dm
  code/modules/hardsuits/modules/ninja.dm
  code/modules/holodeck/HolodeckControl.dm
  code/modules/mob/living/bot/floorbot.dm
  code/modules/mob/living/bot/mulebot.dm
  code/modules/mob/living/living-defense.dm
  code/modules/mob/living/simple_mob/subtypes/animal/sif/frostfly.dm
  code/modules/mob/living/simple_mob/subtypes/lavaland/stormdrifter.dm
  code/modules/projectiles/guns/gun/projectile/energy/special.dm
  code/modules/research/machinery/rdconsole.dm
  code/modules/research/machinery/server.dm
  code/modules/vore/fluffstuff/custom_items.dm
Labels: size/M

#7122 toggle_browser_inspect()
  code/modules/admin/admin_verbs.dm
  code/modules/admin/verbs/debug.dm
  code/modules/client/client_procs.dm
Labels: size/M

#7128 Fixes combat mech melee
  code/modules/vehicles/sealed/mecha/mecha.dm
Labels: size/XS
