Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2025-05, with the labels that each got.

#7129 swaps sofa corners north and east directions
  icons/obj/sofas.dmi
  maps/endeavour/levels/deck2.dmm
  maps/endeavour/levels/deck3.dmm
  maps/euthenia/levels/deck2.dmm
  maps/euthenia/levels/deck3.dmm
  maps/euthenia/levels/deck4.dmm
  maps/rift/levels/rift-03-underground1.dmm
  maps/rift/levels/rift-05-surface2.dmm
  maps/sectors/delerict_casino/levels/delerict_casino.dmm
  maps/sectors/gaia_192/levels/gaia_192.dmm
  maps/sectors/miaphus/levels/miaphus_beach.dmm
  maps/sectors/nebula_tradeport/levels/nebula_tradeport.dmm
  maps/sectors/sky_planet/levels/sky_planet_upper_sky_west.dmm
  maps/submaps/sky_planet_rigs/home.dmm
  maps/templates/admin/killhouse2.dmm
  maps/templates/admin/shipcave.dmm
  maps/templates/shuttles/overmaps/generic/itglight.dmm
  maps/tether/levels/station2.dmm
Labels: size/M

#7131 atomize melee pr a bit more
  citadel.dme
  code/__DEFINES/combat/body_zones.dm
  code/__DEFINES/dcs/signals/README.md
  code/game/objects/items/weapons/paiwire.dm
  code/game/objects/structures/fireaxe.dm
  code/game/objects/structures/guillotine.dm
  code/game/objects/structures/morgue.dm
  code/game/objects/structures/tables/interactions.dm
  code/game/turfs/simulated/floor/floor_attackby.dm
  code/game/turfs/simulated/wall/wall-construction.dm
  code/game/turfs/simulated/wall/wall-damage.dm
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/mob/living/simple_mob/subtypes/lavaland/goliath.dm
  code/modules/mob/living/simple_mob/subtypes/occult/constructs/juggernaut.dm
Labels: size/M

#7130 Turrets Tend Toward Turrety Things
  maps/endeavour/endeavour-overmap.dm
  maps/endeavour/endeavour-sectors.dm
  maps/endeavour/levels/deck1.dmm
  maps/endeavour/levels/deck2.dmm
  maps/endeavour/levels/deck3.dmm
  maps/endeavour/levels/deck4.dmm
Labels: size/XXL

#7139 adds varname assertion to firemode sets
  code/modules/projectiles/guns/firemode.dm
Labels: size/XS

#7119 Remove Advanced Who, Merge it into Who.
  citadel.dme
  code/game/verbs/advanced_who.dm
  code/game/verbs/who.dm
Labels: size/L

#7135 Fixes ethylredoxrazine; makes ethanol scannable
  code/modules/reagents/chemistry/reagents/Chemistry-Reagents-Medicine.dm
  code/modules/reagents/chemistry/reagents/core/ethanol.dm
Labels: size/XS

#7115 Order of Corporate Medical Merit
  code/modules/clothing/under/accessories/medals.dm
  code/modules/loadout/loadout_event_rewards.dm
  icons/mob/clothing/ties.dmi
  icons/obj/clothing/ties.dmi
Labels: size/S

#7145 Fix set_body_cover_flags()
  code/game/objects/items.dm
Labels: size/XS

#7143 oh god oh fuck not another killroom incident
  maps/endeavour/levels/deck1.dmm
  maps/endeavour/levels/deck2.dmm
  maps/endeavour/levels/deck3.dmm
  maps/endeavour/levels/deck4.dmm
Labels: size/XL

#7120 Riding touchup (offset fixed)
  code/__DEFINES/mobs/rendering.dm
  code/datums/components/riding/mob/human.dm
  code/datums/components/riding/mob/robot.dm
  code/datums/components/riding/riding_handler.dm
  code/game/objects/items/storage/backpack.dm
  code/modules/mob/inventory/inventory_slot.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/riding.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/simple_mob/subtypes/lavaland/gutshank.dm
  code/modules/mob/living/simple_mob/subtypes/lavaland/stormdrifter.dm
  code/modules/mob/living/simple_mob/subtypes/vore/horse.dm
  code/modules/vehicles/ridden/quad.dm
  code/modules/vehicles/ridden/three_wheel_carts.dm
  code/modules/vehicles_legacy/Securitrain_vr.dm
  code/modules/vehicles_legacy/cargo_train.dm
  code/modules/vehicles_legacy/quad.dm
Labels: size/L

#7136 Add sleeveless qipao dress
  code/game/machinery/vending/loadout.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/loadout/loadout_uniform.dm
  icons/clothing/uniform/misc/sleeveless_qipao.dmi
Labels: size/S

#7150 fix lowwall colors
  code/modules/mapping/map_helpers/paint.dm
  code/modules/mapping/map_helpers/paint_stripe.dm
  code/modules/mapping/spawner/window.dm
Labels: size/L

#7156 Adds a user agent to byond download request
  tools/ci/download_byond.sh
Labels: size/XS

#7151 config fix
  code/controllers/toml_config/toml_config_entry.dm
Labels: size/S

#7155 species name check instead of UID check
  code/modules/preferences/preference_setup/helpers/species_pick.dm
Labels: size/XS

#7154 gives holospheres the reset to slot and set size verbs
  code/modules/species/holosphere/holosphere.dm
  code/modules/species/species_shapeshift.dm
Labels: size/S

#7158 Renamed Atlas substations/breakers to be consistent
  maps/rift/levels/rift-02-underground2.dmm
  maps/rift/levels/rift-03-underground1.dmm
  maps/rift/levels/rift-04-surface1.dmm
  maps/rift/levels/rift-05-surface2.dmm
  maps/rift/levels/rift-06-surface3.dmm
  maps/rift/levels/rift-09-west_caves.dmm
  maps/rift/levels/rift-10-west_plains.dmm
Labels: size/M

#7159 gives protean blobs unlimited power (1 singular hand slot)
  code/__DEFINES/is_helpers.dm
  code/__DEFINES/screen.dm
  code/datums/status_effects/basic/taser_stun.dm
  code/game/machinery/_machinery.dm
  code/game/machinery/computer/misc/bioscan.dm
  code/game/machinery/nuclear_bomb.dm
  code/game/objects/items/scanners/health.dm
  code/game/objects/items/scanners/spectrometer.dm
  code/game/objects/items/stacks/medical.dm
  code/game/rendering/actor_huds/huds/inventory-screen_object.dm
  code/modules/integrated_electronics/subtypes/manipulation.dm
  code/modules/mining/mine_turfs.dm
  code/modules/mob/living/living_defines.dm
  code/modules/mob/living/simple_mob/simple_hud.dm
  code/modules/mob/living/simple_mob/simple_mob.dm
  code/modules/mob/observer/dead/orbit.dm
  code/modules/projectiles/guns/gun.dm
  code/modules/projectiles/projectile/projectile.dm
  code/modules/species/protean/protean_blob.dm
  icons/mob/screen1_robot_protoblob.dmi
Labels: size/L

#7166 melee refactor atomization - armor rebalancing
  code/datums/armor/antagonist/agent.dm
  code/datums/armor/antagonist/alien.dm
  code/datums/armor/antagonist/changeling.dm
  code/datums/armor/antagonist/cult.dm
  code/datums/armor/antagonist/technomancer.dm
  code/datums/armor/antagonist/wizard.dm
  code/datums/armor/clothing/armor.dm
  code/datums/armor/clothing/gloves.dm
  code/datums/armor/clothing/head.dm
  code/datums/armor/clothing/shoes.dm
  code/datums/armor/clothing/suit.dm
  code/datums/armor/clothing/uniform.dm
  code/datums/armor/core.dm
  code/datums/armor/military.dm
  code/datums/armor/misc.dm
  code/datums/armor/objects/doors.dm
  code/datums/armor/objects/standard.dm
  code/datums/armor/objects/windows.dm
  code/datums/armor/outsider/autolok.dm
  code/datums/armor/outsider/merc.dm
  code/datums/armor/outsider/oricon.dm
  code/datums/armor/outsider/pirate.dm
  code/datums/armor/outsider/vintage.dm
  code/datums/armor/species/phoronoid.dm
  code/datums/armor/species/skrell.dm
  code/datums/armor/species/teshari.dm
  code/datums/armor/species/vox.dm
  code/datums/armor/species/zaddat.dm
  code/datums/armor/station/armor.dm
  code/datums/armor/station/cargo.dm
  code/datums/armor/station/centcom.dm
  code/datums/armor/station/civilian.dm
  code/datums/armor/station/engineering.dm
  code/datums/armor/station/exploration.dm
  code/datums/armor/station/medical.dm
  code/datums/armor/station/science.dm
  code/datums/armor/station/security.dm
  code/datums/armor/unsorted.dm
Labels: size/L

#7164 Sky Planet Fix
  maps/sectors/sky_planet/levels/sky_planet_ground_west.dmm
  maps/sectors/sky_planet/levels/sky_planet_sky_west.dmm
  maps/sectors/sky_planet/levels/sky_planet_upper_sky_west.dmm
  maps/submaps/sky_planet_rigs/clown.dmm
Labels: size/XXL

#7113 Bundle of fixes
  code/datums/components/riding/mob/robot.dm
  code/game/objects/items/scanners/plant.dm
  code/game/objects/items/storage/misc_legacy/fancy.dm
  code/modules/mob/holder.dm
  code/modules/mob/living/carbon/human/riding.dm
  code/modules/mob/living/resist.dm
  code/modules/mob/living/silicon/robot/robot_items.dm
  code/modules/organs/internal/augment/armmounted.dm
  code/modules/organs/internal/augment/bio.dm
  code/modules/organs/internal/subtypes/augment.dm
  code/modules/vore/eating/belly_obj_vr.dm
Labels: size/M

#7134 Haunters in the Dark (corners of the galaxy) - PMD Uniforms Extended
  code/modules/clothing/glasses/hud.dm
  code/modules/clothing/gloves/miscellaneous.dm
  code/modules/clothing/head/misc.dm
  code/modules/clothing/head/soft_caps.dm
  code/modules/clothing/shoes/boots.dm
  code/modules/clothing/suits/labcoat.dm
  code/modules/clothing/under/accessories/accessory.dm
  code/modules/clothing/under/accessories/armor.dm
  code/modules/clothing/under/accessories/badges.dm
  code/modules/clothing/under/miscellaneous.dm
  icons/clothing/suit/coats/labcoats.dmi
  icons/mob/clothing/eyes.dmi
  icons/mob/clothing/hands.dmi
  icons/mob/clothing/head.dmi
  icons/mob/clothing/modular_armor.dmi
  icons/mob/clothing/ties.dmi
  icons/mob/clothing/uniform.dmi
  icons/obj/clothing/glasses.dmi
  icons/obj/clothing/gloves.dmi
  icons/obj/clothing/hats.dmi
  icons/obj/clothing/modular_armor.dmi
  icons/obj/clothing/ties.dmi
  icons/obj/clothing/uniforms.dmi
Labels: size/M

#7140 Dart Door Fix
  maps/rift/levels/rift-06-surface3.dmm
Labels: size/S

#7174 fixes circuit printers
  code/modules/integrated_electronics/core/printer.dm
  tgui/packages/tgui/interfaces/ICPrinter.js
Labels: size/XS

#7176 adds engine repair posing
  code/modules/mob/living/carbon/human/emote.dm
  code/modules/surgery/implant.dm
  code/modules/surgery/organs_internal.dm
Labels: size/S

#7183 Fix Endeavour map errors
  maps/endeavour/levels/deck1.dmm
  maps/endeavour/levels/deck2.dmm
  maps/endeavour/levels/deck3.dmm
  maps/endeavour/levels/deck4.dmm
  maps/endeavour/levels/flagship.dmm
Labels: size/M

#7185 Fix Rift map error
  maps/rift/levels/rift-06-surface3.dmm
Labels: size/M

#7180 fixes holospheres getting their camera stuck when untransforming while held
  code/datums/components/custom_transform.dm
Labels: size/XS

#7181 warming mask loadout
  code/modules/loadout/loadout_mask.dm
Labels: size/XS

#7178 Drone matrix upgrades touchup
  code/modules/mob/living/silicon/robot/drone/matrix_hive.dm
Labels: size/S

#7186 Fix offmap map errors, change WARNING() to CRASH() for remaining mapping issues.
  code/game/objects/structures/catwalk.dm
  code/modules/multiz/structures/stairs.dm
  code/modules/power/smes/smes.dm
  maps/sectors/gaia_192/levels/gaia_192.dmm
  maps/sectors/sky_planet/levels/sky_planet_ground_west.dmm
  maps/sectors/sky_planet/levels/sky_planet_sky_west.dmm
  maps/tether/levels/station2.dmm
  maps/tether/levels/surface1.dmm
  maps/tether/levels/surface2.dmm
  maps/tether/levels/surface3.dmm
  maps/triumph/levels/deck1.dmm
  maps/triumph/levels/deck2.dmm
  maps/triumph/levels/deck3.dmm
  maps/triumph/levels/deck4.dmm
  maps/triumph/levels/flagship.dmm
Labels: size/XXL

#7153 NEV Blackjack & Hookers
  maps/endeavour/levels/deck1.dmm
  maps/endeavour/levels/deck2.dmm
  maps/endeavour/levels/deck3.dmm
  maps/endeavour/levels/deck4.dmm
Labels: size/XXL

#7189 Fixes Rift
  maps/rift/levels/rift-06-surface3.dmm
Labels: FUCK, Priority 0: CRITICAL, size/M

#7182 refactors whitelist to toml config
  citadel.dme
  code/__DEFINES/controllers/_repository.dm
  code/__DEFINES/species/species.dm
  code/__DEFINES/species/species_flags.dm
  code/__HELPERS/lists/merge.dm
  code/controllers/configuration/configuration.dm
  code/controllers/configuration/whitelists.dm
  code/controllers/toml_config/toml_configuration.dm
  code/game/world.dm
  code/modules/jobs/job.dm
  code/modules/mob/living/carbon/alien/diona/progression.dm
  code/modules/mob/living/carbon/human/appearance.dm
  code/modules/mob/new_player/new_player.dm
  code/modules/preferences/preference_setup/background/language.dm
  code/modules/preferences/preference_setup/background/species.dm
  code/modules/preferences/preference_setup/helpers/language_pick.dm
  code/modules/preferences/preference_setup/helpers/species_pick.dm
  code/modules/species/species.dm
  config.default/whitelist.toml
  config/alienwhitelist.txt
  config/jobwhitelist.txt
  config/whitelist.toml
Labels: size/L
