Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2025-08, with the labels that each got.

#7249 Thorough addition/change on Endeavour
  code/game/area/station/security_areas.dm
  maps/endeavour/levels/deck1.dmm
  maps/endeavour/levels/deck2.dmm
  maps/endeavour/levels/deck3.dmm
  maps/endeavour/levels/deck4.dmm
  maps/triumph/levels/deck4.dmm
Labels: size/XXL

#7265 Protean "drop prey" pref fixed not to do the exact opposite of the pref
  code/modules/species/protean/protean_blob.dm
Labels: size/XS

#7266 Replaces loop-switch antipattern with something which is easier to read
  code/modules/mob/living/carbon/human/human.dm
Labels: size/S

#7267 Fixes various door assemblies to be constructible
  code/game/objects/structures/door_assembly.dm
Labels: size/S

#7262 Adds Field Medic Voidsuit
  code/game/machinery/suit_storage/suit_cycler.dm
  code/game/machinery/suit_storage/suit_storage_prepared.dm
  code/modules/clothing/spacesuits/void/station/exploration.dm
  icons/mob/clothing/head.dmi
  icons/mob/clothing/suits.dmi
  icons/obj/clothing/spacesuits.dmi
Labels: size/S

#7272 fix being unable to select dnin-nepid (moths) as a species
  code/modules/species/station/standard/moth.dm
Labels: size/XS

#7259 Well we love Strelka's Fixes
  maps/sectors/nebula_tradeport/levels/nebula_tradeport.dmm
  maps/strelka/levels/flagship.dmm
  maps/strelka/levels/strelka_deck1.dmm
  maps/strelka/levels/strelka_deck2.dmm
  maps/strelka/levels/strelka_deck3.dmm
  maps/strelka/levels/strelka_deck4.dmm
  maps/strelka/strelka-areas.dm
  maps/strelka/strelka-shuttles.dm
  maps/strelka/strelka.dm
Labels: size/XXL

#7277 remove autohiss traits
  code/modules/mob/living/carbon/human/traits/neutral.dm
Labels: size/M

#7283 Blindfold and disruptor cuffs fix
  code/game/objects/items/weapons/handcuffs.dm
  code/modules/clothing/glasses/_glasses.dm
Labels: size/S
