Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2025-10, with the labels that each got.

#7317 Add more nightshift areas to the Atlas
  code/game/area/Space Station 13 areas.dm
  code/game/area/Tether_areas.dm
  code/game/area/rift_areas.dm
  code/game/area/station/security_areas.dm
  maps/rift/levels/rift-04-surface1.dmm
Labels: Test Merge Candidate, size/L

#7310 Fixes unintuitive aim mode code
  code/game/click/click.dm
  code/game/click/item_attack.dm
  code/game/click/items.dm
  code/game/click/melee/melee_attack/unarmed.dm
  code/game/click/melee/melee_attack/weapon.dm
  code/game/objects/items-interaction.dm
  code/game/objects/obj.dm
  code/modules/projectiles/targeting/targeting_overlay.dm
Labels: Test Merge Candidate, size/M

#7307 fix weird bugs around holospheres changing species
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/living/carbon/human/human_helpers.dm
  code/modules/power/cells/power_cells.dm
  code/modules/species/holosphere/actions.dm
  code/modules/species/holosphere/appearance.dm
  code/modules/species/holosphere/health.dm
  code/modules/species/holosphere/holosphere.dm
  code/modules/species/promethean/promethean.dm
  code/modules/species/species_shapeshift.dm
Labels: Test Merge Candidate, size/L

#7316 Fix nightshift again
  code/__DEFINES/time.dm
  code/__HELPERS/time.dm
  code/_globals/time_vars.dm
  code/game/world.dm
Labels: Test Merge Candidate, size/S

#7309 Xenohybrid improvements
  code/__DEFINES/dcs/signals/signals_mob/signals_mob_combat.dm
  code/__DEFINES/traits/mob.dm
  code/game/click/items-melee_attack_chain.dm
  code/game/objects/structures/ashlander.dm
  code/modules/ai/holders/polaris/ai_holder_targeting.dm
  code/modules/mob/living/throwing.dm
  code/modules/power/lighting/lighting.dm
  code/modules/projectiles/guns/gun-firing.dm
  code/modules/projectiles/guns/gun.dm
  code/modules/rogueminer_vr/zonemaster.dm
  code/modules/species/station/xenomorph_hybrids/hybrid_abilities.dm
  code/modules/species/station/xenomorph_hybrids/hybrid_resin.dm
  code/modules/species/station/xenomorph_hybrids/xeno_hybrids.dm
  code/modules/spells/targeted/targeted.dm
  icons/screen/actions/backgrounds.dmi
Labels: Test Merge Candidate, size/M

#7321 Fixes to Deck 4 and 2, with a couple to 3, too.
  maps/endeavour/levels/deck2.dmm
  maps/endeavour/levels/deck3.dmm
  maps/endeavour/levels/deck4.dmm
Labels: size/XL

#7231 fix /obj/item/clothing/under/pmd icon direction
  icons/clothing/uniform/workwear/centcom/pmd_uniform.dmi
Labels: size/XS

#7320 adds status emoji flicking
  citadel.dme
  code/datums/components/movable/status_emoji.dm
  code/datums/status_emoji.dm
  code/game/atoms/_atom.dm
  code/modules/mob/verbs/flick_status_emoji.dm
  code/modules/mob/verbs/flick_status_emoji_quick.dm
  icons/screen/status_emojis.dmi
Labels: size/L
