Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2025-01, with the labels that each got.

#6953 Docking update and bug fixes (i got rid of the funny name)
  citadel.dme
  maps/endeavour/endeavour-papers.dm
  maps/endeavour/levels/deck1.dmm
  maps/endeavour/levels/deck2.dmm
  maps/endeavour/levels/deck3.dmm
  maps/endeavour/levels/deck4.dmm
  maps/sectors/nebula_tradeport/levels/nebula_tradeport.dmm
Labels: size/XXL

#6958 Fixes operating consoles
  code/game/machinery/computer/Operating.dm
  code/modules/surgery/bones.dm
  code/modules/surgery/encased.dm
  code/modules/surgery/external_repair.dm
  code/modules/surgery/face.dm
  code/modules/surgery/generic.dm
  code/modules/surgery/implant.dm
  code/modules/surgery/limb_reattach.dm
  code/modules/surgery/neck.dm
  code/modules/surgery/organs_internal.dm
  code/modules/surgery/other.dm
  code/modules/surgery/robotics.dm
  code/modules/surgery/slimes.dm
  code/modules/surgery/surgery.dm
  tgui/packages/tgui/interfaces/OperatingComputer.js
Labels: size/L

#6957 AAAA fixing Atlas Trading shuttle docking
  maps/rift/levels/rift-06-surface3.dmm
Labels: size/XS

#6921 Offstation Spawns for Visitors, on Nebula
  citadel.dme
  code/__DEFINES/access.dm
  code/__DEFINES/jobs/jobs.dm
  code/game/landmarks/spawnpoint/station/jobs.dm
  code/game/landmarks/spawnpoint/tradeport.dm
  code/game/machinery/vending/misc.dm
  code/game/objects/items/devices/radio/headset.dm
  code/game/objects/items/id_cards/station_ids.dm
  code/modules/jobs/job_types/station/civillian/assistant.dm
  code/modules/jobs/job_types/station/civillian/outsider.dm
  code/modules/jobs/jobs.dm
  code/modules/lore_hardcoded/faction.dm
  code/modules/maps/overmap/space/trade_station/trade_station.dm
  maps/endeavour/endeavour.dm
  maps/rift/levels/rift-10-west_plains.dmm
  maps/rift/rift.dm
  maps/sectors/nebula_tradeport/levels/nebula_tradeport.dmm
  maps/tether/tether.dm
  maps/triumph/triumph.dm
Labels: size/XXL

#6959 bugfix / tweaks
  citadel.dme
  code/__DEFINES/mapping/multiz.dm
  code/__HELPERS/lists/associations.dm
  code/controllers/repository/flooring.dm
  code/datums/components/_component.dm
  code/datums/components/mobs/mob_feign_impairment.dm
  code/datums/components/mobs/mob_self_horizontal_inversion.dm
  code/datums/components/mobs/mob_self_vertical_inversion.dm
  code/game/content/factions/corporations/nanotrasen/nanotrasen-supply/costumes.dm
  code/game/objects/items-inventory-rendering.dm
  code/game/objects/items/gifts.dm
  code/game/objects/items/melee/types/transforming/energy/saber.dm
  code/game/objects/items/stacks/rods.dm
  code/game/objects/items/stacks/stack.dm
  code/game/objects/items/stacks/tiles/tile_types.dm
  code/game/objects/random/maintenance.dm
  code/game/objects/structures/loot_piles.dm
  code/game/objects/structures/trash_pile.dm
  code/game/objects/systems/storage/storage.dm
  code/game/rendering/legacy/radial.dm
  code/game/rendering/mob.dm
  code/game/turfs/simulated/floor/floor-construction.dm
  code/game/turfs/simulated/flooring/flooring.dm
  code/game/turfs/simulated/flooring/flooring_types.dm
  code/modules/artwork/crayon_decal_meta.dm
  code/modules/artwork/items/crayon.dm
  code/modules/clothing/accessories/halo.dm
  code/modules/clothing/clothing.dm
  code/modules/clothing/under/_under.dm
  code/modules/clothing/under/gear_harness.dm
  code/modules/clothing/under/miscellaneous.dm
  code/modules/frames/frame_step.dm
  code/modules/frames/types/fire_alarm.dm
  code/modules/loadout/loadout_xeno.dm
  code/modules/materials/material_sheets.dm
  code/modules/materials/material_synth.dm
  code/modules/mining/tools/vertibore.dm
  code/modules/mob/animations.dm
  code/modules/mob/living/carbon/human/examine.dm
  code/modules/mob/living/carbon/human/human-defense.dm
  code/modules/mob/living/carbon/human/update_icons.dm
  code/modules/mob/living/living.dm
  code/modules/mob/living/say.dm
  code/modules/mob/mob-status_procs.dm
  code/modules/mob/mob.dm
  code/modules/mob/verbs/feign_impairment.dm
  code/modules/mob/verbs/vertical_invert_self.dm
  code/modules/multiz/atom-z_fall.dm
  code/modules/multiz/atom-z_move.dm
  code/modules/multiz/core.dm
  code/modules/multiz/falling.dm
  code/modules/multiz/movement.dm
  code/modules/multiz/turf-multiz_misc.dm
  code/modules/multiz/turf-z_fall.dm
  code/modules/multiz/turf-z_move.dm
  code/modules/multiz/turf.dm
  code/modules/power/cable.dm
  code/modules/preferences/preferences_toggle_procs.dm
  code/modules/vehicles/sealed/mecha/subtypes/micro/mecha_construction_paths_vr.dm
  maps/templates/archive/tradeship.dmm
Labels: size/L

#6950 moves some trivial configs around to new config
  citadel.dme
  code/__HELPERS/_logging.dm
  code/controllers/configuration_old/configuration.dm
  code/controllers/configuration_old/configuration_vr.dm
  code/controllers/toml_config/entries/backend-logging-toggles.dm
  code/controllers/toml_config/entries/backend-logging.dm
  code/controllers/toml_config/entries/backend-repository.dm
  code/controllers/toml_config/toml_configuration.dm
  code/game/machinery/computer/timeclock_vr.dm
  code/game/verbs/who.dm
  code/game/world.dm
  code/modules/admin/topic.dm
  code/modules/admin/verbs/adminpm.dm
  code/modules/admin/verbs/possess.dm
  code/modules/mob/living/carbon/brain/MMI.dm
  code/modules/mob/living/carbon/human/human.dm
  code/modules/mob/mob-login.dm
  code/modules/organs/internal/subtypes/brain.dm
  code/modules/species/species_getters.dm
  config.default/config.toml
  tools/minibot/LICENCE-bot_folder.txt
  tools/minibot/config.py
  tools/minibot/minibot.py
  tools/minibot/nudge.py
Labels: size/XL

#6961 Further endeavour fixes and tweaks
  maps/endeavour/levels/deck1.dmm
  maps/endeavour/levels/deck2.dmm
  maps/endeavour/levels/deck3.dmm
Labels: size/XL

#6970 misplaced backslash fix
  code/modules/reagents/chemistry/reactions/Drink-Recipes.dm
Labels: size/XS

#6968 Outsider Spawn Update.
  maps/sectors/nebula_tradeport/levels/nebula_tradeport.dmm
Labels: size/M

#6966 More Endeavour Bug fixes?
  maps/endeavour/levels/deck1.dmm
  maps/endeavour/levels/deck2.dmm
  maps/endeavour/levels/deck3.dmm
  maps/endeavour/levels/deck4.dmm
Labels: size/XL

#6969 adds the aquatic trait
  citadel.dme
  code/__DEFINES/traits/mob.dm
  code/__DEFINES/traits/sources.dm
  code/game/turfs/simulated/floor_types/water.dm
  code/modules/mob/_modifiers/traits.dm
  code/modules/mob/living/carbon/human/traits/positive.dm
  code/modules/species/station/station_special_abilities.dm
Labels: size/L

#6955 Fixes Intercom Convo
  code/modules/admin/admin.dm
Labels: size/XS

#6960 add passport.dmi to da repo for future use :)
  icons/obj/passports.dmi
Labels: size/XS

#6965 fixes resist (crappily but it works)
  code/datums/status_effects/basic/incapacitation.dm
  code/modules/mob/grab.dm
  code/modules/mob/living/carbon/resist.dm
  code/modules/mob/mobility.dm
  code/modules/mob/status_procs.dm
Labels: size/M

#6973 Adds a bunch of loadout items into the vendors + some fixes
  code/game/machinery/biogenerator.dm
  code/game/machinery/vending/loadout.dm
  code/modules/loadout/loadout_suit.dm
Labels: size/XL

#6974 Removed Tajaran, Unathi, and Promethean centric xenowear lock
  code/modules/loadout/loadout_xeno.dm
Labels: size/XS

#6956 New POI in space : Delerict Casino Station - Monarch Of Autumn
  citadel.dme
  code/__DEFINES/access.dm
  code/__DEFINES/mobs/iff.dm
  icons/obj/card_cit.dmi
  maps/endeavour/endeavour.dm
  maps/euthenia/euthenia.dm
  maps/rift/rift.dm
  maps/sectors/delerict_casino/delerict_casino-areas.dm
  maps/sectors/delerict_casino/delerict_casino-misc.dm
  maps/sectors/delerict_casino/delerict_casino.dm
  maps/sectors/delerict_casino/levels/delerict_casino.dmm
  maps/tether/tether.dm
  maps/triumph/triumph.dm
  sound/ambience/forest-ambience.ogg
Labels: size/XXL

#6976 Makes horror aura only active when players are present in z-level
  code/datums/components/horror_aura.dm
Labels: size/XS

#6977 Stops logging radiation emitter map effects
  code/game/objects/effects/map_effects/radiation_emitter.dm
Labels: size/XS
