Repository Citadel-Station-13/Citadel-Station-13-RP, pull requests merged in 2025-09, with the labels that each got.

#7285 fixes most of the tgui bugs with lathes
  tgui/packages/tgui/interfaces/modules/TGUILatheControl.tsx
Labels: size/M

#7274 ring expansion
  code/modules/clothing/gloves/rings/material.dm
  code/modules/loadout/loadout_gloves.dm
Labels: size/M

#7299 A couple minor fixes
  code/_globals/regexes.dm
  code/modules/mob/emote.dm
  code/modules/mob/living/carbon/human/human_organs.dm
Labels: size/S

#7298 Hazard Bypass Update
  code/modules/clothing/spacesuits/void/station/science.dm
Labels: size/XS

#7302 A couple more fixes
  code/modules/reagents/chemistry/reagents/blood/blood_holder.dm
  code/modules/reagents/machinery/coffeemaker.dm
  code/modules/vore/fluffstuff/life_crystals.dm
Labels: size/S

#7294 fixes mech control consoles lagging the server
  code/modules/vehicles/sealed/mecha/mecha_control_console.dm
  code/modules/vehicles/sealed/mecha/vehicle_tracking_beacon.dm
Labels: size/XS

#7308 Adds Ripped pants and fishnets
  code/game/machinery/vending/loadout.dm
  code/modules/clothing/under/casual/miscellaneous.dm
  code/modules/loadout/loadout_uniform.dm
  icons/clothing/uniform/casual/punk.dmi
  icons/unused/_abandoned_sprites/mob/clothing/uniform.dmi
Labels: size/S
